### ISSUE TITLE
Create TAP adapter

### ISSUE THREAD

**Issue by Raynos** [karma-runner/karma#10]
If a testing library outputs TAP it should be trivial to pipe that TAP output into your framework.

**Comment by Dignifiedquire** [comment]
Closing as this can be done in a plugin.

**Comment by kumavis** [comment]
gentle suggestion that TAP support should be in core

**Comment by joaomilho** [comment]
+1 for having TAP without any plugin

**Comment by Dignifiedquire** [comment]
@kumavis @joaomilho why should TAP be in core, when all other test adapters are plugins?
