### ISSUE TITLE
Karma cant capture Chrome on WIndows 8?

### ISSUE THREAD

**Issue by Timsen88** [karma-runner/karma#1009]
I am running karma 0.12.3

I can get Karma server to run on Windows machine where browser starts up and hangs with "server starting" message (i dont know if thats what suppose to happend on karma start), but everytime i am making a change inside of test files, karma is able to detect that change is made, but then i am getting folowing error:

DEBUG [karma]: List of files has changed, trying to execute WARN [karma]: No captured browser, open localhost:9876/

after 200000 ms i can see in console "IE or Chrome have not captured in 200000 ms, killing".

I have checked my etc/host file it is clean. I have checked that i created IE_BIN and CHROME_BIN enviroment variables but i still cant get it to work. i strugled with this problem for 3 days now, i really dont know what to do now.

I can see folowing error in browser console, but it disapears again  right after i saw it:

WebSocket connection to 'ws://localhost:9876/socket.io/1/websocket/ynDB1e0iun-Zm5IeZKAv' failed: WebSocket is closed before the connection is established.

**Comment by Dignifiedquire** [comment]
Closing for now, please reopen if this is still an issue with the latest version.
