### ISSUE TITLE
"grunt lint" fails on Windows with many "Invalid line break" errors

### ISSUE THREAD

**Issue by DanTup** [karma-runner/karma#1030]
When I run ```grunt lint``` on Windows; I get a bunch of ```Invalid line break``` errors. For example:

```
Invalid line break at lib/reporters/progress.js :
     1 |var BaseReporter = require('./base');
---------------------------------------------^
     2 |
     3 |
Invalid line break at lib/reporters/progress_color.js :
     1 |var ProgressReporter = require('./progress');
-----------------------------------------------------^
     2 |var BaseColorReporter = require('./base_color');
     3 |
Invalid line break at lib/runner.js :
     1 |var http = require('http');
-----------------------------------^
```

I've tried setting ```core.autocrlf``` to true, false and unset it (doing a clean checkout each time) with no joy. Note: I'm a bit of a Git noob, so I may be doing this wrong; but it'd be useful to figure out to make contributing easier!

**Comment by Dignifiedquire** [comment]
For questions and support please use the mailing list or Gitter. The issue tracker is for bug reports and feature discussions only.
