### ISSUE TITLE
Karma doesn't exit properly when using public api with the finish callback

### ISSUE THREAD

**Issue by pkozlowski-opensource** [karma-runner/karma#1035]
Using Karma's server public API with a done callback makes the whole node process "stuck" - there are probably some event listeners that prevent node process from exiting properly. A simple reproduce scenario:

``` javascript
var karma = require('karma').server;

karma.start({
  //transports: ['websocket', 'xhr-polling', 'jsonp-polling'],
  browsers: ['Chrome'],
  frameworks: ['jasmine'],
  files: [
    'src/**/*.js',
    'test/**/*.spec.js'
  ],
  singleRun: true
}, function(karmaExitCode) {
  console.log('Karma exited with ', karmaExitCode);
  console.log('but the process will never exit...');
});
```

Interestingly, removing the flash from the list of transports make the Karma exit after a while (~20s after test are finished on my machine).

There is a small repo with the reproduce scenario here:
https://github.com/karma-runner/gulp-karma/blob/exit_pb/exitTest.js
I will be digging into the topic but any help from someone more knowledgeable about Karma internals would be highly appreciated.

**Comment by bcherny** [comment]
@pkozlowski-opensource This happens for me once per 20-30 builds - the test suite finishes successfully, but hangs at gulp's `Finished 'unit' after 3.08 min`. How did you find the hanging setTimeouts? I'd like like to similarly instrument our code to find the culprit.

For reference, this is our gulp code:

```js
const gulp = require('gulp')
const {Server} = require('karma')

gulp.task('unit', function (done) {
  new Server({
    configFile: './karma.conf.coffee'
  }, exitCode => {
    if (exitCode == 0) {
      done()
    } else {
      process.exit(exitCode)
    }
  }).start()
})
```

**Comment by Fernker** [comment]
@bcherny Were you able to find the solution to your issue?  I'm seeing the same thing happen (20-30 builds) and I'd really like to solve it.

**Comment by jnwu** [comment]
As a workaround, I am forcing the karma server to be executed in a separate process via 'gulp-multi-process'

`
gulp.task('test', () => {
    const config = parseConfig(path.resolve('test/karma.conf.js'));
    const server = new karma.Server(config);
    server.start();
});

gulp.task('multi', (cb) => {
    return multiProcess(['test'], cb);
});

gulp.task('watch', () => {
    gulp.watch(files, ['multi']);
});
`

In addition my karma config has autoWatch off, and singleRun on. Hence, I am using gulp to watch my files and delegating all the test tasks (including report generation) to karma.

**Comment by bcherny** [comment]
@Fernker Missed your comment - we still see this issue every 20-30 builds. When it happens, we restart the build, and it usually passes. I've noticed that it tends to happen more often when we are running multiple builds in parallel on a single environment.

**Comment by yushadowx** [comment]
The problem remains for Karma 1.4.0 on Windows. Is there workaround for that?

**Comment by npetruzzelli** [comment]
- Windows 7 Pro
- node v6.9.4
- npm 3.10.10

I've been experiencing the same issues and have noticed the following:

-   Affected:
    -   Chrome
    -   Firefox
-   Not Affected
    -   PhantomJS
    -   Internet Explorer

I have a couple work arounds, granted niether is perfect:

```javascript
// gulpefile.js
const path         = require('path');
const gulp         = require('gulp');
const karma        = require('karma');
const minimist     = require('minimist');
const ARGV         = minimist(process.argv.slice(2));

/**
 * Option 1
 * Use a stopper in the `run_complete` event listener.
 * Must have access to the port the server is running on.
 */
gulp.task('karma_1', function taskKarma(taskDone){
  /**
   * if `--single` was a command line option, for example:
   * `gulp karma_1 --single`
   */
  var someConditionIsTrue = (ARGV.single === true);
  var karmaConfig = {
    autoWatch: true,
    configFile: path.resolve('./karma.conf.js'),
    port:9876, // Stopper will need to know the port.
    singleRun: false
  };
  if(someConditionIsTrue){
    karmaConfig.singleRun = true;
    karmaConfig.autoWatch = false;
  }

  var karmaServer = new karma.Server(
    karmaConfig,
    function handleKarmaServerExit(processExitCode){
      if(processExitCode === 0 || processExitCode === null || typeof processExitCode === 'undefined'){
        taskDone();
      } else {
        var err = new Error('ERROR: Karma Server exited with code "' + processExitCode + '"');
        taskDone(err);
      }
    }
  );

  if(karmaConfig.singleRun){
    //Stop the server after the first run.
    karmaServer.on('run_complete', function(){
      karma.stopper.stop({
        port: karmaConfig.port
      });
    });
  }

  karmaServer.start();
});

/**
 * Option 2
 * Use `process.exit` in the Karma onExit handler.
 */
gulp.task('karma_2', function taskKarma(taskDone){
  /**
   * if `--single` was a command line option, for example:
   * `gulp karma_2 --single`
   */
  var someConditionIsTrue = (ARGV.single === true);
  var karmaConfig = {
    autoWatch: true,
    configFile: path.resolve('./karma.conf.js'),
    singleRun: false
  };
  if(someConditionIsTrue){
    karmaConfig.singleRun = true;
    karmaConfig.autoWatch = false;
  }

  var karmaServer = new karma.Server(
    karmaConfig,
    function handleKarmaServerExit(processExitCode){
      if(processExitCode === 0 || processExitCode === null || typeof processExitCode === 'undefined'){
        taskDone();
      } else {
        var err = new Error('ERROR: Karma Server exited with code "' + processExitCode + '"');
        taskDone(err);
      }
      process.exit(processExitCode); //Exit the node process
    }
  );

  karmaServer.start();
});
```

I hope this helps!

**Comment by npetruzzelli** [comment]
I should add clarification. The server exit handler is being called for me, but the process never exits if the affected browsers are launched. In hindsight, this may be different from the issue described above.

**Comment by Ivaylo-Lafchiev** [comment]
I've run into the same issue, tested on karma@1.7.1 and karma@latest in my project's gulp chain. Seems there are socket.io handlers (detected using why-is-node-running) that aren't resolved for a good 30-40 seconds after karma has finished executing the tests. The above solutions provided by @npetruzzelli  are of no help as they terminate the node process and the following tasks are not executed. 

I was hoping #3149 would help but it seems that despite Karma exiting gracefully after the test run it seems socket.io is still holding the process hostage. I'm going to try what was suggested by @jnwu but I'm not sure this is the best solution to the problem.
