### ISSUE TITLE
move watcher to a plugin to speed up karma install

### ISSUE THREAD

**Issue by dylang** [karma-runner/karma#1050]
Karma is the slowest thing for us to install because it has to build `fs-events` and `ws` every time. I believe these modules are used by Karma's watcher functionality. 

Because we use Karma through `Grunt` we don't need Karma's own watcher functionality and would prefer a slimmer, faster install.

**Comment by Dignifiedquire** [comment]
The file watcher might be extracted but it will still be a default dependency for now, as too many are depending on it. Ref #1468
