### ISSUE TITLE
grunt task failing after temp_dir is executed

### ISSUE THREAD

**Issue by jpalumbo** [karma-runner/karma#1057]
Currently we are using karma version 0.12.14. There is a sporadic issue where the build fails after "Cleaning temp dir". 

I can not seem to find any specific details about what has failed. 

    DEBUG [launcher]: Disconnecting all browsers
    DEBUG [launcher]: Process Firefox exited with code 0
    DEBUG [temp-dir]: Cleaning temp dir C:\Users\dev\AppData\Local\Temp\karma-34754290
     Use --force to continue.
     Aborted due to warnings.
     Program returned code  : 3

This issue only seems to be present on our jenkins build machines. When I run grunt on the machine myself I can not reproduce the issue.

Does anyone have any ideas as far as steps I can take to troubleshoot this or find details on what is causing the failure?

**Comment by Dignifiedquire** [comment]
Closing for now, please report if this is still an issue with the latest version.
