### ISSUE TITLE
Microsoft VS 2010 build issue on yo scaffolding

### ISSUE THREAD

**Issue by ElliotPsyIT** [karma-runner/karma#1060]
In bootstrapping a new yeoman angular app on a Windows 7 VM, I got the following non-fatal build error. The bootstrap completed successfully and the generated app starts up fine. Also, karma setup wasn't affected, and the default unit test ran under karma without a problem.  

Issue for me is that I have VS 2013 on this VM and cannot load VS 2010 - server admin and space issues.  So, I'm wondering what effect, if any, the failures of 'bufferutil' and 'validation' might have for running karma as I build out my app?  Are there risks I should be aware of now in deciding whether to continue to use karma, which I'd very much like to do?

Any insights would be greatly appreciated.

```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.t
argets(64,5): error MSB8020: The build tools for Visual Studio 2010 (Platform T
oolset = 'v100') cannot be found. To build using the v100 build tools, please i
nstall Visual Studio 2010 build tools.  Alternatively, you may upgrade to the c
urrent Visual Studio tools by selecting the Project menu or right-click the sol
ution, and then selecting "Upgrade Solution...". [C:\WebApps\YeomanWeb\node_mod
ules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws
\build\bufferutil.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.t
argets(64,5): error MSB8020: The build tools for Visual Studio 2010 (Platform T
oolset = 'v100') cannot be found. To build using the v100 build tools, please i
nstall Visual Studio 2010 build tools.  Alternatively, you may upgrade to the c
urrent Visual Studio tools by selecting the Project menu or right-click the sol
ution, and then selecting "Upgrade Solution...". [C:\WebApps\YeomanWeb\node_mod
ules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws
\build\validation.vcxproj]
```

**Comment by Dignifiedquire** [comment]
Closing for now, please reopen if this is still an issue with the latest version.
