### ISSUE TITLE
Double slash

### ISSUE THREAD

**Issue by vance** [karma-runner/karma#1065]
Karma server does not recognize // as a single / when serving files. Tomcat, Apache, IIS etc. all pass paths with double slash as a single slash.

my/resource/has/two//slashes  returns file at  my/resource/has/two/slashes

this causes errors with some i18n solutions.

**Comment by Dignifiedquire** [comment]
Closing for now.

**Comment by evilchewits** [comment]
We have the same problem. Double slashes cased by require.js resolving some paths..
Is it possible to fix it? It's a pretty common behaviour for web-servers treat "//" as "/"
