### ISSUE TITLE
--no-colors for run command

### ISSUE THREAD

**Issue by omouse** [karma-runner/karma#1067]
I'm trying to do this:

    karma run /path/to/myconfig.js --no-colors --port 8080

And it keeps displaying ANSI colors. I'm trying to pipe the output from the `run` command into Emacs and other text editors and I really really don't want to have to add extra code that strips out the ANSI colors when the `run` command really should be accepting the `--no-colors` argument just like the `start` command does.

I've tried setting the option in my config with `color:false` but that apparently only applies to the first running instance of karma, not to any subsequent calls to the karma server.

**Comment by budde377** [comment]
@Dignifiedquire I believe that we can close this issue :)

**Comment by Dignifiedquire** [comment]
Yes :)
