### ISSUE TITLE
Allow file pattern to specify binary

### ISSUE THREAD

**Issue by tpodom** [karma-runner/karma#1070]
What do you think about allowing the files pattern to override whether or not the file should be considered binary?  The current implementation isn't configurable if using custom file extensions.

**Comment by henryptung** [comment]
:+1: My vote as well.

Also adding to the extensions list: `.pbf`, for protobufs.

I really don't like naming things `.pbf.png`...

**Comment by Dignifiedquire** [comment]
We should switch to using isbinaryfile for now.

**Comment by mramato** [comment]
I just opened #1816 to address this issue.  It's my first karma pull request, so hopefully I followed all of the rules.  If anyone is interested in trying it out, I'm happy to have feedback.
