### ISSUE TITLE
Disable sha1 cache busting for HTML Imports

### ISSUE THREAD

**Issue by morethanreal** [karma-runner/karma#1073]
Imagine a config that includes `a.html` and `b.html`:

`a.html`:

```
<link href="b.html" rel="import">
<!-- register custom element x-a -->
```

`b.html`:

```
<!-- register custom element x-b -->
```

When karma generates `context.html`, it appends all paths with ?sha1. The above config would throw an error where `x-b` is registered twice, because b.html was loaded twice, once from `context.html` and once from `a.html` since the path was different.

Since using HTML imports to resolve dependency is a very common pattern, perhaps karma should not cache bust resources loaded with HTML Imports?

**Comment by Dignifiedquire** [comment]
I don't think this is something that karma should be doing.
