### ISSUE TITLE
Socket io causes disconnects

### ISSUE THREAD

**Issue by gantaa** [karma-runner/karma#1082]
Karma relies on the latest 0.9 version of socket io.  They recently updated from 0.9.16 to 0.9.17 and it is causing Karma to disconnect.  I have created an issue with socket io, but it might be a good idea to peg the socket io version to 0.9.16 until this is resolved.

here is the socket io issue i created: https://github.com/Automattic/socket.io/issues/1558

**Comment by Dignifiedquire** [comment]
This should be fixed in 0.13 ( canary)
