### ISSUE TITLE
Question about Preprocessors and ng-html2js

### ISSUE THREAD

**Issue by ashclarke** [karma-runner/karma#1085]
In my app, I have some templates that are server-side files. These are therefore parsed by the server and the parsed html is sent as the response.

I have karma set up to use a proxy, `http://localhost:9005`, which is serving up my app.

When I run my **unit** tests with the ng-html2js preprocessor, I am now getting the *"template must have exactly one root element"* error.

I believe that it is due to the `preprocessor.js` reading in the content straight from the filesystem before sending it to the `ng-html2js` plugin, so the processed template string contains the server directive for the file, as per:

https://github.com/karma-runner/karma/blob/master/lib/preprocessor.js#L91

Assuming I am correct here, could I have some clues to adjust this so that the parsed template html would be read from my proxy? Is this something that is on the roadmap?

If possible, I don't really want to convert these into E2E tests just to load the templates - I didn't have much luck with the `ngMockE2E` module and passthrough fn.

**Comment by Dignifiedquire** [comment]
> For questions and support please use the mailing list or Gitter.
> The issue tracker is for bug reports and feature discussions only.
