### ISSUE TITLE
Not capturing any browser in windows

### ISSUE THREAD

**Issue by Wicus** [karma-runner/karma#1096]
Hi there,

I've tested node v.0.10.28, karma v.0.12.16, windows 7 x64 on three different machines. It works on one and not on the other two, it's sooo weird. I did the PATH thing, the Firewall and Antivirus disabled. Nothing works! It seems to be a bug, cause I can't sanely get this to work. Hopefully I'm just missing something, but it doesn't seem like it :(

Here is my setup and debug:

C:\Users\Wicus\Desktop\work\test>karma init

Which testing framework do you want to use ?
Press tab to list possible options. Enter to move to the next question.
> jasmine

Do you want to use Require.js ?
This will add Require.js plugin.
Press tab to list possible options. Enter to move to the next question.
> no

Do you want to capture any browsers automatically ?
Press tab to list possible options. Enter empty string to move to the next question.
> Chrome
> ChromeCanary
> Firefox
>

What is the location of your source and test files ?
You can use glob patterns, eg. "js/*.js" or "test/**/*Spec.js".
Enter empty string to move to the next question.
>

Should any of the files included by the previous patterns be excluded ?
You can use glob patterns, eg. "**/*.swp".
Enter empty string to move to the next question.
>

Do you want Karma to watch all the files and run the tests on change ?
Press tab to list possible options.
> yes

Config file generated at "C:\Users\Wicus\Desktop\work\test\karma.conf.js".

C:\Users\Wicus\Desktop\work\test>karma start
INFO [karma]: Karma v0.12.16 server started at http://localhost:9876/
INFO [launcher]: Starting browser Chrome
INFO [launcher]: Starting browser ChromeCanary
INFO [launcher]: Starting browser Firefox
Terminate batch job (Y/N)? y

C:\Users\Wicus\Desktop\work\test>karma start --log-level debug
DEBUG [config]: Loading config C:\Users\Wicus\Desktop\work\test\karma.conf.js
DEBUG [plugin]: Loading karma-* from C:\Users\Wicus\Desktop\work\test\node_modules
DEBUG [plugin]: Loading plugin C:\Users\Wicus\Desktop\work\test\node_modules/karma-chrome-launcher.
DEBUG [plugin]: Loading plugin C:\Users\Wicus\Desktop\work\test\node_modules/karma-firefox-launcher.
DEBUG [plugin]: Loading plugin C:\Users\Wicus\Desktop\work\test\node_modules/karma-jasmine.
INFO [karma]: Karma v0.12.16 server started at http://localhost:9876/
INFO [launcher]: Starting browser Chrome
DEBUG [temp-dir]: Creating temp dir at C:\Users\Wicus\AppData\Local\Temp\karma-42215420
DEBUG [launcher]: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe --user-data-dir=C:\Users\Wicus\AppData\Local\Temp\karma-42215420 --no-default-browser-check --no-f
irst-run --disable-default-apps --disable-popup-blocking --disable-translate http://localhost:9876/?id=42215420
INFO [launcher]: Starting browser ChromeCanary
DEBUG [temp-dir]: Creating temp dir at C:\Users\Wicus\AppData\Local\Temp\karma-93586856
DEBUG [launcher]: C:\Users\Wicus\AppData\Local\Google\Chrome SxS\Application\chrome.exe --user-data-dir=C:\Users\Wicus\AppData\Local\Temp\karma-93586856 --no-default-browser-ch
eck --no-first-run --disable-default-apps --disable-popup-blocking --disable-translate http://localhost:9876/?id=93586856 --js-flags="--nocrankshaft --noopt"
INFO [launcher]: Starting browser Firefox
DEBUG [temp-dir]: Creating temp dir at C:\Users\Wicus\AppData\Local\Temp\karma-26193441
DEBUG [launcher]: C:\Program Files (x86)\Mozilla Firefox\firefox.exe http://localhost:9876/?id=26193441 -profile C:\Users\Wicus\AppData\Local\Temp\karma-26193441 -no-remote
DEBUG [watcher]: Resolved files:
        C:/Users/Wicus/Desktop/work/test/node_modules/karma-jasmine/lib/jasmine.js
        C:/Users/Wicus/Desktop/work/test/node_modules/karma-jasmine/lib/adapter.js
DEBUG [web-server]: serving: C:\Users\Wicus\Desktop\work\test\node_modules\karma\static/client.html
DEBUG [web-server]: serving: C:\Users\Wicus\Desktop\work\test\node_modules\karma\static/client.html
DEBUG [web-server]: serving: C:\Users\Wicus\Desktop\work\test\node_modules\karma\static/karma.js
DEBUG [web-server]: serving: C:\Users\Wicus\Desktop\work\test\node_modules\karma\static/karma.js
DEBUG [web-server]: upgrade /socket.io/1/websocket/qHlpjVcmcUcQVep-QgxS
DEBUG [karma]: A browser has connected on socket qHlpjVcmcUcQVep-QgxS
DEBUG [web-server]: upgrade /socket.io/1/websocket/RCNjCPP9V8_eBNkdQgxT
DEBUG [karma]: A browser has connected on socket RCNjCPP9V8_eBNkdQgxT
DEBUG [web-server]: serving: C:\Users\Wicus\Desktop\work\test\node_modules\karma\static/client.html
DEBUG [web-server]: serving: C:\Users\Wicus\Desktop\work\test\node_modules\karma\static/karma.js
DEBUG [web-server]: upgrade /socket.io/1/websocket/AA3CKqujq1HLCgSHQgxU
DEBUG [karma]: A browser has connected on socket AA3CKqujq1HLCgSHQgxU
WARN [launcher]: Chrome have not captured in 60000 ms, killing.
WARN [launcher]: ChromeCanary have not captured in 60000 ms, killing.
WARN [launcher]: Firefox have not captured in 60000 ms, killing.
DEBUG [launcher]: Process Chrome exited with code 0
DEBUG [temp-dir]: Cleaning temp dir C:\Users\Wicus\AppData\Local\Temp\karma-42215420
DEBUG [launcher]: Process ChromeCanary exited with code 0
DEBUG [temp-dir]: Cleaning temp dir C:\Users\Wicus\AppData\Local\Temp\karma-93586856
DEBUG [launcher]: Process Firefox exited with code 0
DEBUG [temp-dir]: Cleaning temp dir C:\Users\Wicus\AppData\Local\Temp\karma-26193441
INFO [launcher]: Trying to start Firefox again (1/2).
DEBUG [launcher]: Restarting Firefox
DEBUG [temp-dir]: Creating temp dir at C:\Users\Wicus\AppData\Local\Temp\karma-26193441
DEBUG [launcher]: C:\Program Files (x86)\Mozilla Firefox\firefox.exe http://localhost:9876/?id=26193441 -profile C:\Users\Wicus\AppData\Local\Temp\karma-26193441 -no-remote
INFO [launcher]: Trying to start Chrome again (1/2).
DEBUG [launcher]: Restarting Chrome
DEBUG [temp-dir]: Creating temp dir at C:\Users\Wicus\AppData\Local\Temp\karma-42215420
DEBUG [launcher]: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe --user-data-dir=C:\Users\Wicus\AppData\Local\Temp\karma-42215420 --no-default-browser-check --no-f
irst-run --disable-default-apps --disable-popup-blocking --disable-translate http://localhost:9876/?id=42215420
INFO [launcher]: Trying to start ChromeCanary again (1/2).
DEBUG [launcher]: Restarting ChromeCanary
DEBUG [temp-dir]: Creating temp dir at C:\Users\Wicus\AppData\Local\Temp\karma-93586856
DEBUG [launcher]: C:\Users\Wicus\AppData\Local\Google\Chrome SxS\Application\chrome.exe --user-data-dir=C:\Users\Wicus\AppData\Local\Temp\karma-93586856 --no-default-browser-ch
eck --no-first-run --disable-default-apps --disable-popup-blocking --disable-translate http://localhost:9876/?id=93586856 --js-flags="--nocrankshaft --noopt"
DEBUG [web-server]: serving: C:\Users\Wicus\Desktop\work\test\node_modules\karma\static/client.html
DEBUG [web-server]: serving: C:\Users\Wicus\Desktop\work\test\node_modules\karma\static/karma.js
DEBUG [web-server]: upgrade /socket.io/1/websocket/sJjhdxnivefUR0t4QgxV
DEBUG [karma]: A browser has connected on socket sJjhdxnivefUR0t4QgxV
DEBUG [web-server]: serving: C:\Users\Wicus\Desktop\work\test\node_modules\karma\static/client.html
DEBUG [web-server]: serving: C:\Users\Wicus\Desktop\work\test\node_modules\karma\static/karma.js
DEBUG [web-server]: upgrade /socket.io/1/websocket/dySFb5cVjtlAMHkNQgxW
DEBUG [karma]: A browser has connected on socket dySFb5cVjtlAMHkNQgxW
DEBUG [web-server]: serving: C:\Users\Wicus\Desktop\work\test\node_modules\karma\static/client.html
DEBUG [web-server]: serving: C:\Users\Wicus\Desktop\work\test\node_modules\karma\static/karma.js
DEBUG [web-server]: upgrade /socket.io/1/websocket/qku1dZUQG7MlwEoxQgxX
DEBUG [karma]: A browser has connected on socket qku1dZUQG7MlwEoxQgxX
WARN [launcher]: Firefox have not captured in 60000 ms, killing.
WARN [launcher]: Chrome have not captured in 60000 ms, killing.
WARN [launcher]: ChromeCanary have not captured in 60000 ms, killing.
DEBUG [launcher]: Process Chrome exited with code 0
DEBUG [temp-dir]: Cleaning temp dir C:\Users\Wicus\AppData\Local\Temp\karma-42215420
DEBUG [launcher]: Process Firefox exited with code 0
DEBUG [temp-dir]: Cleaning temp dir C:\Users\Wicus\AppData\Local\Temp\karma-26193441
INFO [launcher]: Trying to start Firefox again (2/2).
DEBUG [launcher]: Restarting Firefox
DEBUG [temp-dir]: Creating temp dir at C:\Users\Wicus\AppData\Local\Temp\karma-26193441
DEBUG [launcher]: C:\Program Files (x86)\Mozilla Firefox\firefox.exe http://localhost:9876/?id=26193441 -profile C:\Users\Wicus\AppData\Local\Temp\karma-26193441 -no-remote
DEBUG [launcher]: Process ChromeCanary exited with code 0
DEBUG [temp-dir]: Cleaning temp dir C:\Users\Wicus\AppData\Local\Temp\karma-93586856
INFO [launcher]: Trying to start Chrome again (2/2).
DEBUG [launcher]: Restarting Chrome
DEBUG [temp-dir]: Creating temp dir at C:\Users\Wicus\AppData\Local\Temp\karma-42215420
DEBUG [launcher]: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe --user-data-dir=C:\Users\Wicus\AppData\Local\Temp\karma-42215420 --no-default-browser-check --no-f
irst-run --disable-default-apps --disable-popup-blocking --disable-translate http://localhost:9876/?id=42215420
INFO [launcher]: Trying to start ChromeCanary again (2/2).
DEBUG [launcher]: Restarting ChromeCanary
DEBUG [temp-dir]: Creating temp dir at C:\Users\Wicus\AppData\Local\Temp\karma-93586856
DEBUG [launcher]: C:\Users\Wicus\AppData\Local\Google\Chrome SxS\Application\chrome.exe --user-data-dir=C:\Users\Wicus\AppData\Local\Temp\karma-93586856 --no-default-browser-ch
eck --no-first-run --disable-default-apps --disable-popup-blocking --disable-translate http://localhost:9876/?id=93586856 --js-flags="--nocrankshaft --noopt"
DEBUG [web-server]: serving: C:\Users\Wicus\Desktop\work\test\node_modules\karma\static/client.html
DEBUG [web-server]: serving: C:\Users\Wicus\Desktop\work\test\node_modules\karma\static/karma.js
DEBUG [web-server]: upgrade /socket.io/1/websocket/Ok5NtxaRLEAykbLEQgxY
DEBUG [karma]: A browser has connected on socket Ok5NtxaRLEAykbLEQgxY
DEBUG [web-server]: serving: C:\Users\Wicus\Desktop\work\test\node_modules\karma\static/client.html
DEBUG [web-server]: serving: C:\Users\Wicus\Desktop\work\test\node_modules\karma\static/karma.js
DEBUG [web-server]: upgrade /socket.io/1/websocket/gxHKnL_FkTiymyH4QgxZ
DEBUG [karma]: A browser has connected on socket gxHKnL_FkTiymyH4QgxZ
DEBUG [web-server]: serving: C:\Users\Wicus\Desktop\work\test\node_modules\karma\static/client.html
DEBUG [web-server]: serving: C:\Users\Wicus\Desktop\work\test\node_modules\karma\static/karma.js
DEBUG [web-server]: upgrade /socket.io/1/websocket/bRFUuHafxjg125v8Qgxa
DEBUG [karma]: A browser has connected on socket bRFUuHafxjg125v8Qgxa
WARN [launcher]: Firefox have not captured in 60000 ms, killing.
WARN [launcher]: Chrome have not captured in 60000 ms, killing.
WARN [launcher]: ChromeCanary have not captured in 60000 ms, killing.
DEBUG [launcher]: Process Firefox exited with code 0
DEBUG [temp-dir]: Cleaning temp dir C:\Users\Wicus\AppData\Local\Temp\karma-26193441
ERROR [launcher]: Firefox failed 2 times (timeout). Giving up.
DEBUG [launcher]: Process Chrome exited with code 0
DEBUG [temp-dir]: Cleaning temp dir C:\Users\Wicus\AppData\Local\Temp\karma-42215420
DEBUG [launcher]: Process ChromeCanary exited with code 0
DEBUG [temp-dir]: Cleaning temp dir C:\Users\Wicus\AppData\Local\Temp\karma-93586856
ERROR [launcher]: Chrome failed 2 times (timeout). Giving up.
ERROR [launcher]: ChromeCanary failed 2 times (timeout). Giving up.

**Comment by dongidea** [comment]
@Wicus Do you have any update on this? I have the same issue too.

**Comment by Dignifiedquire** [comment]
For questions and support please use the mailing list or Gitter. The issue tracker is for bug reports and feature discussions only.
