### ISSUE TITLE
PhantomJS issues w/ version: 0.12.16

### ISSUE THREAD

**Issue by toranb** [karma-runner/karma#1107]
I've been using karma 0.10 for a while and recently upgraded to 0.12.16 and I seem to get the familiar "bind" issue that you normally fix by adding a polyfill. Yet in this specific version I can't seem to get around this issue (using either the ES5-shim version or a hand rolled version that I've used successfully with in the past with previous versions of karma)

Here is the full errror for anyone who wants more details.

node 0.10.29
npm 1.4.16
phantomjs 1.9.7

``` js
PhantomJS 1.9.7 (Mac OS X) ERROR
  TypeError: 'undefined' is not a function (evaluating 'RegExp.prototype.test.bind(
      /^(data|aria)-[a-z_][a-z\d_.\-]*$/
    )')
```

**Comment by tschaub** [comment]
If anybody is looking for an easy way to add `Function.prototype.bind` when running tests in PhantomJS 1.x, you can configure Karma to use the [`karma-phantomjs-shim` framework](https://www.npmjs.com/package/karma-phantomjs-shim).  Here's a sample Karma config that add a `Function.prototype.bind` implementation:

```js
module.exports = function(config) {
  config.set({
    frameworks: ['phantomjs-shim']
    // additional settings here ...
  });
};
```

**Comment by gruppjo** [comment]
@tschaub, thank you!
