### ISSUE TITLE
Allow proxy config changes by plugins

### ISSUE THREAD

**Issue by mattyclarkson** [karma-runner/karma#1110]
I have a plugin that would like to specify some proxies. Adding them to the configuration doesn't work because the proxies are bound early and my plugin injected to late. Call graph:

[middleware/proxy.js:66](https://github.com/karma-runner/karma/blob/3873c531/lib/middleware/proxy.js#L66)
[middleware/proxy.js:126](https://github.com/karma-runner/karma/blob/3873c531/lib/middleware/proxy.js#L126)
[web-server.js:54](https://github.com/karma-runner/karma/blob/3873c531/lib/web-server.js#L54)
[web-server.js:46](https://github.com/karma-runner/karma/blob/3873c531/lib/web-server.js#L46)
[web-server.js:29](https://github.com/karma-runner/karma/blob/3873c531/lib/web-server.js#L29)
[web-server.js:74](https://github.com/karma-runner/karma/blob/3873c531/lib/web-server.js#L74)
[server.js:288](https://github.com/karma-runner/karma/blob/3873c531/lib/server.js#L288)

The problem is that the injector runs my plugin after the [`webServer: ['factory', ws.create],`](https://github.com/karma-runner/karma/blob/3873c531/lib/server.js#L288) line which where the proxies are bound.

There is a [`// TODO(vojta): extract the proxy into a plugin`](https://github.com/karma-runner/karma/blob/3873c531/lib/web-server.js#L53), so this is obviously something that is to be done, can I help out now?

All links are to commit 3873c531, so that they don't rot overtime.

**Comment by jamestalmage** [comment]
See PR #2183 for the fix
