### ISSUE TITLE
Watching is not working properly on linux

### ISSUE THREAD

**Issue by ertwroc** [karma-runner/karma#1113]
Watching functionality is not working properly on linux. After initial execution of test Karma is only watching one change in file and stop watching it.

**Comment by bcherny** [comment]
If anyone runs into this in the future, what worked for me was adding the following line to karma.conf.js:

```js
transports: ['polling']
```

**Comment by henrythach** [comment]
Another suggestion for those reading this in the future, what worked for me was increasing the amount of inotify watchers.

Check out this [Increasing the amount of inotify watchers](https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers) to learn about the details, but here's a snippet if you want to try it out:

> - If you are running Debian, RedHat, or another similar Linux distribution, run the following in a terminal:
> 
> ```
> echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/> sysctl.conf && sudo sysctl -p
> ```
> 
> - If you are running ArchLinux, run the following command instead (see [here](https://www.archlinux.org/news/deprecation-of-etcsysctlconf/) for why):
> 
> ```
> echo fs.inotify.max_user_watches=524288 | sudo tee /etc/> sysctl.d/40-max-user-watches.conf && sudo sysctl --system
> ```

Hope this helps.
