### ISSUE TITLE
Plugin for managing a second server

### ISSUE THREAD

**Issue by tschaub** [karma-runner/karma#1122]
I'm working on a library that uses a server to resolve dependencies and serve library files in dependency order.  This server is currently used to view examples and run tests in development mode.  I'd like to write a module that adapts this server as a Karma plugin, but I could use advice on what type of plugin this would be.

One way I can imagine this working is to have the plugin start my server when the Karma server starts and kill my server when the karma server exits.  But it seems to me like I'd want to delay the launching of all launchers until my server is listening.  I don't see a way to do this (looking just at [`server.start()`](https://github.com/karma-runner/karma/blob/a50ebdd9f611e826aabe20bec4d61327a8f32903/lib/server.js#L27)).

Looking at [`karma-closure`](https://github.com/karma-runner/karma-closure), I get the sense that it would also be possible to do what I want by creating a plugin that acts as a framework and/or perhaps a preprocessor.

Can anyone comment on what type of plugin would be appropriate for this?

**Comment by Dignifiedquire** [comment]
I think the way to go would be a preprocessor, as they interact with the way files are loaded. Maybe https://github.com/nikku/karma-browserify could help you

**Comment by Dignifiedquire** [comment]
For questions and support please use the mailing list or Gitter. The issue tracker is for bug reports and feature discussions only.
