### ISSUE TITLE
Allow configuration for retryLimit

### ISSUE THREAD

**Issue by alias-mac** [karma-runner/karma#1126]
It would be really helpful to allow a config param in `karma.conf.js` for retryLimit for browser crashes.

It would avoid us to wrap the `grunt` or `karma` call in a command like:
```bash
$ for i in `seq 1 3`; do grunt karma:ci; test $? -ne 3 && break; done
```
command.

I don't see any available configuration in http://karma-runner.github.io/0.12/config/configuration-file.html, but I do see it in the code a possibility to pass it: https://github.com/karma-runner/karma/blob/9e0e3854853dc04dd273dd0c17878d76de24fb70/lib/launchers/retry.js#L3

Could we make this setting available in config file?
Thanks!

**Comment by gotofritz** [comment]
+1

**Comment by nuthankumarns** [comment]
+1
