### ISSUE TITLE
File load order using ! operator

### ISSUE THREAD

**Issue by jhoguet** [karma-runner/karma#1133]
Is it possible to influence the load order using the ! operator. 

For example
   files : [ '**/*.js' , '!last.js', 'last.js]

We are doing this in our grunt config but find that we are unable to do it in our karma config. 

We end up with a warning that no files were matched because the ! operator is now in the middle instead of the beginning. 
    WARN [watcher]: Pattern "/git/cc-inventory/!web-app/javascript/angular/**/*decorator*.js" does not match any file.

In looking at the source, it appears that karma is using node-glob so I was expecting this to work like grunt. 

thanks,

jon

**Comment by Dignifiedquire** [comment]
As we do more work on the file path internally, as you can see this will not work.
