### ISSUE TITLE
Wrong line number in console stack trace

### ISSUE THREAD

**Issue by clakech** [karma-runner/karma#1141]
Hi,

When an error occurs in a karma test, the line number is always the same number that does not match with the real line number where the error occurs:

Karma version: 0.12.17
Node: v0.10.25

```
Chrome 36.0.1985 (Mac OS X 10.9.4) Controller: blablaController should do some stuff FAILED
	Expected spy foo.bar to have been called with [ 'foobar' ] but it was never called.
	Error: Expected spy foo.bar to have been called with [ 'foobar' ] but it was never called.
	    at null.<anonymous> (/Users/me/workspace/foobar/app/common/foobarCtrl.spec.js:9:6615)
```

What should we do to get good line number ? On line 9 there is no code at all, its an empty line.

Any suggestion ?

**Comment by Dignifiedquire** [comment]
Closing this issue as this is not an issue with karma itself.

**Comment by jdmarshall** [comment]
Upgrading karma-coverage fixes this problem.
