### ISSUE TITLE
Chrome not captured when running tests on Travis

### ISSUE THREAD

**Issue by manleyjster** [karma-runner/karma#1144]
Karma tests are failing on Travis when it tries to run tests in Chrome.

Since I posted this issue on the travis-ci issues page, I've noticed that the tests run successfully in PhantomJS, so I'm wondering if this error may be traced back to Karma.

The error message is:
```
INFO [launcher]: Starting browser Chrome
WARN [launcher]: Chrome have not captured in 60000 ms, killing.
INFO [launcher]: Trying to start Chrome again (1/2).
WARN [launcher]: Chrome have not captured in 60000 ms, killing.
INFO [launcher]: Trying to start Chrome again (2/2).
WARN [launcher]: Chrome have not captured in 60000 ms, killing.
ERROR [launcher]: Chrome failed 2 times (timeout). Giving up.
```

Detailed issue report here: https://github.com/travis-ci/travis-ci/issues/2555

**Comment by Dignifiedquire** [comment]
Not an issue with karma, so closing.

**Comment by inf3rno** [comment]
@MrOrz Thanks! The no-sandbox flag was missing. :-)
