### ISSUE TITLE
Wrong script URL when debugging

### ISSUE THREAD

**Issue by ladariha** [karma-runner/karma#1145]
I have karma.conf.js which contains files defined like:

           basePath : '../',
           files: [
            '../neco/test/lib/angular/angular-mocks.js',
            'app/js/**/*.js',
            '../neco/test/unit/**/*.js'
        ],

As you can see, I have ```../neco/``` for paths for my test files. If I open the Karma debug page (debug.html) and check CDT for loaded scripts, the test files have absolute URL:

    <script type="text/javascript" src="/absoluteC:/Users/vlriha/Downloads/debug2/debug/project_debug_5/neco/test/unit/directivesSpec.js"></script>

while the source files have relative URL

    <script type="text/javascript" src="/base/app/js/services.js"></script>

Shouldn't the absolute url be like

    /absolute/C:/Users/vlriha/Downloads/debug2/debug/project_debug_5/neco/test/unit/directivesSpec.js

BTW Is there some command line parameter to force Karma to use always absolute paths?

**Comment by Dignifiedquire** [comment]
This is a known issue and hasn't been fixed yet: #251
