### ISSUE TITLE
Chrome browser fails on presence of existing "//@ sourceMappingURL" source maps

### ISSUE THREAD

**Issue by kimardenmiller** [karma-runner/karma#1173]
Because our app relies on certain Javascript Rails Assets, we are attempting to set the conf. -> files to ```http://railsapp.dev/assets/application.js``` following [this example](http://danott.co/posts/rails-javascript-testing-using-karma.html). It seems to work until Chrome finds ```//@ sourceMappingURL``` in that ```application.js``` file, at which point it throws ```Uncaught SyntaxError: Unexpected token }```

The same ```application.js``` works fine in Chrome served with the full webpage. [Here is a Gist of that application.js](https://gist.github.com/kimardenmiller/cfa0981b7f60d4c3c502)

Ways to work around this issue?

**Comment by Dignifiedquire** [comment]
@kimardenmiller sorry for the late reply, is this still an issue and have you looked at https://github.com/tschaub/karma-source-map-support which might help you in this.

**Comment by kimardenmiller** [comment]
@Dignifiedquire thank you for the follow up. I did solve this issues last year.

**Comment by Dignifiedquire** [comment]
Thanks
