### ISSUE TITLE
Write some documentation on how to write a karama plugin

### ISSUE THREAD

**Issue by fresheneesz** [karma-runner/karma#1176]
I can't find any information about how to write a Karma plugin. The [plugin page](http://karma-runner.github.io/0.12/dev/plugins.html) doesn't seem to tell you anything at all about how to write one, it just lists some example plugins.

Where's the docs for this?

**Comment by Dignifiedquire** [comment]
We need some documentation for this. If anyone is up to it please feel free to submit a PR

**Comment by devoto13** [comment]
The basic documentation for how to write a simple plugin has been added to http://karma-runner.github.io/latest/dev/plugins.html. It's likely not as elaborate as it could be, so feel free to open a new issue if something specific is unclear and we'll refine it further.
