### ISSUE TITLE
Karma tests failing because of $location:nobase error

### ISSUE THREAD

**Issue by thanpolas** [karma-runner/karma#1178]
When having html5Mode enabled in $location it is now required to have a `<base href="/">` tag into the `HEAD` element.

If no `base` element is found then a [$location:nobase error](https://docs.angularjs.org/error/$location/nobase) is thrown, karma needs to adjust to this requirement.

**Comment by marthinus-engelbrecht** [comment]
Facing the same issue.

**Comment by marthinus-engelbrecht** [comment]
I'm facing the same issue.

**Comment by marthinus-engelbrecht** [comment]
The problem can be solved by adding   <base href="/"> in the <head> tag in "context.html" file but I'm not sure how that would affect other users.
