### ISSUE TITLE
Bare reference to `window.console` in IE

### ISSUE THREAD

**Issue by mightyiam** [karma-runner/karma#1209]
Perhaps I'm missing something.

[This line](https://github.com/karma-runner/karma/blob/master/static/debug.html#L26) has `window.console.log` reference, which, in IE8—and perhaps in other IEs—isn't available.

So, there's an exception. I'm not even sure that this causes issues but perhaps it does?

**Comment by freethejazz** [comment]
@mightyiam @maksimr What do you think would be acceptable alternative behavior? Should the log message be swallowed if console isn't present? Should it be replaced with an alert instead?

**Comment by maksimr** [comment]
@freethejazz 
I think we should not print message in console.log on debug page if console does not exist

**Comment by mightyiam** [comment]
@freethejazz, I agree with @maksimr. Use `console` only when it exists. I think it can be a simple `if (window.console)`.

**Comment by mightyiam** [comment]
Thank you, @freethejazz and @maksimr.
