### ISSUE TITLE
WARN optional dep failed while Installing npm install -g karma

### ISSUE THREAD

**Issue by gitsuraj** [karma-runner/karma#1216]
For some reason I cannot install karma in my windows 8.1 system. Here's a error log from my installation log.  
>>  npm install -g karma
    npm WARN optional dep failed, continuing fsevents@0.3.0
    npm ERR! Error: ENOENT, lstat 'C:\Users\suraj\AppData\Roaming\npm\node_modules\karma\node_modules\socket.io\node_modules\redis\multi_bench.js'
    npm ERR! If you need help, you may report this *entire* log,
    npm ERR! including the npm and node versions, at:
    npm ERR!    
    npm ERR! System Windows_NT 6.2.9200
    npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "karma"
    npm ERR! cwd C:\Users\suraj
    npm ERR! node -v v0.10.29
    npm ERR! npm -v 1.4.14
    npm ERR! path C:\Users\suraj\AppData\Roaming\npm\node_modules\karma\node_modules\socket.io\node_modules\redis\multi_bench.js
    npm ERR! fstream_path C:\Users\suraj\AppData\Roaming\npm\node_modules\karma\node_modules\socket.io\node_module\redis\multi_bench.js
    npm ERR! fstream_type File
    npm ERR! fstream_class FileWriter
    npm ERR! code ENOENT
    npm ERR! errno 34
    npm ERR! fstream_stack C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
    npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
    npm ERR! Error: ENOENT, lstat C:\Users\suraj\AppData\Roaming\npm\node_modules\karma\node_modules\socket.io\node_moduls\socket.io-client\components\learnboost-engine.io-client\lib\emitter.js'
    npm ERR! If you need help, you may report this *entire* log,
    npm ERR! including the npm and node versions, at:
    npm ERR!
    npm ERR! System Windows_NT 6.2.9200
    npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "karma"
    npm ERR! cwd C:\Users\suraj
    npm ERR! node -v v0.10.29
    npm ERR! npm -v 1.4.14
    npm ERR! path C:\Users\suraj\AppData\Roaming\npm\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\components\learnboost-engine.io-client\lib\emitter.js    npm ERR!
 fstream_path C:\Users\suraj\AppData\Roaming\npm\node_modules\karma\node_modules\socket.io\node_module\socket.io-client\components\learnboost-engine.io-client\lib\emitter.js
    npm ERR! fstream_type File
    npm ERR! fstream_class FileWriter

**Comment by Dignifiedquire** [comment]
Closung due to inactivity. Please feel free to open a new issue if this problem still persists.
