### ISSUE TITLE
Dynamically add file available in testing inside preprocessor.

### ISSUE THREAD

**Issue by ouhouhsami** [karma-runner/karma#1219]
Hello, 

In a preprocessor, I process a file (and return it, all works well), but also I create a new one that I need to have available during testing. How can I achieve this, inside a preprocessor.

Best

**Comment by andersekdahl** [comment]
+1

I'm trying to get this working as well. What I'm doing is having both a framework and a preprocessor, and in the framework factory appending a file to the `config.files` list, and adding it to the `config.preprocessors` object as well. But for some reason it's not passed through my preprocessor. Is there some sort of timing issue where it's too late for the framework factory to add patterns to the `config.preprocessors` object? I can add them to `config.files` and they get included, just not processed.

**Comment by Dignifiedquire** [comment]
Should be solved by #1341
