### ISSUE TITLE
karma ignored passed tests, using mocha and debug mode

### ISSUE THREAD

**Issue by darrrk** [karma-runner/karma#1221]
I have tests, written using mocha. Approximate file structure:

    describe "all tests in specific partition", ->
    
        before (done)->
            # here some logic, where I check that entrance in partition seems good
  
        it "test1", ->
            # bla-bla

        it "test2", ->
            # bla-bla

        # other test bla-bla

When I run karma, using debug mode, I see, that all tests passed and before hook call done correctly.
But karma say, that:

      "all tests in specific partition"
         "before all" hook
            Chrome 38.0.2125 (Mac OS X 10.9.5)
               Error: timeout of 30000ms exceeded

And all passed tests ignored

This problem also affect using karma-teamcity-reporter

**Comment by Dignifiedquire** [comment]
Closung due to inactivity. Please feel free to open a new issue if this problem still persists
