### ISSUE TITLE
Karma init. TypeError: Cannot call method 'slice' of undefined

### ISSUE THREAD

**Issue by maksimr** [karma-runner/karma#1231]
Get error when try run `karma init`: 

```
 readline.js:507
  this.line = this.line.slice(this.cursor);
                        ^
TypeError: Cannot call method 'slice' of undefined
    at Interface._deleteLineLeft (readline.js:507:25)
    at suggestNextOption (/home/maksimrv/www/jetbrains/.../node_modules/karma/lib/init/state_machine.js:43:9)
    at nextQuestion (/home/maksimrv/www/jetbrains/.../node_modules/karma/lib/init/state_machine.js:120:12)
 ```

- Linux 3.13.0-24-generic 47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
- Ubuntu 14
- Karma version: 0.12.24
- karma-cli 0.0.4
- node 0.10.29/0.11.13
- use nvm

We had same error on [Windows under *Cygwin*](http://stackoverflow.com/questions/19070777/get-error-with-line-slice-on-karma-init) now I can reproduce it on *ubuntu*

**Comment by Dignifiedquire** [comment]
@maksimr is this still an issue with the latest node versions?

**Comment by maksimr** [comment]
@Dignifiedquire nope
