### ISSUE TITLE
API for filtering executed tests

### ISSUE THREAD

**Issue by segrey** [karma-runner/karma#1235]
Karma IDE integrations' users would benefit from the opportunity to be able to run single test / test suite / test file only.

At the moment it's already available for karma-mocha adapter through passing client argument (`--grep`).

Also it's possible to run single Jasmine spec/suite through editing source code (`iit/ddescribe`). Seems source code editing could be avoided if a new preprocessor would insert `iit/ddescribe` in the result file at proper offset that is served. Maybe better solutions for Jasmine exist.

How about having a common universal API on Karma level (JavaScript API or a new cli option) for filtering executed tests by test name / test suite name / test file name?

**Comment by Dignifiedquire** [comment]
I don't think this will be doable right now as Karma does not understand tests on this level, it only supports what the underlying test runner supports.

**Comment by segrey** [comment]
@Dignifiedquire  Probably, requesting "API" was too much. Well, I understand that test filtering is implemented on an adapter level. The problem is that each framework adapter (e.g. `karma-mocha` and `karma-jasmine`) handles client argument in its own non-unified way. This issue is about client argument format unification.
I mean, currently, IDE needs to identify the adapter that is being used, and then format client argument depending on this information. It'd be great if there would be a common rule of formatting client argument to filter tests.

**Comment by Dignifiedquire** [comment]
@segrey I see. I'm still not sure if it's possible to do, as we could only pass something like the `grep` options from mocha, as using `iit` is not an option (we would have to rewrite test files on the fly). Do you know if jasmine and qunit support grep like  options?

**Comment by segrey** [comment]
@Dignifiedquire As for `karma-jasmine`, it already supports `--grep` (https://github.com/karma-runner/karma-jasmine/pull/56) by the mean of `jasmineEnv.specFilter`. Don't know about qunit. Looks like it exposes some API https://github.com/jquery/qunit/blob/master/src/test.js#L378, but `karma-qunit` doesn't use it.

**Comment by adambiggs** [comment]
@dignifiedquire I'm working on a very large app with ~5k Mocha tests loaded via RequireJS. While it's true that we can run specific tests using Mocha `--grep`, the feature is severely crippled because RequireJS still loads our entire test suite... So even running a single test takes around 10-20 seconds.

It would be very powerful if Karma provided some way to modify the `window.__karma__.files` array before starting the test run.

**Comment by wesleycho** [comment]
What would grep like support look like for this @dignifiedquire? I have had a work request for this on my team a couple of months ago, as it would aid developer workflow greatly when using an IDE like WebStorm, so I would be interested in implementing support for this.

**Comment by segrey** [comment]
Looks like there is no way to run tests in a given folder. Currently, it's possible to pass a string literal only as `--grep`. What do you think about extending `--grep` option and allowing passing a regexp like `^(top level suite1)|(top level suite2)|...` where `top level suite 1` is a name of top level suite in file1, etc. This regexp accepts tests from a given file set and, thus, is a rough approach to run all tests in a given folder.
@dignifiedquire @maksimr What do you think?

Should I file corresponding issues in karma-jasmine and karma-mocha?

**Comment by maksimr** [comment]
@segrey We parse `--grep` as regular expression now - https://github.com/karma-runner/karma-jasmine/blob/4213b187c406d6a568592c7485d0fc5ff8271500/src/adapter.js#L274-L281.

So you already could pass any valid regexp.

**Comment by segrey** [comment]
@maksimr Yeah, but regexp is also escaped with `.replace(/[-[\]{}()*+?.,\\^$|#\s]/g, '\\$&')`. IIUC, it makes `--grep` value to behave like a string literal.

**Comment by segrey** [comment]
`--grep` can be handled as regexp after https://github.com/karma-runner/karma-jasmine/commit/3b20480a5a1cfa769c2a1861455c76d3bfaaab52

Closing this issue.
