### ISSUE TITLE
Support serving precomputed static gzip source files

### ISSUE THREAD

**Issue by plasticine** [karma-runner/karma#1241]
Hi there,

I understand that on-the-fly serving of Gzipped source files was removed sometime in `0.11` (in 5ee886b specifically), however I would like to propose that Karma should support the serving of precompiled `*.js.gz` source files if they exist.

When doing remote testing one of the big stumbling blocks, and the cause of nearly all false-fails is due to the network overhead of serving large test bundles to Saucelabs or similar. For example our main test bundle weighs in at ~20MB without compression (~3MB with compression).

I totally understand why computing and serving a gzip alternative is not ideal in most cases, however using something like `connect-gzip-static` seems like a reasonable compromise between control and speed.

Cheers,
Justin

**Comment by dignifiedquire** [comment]
Karma already does a lot of things, and I do not want to add this on top of it. If you really need this, it should be very easy to add sth like nginx or a simple connect server in front of it that gzips files when needed
