### ISSUE TITLE
any guide for writing karma plugins?

### ISSUE THREAD

**Issue by atian25** [karma-runner/karma#1254]
more detail

**Comment by brutalcrozt** [comment]
I also expecting this.

### Developing Plugins
> The best way to understand how this works is to take a look at some of the existing plugins

existing plugins can be wrong, have existing bug, also possibly not utilize all functionality core karma offers.

### Public Api

point from @atian25 
- seq
 I also need that, if it stand for sequence 
- concept
clear, but i expecting deeper explanation

I like to suggest updating the documentation, especially FAQ and public API.

I hope when the documentation improved. Then when it did we got benefit that existing issues and bug are easier to tackle.

**Comment by gabrielalan** [comment]
Hi guys, any clue on how to write an async framework factory?

**Comment by johnjbarton** [comment]
'async' here is ambiguous, but I assume you mean a plugin that can block testing until a remote service responds with eg test data or service-availability signal. I don't think that is supported. The equivalent functionality can be achieved by starting remote services before invoking karma.

**Comment by gabrielalan** [comment]
Please check @pact-foundation/karma-pact. You will understand what I’m talking about... they use “deasync” which is a lib that uses C++ under the hood just to block the thread so I can start a server... so you are basically saying that what they do there, it’s bad practice?

**Comment by johnjbarton** [comment]
No, I did not say that. I said

> The equivalent functionality can be achieved by starting remote services before invoking karma.

**Comment by gabrielalan** [comment]
I just wanted to have a statement, because what they did on karma-pact, seems really bad practice.
