### ISSUE TITLE
Failed to proxy requests

### ISSUE THREAD

**Issue by cinan** [karma-runner/karma#1264]
I set up proxies like this:

```
proxies: {
      '/config.yaml': 'http://project.local:8081/config.yaml',
}
```
Now if I go to http://localhost:9876/config.yaml (there's ```node node_modules/karma/bin/karma start test/karma.conf.js --single-run --log-level=debug``` running) I get this error:

```
DEBUG [proxy]: proxying request - /config.yaml to project.local:8081
WARN [proxy]: failed to proxy /config.yaml (connect ECONNREFUSED)
```

Although project.local:8081/config.yaml does exist and I can access it from a browser. Chrome and Firefox are saying 'Waiting for localhost...' in status bar.

I've found (with wireshark) there's no request to 'http://project.local:8081/config.yaml'.

Probably it's a OS X related issue because on Ubuntu 14.04 everything's working correctly (same project/configuration/package versions).

I'm running OS X 10.10.1, karma 0.12.28, node 0.10.33

**Comment by cinan** [comment]
I found fix. Probably this issue isn't related to karma but Yosemite. I've stop using custom hosts (e.g. project.local). I'm running the project on localhost and everything's fine now.

**Comment by PowerKiKi** [comment]
This is old, but for others: Instead of `.local` TLD you [should use something else](http://unix.stackexchange.com/a/92517/52623), such as `.lan`. This would avoid the issue while still allowing you to have custom domains.
