### ISSUE TITLE
Breaks source map if error message contain url without line number and column

### ISSUE THREAD

**Issue by maksimr** [karma-runner/karma#1274]
We have two cases when it possible

- In latest version of [karma-jasmine](https://github.com/karma-runner/karma-jasmine) when test contain variable which does not defined we have error message:

```txt
ReferenceError: plus is not defined in http://localhost:9876/base/test.js?5e4e9f0005ec2172d5edc1234305ab74e3267861 (line 6)
```

- Firefox [sometimes](https://github.com/karma-runner/karma/pull/1098) throw error with formatted stack trace. (NOTE: Maybe it's first case)

- Rare case. User can define test cases or test suites which contain url, for example:

```js
it('should go to the http://lolcalhost/base/rest', function(){...})
```
 
In those three cases [reporter.js](https://github.com/karma-runner/karma/blob/master/lib/reporter.js#L49) breaks with error:
```
ERROR [karma]: [TypeError: Line must be greater than or equal to 1, got 0]
TypeError: Line must be greater than or equal to 1, got 0
```

**Comment by Dignifiedquire** [comment]
@maksimr are you actually working on this? I added it to the 1.0 milestone as it feels like this is something that needs fixing.

**Comment by maksimr** [comment]
@Dignifiedquire 
Now dont work, but I will look at it on this week

**Comment by Dignifiedquire** [comment]
Okay cool

**Comment by Nathan219** [comment]
I have managed to get this error to happen when I had a unit test still being ran meant to test a service that no longer existed.  I managed to see an angular 'Unknown provider' error when I ran the tests in debug (in webstorm).

**Comment by codehotter** [comment]
This patch fixes at least the jasmine case for me (didn't test the others).
How naive is this fix?

```
diff --git a/lib/reporter.js b/lib/reporter.js
index 9bcbab0..8c62cfe 100644
--- a/lib/reporter.js
+++ b/lib/reporter.js
@@ -49,7 +49,7 @@ var createErrorFormatter = function (basePath, emitter, SourceMapConsumer) {
 
       var file = findFile(path)
 
-      if (file && file.sourceMap) {
+      if (file && file.sourceMap && line) {
         line = parseInt(line || '0', 10)
 
         column = parseInt(column, 10)
```

**Comment by davidparsson** [comment]
Thanks for the pointer, @codehotter. I implemented that in the PR above.
