### ISSUE TITLE
Background and istanbul coverage

### ISSUE THREAD

**Issue by samudurand** [karma-runner/karma#1278]
I wrote a karma configuration using Istanbul coverage that was working perfectly fine when I run it using Grunt, until I tried to make it run in background.

Here is the Grunt task : 

```
karma: {
      unit: {
        configFile: 'karma.conf.js'
      },
      continuous: {
        configFile: 'karma.conf.js',
        singleRun: true,
        background: true
      }
    }
```

The tests are running well with or without the 'background' config, but if I let the 'background' then istanbul does not write the report (no error shown, just nothing generated).

**Comment by maksimr** [comment]
@samudurand seems it is issue of [grunt-karma](https://github.com/karma-runner/grunt-karma) or [karma-coverage](https://github.com/karma-runner/karma-coverage)

**Comment by samudurand** [comment]
You never had the problem with karma only then ? Ok I will contact them then

**Comment by maksimr** [comment]
@samudurand sorry but what mean 'background' in context of karma.conf.js? For me it is grun specific option. Thanks

**Comment by samudurand** [comment]
indeed... It is the possibility of not showing the browser opened by karma while the tests are run. Does it not exist nativelly on karma ?

**Comment by maksimr** [comment]
@samudurand nope. But some launchers have [workaround](https://github.com/karma-runner/karma-chrome-launcher/issues/27)

**Comment by samudurand** [comment]
Thanks for the information @maksimr , I thought it was native. I will contact karma-runner team.

**Comment by maksimr** [comment]
@samudurand no problems

> I will contact karma-runner team

I'm one of the members of this team ;)

**Comment by samudurand** [comment]
xD sorry comment edited, kind of late in France ;)
