### ISSUE TITLE
BrowserStack timeouts on OS X

### ISSUE THREAD

**Issue by mzgol** [karma-runner/karma#1284]
I've noticed that even with latest Karma versions (like 0.12.31) BrowserStack is disconnecting when running browsers on OS X. With Firefox/Chrome it's easy enough to switch to Windows, not so much with Safari.

After e-mail exchanges with the BrowserStack team it turned out the old socket.io version is the culprit. I see @vojtajina already has a [WIP branch](https://github.com/vojtajina/karma/tree/socketio_10) with newer socket.io version but I didn't see any issue to track these BrowserStack issues so I'm creating this one.

BTW, I can't run this WIP branch in my project as we rely on Node 0.11.14 and the version from the branch doesn't have fixes making it work in this Node versions (those fixes are included in newest released Karma versions).

I've checked locally and I confirm that Karma version from the branch seems to fix those BrowserStack issues when run from Node 0.10.

**Comment by dhimil** [comment]
@Grummle, I already working with @vojtajina to fix the issue and upgrade the socket.io version in karma. Apart from the socket.io branch in Vojta's fork we have:
PR: https://github.com/karma-runner/karma/pull/1257
Issue: https://github.com/karma-runner/karma/issues/1220

May be we can continue there.

**Comment by mzgol** [comment]
I've missed issue #1220 somehow, I'm closing this one then.
