### ISSUE TITLE
Start karma with no autorun

### ISSUE THREAD

**Issue by balauru** [karma-runner/karma#1288]
Hi, 

I will love it if karma won't run all the tests at start.

**Comment by maksimr** [comment]
@balauru why?

**Comment by maksimr** [comment]
You can put to karma.conf.js:

```js
        frameworks: ['jasmine'],
        files: [
            '*.test.js'
        ],
        autoWatch: false,
        browsers: ['PhantomJS'],
        singleRun: false
```

and then manually run tests `karma run --port=9876`

**Comment by balauru** [comment]
@maksimr the current project has about 3k tests that take around 5 minutes to run, I don't want to run them on each start given that the CI is green

The answer I was looking for is to simply double the letter of the test `ddescribe` or `iit` and then when you call karma start it will only run that test.

**Comment by maksimr** [comment]
@balauru great.

Be careful, since version of 0.3 karma-jasmine [change](https://github.com/karma-runner/karma-jasmine/commit/207018b83201b2b72cb14a8c6d528ac24d53f7a9) ddescribe on [fdescribe](http://jasmine.github.io/2.1/focused_specs.html) and iit on fit.
