### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by tflori** [karma-runner/karma#1290]
there are just some redirects to this or that but no documentation like:
void module(string moduleName[, requirements...])... 

after searching half an hour i've not found any api reference for karma.. thats poor :(

**Comment by tflori** [comment]
sorry, but thats frustrating.. I've seen that you can call module with a second parameter that uses dependency injection. I don't know if it is a config function or a run function or something else?

on the projects github page:
Using it: see configuration (https://karma-runner.github.io/0.12/intro/configuration.html)

there is no description how to write tests, what is module() and what is inject()...

So: I still don't get it. Where can I get help? Docs (https://karma-runner.github.io/0.12/index.html)

there is a video (I'm not at home with limited data transfer) - I don't want to watch a video. so there are some links to jasmine, qunit and so on.. and to the github page. but there is no documentation.

**Comment by juliemr** [comment]
Hi @tflori - `inject` and `module` are AngularJS functions, which are introduced by the angular mocks module. There's information on using them at https://docs.angularjs.org/guide/unit-testing and at https://docs.angularjs.org/api/ngMock/function/angular.mock.inject for inject and https://docs.angularjs.org/api/ngMock/function/angular.mock.module for module.

**Comment by Dignifiedquire** [comment]
If you need help on documentation please ask on the mailing list or on gitter, thanks.
