### ISSUE TITLE
Race condition in our E2E tests

### ISSUE THREAD

**Issue by sjelin** [karma-runner/karma#1291]
@juliemr and I spent a little while hunting this one down yesterday.  The short of it is that [asynchronously writing `karma.conf.js`](https://github.com/karma-runner/karma/blob/master/test/e2e/support/world.coffee#L38) causes the tests to be asynchronous, and as a result two tests can run at the same time.  Specifically, I can consistently cause the following to happen on my OSX and Ubuntu machines:

1. [`proxy.feature`](https://github.com/karma-runner/karma/blob/master/test/e2e/proxy.feature) reaches the `fs.writeFile` line
2. [`reconnecting.feature`](https://github.com/karma-runner/karma/blob/master/test/e2e/reconnecting.feature) reaches the `fs.writeFile` line
3. `reconnecting.feature`'s callback is called
4. `proxy.feature`'s callback is called

The result is that both `reconnecting.feature` and `proxy.feature` read from a corrupted `karma.conf.js`, causing both tests to fail dramatically.  I see three possible solutions:

1. Get cucumber.js to wait for one test to finish before starting the next
2. Make writing a file synchronous
3. Randomize the file name for what is currently `karma.conf.js` so that collisions are unlikely

Solution 1 the best of course.  I dug into how `grunt-cucumberjs` invokes the tests, and basically it's just running cucumber's [command-line script](https://github.com/cucumber/cucumber-js/blob/master/bin/cucumber.js).  I couldn't find a cucumber flag for waiting for asynchronous tests however (I even looked at parts of the [source code](https://github.com/cucumber/cucumber-js/blob/master/lib/cucumber/cli/argument_parser.js#L129)).  So this solution seems unfeasible.

Solution 3 is a terrible idea, since it exposes us to more race conditions in the future*.  So I vote that we make writing the config file synchronous.  It's a little inefficient, but it's the simplest, most future-proof solution.

*Julie ran into an error about a port being in use at one point in time.  It could have been that two tests were both trying to run `karma start` at the same time

**Comment by vojtajina** [comment]
Thanks for looking into this @sjelin !

Are you sure Cucumber runs the scenarios in parallel? I don't think that's the case. Sounds like there might be some problem in our code in test/e2e/steps/core_steps.coffee or test/e2e/support/world.coffee.

Ad3, I think ideally the scenarios should not depend on each other so that they are concurrent (can be run in parallel). Can we name the files somehow deterministically (not randomly) to avoid conflicts? I think that would be the best solution.

**Comment by sjelin** [comment]
I'm not totally sure if cucumber tries to run the tests in parallel or if we're doing something wrong on our end.  I tried reading through the cucumber code last night but it was getting late.  I'll take another look later today.

I'm sure we could do some sort of hash on the config file to generate unique file names.  I suppose we could also add some logic for finding an unused port, if I can reproduce that problem.

**Comment by sjelin** [comment]
Hey @vojtajina, did a bit more digging.  You're right that cucumber should wait for our asynchronous tests.  However, if you call the callback function multiple times, you can trick cucumber into running multiple tests at once.  Which is exactly what we're doing!

The problem is actually that right [here](https://github.com/sjelin/karma/blob/master/test/e2e/steps/core_steps.coffee#L63).  That particular line is getting executed four times in [pass-opts.feature](https://github.com/sjelin/karma/blob/master/test/e2e/pass-opts.feature) and twice in [timeout.feature](https://github.com/sjelin/karma/blob/master/test/e2e/timeout.feature).  I'll dig a bit deeper and try to fix the problem.
