### ISSUE TITLE
Karma exits with code 1 when it doesnt execute any spec tests

### ISSUE THREAD

**Issue by ankurp** [karma-runner/karma#1301]
Karma test runs fine but exits with code `1` if `0 of 0` tests are run. Is this a bug or by design?

`Executed 0 of 0 ERROR`

**Comment by ankurp** [comment]
Having no specs is an error in karma. https://gist.github.com/armw4/0344468bc84363ce570e

**Comment by ilanbiala** [comment]
+1 please fix this. I exclude tests or have 0 tests for a reason.

**Comment by wesleycho** [comment]
Why would one want to use karma with zero tests?

**Comment by devoto13** [comment]
This behaviour can now be controller with [`failOnEmptyTestSuite` parameter](http://karma-runner.github.io/5.0/config/configuration-file.html). The default stays the same - empty test suite will exit with 1 as it is likely an mistake.
