### ISSUE TITLE
Karma doesn't find Worker script

### ISSUE THREAD

**Issue by janpetzold** [karma-runner/karma#1302]
I'm trying to test WebWorkers with PhantomJS/Karma/Angular/Jasmine and Karma always states that it can't find the file:

`var worker = new Worker('js/path/to/my/worker.js');`

Path matches the path of all my other scripts, I can enter any (valid) path here, I've tried dozens of combinations, but Karma always gives me a 404 and the test fails.

I'm working around this by overwriting window.Worker in `beforeEach`, but there should be a better way?

It doesn't matter that much whether the Worker is actually executed, but it should not break the test.

**Comment by maksimr** [comment]
Try put `new Worker('/base/js/path/to/my/worker.js')`.
Karma served scripts under path `base/<path-from-config`. You can look at the script path on debug page (localhost:9876/debug.html).

![](http://sc-cdn.scaleengine.net/i/cf9cc152437301f9b7abcf135a60aa81.png)

**Comment by janpetzold** [comment]
Yep, that works. Thanks a lot.

**Comment by liuxiong332** [comment]
great!
