### ISSUE TITLE
yo angular generator error phantomjs install

### ISSUE THREAD

**Issue by saqueib** [karma-runner/karma#1305]
I have a ticket opened at yo angular [npm](https://github.com/npm/npm/issues/7306#issuecomment-73453466), as @smikes suggested its related to Karma so I am opening this issue, Please help me with this error, its coming when i ran `$ yo angular `

       {"node":"~0.8 || ~0.10"} (current: {"node":"0.12.0","

my Node version is v0.12.0 NPM is 2.5.0 and OSX 10.9

**Comment by Dignifiedquire** [comment]
the latest version of Karma supports 0.12 which should fix this issue.
