### ISSUE TITLE
Attempting to change the getter of an unconfigurable property

### ISSUE THREAD

**Issue by rinatio** [karma-runner/karma#1306]
Hello guys,

I use karma to test angularjs application and one of my services has a getter definition and since it's got included on every test I get a phantomjs exception `Attempting to change the getter of an unconfigurable property`. 

Here's a code to reproduce

```
describe('test getter', function() {

    var Func = function() {};

    it('test1', function() {
        Object.defineProperty(Func.prototype, 'test', {get: function() {
            return 'test';
        }});
    });

    it('test2', function() {
        Object.defineProperty(Func.prototype, 'test', {get: function() {
            return 'test';
        }});
    });

});
```

**Comment by freethejazz** [comment]
@rinatio By default, when you add accessors like `get` and `set` using `Object.defineProperty`, they cannot be changed in the future. If you want to do that, you need to pass a third argument to the `defineProperty` method: `{configurable: true}`. This is not an issue with karma, but intended behavior of `Object.defineProperty`.

Some resources that might help clarify: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

http://www.ecma-international.org/ecma-262/5.1/#sec-15.2.3.6

**Comment by maksimr** [comment]
Issue is not relate to `karma`.
Answer @freethejazz should help you solve the problem.

Thanks

**Comment by rinatio** [comment]
@freethejazz Yeah, I know that. The thing is that in the tests you usually instantiate some services many times and `defineProperty` executed each time (in real browser application it doesn't happen). I use workaround for my usecase by defining getter outside of `angular.module('app').factory(function() {})`. Thanks anyway

**Comment by freethejazz** [comment]
@rinatio There should be a way to isolate application state in between tests. In the sample test case, you're declaring `Func` on the describe level, and because of that the same variable gets used across the tests. Is this something you're doing in your actual test case? If so, try to move that declaration into the `it` block so it doesn't get used across each test.
