### ISSUE TITLE
Max number of browsers to launch at a time

### ISSUE THREAD

**Issue by lukescott** [karma-runner/karma#1307]
Using a launcher such as karma-browserstack-launcher or karma-sauce-launcher allows you to spawn dozens of browsers at a time. Unfortunately if you add too many of these they tend to disconnect more frequently.

It would be nice if there was an option to specify how many browsers should be launched and finished before the next set gets launched. For example, if you set 5 and had 20 browsers it would launch the first 5 and wait for that 5 to complete before launching the next 5.

**Comment by freethejazz** [comment]
Have you tried tweaking timeout settings? A combination of `captureTimeout`, `timeout`, and `browserNoActivityTimeout` might do the trick.

This thread describes something that may be similar, although it doesn't specify the _number_ of browsers connecting to be a problem. I wonder if the underlying issue of what you're experiencing is related.
https://groups.google.com/forum/#!topic/karma-users/B-E7nLphNHQ

**Comment by freethejazz** [comment]
This may also help in the mean time: https://oligofren.wordpress.com/2014/05/27/running-karma-tests-on-browserstack/

**Comment by Dignifiedquire** [comment]
This should be something that is done in the plugin specific configuration I would say.
