### ISSUE TITLE
JQuery 2.1.1.js throws 'Unexpected identifier' exception

### ISSUE THREAD

**Issue by thesameqad** [karma-runner/karma#1308]
Hello,

After migration from jQuery 2.0.0 to 2.1.1, we start receiving an error:

Uncaught SyntaxError: Unexpected identifier
at http://localhost:9877/context.html:1

That happens once we are running a karma, before our specs execution. Such error occurs, if you will make a typo in javascript file. However, I believe, jquery-2.1.1.js should not have any typo. I also checked that it is fine in JSLint.  
After some investigations, we found out, that this happens in karma.js here:

    // This causes memory leak in Chrome (17.0.963.66)
    contextWindow.onerror = function() {
      return contextWindow.__karma__.error.apply(contextWindow.__karma__, arguments);
    };

It looks like karma checks for js files syntax and thows exceptions if the validation was failed.  For some reasons, jquery-2.1.1.js never passes the validation. 
I am pretty sure, that the reason is in jquery-2.1.1.js validation, because, everything works fine if we remove jquery-2.1.1.js from karma.conf.js or change to jquery-2.0.0.js.  

Any ideas? 

Thanks

**Comment by maksimr** [comment]
@thesameqad do you use preprocessors?

**Comment by thesameqad** [comment]
No,

Here is my karma.conf.js:

// Karma configuration
// Generated on Fri Nov 07 2014 10:49:38 GMT-0600 (Central Standard Time)
module.exports = function(config) {
    config.set({
        // base path that will be used to resolve all patterns (eg. files, exclude)
        basePath: '',

        // frameworks to use
        // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
        frameworks: ['mocha','chai','sinon'],

        // list of files / patterns to load in the browser
        files: [
            'framework/libs/deps/jquery-2.1.1.js',
            'SOME_FILES'
        ],

        // list of files to exclude
        exclude: [
            'SOME_FILES'
        ],
        // test results reporter to use
        // possible values: 'dots', 'progress'
        // available reporters: https://npmjs.org/browse/keyword/karma-reporter
        reporters: ['progress'],

        // web server port
        port: 9877,

        // enable / disable colors in the output (reporters and logs)
        colors: true,

        logLevel: config.LOG_INFO,
        autoWatch: true,

        browsers: ['Chrome_without_security'],

        customLaunchers: {
            Chrome_without_security: {
                base: 'Chrome',
                flags: ['--disable-web-security']
            }
        },
        singleRun: false,
        browserNoActivityTimeout: 100000

    });
};

**Comment by Dignifiedquire** [comment]
the error is not very helpful but karma isn't checking the validity of your file but rather the browser trying to execute it. So it seems you have simply some error in your code. Try using the debug view to get a more usefull error.

**Comment by Dignifiedquire** [comment]
For questions and support please use the mailing list or Gitter. The issue tracker is for bug reports and feature discussions only.

**Comment by witwit** [comment]
just as an information for the future seekers:
    files: [
        { pattern: '*.html', served: true, included: false },
    ]
make sure your files that are not javascript, are not included as such (included:false)

**Comment by mcastre** [comment]
@witwit I tried your fix and im still getting that error. I'm on v1.0.0. Should I try updating from that?
