### ISSUE TITLE
No stdout option

### ISSUE THREAD

**Issue by simonzack** [karma-runner/karma#1314]
I'm doing `karma start` and `karma run` in the same process. Both print the test results to stdout, which is rather annoying. Can there be an option to disable `runner.js`'s stdout?

I'm monkey-patching `http.request` right now which is rather ugly.

**Comment by freethejazz** [comment]
I would just redirect the output of one of the two processes to `/dev/null`. That would look like:
```
karma start > /dev/null
```

This is a pretty standard "unixy" way of dealing with output of programs and is quite powerful. For more info on this approach, look for resources explaining stdout redirection in linux (that's what the > is for)

**Comment by simonzack** [comment]
I'm running it on the same process.

**Comment by freethejazz** [comment]
I'm not an expert on these things, but my understanding of a process is that is a running instance of some program. By that definition, `karma start` and `karma run` are two separate instances of a running program and would thus each have their own process.

How are you running the two commands?

**Comment by simonzack** [comment]
I'm using the api.

**Comment by simonzack** [comment]
I ended up doing the ajax request myself, the runner api is really unfriendly, with `process.exit` and stdout prints.

**Comment by Dignifiedquire** [comment]
The node api was never designed to be feature complete. If you have concrete suggestions please file a new issue and/or feel free to submit a PR with the methods you are looking for.
