### ISSUE TITLE
Parallel builds failing

### ISSUE THREAD

**Issue by Krinkle** [karma-runner/karma#1321]
I'm frequently running into issues where browsers are not connected according to Karma.

While I'm not certain what the cause is, I suspect it might be that things don't work well when multiple browsers share the same Xvfb window.

Here's a snapshot of a scenario that happens on a daily base and been subject of false build failures for the past few days. Jenkins has a pool of a dozen slave servers. Most jobs allow concurrency, including projects using `npm test`. An Xvfb display at port `:94` is maintained by a central deamon on each server.

I did a controlled experiment and ran these two builds ran in parallel on the same (otherwise idle) server. I can consistently reproduce this.

Concurrency between PhantomJS instances are never an issue (Karma supports multiple instances of itself just fine, it automatically finds a different port for its web server). It only happens with Chromium and/or Firefox and typically only when another build ran concurrently on the same server.

The only common element I suspect is Xvfb. However, as I understand it, even in the same build Karma launches browsers in parallel. Hence, I'm not certain that that is the problem.

I read comments from @vojtajina in various places noting that browsers need focus in order to get CPU. That makes sense, but that would suggest browsers can't be in parallel on the same display. Yet, when I run these on Mac OS X without Xvfb, it starts Chrome and Firefox  on the same monitor and runs the tests without any issues (Karma seems to default to launching them in the background behind the terminal. I like that, but I do wonder whether them not having focus is an issue).

I filed #1320 about having Karma support Xvfb so that it can start its own display for each browser. Because if that's the problem indeed, then starting Xvfb and exporting a `DISPLAY` variable is not sufficient to use Karma with multiple browsers.

Jenkins build 406 @ integration-slave1010:

```
06:48:01 Running "karma:main" (karma) task
06:48:02 WARN [karma]: Port 9876 in use
06:48:02 INFO [karma]: Karma v0.12.31 server started at http://localhost:9877/
06:48:02 INFO [launcher]: Starting browser PhantomJS
06:48:03 INFO [PhantomJS 1.9.8 (Linux)]: Connected on socket OKJPCr1rqy4-vNZU5Jcw with id 34649342
06:48:03 .....................................
06:48:03 PhantomJS 1.9.8 (Linux): Executed 37 of 37 SUCCESS (0.069 secs / 0.069 secs)
06:48:04 
06:48:04 =============================== Coverage summary ===============================
06:48:04 Statements   : 96.88% ( 248/256 )
06:48:04 Branches     : 93.59% ( 146/156 )
06:48:04 Functions    : 100% ( 33/33 )
06:48:04 Lines        : 96.88% ( 248/256 )
06:48:04 ================================================================================
06:48:04 
06:48:04 Running "karma:jquery" (karma) task
06:48:04 WARN [karma]: Port 9876 in use
06:48:04 INFO [karma]: Karma v0.12.31 server started at http://localhost:9877/
06:48:04 INFO [launcher]: Starting browser PhantomJS
06:48:04 INFO [PhantomJS 1.9.8 (Linux)]: Connected on socket Knuziptm4yrj5aEI5JzP with id 92943452
06:48:04 .....................................
06:48:04 PhantomJS 1.9.8 (Linux): Executed 37 of 37 SUCCESS (0.071 secs / 0.066 secs)
06:48:04 
06:48:04 Running "karma:other" (karma) task
06:48:04 INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
06:48:04 INFO [launcher]: Starting browser Chrome
06:48:04 INFO [launcher]: Starting browser Firefox
06:48:57 INFO [Chromium 40.0.2214 (Ubuntu)]: Connected on socket u8KxRXEkWKwEmhRV5KAP with id 36808005
06:48:57 .....................................
06:48:57 Chromium 40.0.2214 (Ubuntu): Executed 37 of 37 SUCCESS (0.139 secs / 0.125 secs)
06:49:34 WARN [launcher]: Firefox have not captured in 90000 ms, killing.
06:49:36 WARN [launcher]: Firefox was not killed in 2000 ms, sending SIGKILL.
06:49:39 INFO [launcher]: Trying to start Firefox again (1/2).
06:50:58 INFO [Firefox 35.0.0 (Ubuntu)]: Connected on socket 2azAnrpEBjqQpYiZ5KAQ with id 17076815
06:50:59 .....................................
06:50:59 Firefox 35.0.0 (Ubuntu): Executed 37 of 37 SUCCESS (0.12 secs / 0.1 secs)
06:50:59 TOTAL: 74 SUCCESS
06:50:59 
06:50:59 Done, without errors.
```

Jenkins build 407 @ integration-slave1010:

```
06:48:01 Running "karma:main" (karma) task
06:48:02 INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
06:48:02 INFO [launcher]: Starting browser PhantomJS
06:48:03 INFO [PhantomJS 1.9.8 (Linux)]: Connected on socket V-Z-kOOSzAjbdjZd5Ja1 with id 38154904
06:48:03 .....................................
06:48:03 PhantomJS 1.9.8 (Linux): Executed 37 of 37 SUCCESS (0.079 secs / 0.075 secs)
06:48:03 
06:48:03 =============================== Coverage summary ===============================
06:48:03 Statements   : 96.88% ( 248/256 )
06:48:03 Branches     : 93.59% ( 146/156 )
06:48:03 Functions    : 100% ( 33/33 )
06:48:03 Lines        : 96.88% ( 248/256 )
06:48:03 ================================================================================
06:48:03 
06:48:03 Running "karma:jquery" (karma) task
06:48:03 INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
06:48:03 INFO [launcher]: Starting browser PhantomJS
06:48:04 INFO [PhantomJS 1.9.8 (Linux)]: Connected on socket ipvyp94Zmfl7jrJx5Jvm with id 10701783
06:48:04 .....................................
06:48:04 PhantomJS 1.9.8 (Linux): Executed 37 of 37 SUCCESS (0.068 secs / 0.073 secs)
06:48:04 
06:48:04 Running "karma:other" (karma) task
06:48:04 WARN [karma]: Port 9876 in use
06:48:04 INFO [karma]: Karma v0.12.31 server started at http://localhost:9877/
06:48:04 INFO [launcher]: Starting browser Chrome
06:48:04 INFO [launcher]: Starting browser Firefox
06:48:57 INFO [Chromium 40.0.2214 (Ubuntu)]: Connected on socket VhQegjAZ1qoZ1xqI5KAe with id 35868359
06:48:57 .....................................
06:48:57 Chromium 40.0.2214 (Ubuntu): Executed 37 of 37 SUCCESS (0.168 secs / 0.151 secs)
06:49:34 WARN [launcher]: Firefox have not captured in 90000 ms, killing.
06:49:36 INFO [launcher]: Trying to start Firefox again (1/2).
06:50:58 INFO [Firefox 35.0.0 (Ubuntu)]: Connected on socket _E-x_UXTwPmfGSko5KAf with id 18596356
06:50:58 .....................................
06:50:58 Firefox 35.0.0 (Ubuntu): Executed 37 of 37 SUCCESS (0.099 secs / 0.085 secs)
06:50:58 TOTAL: 74 SUCCESS
06:50:58 
06:50:58 Done, without errors.
```

Thanks!

**Comment by Krinkle** [comment]
I've further investigated, trying to narrow it down. See https://phabricator.wikimedia.org/T90673#1073556.

Merely having different browsers (e.g. Firefox and Chrome) sharing an Xvfb display is not a problem. At least not consistently. Running multiple Karma instances, each launching concurrent browsers wasn't a consistent problem, either.

But starting the Karma more spaced out from one another (like a realistic continuous integration scenario, where builds start any time), disconnects became a common observation. In my simulations, each time I started more than 3 instances where each started 2-3 seconds after the previous one, Firefox would get disconnected.

The concurrency or load is not an issue as I've run as much as 13 concurrent instances of Karma, each launching Chromium and Firefox, with no sweat. But those were started around the same time (before any started launching browsers).

Any ideas for how to debug this further? I've reproduced it with logLevel=DEBUG but nothing stood out to me in the output.
https://phabricator.wikimedia.org/P338
```
................................WARN [Firefox 36.0.0 (Ubuntu)]: Disconnected (1 times), because no message in 10000 ms.
Firefox 36.0.0 (Ubuntu): Executed 0 of 0 DISCONNECTED (10.003 secs / 0 secs)
```

**Comment by pauldraper** [comment]
I've had similar problems with xvfb before, but they were because I ran multiple *xvfb* sessions, not multiple browsers in the same session.

xvfb-run has a race conditions when starting sessions in parallel. http://stackoverflow.com/questions/30332137/xvfb-run-unreliable-when-multiple-instances-invoked-in-parallel

**Comment by Krinkle** [comment]
Solution:

* Use separate Xvfb instances.
* Or; Use `--headless` for one of the browsers, such as Chrome, which avoids the issue.
