### ISSUE TITLE
Update Node.JS to the latest stable version (v0.12)

### ISSUE THREAD

**Issue by stephenjwatkins** [karma-runner/karma#1328]
The latest stable Node.JS is at [v0.12](http://blog.nodejs.org/2015/02/06/node-v0-12-0-stable/). Karma should be updated to support this latest stable Node version.

**Comment by ilanbiala** [comment]
+1.

**Comment by akiokajima** [comment]
+1.

**Comment by tophallen** [comment]
+1.

**Comment by JT703** [comment]
+3 (me and my team)

**Comment by Krinkle** [comment]
#1304

**Comment by interactionist** [comment]
+2 (me and my office dog)

**Comment by nfantone** [comment]
+1 to this.

**Comment by leachryanb** [comment]
+1

**Comment by NateRedding** [comment]
+1

**Comment by OV2012** [comment]
+1

**Comment by yngvebn** [comment]
+1!

**Comment by pisquared** [comment]
+1

**Comment by mikeblakeuk** [comment]
+1

**Comment by macqm** [comment]
+1

**Comment by bartread** [comment]
+6 (my team and I)

**Comment by mr-moon** [comment]
+3

**Comment by alrouen** [comment]
+1

**Comment by davepoon** [comment]
++1

**Comment by joerideg** [comment]
Hi guys,
I see that the commit to up the supported nodejs version is there.
Any idea when this will be released?
It is currently a blocker for my team as we need to enforce NodeJS 0.12.x

regards,
Joeri

**Comment by fredtma** [comment]
+1

**Comment by PyroSA** [comment]
+1

**Comment by raikoroje** [comment]
+1

**Comment by aMarCruz** [comment]
+++1

**Comment by AaronBuxbaum** [comment]
+1 -- it works if you pull from master, but it'd be much better if a new version could be cut (`v0.12.32`)...

**Comment by dx9** [comment]
+1

**Comment by hao1939** [comment]
+1, any release date?

**Comment by tspratt** [comment]
+1

**Comment by dsge** [comment]
+1

**Comment by goodbomb** [comment]
+1

**Comment by astreate** [comment]
+1

**Comment by kuldarim** [comment]
+1

**Comment by Dignifiedquire** [comment]
We will release a new version with fixed engine support in the next couple of days, promised. 
There will be a stable release supporting `0.8`, `0.10`, `0.12` and `iojs > 2.0` and an unstable release which will drop the `0.8` support as it will feature connect3 which drops support for `0.8`. 
I'm very sorry for the long wait, and hope to avoid any long running issues like that in the future. 
Thanks for understanding.
