### ISSUE TITLE
Fatal error: Cannot call method 'ele' of null

### ISSUE THREAD

**Issue by dsuckau** [karma-runner/karma#1350]
Hey,

I'm using Karma with WebDriver since many months and generally it works very good. But from time to time I get the following error:

    Fatal error: Cannot call method 'ele' of null

The full output is:

    Running "karma:remote" (karma) task
    INFO [karma]: Karma v0.12.31 server started at http://192.168.2.54:9876/
    INFO [launcher]: Starting browser firefox via Remote WebDriver
    INFO [launcher]: Starting browser chrome via Remote WebDriver
    INFO [launcher]: Starting browser internet explorer via Remote WebDriver
    INFO [launcher]: Starting browser internet explorer via Remote WebDriver
    INFO [launcher]: Starting browser internet explorer via Remote WebDriver
    INFO [framework.browserify]: 184045 bytes written (0.68 seconds)
    INFO [framework.browserify]: bundle built
    INFO [Firefox 24.0.0 (Windows 7)]: Connected on socket dJLC290KOFqmv1t5kAgg with id 60146163
    INFO [IE 9.0.0 (Windows 7)]: Connected on socket SEhGqXY1etmtjCdrkAgh with id 48264404
    Firefox 24.0.0 (Windows 7): Executed 1 of 1 SUCCESS (0.005 secs / 0 secs)
    Chrome 41.0.2272 (Windows 7): Executed 1 of 1 SUCCESS (0.004 secs / 0.001 secs)
    IE 10.0.0 (Windows 7): Executed 1 of 1 SUCCESS (0.014 secs / 0 secs)
    IE 11.0.0 (Windows 7): Executed 1 of 1 SUCCESS (0.009 secs / 0 secs)
    IE 9.0.0 (Windows 7): Executed 0 of 1 SUCCESS (0 secs / 0 secs)
    Fatal error: Cannot call method 'ele' of null

My dependencies:

    ...
    "grunt-karma": "0.10.1",
    "karma-browserify": "4.0.0",
    "karma-coverage": "0.2.6",
    "karma-junit-reporter": "0.2.2",
    "karma-mocha": "0.1.10",
    "karma-phantomjs-launcher": "0.1.4",
    "karma-webdriver-launcher": "1.0.1",
    ...

My config:

    // Common options
    options: {
        files: [
            '<%= dir.unit %>/**/*.js'
        ],
        singleRun: true,
        hostname: getIpAddress(), // Just returns my local network IP
        frameworks: [
            'mocha',
            'browserify'
        ],
        reporters: [
            'progress',
            'junit',
            'coverage'
        ],
        preprocessors: {
            '<%= dir.unit %>/**/*.js': [
                'browserify'
            ]
        },
        coverageReporter: {
            reporters: [
                {
                    type: 'html',
                    dir: '<%= dir.coverage %>'
                },
                {
                    type: 'cobertura',
                    dir: '<%= dir.cobertura %>'
                }
            ]
        },
        browserify: {
            transform: [
                'browserify-istanbul'
            ]
        },
        customLaunchers: getCustomLaunchers(), // Just returns my WebDriver launcher config
        captureTimeout: 120000
    },

    // Configuration for unit tests on local machine
    local: {
        browsers: [
            'PhantomJS'
        ],
        junitReporter: {
            outputFile: '<%= dir.junit %>/unit-local.xml'
        }
    },

    // Configuration for unit tests on remote machines
    remote: {
        browsers: [
            'FF_WIN7',
            'CHROME_WIN7',
            'IE9_WIN7',
            'IE10_WIN7',
            'IE11_WIN7'
        ],
        junitReporter: {
            outputFile: '<%= dir.junit %>/unit-remote.xml'
        }
    }

Does anyone have an idea? The behavior is really random, most of the times it works with the next try. But its really a problem due to I have integrated the task in Jenkins and it will stop at this point.

Thanks a lot

**Comment by Dignifiedquire** [comment]
This sounds like mocha is actually failing here, not a 100% sure though. Is the referenced `ele` something that you use in your code/test code?
