### ISSUE TITLE
command line I/F

### ISSUE THREAD

**Issue by koba04** [karma-runner/karma#1351]
Currently, karma doesn't export `karma` command.
You recommend to install `karma-cli` locally to the project in case of `npm test`.
This is why It's for separation of concerns. #1078 #1322 

But, some documents describe using `./node_modules/karma/bin/karma` now.

https://github.com/karma-runner/karma/blob/master/docs/plus/02-travis.md
https://github.com/karma-runner/karma/blob/master/docs/plus/04-semaphore.md

In addition, `karma-cli` specifies the `preferGlobal`.
https://github.com/karma-runner/karma-cli/blob/master/package.json#L41

I feel that there is no consistency.

## Solution
1. Export `karma` command and treats `karma-cli` as just global command I/F. (+1)
1. Remove `bin/karma` from this repository and remove the `preferGlobal` from `karma-cli`.

Thank you.

**Comment by peter-mouland** [comment]
but running `./node_modules/karma/bin/karma start xx.js` does work. so having the `bin/karma` makes sense.

I would prefer to keep `bin/karma` and add this to the bin object within karma's package.json.  This would mean that in my package.json `scripts.test` i could write write `karma start xx.js`.

**Comment by koba04** [comment]
I agree with @peter-mouland.
I hope `bin/karma` is specified in `package.json`'s `bin` field.

**Comment by koba04** [comment]
@Dignifiedquire Great! I'm looking forward to fixing this :smile:
