### ISSUE TITLE
Fatal error: Line must be greater than or equal to 1, got 0

### ISSUE THREAD

**Issue by blacksonic** [karma-runner/karma#1354]
When i have error in ```beforeEach``` of Mocha i get this error out of Karma. Im testing AngularJs project and the error is emitted inside an ```inject``` function call.

**Comment by blacksonic** [comment]
tried it with a simple ```beforeEach``` with a single line that throws an ```Error``` same issue. It is not related to Angular.

**Comment by miljonaarimake** [comment]
+1

**Comment by maksimr** [comment]
relates https://github.com/karma-runner/karma/pull/1098

**Comment by Dignifiedquire** [comment]
Closing in favor of #1274
