### ISSUE TITLE
PathTooLongException on windows because of node dependency directory tree

### ISSUE THREAD

**Issue by Zazcallabah** [karma-runner/karma#1362]
The node module chokidar (in package.json: "chokidar": ">=0.8.2") added a dependency on 'anymatch' in december, right before their 0.12.6 release. (https://github.com/paulmillr/chokidar/commit/1b9a73d6793b40b2189b525c2bdd8a007158a2d9)

This generates the following node dependency directory tree (just the deepest one I found)
karma\node_modules\chokidar\node_modules\anymatch\node_modules\micromatch\node_modules\
regex-cache\node_modules\benchmarked\node_modules\file-reader\node_modules\read-yaml\node_modules\js-yaml\node_modules\argparse\node_modules\
lodash

Which is enough characters to make it very troublesome to handle on windows. Would it be possible to explicitly specify the chokidar version to 0.12.5?

**Comment by codecadwallader** [comment]
I am also encountering this issue.

**Comment by Dignifiedquire** [comment]
What version of npm are you on? The latest versions of npm do a good job of deduping things to avoid these kinds of issues.

**Comment by codecadwallader** [comment]
npm v2.5.1

**Comment by Dignifiedquire** [comment]
@codecadwallader could you try
a) running `npm dedupe` and
b) upgrading to npm@2.9 and do a fresh install of your dependencies 
and let me know if this solves anything or if the issue is still the same

**Comment by codecadwallader** [comment]
@Dignifiedquire Thanks for the suggestions.  I have upgraded to npm@2.9.1, and have been running dedupe's all along.  dedupe definitely helps, but only if another package happens to have the same internal dependencies.

chokidar still has some pretty lengthy paths, for example: 

\node_modules\karma\node_modules\chokidar\node_modules\anymatch\node_modules\micromatch\node_modules\regex-cache\node_modules\is-equal-shallow\node_modules\is-primitive

FWIW: My workaround has been to explicitly add dependencies on those internal packages (e.g. chokidar, anymatch, micromatch, etc.) which causes npm to flatten the hierarchy enough for it to work.

**Comment by Dignifiedquire** [comment]
Not the greatest situation, but at least you got it to work. It might make sense to file an issue with npm a swell as with chokidar to get some input from their sides, as from the karma side we can't do a whole lot right now :/

**Comment by wesleycho** [comment]
This might not really be an issue anymore with npm 3.

**Comment by dignifiedquire** [comment]
@wesleycho you are right upgrading to npm@3 should solve this
