### ISSUE TITLE
Code coverage for child Project

### ISSUE THREAD

**Issue by rohitagg28** [karma-runner/karma#1367]
I am having two projects on my machine named Proj1 and Proj2 using Require.js and Jasmine for the test-cases .
The Proj2 is having dependencies(library files,modules) on Proj1 ,so Proj2 is child node of Proj1 .

I have got the code-coverage of Proj1 by making the test-main.js and karma.conf.js files in it and run  karma from terminal .

But now I want the code-coverage of Proj2 ,so I make test-main.js and karma.conf.js files in it but as its having the dependecies on Proj1 , so that dependent files are not getting when I ran karma on terminal . So how should I include/link the Proj1 files with Proj2 and get the code-coverage .

**Comment by Dignifiedquire** [comment]
This depends a lot on how you actually include the files from Proj1 into Proj2. The simplest way that I can imagine is to put the `karma.conf` of Proj2 into the top level folder and reference things in a nested way.

**Comment by Dignifiedquire** [comment]
For questions and support please use the mailing list or Gitter. The issue tracker is for bug reports and feature discussions only.
