### ISSUE TITLE
Can't open browsers installed in user's Application directory on OSX

### ISSUE THREAD

**Issue by natecavanaugh** [karma-runner/karma#1375]
I see in the launcher files for [Chrome](https://github.com/karma-runner/karma-chrome-launcher/blob/7f32b59d61232f3f377cc982975eef748bccdc11/index.js#L41-L76) and Firefox there are some lookups for both Windows and Linux to get the correct browser. However, with OSX, it's always being hardcoded to /Applications.
While I know this can be worked around by setting the CHROME_BIN and FIREFOX_BIN to the users Application directory, I think it's a common enough scenario that I imagine the launchers should at least attempt to see if it exists in ~/Applications first.

(As a side note, the files seem a little inconsistent in how they're looking up the different browsers, Opera doesn't appear to try to look up for any of the systems).

Is this something you guys would think about fixing? (Also not sure if this is the right place, or if I should file separate issues on each launcher repo?)

**Comment by Dignifiedquire** [comment]
Hey, thanks for the report, but can you please repost it here: https://github.com/karma-runner/karma-chrome-launcher/issues. There were also some discussions around path issues on there, if I remember correct.
