### ISSUE TITLE
Node 0.12 support justifies a new version

### ISSUE THREAD

**Issue by mischkl** [karma-runner/karma#1378]
The NPM package v0.12.31 contains the the following in its package.json:

```js
  "engines": {
    "node": "~0.8 || ~0.10"
  },
```

This causes a warning to be shown whenever karma is installed on node >0.10 

Meanwhile support for the node 0.12 is already fixed in the github repo:

```js
  "engines": {
    "node": ">=0.8 <=0.12",
    "iojs": "~1"
  },
```

Please increment the version number and publish the new version to NPM as soon as possible. The current state with the warning looks kind of scary. Maybe not top prio but an easy fix. ;)

**Comment by vvakame** [comment]
:+1: please publish to npm!

**Comment by laco0416** [comment]
:+1:

**Comment by Dignifiedquire** [comment]
@maksimr @vojtajina is there any specific reason no new release for this has been cut yet?

**Comment by rfink** [comment]
+1

**Comment by maksimr** [comment]
@Dignifiedquire build script is broken :(

Now project lead @zzo

**Comment by Dignifiedquire** [comment]
Ah right, that explains it, @zzo any chance we can get that script running again, and or that you can publish a new version/give some of us the ability to manually publish a new version in the meantime?

**Comment by nmccready** [comment]
![bueller](https://cloud.githubusercontent.com/assets/583593/7474175/a70f6a52-f30d-11e4-80e8-b9dd78d4f257.gif)

**Comment by zzo** [comment]
Sorry guys am on it - having problems with the auto-release system so I'll
try to release this one manually - I'm sure nothing will go wrong :)
thanks,
  Mark

**Comment by nmccready** [comment]
@zzo thanks for the reply. Not sure if this is related or not (requires a new issue). master is hanging against io.js 1.8.1 and likely (2.0.0).

**Comment by demisx** [comment]
+1 for Node 0.12

**Comment by zzo** [comment]
Anyone have any idea why this is?  Sounds like a new issue.
thanks!
  Mark

**Comment by noherczeg** [comment]
Can we help somehow? If I'm not mistaken there new release isn't public yet, but if there is anything that we could help with to make it happen please let us know @zzo !

**Comment by Dignifiedquire** [comment]
0.12.33 should be on npm allowing for node 0.12 and iojs. Please comment and or reopen if it does not work.

**Comment by noherczeg** [comment]
Works for me, thank you very much! :)
