### ISSUE TITLE
Add .config/karma.conf.js to the default lookup path

### ISSUE THREAD

**Issue by shannonmoeller** [karma-runner/karma#1387]
As more and more tools have become best-practice when authoring npm modules, from `package.json` to `.*rc` to `*file.js`, the root directory of projects has become a very loud place. This dot-noise pushes README content farther and farther down the main page of git repos.

![screenshot 2015-05-01 21 41 51](https://cloud.githubusercontent.com/assets/155164/7439468/e8f2ff9e-f04a-11e4-8c1b-4248379053e9.png)

What if the above could optionally be simplified to the following?

![screenshot 2015-05-01 21 50 12](https://cloud.githubusercontent.com/assets/155164/7439513/179455c2-f04c-11e4-9577-c3b73c2b01c3.png)

This is a simple example and that's already about a 30% vertical space savings. I started the conversation over in the [npm repo](https://github.com/npm/npm/issues/8159), but I'm also submitting issues to the `findup`, `findup-sync`, `travis-ci` and `zuul` repos.

**Comment by Dignifiedquire** [comment]
What exactly are you asking? You can do this today with karma, just pass the `configFile` on  the command line and up you go.

**Comment by hax** [comment]
I think what this issue ask is make karma and many other utils/services add `.config` to lookup paths by default.

**Comment by shannonmoeller** [comment]
@Dignifiedquire I understand that the path can be configured, but as @hax so aptly stated, this is about adding `.config` to the default lookup paths. This request has been made of several other projects and many have stated they're waiting to see what others do. At this point, I'm working in my spare time to affect the change, prove it works without breaking anything, and submit PRs.

**Comment by Dignifiedquire** [comment]
@shannonmoeller I see. In general I don't mind adding it to the default lookup path. If someone provides a pr for this I'll consider it.

**Comment by shannonmoeller** [comment]
Thanks! PR forthcoming.

**Comment by cvburgess** [comment]
Any reason the config object can't be optionally put in package.json? Web pack supports this and so does bower IIRC
