### ISSUE TITLE
WARN [PhantomJS 1.9.8 (Linux)]: Disconnected (1 times), because no message in 10000 ms.

### ISSUE THREAD

**Issue by joseph-jja** [karma-runner/karma#1388]
I am getting this error and tracked it down to karma karma/lib/browser.js The issue is that when this fails and the message comes up the terminal is no longer useful.  This is also an issue when run on jenkins as it causes jenkins to hang until the process is killed manually.  Usually that means ps -ef |grep grunt or lsof |grep karma

This is also because some test is bad.  

PhantomJS 1.9.8 (Linux) ERROR: [36m'There is no timestamp for <filename>

WARN [PhantomJS 1.9.8 (Linux)]: [39mDisconnected (1 times), because no message in 10000 ms.

**Comment by nmccready** [comment]
I am seeing this on master when trying to run against io.js 1.8.1 .

**Comment by maksimr** [comment]
@joseph-jja Thanks

What is expected behavior in this case?

**Comment by joseph-jja** [comment]
I would expect it to die and exit normally. Also a more useful message.  I've added jshint to the tests and that forces developers to have proper syntax, but still tests fail, and don't always return the console back to the user.

**Comment by devoto13** [comment]
This sounds like a valid bug to me. However, there have been many changes to the libraries since it was reported. Please open a new issue including a minimal reproduction if you still experience this issue.
