### ISSUE TITLE
Can browsers connect to Karma server from a remote machine?

### ISSUE THREAD

**Issue by youssef06** [karma-runner/karma#1396]
I have setup testing locally using Karma, Mocha and Chai, whenever I run
```sh
$ karma start
```
I get a webserver running locally:
```sh
$ INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
```
I can then go to http://localhost:9876 using any browser I have and see how my tests run on that browser.

Is it possible to launch karma testing on a remote server so me and my collegues can access it with various browsers, without each one of us having to run karma locally?

**Comment by maksimr** [comment]
@youssef06 Yes.

Karma web server run with IP `0.0.0.0` This means listen on every available network interface.
For accessing you can use public IP/machine IP/host name

Thanks!

**Comment by youssef06** [comment]
Thx @maksimr 
It turned out i just had to open port 9876 on the server, then me and my colleagues were able to access the tests with:

http://url.test.server:9876
