### ISSUE TITLE
Error Reporting Slow With Source Maps

### ISSUE THREAD

**Issue by minznerjosh** [karma-runner/karma#1398]
I'm working on a fairly large app (over 2300 unit tests) that uses browserify and babel with source maps enabled. I'm estimating that the source maps are probably > 1 MB in size.

When an assertion fails or an exception is thrown, it takes a *really* long time for the error to log to the console. If the stack is long enough, it can take upwards of 30 seconds per ```it()``` block to see the message in the console.

I was looking through the Karma source, and it looks like, even if the entire stack comes from the same file (as is the case when using browserify,) the [source map is re-parsed for every line in the stack trace message](https://github.com/karma-runner/karma/blob/v0.12.31/lib/reporter.js#L36-L48).

I was thinking performance could be improved if the ```SourceMapConsumer``` for each file was cached (probably as a property on the ```file``` object.) I'd be happy to submit a PR for this, but I can't figure out where the [```file```'s ```sourceMap```](https://github.com/karma-runner/karma/blob/v0.12.31/lib/reporter.js#L48) property is assigned. Could somebody point me in the right direction?

Thanks!

**Comment by maksimr** [comment]
@minznerjosh Thanks

This issue should be fixed by this [PR](https://github.com/karma-runner/karma/pull/1232)

**Comment by minznerjosh** [comment]
@maksimr Well look at that! Thanks!
