### ISSUE TITLE
errors.angularjs.org URL incredibly long.

### ISSUE THREAD

**Issue by lethjakman** [karma-runner/karma#1399]
I've attempted to change the log level in order to get rid of the http://errors.angularjs.org/1.3.14/$injector/modulerr?<crazy_long_params_here> URL, but I've had no luck. Is there an option to minify or remove this URL when running tests through karma? It's including many full file paths which happen to be very long making the tests almost unreadable.

**Comment by maksimr** [comment]
@lethjakman totally agree, but really is it issue of karma?
I [created](https://github.com/angular/angular.js/issues/10590) the issue in angular.js about it

**Comment by lethjakman** [comment]
Ahh maybe it isn't a karma. I'll go weigh in there, thank you.

**Comment by Dignifiedquire** [comment]
Closing as it's not an issue with karma itself.
