### ISSUE TITLE
npm install WARN message

### ISSUE THREAD

**Issue by MetaMemoryT** [karma-runner/karma#1402]
with npm install of karma, npm warns:

```
npm WARN engine karma@0.12.31: wanted: {"node":"~0.8 || ~0.10"} (current: {"node":"0.12.0","npm":"2.7.2"})
```

**Comment by zzo** [comment]
#merge

**Comment by maksimr** [comment]
Will be fixed in [new version](https://github.com/karma-runner/karma/commit/29620de56d4796e25dd9202ce2994602a07379be) karma
