### ISSUE TITLE
Move all support to gitter and the mailing list

### ISSUE THREAD

**Issue by Dignifiedquire** [karma-runner/karma#1414]
The issue tracker is overflowing, and not at least because there are a lot of support questions around here. 

I would suggest closing those, and adding a friendly comment pointing people to 

* [Gitter](https://gitter.im/karma-runner/karma) 
* [StackOverflow](http://stackoverflow.com/questions/tagged/karma-runner)
* [FAQ](http://karma-runner.github.io/0.12/intro/faq.html)

Also we should try to update the FAQ with questions that are asked more than once while doing this.

What do you think @karma-runner/contributors ?

**Update** Add FAQ and StackOverflow, drop the mailing list

**Comment by aymericbeaumet** [comment]
:+1: There are also a lot of recurring questions, we could create a FAQ on the website.


—
Aymeric Beaumet

**Comment by Dignifiedquire** [comment]
I've dropped the mailinglist from my proposal as from my experience I feel that Gitter and StackOverflow are a much better medium for handling support, at least as the official pointers.

**Comment by maksimr** [comment]
cons of Gitter - it is poorly indexed by search engines.

**Comment by Dignifiedquire** [comment]
> cons of Gitter - it is poorly indexed by search engines.

That is true :/

**Comment by Dignifiedquire** [comment]
React moved to using [discourse](http://www.discourse.org/) for support, which might be an even better solution, as it does get properly indexed but has a much better interface and better ways for realtime interactions

**Comment by aymericbeaumet** [comment]
> Discourse

+1

**Comment by Dignifiedquire** [comment]
For now using the mailing list and gitter. Happy to revisit with better options when someone has time to set it up
