### ISSUE TITLE
0.12.32 Is missing?

### ISSUE THREAD

**Issue by kahnjw** [karma-runner/karma#1415]
Am I missing something or is the latest release of karma missing from github. Npm has 0.12.32, but the latest github tag is 0.12.31?

https://www.npmjs.com/package/karma

https://github.com/karma-runner/karma/releases

**Comment by Dignifiedquire** [comment]
We are fighting with our release bot,  so maybe he messed up the last release as well :(

**Comment by kahnjw** [comment]
Hm ok. Yeah caused me some confusion. The weirdest part is that the master package.json is still 0.12.31. So not only did the tag never get pushed back to the repo, neither did the package.json version bump/changelog commit. https://github.com/karma-runner/karma/blob/master/package.json

**Comment by Dignifiedquire** [comment]
Sorry about that, hopefully this will be fixed soon.

cc @zzo any idea what went wrong there?

**Comment by kahnjw** [comment]
No worries. I figured it out pretty fast. Was just confused for a minute. Thanks for the great project!

**Comment by zzo** [comment]
It's up now - sorry for the delay

**Comment by zzo** [comment]
@Dignifiedquire do you know what went into .32 /  what would cause this?

**Comment by Dignifiedquire** [comment]
@zzo No idea, the version doesn't even exist in master :( So I suggest we cut a release `0.12.33` with everything that is now in master

**Comment by Dignifiedquire** [comment]
Probably this is related to the messed up `canary` branch and those beta releases there

**Comment by zzo** [comment]
There was that one patch to move the loading of the plugins further down -
that must be it?

**Comment by Dignifiedquire** [comment]
0.12.33 should be marked as latest and be available on npm, so closing this for now :)
