### ISSUE TITLE
Code style ES2015 and beyond

### ISSUE THREAD

**Issue by dignifiedquire** [karma-runner/karma#1417]
> **Warning** the following content might be viewed as disruptive as it challenges currently used standards. 

In most of my projects I've started moving the code use [babel](http://babeljs.io/) to leverage all new and nice things that ES2015 (was ES6) and some additional proposals bring. For me this brought a lot of clarity and general better code in every case. At the same time I've been removing semicolons. [It's](http://blog.izs.me/post/2353458699/an-open-letter-to-javascript-leaders-regarding) [fine.](http://inimino.org/~inimino/blog/javascript_semicolons) [Really!](https://github.com/maxogden/messages/issues/18) making the overall code even more clean. 

As I know though these are some very personal preferences (at least the semicolons) so what do you think about it? Do you care or do you just want karma to work no matter what style it is written in :wink: 

// cc @karma-runner/contributors

**Comment by Dignifiedquire** [comment]
First step of moving to standard code style was done :)

**Comment by kahwee** [comment]
I was wondering about this when I was working on #2315. Babel and Standard makes such an essential combination to clean code for me.

**Comment by dignifiedquire** [comment]
Well the code base was written way before standard, ES2015 & babel came to existence. The tests I moved to use babel and refactored them somewhat but moving the main codebase will be pretty big undertaking.

**Comment by devoto13** [comment]
This is done as the codebase uses both standard and modern JS syntax (without Babel though).
