### ISSUE TITLE
why i failed to install karma on windows? 

### ISSUE THREAD

**Issue by chapgaga** [karma-runner/karma#1419]
btw, i am using win7 x64 with vs 2013

![](http://img.itc.cn/photo/jR6XkNISp1L.jpg)

http://img.itc.cn/photo/jR6XkNISp1L.jpg

details of error message here
http://pastie.org/10201538

**Comment by Dignifiedquire** [comment]
I'm not sure but it looks like socket.io fails to install, could you try installing it on its own?

**Comment by chapgaga** [comment]
@Dignifiedquire  seems you are right, i failed to install socket.io 

https://github.com/Automattic/socket.io/issues/2128

**Comment by EzraBrooks** [comment]
This appears to have been fixed quite a while ago.
