### ISSUE TITLE
socket.io.js not loaded when urlRoot is specified

### ISSUE THREAD

**Issue by tkrotoff** [karma-runner/karma#1422]
When specifying `urlRoot: '/base/'` inside karma.conf.js, Karma fails because it cannot load socket.io.js:
`WARN [web-server]: 404: /base/socket.io/socket.io.js`

socket.io.js URL is `/base/socket.io/socket.io.js` (because of urlRoot: '/base/') instead of `/socket.io/socket.io.js`. I believe socket.io.js should be independent from urlRoot (it was before?).

Specifying `urlRoot: '/base/'` was working a few days/weeks ago and is now broken. I could not find the culprit: karma is still at v0.12.31 but its multiple dependencies might have been changed.

One "hacky" way to fix this is to prepend / to `<script src="socket.io/socket.io.js">` inside [static/client.html](https://github.com/karma-runner/karma/blob/v0.12.31/static/client.html#L113).
(I don't understand why [the line below](https://github.com/karma-runner/karma/blob/v0.12.31/static/client.html#L114) `<script src="karma.js">` works without prepending /.)

**Comment by Dignifiedquire** [comment]
Thanks for reporting this, could you check which version of socket.io is installed please?

**Comment by tkrotoff** [comment]
The one from `/node_modules/karma/node_modules/socket.io` is 1.3.5 (the one from `/node_modules/browser-sync/node_modules/socket.io` is also 1.3.5).

**Comment by Dignifiedquire** [comment]
So it turns out 0.12.32 was shipping a socket.io version which we actually didn't support fully. Could you please check 0.12.33 if that solves the issue?

**Comment by tkrotoff** [comment]
Problem fixed after upgrading from 0.12.31 to 0.12.33, thx. `node_modules/karma/node_modules/socket.io` is now at 0.9.16.

**Comment by Dignifiedquire** [comment]
Great to hear
