### ISSUE TITLE
Some dependency tries to be loaded by direct URL - 0.12.32

### ISSUE THREAD

**Issue by wips** [karma-runner/karma#1424]
When installing karma 0.12.32 from npm some dependency is trying to be loaded by direct github URL:

`npm http GET https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
npm ERR! fetch failed https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
npm http GET https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
npm ERR! fetch failed https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz`

It breaks install when build machine has no access to internet and private npm is used.

**Comment by Dignifiedquire** [comment]
This is already known and we are waiting for a fix from upstream at the moment: #1366 
You can weigh in here https://github.com/Automattic/engine.io-client/issues/348 so maybe they'll fix it sooner.

**Comment by wips** [comment]
Didn't notice that. Thanks

**Comment by Ajithsou** [comment]
I am facing the same issue, any solution identified?

**Comment by BernhardRode** [comment]
Hanging on the same issue :(

**Comment by snajo** [comment]
+:100:

**Comment by adelinor** [comment]
I am facing the same issue

**Comment by Solksjaer** [comment]
I´m having the same issue here.
Installation oh karme tries to connect to the internet directly to GitHub.
Any news regarding this issue?
BTW: this issue is a known issue since September 2014 and no new release/fix available. Look at https://github.com/socketio/engine.io-client/issues/348

**Comment by estekhin** [comment]
https://github.com/socketio/engine.io-client/issues/348 seems to be closed, but not properly released.

**Comment by Igogrek** [comment]
Still having the same issue. Will it be fixed?

**Comment by eladh** [comment]
how such critical package as node-XMLHttpRequest don't get fixed for such a long time :-(

is there any workaround 


10x

**Comment by eladh** [comment]
Important update - in the latest version of Artifactory there is support for this kind of problems via the NPM/Bower 

https://www.jfrog.com/jira/browse/RTFACT-7664

**Comment by julianvmodesto** [comment]
+1! Even though it's upstream, is there anything that can be done to resolve this dependency? I'm unfamiliar with npm shrinkwrapping... does anyone know how to do this correctly for Karma?

**Comment by Dignifiedquire** [comment]
Looks like this is supposedly fixed upstream now, please try either installing karma fresh, or running `npm update` to try it out

**Comment by americoneto1** [comment]
This issue should be fixed only on next release of socket.io https://github.com/socketio/socket.io-client/issues/917

**Comment by shevatki** [comment]
If you dont fancy the latest karma version, use npm install karma@0.12.31 or any other previous version and get going.

**Comment by karsunke** [comment]
socket.io has been released (https://github.com/socketio/socket.io-client/issues/917 ist closed). 

is it possible to fix this bug now?

**Comment by Dignifiedquire** [comment]
@karsunke this should be fixed reinstall the latest version

**Comment by karsunke** [comment]
@Dignifiedquire ah thanks. I just tried it and it works!

**Comment by Dignifiedquire** [comment]
Thanks @karsunke closing this issue then :)
