### ISSUE TITLE
0.12.32 socket.io failed to proxy

### ISSUE THREAD

**Issue by boldfacedesign** [karma-runner/karma#1425]
I updated to Karma v0.12.32 and now see this error message.
```
[16:10:07] Starting Karma server...
INFO [karma]: Karma v0.12.32 server started at http://localhost:9876/__karma__/
INFO [launcher]: Starting browser PhantomJS
INFO [framework.browserify]: 1606911 bytes written (4.38 seconds)
INFO [framework.browserify]: bundle built
WARN [proxy]: failed to proxy /__karma__/socket.io/socket.io.js (connect ECONNREFUSED)
WARN [launcher]: PhantomJS have not captured in 60000 ms, killing.
INFO [launcher]: Trying to start PhantomJS again (1/2).
```
I tried using Chrome as my test browser with the same results.
I dropped back down to Karma v0.12.31 and do not get this issue.

I can post more info about my config if needed.

**Comment by Dignifiedquire** [comment]
Can you please run with log level debug and post the output?

**Comment by boldfacedesign** [comment]
I've had to reduce some of the file paths due to company privacy but I don't believe they're important.

DEBUG [plugin]: Loading plugin karma-jasmine.
DEBUG [plugin]: Loading plugin karma-jasmine-matchers.
DEBUG [plugin]: Loading plugin karma-browserify.
DEBUG [plugin]: Loading plugin karma-chrome-launcher.
DEBUG [plugin]: Loading plugin karma-html-reporter.
DEBUG [plugin]: Loading plugin karma-firefox-launcher.
DEBUG [plugin]: Loading plugin karma-less-preprocessor.
DEBUG [plugin]: Loading plugin karma-phantomjs-launcher.
DEBUG [plugin]: Loading plugin karma-coverage.
DEBUG [plugin]: Loading plugin karma-spec-reporter.
DEBUG [plugin]: Loading plugin karma-junit-reporter.
DEBUG [framework.browserify]: created browserify bundle: /var/folders/4g/j2_jcfw503v1bq5m1z_68v540000gp/T/d2ab0d6b137bebce6c8f38cc7c86c2bb5bcb491e.browserify
DEBUG [framework.browserify]: add bundle to config.files at position 4
INFO [karma]: Karma v0.12.32 server started at http://localhost:9876/__karma__/
INFO [launcher]: Starting browser PhantomJS
DEBUG [temp-dir]: Creating temp dir at /var/folders/4g/j2_jcfw503v1bq5m1z_68v540000gp/T/karma-38801695
DEBUG [launcher]: ..../node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom/bin/phantomjs /var/folders/4g/j2_jcfw503v1bq5m1z_68v540000gp/T/karma-38801695/capture.js
DEBUG [framework.browserify]: building bundle
DEBUG [framework.browserify]: adding test/spec/index.test.js to bundle
DEBUG [framework.browserify]: bundling
DEBUG [web-server]: serving: ..../node_modules/karma/static/client.html
DEBUG [web-server]: serving: ..../node_modules/karma/static/karma.js
INFO [framework.browserify]: 1606911 bytes written (4.15 seconds)
INFO [framework.browserify]: bundle built
DEBUG [watcher]: Resolved files:
	..../node_modules/jasmine-core/lib/jasmine-core/jasmine.js
	..../node_modules/karma-jasmine/lib/boot.js
	..../node_modules/karma-jasmine/lib/adapter.js
	..../node_modules/jasmine-expect/dist/jasmine-matchers.js
	/var/folders/4g/j2_jcfw503v1bq5m1z_68v540000gp/T/d2ab0d6b137bebce6c8f38cc7c86c2bb5bcb491e.browserify
	..../test/spec/index.test.js
DEBUG [proxy]: proxying request - /__karma__/socket.io/socket.io.js to localhost:8000
WARN [proxy]: failed to proxy /__karma__/socket.io/socket.io.js (connect ECONNREFUSED)
WARN [launcher]: PhantomJS have not captured in 60000 ms, killing.
DEBUG [launcher]: Process PhantomJS exited with code 0
DEBUG [temp-dir]: Cleaning temp dir /var/folders/4g/j2_jcfw503v1bq5m1z_68v540000gp/T/karma-38801695
INFO [launcher]: Trying to start PhantomJS again (1/2).
DEBUG [launcher]: Restarting PhantomJS
DEBUG [temp-dir]: Creating temp dir at /var/folders/4g/j2_jcfw503v1bq5m1z_68v540000gp/T/karma-38801695
DEBUG [launcher]: ..../node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom/bin/phantomjs /var/folders/4g/j2_jcfw503v1bq5m1z_68v540000gp/T/karma-38801695/capture.js /var/folders/4g/j2_jcfw503v1bq5m1z_68v540000gp/T/karma-38801695/capture.js
DEBUG [web-server]: serving (cached): .../node_modules/karma/static/client.html
DEBUG [proxy]: proxying request - /__karma__/socket.io/socket.io.js to localhost:8000
DEBUG [web-server]: serving (cached): ..../node_modules/karma/static/karma.js
WARN [proxy]: failed to proxy /__karma__/socket.io/socket.io.js (connect ECONNREFUSED)
^CDEBUG [framework.browserify]: cleaning up
DEBUG [launcher]: Disconnecting all browsers
DEBUG [launcher]: Process PhantomJS exited with code 0
DEBUG [temp-dir]: Cleaning temp dir /var/folders/4g/j2_jcfw503v1bq5m1z_68v540000gp/T/karma-38801695

**Comment by Dignifiedquire** [comment]
Please try again with the latest version (0.12.33) I think it should fix this issue

**Comment by boldfacedesign** [comment]
Yep all good. Test running as expected on PhantomJS.
