### ISSUE TITLE
Running karma In node for debugging purposes

### ISSUE THREAD

**Issue by tomitrescak** [karma-runner/karma#1427]
I'm trying to debug karma tests, but in order to run the debugger I need to run karma as node.js process in form "node ...." (In visual studio code). Something like "node ./lib/cli.js start" but it has no entry point for server.

Is it possible to omit the karma binary and run karma from node.js?

**Comment by maksimr** [comment]
You can use [public API](http://karma-runner.github.io/0.12/dev/public-api.html) to write own script for starting `karma`

**Comment by tomitrescak** [comment]
I managed to hook onto karma after all, through "node --debug-brk karma start", but the problem is that it's debugging karma itself and not the tests which are ran in the browser. Any who .... I'll stick yo debugging them in chrome I guess;) but if you have any idea on how to hook onto them I would appreciate that.

**Comment by Dignifiedquire** [comment]
As the tests are executed in the browser, you'll need to setup your debugger to hook into that, independently of what karma does. The node process that runs karma, has very little information about the actual execution of your tests.

**Comment by Dignifiedquire** [comment]
For questions and support please use the mailing list or Gitter. The issue tracker is for bug reports and feature discussions only.
