### ISSUE TITLE
MS Edge is detected as IE12

### ISSUE THREAD

**Issue by harmoney-nikr** [karma-runner/karma#1433]
We recently upgraded from v0.12.32 to v0.12.35. Previously Karma detected Edge as Chrome, which has now been fixed. But it's been fixed incorrectly as it's now detecting it as IE12. Edge is not IE12 and should not be detected as such.

User agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.9600`

![Screenshot](https://cloud.githubusercontent.com/assets/11603420/7949133/260b4834-09df-11e5-9f58-d299442b0b16.png)

**Comment by Dignifiedquire** [comment]
We use https://github.com/broofa/node-mime for this detection. Could you file an issue there please?

**Comment by harmoney-nikr** [comment]
Ah yes, certainly!

**Comment by harmoney-nikr** [comment]
Hmm, I assume you mean [https://github.com/3rd-Eden/useragent]?

**Comment by Dignifiedquire** [comment]
> Hmm, I assume you mean https://github.com/3rd-Eden/useragent?

Yes I do, sorry my mind always mixes mime types and useragents -.-

**Comment by nikrolls** [comment]
All good. 3rd-Eden/useragent in turn uses uaparser/uap-core, so I've [submitted a PR there](https://github.com/ua-parser/uap-core/pull/59) and Karma will get it in a future dependency update.

**Comment by harmoney-nikr** [comment]
All good. [3rd-Eden/useragent](https://github.com/3rd-Eden/useragent) in turn uses [uaparser/uap-core](https://github.com/ua-parser/uap-core), so I've [submitted a PR there](https://github.com/ua-parser/uap-core/pull/59) and Karma will get it in a future dependency update.

**Comment by Dignifiedquire** [comment]
Great, thanks :)

**Comment by mzgol** [comment]
The uap-core PR has been merged, I submitted https://github.com/3rd-Eden/useragent/issues/76 to `useragent` to get the regex database updated.

**Comment by nikrolls** [comment]
Great, thanks!

**Comment by nicolasmccurdy** [comment]
3rd-Eden/useragent 2.1.7 was just released with a fix for 3rd-Eden/useragent#76.

**Comment by Dignifiedquire** [comment]
Great, closing this then as a fresh install of karma or a simple `npm update` should pull in that version

**Comment by harmoney-nikr** [comment]
`npm update` didn't work for me (though our versions are all locked down). A fresh `npm install` worked fine however. Thanks everyone for your help!
