### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined in changeFile

### ISSUE THREAD

**Issue by cassus** [karma-runner/karma#1436]
Occurs when I save a file that is still being processed by karma-webpack preprocessor.

```
ERROR [karma]: [TypeError: Cannot read property 'length' of undefined]
TypeError: Cannot read property 'length' of undefined
    at changeFile (.../node_modules/karma/lib/file_list.js:345:33)
    at EventEmitter.<anonymous> (.../node_modules/karma/lib/watcher.js:90:17)
    at EventEmitter.emit (events.js:110:17)
    at EventEmitter.<anonymous> (.../node_modules/karma/node_modules/chokidar/index.js:136:15)
    at EventEmitter.FSWatcher._emit (.../node_modules/karma/node_modules/chokidar/index.js:149:5)
    at EventEmitter.<anonymous> (.../node_modules/karma/node_modules/chokidar/lib/nodefs-handler.js:268:12)
    at .../node_modules/karma/node_modules/chokidar/lib/nodefs-handler.js:176:13
    at Array.forEach (native)
    at StatWatcher.<anonymous> (.../node_modules/karma/node_modules/chokidar/lib/nodefs-handler.js:175:31)
    at StatWatcher.emit (events.js:110:17)
    at StatWatcher._handle.onchange (fs.js:1226:10)
```

code context:
```
    for (i = 0; i < buckets.length; i++) {
      for (j = 0; j < buckets[i].length /* Error here */; j++) {
        if (buckets[i][j].originalPath === path) {
          break outer;
        }
      }
    }
```

variables:
```
path == .../app/components/RegisterPage/__tests__/index.js
i == 5
buckets.length == 6
buckets[i] == undefined
buckets[i-1] == []
```

**Comment by Dignifiedquire** [comment]
What version are you running?

**Comment by cassus** [comment]
```
├─┬ karma@0.12.35
├─┬ karma-webpack@1.5.1
```

**Comment by Dignifiedquire** [comment]
Thanks, I'll take a look

**Comment by cassus** [comment]
I also have sometime "Some of your tests did a full page reload!" errors before this crash happens. This might be a helpful cue.

I'm still trying to isolate that error / make it somewhat reproducible.

**Comment by Dignifiedquire** [comment]
Okay thanks, I just did a basic test with https://github.com/webpack/karma-webpack/blob/master/example/karma.conf.js and that worked fine while editing the files. 
A couple more things, what editor are you using? Does this happen as well when you use `touch` instead? 
What node version are you running?

**Comment by cassus** [comment]
I'm using IntellJ but I can reliably crash karma it with
```for i in `seq 1 100`; do touch index.js && sleep 0.2; done```

```
$ node --version
v0.12.4
```

**Comment by cassus** [comment]
here is my reduced config:
```
module.exports = function(config) {
    config.set({
        browsers: ['PhantomJS'],

        basePath: __dirname + '/../',

        files: [
            'app/**/__tests__/*.js',
        ],

        preprocessors: {
            'app/**/__tests__/*.js': ['webpack'],
        },

        webpackMiddleware: {
            noInfo: true,
        },

        reporters: ['dots'],

        plugins: [
            'karma-webpack',
            'karma-phantomjs-launcher',
        ],
        webpack: {
            "debug": true,
            "devtool": "cheap-module-source-map",
            "module": {
                "loaders": [
                    {
                        "test": /\.js$/,
                        "loaders": ["babel"],
                    },
                ],
            },
        }
    })
}

```

It produces the error with an empty \__tests\__/index.js in a minute. If I require a big lib (I did ```require('react')```) then the crash happens within 10 seconds.

My command to trigger the crash is:
```./node_modules/karma/bin/karma start conf/karma.conf.js & ( cd app/components/RegisterPage/__tests__/ && for i in `seq 1 200`; do touch index.js && sleep 0.2; done )```

**Comment by Dignifiedquire** [comment]
Thanks I was able to reproduce the issue under different circumstances with the simple `touch` loop. It looks like it's an issue that the `List.refresh` method is called while already running a refresh. If you look at https://github.com/karma-runner/karma/blob/master/lib/file_list.js you can see the `TODO`s all over the place which correspond to a degree to your issue. I'm afraid it won't be a quick fix, as I probably have to refactor the whole file to make this work reliable but I'm working on it.

**Comment by cassus** [comment]
Thank you!

**Comment by davincho** [comment]
+1 I have got the same issue as @cassus

**Comment by Dignifiedquire** [comment]
@cassus getting there, #1451 should fix this issue and make file-list.js much saner :)

**Comment by Aaronius** [comment]
Thank you! I'm seeing the same issue sporadically and appreciate that you're already working on a fix.

**Comment by Dignifiedquire** [comment]
@Aaronius if you want you can try to install karma@canary which should have the fix
