### ISSUE TITLE
In case of Uncaught Error no test is marked as a failure

### ISSUE THREAD

**Issue by marfous** [karma-runner/karma#1441]
Our test started reporting "Uncaught Error: You cannot apply bindings multiple times..." which was definitely issue in our unit tests but the Karma doesn't reports any test case as a failure. Instead of that we are getting this error and the summary after that.

Would be possible to mark any test where it happens as a FAILED one? Or could the uncaught error mean something else?

**Comment by Dignifiedquire** [comment]
I'm going to need some more details, what version of Node and Karma are you running? What testing framework do you use (mocha, jasmine, qunit, ...) ?

**Comment by marfous** [comment]
Node v0.10.28, Karma v0.12.31, Jasmine v2.1.1. Let me know if anything more would help, thanks.

**Comment by marfous** [comment]
Did you get to investigation of this please? I would be able to attach output from the test run but I'm afraid that it would not help much.

**Comment by Dignifiedquire** [comment]
Sorry for the late reply. I'm not sure if there is something we can do from our side as that sounds like Jasmine wasn't able to catch the error, which in return lead to Karma not being able to report on it properly. If you could provide me with a minimal working repro I can try to take a closer look though 
Thanks

**Comment by Dignifiedquire** [comment]
I'm closing this as we are moving all support issues to gitter and the mailing list. Please feel free to ask there again with updated info and reproducible repo if possible.
