### ISSUE TITLE
Allow `config.preprocessors` paths to be generated dynamically

### ISSUE THREAD

**Issue by mystro-bryce** [karma-runner/karma#1444]
Right now in my Gruntfile I've got something along the lines of this:

    var appVersion = '2.0.5';

Which--among other things--builds my project into a folder like this:

    /app/2.0.5/scripts/file_that_should_be_tested.js

I would love to be able to use this dynamically in my `karma.conf.js` like so:

    preprocessors: {
        'app/' + appVersion + '/scripts/*.js' : 'coverage'
    }

But since the file is a JSON key, it can only be a string literal, not an expression. 

Can there be some way to allow for the full expressiveness of Node to do this?

**Comment by Dignifiedquire** [comment]
That's one of the reasons why the karma config is a javascript file and not a simple json file. You can do something like this:

```js
// Read app version from `package.json`
var pkg = require('./package.json')
var appVersion = pkg.version

module.exports = function (config) {
  var myConfig = {
    // more config
    preprocessors: {}
  }
  myConfig.preprocessors['app/' + appVersion + '/scripts/*.js'] = 'coverage'

  config.set(myConfig)
}
```
and it should work exactly as you described it

**Comment by Dignifiedquire** [comment]
For questions and support please use the mailing list or Gitter. The issue tracker is for bug reports and feature discussions only.
