### ISSUE TITLE
Docs for config need example for inclusion of libraries

### ISSUE THREAD

**Issue by anshbansal** [karma-runner/karma#1445]
I cannot find the location but I read it somewhere that the list of files / patterns to load in the browser in `karma.conf.js` i.e. the `files`  key should not have libraries. But I cannot find it in documentation about how to actually add those js files.

e.g. I need angular.js to be present so in my [karma.conf.js](https://github.com/anshbansal/linksharing2/blob/ea2cc8cb09da1783c5d01c4e847035e13377cefd/grails-app/conf/karma.conf.js) I have added it in `Files`.

It would be good to add this in the documentation.

**Comment by anshbansal** [comment]
When I debugged I found that these are actually being watched by karma for changes. Obviously that is not needed. As these libraries will not be changing.

**Comment by bganguly** [comment]
You can't use the exclude:[] option to exclude library files from being watched?

**Comment by Dignifiedquire** [comment]
Take a look at this page: http://karma-runner.github.io/0.12/config/files.html

**Comment by bganguly** [comment]
In the alternative way of specifying the files, i assume that if a property is left blank, the default value will be inferred.
So maybe the following barebones array will work?
files: [
      {'pattern':'includes/angular/angular.min.js','watched':false},
      'myTodoApp/app.js',
      'myTodoApp/directives/directives.js',
      'myTodoApp/configs/configs.js',
      'myTodoApp/controllers/authsListController.js',
      'jsUnitTests/angularUnitTests/*.js'
    ],

**Comment by anshbansal** [comment]
I understand that using watched is the way to go. Perhaps adding a sentence that for libraries this is the preferred way to add?

**Comment by Dignifiedquire** [comment]
Sure, @anshbansal feel free to send a PR with an explanation that you think would help
