### ISSUE TITLE
TypeError with io.js v2.3.0

### ISSUE THREAD

**Issue by bricss** [karma-runner/karma#1454]
```
ERROR [karma]: [TypeError: options must be a string or an object]
TypeError: options must be a string or an object
    at new WriteStream (fs.js:1798:11)
    at Object.fs.createWriteStream (fs.js:1784:10)
    at c:\Users\<username>\Documents\Aptana Studio 3 Workspace\admin-gui\node_modules\karma-html-reporter\index.js:89:22
    at FSReqWrap.oncomplete (fs.js:82:15)
.write(string, encoding, offset, length) is deprecated. Use write(string[, offset[, length]][, encoding]) instead.
```

**Comment by Dignifiedquire** [comment]
Thanks, could you provide the full `DEBUG` log please and if possible your `karma.conf`?

**Comment by bricss** [comment]
Actually this bug related to karma-html-reporter, I've created bug [issue](https://github.com/dtabuenc/karma-html-reporter/issues/26) in their repo.

It could be easily fixed by empty object in options:
```
writeStream = fs.createWriteStream(reportFile , null, function(err) {
	if (err) {
		log.warn('Cannot write HTML Report\n\t' + err.message);
	} else {
		log.debug('HTML report written to "%s".', reportFile);
	}
});
```

But I think its a issue with new version of io.js v2.3.0, I will rise a new bug in theirs repo too.

**Comment by Dignifiedquire** [comment]
Thanks. It looks like it generated quite the discussion on the iojs repo. 

I will close this issue as there is nothing we can do from this side.

**Comment by ChALkeR** [comment]
Just for the reference: this is not an io.js bug, it's a bug in `karma-html-reporter`.

It looks like the idea of placing a work-around for such errors in io.js did not receive any support, and this is not going to be fixed on the io.js side.

The proper solution would be to merge https://github.com/dtabuenc/karma-html-reporter/pull/27 into `karma-html-reporter`.
