### ISSUE TITLE
Please consider using node-pre-gyp

### ISSUE THREAD

**Issue by Pomax** [karma-runner/karma#1455]
Any Nodejs/npm module that relies on node-gyp basically means Windows users can't use your project without compiling, which is an incredibly much harder dev track than on OSX and Unix/Linux. However, that problem can be entirely negated by using [node-pre-gyp](https://www.npmjs.com/package/node-pre-gyp), so I cannot stress enough how important it is to work that into karma=cli, so that webpack-dev-server (which relies on karma-cli) can actually run on Windows, instead of somewhat (hopefully unintentionally, of course!) giving them the finger

A fantastic example is sqlite3 - install that on any OS and instead of compiling it just checks if there is a precompiled version on S3. If so, it downloads that, and done. Especially for windows users, that makes the difference between "I can't use this module" and "everything just works" =)

**Comment by Dignifiedquire** [comment]
Thanks. Still the same guy doing the work though ;)


Could you explain a little bit more what we would actually need to do, as karma itself does not have any native code but only its dependencies.

**Comment by Pomax** [comment]
down the module chain we go - it looks like the socket.io module that karma relies on is the part that's causing the node-gyp building.

**Comment by devoto13** [comment]
Closing as there is nothing to fix in `karma` itself and it's probably obsolete by now.
