### ISSUE TITLE
Init dev script not installing git message validator hook correctly

### ISSUE THREAD

**Issue by maoueh** [karma-runner/karma#1457]
Just wanted to report that none of the init dev script (neither `scripts/init-dev-env.js` or `tasks/init-dev-env.js`) are installing the git commit message validator hook correctly. Both of them points to invalid location
 * `scripts/init-dev-env.js` => Tries to symlink `node_modules/grunt-conventional-changelog/lib/validate-commit-msg.js`
 * `tasks/init-dev-env.js` => Tries to symlink `tasks/lib/validate-commit-msg.js`

I'm willing to fix this issue if you tell me what are the next course of actions (remove or fix).

**Comment by Dignifiedquire** [comment]
Thanks, I opened an issue on grunt-conventional-changelog to find out what happened to that file.

**Comment by Dignifiedquire** [comment]
Here is the old file, lets just maintain it in the repo for now https://gist.github.com/Dignifiedquire/cb237d55a3d81bf95e92

**Comment by Dignifiedquire** [comment]
I setup git hooks using ghooks which should solve this :)
