### ISSUE TITLE
Karma launchers do not support Windows 8+ modern apps

### ISSUE THREAD

**Issue by nicolasmccurdy** [karma-runner/karma#1469]
Modern apps in Windows 8+ use appx files instead of exes. This is important for using modern apps with Karma launchers because you must use a different command to launch the appx file, which causes a separate process to be created. When the launching process (for example, the `start` command) is done launching the modern app, the original process will complete, and Karma will think the modern app has already died and will ignore its results. 

The main reason I am reporting this is because Microsoft Edge, Microsoft's new browser that will launch in late July, is a modern app, and I am working on a Karma launcher for it. If this is something that Karma should not need to support natively and should be able to be implemented in just the launcher, please let me know.

**Comment by nicolasmccurdy** [comment]
I noticed that this issue has been labeled. Is there anything I can do to help working on it?

**Comment by Dignifiedquire** [comment]
Hey sorry, it's on my todo list to investigate how this can best solved. In general I think karma core should  be able to launch anything, including `appx` files. So if you have an idea how to solve this, feel free to open a PR (please against `canary` branch, as that will be released as a new stable very soon)

**Comment by nicolasmccurdy** [comment]
I'm switching to a different way of launching Edge which no longer depends on this feature (and works based off an EXE instead, just like the Karma IE launcher). I probably won't work on a fix for this, so please mark this as `wontfix` or leave it open if you think someone else would find it useful.

**Comment by dignifiedquire** [comment]
Thanks for the update @nicolasmccurdy closing :)
