### ISSUE TITLE
Inconsistent regex and test file naming in plus/RequireJS documentation

### ISSUE THREAD

**Issue by jfarid27** [karma-runner/karma#1474]
It's a minor issue but it catches me every time I start a new project. The [documentation example for RequireJS](http://karma-runner.github.io/0.12/plus/requirejs.html) names test files with a  **Spec.js** suffix, but the regex to filter the loaded files is...

```regex
test\.js$
```

Clearly it never loads test files. PR incoming.

**Comment by jfarid27** [comment]
@Dignifiedquire I saw your message in the PR. What's a good fix for this? I'm not sure I'm on the right branch in #1475 since the docs on the website actually don't show. 
```regex
/(spec | test)\.js$/
```
as the regex filter. It only shows

```regex
/test\.js$/
```

It looks like it's technically fixed if you're sure the regex is case insensitive, it's just the live version on the website isn't updated to the (spec | test) regex.

**Comment by Dignifiedquire** [comment]
I had forgotten to sync the docs, they should be now the same as here in the repo. Could you check if it's now good please?

**Comment by jfarid27** [comment]
@Dignifiedquire looks good! Thanks a bunch!
