### ISSUE TITLE
Cannot find jsx files

### ISSUE THREAD

**Issue by jannavarro** [karma-runner/karma#1478]
I have a combination of js and jsx files and when I run karma test on them the jsx files cannot be read (e.g KeymapManager is my jsx file). Error is: "Module not found: Error: Cannot resolve 'file' or 'directory' ../src/modules/core/Keymap/KeymapManager in D:somepath..." 

I know there is a karma react jsx preprocessor module but I have seen several guides like [this] (http://nicolasgallagher.com/how-to-test-react-components-karma-webpack/) wherein I can test jsx files without needing that karma react jsx preprocessor module. Is there some special step for karma to find my jsx files?

**Comment by jannavarro** [comment]
my path is wrong. sorry bout that.

**Comment by Dignifiedquire** [comment]
No problem, happy to hear it worked out
