### ISSUE TITLE
Missing karma.js in static folder

### ISSUE THREAD

**Issue by jchonde** [karma-runner/karma#1483]
Hello, 

The 0.1.37 tag and master branch miss the `static/karma.js` file.
The problem comes from the `.gitignore` file.

**Comment by Dignifiedquire** [comment]
This is because the `static/karma.js` file is automatically build, it never gets checked into git, only into npm.

**Comment by Dignifiedquire** [comment]
This is the grunt task that generates it: https://github.com/karma-runner/karma/blob/master/Gruntfile.coffee#L14-L17
