### ISSUE TITLE
Jasmine test crashes Karma in Firefox before completion of run

### ISSUE THREAD

**Issue by keirlawson** [karma-runner/karma#1489]
This test seems to run ok in Jasmine standalone but crashes my Karma setup:

```javascript
it('should catch error thrown by JSON.parse', function (done) {
  new Promise(function (resolve) {
    resolve('notjson');
  }).then(JSON.parse)
  .catch(function () {
    console.log('caught');
    expect(true).toBe(true);
    done();
  });
});
```

Karma config:

```javascript
var TEST_FILES = 'test/integration/promiseSpec.js';

module.exports = function(config) {
  config.set({

    files: [
      TEST_FILES
    ],

    frameworks: ['jasmine'],

    browsers: ['Firefox'],

    reporters: ['mocha'],

  });
};

```

It runs fine with Chrome. I am running Karma 0.12.37

**Comment by Dignifiedquire** [comment]
Can you give the full stack trace of the errors please?

**Comment by keirlawson** [comment]
There is no stack trace, only `SyntaxError: JSON.parse: unexpected keyword at line 1 column 1 of the JSON data`

**Comment by keirlawson** [comment]
After experimenting a bit more, wrapping JSON.parse in another function produces the expected result of the test passing and test execution continuing:

```javascript
var jsonparse = function (toParse) { return JSON.parse(toParse); };

it('should catch error thrown by JSON.parse', function (done) {
  new Promise(function (resolve) {
    resolve('notjson');
  }).then(jsonparse)
  .catch(function () {
    console.log('caught');
    expect(true).toBe(true);
    done();
  });
});
```

**Comment by Dignifiedquire** [comment]
Interesting, what Promise library are you using?

**Comment by keirlawson** [comment]
I'm currently using Firefox's native ES6 promises

**Comment by Dignifiedquire** [comment]
It looks like that is a bug in Firefox then, because executing this on its own in the Firefox console, I get the same result as you do.

**Comment by keirlawson** [comment]
Swapping out Firefox's native implementation for core-js ES6 promises (via Babel) makes the tests run as expected so perhaps there is some issue with the way Firefox is propagating this particular exception?

**Comment by Dignifiedquire** [comment]
Yes pretty sure it's a bug in their promise implementation.

**Comment by keirlawson** [comment]
Have created a bug report here: https://bugzilla.mozilla.org/show_bug.cgi?id=1182758

**Comment by Dignifiedquire** [comment]
Closing, as there is nothing we can do from this side.
