### ISSUE TITLE
Test still passes when trying to use dependencies in Jasmine "it" without using inject()

### ISSUE THREAD

**Issue by vinhnghi223** [karma-runner/karma#1490]
Let's say I write something like this by mistake, the test run by Karma still passes
```
   it('should test my directive', function($compile) {
      scope.data = data;
      element = angular.element('<my-directive></my-directive>');
      $compile(element)(scope);
      scope.$digest();

      expect(<something>).toEqual(<something>);
    });
```
Obviously it should be inject(function($compile){...}) and the first 4 lines can be put inside beforeEach, but I just want to point out the issue. I only notice the issue when I read Jasmine report on my browser.

**Comment by Dignifiedquire** [comment]
I'm not sure the fault lies with karma if this passes, in theory, without the `inject` it should simply throw an error, as `expect(<something>)` is no valid javascript, or is this run through a perprocessor?

**Comment by vinhnghi223** [comment]
No, it is just a normal expect, something like this:      expect(element.find('li').eq(0).text()).toEqual('China Doll');

When I tried something like this, it throw " TypeError: $compile(...) is not a function":

    it('should test my directive', function($compile) { });

but it won't throw any error if I do sth like this:

    it('should test my directive', function($compile) {
      $compile(element)(scope);
    });

**Comment by timkindberg** [comment]
Cause it might think $compile is the 'done' function that you can
optionally pass into every it function. And from its perspective you called
done so you're "async" test has completed.
On Fri, Jul 10, 2015 at 2:33 PM Nghi Le <notifications@github.com> wrote:

> No, it is just a normal expect, something like this:
> expect(element.find('li').eq(0).text()).toEqual('China Doll');
>
> When I tried something like this, it throw " TypeError: $compile(...) is
> not a function":
>
> it('should test my directive', function($compile) { });
>
> but it won't throw any error if I do sth like this:
>
> it('should test my directive', function($compile) {
>   $compile(element)(scope);
> });
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/karma-runner/karma/issues/1490#issuecomment-120488975>
> .
>
-- 
- Tim

**Comment by Dignifiedquire** [comment]
Closing, as this has nothing to do with karma, if you want a different behaviour you will have to modify/change jasmine
