### ISSUE TITLE
Breaking change in minor version

### ISSUE THREAD

**Issue by c24w** [karma-runner/karma#1496]
If "[Karma uses Semantic Versioning](https://github.com/karma-runner/karma/blob/2c9be5a03f8de1311a62014966d5d87c94067ec0/docs/about/01-versioning.md)", why did the v0.13.0 minor version change introduce a [breaking API change](https://github.com/karma-runner/karma/blob/2c9be5a03f8de1311a62014966d5d87c94067ec0/CHANGELOG.md#breaking-changes)?

>Given a version number MAJOR.MINOR.PATCH, increment the:
>    1. MAJOR version when you make incompatible API changes,
>    2. MINOR version when you add functionality in a backwards-compatible manner, and
>    3. PATCH version when you make backwards-compatible bug fixes.
>Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

_http://semver.org_

**Comment by Dignifiedquire** [comment]
Because we are still on `0.x.y`, so we follow the same convention as node followed, that is having breaking changes in the minor versions, until a `1.0.0` is released.
