### ISSUE TITLE
File matching 2 patterns doesn't match the first pattern like the docs say

### ISSUE THREAD

**Issue by Robin-Hoodie** [karma-runner/karma#1499]
See http://stackoverflow.com/questions/31452862/testing-angular-with-karma-file-ordering/31454420#31454420 + my own answer for the (possible) issue

**Comment by Dignifiedquire** [comment]
Thanks for the report, will try to find out what is going on asap

**Comment by synarque** [comment]
I have it as well :
"app/scripts/elportalapp.js",
"app/scripts/**/*.js",
"test/mock/**/*.js",
"test/spec/**/*.js"

'/base/app/scripts/elportalapp.js': '2297e40af2d6c5cf6b06a355d867c3875bd39b1f', '/base/app/scripts/controllers/aceselector.js': '158b2c676e2f19db05248efdc07f3d713275aa40', '/base/app/scripts/controllers/admin.js': 'fd0988775454ae5828b034c767db647b09806e3f', '/base/app/scripts/controllers/appdetails.js': '650a4aa60ac452c175ea604d009a29b5c28125b6', '/base/app/scripts/controllers/applicationselector.js': '1bd3d7474789ea6d211152a4f544e5dbd29fc1b7', '/base/app/scripts/controllers/approvaldlg.js': '90e2e48e804abc3e966e35e53413549e09b42d87', '/base/app/scripts/controllers/audit.js': '4a7fdc86f7381d7a459d242f4a0c43e0d588452c', '/base/app/scripts/controllers/createapp.js': '21e962048f80730c38779168383ed4391a24883b', '/base/app/scripts/controllers/createappprogressdlg.js': '79ebd0f461b014b30fc6a2856f52cf5630c9f672', '/base/app/scripts/controllers/createrelease.js': '401b3e85a4795ba5ce0ecbe8be54d4a94ff73059', '/base/app/scripts/controllers/errordisplay.js': '4437e63846cb6a853bf5ebfb730209a7418f0a85', '/base/app/scripts/controllers/governance.js': '7d285adbc291063c78c9193b7619e25bb772250a', '/base/app/scripts/controllers/groupdetailsdialog.js': '4d2da220a24ae86032b3b01bc2c53a6fbad2164d', '/base/app/scripts/controllers/main.js': '11a97f162c60f35d1430bc244481b9659742a436', '/base/app/scripts/controllers/release.js': 'dda68d376a3bdb0a9fd70a0994401710e9c5f406', '/base/app/scripts/controllers/workflowchart.js': 'd57f43269894a4a856dd04edb932a2ee673cab6a', '/base/app/scripts/controllers/workflowdialog.js': 'f2de8b5037479c7866839e331cab2ad7b8e4453a', '/base/app/scripts/directives/aceselector.js': '341069cc93855667b650f4ab55947382891d1365', '/base/app/scripts/directives/applicationselector.js': 'a3ec5286124f2a7b926a68be640e140cb1412be4', '/base/app/scripts/directives/errordisplay.js': 'c27e00769b74b2bcf671ccda5ef3576ad345e432', '/base/app/scripts/directives/horizontalcollapse.js': '64f6234fd5ca0be4e28a3106d83d4954c71a29cb', '/base/app/scripts/directives/kcode.js': '63b13911efa377986dfe3df4745aa963c45a6425', '/base/app/scripts/directives/wipoverlay.js': '985a854fba11d6186edd9aa705bd6ac9b22008f4', '/base/app/scripts/directives/workflowchart.js': 'dd1f0a23944895fc7fd999905f53e82f857052b4', '/base/app/scripts/elportalapp.js': '2297e40af2d6c5cf6b06a355d867c3875bd39b1f', '/base/app/scripts/factories/approvals.js': '52267989c9a86f9225fea6f0e1464d7e9ed2f5cc',

**Comment by Dignifiedquire** [comment]
Fix was released in `0.13.1`
