### ISSUE TITLE
Versioning scheme confusion.

### ISSUE THREAD

**Issue by NicBright** [karma-runner/karma#1506]
Hello, I'm a little bit confused about the versioning scheme. 

1. From the gruntfile.js (npm-publish task) I read that odd versions should be canary versions, while "npm info karma" clearly states that the "latest" version is 0.13.2. In my understanding 0.13.x should not have been published as a latest version if this gruntfile was followed. The next latest version should have been 0.14.0 then. 

2. The [docs](http://karma-runner.github.io/0.13/about/versioning.html) talk about a *master* (for canary) and a *stable* (for latest) branch. This does not match the current repository layout (there is a *canary* branch, but not a *stable* branch)

Can somebody please clarify?

**Comment by Dignifiedquire** [comment]
Sorry about that, we recently changed this behaviour and I hadn't updated the documentation accordingly. It should be now unified in both the `gruntfile.js` and the docs.

**Comment by NicBright** [comment]
Thank you for the quick response. Now it's clear :-)
