### ISSUE TITLE
conventional-changelog 0.1.x is release

### ISSUE THREAD

**Issue by stevemao** [karma-runner/karma#1510]
Just wondering if you guys are cool to switch to the latest version. All issues with the CHANGELOG here or in any related repos are fixed. Because of the rewrite, the syntax is completely changed. A few people are using it and I've been using it but I haven't found any problems so far. 
Related modules such as conventional-github-releaser should also be good to use ~~but need more tests~~. Tests are comprehensive now.

There are grunt/gulp plugins

**Comment by Dignifiedquire** [comment]
Sure, if you want to make a PR, I'd be happy to update it
