### ISSUE TITLE
Chrome is not closing when tests are complete nothing in debug.

### ISSUE THREAD

**Issue by jrgleason** [karma-runner/karma#1512]
# Environment

   * Windows 7
   * Cygwin Browser

# Issue

I have the following config...

    module.exports = function (config) {
      config.set({
        browsers: ['Chrome'],
        basePath: '',
        frameworks: ['jasmine'],
        files: [
            './src/dependencies/angular/angular.js',
            './src/dependencies/angular/*.js',
            'http://cdnjs.cloudflare.com/ajax/libs/restangular/1.5.1/restangular.min.js',
            'http://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js',
            'http://cdnjs.cloudflare.com/ajax/libs/ng-tags-input/2.3.0/ng-tags-input.js',
            'http://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.js',
            './build/df-insight-templates.js',
            './src/**/*.js'
        ],
        phantomjsLauncher: {
            // Have phantomjs exit if a ResourceError is encountered (useful if karma exits without killing phantom)
            exitOnResourceError: true
        }
      });
      singleRun = true;
      reporters = ['dots', 'junit'];
      junitReporter = {
        outputFile: 'test-results.xml'
      };
    };

But when I run `karma start --log-level debug` The output ends as follows...

    Chrome 42.0.2311 (Windows 7 0.0.0): Executed 1 of 6 SUCCESS (0 secs / 0.037 secs
    Chrome 42.0.2311 (Windows 7 0.0.0): Executed 2 of 6 SUCCESS (0 secs / 0.047 secs
    Chrome 42.0.2311 (Windows 7 0.0.0): Executed 3 of 6 SUCCESS (0 secs / 0.058 secs
    Chrome 42.0.2311 (Windows 7 0.0.0): Executed 4 of 6 SUCCESS (0 secs / 0.062 secs
    Chrome 42.0.2311 (Windows 7 0.0.0): Executed 5 of 6 SUCCESS (0 secs / 0.065 secs
    Chrome 42.0.2311 (Windows 7 0.0.0): Executed 6 of 6 SUCCESS (0 secs / 0.068 secs
    Chrome 42.0.2311 (Windows 7 0.0.0): Executed 6 of 6 SUCCESS (0.075 secs / 0.068 secs)

     ******$ <-prompt

So it appears it isn't trying to close at all and I don't see any errors. Chrome stays open and Karma does not end running. I can't find any errors on the output. I did notice this warning...

    22 07 2015 09:57:27.351:WARN [karma]: No captured browser, open http://localhost:9876/

Can someone see what is missing?

**Comment by jrgleason** [comment]
Oops

**Comment by jrgleason** [comment]
NM I thought I was supposed to have something in JSON syntax I was wrong. Still can't figure it out. Running as ` karma start --reporters junit,dots --singleRun true` works fine so maybe a config parsing issue?

**Comment by Dignifiedquire** [comment]
All good @jrgleason ?

**Comment by jrgleason** [comment]
Yup sorry for the garbage
