### ISSUE TITLE
Karma 0.13.3 - You need to include some adapter that implements __karma__.start method! Error when using urlRoot

### ISSUE THREAD

**Issue by codependent** [karma-runner/karma#1516]
I am using Karma's latest release (0.13.3) and found that when using urlRoot in the configuration I got this error:

    24 07 2015 10:58:16.957:WARN [proxy]: proxy "http://localhost:3000" normalized to "http://localhost:3000/"
    24 07 2015 10:58:16.993:WARN [karma]: No captured browser, open http://localhost:8080/__karma__/
    24 07 2015 10:58:16.999:WARN [karma]: Port 8080 in use
    24 07 2015 10:58:17.000:WARN [karma]: Port 8081 in use
    24 07 2015 10:58:17.001:INFO [karma]: Karma v0.13.3 server started at http://localhost:8082/__karma__/
    24 07 2015 10:58:17.005:INFO [launcher]: Starting browser Chrome
    24 07 2015 10:58:17.771:INFO [Chrome 44.0.2403 (Windows 7 0.0.0)]: Connected on socket w_eh0ikyk0IMkyocAAAA with id 71443510
    24 07 2015 10:58:18.817:WARN [proxy]: failed to proxy //__karma__/absoluteC:/Users/MYUSER/git/karmando/karma-demo/node_modules/karma-ng-scenario/lib/
    angular-scenario.js?62f813822d0794a1cdd19bc13cf43fb56f3e6eab (connect ECONNREFUSED 127.0.0.1:3000)
    24 07 2015 10:58:18.820:WARN [proxy]: failed to proxy //__karma__/absoluteC:/Users/MYUSER/git/karmando/karma-demo/node_modules/karma-ng-scenario/lib/
    adapter.js?7e76033575f4234bc4bcce0690b5986f1151c74c (connect ECONNREFUSED 127.0.0.1:3000)
    24 07 2015 10:58:18.820:WARN [proxy]: failed to proxy //__karma__/base/scenario.test.js?61ddd448331e86e3fb529e62ca00722fad762fd1 (connect ECONNREFUSED
     127.0.0.1:3000)
    24 07 2015 10:58:19.821:WARN [proxy]: failed to proxy //__karma__/absoluteC:/Users/MYUSER/git/karmando/karma-demo/node_modules/karma-ng-scenario/lib/
    angular-scenario.js?62f813822d0794a1cdd19bc13cf43fb56f3e6eab (connect ECONNREFUSED 127.0.0.1:3000)
    24 07 2015 10:58:19.823:WARN [proxy]: failed to proxy //__karma__/absoluteC:/Users/MYUSER/git/karmando/karma-demo/node_modules/karma-ng-scenario/lib/
    adapter.js?7e76033575f4234bc4bcce0690b5986f1151c74c (connect ECONNREFUSED 127.0.0.1:3000)
    Chrome 44.0.2403 (Windows 7 0.0.0) ERROR
       You need to include some adapter that implements __karma__.start method!

However, changing the dependency back to version 0.12.31 it works:

    WARN [proxy]: proxy "http://localhost:3000" normalized to "http://localhost:3000/"
    WARN [karma]: Port 8080 in use
    WARN [karma]: Port 8081 in use
    INFO [karma]: Karma v0.12.31 server started at http://localhost:8082/__karma__/
    INFO [launcher]: Starting browser Chrome
    INFO [Chrome 44.0.2403 (Windows 7)]: Connected on socket 4f0aiMxx34UkZs63UCVj with id 37065433
    Chrome 44.0.2403 (Windows 7): Executed 1 of 1 SUCCESS (0.093 secs / 0.085 secs)

This can be reproduced with the code located here https://github.com/codependent/karma-demo

1) Start the server with `node index.js`
2) `karma start test/karma.ng-scenario.conf.js`

**Comment by mjw56** [comment]
:+1: just ran into this too.

downgrading to 0.12.31 worked for me as well. Also, had to downgrade ```grunt-karma``` down to ```0.11``` because of peerDeps.

**Comment by Dignifiedquire** [comment]
Published as [0.13.8](https://github.com/karma-runner/karma/releases/tag/v0.13.8)

**Comment by mjw56** [comment]
Thanks @Dignifiedquire for the quick turnaround.

**Comment by QuantumInformation** [comment]
I'm still getting this issue with 
   "karma": "^0.13.22",
    "karma-babel-preprocessor": "^6.0.1",
    "karma-browserify": "^5.0.1",
    "karma-chrome-launcher": "^0.2.3",
    "karma-cli": "0.1.2",
    "karma-coverage": "^0.5.5",
    "karma-fixture": "^0.2.1-1",
    "karma-html2js-preprocessor": "^0.1.0",
    "karma-mocha": "^0.2.2",
    "karma-phantomjs-launcher": "^1.0.0",
    "karma-sinon": "^1.0.4",

**Comment by QuantumInformation** [comment]
Chrome 49.0.2623 (Mac OS X 10.10.4) ERROR
