### ISSUE TITLE
Tests take 100x+ longer when the browser isn't in the current screen on mac

### ISSUE THREAD

**Issue by mkolodny** [karma-runner/karma#1517]
I have about 100 tests. When I'm looking at the screen/window with the browser (I usually use full screen mode, with the browser in it's own screen), the tests take about .8 seconds to run. When the browser is in another screen, the tests take almost two minutes to run.

An interesting side note is that when the browser is in the same screen as my terminal, and I'm looking at that screen I stop getting the error "Some of your tests did a full page reload!". Whereas I was getting that error every couple of times I ran my tests when my terminal and browser were each in their own full screen.

**Comment by mtscout6** [comment]
I'm assuming you see this on Chrome? There is a known "performance" improvement in chrome that throttles timeouts to once per second if a Chrome tab is not visible. Have you tried Firefox or PhantomJS?

**Comment by mkolodny** [comment]
Yes, this is on Chrome. I haven't tried Firefox or PhantomJS, but I'll keep it in mind that using them is a potential solution.



—

**Comment by Dignifiedquire** [comment]
Closing as this is a "feature" of Chrome on OS X that we can't do anything about :(
