### ISSUE TITLE
timer.setTimeout causes Illegal Invocation error in a limited execution environment

### ISSUE THREAD

**Issue by schmuli** [karma-runner/karma#1519]
I am writing an Atom plugin for running Karma, which currently uses the Atom process to start the Karma server. I believe that Atom runs its plugins in a limited execution environment (I had a similar issue when loading the karma plugin, but found an Atom-specific workaround).

However, I keep getting an <b>Illegal Invocation</b> exception in <code>lib/launchers/capture_timeout.js</code> on line 15, when trying to set a timeout. It appears that the exception is caused by <code>setTimeout</code> being called as a method of the <code>timer</code> object.

Changing the timer definition in <code>lib/server.js</code> to delegate to the <code>setTimeout/clearTimeout</code> functions, rather than pass by reference, eliminates the exception.

Is this a valid use-case for making a change in Karma's code base?

**Comment by Dignifiedquire** [comment]
The main reason why those timers are injected is to be able to easily mock them during testing of Karma itself. If that turns out to be an issue in this scenario this is definitely a bug. 
Would you be up to creating a PR?

**Comment by schmuli** [comment]
I added a PR but one of the unit-tests are failing for some reason, which doesn't appear to have anything to do with the changes I made.

**Comment by Dignifiedquire** [comment]
@schmuli thanks I will check it out later
