### ISSUE TITLE
Karma Often Crashes While Debugging

### ISSUE THREAD

**Issue by knpwrs** [karma-runner/karma#1528]
My team has noticed that Karma often crashes while stepping through code in a Browser's debugger:

![image](https://cloud.githubusercontent.com/assets/174864/8990484/a3438542-36c0-11e5-9d91-148b6176e004.png)

This causes the browser to crash and makes debugging very difficult. Is there any way to avoid this?

**Comment by Dignifiedquire** [comment]
Thanks for the report. The main issue here is that karma has a timeout for failing when a browser fails to communicate for a longer period of time. When you start stepping through your code to debug it the whole JavaScript execution is paused, so there are no pings sent back to Karma, so it things the browser stopped working and it stops trying. 

On the other hand it should simply disconnect, but not throw the error I'm seeing in your log output, could you give some more detail on that error, and the setup you have so I can reproduce it please?

**Comment by KenPowers** [comment]
I've created a Gist with the minimally reproducible example according to what we are using: https://gist.github.com/KenPowers/1a157d23d30905efa938

Turns out this only appears to reproduce when using `karma-junit-reporter`. Otherwise everything works fine.

Steps to reproduce:

1. `npm i`
1. `npm run test`
1. In Chrome, set a breakpoint in the test.
1. Refresh the page.
1. Hit the breakpoint, allow browser to disconnect.
1. Continue.
1. Karma crashes.

I've also seen this happen on the debug page. What's probably happening there is the real Karma runner page gets backgrounded by Chrome, thereby becoming disconnected, and then the tests resume once the debug page is closed.

**Comment by KenPowers** [comment]
I've also noticed this with the `karma-html-reporter`. The `karma-progress-reporter` appears to work fine.

**Comment by Dignifiedquire** [comment]
Thanks, might be an issue with the karma-html-reporter then. Could you open an issue there please?

**Comment by KenPowers** [comment]
It also happens with the junit reporter. I think it might just be a problem with how reporters are made in general. Notice the error in the screenshot happens in `onBrowserComplete` in the junit reporter.

**Comment by Dignifiedquire** [comment]
Thanks @KenPowers

**Comment by isiahmeadows** [comment]
By the way, this appears to also be the case with the `dots` built-in reporter and both `karma-phantomjs-launcher` and `karma-phantomjs-launcher`, and I run into it fairly regularly regularly. Here's my config (pulled out some of the irrelevant bits):

```js
"use strict"

module.exports = function (config) {
    config.set({
        basePath: __dirname,
        restartOnFileChange: true,

        // This is normally specified in the command line
        // browsers: ["Chrome", "Firefox", "PhantomJS"]
        frameworks: ["browserify", "mocha"],
        reporters: ["dots"],

        customLaunchers: {
            PhantomJSDebug: {
                base: "PhantomJS",
                debug: true,
            },
        },

        files: [
            "./scripts/globals.js",
            {pattern: "./test/**/*.js", nocache: true},
            {pattern: "./lib/**/*.js", included: false, served: false},
            {pattern: "./scripts/**/*.js", included: false, served: false},
            {pattern: "./r/**/*.js", included: false, served: false},
        ],

        exclude: ["./test/cli/**"],

        preprocessors: {
            "./scripts/globals.js": ["browserify"],
        },

        browserify: {
            debug: true,
            insertGlobals: true,
            fullPaths: true,
        },

        singleRun: true,

        // This should be way more than enough.
        browserNoActivityTimeout: 1000000000,
    })
}
```

I suspect it's a Karma issue (or one of its dependencies), not necessarily that of reporters.

**Comment by isiahmeadows** [comment]
To be honest, it's slightly crippling for me when I'm debugging highly async code in PhantomJS or Chrome.

**Comment by isiahmeadows** [comment]
No errors are thrown, though.

**Comment by devoto13** [comment]
This sounds like a valid bug to me. However, there have been many changes to the libraries since it was reported. Please open a new issue including a minimal reproduction if you still experience this problem.

**Comment by isiahmeadows** [comment]
It's been years, so this may or may not even be valid anymore.
