### ISSUE TITLE
IE8 doesn't work since karma 0.13.0

### ISSUE THREAD

**Issue by dchambers** [karma-runner/karma#1529]
IE8 stopped working since karma started using the [dom-serialize](https://github.com/webmodules/dom-serialize) library in karma 0.13.0. This is because `Object.reduce` is used [on this line of code](https://github.com/webmodules/dom-serialize/blob/f2d60cf6ec92277fc1b27ed8b0d3be310178eaf0/index.js#L9), but no shim has been provided for IE8.

**Comment by Dignifiedquire** [comment]
Thanks for the report.

**Comment by dchambers** [comment]
Actually, karma 0.12.37 doesn't seem to work either because there is a file with a URL like `http://localhost:9876/absolute/tmp/4a09ba9cdb71424e0ecb978e4c0a49ce.browserify` that is served with the content type `text/plain`, which IE8 then refuses to load.

Is there an older version of karma that you would recommend for people still needing to test against IE8?

**Comment by Dignifiedquire** [comment]
The official policy is that all versions of Karma should support IE8, so I'm not sure at which point we broke this contract. If you are up to it, I would be happy to accept a PR fixing it, as I can only test against IE11 with simulated IE8 behaviour at the moment.
