### ISSUE TITLE
Karma 0.13 ignores included:false pattern

### ISSUE THREAD

**Issue by hacst** [karma-runner/karma#1530]
Hi. In one of my projects Karma started to include files marked with "included:false" in the karma.conf.js after I upgraded to Karma 0.13.3. Switching back to 0.12.37 resolves the issue so either there was a intended behavioral change (either undocumented or breaking some wrong assumptions on my side) or a regression. I reproduced the issue on Windows 10 as well as Ubuntu 15.04.

The karma.conf.js looks something like this:
```js
module.exports = function(config) {
  config.set({
    basePath: '../',
    ...
    files: [
      {pattern: 'src/scripts/backend/worker.js', included: false}, // Web-worker script with entry point
      'src/scripts/**/*.js',
      'test/unit/test_*.js'
    ],
    ...
  });
};
```
The worker.js script contains web-worker specific functionality and hence must not be executed directly.

Steps to reproduce:
* Download the reproducer from http://d0t.dbclan.de/dump/karma-included-false-ignored-in-0.13.zip and extract it somewhere
* Run ```npm install```
* Run ```npm test```
* Replace the package.json with package-working.json
* Re-run ```npm install```
* Re-run ```npm test```

**Expected:** As worker.js should not be included directly its contents should be ignored and the dummy test should pass in both runs of ```npm test```

**Actual:** For the first run with Karma 0.13.3 worker.js is included and Karma fails and complains about ```someWebworkerSpecificFunction``` in worker.js. The second run with Karma 0.12.37 works as expected.

As I said. I'm not sure if it's something I'm doing or not but the behavior definitely changed between those two versions.

**Comment by Dignifiedquire** [comment]
Thanks for the detailed report I will see what I can find out. There have been a lot of changes in this area so this is probably a simple regression on our side

**Comment by khealy316** [comment]
I have the same problem as well.  I would like to use the latest version for testing with ES6 and WebPack, but I still need to run my old ES5 tests and would like to ignore the ES6 files for those tests.  Thanks!

**Comment by ahutchings** [comment]
I'm running into this as well using this set of patterns:

```js
{
  files: [
    '**/__tests__/**/*',
    {
      pattern: 'node_modules/**/__tests__/**/*',
      included: false,
      watched: false,
      served: false
    }
  ]
}
```

**Comment by jaymes-bearden** [comment]
I'm having the exact same issue with the glob pattern ignoring previously declared patterns that have been defined as not included / not served:

	...

	var sources = [
		'src/app.js',
		...
		{pattern: 'src/login.js', included: false, served: false, watched: false, useSourcesPath: true},
		'src/**/*.js'
	].map(mapToSourcesPath);

	var tests = [
		'src/unit/**/*.spec.js',
	];

	var files = externalSources.concat(libraries, sources, tests);

	config.set({
		autoWatch: true,
		basePath: './',
		browsers: ['PhantomJS'],
		files: files,
		frameworks: ['jasmine'],
		reporters: ['dots']
	});

	...

As specified above, login.js is under /src/ and becomes included even though included and served are set to false. Reverting back to 0.12.37 returns to the expected behavior.

**Comment by danhaller** [comment]
Similar problem with 0.13 here, this pattern previously worked but now does not:

```json
'src/**/!(*scenario).js'
```

i.e. include all .js files except ones containing scenario

**Comment by DarthCharles** [comment]
I've been trying to track this down to see whats going on, it appears that in this part
```javascript
   var included = this._patterns.filter(function (pattern) {
      return pattern.included
    })
    .map(function (p) {
          return from(self.buckets.get(p.pattern) || []).sort(byPath)
    });
```
the map function is not working properly, it returns files that are not included in the filter function. I don't how to proceed next.

**Comment by jaymes-bearden** [comment]
Any update on the proposed fix above?

**Comment by fareskronos** [comment]
I had the issue earlier with 0.13.15 so I installed old version 0.12.37 but it did not fix the problem.
Now I fixed my problem by installing new NodeJS version
![image](https://cloud.githubusercontent.com/assets/16155100/11595769/1d1a4424-9a7f-11e5-93ce-ac31b7c8cda0.png)

**Comment by boneskull** [comment]
I'm having a similar problem.  I was not able to get `included: false` to work in any way, shape or form.

The documentation claims:

> Eventually, all the patterns will get resolved into files using glob, so you can use minimatch expressions like test/unit/**/*.spec.js.

I was unable to get a glob like `!path/to/file` working; Karma wants to form a path which looks like `/absolute/path/to/cwd/!path/to/file`, and throws an exception.

My workaround:

```js
var globby = require('globby');
module.exports = function(config) {
  config.set({
    files: globby.sync([
      './src/**/*.js',
      './test/unit/**/*.js',
      '!./src/util/async-listener.js',
      '!./src/plugins/resolver.js',
      '!./src/options/rc.js'
    ])
  });
};
```

Use case: I'm using `karma-browserify` to transform my modules, but I have a `browser` field which replaces the three files above prefixed with `!` with browser versions.  I was unable to find another solution than the above.

**Comment by dignifiedquire** [comment]
@budde377 any chance you could take a look at this?

**Comment by budde377** [comment]
@dignifiedquire Yes. I'll get right at it.

**Comment by dignifiedquire** [comment]
Thanks @budde377 !
