### ISSUE TITLE
Cut 0.13.4 release

### ISSUE THREAD

**Issue by KJTsanaktsidis** [karma-runner/karma#1531]
Hey, it'd be great if you could cut a new release of karma soon that includes https://github.com/karma-runner/karma/pull/1515. This is a real pain point for us and we'd be much happier if this was in npm :)

**Comment by Dignifiedquire** [comment]
Will do one today, sorry for the hold up

**Comment by Dignifiedquire** [comment]
Done

**Comment by KJTsanaktsidis** [comment]
Thank you, much appreciated :)
