### ISSUE TITLE
Load and use a Service Worker in Karma test

### ISSUE THREAD

**Issue by onsetsu** [karma-runner/karma#1547]
We want to write a [Service Worker][1] that performs source code transformation on the loaded files. In order to test this functionality, we use Karma.

Our tests import source files, on which the source code transformation is performed. The tests only succeed if the Service Worker performs the transformation and fail when the Service Worker is not active.

Locally, we can start Karma with `singleRun: false` and watch for changed files to restart the tests. However, Service Workers are not active for the page that originally loaded them. Therefore, every test case succeeds but the first one.

However, for continuous integration, we need a single-run mode. So, our Service Worker is not active during the run of the test, which fail accordingly.
Also, two consecutive runs do not solve this issue, as Karma restarts the used browser (so we lose the Service Worker).

So, the question is, how to make the Service Worker available in the test run?
E.g., by preserving the browser instance used by karma.

[StackOverflow Question][2]

  [1]: http://www.html5rocks.com/en/tutorials/service-worker/introduction/
  [2]: http://stackoverflow.com/questions/31858471/load-and-use-a-service-worker-in-karma-test

**Comment by Dignifiedquire** [comment]
So in general you would want a file like this

```js
navigator.serviceWorker.register('coolstuff.js').then(function(registration) {
   window.__karma__.start()
})
```
 and tell karma to wait to start the test run until `start` is called, so you have time to register the service worker. This is pretty much the feature that was discussed and worked on in #375 

It looks like I need to take a stab at this sooner rather than later ;) If you want to yourself feel free.

**Comment by Dignifiedquire** [comment]
Ref #380 where most of the work was already done

**Comment by onsetsu** [comment]
Actually our use-case needs a refresh of the page/redirect to another page in order for the Service Worker to become enabled (Service Worker can intercept all requests at a certain scope, but not at the very page instance it was created). A simple client side hook won't make it.

**Comment by Dignifiedquire** [comment]
What about using this:

> The exception is if the worker calls event.replace() in the install event, then it takes control of all in-scope pages immediately.

from https://jakearchibald.com/2014/using-serviceworker-today/

**Comment by onsetsu** [comment]
A similar behavior can be achieved using `self.clients.claim()` in our service worker's `activate` handler, as suggested [here][1]. Using `navigator.serviceWorker.ready.then(window.__karma__.start);`, we can wait for our worker to be ready and start our tests.

Anyway, thanks for the quick and helpful response.

[1]: http://stackoverflow.com/questions/31858471/load-and-use-a-service-worker-in-karma-test/31864646#31864646
