### ISSUE TITLE
Publishing node_modules, jspm_packages

### ISSUE THREAD

**Issue by nicklasb** [karma-runner/karma#1559]
Hi,

Is there any way to make Karma just publish a given folder?  

I am using Karma-SystemJS, and I have this problem. I have defined where everything is and so on, and that works. One of the biggest points with JSPM and SystemJS it that I get one place where all dependencies and what to load is defined. 

I am not sure if I am completely off the rails here, but during testing, publishing node_modules and jspm_packages under /base would make everything work without special actions. 
At least WRT the jspm_packages folder, I *must* be able to publish that so that it is freely available to SystemJS. 
But the only thing I find is adding the entire folder to files, meaning that *all* the files are loaded in the browser. And adding all the dependencies one by one sort of nullifies the point of SystemJS.

I think that I have looked around the documentation, but obviously, I may have missed it.

**Comment by Dignifiedquire** [comment]
If you mean by "publish" to make Karma serve all files under one folder, that is easily possible by using a simple glob, like this

```js
files: [
  'node_modules/**/*.*'
]
```
But I would be careful, and especially disable `autoWatch` as this means Karma will scan and stat every single file in `node_modules`. It might make sense to do sth like `node_modules/**/*.js` to at least only grab JavaScript files or some restrictions like this.
I hope this helps

**Comment by nicklasb** [comment]
The problem is that Karma seems to load the files either way, karma loads for *loong* while.
Especially, it seems to try running tests in node_modules as there are js-files in there that ends with spec.js.

**Comment by Dignifiedquire** [comment]
Yes that could be, as there are probably a lot of files in there, did you make sure to set `included: false`? As this is important so it doesn't go and try to execute those tests

**Comment by nicklasb** [comment]
Yes, included is false. That is what's so strange.

**Comment by nicklasb** [comment]
I am using the karma-chrome-launcher, karma-systemjs, karma-jasmine plug-ins. Not sure if any of them looks around..

**Comment by Dignifiedquire** [comment]
Do you have a small example I could try out?

**Comment by nicklasb** [comment]
Hm. No, it is kind of a large project, not sure where to start, really, if I'd need to break it out. 
For what its worth, here is the karma.conf: https://github.com/OptimalBPM/mbe-nodes/blob/master/karma.conf.js

**Comment by Dignifiedquire** [comment]
Is that the full project https://github.com/OptimalBPM/mbe-nodes?

**Comment by nicklasb** [comment]
Yes, it is. 
For now, I have set the `testFileSuffix` to mbe.spec.js  to avoid the other tests from being run.
But as soon as I set it to just spec.js, they start running again.

One thing, not that the test.spec.js in the project matters, but the thought was to write the tests in typescript, but that doesn't work yet, the compiled ES6 output `test/test-main.mbe.spec.js` is:

´´´javascript
///<reference path="../typings/tsd.d.ts"/>
console.log("In test-main.spec.ts");
import { SchemaTreeController } from "../src/controllers/schemaTreeController";
describe("Test", () => {
    it("Assertion", () => {
        let test = new SchemaTreeController(this, null);
        console.log("sdfsdddd");
        expect(test).toEqual(true); // Force failure
    });
});
//# sourceMappingURL=test-main.mbe.spec.js.map 
´´´

Nothing in there, obviously, haven't started implementing the tests yet.

**Comment by Dignifiedquire** [comment]
Okay, will take a look later today

**Comment by nicklasb** [comment]
Hm, change to using mocha and chai, didn't matter, as soon as I broadened to spec.js, it started to run all tests everywhere.

**Comment by nicklasb** [comment]
Oh, it seems that `testFileSuffix` is a karma-systemjs configuration option, and so, this it not likely to be related to karma. So I have created an issue there instead: https://github.com/rolaveric/karma-systemjs/issues/38

Closing this for now, thanks for your help!
