### ISSUE TITLE
Give karma.config.js access to command line arguments

### ISSUE THREAD

**Issue by danielsiwiec** [karma-runner/karma#1561]
Currently, the ```config``` argument passed into karma.config.js is an empty object, that gets filled out. It would be beneficial, to have access to command line arguments from within the configuration, through the passed ```config``` object, as this would allow custom logic, based on those arguments to be applied. 

Example scenario: There are two test suites (eg. unit and component) in two different folders. It's desired to run only the selected test suite. This could easily be achieved by passing an argument on the command line (like ```suite=unit```), that karma.config.js would have access to and would set the proper value on the ```config.files``` property.

What do people think about it? The implementation of this would be very straightforward (basically a one-liner).

**Comment by dtabuenc** [comment]
This would definitely be useful, such as for turning on/off coverage instrumentation via commandline when using non-standard processors like webpack.

**Comment by Dignifiedquire** [comment]
I agree, and can see how this could be useful. If someone wants to work on this I'd be happy to accept a PR

**Comment by danielsiwiec** [comment]
Cool. I'll submit a PR for this. Thanks!

**Comment by naganowl** [comment]
A workaround that currently exists would is https://github.com/karma-runner/karma/issues/61#issuecomment-9006663.

I'm planning on using the suggestion in order to toggle coverage as @dtabuenc mentioned.

**Comment by danielsiwiec** [comment]
PR submitted

**Comment by JamieMason** [comment]
Hi @Dignifiedquire @danielsiwiec - thanks for this it looks useful, but I can't see any docs for how to make use of it?

**Comment by Dignifiedquire** [comment]
@danielsiwiec could you make a PR with some docs about this please? Thanks

**Comment by danielsiwiec** [comment]
Good idea. Will do shortly

**Comment by JamieMason** [comment]
Thanks @Dignifiedquire @danielcompton. 

I figured out after posting that it's mentioned in the OP (resolved config is under `config.*`).
