### ISSUE TITLE
karma doesn't play nicely with HTML Imports de-dup

### ISSUE THREAD

**Issue by onelaview** [karma-runner/karma#1563]
## Environment
- karma v0.13.9
- Windows 10
- Chrome 44.0.2403
## Summary

When I use `karma` to test Web Component, I saw my Web Component's html file being served with **"?undefined"** query string. This could pose a problem with [HTML Imports](http://www.html5rocks.com/en/tutorials/webcomponents/imports/) de-dup functionality where it only prevents html to be imported several times if it's from the **exact** same url.

For example, imagine my test setup is going to test 2 Web Components:- `my-element-1` and `my-element-2`. And `my-element-1` also relies on `my-element-2` so it has `<link rel="import" href="my-element-2.html">`. When runs test, I saw script in `my-element-2.html` being executed twice as if it was being included in my test page twice.
## Reproduce Step

Let say, I have my project structure as following.

```
\- node_modules
\- app
    \- my-element-1.html
    \- my-element-2.html
\- tests
    \- my-element-1.spec.js
\- karma.conf.js
\- package.json
```

Let imagine `my-element-1.html` and `my-element-2.html` is my Web Component that should be imported via `<link rel="import">` tag.

In my `my-element-1.html`, there is `<link rel="import">` to import `my-element-2.html`.

``` html
<link rel="import" href="my-element-2.html">
```

In `my-element-2.html`, there is simply a script to log output to console.

``` html
<script>
    console.log('I am `my-element-2`');
</script>
```

Now, in my `karma.conf.js`, I configured it to include both `my-element-1.html` and `my-element-2.html` in the test page. My expectation is that both html files will be imported using `<link rel="import">`.

``` javascript
// list of files / patterns to load in the browser
files: [
  {pattern: 'app/my-element-1.html', nocache: true},
  {pattern: 'app/my-element-2.html', nocache: true},
  {pattern: 'tests/my-element-1.spec.js', nocache: true}
],
preprocessors: {
},
```

When I run `karma start --log-level debug`, I saw log message "I am `my-element-2`" being output twice i.e. one from the test page, and the other from `my-element-1.html`. This is not correct behavior regarding HTML Imports de-dup functionality.

```

18 08 2015 01:02:10.246:DEBUG [middlware:source-files]: Fetching O:/p/test-karma/node_modules/karma-jasmine/lib/adapter.js
18 08 2015 01:02:10.246:DEBUG [middlware:source-files]: Requesting /base/tests/my-element-1.spec.js?undefined /
18 08 2015 01:02:10.247:DEBUG [middlware:source-files]: Fetching O:/p/test-karma/tests/my-element-1.spec.js
18 08 2015 01:02:10.247:DEBUG [web-server]: serving (cached): O:/p/test-karma/node_modules/karma-jasmine/lib/adapter.js
18 08 2015 01:02:10.248:DEBUG [web-server]: serving: O:/p/test-karma/tests/my-element-1.spec.js
18 08 2015 01:02:10.264:DEBUG [middlware:source-files]: Requesting /base/app/my-element-1.html?undefined /
18 08 2015 01:02:10.264:DEBUG [middlware:source-files]: Fetching O:/p/test-karma/app/my-element-1.html
18 08 2015 01:02:10.264:DEBUG [middlware:source-files]: Requesting /base/app/my-element-2.html?undefined /
18 08 2015 01:02:10.265:DEBUG [middlware:source-files]: Fetching O:/p/test-karma/app/my-element-2.html
18 08 2015 01:02:10.265:DEBUG [web-server]: serving: O:/p/test-karma/app/my-element-1.html
18 08 2015 01:02:10.266:DEBUG [web-server]: serving: O:/p/test-karma/app/my-element-2.html
18 08 2015 01:02:10.267:DEBUG [middlware:source-files]: Requesting /base/app/my-element-2.html /
18 08 2015 01:02:10.268:DEBUG [middlware:source-files]: Fetching O:/p/test-karma/app/my-element-2.html
18 08 2015 01:02:10.268:DEBUG [web-server]: serving: O:/p/test-karma/app/my-element-2.html
Chrome 44.0.2403 (Windows 10 0.0.0) LOG: 'I am `my-element-2`'

Chrome 44.0.2403 (Windows 10 0.0.0) LOG: 'I am `my-element-1`'

Chrome 44.0.2403 (Windows 10 0.0.0) LOG: 'I am `my-element-2`'

Chrome 44.0.2403 (Windows 10 0.0.0): Executed 1 of 1 SUCCESS (0.003 secs / 0.001 secs)
```

In the above log, it seems `my-element-2.html` was being served twice via 2 different url which is

```
18 08 2015 01:02:10.264:DEBUG [middlware:source-files]: Requesting /base/app/my-element-2.html?undefined /
```

and

```
18 08 2015 01:02:10.267:DEBUG [middlware:source-files]: Requesting /base/app/my-element-2.html /
```

I suspect that because it's being served twice via different url that causing my script to run twice.
Note that, I can only reproduce this problem in non-debug test runner.

PS. I just pushed the sample source code that can reproduce this issue in https://github.com/onelaview/test-karma. Just run `npm install` and `karma start --log-level debug` to see the problem.

**Comment by devoto13** [comment]
Closing as [HTML Imports](https://developer.mozilla.org/en-US/docs/Web/Web_Components/HTML_Imports) feature is obsolete and no longer supported by Karma.
