### ISSUE TITLE
Actually send the promises

### ISSUE THREAD

**Issue by Galaf** [karma-runner/karma#1567]
Hello,

I was wondering if, instead of relying on $httpBackend and respond fake data, it could be possible to actually launch the promises and get the actual results.

When dealing with a lot of HTTP request and/or really long JSON objects, it can quickly become bothersome as I don't want to end up having a unit test file with more than 2000 lines.

Is there a way to make this painless?

**Comment by wesleycho** [comment]
Karma has nothing to do with $httpBackend from Angular 1. One could configure one's application for testing where it makes a request to `/api/url` and `/api` is proxied to your api server in the karma config. On the Angular 1 side, one could use the ngMockE2E module and use $httpBackend.passThrough

**Comment by devoto13** [comment]
Closing as per above.
