### ISSUE TITLE
files included via https not loading, no error message

### ISSUE THREAD

**Issue by benedictfischer09** [karma-runner/karma#1572]
The files property in the config object of my karma.conf looks like 

```
files: [
      // bower:js
      'https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.2/angular.min.js',
      'https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.2/angular-resource.min.js',
      'https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.2/angular-route.min.js',
      'https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.2/angular-mocks.js',
      'https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js',
      // endbower
      'app/scripts/**/*.js',
      'specs/**/*.js',
    ]
```

If I run `grunt test` it comes up with `ReferenceError: Can't find variable: angular`

Loading the libs over http instead of https works fine.  Not sure why the scripts won't load over https, my browser loads them fine. Regardless the error messaging from karma would be better if it said something like can't load file...

I'm on OSX Yosemite 10.10.5

**Comment by lgiraudel** [comment]
I just had the same behavior with jQuery loaded through https.

Tests are working with http or if I use Chrome instead of PhantomJS.

**Comment by devoto13** [comment]
I'm unable to reproduce it using the latest version of Karma. Please open a new issue including a minimal reproduction if you still experience this problem.
