### ISSUE TITLE
Proxy issue with local forward

### ISSUE THREAD

**Issue by abhijeetkpawar** [karma-runner/karma#1575]
I am using Karma (v0.12.37) as test runner along with JSPM (v0.16.2). I have added following proxy config in karma so as to allow proper loading of JSPM files:

```
proxies: {
    '/base/jspm_packages/': '/base/app/jspm_packages/'
}
```

Bu this doesn't work out and fails on following:

```
PhantomJS 2.0.0 (Windows 8 0.0.0) ERROR: 'Potentially unhandled rejection [10] Error: XHR error loading http://localhost:9876/base/jspm_packages/npm/babel-core@5.8.22.js
        Error loading http://localhost:9876/base/jspm_packages/npm/babel-core@5.8.22.js
        Error loading http://localhost:9876/base/app/pages/examples/todo-example/todo.controller.test.js'
```

Debug Logs are giving:

```
proxying request - /base/jspm_packages/npm/babel-core@5.8.22.js to localhost:9876
/base/app/jspm_packages/npm/babel-core@5.8.22.js { host: 'localhost',
  port: 9876,
  baseProxyUrl: '/base/app/jspm_packages/',
  https: false } // This is console.log of proxiedUrl in proxy.js
```

But the following url containing 'app' in it works properly:
`http ://localhost:9876/base/ app/ jspm_packages/npm/babel-core@5.8.22.js`

**Comment by EzraBrooks** [comment]
Hi, have you solved this issue?

**Comment by devoto13** [comment]
While this may be a vaild issue without more information we're unable to reproduce and fix it. Please open a new issue including a minimal reproduction of the problem if you still experience this.
