### ISSUE TITLE
Strategy to deal with listeners on $window

### ISSUE THREAD

**Issue by plestik** [karma-runner/karma#1576]
Hi,

I have a service which tacks listeners on the `window` object (via `$window`). It seems like the `$window` object is not re-initialised after each test is run (which makes sense). However, this poses a problem when I have services that add a listener. The listeners add up every time a test has run causing my test to fail. I know I can use afterEach, however, it's not always obvious the service is being used when writing tests for another directive/service. This sometimes causes tests to fail in non-obvious ways. I've tried this approach: https://gist.github.com/plestik/d722633cd77164c4e02f but it's pretty hideous to be honest. Is there a better way to deal with this issue?

**Comment by wesleycho** [comment]
If using angular, one can mock the $window object using $provide, that way the listeners do not pollute `window`.

This isn't really a karma issue, and can probably be closed.

**Comment by dignifiedquire** [comment]
thanks @wesleycho, agreed
