### ISSUE TITLE
Installation and TypeError after upgrading to Node 4.0.0

### ISSUE THREAD

**Issue by samjulien** [karma-runner/karma#1581]
I just got a new work machine (Windows 7) and installed Node 4 (and npm 2.14.2). While trying to install Karma (both globally and locally), I get a bunch of node-gyp errors that are no longer solved by passing the "--msvs-version=2013" flag and having Python in my path.  However, more pressing is that when running my tests through Gulp on my main project, I'm getting the following error:

    ERROR [karma]: [TypeError: options must be a string or an object]
    TypeError: options must be a string or an object  
    at new WriteStream (fs.js:1793:11)
    at Object.fs.createWriteStream (fs.js:1779:10)
    at C:\[edited]\devtools\node_modules\karma-html-reporter\index.js:89:22
    at C:\[edited]\devtools\node_modules\karma\lib\helper.js:80:7
    at FSReqWrap.oncomplete (fs.js:82:15)

    (node) Buffer.write(string, encoding, offset, length) is deprecated. Use write(string[, offset[, length]][,      
    encoding]) instead.

What do I need to do?

Update: I rolled back to Node 0.12.7 and I get a soft warning about the deprecation but everything works as normal. So, it must be an issue with the Node 4 interface.

**Comment by KenanSulayman** [comment]
Relates to #1577 and is due to a breakage in a third-party dependency of karma.

**Comment by pmq20** [comment]
Adding to the list: nodejs/node#2798.

**Comment by KenanSulayman** [comment]
@pmq20 that would be stupid, because karma _is working_.

**Comment by Dignifiedquire** [comment]
This is not an issue in karma, but an issue in karma-html-reporter see https://github.com/dtabuenc/karma-html-reporter/pull/27

**Comment by Dignifiedquire** [comment]
Should be fixed now
