### ISSUE TITLE
update socket.io version 

### ISSUE THREAD

**Issue by vsharmaGit** [karma-runner/karma#1583]
socket.io version 1.3.5 depends on an engine.io version which has a direct dependency pulled from Github (XMLHttpRequest). A lot of environment block Github and rely on the npm registry to retrieve dependencies.

**Comment by Dignifiedquire** [comment]
Not needed, if you run a fresh install of karma or `npm update` you already get socket.io `1.3.6` as the dependency is specified as `~1.3.6`

**Comment by vsharmaGit** [comment]
Please correct me if I am wrong, I see the dependency is specified as ~1.3.5 in the master branch.

**Comment by Dignifiedquire** [comment]
Yes sorry, that was what I meant to write, but it `~1.3.5` matches `1.3.6`

**Comment by vsharmaGit** [comment]
ok cool...looks like socket.io version 1.3.6 has not changed the engine.io version to 1.5.4. The master branch pulls the latest version however, 1.3.6 specifies 1.5.2. Thanks for your help

**Comment by Dignifiedquire** [comment]
No prob, for more details on socket.io being not upto date see #1577 and #1366
