### ISSUE TITLE
npm install -g karma (unable to install)

### ISSUE THREAD

**Issue by rajeevkb** [karma-runner/karma#1584]
I have tried to install node.js two numbers of systems.  no one is working. environment variables are set. Please help me out, Even I have tried to create .npmrc file
Node.JS tried with https://nodejs.org/dist/latest/node-v4.0.0-x64.msi

```
===SYSTEM ONE ===after this other system has some issues===================
C:\installer\Solution\MVCApp>npm install -g karma
npm ERR! registry error parsing json
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "karma"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! Unexpected token <
npm ERR! <!DOCTYPE html PUBLIC"-//W3C//DT
D XHTML 1.0 StaticRequestInfo={Referer:document.referrer};function EscapeBrowser
Frame(){try{if(window.top.location==window.self.locatio
![node_err]n){}else{window.top.location.href=document.location.href}}catch(Error){}}function SetRequestTitle(){document.title=document.domain}function InitiateFrameRequest(){var url = "/?acc=0F4B1
727-114A-4EF2-AC1B-1DB964D84818&ref=http%3A%2F%2Fww15.registry.nmpjs.org%2Fkarma
&framerequest=1&pcc=";document.write("<frameset rows=\"100%,*\" frameborder=\"no
\" border=\"0\" framespacing=\"0\"><frame src=\""+url+"\" name=\"landingparent\"
 id=\"landingparent\"><\/frameset>")}SetRequestTitle();EscapeBrowserFrame();</sc
ript></head><script type="text/javascript">InitiateFrameRequest();</script><body
><noscript><meta http-equiv="refresh" content="0;url=/?acc=0F4B1727-114A-4EF2-AC
1B-1DB964D84818&ref=http%3A%2F%2Fww15.registry.nmpjs.org%2Fkarma&framerequest=1&
noscript=1&pcc="></noscript><noframes><meta http-equiv="refresh" content="0;url=
/?acc=0F4B1727-114A-4EF2-AC1B-1DB964D84818&ref=http%3A%2F%2Fww15.registry.nmpjs.
org%2Fkarma&framerequest=1&noscript=1&pcc="></noframes></body></html>
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\installer\Solution\MVCApp\npm-debug.log
===SYSTEM SECOND ====================================================
```
![node_err](https://cloud.githubusercontent.com/assets/2646890/9877216/16c59e00-5bd9-11e5-8b61-18811e4f6ac8.png)

**Comment by Dignifiedquire** [comment]
There are two main issues here, the first one is that `python` is missing from your path, make sure you follow the instructions [here](https://github.com/nodejs/node-gyp) to ensure `node-gyp` is working.

The second is that `karma` should not be installed globally, it should be installed locally to your project and to get `karma` as a binary into your path you should run `npm install -g karma-cli`.

**Comment by rajeevkb** [comment]
Thanks for this (Problem resolved, but there is one issue left),  
Python 2.7.10
I have followed the same steps from Windows section
 Downloaded : https://www.python.org/ftp/python/2.7.10/python-2.7.10.amd64.msi
 Installation Done:
 Verified with Path Envirnoment Variables.
It works fine with npm install -g karma-cli.

I am also getting another issue Node pattern, is mis match patterm, refer below screen shot.
![node_pattern](https://cloud.githubusercontent.com/assets/2646890/9880571/bba9d778-5be9-11e5-9e6e-cfb50772d4ee.png)

**Comment by Dignifiedquire** [comment]
You need use `*.js` and not `**.js`

**Comment by rajeevkb** [comment]
Yes, sorry silly mistake. that is resolved.
I was struggling installation issue from last 1 day.
Now I am going to write test cases.

**Comment by Dignifiedquire** [comment]
Enjoy :)
