### ISSUE TITLE
included: false getting 404ed when the paths are 1:1 map

### ISSUE THREAD

**Issue by mohsen1** [karma-runner/karma#1590]
I had to apply `proxies` to be able to serve files locally where the proxy itself was something redundant

Here is my `files`:

``` js
files: [
      {pattern: 'index.js', included: true},
      {pattern: 'spec/tests.js', included: true},
      {pattern: 'bower_components/**/*.js', included: false},
      {pattern: 'worker.js', included: false},
    ],
```

with this, `worker.js` was 404-ing.

But when I added this unnecessary proxy, it worked: 

``` js
 proxies: {
      '/worker.js': path.join(__dirname, 'worker.js'),
      '/bower_components/': path.join(__dirname, 'bower_components')
    },
```

Here is the commit  I made the change I described above: https://github.com/mohsen1/yaml-worker/commit/ec411035d2ec4b7c87277458666375cc91a0c293

Karma version: `karma": "^0.13.2",`

**Comment by DarthCharles** [comment]
Yep, looks like something is odd. I recommend you to use karma 0.12. This has already been reported in #1530

**Comment by devoto13** [comment]
This sounds like a valid bug to me. However, there have been many changes to the libraries since it was reported. Please open a new issue including a minimal reproduction if you still experience this problem.
