### ISSUE TITLE
Option Single-run not working anymore

### ISSUE THREAD

**Issue by Sabartius** [karma-runner/karma#1591]
Hey,

i am using Chrome with Karma to test my Website. For testing on my CI-server i use the single-run option. This worked fine, until Chrome updated itself. After the Update to Chrome Version 45.0.2454 the karma-process does not return anymore, so i have to manually kill it (in my bash with ctrl-c, funny thing is, i need to press it twice, one press is not enough).

Im working on Centos 7 using node v0.12.7 and karma v0.13.10.

**Comment by Dignifiedquire** [comment]
Are you seeing this in all projects, and are you able to test this on a different OS?

**Comment by Sabartius** [comment]
I'm having this problem with several projects and machines. Unfortunatly i have no other OS to test on.

**Comment by Sabartius** [comment]
As of Chrome Version 46 this bug is not present anymore. So this wasn't a karma problem in the first place. Closing this now.

**Comment by Dignifiedquire** [comment]
Thanks for the update
