### ISSUE TITLE
Allow configuration of listener `hostname`

### ISSUE THREAD

**Issue by larkin** [karma-runner/karma#1593]
Karma does not currently expose a method for specifying the server's listener `hostname`.  So, by default, the web server runs and binds to `0.0.0.0` and `::`, which means that it is accessible by anyone on the same network as you.  Depending on the project you are working on, you may not want your test config available to that nice looking gentleman sitting on the other side of the coffee shop.

I would like to be able to change the listener hostname in the configuration so that I can bind to the loop back address and keep my files private.

**Comment by maksimr** [comment]
@larkin
Join this issue with #2477 
It will be nice if you or @grifball create pull request

Thanks!
