### ISSUE TITLE
karma 0.13 significantly slower than 0.12

### ISSUE THREAD

**Issue by peacechen** [karma-runner/karma#1608]
We've introduced ES6 into our codebase which requires transpiling it with Babelify.  I experimented with grunt-karma preprocessors but due to slow performance went with pre-bundling the unit tests.  Even after doing so, the karma unit tests run much slower.  Approx 1300 tests used to run in 76 seconds; after bundling it takes 118 seconds.

Transpiling each test separately skyrocketed the time to over 200 seconds.  I expected the pre-bundling to eliminate all delay from the original 76 seconds. It helped but there's still a performance hit.

The tests used to run at a fairly steady clip.  After transpilation it runs in fits & starts.  It'll run 10 tests quickly, then stall for a dozen seconds, then run 12 more tests, then stall, etc.  Debug loglevel doesn't report anything unusual.  How should I dig deeper to find out what's slowing things down?

**Comment by peacechen** [comment]
I had upgraded from karma 0.12.23 to 0.13.10 to aid supporting ES6.  That led me to believe the slowdown was an ES6 issue.  However I've now narrowed the performance issue down to karma 0.13.10, with or without ES6.  Is this a known issue, and is there anything that can be done about it on the user's end?

**Comment by Dignifiedquire** [comment]
Thanks for the investigation. No it's not a known issue that performance is worse, I actually saw improved performance in areas like file watching.

**Comment by peacechen** [comment]
This problem appears to manifest with a large number of tests.  When the number of tests is small (say ~50), karma executes fairly fast.  With our full suite of 1300 tests, karma 0.13 adds significant delay compared to 0.12.

**Comment by nmccready** [comment]
Yes I am seeing this as well in [angular-leaflet-directive](https://github.com/tombatossals/angular-leaflet-directive). 
To test:
- clone our project
- run `grunt default` specs should run (not as fast as I like but they do run within reason)
- bump grunt-karma and karma to latest versions.
- run `grunt default` specs run, eventually (wait is way too long)

You will see karma almost essentially hang.

Now funny thing to note is I am using karma at work and I have not noticed this slowdown when using gulp. So this might be a grunt-karma issue. 


I will file an issue with grunt-karma as well.

**Comment by nmccready** [comment]
Actually I am seeing slowness in gulp, but not as bad.

**Comment by nmccready** [comment]
Any update on this?

**Comment by nmccready** [comment]
Actually I think I finally figured this out. It was basically broke in 0.12.X for us, but it was easier to debug.

Basically our globs were far to relaxed.

```
files: [
{pattern:'**/**/**/*.coffee', included: false},
 {pattern: '**/*.js.map', included: false}
]
```

changed to:
```
files: [
            {pattern:'test/**/**/*.coffee', included: false},
            {pattern: 'dist/**/*.js.map', included: false}
        ],
```

In 0.12.X I would eventually run out of memory where in 0.13.X it just hangs.

**Comment by EzraBrooks** [comment]
Looks like this issue is solved. If the above fix doesn't work, please try on a newer version of Karma.
