### ISSUE TITLE
Allow for multiple preprocessors to be chained

### ISSUE THREAD

**Issue by dignifiedquire** [karma-runner/karma#161]
As discussed before we need the ability to chain preprocessors. I suggest the following api.

``` js
preprocessors = {
  '**/coverage/*.coffee': ['coffee', 'coverage'],
  '**/other/*.coffee': 'coffee'
};
```

This would allow you to specify an array of preprocessors in exactly the order you want them to be executed or if you just define one, only this one will be executed.

Gonna implement this later this day if I find the time.

**Comment by HamletHakobyan** [comment]
It would be better to have possibility to bypass part of input files by specific processor. It will be handy in cases like, for example karma-coverage when using webpack. We can pass all test and source files to pipeline where chained coverage then webpack. We can bypass the test files for coverage then pack them all.
