### ISSUE TITLE
bin folder is missing in release 0.13.10

### ISSUE THREAD

**Issue by volkanunsal** [karma-runner/karma#1613]
Is this a mistake? What replaces it?

**Comment by maksimr** [comment]
@volkanunsal it should be. What Operation System and version of npm?
Could you post file structure in folder `node_modules/karma`

Thanks!

**Comment by volkanunsal** [comment]
I think I had an old version of npm. Upgrading npm fixed the problem. Thanks.

**Comment by maksimr** [comment]
@volkanunsal no problems!
