### ISSUE TITLE
SyntaxError: Parse error with javascript const

### ISSUE THREAD

**Issue by cs0511** [karma-runner/karma#1621]
Dear Karma 

   I am using Karma for unit test in my Angularjs project.

   In one of my code, I have 

```
    const SAY = 'hello';
```

  When I run test, I got errors

```
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  SyntaxError: Parse error
```

I don't exactly know if this was cased by phantomjs. Could you give me some clue?

Thanks

**Comment by Dignifiedquire** [comment]
Phantomjs does not understand `const` as this is an ES2015 feature. You will need to preprocess your code with something like [babel](http://babeljs.io/) or [typescript](http://www.typescriptlang.org/) to make this code run in Phantomjs.

**Comment by wesleycho** [comment]
Closing this as a support ticket - PhantomJS uses quite an outdated version of Webkit, so one cannot use most raw ES2015 features with it.
