### ISSUE TITLE
XHR and Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by jshohel** [karma-runner/karma#1627]
Hi,

One of the method that I am testing sends a XMLHttpRequest to "http://localhost:4848/qrs/extension/schema?xrfkey=asdfasdfdf". I am getting an error which looks like this -

```
XMLHttpRequest cannot load http://localhost:4848/qrs/extension/schema?xrfkey=asdfasdfdf. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9875' is therefore not allowed access. The response had HTTP status code 404.
```

Now I understand that test are served on "localhost:9876", and trying access localhost:4848 is actually violating cross domain policy. I have seen the karma proxy settings and tried -

```
proxies: {
   '/qrs': 'http://localhost:4848/qrs'
}
```

But doing this actually serves my content from "http://localhost:9876/qrs/extension/schema?xrfkey=asdfasdfdf". But this way my client code will not work. Because client code directly sends XHR request to "http://localhost:4848/qrs/.....", but NOT to "http://localhost:9876/qrs/.....".

Any suggestion how can I solve this?

Also, wouldn't it be better to have an option to set different headers in the config file? At lest we know that we are talking about test here (I mean not in production).

Thanks in advance.

**Comment by wesleycho** [comment]
If it directly requests `http://localhost:4848/qrs/...`, then there is nothing you can do. One thing that can be done is to change the request url to hit `/qrs/extension/schema?...` in the client code, and have a proxy in your codebase to send the request over to.

Even better would be to mock out the XHR mechanism, that way it avoids fragility from testing the server/client interaction.

**Comment by DmitryEfimenko** [comment]
actually, for these who has an issue similar to mine, [this is how I solved it](https://stackoverflow.com/a/49076615/894273)

**Comment by devoto13** [comment]
Closing as everything works as designed. Use [the workaround](https://github.com/karma-runner/karma/issues/1627#issuecomment-455323907) if you're unable to properly configure your code/servers for some reason.
