### ISSUE TITLE
Silent failure when using special characters with wrong file encoding

### ISSUE THREAD

**Issue by tomcooksey** [karma-runner/karma#1641]
We are writing tests using Jasmine and running them with Karma.  We are experiencing a silent failure when using special characters in our tests and the encoding is not UTF8.  Obviously we understand that this is a problem that we need to fix but we have a large, distributed development team, and having Karma fail with an appropriate error would be useful.

To reproduce run an assertion like this:

expect(currencyCharacter).toBe('ç');

Within a test script that is encoded in, for instance, US-ASCII and the tests will seemingly pass whatever their state.  I should add we are running this within gulp using gulp-karma.  We haven't found a way to reliably determine the encoding of a particular file and throw the error ourselves.

**Comment by Dignifiedquire** [comment]
Thanks for the report, this should obviously not result in a passing test, do I understand right that 

```js
expect('c').toBe('ç')
```

passes if saved as an ascii file?

**Comment by tomcooksey** [comment]
Seemingly, yes.  When we include this file during our test run we get a false positive when we actually know we have failing tests.  When removing this assertion we get our failures as expected again.

**Comment by tomcooksey** [comment]
This is on a Windows 7 environment for your information.

**Comment by devoto13** [comment]
I've tried to check it and could not reproduce the problem. Used attached files (`my-test.js` is encoded as ISO-8859-1, because it is impossible to represent `ç` in US-ASCII according to my editor) and ran `karma start`. 

[files.zip](https://github.com/karma-runner/karma/files/6291879/files.zip)

```
$ karma start
11 04 2021 15:27:44.742:INFO [karma-server]: Karma v6.3.2 server started at http://localhost:9876/
11 04 2021 15:27:44.745:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
11 04 2021 15:27:44.753:INFO [launcher]: Starting browser Chrome
11 04 2021 15:27:46.895:INFO [Chrome 89.0.4389.114 (Mac OS 11.2.3)]: Connected on socket NSsNXe4wMNO0Iz24AAAB with id 35834951
Chrome 89.0.4389.114 (Mac OS 11.2.3) test test FAILED
	Error: Expected 'c' to be '�'.
	    at <Jasmine>
	    at UserContext.<anonymous> (my-test.js:3:17)
	    at <Jasmine>
Chrome 89.0.4389.114 (Mac OS 11.2.3): Executed 1 of 1 (1 FAILED) (0.002 secs / 0.003 secs)
TOTAL: 1 FAILED, 0 SUCCESS
```

Please open a new issue including a minimal reproduction if you still experience this problem.
