### ISSUE TITLE
Does not load local plugins when runing from cli globally

### ISSUE THREAD

**Issue by inf3rno** [karma-runner/karma#1649]
![nevtelen](https://cloud.githubusercontent.com/assets/408911/10652499/7558a170-7857-11e5-83b5-e467a5d6ac94.png)

Any idea? (windows 7 x64 and node 0.12 if that matters)

**Comment by inf3rno** [comment]
I think I know what the problem is. I run the global karma instead of the karma I installed. Maybe that causes the problem.

**Comment by inf3rno** [comment]
Yepp, solved with these lines in the package.json:

```js
  "scripts": {
    "test": "node ./node_modules/karma/bin/karma start",
    "node-test": "node ./node_modules/jasmine/bin/jasmine",
    "build": "node ./node_modules/gulp/bin/gulp build"
  },
```
So it uses local libs now. I am not sure whether there is a better solution or not. It's working, that's enough to me.

**Comment by grassick** [comment]
Found this issue! If you install karma globally, it will always fail to load plugins that are local since it does not have the code from karma-cli to use the local one:

```
resolve('karma', {basedir: process.cwd()}, function (err, pathToKarma) {
  // There is a local version, let's use it.
  if (!err) {
    return requireCliAndRun(pathToKarma.replace(/(\/|\\)lib(\/|\\)index\.js/, ''))
  }
...
```

Solution:

`npm uninstall karma -g`
`npm install karma-cli -g`

This extra code should maybe be added to `karma` too to prevent this.

**Comment by inf3rno** [comment]
@grassick I assume this is a karma issue and not a nodejs issue then. I reopened, maybe somebody fixes it.

**Comment by ttbarnes** [comment]
Uninstalling karma globally and installing karma-cli globally works for me, thanks for the tip @grassick.
