### ISSUE TITLE
Determine if full page reload error is obsolete

### ISSUE THREAD

**Issue by FuzzySockets** [karma-runner/karma#1656]
@Dignifiedquire After the previous fixes to the reloadingContext flag, I'm unable to trigger the full page reload error at all regardless of what I put in my jasmine tests.  I've tried causing a page reload via window.location.reload(), window.location.href = '', window.location.assign, etc... None of these trigger the error.

Did our fixes to the reloadingContext flag break some important behavior?  Or is the full page reload error (Some of your tests did a full page reload!) now obsolete?

**Comment by Dignifiedquire** [comment]
No it's not obsolete, if that is the case that means our fixes our not working as intended. I'm afraid I will have to roll back to the earlier version then for now until we figure out a better way :(

**Comment by FuzzySockets** [comment]
@Dignifiedquire This appears to be an issue with jasmine-core.  Refer to https://github.com/jasmine/jasmine/issues/366

**Comment by Dignifiedquire** [comment]
@FuzzySockets thanks for digging into this!

**Comment by adjavaherian** [comment]
So, it looks like a jasmine-core issue?  I'm seeing this on one environment but not another. 
http://stackoverflow.com/questions/35189214/karma-sauce-labs-test-failing-in-one-environment

**Comment by adambiggs** [comment]
I'm seeing this issue intermittently from Chrome when running a large (5000+) test suite in multiple browsers (Chrome, Firefox, and PhantomJS). Using the latest version of Karma.

**Comment by shaharmor** [comment]
Hi, is there any intention to do this today? I am seeing this error when using Karma + Mocha as well.
The tests are all passing but somewhere in the middle i (sometimes) see a "Page reload" error which causes the entire suite to fail even though all tests passed.
Can we somehow make Karma just return the correct exit code and ignore this error?

**Comment by madnight** [comment]
I found something interesting if you run the tests separate:
```
- npm run test  # firefox, phantom, .... all you like execpt chrome
- npm run test-travis-chrome # only chrome
```
then this page reload error does not occur, however this solution results in longer test run times, since they are executed twice

**Comment by madnight** [comment]
`Chromium 37.0.2062 (Ubuntu 0.0.0) ERROR
  Some of your tests did a full page reload!`

still an issue

**Comment by devoto13** [comment]
This sounds like a valid bug to me. However, there have been many changes to the library since it was reported. Please open a new issue including a minimal reproduction if you still experience this problem.
