### ISSUE TITLE
Testing with requestAnimationFrame

### ISSUE THREAD

**Issue by gabrielelanaro** [karma-runner/karma#1670]
Hi, I have a WebGL app that I'd like to test, but now I'm stumbling upon making the app animate for debugging purposes. So far karma has been "ignoring" requestAnimationFrame (likely because once a test is run, it is "stopped".

One solution would be for example to "block" the execution of the program, is there any way to accomplish that?

**Comment by Dignifiedquire** [comment]
Do you have a small sample to test with?

**Comment by EzraBrooks** [comment]
Two years later, no further discussion. Closing.
