### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by DavidHolzgang** [karma-runner/karma#1682]
Hi Folks...

On the page 
http://karma-runner.github.io/0.13/intro/installation.html
you have an FAQ link with the href of 
http://karma-runner.github.io/0.13/intro/04-faq.md#which-version-of-nodejs-does-karma-run-with-
which is broken.

I believe this should be 
http://karma-runner.github.io/0.13/intro/faq.html

**Comment by zzo** [comment]
thanks want to make a PR? :)

**Comment by DavidHolzgang** [comment]
Hi Mark...

Ummm... I'll give it a try. Never done that for a public repo or for documentation. ;-)

**Comment by DavidHolzgang** [comment]
Hi Mark...

Gave it

**Comment by DavidHolzgang** [comment]
Hi Mark...

Sorry for the interrupted message before. Anyway, I gave it a shot. Hope
this help.

Cordially,
DHz

**Comment by zzo** [comment]
I do not see your PR?
thanks!
  Mark

**Comment by wesleycho** [comment]
Closing, as this appears to be fixed by https://github.com/karma-runner/karma-runner.github.com/commit/c2760258284cb195f60dd8e961ecbc065b9a88ce#diff-dc3f769f4b7820f0f31d4c5c9065b392
