### ISSUE TITLE
Progress reporter: skipped/overall count broken when `pending()` used inside `describe`

### ISSUE THREAD

**Issue by jrencz** [karma-runner/karma#1683]
I've got ~1k unit tests in my project

When I skip some of them by switching `describe` to `xdescribe` Karma counts tests as skipped (let's say that in that describe I had 21 tests) and the overall counter is not decreased. But Jasmine allows `panding()` to be used to suppress test execution as well.
http://jasmine.github.io/2.0/introduction.html#section-Pending_Specs
According to the spec it works in `it`s, but when `pending()` is placed inside `describe()` Karma won't run all `it`s inside. Seems legit. But the progress reporter acts weird:

with `describe` (I have 95 tests skipped in other suites)
PhantomJS 1.9.7 (Mac OS X 0.0.0): Executed 899 of 994 (skipped 95) SUCCESS (4.732 secs / 4.317 secs)

with `xdescribe` instead of `describe`
PhantomJS 1.9.7 (Mac OS X 0.0.0): Executed 877 of 994 (skipped 117) SUCCESS (4.645 secs / 4.125 secs)
(21 more skipped, overall as before)

with `pending()` call inside describe:
PhantomJS 1.9.7 (Mac OS X 0.0.0): Executed 877 of 973 (skipped 96) SUCCESS (4.986 secs / 4.211 secs)
(21 less overall AND 1 more in skipped)

I suggest that tests that are pending should either be reported as skipped or reported should report pending tests in some other way than skipped ones.

**Comment by devoto13** [comment]
I've tried with the below test code:

```js
describe('test', function () {
  pending()

  it('test1', () => {
    expect('c').toBe('c')
  })

  it('test2', () => {
    expect('c').toBe('c')
  })

  it('test3', () => {
    expect('c').toBe('c')
  })
})

```

And got the below result:

```
Chrome 89.0.4389.114 (Mac OS 11.2.3) ERROR
  An error was thrown in afterAll
  => marked Pending thrown
Chrome 89.0.4389.114 (Mac OS 11.2.3): Executed 0 of 0 ERROR (0.008 secs / 0 secs)
```

Then I've tried with the below test code based on https://github.com/jasmine/jasmine/issues/1579.

```js
describe('test', function () {
  beforeEach(() => {
    pending()
  })

  it('test1', () => {
    expect('c').toBe('c')
  })

  it('test2', () => {
    expect('c').toBe('c')
  })

  it('test3', () => {
    expect('c').toBe('c')
  })
})
```

And got the expected output:

```
Chrome 89.0.4389.114 (Mac OS 11.2.3): Executed 0 of 3 (skipped 3) SUCCESS (0.001 secs / 0 secs)
```

I assume what happens is that call to `pending()` directly inside `describe` throws and no further code is executed, hence `it()` calls are never executed and Jasmine has no idea that these tests exist. So the total count is 0. AFAIU this is plainly incorrect usage of `pending()` and hence there is nothing to fix here.

**Comment by jrencz** [comment]
@devoto13 thank you for the explanation. You're clearly right, and I was so inexperienced at the time I filed this report I haven't thought about just trying `beforeEach`
