### ISSUE TITLE
Is there a way to run a subset of tests?

### ISSUE THREAD

**Issue by jamesshore** [karma-runner/karma#1709]
I have two directories with tests--let's call them `fast` and `slow`. I want to run `fast` under some circumstances and `slow` under other circumstances. Is there any way to configure Karma to do this, without restarting the Karma server between test runs?

**Comment by jcrben** [comment]
I'm not sure, but you might take a look at https://github.com/karma-runner/karma/issues/1507

**Comment by jamesshore** [comment]
The `--grep=<pattern>` trick will do, and it doesn't actually require a restart. Thanks!

**Comment by GBarthos** [comment]
but still, is it possible to do this through the public API ?
