### ISSUE TITLE
You need to include some adapter that implements __karma__.start method!

### ISSUE THREAD

**Issue by randallmeeker** [karma-runner/karma#1715]
Have attempted research on this error and found many people with it, but no solution avails.

```
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  You need to include some adapter that implements __karma__.start method!
```

Node 5.0

Installed Deps
```
  "devDependencies": {
    "browser-sync": "^2.9.3",
    "codeclimate-test-reporter": "^0.1.1",
    "dev-ip": "^1.0.1",
    "express": "^4.13.3",
    "gulp-print": "^2.0.1",
    "gulp-rename": "^1.2.2",
    "gulp-template": "^3.0.0",
    "gulp-todo": "^4.0.0",
    "gulp-watch": "^4.3.5",
    "jasmine-core": "^2.3.4",
    "karma": "^0.13.15",
    "karma-babel-preprocessor": "^6.0.1",
    "karma-chrome-launcher": "^0.2.1",
    "karma-jade-preprocessor": "0.0.11",
    "karma-jasmine": "^0.2.2",
    "karma-ng-html2js-preprocessor": "^0.2.0",
    "karma-phantomjs-launcher": "^0.2.1",
    "phantomjs": "^1.9.18",
    "readline": "^1.0.0",
    "string": "^3.3.1"
  },
```

Karma Config.js
```
module.exports = function(config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine'],
    files: files,
    exclude: [
    ],
    preprocessors: {
      'src/**/*.jade': ['jade', 'ng-html2js'],
      'src/**/*.js': ['babel']
    },
    reporters: ['progress'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_DEBUG,
    autoWatch: true,
    browsers: ['PhantomJS'],
    singleRun: false,
    concurrency: Infinity,
    ngHtml2JsPreprocessor: {
      moduleName: 'templates',
      cacheIdFromPath: function(filepath) {
        var id = filepath.slice( filepath.lastIndexOf( '/' ) + 1 ).replace( '.jade', '' )
        return id
      }
    },
  })
}
```

**Comment by Dignifiedquire** [comment]
How did you install karma?

**Comment by randallmeeker** [comment]
followed instructions found here
http://karma-runner.github.io/0.13/intro/installation.html

**Comment by randallmeeker** [comment]
I forgot to include in my original comment that this was tested using both PhantomJS and Chrome, resulting the same error.

**Comment by Dignifiedquire** [comment]
Odd, could you provide a small repo that reproduces this? (It's probably not finding the correct version of the adapter for some reason)

**Comment by henriklundgren** [comment]
Pretty sure this is related to miss configuration of babel-preprocessor,

1. make sure you include the babel-polyfill.
2. also configure babel, ie probably want the es2015 preset and so on.

Check https://github.com/babel/karma-babel-preprocessor#configuration

**Comment by randallmeeker** [comment]
This looks to be an issue with the jade preprocessor which does not look like it is maintained. I'll close this but will update with the specific problem the jade preprocessor is causing when I find it.

**Comment by randallmeeker** [comment]
Going to dig into this further, but as requested here is a repo that will generate the error.

https://github.com/randallmeeker/karma-runnner-test

**Comment by henriklundgren** [comment]
npm version out of date, clone repo instead
https://github.com/ojdx/karma-jade-preprocessor/pull/2

**Comment by Denis-Evseev** [comment]
npm 3.5.0 version

**Comment by hasmukh** [comment]
Can anyone please  see this https://github.com/karma-runner/karma/issues/2171 ?
I am new to Node, phantom, gulp and Karma. 
Any help will be appreciated.
