### ISSUE TITLE
Allow specifying the javascript version in the debug html window

### ISSUE THREAD

**Issue by simonzack** [karma-runner/karma#1719]
I would like to test javascript 1.8 as this is what I would like my target to run on (greasemonkey on firefox), but currently `SCRIPT_TYPE` is hard-coded

            return util.format(SCRIPT_TAG, SCRIPT_TYPE[fileExt] || 'text/javascript', filePath)

without `application/javascript;version=1.8` firefox runs ES5 only, so can there be some option to put this in the config?

**Comment by Moumi** [comment]
@simonzack This is possible to do. However, in case the user uses multiple browsers, this might go wrong. If, in any case Chrome is used to run besides Firefox 4 (which supports 1.8 now), the tag will make the tests all fail. Even more, Karma will throw an **Error**. 

I was able to make the configuration for you and was wanting to add a PR for it, but I stumbled upon the error part of Karma when trying to add the tag when running Chrome. Maybe @dignifiedquire has an idea how to make this fail-safe?

**Comment by dignifiedquire** [comment]
Not sure (I never had to use this in a real world example before)
But we just merged custom context and debug files in #1825  so maybe that can help you to specify exactly what you want.

**Comment by Moumi** [comment]
I have seen that, but it is not exactly what I'm looking for. The case would be that Firefox 4 *supports* 1.8, but Chrome (even latest version) does *not*. This makes it that in the *karma.js*-file, when the Firefox 4 browser is run, it should add the tag of ";version=1.8", otherwise not. I'd think that there should be some check which browser is being run at that moment and perhaps the version of it. 

This might be a solution to it, but takes the effort to update this *whitelist* of browsers to be updated everytime a new update comes out...

**Comment by Moumi** [comment]
@dignifiedquire: Do you know a possible way to capture the current browser being run? That would solve the issue mainly.

**Comment by dignifiedquire** [comment]
@Moumi capture it where?

**Comment by Moumi** [comment]
@dignifiedquire: At https://github.com/karma-runner/karma/blob/master/lib/middleware/karma.js just before the return statement:
*return util.format(SCRIPT_TAG, SCRIPT_TYPE[fileExt] || 'text/javascript', filePath)*

**Comment by Moumi** [comment]
@dignifiedquire ping

**Comment by dignifiedquire** [comment]
I don't think that will easily work as the file is simply served to every browser the same atm. You could check the express docs how to do browser detection in a single request

**Comment by Moumi** [comment]
@dignifiedquire I managed to get the full functionality working. I wanted to create a PR, but I wanted to write a test or 2 for it too. However, it seems very difficult to test it. The check to add the tag depends on:

1. If the configuration is set
2. If the current browser is Firefox. Which is derived from a request and the user-agent header in it.

Well, how can you force during a test that the user-agent should say "Firefox"? If you could help me with figuring this out, that'd be great and this issue would be fixed (I hope). I am just learning about *Sinon* and it isn't that clear to me either.

**Comment by dignifiedquire** [comment]
@Moumi your best bet is to use an e2e test (see `test/e2e`) which can specify a browser type and does a full karma run and checks the output.

**Comment by Moumi** [comment]
I managed to create a fix and two e2e tests for it. I will provide a PR this evening for it.
