### ISSUE TITLE
Feature suggestion: Proxying a request may want to change the Host header

### ISSUE THREAD

**Issue by Volune** [karma-runner/karma#1729]
I have a case where I need karma to proxy requests with a specific Host header (matching the target configuration).

The http-proxy module, used by karma, has an option to do so: `changeOrigin`. I would like to be able to enable this option in the configuration file, per proxy.

I have a suggestion of solution ready at [this branch](/Volune/karma/commits/feature-proxies-changeorigin)
Example of configuration in config file:
```
proxies: {
        '/foo': 'http://foo.localhost',
        '/bar': {
            target: 'http://bar.localhost',
            changeOrigin: true
        }
    }
```

Thanks

**Comment by Dignifiedquire** [comment]
I think as we are already providing the functionality of proxying we might as well allow this. So please send a PR and I'll review it :smile:
