### ISSUE TITLE
`karma run` overwrites client.args state

### ISSUE THREAD

**Issue by danielcompton** [karma-runner/karma#1746]
### Summary

`karma run` calls this line [lib/middleware/runner.js#L50](https://github.com/karma-runner/karma/blob/v0.13.15/lib/middleware/runner.js#L50) which overwrites the state of `config.client.args` with an empty array. This means that plugins that rely on `config.client.args` will run when calling `karma start`, but fail after calling `karma run` once (even when they are subsequently autorun from the `karma start` process).

### Details

I'm using [karma-cljs-test](https://github.com/honzabrecka/karma-cljs-test) to run my ClojureScript tests. It needs a main function to be provided in `config.client.args`. I was able to run my tests successfully through the auto runner in `karma start` but when I called `karma run`, my tests would fail to run as `config.client.args` had been overwritten with an empty array. Because `config` is a mutable object, once I had called `karma run` once, my tests would fail when being rerun by the `karma start` autorunner.

Commenting out 

```js
config.client.args = data.args
```

let my tests pass, but this is clearly not a viable solution. One option would be to only set `config.client.args` if `data.args` is not an empty array. 

This also raises the wider question of why a `karma run` is setting global mutable state. That behaviour was surprising to me, and I don't think it is intentional.

This behaviour seems to have been introduced in https://github.com/karma-runner/karma/commit/ca4c4d88b9a4a1992f7975aa32b37a008394847b, and relates to https://github.com/karma-runner/karma/commit/27b8d678cdc43f823d2531d25fc548d542dc9078, https://github.com/karma-runner/karma/issues/283, https://github.com/karma-runner/grunt-karma/issues/79, https://github.com/karma-runner/grunt-karma/issues/79, https://github.com/karma-runner/grunt-karma/commit/b658ec9701c7a35673a3011b703e3888364a3733 and https://github.com/karma-runner/grunt-karma/commit/168f7b7a6af02e78e44b87b27553cdb65785221c.

**Comment by xtianjohns** [comment]
Some introspection into whether or not the objects share properties would be really great.

I'm experiencing a pretty crummy situation right now with [`karma-browserstack-launcher`](https://github.com/karma-runner/karma-browserstack-launcher) that involves parameterizing Browserstack access keys.

`karma.conf.js`:

```js
//...
browserStack: {
  'startTunnel': true,
  'project': 'some_project_name',
  'build': 'some_build_name',
  'rateLimitTimeout': 5000
},
//...
```
This command, run by Jenkins or some other CI system that wants to pass username/access tokens would look like:
```sh
karma start --browserstack.username=my_username --browserstack.accessKey=some_key
```
Executing this will essentially throw away any configuration that would have been made in `karma.conf.js`.

The workaround in my situation is to have the CI pass all of the arguments. And then I lose all of the flexibility of having the keys in a configuration file for developers to share.

I'm not sure whether your situation, @danielcompton, is unique to `karma run` or not, I've only experienced my behavior with `karma start` and haven't tried `karma run`.

**Comment by danielcompton** [comment]
This sounds like a similar problem of handling input from the command line, although the exact mechanics to fix it will be different.

**Comment by Dignifiedquire** [comment]
Thanks @danielcompton for the detailed write up. From looking at this I feel the most sensible option would be to merge the two together (with the options provided from `run` taking precedence) rather than replacing them. Do you think that would be a good solution?

**Comment by danielcompton** [comment]
>  I feel the most sensible option would be to merge the two together

Yep, I think you're right, that was the conclusion I came to. I think it would also be good to make the Karma config created at `karma start` immutable, and have `karma run` make a copy of the config. However that sounds like a much bigger change :)
