### ISSUE TITLE
Delete erroneous tags

### ISSUE THREAD

**Issue by danielcompton** [karma-runner/karma#1747]
It looks like the tags `v1.0.0-0` and `rm` should be deleted?

![screenshot of safari 4-12-15 4-07-49 pm](https://cloud.githubusercontent.com/assets/811954/11580925/4720d270-9aa1-11e5-8423-d0c615a1f1ab.png)

**Comment by Dignifiedquire** [comment]
Thanks, should be cleaned up now

**Comment by danielcompton** [comment]
Might pay to run http://stackoverflow.com/questions/19542301/delete-all-tags-from-a-git-repository and then `git fetch` for everyone who has push access to prevent the tags being created again.
