### ISSUE TITLE
Run QUnit within HTML pages

### ISSUE THREAD

**Issue by ernsheong** [karma-runner/karma#1752]
Hi all,

In my project we have a lot of QUnits run in various HTML pages as described at the top of https://qunitjs.com/cookbook/ 

Would it be possible to configure Karma to be able to run these HTML pages, instead of running the JS file directly? I've looked at `karma-html2js-preprocessor`, but it doesn't look like a solution.

`grunt-contrib-qunit` project allows this to be done via PhantomJS, but the integration with RequireJS is problematic and unreliable using PhantomJS (and hard to debug). Karma seems the most promising as tests can be run in Chrome/IE, etc.

Thanks in advance,
Jonathan

**Comment by Dignifiedquire** [comment]
I'm afraid it's not really possible at the moment, but there is a PR to allow a custom html page for setups like this here: #1360

**Comment by ernsheong** [comment]
Thanks for the reply 👍

Jonathan

    _____________________________
