### ISSUE TITLE
windows 10 karma 0 13 15 does not execute tests [solved]

### ISSUE THREAD

**Issue by Denis-Evseev** [karma-runner/karma#1755]
// Karma configuration
// Generated on Tue Jul 22 2014 13:41:07 GMT+0400 (Russian Standard Time)

module.exports = function (config) {
    config.set({

        // base path that will be used to resolve all patterns (eg. files, exclude)
        basePath: '../',

        // frameworks to use
        // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
        frameworks: ['jasmine'],

        // list of files / patterns to load in the browser
        /*
         * "~/src/assets/libs/jquery-{version}.js",
                "~/src/assets/libs/moment.js",
                "~/src/assets/libs/bootstrap.js",
                "~/src/assets/libs/angular.js",
                "~/src/assets/libs/angular/angular-ui-router.js",
                "~/src/assets/libs/angular/ui-bootstrap-tpls.js",
                "~/src/assets/libs/angular/ui-grid.js",
                "~/src/assets/libs/angular/angular-moment.js",
                "~/src/assets/libs/angular/datetime-picker.js",
                "~/src/assets/libs/angular/angular-local-storage.js",
                "~/src/assets/libs/angular/ng-tags-input.modified.js",
                "~/src/assets/libs/angular/ng-file-upload.js"
         */
        files: [
            { pattern: 'Bleu.Web/src/assets/libs/jquery-2.1.4.js', included: true },
            { pattern: 'Bleu.Web/src/assets/libs/moment.js', included: true },
            { pattern: 'Bleu.Web/src/assets/libs/bootstrap.js', included: true },
            { pattern: 'Bleu.Web/src/assets/libs/angular.js', included: true },
            { pattern: 'Bleu.Web/src/assets/libs/angular/angular-ui-router.js', included: true },
            { pattern: 'Bleu.Web/src/assets/libs/angular/ui-bootstrap-tpls.js', included: true },
            { pattern: 'Bleu.Web/src/assets/libs/angular/ui-grid.js', included: true },
            { pattern: 'Bleu.Web/src/assets/libs/angular/angular-moment.js', included: true },
            { pattern: 'Bleu.Web/src/assets/libs/angular/datetime-picker.js', included: true },
            { pattern: 'Bleu.Web/src/assets/libs/angular/angular-local-storage.js', included: true },
            { pattern: 'Bleu.Web/src/assets/libs/angular/ng-tags-input.modified.js', included: true },
            { pattern: 'Bleu.Web/src/assets/libs/angular/ng-file-upload.js', included: true },
            { pattern: 'Bleu.Web/src/assets/libs/angular/ng-sortable.js', included: true },
            { pattern: 'Bleu.Web/src/assets/libs/angular/angular-ui-tree.js', included: true },
            { pattern: 'Bleu.Web/src/app/*/*.js', included: true },
            { pattern: 'Bleu.Web/src/core/*/*.js', included: true },
            { pattern: 'Bleu.Web/src/**/services/*.js', included: true },
            { pattern: 'Bleu.Web/src/**/models/*.js', included: true },
            { pattern: 'Bleu.Web/src/**/mappers/*.js', included: true },
            { pattern: 'Bleu.Web/src/**/constants/*.js', included: true },
            { pattern: 'Bleu.Web/src/**/enums/*.js', included: true },
            { pattern: 'Bleu.Web/src/**/helpers/*.js', included: true },
            { pattern: 'Bleu.Web/src/core/main/transports/FakeTransport.js', included: true },
            { pattern: 'Bleu.Web.Tests.Client/mocks/*/*.js', included: true },
            { pattern: 'Bleu.Web.Tests.Client/mocks/**/*.js', included: true },
            { pattern: 'Bleu.Web.Tests.Client/testData/**/*.js', included: true },
            { pattern: 'Bleu.Web.Tests.Client/Specs/**/*.js', included: true },
            { pattern: 'Bleu.Web/src/assets/libs/d3.js', included: true },
            { pattern: 'Bleu.Web/src/assets/libs/nv.d3.js', included: true },
            { pattern: 'Bleu.Web/src/assets/libs/angular/angularjs-nvd3-directives.js', included: true }
        ],

        // list of files to exclude
        exclude: [
        ],

        // preprocess matching files before serving them to the browser
        // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
        preprocessors: {
        },

		proxies: {
            '/src/app': '/base/.build/app',
        },
		
        // test results reporter to use
        // possible values: 'dots', 'progress'
        // available reporters: https://npmjs.org/browse/keyword/karma-reporter
        //reporters: ['progress'],
        //reporters: ['html'],
        reporters: ['dots', 'junit'],
        junitReporter: {
            outputFile: 'test-results.xml'
        },

        // web server port
        port: 9876,

        // enable / disable colors in the output (reporters and logs)
        colors: true,

        // level of logging
        // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
        //logLevel: config.LOG_DEBUG,
        logLevel: config.LOG_ERROR,

        // enable / disable watching file and executing tests whenever any file changes
        autoWatch: false,

        // start these browsers
        // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
        //browsers: ['Chrome', 'PhantomJS', 'Firefox'],
        browsers: ['PhantomJS'],

        // Continuous Integration mode
        // if true, Karma captures browsers, runs the tests and exits
        singleRun: true
    });
};

**Comment by Denis-Evseev** [comment]
npm 3.5.0 version

**Comment by aiboy** [comment]
same here.. Windows 8.1, karma 0.13.15

**Comment by Denis-Evseev** [comment]
request "karma start my.conf.js --log-level debug --single-run" helped me to find missed modules

**Comment by budde377** [comment]
@Denis-Evseev You can close the issue, if it isn't relevant anymore.
