### ISSUE TITLE
Disagrement between GitCop and documentation

### ISSUE THREAD

**Issue by budde377** [karma-runner/karma#1776]
GitCop requires commit messages of the format:

    %{type}(%{scope}): %{description}

I.e. with a mandatory *scope*. (See #1775). While the documentation states:

> The <scope> can be empty (eg. if the change is a global or difficult to assign to a single component), in which case the parentheses are omitted. In smaller projects such as Karma plugins, the <scope> is empty.

I.e. an optional *scope*. (See https://github.com/karma-runner/karma/blob/master/docs/dev/06-git-commit-msg.md).

**Comment by Dignifiedquire** [comment]
Yes I'm sorry about that, but I haven't figured out yet how to tell gitcop to do that. If you have any suggestions about that I'm happy to hear them.

**Comment by budde377** [comment]
So I wrote GitCop and they said that writing

    %{type}(?%?{scope})?: %{description}

as subject would allow you to make an optional scope. It would however (I guess) also allow subjects of the form:

    feat(: Some desc 
    featscope: Some desc 
    feat(): Some desc 
    ...

They furthermore stressed that the feature was beta and could change anytime for a better solution, but that they would let any users of the undocumented syntax know before changing it.

**Comment by Dignifiedquire** [comment]
I just setup git hooks with ghooks to make this easier, also update the gitcop to follow your ideas, thanks a lot :)
