### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by bibhas2** [karma-runner/karma#1787]
I am following the installation guide from http://karma-runner.github.io/0.13/intro/installation.html.

Platform: Windows 7.

```
npm install karma
```

Fails with errors like this:

```
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.

install: `node-gyp rebuild
```

According to http://stackoverflow.com/questions/21365714/nodejs-error-installing-with-npm/21366601#21366601 I will need to install node-gyp. This seems to be quite an onerous step.

**Comment by bibhas2** [comment]
The problem went away after I updated to the latest Node.js.

**Comment by Dignifiedquire** [comment]
Happy to hear :)
