### ISSUE TITLE
Karma 0.13.16 introduces breaking changes (through core-js 2.0.0)

### ISSUE THREAD

**Issue by mleonh** [karma-runner/karma#1800]
We recently noticed missing file names in the console output from grunt-contrib-jshint. Turns out that:

* Karma 0.13.16 bumped core-js to 2.0.0
* core-js is loaded by Karma's file-list.js (which in our case was loaded because we use grunt-karma)
* core-js 2.0.0 includes String.prototype.bold, which clashes with the one provided by the 'colors' package, which grunt-contrib-jshint implicitly uses ([link to issue](https://github.com/gruntjs/grunt-contrib-jshint/issues/237))

Hopefully, noting this here saves other people using grunt-contrib-jshint and/or colors some trouble. 

It could be argued that Karma should have bumped the minor version to 14 – even if the semver spec says otherwise. A look at the [core-js changelog for 2.0.0](https://github.com/zloirock/core-js/blob/master/CHANGELOG.md#200---20151224) reveals _a lot_ of breaking changes, and Karma doesn't just ships core-js, it loads it by default, so they kind of become breaking by association.

**Comment by zloirock** [comment]
Hmm... `color` package replaces methods (not only `bold`), [defined in the ECMAScript spec](http://tc39.github.io/ecma262/#sec-string.prototype.bold) and enabled by default in the Node.js (`core-js` just try to call it for feature detection and should not replace it the Node.js), to... getter?O_o Sorry, it's definitely not `core-js` or `karma` issue. Sure, I can add a fallback for that, but `color` behavior here - something inadmissible.

**Comment by Dignifiedquire** [comment]
I think there are multiple issues here. 

1) Karma is using core-js actually for very little so ideally I'd have the usage contained to just the Karma code and not touch that others people code. But I'm not a 100% sure how to best achieve this yet. 

2) I hope to very soon move Karma to `1.0` and try to follow semver as close as possible

3) It sounds like the `color` package is asking for trouble if they are defining these kinds of methods on the String prototype tbh. This will break completely as soon as this gets implemented in V8.

**Comment by zloirock** [comment]
@Dignifiedquire as I see, in some places you use `core-js` without global namespace pollution, in some - with. Usage `library` version everywhere should prevent similar issues.

**Comment by mleonh** [comment]
First of all, my original comment contained a typo, which I fixed: the package adding the String prototype functions is named color**s**, not color. Sorry for that. The package does offer a 'safe mode' which doesn't modify the prototype, but I don't know how often that's actually used – not by grunt-contrib-jshint, obviously.

@zloirock: I agree that this is not a Karma or core-js issue, in the sense that something can/needs to be changed right now. Although I think it's certainly preferable it if Karma doesn't use core-js in global mode, as you just suggested.

@Dignifiedquire: Thanks for the additional information. Looking forward to 1.0!
Concerning "Following semver as close as possible": I think this is actually what caused this – Karma did not change its public API, so specification-wise you were correct in only increasing the patch level. My argument is that in this case ignoring the spec and bumping the minor version would have been better :)

**Comment by dignifiedquire** [comment]
1.0 is released, will try to keep things as close to semver as possible, but we are all human so sometimes errors happen :)
