### ISSUE TITLE
Upgrade to lodash 4.0.0

### ISSUE THREAD

**Issue by dignifiedquire** [karma-runner/karma#1812]

**Comment by dignifiedquire** [comment]
I have thought about it a little bit more and I think I want for the next major release to drop helper._ so that I don't run into this issue anymore. It's pretty easy to upgrade, just need to make sure to release new versions of all the different plugins that rely on it.

**Comment by dignifiedquire** [comment]
We should get the deprecation notice in for 1.0

**Comment by Krinkle** [comment]
lodash* :)

**Comment by dignifiedquire** [comment]
Deprecation notice is in, will be removed from `helpers._`  in 2.0 and upgraded.
