### ISSUE TITLE
Tests run twice (but with different results) using PhantomJS in singleRun

### ISSUE THREAD

**Issue by pidupuis** [karma-runner/karma#1819]
When I run

```
karma start app/client/tests/karma.conf.js --singleRun=true --log-level debug --browsers PhantomJS
```

I obtain the following output:

```
...
PhantomJS 1.9.8 (Linux 0.0.0): Executed 8 of 8 SUCCESS (0.041 secs / 0.233 secs)
22 01 2016 14:21:54.516:DEBUG [karma]: Run complete, exiting.
PhantomJS 1.9.8 (Linux 0.0.0) ERROR
  Error: Unexpected request: GET /client/modules/layout/modules/app/views/app.html
  No more request expected
  at /home/projects/app/client/libs/bower/angular-mocks/angular-mocks.js:1245
PhantomJS 1.9.8 (Linux 0.0.0): Executed 8 of 8 ERROR (0.044 secs / 0.233 secs)
22 01 2016 14:21:54.518:DEBUG [karma]: Run complete, exiting.
22 01 2016 14:21:54.518:DEBUG [launcher]: Disconnecting all browsers
22 01 2016 14:21:54.523:DEBUG [launcher]: Process PhantomJS exited with code 0
22 01 2016 14:21:54.523:DEBUG [temp-dir]: Cleaning temp dir /tmp/karma-87144981
22 01 2016 14:21:54.528:DEBUG [launcher]: Finished all browsers
```

So my tests successed, then failed. If I run without verbose, I see only the failure output.

If I run with Chrome, there is only one run and it successes.
If I run without singleRun, there is only one run and it successes, but I then have to kill the terminal...

Any idea ?

**Comment by Dignifiedquire** [comment]
Looks like somewhere the state is not cleaned up. The request that is being made after the fact that the tests finished throw an error so karma things something went suddenly wrong and fails things. Try figuring out where the ` Error: Unexpected request: GET /client/modules/layout/modules/app/views/app.html` comes from that should solve this.

**Comment by wei2011** [comment]
I see the issue is closed now. Can you please describe how you got it resolved?  I'm getting the same problem, my tests run successfully in Chrome but fails with PhantomJS in singleRun  (the only difference is the error I'm getting from PhantomJS is Script error):

```
PhantomJS 2.1.1 (Windows 7 0.0.0): Executed 2 of 2 SUCCESS (0.016 secs / 0.027 secs)
03 02 2016 09:57:35.365:DEBUG [karma]: Run complete, exiting.
PhantomJS 2.1.1 (Windows 7 0.0.0) ERROR
  Script error.
PhantomJS 2.1.1 (Windows 7 0.0.0): Executed 2 of 2 ERROR (0.031 secs / 0.027 secs)
03 02 2016 09:57:35.380:DEBUG [karma]: Run complete, exiting.
03 02 2016 09:57:35.380:DEBUG [launcher]: Disconnecting all browsers
03 02 2016 09:57:35.396:DEBUG [launcher]: Process PhantomJS exited with code 0
03 02 2016 09:57:35.396:DEBUG [temp-dir]: Cleaning temp dir C:\Users\ADMINI~1\AppData\Local\Temp\karma-46189519
03 02 2016 09:57:35.412:DEBUG [launcher]: Finished all browsers
```

**Comment by pidupuis** [comment]
The fact is that I don't have this error anymore since I updated to phantomjs@2.1.3.

But I don't think that solved the problem since I can't reproduce even by downgrading phantomjs...

**Comment by mathiasmoeller** [comment]
+1

**Comment by devoto13** [comment]
PhantomJS has been archived a while ago and it is better to use headless Chrome or Firefox now. Either way we can't do much about this issue without having a minimal reproduction to debug the root cause of the problem and to verify that our fix actually works. Please open a new issue including a minimal reproduction of the problem if you still experience this.
