### ISSUE TITLE
Can't find variable: exports with ember

### ISSUE THREAD

**Issue by GCorbel** [karma-runner/karma#1851]
This may be a question for beginners but I can't find the solution. I'm trying to run my tests with Karma in an Ember app.

I have this `karma.conf.js` file : 

    // Karma configuration
    // Generated on Wed Jan 27 2016 13:35:28 GMT+0000 (UTC)

    module.exports = function(config) {
      config.set({

        // base path that will be used to resolve all patterns (eg. files, exclude)
        basePath: '',

        // frameworks to use
        // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
        frameworks: ['mocha'],

        // list of files / patterns to load in the browser
        files: [
          'bower_components/jquery/dist/jquery.js',
          'bower_components/ember/ember.debug.js',
          'bower_components/ember-data/ember-data.js',
          'bower_components/ember-mocha-adapter/adapter.js',
          "app/**/*.hbs",
          "app/**/*.js",
          "tests/**/*.js"
        ],

        // list of files to exclude
        exclude: [
        ],

        plugins: [
         'karma-mocha',
         'karma-ember-preprocessor',
         'karma-phantomjs-launcher',
         'karma-babel-preprocessor'
        ],

        // preprocess matching files before serving them to the browser
        // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
        preprocessors: {
          'app/**/*.js': ['babel'],
          'tests/**/*.js': ['babel']
        },

        babelPreprocessor: {
          options: {
            presets: ['es2015'],
            sourceMap: 'inline'
          },
        },

        // test results reporter to use
        // possible values: 'dots', 'progress'
        // available reporters: https://npmjs.org/browse/keyword/karma-reporter
        reporters: ['progress'],

        // web server port
        port: 9876,

        // enable / disable colors in the output (reporters and logs)
        colors: true,

        // level of logging
        // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
        logLevel: config.LOG_INFO,

        // enable / disable watching file and executing tests whenever any file changes
        autoWatch: false,

        // start these browsers
        // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
        browsers: ['PhantomJS', 'Chrome'],

        // Continuous Integration mode
        // if true, Karma captures browsers, runs the tests and exits
        singleRun: false,

        // Concurrency level
        // how many browser should be started simultaneous
        concurrency: Infinity
      })
    }

When I do `karma start` and `karma run`, I have this error message :

    PhantomJS 2.1.1 (Linux 0.0.0) ERROR
      ReferenceError: Can't find variable: exports
      at /frontend/app/adapters/application.js:3
    
    PhantomJS 2.1.1 (Linux 0.0.0) ERROR
      ReferenceError: Can't find variable: exports
      at /frontend/app/adapters/application.js:3

Here is the line in question :

    export default ActiveModelAdapter.extend(DataAdapterMixin, {

If I understand, babel should convert, from es6 to e5, this file but it didn't.

What can I do ?

**Comment by dignifiedquire** [comment]
Babel converts from es6 to es5 which results in commonjs exports (that's why the error says `exports` and not `export`) commonjs only works in node so you need to add a module bundler e.g webpack or browserify to the mix to get a bundle usable in the browser.

**Comment by GCorbel** [comment]
@dignifiedquire you're right. I have a lot of problems with ember and karma but it's not related to karma. If you know a tutorial to use karma with ember can you share it ?

Thanks !

**Comment by buzzware** [comment]
@GCorbel Did you solve this? I can't find a complete tutorial either
