### ISSUE TITLE
Angular2 support

### ISSUE THREAD

**Issue by andrashatvani** [karma-runner/karma#1857]
Currently besides the Karma config an additional adapter is required for Karma to work with Anguar 2.
We use the attached shim.
[karma-test-shim.zip](https://github.com/karma-runner/karma/files/112023/karma-test-shim.zip)
I'd expect to only use the standard karma.conf constructs to set up a new test project. 
Ideally there should be no need for an additional adapter, or if it's still necessary, there should be a plugin architecture allowing for support of the different frameworks.

**Comment by dignifiedquire** [comment]
Looking at the shim, it seems to me that this is mostly setting up systemjs, so you could use [karma-systemjs](https://github.com/rolaveric/karma-systemjs) for that. If you want to a more finished solution, why not create a plugin/npm package that sets things up as needed? 
No other framework has currently integration in core, so I don't see a need to pull this directly in. If there is functionality missing that you require from the plugin side I'm happy to discuss that.

cc @zzo do you have any pointers/thoughts on this?

**Comment by zzo** [comment]
Just want to make sure you've seen https://github.com/sjelin/karma-redirect-preprocessor for dynamically loading ng2 templates (which really just sets up a some proxies).
So yes agree where there is not a completely 'polished for angular2 all in one solution' for karma + angular2 I don't think there's anything 'missing' from karma itself to handle angular2 successfully

**Comment by dignifiedquire** [comment]
Closing this for now.
