### ISSUE TITLE
FAQ link on main page returns 404

### ISSUE THREAD

**Issue by ketus** [karma-runner/karma#1885]
Minor thing but there's link to FAQ on your intro page http://karma-runner.github.io/0.13/intro/installation.html
![image](https://cloud.githubusercontent.com/assets/9350920/12958683/2b0f0b5c-d033-11e5-936a-9ed61d7797eb.png)

which redirects to:
http://karma-runner.github.io/0.13/intro/04-faq.md#which-version-of-nodejs-does-karma-run-with-

I'm strong believer that it should be : 
http://karma-runner.github.io/0.13/intro/faq.html

:)

**Comment by dignifiedquire** [comment]
Yes it should, thanks for spotting, mind doing a PR? :)

**Comment by ketus** [comment]
Will do?
https://github.com/ketus/karma-runner.github.com/pull/1

**Comment by dignifiedquire** [comment]
That won't help, the docs source is in this repo under /docs and the html is just generated from it.

**Comment by ketus** [comment]
What do you use to generate html?

Source appears to be correct (01-installation.md):
`8 [...] See [FAQ] for more info. `
`47 FAQ]: ./faq.html`

so maybe issue lies in generator.

Sorry to bother you on such simple matter, 
I've never encountered that approach (.md -> .html)

**Comment by dignifiedquire** [comment]
Fixed in the latest version.
