### ISSUE TITLE
Karma 0.13.20 broke karma-teamcity-reporter

### ISSUE THREAD

**Issue by cliechty** [karma-runner/karma#1895]
In version 0.13.19 the karma-teamcity-reporter was outputting tests properly. In version 0.13.20 there is no test run output when the reporter is set to 'teamcity'.

I'm also using the 'coverage' reporter and it is behaving normally in both versions.

**Comment by dignifiedquire** [comment]
Thanks for the report. Looks to be the same issue as in #1894

**Comment by mramato** [comment]
It looks like all reporter plug-ins are broken, since I just upgraded and `karma-spec-reporter` is broken as well.

**Comment by dignifiedquire** [comment]
Released `0.13.21` that reverts the problematic commit.
