### ISSUE TITLE
Karma reconnect screen display wrong time unit

### ISSUE THREAD

**Issue by goldensunliu** [karma-runner/karma#1936]
### Expected behavior
should use Seconds instead of ms.
### Actual behavior
![image](https://cloud.githubusercontent.com/assets/1348993/13373866/f722dc86-dd40-11e5-98df-bddb527faa67.png)

### Steps to reproduce the behaviour

1. run karma
2. launch a browser and kill karma
3. look at the reconnect copy in English

**Comment by Moumi** [comment]
I have seen this issue myself and have created a fix. Anytime this evening I will create a PR for it.

**Comment by goldensunliu** [comment]
@Moumi thanks! Community power!

**Comment by dignifiedquire** [comment]
Thanks for the report, @Moumi PR already got merged
