### ISSUE TITLE
Regression with core-js 2.1.1 -> 2.1.2

### ISSUE THREAD

**Issue by cyrilgandon** [karma-runner/karma#1946]
My automatic build runs successfully this night at 3am, but failed this morning at 7am.
I got the following error message:

```
Running karma task
Fatal error: Cannot read property 'length' of undefined
```

The difference between the two builds is the release of core-js 2.1.2 during this time span.

I tried to downgrade manually the dependency of Karma to use core-js 2.1.1, and the error is gone!

- Karma version: 0.13.21

I'm not sure if this is a Karma problem or a core-js problem, still investigating..

**Comment by cyrilgandon** [comment]
The Karma task take part in a scenario where a typescript build happens before.
The Karma task successfuly runs on this own. When it is the second task of a grunt multitask, the error appeared.

```
grunt.registerTask('tests', ['typescript', 'karma']);
```
```
grunt karma  // FAILURE
```
```
grunt typescript
grunt karma // SUCCESS
```

**Comment by cyrilgandon** [comment]
```
TypeError: Cannot read property 'length' of undefined
    at lib$es6$promise$$internal$$fulfill (.\node_modules\grunt-ts\node_modules\csproj2ts\node_modules\es6-promise\dist\es6-promise.js:273:31)
    at lib$es6$promise$$internal$$resolve (.\node_modules\grunt-ts\node_modules\csproj2ts\node_modules\es6-promise\dist\es6-promise.js:255:9)
    at lib$es6$promise$$internal$$invokeCallback (.\node_modules\grunt-ts\node_modules\csproj2ts\node_modules\es6-promise\dist\es6-promise.js:366:9)
    at .\node_modules\grunt-ts\node_modules\csproj2ts\node_modules\es6-promise\dist\es6-promise.js:891:13    
	at lib$es6$promise$asap$$flush (.\node_modules\grunt-ts\node_modules\csproj2ts\node_modules\es6-promise\dist\es6-promise.js:125:9)    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)
```

It seems typescript/grunt-ts is effectively involved in this error

**Comment by zloirock** [comment]
I don't see [in the `core-js` diff `2.1.1...2.1.2` (see, for example, `client/shim.js` for all changes)](https://github.com/zloirock/core-js/compare/v2.1.1...v2.1.2) that can break something - only minor fixes, so I don't think the problem in `core-js`. Awaiting results of investigation.

**Comment by wen96** [comment]
Not sure how `core-js` works (dependency of dependency of...) but this commit:
https://github.com/zloirock/core-js/commit/3b8292d496a27b5f0d7a90010e77afa101d7f872#diff-ee864bf9a84ab105426dbe4fbbad2a69 is creating the issue, if you remove the .f from line #30 it works again.

If someone with more idea about NodeJS could through some light on it.

**Comment by cyrilgandon** [comment]
Not Karma related

**Comment by zloirock** [comment]
It's a bug in es6-promise. In feature detection, core-js detected @@species constructor pattern support in Promise#then. es6-promise not supports it and throws an error. Feature detection wrapped in try / catch, but an error throws async.

Reproducible example:
```js
require('es6-promise');
var p = Promise.resolve();
p.constructor = function(it){ it(function(){}, function(){})};
p.constructor[Symbol.species] = function(it){ it(function(){}, function(){})};

try {
  var f = p.then(function(){});
  console.log('works: ', f instanceof p.constructor[Symbol.species]);
} catch(e){
  console.log('caught error');
}
```

**Comment by zloirock** [comment]
In `core-js` `2.1.3` added a fallback for this `es6-promise` bug.
