### ISSUE TITLE
process.js should expose its logger

### ISSUE THREAD

**Issue by marcoscaceres** [karma-runner/karma#1949]
### Expected behavior
Custom launcher should be able to log to Karma's logger. 

### Actual behavior
It's currently not possible for third parties to hook into the logger for special cases. 

### Enviroment Details
n/a

### Steps to reproduce the behaviour
Ideally, there should be a launcher.log getter or even ._log.

**Comment by marcoscaceres** [comment]
I worked around it by: 

```JS
const log = require('karma/lib/logger').create('launcher');
```

Which I guess is probably fine, but would like to hear if anyone else has an opinion.

**Comment by dignifiedquire** [comment]
This is already possible using dependency injection, see https://github.com/karma-runner/karma-firefox-launcher/blob/master/index.js#L63-L66 for an example.

**Comment by marcoscaceres** [comment]
Awesome! Thanks for pointing me to an example
