### ISSUE TITLE
Add a code_complete event to Browser class

### ISSUE THREAD

**Issue by nicojs** [karma-runner/karma#1950]
I'm missing an event to let us know the code coverage report is ready. We need it to programmatically read the report for our js mutation testing framework [Stryker](http://github.com/infosupport/stryker) . Right now we need to implement a polling mechanism (which is ugly as hell).

Let's call it `coverage_complete`. I want to add the event to the Browser (`lib/browser.js`)

```javascript
this.onCoverageComplete = function (result) {
    emitter.emit('coverage_complete', this, result)
    clearNoActivityTimeout()
  }
```

When this event is added, i will also add the firing of the event in karma-coverage

**Comment by dignifiedquire** [comment]
Why does this need to be in karma itself, couldn't this simply be added to `karma-coverage`? The emitter can be injected there and the event emitted manually.

**Comment by nicojs** [comment]
I didn't know that. I will move it to there. I'll let the emitter be injected in `reporter.js`. I also want to add a new report type, something like `inMemory`. If that is enabled, the coverage report will be provided as second argument to the event (first is the browser). Is this OK? Create one issue for that or 2?

**Comment by dignifiedquire** [comment]
Sounds okay to me, best if you open an issue on karma-coverage describing the full use case. But that should work fine as far as I understand.

**Comment by nicojs** [comment]
Ok, i did that. You can read it here: https://github.com/karma-runner/karma-coverage/issues/215
Could you please review my problem and the proposed solution?

Thanks for the help! :+1:
