### ISSUE TITLE
Generated config lacks two semicolons at the end

### ISSUE THREAD

**Issue by eric-burel** [karma-runner/karma#1952]
Hi,
### Expected behavior

The config file generated by karma.init lacks a semicolon at the end of the module.exports = function(config){} call and also at the end of config.set() call.

The JavaScriptFormatter() is to blame, yet I can't tell how to fix. It does not create any particular issue however and karma runs fine.

### Enviroment Details

- Karma version (output of `karma --version`): 0.13.21
- Relevant part of your `karma.config.js` file

### Steps to reproduce the behaviour

1. karma init karma.conf.js

**Comment by budde377** [comment]
The semicolons are (in these cases) optional in JavaScript and following the [JavaScript Standard Style](http://standardjs.com/) not permitted. Karma adheres to the JavaScript Standard Style.

**Comment by dignifiedquire** [comment]
As @budde377 said :)
