### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

### ISSUE THREAD

**Issue by alvipeo** [karma-runner/karma#1954]
Running angular 2 tests, all been working fine until this morning when I upgraded some packages. One of them is typescript - from 1.7.5 to 1.8.2

Using with typescript 1.8.2, node 5.7.0,

    "karma": "^0.13.21",
    "karma-chrome-launcher": "^0.2.2",
    "karma-coverage": "^0.5.3",
    "karma-jasmine": "^0.3.7",
    "karma-mocha-reporter": "^1.2.3",
    "karma-phantomjs-launcher": "^1.0.0",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "1.7.0",

Here's an output:

ts-loader: Using typescript@1.8.2 and d:\Documents\Visual Studio 2015\Projects\MyPrj\tsconfig.json

<--- Last few GCs --->

   80496 ms: Mark-sweep 1380.1 (1457.2) -> 1379.9 (1457.2) MB, 1205.6 / 0 ms [allocation failure] [GC in old space requested].
   81726 ms: Mark-sweep 1379.9 (1457.2) -> 1379.9 (1457.2) MB, 1229.6 / 0 ms [allocation failure] [GC in old space requested].
   82944 ms: Mark-sweep 1379.9 (1457.2) -> 1377.5 (1457.2) MB, 1217.7 / 0 ms [last resort gc].
   84158 ms: Mark-sweep 1377.5 (1457.2) -> 1379.9 (1457.2) MB, 1213.9 / 0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0000017062DE3AD1 <JS Object>
    2: objectTypeRelatedTo(aka objectTypeRelatedTo) [d:\Documents\Visual Studio 2015\Projects\MyPrj\node_modules\typescript\lib\typescript.js:19809] [pc=000003AA2E94DD3E] (this=0000017062D04189 <undefined>,source=00000182C9217CC1 <a TypeObject with map 000003805A847911>,originalSource=00000182C9217CC1 <a TypeObject with map 000003805A847911>,target=0000037567B6A851 <a TypeObject with...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test" "--" "--auto-watch" "--no-single-run"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@2.0.0 test: `karma start "--auto-watch" "--no-single-run"`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the angular2-webpack-starter@2.0.0 test script 'karma start "--auto-watch" "--no-single-run"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     karma start "--auto-watch" "--no-single-run"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-webpack-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-webpack-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     d:\Documents\Visual Studio 2015\Projects\MyPrj\npm-debug.log

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch:test"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@2.0.0 watch:test: `npm run test -- --auto-watch --no-single-run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-webpack-starter@2.0.0 watch:test script 'npm run test -- --auto-watch --no-single-run'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run test -- --auto-watch --no-single-run
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-webpack-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-webpack-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     d:\Documents\Visual Studio 2015\Projects\MyPrj\npm-debug.log

karma.config.js:

```
// @AngularClass

module.exports = function(config) {
  var testWebpackConfig = require('./webpack.test.config.js');

  config.set({

    // base path that will be used to resolve all patterns (e.g. files, exclude)
    basePath: '',

    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['jasmine'],

    // list of files to exclude
    exclude: [ ],

    // list of files / patterns to load in the browser
    // we are building the test environment in ./spec-bundle.js
    files: [ { pattern: 'spec-bundle.js', watched: false } ],

    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: { 'spec-bundle.js': ['coverage', 'webpack', 'sourcemap'] },

    // Webpack Config at ./webpack.test.config.js
    webpack: testWebpackConfig,

    coverageReporter: {
      dir : 'coverage/',
      reporters: [
        { type: 'text-summary' },
        { type: 'json' },
        { type: 'html' }
      ]
    },

    // Webpack please don't spam the console when running in karma!
    webpackServer: { noInfo: true },

    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: [ 'mocha', 'coverage' ],

    // web server port
    port: 9876,

    // enable / disable colors in the output (reporters and logs)
    colors: true,

    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_INFO,

    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: false,

    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: [
      'Chrome',
      //'PhantomJS'
    ],

    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: true
  });

};

```

**Comment by alvipeo** [comment]
tried typescript 1.7.5 - no go. so it's not because of typescript.

**Comment by dignifiedquire** [comment]
Closing as the referenced error seems to be solved and this is not an issue with Karma
