### ISSUE TITLE
Scenarios in E2E tests of pass-opts.feature and timeout.feature fail

### ISSUE THREAD

**Issue by Moumi** [karma-runner/karma#1956]
### Expected behavior
During the last few days, when fixing program related issues or even broken links, when I perform `grunt test` the scenario of the `Broken Browser` and `Passing Options to run on the Command Line` fails often. Both tests should pass. 

### Actual behavior
Instead of passing, they fails fairly often the last few days. It even seems that the tests fail in an (almost) regular base. Even a PR of almost a month ago, had the same scenarios failing ([link](https://travis-ci.org/karma-runner/karma/jobs/106512181))

### Enviroment Details
- Karma version (output of `karma --version`): v0.13.21 and in the latest case found v0.13.19
- When run locally and on Travis.
- Failures only seen on tests run using Node.js 0.10, 0.12 and currently 5. (Not tried 4)

### Steps to reproduce the behaviour

1. Create small change, can be a change in the documentation.
2. Run `grunt test`.
3. Sometimes the scenarios don't fail immediately, but appear after 2-3 runs of `grunt test`.

This issue makes the developer uncertain if his code changes have broken something else and the Travis reports on a PR need a second look instead of relying on them being accurate. 

I will try to take a look into the issue and if I find the cause, I will report it here.

**Comment by dignifiedquire** [comment]
They usually run fine on my machine, but I have seen them fail on travis often. I think this is an issue of timeouts and these tests taking their time depending on the machine resources.

**Comment by Moumi** [comment]
Most of the E2E tests that fail are in terms of that timeout. Is there no general solution for this?

**Comment by dignifiedquire** [comment]
Increasing the timeouts is the only solution we have as far as I know.

**Comment by dignifiedquire** [comment]
This should make things a bit more stable: https://github.com/karma-runner/karma/commit/b35a53c69a9cd5050de3ba1b60b7c432b6ea531d

**Comment by Moumi** [comment]
Yes, it seems that that has solved the issue. Well, this should not in fact be the solution to solving this, but it works. :+1:
