### ISSUE TITLE
Please release a new version based on master

### ISSUE THREAD

**Issue by rosenfeld** [karma-runner/karma#1957]
I'd like to write an npm package for integrating oojspec to Karma but it requires the new feature that allows custom context and debug HTML to make it work, so I can't release such package before karma is released with that feature.

I've already got it to work using a symlink to a git clone of karma and I'm currently working on refactoring it and will try to understand how to write frameworks by taking a look at other framework integrations implementation but if you could release a new version of karma that will allow me to publish the new integration package once I'm finished.

**Comment by dignifiedquire** [comment]
I'm waiting for a couple of things to get finished and will release 1.0 very soon (hopefully next week) You can track progress for that here: https://github.com/karma-runner/karma/milestones/v1.0

**Comment by rosenfeld** [comment]
@dignifiedquire I've implemented the adapter for OOJSpec and I'm just waiting for a new release before publishing it to NPM:

https://github.com/rosenfeld/karma-oojspec

But I think karma should allow plugins to change the custom context and debug files, don't you agree? Please take a look at the notes in the README and on this snippet:

https://github.com/rosenfeld/karma-oojspec/blob/master/src/index.coffee#L2-L4

Could Karma accept such changes to the configuration?

**Comment by rosenfeld** [comment]
If you want to see it working, take a look here:

https://github.com/fredericoschardong/karma-oojspec

The tests will fail so that I can test the output properly.

**Comment by dignifiedquire** [comment]
@rosenfeld understood :) will try to get things ready on Monday hopefully

re changing the context files, you already do it, so I don't see any issues there. A lot of plugins add or change things on the config for their needs.

**Comment by rosenfeld** [comment]
@dignifiedquire, I'm changing the context files in the plugin but it's not working. You can test it by commenting these lines in this project:

https://github.com/fredericoschardong/karma-oojspec/blob/master/karma.conf.coffee#L66-L67

If you do so you'll notice that the custom files are not being loaded even though they are being set by the plugin.

If this is unexpected then it should probably be fixed before releasing 1.0.0, right?

**Comment by dignifiedquire** [comment]
Interesting, I expected this to work. Sounds like a bug if it doesn't

**Comment by rosenfeld** [comment]
Yes, I also expected it to work, that's why I'm reporting this behavior ;)

**Comment by rosenfeld** [comment]
@dignifiedquire, should I create a new issue for that?

**Comment by dignifiedquire** [comment]
@rosenfeld Fixed in latest `master`

**Comment by rosenfeld** [comment]
Thanks, @dignifiedquire! I could confirm it now indeed works :) Good job

**Comment by dignifiedquire** [comment]
1.0 was just released

**Comment by rosenfeld** [comment]
great, thanks!

**Comment by rosenfeld** [comment]
@dignifiedquire, before the release I was able to access my custom JS using the path `/base/node_modules/karma-oojspec/dist/oojspec-initializer.js`. Now I get a 404 when trying to do so. Is there any method I could use to serve that file? I can't find a proper documentation for runners authors...

**Comment by rosenfeld** [comment]
nevermind
