### ISSUE TITLE
Can Karma use a locally installed nodejs?

### ISSUE THREAD

**Issue by xavierhaurie** [karma-runner/karma#1975]
### Expected behavior
I would like for Karma to not try to run a globally installed nodejs; instead I want to rely on the maven plugin "frontend-maven-plugin" to install node and npm in the project's local node folder, and I just need to point Karma to node/node.

**Comment by budde377** [comment]
The karma executable is a javascript file with a shebang line instructing which node to use (e.g. `#!/usr/bin/env node`). You can run karma with your local node with: `./local_node path/to/karma` where `./local_node` is the locally installed node.

**Comment by xavierhaurie** [comment]
That worked, though not with the  frontend-maven-plugin plugin. Instead I used the exec-maven-plugin plugin, and that worked. 

Thanks!
