### ISSUE TITLE
Executed 0 of 0 ERROR even the test spec executed!

### ISSUE THREAD

**Issue by creeperyang** [karma-runner/karma#1978]
### Expected behavior

The terminal Should log `Success`.

### Actual behavior

The terminal get `Executed 0 of 0 ERROR (0.003 secs / 0 secs)`.

But at <http://localhost:9876/debug.html>, the console logs:

```
Skipped 0 tests
SUCCESS when the app starts outputs 'App Started!' in the target
Skipped 0 tests
```

It's clear that spec is executed.

### Enviroment Details

- `karma@0.13.21`
- `karma.config.js`

```js
    frameworks: ['jasmine'],
    files: [
      'amd.js',
      'test/test-main.js',
      { pattern: 'node_modules/jquery/dist/jquery.js', included: false },
      { pattern: 'demo/*.js', included: false },
      { pattern: 'test/**/*.spec.js', included: false }
    ],
```

**Comment by Florian-R** [comment]
Dupe on #926 (fixed in 0.13.20)

**Comment by creeperyang** [comment]
@Florian-R  Absolutely not the same thing with #926 .

I mean my tests are executed successfully. And the browser console get correct output but terminal not.

test code `xx.spec.js`:

```js
define(['demo/app', 'jquery'], function (App, $) {
    describe("when the app starts", function () {
        it("outputs 'App Started!' in the target", function () {
            var target = $("body");

            var app = new App(target);
            app.start();

            expect(target.html()).toEqual("App Started!");
        });
    });
});
```

The browser just output:

`SUCCESS when the app starts outputs 'App Started!' in the target`

**Comment by Florian-R** [comment]
Indeed, my bad.

I'm not very versed with an AMD setup but it seems to me that you need to require your specs no?

**Comment by creeperyang** [comment]
@Florian-R I solved it just now.

I drop `karma-requirejs` and because I want to test my own `amd.js` lib. And then I run into the issue above.

So I checked the source code of `karma-requirejs` and finally I saw what I missed for running test successfully. I write my adapter code and make it a custom plugin. Now everything is ok.

Thanks anyway.
