### ISSUE TITLE
doing npm install karma pulls in a very large geth.log file

### ISSUE THREAD

**Issue by kasajian** [karma-runner/karma#1980]
### Expected behavior
When do an npm install karma, i don't expect to get large log files

### Actual behavior
When i do npm install, in node_modules/karma folder I see geth.log which is 657,984 bytes.   

### Enviroment Details

- Karma version (output of `karma --version`):
Karma version: 0.13.21

- Relevant part of your `karma.config.js` file
don't have one yet.

### Steps to reproduce the behaviour

1. npm install karma --save-dev
2.
3.

**Comment by dignifiedquire** [comment]
Thanks, going to publish a new version that only removes this file asap. No idea how did not notice this.

**Comment by dignifiedquire** [comment]
I just published v0.13.22 which drops this file (otherwise it's identical). Thanks again for noticing!

**Comment by dignifiedquire** [comment]
https://github.com/karma-runner/karma/releases/tag/v0.13.22
