### ISSUE TITLE
Connect to MongoDB using browserify

### ISSUE THREAD

**Issue by dhruv004** [karma-runner/karma#1985]
### Expected behavior

I have a server file which includes models from mongoose defined in database.
I want to require this api file in my testSpec,but get an error.
### Actual behavior

>  Uncaught Error: Cannot find module './commandsC:/Users/DHRUVD/Desktop/ReactKarmaJasmine/New folder_command'
>   at C:/Users/DHRUVD/AppData/Local/Temp/98629401e2cb04811eddba5b9156d917.browserify:1 <- node_modules/browser-pack/_prelude.js:1:0

how do I require this file which includes mongoose models..??
### Enviroment Details
- Karma version (output of `karma --version`):Karma version: 0.13.21
- My `karma.config.js` file

`module.exports = function(config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', 'browserify'],

```
browserify: {
  debug: true,
  transform: [ 'brfs' ]
},
files: [        
    'test/testSpec.js'      
],
preprocessors: {
    'test/testSpec.js': [ 'browserify' ]    
},
reporters: ['progress'],
port: 9876,
colors: true,
logLevel: config.LOG_INFO,
autoWatch: true,
browsers: ['Chrome'],
singleRun: false,
concurrency: Infinity
```

  })
}`

**Comment by dignifiedquire** [comment]
This is a problem with browserify and not with karma. Not sure you can browserify mongoose actually

**Comment by dhruv004** [comment]
any workaround for this would be helpful..

**Comment by devoto13** [comment]
Please use StackOverflow for questions and support in the future as we want to keep the issue tracker for bug reports and feature requests.
