### ISSUE TITLE
test files are unexpectedly removed when edited by certain editors

### ISSUE THREAD

**Issue by fredsa** [karma-runner/karma#199]
Using:

```
$ testacular --version
Testacular version: 0.5.5
```

It appears that, when saving, some editors (e.g vim) move the original file (to preserve it as a backup) and create a new file, rather than updating the file in place.

As a result Testacular (almost always) removes the edited file:

```
info (watcher): Removed file "/path/to//test/unit/controllersSpec.js".
```

Future changes to the file are no longer detected. Once is forced to restart Testacular.

Note, Testacular behaves normally (recognizing the file has been updated) when one simply touches the file:

```
$ touch test/unit/controllersSpec.js
```

A workaround is to specify an explicit file backup policy, i.e. in the vim case by adding `:set backupcopy=yes` to your `~/.vimrc`:

```
"backupcopy                                                                     
"    "yes"   make a copy of the file and overwrite the original one             
"    "no"    rename the file and write a new one                                
"    "auto"  one of the previous, what works best                               
:set backupcopy=yes
```

**Comment by paleopeti** [comment]
This problem still exists. I use vim and when I change a file several times Karma sometimes removes the file, sometimes reloads the file.
Karma version: 0.12.31

**Comment by pawer13** [comment]
Same happens with IntelliJ: Sometimes a file is detected as removed and I've never seen it being added again. The only solution is restarting Karma

**Comment by KamilSzot** [comment]
The first version that thinks one of the watched files got deleted is 0.12.5.
I'm on windows. On 0.12.4 and earlier, 0.12.0 for example, problem does not occur.

**Comment by JamesBender** [comment]
I'm seeing this issue still as well in both WebStorm and Sublime 3. Using Windows 8.1 and Karma 0.12.31

**Comment by jagandecapri** [comment]
I'm using Vim too and having the same problem. 
Using Chrome as the testing browser.
Only solution I can think of is to restart Karma.
Karma version : 0.12.31

**Comment by hoxu** [comment]
Karma 0.12.35 + vim, still having this issue. I get "Removed file" occasionally, followed by "Added file" when I save again.

**Comment by Dignifiedquire** [comment]
@hoxu this is most likely an issue https://github.com/paulmillr/chokidar the filewatcher we use itself. So if you have a detailed report, please file an issue there.

**Comment by s-o-r-o-u-s-h** [comment]
same issue with karma  v0.13.21

**Comment by rryter** [comment]
I just ran into this problem with karma `1.1.2`
I can confirm disabling 'safe write' in Intellij _"solves"_ the problem.

**Comment by lvanderbijl** [comment]
having the same problem in webstorm 2017 using typescript spec files.

Karma 1.5.0

Can also confirm disabling safe write "fixes" the issue.

**Comment by RndmRanger** [comment]
I am also having this issue, 6 years after it's original posting. What is going on here?

**Comment by johnjbarton** [comment]
Without practical steps to reproduce this issue, only someone who experiences the issue often will be able to investigate and find a fix.  The issue is likely with the file-watcher library, not karma-runner itself.
