### ISSUE TITLE
watching does not make karma run again

### ISSUE THREAD

**Issue by inancgumus** [karma-runner/karma#1991]
### Expected behavior
- Karma should run the tests again when a file has changed while watching
### Actual behavior
- Karma does not run the runner again when a watched file has been changed
- It only reports that it has been changed
### Enviroment Details
- Karma version: 0.13.22
- karma.config.js: https://github.com/deeperx/riot-testing-browserify/blob/master/karma.conf.js
### Steps to reproduce the behaviour
1. `git clone https://github.com/deeperx/riot-testing-browserify`
2. `npm i`
3. `karma start`
4. modify the content of `tags/hello-world.tag`
5. see that it does not run karma runner again, you will only see that watcher notifies that .tag file has changed

**Comment by dignifiedquire** [comment]
Looks like your pattern config is not correct. The property for not including is `included: false`. Also try adding explicitly `watched: true`, so sth like this:

```js
{ pattern: 'tags/**/*.tag', included: false, watched: true }
```

For more details check http://karma-runner.github.io/0.13/config/files.html

**Comment by deeperx** [comment]
@dignifiedquire yes, you're right on that typo but it does not change the problem. It still does not run the runner again. Only notifies me about that .tag file has changed.

**Comment by dignifiedquire** [comment]
This sounds like `watchify` is not picking up the changes rather than an issue with karma: https://github.com/nikku/karma-browserify#watchify-config

**Comment by deeperx** [comment]
@dignifiedquire Actually, it picks up the changes I believe but karma does not run them again. When I change spec file instead of tag file (_which is a preprocessed file of Riot.js_) karma correctly runs the tests again. Or, how can I validate that watchify has a problem?

When I change .tag file it logs this but does run the previous tests as if nothing has changed:

```bash
14 03 2016 21:35:18.309:INFO [watcher]: Changed file "/Users/deeperx/dev/local-experiments/riot.js/riot-testing-browserify/tags/hello-world.tag".
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 1 of 1 SUCCESS (0.001 secs / 0.003 secs)
```

**Comment by devoto13** [comment]
This sounds like a valid bug to me. However there have been many changes to the libraries since it was reported. The reproduction repository is not available anymore either. Please open a new issue including a minimal reproduction if you still experience this issue.
