### ISSUE TITLE
Unexpected token ILLEGAL at .mp3 [bug]

### ISSUE THREAD

**Issue by karneaud** [karma-runner/karma#2028]
### Expected behavior
Should load mp3 file

### Actual behavior
Getting an Uncaught SyntaxError: Unexpected token ILLEGAL
### Enviroment Details

- Karma version (output of `karma --version`):
Karma version: 0.13.22

- Relevant part of your `karma.config.js` file
 files:[ 'tests/*_test.js',
      {pattern: 'app/images/*.*', watched: false, included: true, served: true},
      {pattern: 'app/sounds/*.mp3', watched: false, included: true, served: true}
    ],
    proxies: {
        '/images/': 'http://localhost:9876/base/app/images/',
        '/sounds/': 'http://localhost:9876/base/app/sounds/'
    },
### Steps to reproduce the behaviour

1. add audio files to project
2. config karma to load mp3 files via proxies 
3. run karma from node gulp task

**Comment by budde377** [comment]
Can you try and not include the mp3 file (and I guess also your images)? I.e changing your config to
```javascript
files:[ 'tests/_test.js',
{pattern: 'app/images/.', watched: false, included: false, served: true},
{pattern: 'app/sounds/.mp3', watched: false, included: false, served: true}
],
```

**Comment by wesleycho** [comment]
Shouldn't this be `app/sounds/*.mp3`?

**Comment by dignifiedquire** [comment]
as @wesleycho said, the glob is invalid, it needs a star
