### ISSUE TITLE
[Close] karma cannot find plugins on Windows 10

### ISSUE THREAD

**Issue by ruslanss** [karma-runner/karma#2033]
**Edit: resolved by installing karma-cli globally. Please close.**

This issue is happening in all my projects. karma cannot find plugins on my new machine. while node.js can. I am using Windows 10 64x PowerShell.

For this example I will be using angular-seed repo:

> cd c:/git
> git clone https://github.com/angular/angular-seed.git
> cd angular-seed
> npm test

### Expected behavior
**npm test command works fine:**

> angular-seed@0.0.0 test C:\git\angular-seed
> karma start karma.conf.js

> INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
> INFO [launcher]: Starting browser Chrome
> INFO [Chrome 49.0.2623 (Windows 10 0.0.0)]: Connected on socket xBgNZ_H3-JMOs3RFAEjx with id 10297817
> Chrome 49.0.2623 (Windows 10 0.0.0): Executed 5 of 5 SUCCESS (0.09 secs / 0.079 secs)

### Actual behavior
**karma start command doesn't:**

> C:\git\angular-seed>karma start karma.conf.js
> 31 03 2016 01:11:11.816:WARN [plugin]: Cannot find plugin "karma-chrome-launcher".
>   Did you forget to install it ?
>   npm install karma-chrome-launcher --save-dev
> 31 03 2016 01:11:11.816:WARN [plugin]: Cannot find plugin "karma-firefox-launcher".
>   Did you forget to install it ?
>   npm install karma-firefox-launcher --save-dev
> 31 03 2016 01:11:11.831:WARN [plugin]: Cannot find plugin "karma-junit-reporter".
>   Did you forget to install it ?
>   npm install karma-junit-reporter --save-dev
> 31 03 2016 01:11:11.909:WARN [karma]: No captured browser, open http://localhost:9876/
> 31 03 2016 01:11:11.925:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
> 31 03 2016 01:11:11.925:WARN [launcher]: Can not load "Chrome", it is not registered!
>   Perhaps you are missing some plugin?
> 

**How? What? Why? I know I'm not missing any plugins **and** it is exactly the same command!!**

### Enviroment Details

- Karma version (output of `karma --version`):

> Karma version: 0.13.22

- Relevant part of your `karma.config.js` file:
```
module.exports = function(config){
  config.set({

    basePath : './',

    files : [
      'app/bower_components/angular/angular.js',
      'app/bower_components/angular-route/angular-route.js',
      'app/bower_components/angular-mocks/angular-mocks.js',
      'app/components/**/*.js',
      'app/view*/**/*.js'
    ],

    autoWatch : true,

    frameworks: ['jasmine'],

    browsers : ['Chrome'],

    plugins : [
            'karma-chrome-launcher',
            'karma-firefox-launcher',
            'karma-jasmine',
            'karma-junit-reporter'
            ],

    junitReporter : {
      outputFile: 'test_out/unit.xml',
      suite: 'unit'
    }

  });
};
```

### Steps to reproduce the behaviour

1. git clone https://github.com/angular/angular-seed.git
2. cd angular-seed
3. karma start

Please help. I've been trying to sort this out for days.

**Comment by xdeetan** [comment]
Hi ruslanss,

I had the same problem and got it resolved by installing karma-cli globally.
In my case it's not able to find **"Error: No provider for "framework:jasmine"! (Resolving: framework:jasmine)"**.
 
I ran the below command after installing 'karma-jasmine'.
npm install -g karma-cli
