### ISSUE TITLE
Error when running karma without internet connection

### ISSUE THREAD

**Issue by RobertDiebels** [karma-runner/karma#2050]
### Expected behavior

I would expect to be able to run unittests even when I do not have an internet connection available. 
My internet provider decided to ditch my connection today, I was working from home and I thought well, while they fix this I'll go write some more unittests.
No go. Apparently something goes wrong when it tries to lookup address information (which is not available).
### Actual behavior

I get the following error: 

```
C:\Users\project_name\node_modules\karma\lib\runner.js:65
      throw e
      ^

Error: getaddrinfo ENOENT localhost:9877
    at Object.exports._errnoException (util.js:849:11)
    at errnoException (dns.js:31:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
```
### Enviroment Details
- Karma version (output of `karma --version`): 0.13.22 (reproducible on 1.3.0)
- Relevant part of your `karma.config.js` file: None
- Other info: 
- Running Windows 10.
- Running this in Webstorm 11 (though it also happens running CLI commands).

See: https://github.com/RobertDiebels/karma-test/tree/master for further details.

### Steps to reproduce the behaviour
1. Disconnect from all your networks.
2. run command `karma start`
3. run command `karma run --conf karma.conf.js --file jasmine-test.spec.js`
4. Behold the error message

This is reproducible on Karma version: 1.3.0 just ran the steps above again.

**Comment by RobertDiebels** [comment]
Is there anything I need to provide to speed up the investigation?

**Comment by RobertDiebels** [comment]
Any chance on this getting picked up?

**Comment by maksimr** [comment]
@RobertDiebels is it reproduced on latest version of karma?

Thanks

**Comment by maksimr** [comment]
Which command do you run in terminal to start karma?

**Comment by RobertDiebels** [comment]
@maksimr I've created a repo for reproduction purposes https://github.com/RobertDiebels/karma-test/tree/master . I'll update my initial description with version numbers and the like.

**Comment by RobertDiebels** [comment]
@maksimr just updated the description and checked if I get the same on 1.3.0. I think it's caused running in the browser? Shutting off the network adapter disables the websockets I think, I haven't looked at the code.

Still the thing with unit tests is that they should be able to run with or without a functioning or connected network adapter.

**Comment by maksimr** [comment]
@RobertDiebels Thanks!

I totally agree that karma should work without internet connection (offline).

I have checked on MacOs all work as expected if disable network, I don't understand what meant `shut off your adapter` and I don't know how it works on Windows

but be carefully `karma` based on network client-server architecture and if you totally remove network adapter so that local network also does not work `karma` will not work and this is expected behaviour.

**Comment by RobertDiebels** [comment]
@maksimr yea the part about the adapter makes sense. 

I think I first encountered this when my connection dropped for an hour or two when I was working from home. So I tried reproducing by just shutting off the adapter (not the same ofc. I just didn't feel like crawling under my desk xD).

I'll try to simulate by disconnecting my LAN cable or turning off my router. Will report back in a second.

**Comment by maksimr** [comment]
@RobertDiebels thanks, very strange I will try check it on windows 10

**Comment by maksimr** [comment]
I can confirm that problem exist, but problem in `karma run` command only

`karma start` work as expected, `karma run` does not work if disable network

<img width="1370" alt="karma-windows-problem" src="https://cloud.githubusercontent.com/assets/616193/21292895/0fb2bace-c525-11e6-9889-5fe9a1c693b3.png">

**Comment by maksimr** [comment]
@RobertDiebels how workaround you cuold set `hostname: '127.0.0.1' in karma.config.js

**Comment by maksimr** [comment]
I have investigated the problem and the problem in nodejs iteself - https://github.com/nodejs/node-v0.x-archive/issues/25489 


I don't think that add workaround to runner.js is best solution because it could break ipv6.
So my suggest add this problem with [workaround](https://github.com/karma-runner/karma/issues/2050#issuecomment-267814425) to FAQ.

cc @dignifiedquire

**Comment by RobertDiebels** [comment]
@maksimr thanks for the investigation. Will use the work-around.

**Comment by yaacovCR** [comment]
Consider [node-offline-localhost][1].

Add the following before the breaking code:

    require('node-offline-localhost').always();

And it just works (hopefully), at least until [RFC 3493][2] gets [fixed][3].

Full disclosure: I authored this package to streamline https in my dev environment when offline.

[1]: https://www.npmjs.com/package/node-offline-localhost
[2]: https://www.ietf.org/rfc/rfc3493.txt
[3]: https://fedoraproject.org/wiki/QA/Networking/NameResolution/ADDRCONFIG
