### ISSUE TITLE
404 on static/client.html

### ISSUE THREAD

**Issue by zgardner** [karma-runner/karma#2067]
### Expected behavior

Running static/client.html in the browser should work.
### Actual behavior

I am getting a 404 because socket.io/socket.io.js is not there
### Enviroment Details

This can be reproduced by cloning the latest of this repo, and opening static/client.html in your favorite browser.
- Karma version (output of `karma --version`): 0.13.22
- Relevant part of your `karma.config.js` file
### Steps to reproduce the behaviour

1.
2.
3.

**Comment by dignifiedquire** [comment]
You need to first build the code, karma is not ready to be run by just cloning. For more details take a look at http://karma-runner.github.io/0.13/dev/making-changes.html

**Comment by devoto13** [comment]
`static/client.html` is not expected to work without the Karma server as it needs some pre-processing and needs Karma server to load certain files. Closing as works as designed.
