### ISSUE TITLE
2KLOG Logs Different Formatted Message

### ISSUE THREAD

**Issue by MartyZhou** [karma-runner/karma#2070]
### Expected behavior

In the log file, I should have log message like this:
_[2KLOG: 'data returned with code: 404'_
### Actual behavior

But the log I got is like this:
_[2KLOG 404 '_
### Enviroment Details
- Karma version (output of `karma --version`): 0.13.15
### Steps to reproduce the behaviour
1. I am using AngularJS's $http service. I have the following code

`$http({method:'GET', url:'...'}).then(function(data){`
`console.log('data returned with code: 200'); // 2KLOG for this is normal`
`}, function(error){`
`console.log('data returned with code: 404'); // But 2KLOg for this is not correct. The log is normal if I removed the colon.`
`});`

**Comment by dignifiedquire** [comment]
You will need to disable colors, that 2K is part of color codes in bash.

**Comment by devoto13** [comment]
Closing per above.
