### ISSUE TITLE
Disable or listen to the runner logs

### ISSUE THREAD

**Issue by lifenautjoe** [karma-runner/karma#2121]
### Expected behavior

I want to be able to disable or listen to the runner logs.
### Actual behavior

All runner logs are written in the standard output as seen [here](https://github.com/karma-runner/karma/blob/master/lib/runner.js#L56)
### Enviroment Details
- Karma version: 3.8.6
### Steps to reproduce the behaviour
1. Create and start a server

``` js
var server = new Server({
    configFile : karmaConfigFile
}, function(exitCode) {
    console.log('Karma has exited with ' + exitCode);
    process.exit(exitCode)
});
server.start();
```
1. On `browsers_ready` `server` event, trigger a run

``` js
server.on('browsers_ready',function () {
    runner.run({ configFile: karmaConfigFile});
});
```
1. See the run output on the console twice, as both the `server` and the `runner` print the output

``` bash
PhantomJS 2.1.1 (Linux 0.0.0): Executed 0 of 1 SUCCESS (0 secs / 0 secs)
PhantomJS 2.1.1 (Linux 0.0.0): Executed 1 of 1 SUCCESS (0.036 secs / 0.001 secs)
```
#### Implement as event

_Preferred_

``` js
var run = runner.run({ configFile: karmaConfigFile});

run.on('data',function(data){
  console.log(data);
});
```
#### Implement flag

``` js
runner.run({ configFile: karmaConfigFile, logs: false});
```
### Notes

This might reflect another issue.
 My `logLevel` is set to `config.LOG_DISABLE` in my karma configuration file. The server seems to not respect the flag when manually triggering the run.

**Comment by developit** [comment]
This behavior makes it really hard to wrap Karma in an overarching CLI, which is something you'll be seeing more and more over the next year.

**Comment by JakeChampion** [comment]
Also seeing this behaviour, if someone can point to what needs changing, I will give it a go :-)
