### ISSUE TITLE
Karma failed to detect soucemaps since systemjs@0.19.19

### ISSUE THREAD

**Issue by unlight** [karma-runner/karma#2122]
Found it empirically.

systemjs@0.19.18
![](https://i.gyazo.com/478b227b5c2b2d1b373f444c8923f132.png)

systemjs@0.19.19 - 0.19.27
![](https://i.gyazo.com/87a1deddd2a600af6072665e077759a1.png)
No link to source.

### Enviroment Details
Karma 0.13.22
[Karam config](https://github.com/unlight/angular2-blank-project/blob/faba28137cb71374fe57fa397907490c75e9a5d4/karma.conf.js)

**Comment by dignifiedquire** [comment]
Can you test with the latest release please?

**Comment by unlight** [comment]
Something happened and I cannot reproduce both cases (using phantomjs as launcher)
I think it is somehow connected with phantomjs, because when using chrome launcher everything is ok with sourcemapped stack traces.

**Comment by dignifiedquire** [comment]
Happy to hear
