### ISSUE TITLE
CLI boolean options don't work as expected

### ISSUE THREAD

**Issue by dignifiedquire** [karma-runner/karma#213]
The following throws an error

``` bash
$ testacular start --single-run testacular.conf.js
```

but 

``` bash
$ testacular start --single-run --log-level error testacular.conf.js
```

and 

``` bash
$ testacular start testacular.conf.js --single-run
```

The reason is that optimist interprets `testacular.conf.js` as the value of the option `single-run` and so the config file isn't defined.

See also substack/node-optimist#42

**Comment by johnjbarton** [comment]
Super old, please reopen if this is still important.
