### ISSUE TITLE
Add support for range requests to the server

### ISSUE THREAD

**Issue by zhuker** [karma-runner/karma#2140]
### Expected behavior

Files served by karma http server should support Range: bytes=42-43

### Actual behavior

Entire file is output

### Enviroment Details
Karma version: 0.13.22

- Karma version (output of `karma --version`):
- Relevant part of your `karma.config.js` file

### Steps to reproduce the behaviour

1. Write in a test
```javascript
var xhr = new XMLHttpRequest();
xhr.open("GET", "/base/big_binary_file.dat", true);
xhr.setRequestHeader("Range", "bytes=42-43");
xhr.responseType =  "arraybuffer";
xhr.onload = () => {
expect(xhr.response.byteLength).toBe(2) 
}
```
2. Run test
3. Test fails

**Comment by dignifiedquire** [comment]
Thanks for the report, it's an interesting feature so if someone wants to implement it I'd be happy to accept a PR for it.
