### ISSUE TITLE
Fails silently if only reporter is missing

### ISSUE THREAD

**Issue by wordofchristian** [karma-runner/karma#2141]
### Expected behavior

If the plugin is missing for the only configured reporter (e.g. karma-mocha-reporter), karma should exit with an error status.
### Actual behavior

It does not run any tests and gives no failure. Only a log warning:

```
17 05 2016 13:28:27.831:WARN [reporter]: Can not load "mocha", it is not registered!
  Perhaps you are missing some plugin?
17 05 2016 13:28:27.851:WARN [karma]: No captured browser, open http://localhost:9876/
17 05 2016 13:28:27.857:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
```
### Enviroment Details
- Karma version: 0.13.22

```
module.exports = function(config) {
  config.set({
    frameworks: ['jasmine'],
    reporters: ['mocha'],
    files: ['tests/**/*']
    //...
  });
};
```
### Steps to reproduce the behaviour
1. Create simple project set reporter to `['mocha']`, but do not install the plugin for that reporter
2. `karma start`

**Comment by benwill** [comment]
Running into same issue

**Comment by johnjbarton** [comment]
Based on reading the current code this bug should have been fixed. Please reopen if you see it again.
