### ISSUE TITLE
Error while running: karma start karma.conf.js

### ISSUE THREAD

**Issue by steel119** [karma-runner/karma#2148]
When i run 
karma start karma.conf.js

I am getting the below error:

```
c:\NIWorkSpace\network-insights-web-portal>karma start karma.conf.js
24 05 2016 12:24:51.473:INFO [karma]: Karma v0.13.22 server started at http://lo
calhost:9876/
24 05 2016 12:24:51.488:INFO [launcher]: Starting browser PhantomJS
24 05 2016 12:24:52.488:INFO [reporter.remote]: Error while communicate to remot
e server ("localhost:8888") to report test results.
Error: connect ECONNREFUSED 127.0.0.1:8888
24 05 2016 12:24:52.489:INFO [reporter.remote]: Connection closed
24 05 2016 12:24:53.057:INFO [PhantomJS 2.1.1 (Windows 8 0.0.0)]: Connected on s
ocket /#dGuxYeoDdWFNol1QAAAA with id 55430891
24 05 2016 12:24:53.079:ERROR [reporter.remote]: Not connected to server.
24 05 2016 12:24:53.089:ERROR [reporter.remote]: Not connected to server.
24 05 2016 12:24:53.091:INFO [reporter.remote]: Error while communicate to remot
e server ("localhost:8888") to report test results.
Error: This socket is closed
24 05 2016 12:24:54.095:INFO [reporter.remote]: Karma finished...

c:\NIWorkSpace\network-insights-web-portal>
```

My karma.conf.js file is:

``` js
// Karma configuration
// Generated on Tue May 24 2016 10:48:30 GMT-0400 (Eastern Daylight Time)

module.exports = function(config) {
config.set({

// base path that will be used to resolve all patterns (eg. files, exclude)
basePath: '',


// frameworks to use
// available frameworks: https://npmjs.org/browse/keyword/karma-adapter
frameworks: ['jasmine'],


// list of files / patterns to load in the browser
files: [

  //'js/angular/angular.min.js',
  //'web-app/test/angular-mocks.js',
  //'js/angular/angular-mocks.js',
  'web-app/test/*Spec.js'

],


// list of files to exclude
exclude: [
],


// preprocess matching files before serving them to the browser
// available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
preprocessors: {
},


// test results reporter to use
// possible values: 'dots', 'progress'
// available reporters: https://npmjs.org/browse/keyword/karma-reporter
reporters: ['remote'],
remoteReporter: {
    host: 'localhost',
    port: '8888'
},



// web server port
port: 9876,


// enable / disable colors in the output (reporters and logs)
colors: true,


// level of logging
// possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
logLevel: config.LOG_INFO,


// enable / disable watching file and executing tests whenever any file changes
autoWatch: false,


// start these browsers
// available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
browsers: ['PhantomJS'],


// Continuous Integration mode
// if true, Karma captures browsers, runs the tests and exits
singleRun: true,

logLevel: config.LOG_INFO,

plugins: [
  'karma-jasmine',
  //'karma-junit-reporter',
  'karma-chrome-launcher',
  'karma-phantomjs-launcher',
  'karma-remote-reporter'
],

// Concurrency level
// how many browser should be started simultaneous
concurrency: Infinity
})
}
```

Any help would be appreciated.

Thanks

**Edit** added code block formatting (@dignifiedquire)

**Comment by dignifiedquire** [comment]
Looking at the error message it has to do with the remote reporter you are using, it seems the reporter is not actually available at `localhost:8888`

**Comment by steel119** [comment]
Thanks for your response. I have even tried the default port 9889 got the same error message . Any idea what to do to fix it

**Comment by dignifiedquire** [comment]
I'm not sure, what exactly this remote reporter is, I have never used it myself. Does it work if you remove it?

**Comment by steel119** [comment]
yup . It working with progress reporter
 but i am trying to set it up with grails environment using 'karma-test-runner:0.2.1'
Below is the link that i used for the reference:
https://objectpartners.com/2014/08/19/add-javascript-unit-tests-and-run-them-with-grails-test-app/

**Comment by dignifiedquire** [comment]
So according to the article this [grails plugin](http://grails.org/plugin/karma-test-runner) needs to be working, it seems the remote reporter is not connecting to it. Your best bet is to check the docs of the plugin and test if there is a service being started on the configured port.

**Comment by steel119** [comment]
Ok. Makes sense . I will try that and will get back. Thanks again

**Comment by steel119** [comment]
I got it working. Thanks for the help 
A quick question though
I have my own grails plugins where we have given angular.min.js
Now in my module where i have configured karma.conf.js i need to use the angular.min.js from the plugin as i don't want to duplicate it in all the modules.
When i run the unit test with ''test-app unit:javascript" it is not able to reference the "angular.min.js" from the plugin. Though if i give "angular.min.js" locally its running fine.

**Comment by wesleycho** [comment]
This sounds like something outside the responsibility of a reporter - it should be served statically and referenced appropriately. Depending on the approach, using the proxy option in karma's config could help accomplish this.

Going to close this, as the original issue is addressed - feel free to open a new issue if you feel there is an issue in karma itself.
