### ISSUE TITLE
Karma does not include custom context.html when running

### ISSUE THREAD

**Issue by newnottakenname** [karma-runner/karma#2151]
We are creating an ionic app and it really wants to have an `<ion-app></ion-app>` element in the html. 
### Expected behavior
test/karma-static/context.html should be used when running tests

### Actual behavior
the context.html from node_modules/karma/static/context.html is run. This is confirmed when adding a `<ion-app></ion-app>` element to this file.

### Enviroment Details

Karma version: 0.13.22
Karma Config: https://gist.github.com/newnottakenname/d35e9a69c186721b4da843157c4fc556

### Steps to reproduce the behaviour
These are the way we created it. Am not 100% sure it is reproducable this way.
1. Create a standard ionic platform
2. Change the context.html
3. See no change when testing

**Comment by dignifiedquire** [comment]
Please test the latest 1.0 release this should fix your issue. Feel free to reopen if it does not.
