### ISSUE TITLE
Moment not working with Karma unit tests

### ISSUE THREAD

**Issue by leopoldjoy** [karma-runner/karma#2156]
### Expected behavior

I expected all of my unit tests to run properly, as they do when I do not include [`moment-timezone`](https://github.com/moment/moment-timezone/) in my component that is being tested by Karma.

### Actual behaviour

None of my tests run and instead I get this error:

    START:
    Chrome 50.0.2661 (Mac OS X 10.9.2) ERROR
      Uncaught Error: Cannot find module "./data/packed/latest.json"
      at /Users/myuser/myapp/tests.webpack.js:50215 <- webpack:///~/moment-timezone/index.js:2:0
    Chrome 50.0.2661 (Mac OS X 10.9.2) ERROR
      Uncaught Error: Cannot find module "./data/packed/latest.json"
      at /Users/myuser/myapp/tests.webpack.js:50215 <- webpack:///~/moment-timezone/index.js:2:0

### Enviroment Details

- Karma version (output of `karma --version`): 0.13.22

### Steps to reproduce the behaviour

1. Run `npm install moment-timezone`
2. Include this in the top of your file: `import moment from 'moment-timezone';`
3. Include this in your component: `console.log(moment.tz.guess());`

NOTE: This is a duplicate of this [issue](https://github.com/moment/moment-timezone/issues/351) filed on the `moment-timezone` GitHub page.

**Comment by dignifiedquire** [comment]
This looks like an issue with your webpack configuration not with karma as far as I can see

**Comment by maksimr** [comment]
I agree with @dignifiedquire 

@leopoldjoy could you create small(gist) project which reproduce this problem?

**Comment by leopoldjoy** [comment]
@dignifiedquire @maksimr Thanks so much for the responses. The app I'm building is created from [this starter kit](https://github.com/erikras/react-redux-universal-hot-example). I have forked it and added one commit that illustrates the bug. You can see my example [here](https://github.com/leopoldjoy/react-redux-universal-hot-example-karma-moment-timezone-bug). If you clone it, then run `npm install` then run `npm run test` you will see the error:

    PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
      Error: Cannot find module "./data/packed/latest.json"
      at /Users/myuser/github/react-redux-universal-hot-example-karma-moment-timezone-bug/tests.webpack.js:33463 <- webpack:///~/moment-timezone/index.js:2:0

**Comment by maksimr** [comment]
@leopoldjoy thanks,

first of all you have forgotten install moment-timezone (npm install --save-dev moment-timezone) [here](https://github.com/leopoldjoy/react-redux-universal-hot-example-karma-moment-timezone-bug)

Problem in webpack config which you set in [karma.config.js](https://github.com/leopoldjoy/react-redux-universal-hot-example-karma-moment-timezone-bug/blob/master/karma.conf.js#L31-L59).
In your configuration for test you [ignore json files](https://github.com/leopoldjoy/react-redux-universal-hot-example-karma-moment-timezone-bug/blob/master/karma.conf.js#L50).
To fix your problem simple remove or comment [ignore plugin](https://github.com/leopoldjoy/react-redux-universal-hot-example-karma-moment-timezone-bug/blob/master/karma.conf.js#L50)

Thanks

**Comment by leopoldjoy** [comment]
@maksimr Thank you for the response! I had `moment-timezone` installed, I just forgot the `--save`, sorry. Worked perfectly once commented! 👍
