### ISSUE TITLE
Karma proxy matching url patterns

### ISSUE THREAD

**Issue by gayanwiharagoda** [karma-runner/karma#2167]
I am trying to match url pattern that ending up with .cmd and map it for other url  like below examples.

http://localhost:9877/test1.cmd  to http://localhost/test1.cmd 
http://localhost:9877/test2.cmd   to http://localhost/test2.cmd 
http://localhost:9877/test3.cmd   to http://localhost/test3.cmd 

You can see that target url contain part of the original url. Can we achieve this using Karma proxy.

**Comment by wesleycho** [comment]
I do not believe this is possible, as Karma requires a server to serve off of, and port 80 is reserved by the browser. Is there a particular reason why one absolutely must have the port number removed when running tests?

**Comment by gayanwiharagoda** [comment]
I have resolve this by adding port 80 in target pattern like below. Thank you for the reply. I hope it will help others.
http://localhost:9877/test1.cmd to http://localhost:80/test1.cmd

**Comment by wesleycho** [comment]
Ah, so you were serving from port 80 - a proxy with karma.conf.js then accomplishes that.

Sounds like you have a solution, so I am going to close this issue.
