### ISSUE TITLE
Node-6.x compatability

### ISSUE THREAD

**Issue by Trakkasure** [karma-runner/karma#2170]
### Expected behavior
It installs when "npm install"ing with node v6

### Actual behavior
Does not since current version published in NPM (0.13.22) does not have 6 in engines

### Enviroment Details
Node v6

- Karma version (output of `karma --version`):
- Relevant part of your `karma.config.js` file

### Steps to reproduce the behaviour

1. Using node v6 install karma

**Comment by dignifiedquire** [comment]
1.0 has full 6.0 compatability
