### ISSUE TITLE
Proxies throwing WARN as of 0.13

### ISSUE THREAD

**Issue by stramel** [karma-runner/karma#2174]
### Expected behavior

No `WARN [proxy]: failed to proxy` messages while running unit tests. These were previously working fine in 0.12.
### Actual behavior

While running unit tests, `WARN [proxy]: failed to proxy` messages are thrown
### Enviroment Details
- Karma version (output of `karma --version`): Karma version: 0.13.22
- Relevant part of your `karma.config.js` file

```
...
proxies: {
   '/profileImageUrl': 'http://lorempixel.com/60/60',
   '/assets/images/default-logo.png': 'http://lorempixel.com/60/60',
},
...
```
### Steps to reproduce the behaviour
1. Add the above snippet to your `karma.conf.js`
2. Test making a call to either URI
3. Observe that a `WARN [proxy]: failed to proxy /60/60 (connect ECONNREFUSED)` has been produced

**NOTE:** Adding `:80` to the url gives `WARN [proxy]: failed to proxy /60/60 (getaddrinfo ENOTFOUND lorempixel)`

**Comment by Karatsuba** [comment]
Hey @stramel . I run into the same problem. Do you find some solution for this?

**Comment by maksimr** [comment]
@Karatsuba @stramel 

You should use [`changeOrigin`](http://karma-runner.github.io/1.0/config/configuration-file.html) option

```js
 proxies: {
      '/profileImageUrl': {
        target: 'http://lorempixel.com/60/60',
        changeOrigin: true
      },
      '/assets/images/default-logo.png': {
        target: 'http://lorempixel.com/60/60',
        changeOrigin: true
      }
    },
```


[Example](https://gist.github.com/maksimr/30626efa5e63df2cb8836d80455cf96e)
