### ISSUE TITLE
Is this repository slowly dying ?

### ISSUE THREAD

**Issue by vperron** [karma-runner/karma#2184]
### Expected behavior
Have updated versions from time to time.

### Actual behavior
Current master breaks API compatibility with many plugins, no version update since March.
Docs are slightly outdated.

### Enviroment Details
Latest 0.13.22 lacks so many things.

### Steps to reproduce the behaviour

1. Install karma
2. Notice how many workarounds you need
3. Wonder why all those PRs are just sitting there :)

### Seriously now
I'd be more than happy to be of any help here ! But if this keeps this really slow pace of fixups, I will have to turn to another solution or become one of the 1133 forks out there. Maybe open up to many, many more contributors able to merge (and fix) stuff ? Stop making us click on those "Agree to Google Guidelines" forms that just slows improvement attempts ?

Let us know !

**Comment by Florian-R** [comment]
I guess you can close this one : https://github.com/karma-runner/karma/issues/1406#issuecomment-228146183

**Comment by dignifiedquire** [comment]
No this repository is not dying. If you want to help out I would appreciate it. I'm sorry you that the Google CLA is an issue for you but I'm afraid it won't go away anytime soon. I work on this project in my free time  pretty much alone and sometimes I don't find to maintain it to the level I would like. So if you want to help please do so.
