### ISSUE TITLE
Broken links on CONTRIBUTING.md

### ISSUE THREAD

**Issue by hpurmann** [karma-runner/karma#2207]
### Expected behavior

Links
* https://github.com/karma-runner/karma/blob/master/egghead_series
* http://karma-runner.github.io/0.13/dev/egghead_series

lead somewhere.

### Actual behavior

The links are leading to 404 pages.

### Steps to reproduce the behaviour

1. Go on https://github.com/karma-runner/karma/blob/master/CONTRIBUTING.md
2. Click links "get started" and "How to Contribute to an Open Source Project on GitHub"
3. See 404 ;)

**Comment by dignifiedquire** [comment]
Thanks, looking at the raw markdown for CONTRIBUTING.md it should work though, the correct link is at the bottom and it looks like Github somehow doesn't resolve the right link?
