### ISSUE TITLE
Error formatting misleads when URL ends base/

### ISSUE THREAD

**Issue by mthx** [karma-runner/karma#2209]
### Actual behavior

I had a test that ultimately boiled down to the following Jasmine expectation:

```
expect('http://www.google.com/base/').toEqual('http://www.example.com/base/');
```

As the failure message, I get:

```
Expected '' to equal ''
```

This was quite puzzling and a pain to isolate to karma in my real scenario.
### Expected behavior

Clear message as given by Jasmine directly:

```
Expected 'http://www.google.com/base/' to equal 'http://www.example.com/base/'.
```

I think this issue relates to the URL_REGEXP in Karma's reporter.js but I haven't dived deep enough to follow what's going on there.
### Environment Details
- Karma version (output of `karma --version`):

Karma version: 1.1.0
- Relevant part of your `karma.config.js` file

Minimal jasmine config.
### Steps to reproduce the behaviour
1. Checkout https://github.com/mthx/karma-error-reporting-issue
2. npm install
3. npm run test-jasmine
4. npm run test-karma
5. Note the failures from the latter have empty strings as URLs in the error message

**Comment by wesleycho** [comment]
What is happening here is that karma is truncating the strings before `/base`

**Comment by wesleycho** [comment]
@dignifiedquire what are your thoughts on perhaps making a breaking change to choose a unique name for the base url, such as `karma-base/`? It would be much less likely to conflict than a common name like `base` is alone.

**Comment by dignifiedquire** [comment]
If we are switching we should be switching to something more specific, like`__karma__base__/`. But to fix this issue we should be able to adjust the matcher, such that it only replaces inside urls where the host is the same as `config.hostname`.

**Comment by wesleycho** [comment]
So maybe a configurable option like `config.basename` would work?
