### ISSUE TITLE
Needed boilerplate for call `require` inside adapter.js

### ISSUE THREAD

**Issue by bySabi** [karma-runner/karma#2216]
I'm in the process of rewrite a Karma adapter and need `require` modules inside `adapter.js` file.

Is any example that expose `require` global inside `adapter.js`??

**Comment by dignifiedquire** [comment]
There are mo adapters that use a global require as far as I know. Dependencies are usually injected in a build step using browserify or webpack or sth self built

**Comment by bySabi** [comment]
this make sense!
@dignifiedquire you know project that include a build step with browserify or webpack?

**Comment by dignifiedquire** [comment]
Not really I'm afraid, but you can look at e.g. https://github.com/karma-runner/karma-mocha for an example with a custom build step.

**Comment by bySabi** [comment]
Not prob!
I have a working repo with a browserify build step that bundled dependencies. Is really simple one time you know how doit :-)

I put a fragment here of the relevant part for any one ...

package.json
```json
 ...
  "main": "index.js",
  "scripts": {
    "clean": "rimraf lib",
    "build:parser": "browserify src/parser.js --s tapParser -o lib/parser.js",
    "build-npm": "npm run clean && mkdirp lib && npm run build:parser",
...
```
karma adapter files:

index.js
```js
var createPattern = function(path) {
  return {pattern: path, included: true, served: true, watched: false};
};

var initTAP = function(files, tapConfig) {
  files.unshift(createPattern(__dirname + '/src/adapter.js'));
  files.unshift(createPattern(__dirname + '/lib/parser.js'));
};

initTAP.$inject = ['config.files'];

module.exports = {
  'framework:tap': ['factory', initTAP]
};

``` 


src/parser.js
```
var finished = require('tap-finished');
var parser = require('tap-parser');

module.exports = {
  finished: finished,
  parser: parser
};
```


fragment of `src/adapter.js`
```
// global object tapParser from 'parser.js'
var finished = tapParser.finished;
var parser = tapParser.parser;

var createStartFn = function(tc, env) {
  var numResults = 0;
...
```

I'll try update current `karma-tap` module, it need  some love :-)

Thanks

**Comment by bySabi** [comment]
Hello @dignifiedquire I need a little support from you.

Right know I´m trying to improve  [karma-tap](https://github.com/tmcw-up-for-adoption/karma-tap) framework adapter. Author don´t used anymore cause that the project don´t have a maintainer. I cannot be this man cause my english, karma, and tap is not enough but I want to help with some code.

I have been working with the adapter output, `karma.result` object. But 'TAP output' not fit very well with `result`. tap-parser emit various kinds of outputs: 'version', 'comment', 'assert', ...

* 'assert' fit on result `description` and `sucess` property
* 'comment' could be on `suite` of already set result 'assert'
* 'version' don´t fix at all

I don´t know what is next ...

I need implement a custom reporter inside the adapter framework and create a framework/reporter karma plugin ??

Thanks for your time.

Current working `adapter.js`

```
// global object tapParser from 'parser.js'
var finished = tapParser.finished;
var parser = tapParser.parser;

function createStartFn(tc) {
  var numResults = 0;
  var done = false;
  var res = [];
  var suite = [];
  var startTime = new Date().getTime();
  var parse_stream = parser();

  parse_stream.on('version', function(version) {
    res.push({
      description: version,
    });
  });

  parse_stream.on('comment', function(comment) {
    suite = [comment];
  });

  parse_stream.on('assert', function(assertion) {
    numResults++;
    res.push({
      description: assertion.name,
      success: assertion.ok,
      log: [JSON.stringify(assertion.diag || assertion, null, 2)],
      suite: suite,
      time: new Date().getTime() - startTime
    });
  });

  parse_stream.on('complete', function(results) {
    tc.info({ total: numResults });
    for (var i = 0, len = res.length; i < len; i++) {
      tc.result(res[i]);
    }
    tc.complete({
      coverage: window.__coverage__
    });
  });

  // this part lifted from zuul
  // https://github.com/defunctzombie/zuul/blob/master/frameworks/tape/client.js

  var finished_stream = finished(function() {
      done = true;
      parse_stream.end();
  });

  var originalLog = console.log;
  console.log = function () {
      var msg = arguments[0];

      // do not write in a closed WriteStream
      if (!done) {
          parse_stream.write(msg + '\n');
          finished_stream.write(msg + '\n');
      }

      // transfer log to original console,
      // this shows the tap output in console
      // and also let the user add console logs
      if (typeof originalLog === 'function') {
          return originalLog.apply(this, arguments);
      }
  };

  return function(config) {
  };
};

window.__karma__.start = createStartFn(window.__karma__);

```

console OUTPUT

```
30 06 2016 19:27:00.935:INFO [Node.js (darwin; U; rv:v6.2.2)]: Connected on socket /#NPEEVgJo1Wmp5XodAAAA with id 4924025
ok 1 # beep
 should be equal
ok 2 # beep
 should be equivalent
ok 3 # boop
 should be equal
ok 4 # boop
 should be truthy
1..4
```


Normal, wanted!,  OUTPUT from `node test.js`

```
$ node test.js
TAP version 13
# beep
ok 1 should be equal
ok 2 should be equivalent
# boop
ok 3 should be equal
ok 4 should be truthy

1..4
# tests 4
# pass  4

# ok
```


Thanks again for reading over here  :-)

**Comment by bySabi** [comment]
@tmcw I know you don´t use karma-tap anymore but maybe you can comment anything on this issue.

**Comment by dignifiedquire** [comment]
The output already looks pretty close to what is expected, it looks like the only thing you are missing are a couple of line breaks and the version?

**Comment by bySabi** [comment]
Well it seens I could solve all `karma-tap` problems. Solution is on PR status now: https://github.com/tmcw-up-for-adoption/karma-tap/pull/15
I fixed `karma-tap-reporter` too but I have not PR yet.

**Comment by bySabi** [comment]
The issues are solved!

 Thanks for feedback :-)

**Comment by dignifiedquire** [comment]
Awesome great to hear and thanks for the work @bySabi
