### ISSUE TITLE
could not load plugins while karma not installed in node_modules/karma

### ISSUE THREAD

**Issue by zincli** [karma-runner/karma#2221]
### Expected behavior

loading plugins even if karma installed in sub directory in node_modules
### Actual behavior

can not load plugins
### Enviroment Details
- Karma version 1.1.0 and 0.0.13 (output of `karma --version`):
### Steps to reproduce the behaviour

karma installed by a npm installing tool, located in `node_modules/.npminstall/karma`, the same as all other karma plugins.

**Comment by zincli** [comment]
I think that code [here](https://github.com/karma-runner/karma/blob/master/lib/plugin.js#L33) load plugins could be promoted to resolve this problem.

```
var pluginDirectory = path.normalize(path.join(__dirname, '/../..'))

// could be changed to 

var pluginDirectory = path.normalize(path.join(process.cwd(), 'node_modules'))

```

I'd like to make a PR, but it would take some time

**Comment by zincli** [comment]
I checked out the source code, but the unit test failed ... master branch

here is some error info, is that normal?

```
01 07 2016 00:58:06.047:ERROR [launcher]: Chrome failed 2 times (timeout). Giving up.
[Error: failed to add custom browserify preprocessor
{ [Error: Cannot find module 'karma/lib/preprocessor'] code: 'MODULE_NOT_FOUND' }]
Fatal error: Client unit tests failed.
```

**Comment by zincli** [comment]
I made some change in #2404, now all ci passed. @dignifiedquire could you please take a look at it.  I would like to add some tests but not found tests about plugin loading.

**Comment by wesleycho** [comment]
Can you explain more in detail your setup that causes this problem to be exposed? The change in the PR is likely not to get merged, as it appears to add potential problems & smells like a hack. With more detail, a better fix can probably emerge.

**Comment by zincli** [comment]
Thanks you guys. This issue could be closed. We had drop the use of npm-install which causes this problem. `npm install` is too slow for us T_T, but now we found another way faster to install.
