### ISSUE TITLE
How to load external static files when my source code needs 

### ISSUE THREAD

**Issue by tangbc** [karma-runner/karma#2233]
### Expected behavior

I want to test a `loading-external-template` module, it needs to load some external html template files.
### Actual behavior

The test code look likes:

``` javascript
// template is a encapsulation module of ajax
var template = require('template');

describe('loading-external-template test', function(done) {
    it('test', function() {
        template('/assets/page.html', function(text) {
            expect(text).toBe('<b>hello Karma runner</b>');
            done();
        });
    });
});
```

/assets/page.html :

``` html
<b>hello Karma runner</b>
```

When I running test, it throw:

```
04 07 2016 17:04:51.564:WARN [web-server]: 404: /assets/page.html
```
### Enviroment Details
- karma version 0.13.22:
- karma.config.js is:

``` javascript
...
'basePath': '../test/units/',
'files': [
    'index.js',
    {'pattern': 'assets/*.html', 'watched': false, 'included': false, 'served': true}
],
...
```

So my question is, how to load external static files(html, json ...) when my source code needs to load them ?

**Comment by yudhasetiawan** [comment]
@tangbc did you try using ```/base/assets/page.html```?

Because Karma serves files from base path under ```<urlRoot>/base/```, where **urlRoot** is ```/``` by default.

**Comment by wesleycho** [comment]
In this case, likely what is desired is to use a proxy. @tangbc can you let us know if either approach works for you, so that we can close this issue?
