### ISSUE TITLE
v1.1.0 with `karma-tap`: "You need to include some adapter that implements __karma__.start method!"

### ISSUE THREAD

**Issue by unional** [karma-runner/karma#2236]
Confirm it is v1 issue. Downgrade back to 0.13.22 works correctly.

**Comment by dignifiedquire** [comment]
This is a bug in karma-tap rather than karma itself, some of the internals changed in v1 and karma-tap needs to be updated accordingly

**Comment by unional** [comment]
What need to change? Do you have some info about that?  Karma-tap is not being maintained so I need to create pr to fix it.

**Comment by dignifiedquire** [comment]
Someone is already working on fixing karma-tap I believe, see #2216. 
As to what exactly needs to be fixed I don't know as I have not looked at karma-tap yet.

**Comment by bySabi** [comment]
With current karma-tap 1.0.4 and karma 1.1.0 I don´t have this issue.
Tested on OSX

**Comment by dignifiedquire** [comment]
@unional can you please check if that fixes your issues?

**Comment by unional** [comment]
Nope. I checked with `karma-tap@1.0.4` and `karma@1.1.1` and still has the same error.
Test on Windows

**Comment by bySabi** [comment]
Probably is a windows only error. I will test on windows to see what happend.

**Comment by bySabi** [comment]
Finally `karma-tap` v2 and [karma-tap-pretty-reporter](https://www.npmjs.com/package/karma-tap-pretty-reporter) is out.
Can be tested with [karma--tap--boilerplate](https://github.com/bySabi/karma--tap--boilerplate)

I don´t test it on windows yet, sorry! :-(

**Comment by unional** [comment]
Ouch. Still doesn't work. :(

**Comment by unional** [comment]
Closing this and move to `karma-tap`

**Comment by bySabi** [comment]
@unional I can confirm that `karma 1.1.1` and `karma-tap 2.0.1` works OK on windows.
Tested with  [karma--tap--boilerplate](https://github.com/bySabi/karma--tap--boilerplate)

**Comment by unional** [comment]
Yes. I found it to be `karma-jspm` issue which causes this. Thanks! 🌷
