### ISSUE TITLE
How to debug the "You need to include some adapter that implements __karma__.start method!" error?

### ISSUE THREAD

**Issue by C3-TKO** [karma-runner/karma#2237]
### Expected behavior
I expected that karma is still working after update from 0.13.9 to 1.1.0. If karma is not working properly anymore i would like to have some more information how to fix this problem myself

### Actual behavior
07 07 2016 08:36:13.016:INFO [karma]: Karma v1.1.0 server started at http://localhost:8080/
07 07 2016 08:36:13.019:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
07 07 2016 08:36:13.087:INFO [launcher]: Starting browser PhantomJS
07 07 2016 08:36:14.570:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket /#kR-iedk86tRVJxHqAAAA with id 89582790
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  You need to include some adapter that implements __karma__.start method!

### Enviroment Details
https://github.com/C3-TKO/junkan/blob/update-karma-to-1.0.0/karma.conf.js
https://github.com/C3-TKO/junkan/blob/update-karma-to-1.0.0/package.json

### Steps to reproduce the behaviour

1. Checkout branch https://github.com/C3-TKO/junkan/tree/update-karma-to-1.0.0
2. npm install
3. npm run test

I would be glad if you could tell me hoy debug this issue myself. I already checked other issues with the same error and most of the times this is an error regarding a dependency but i failed at recognizing how to debug this myself and how to find out where the adapter fails. It should be the one of karma-mocha.

**Comment by dignifiedquire** [comment]
This is related due to some plugins not being updated and ready for karma 1.0. See #2194 for details and workarounds.
