### ISSUE TITLE
Received `postMessage` for "undefined" but the method doesn't exist

### ISSUE THREAD

**Issue by mstaas** [karma-runner/karma#2239]
### Expected behavior

Projects that use postMessage should not break karma

### Actual behavior

This change makes karma incompatible with projects that use postMessage https://github.com/karma-runner/karma/commit/81b1f04c70eb14ca675f60b3f374bb50b96d80fe#diff-e935b6c040afc12b7a014e625f4f0cedR40

### Enviroment Details

https://bitbucket.org/atlassian/simple-xdm/addon/pipelines/home#!/results/%7Bcc56070d-5ec1-43f2-ab8e-07cf4e6309a5%7D

- Karma version (output of `karma --version`): 1.1.1
- Relevant part of your `karma.config.js` file N/A

### Steps to reproduce the behaviour

1. Write test that uses postMessage
2. Run test with karma
3. Karma receives postMessage it doesn't expect and balks

Consider changing log to warn rather than error or namespacing your postMessages

**Comment by pronav** [comment]
I faced the exact same issue with Karma 1.1.1, had to roll back.

**Comment by dignifiedquire** [comment]
@twolfson you wrote that patch, any good ideas on how we can enable `postMessage` to be used by client code?

**Comment by twolfson** [comment]
Ah, damn. Sorry for my ignorance on that. Maybe we should move from `data.method` to `data.__karma_method` as a magic key (to prevent issues where an application might use `data.method` as well) and remove the assertion (or drop it to a `console.warn`) to prevent throwing errors with other programs using `postMessage` at all.

**Comment by twolfson** [comment]
I should clarify that that assertion is mostly for development on Karma; when we were porting between contexts I wanted to make sure I didn't create any typos. Maybe there is an environment variable we can look at to perform the assertion as well?

**Comment by dignifiedquire** [comment]
I don't think we need to keep the assertion, dropping it to a warning would be good. That way you would easily see it during development.

**Comment by mstaas** [comment]
I'm not particularly concerned about warns in my logs but I would like my build to pass 😄

**Comment by twolfson** [comment]
I think I had fixation on the solution before; an equally valid check is that the method name is truthy. I don't have much time this morning but I'm going to try to push out a PR to fix it (with a test).

**Comment by dignifiedquire** [comment]
thanks @twolfson I won't be available much as I'm travelling for the next week, but I'll make sure to check your PR when it's up.

**Comment by twolfson** [comment]
I took a shot at a test but wasn't able to get it working and ran out of time. However, I have completed a patch and will be submitting a PR shortly.
