### ISSUE TITLE
Karma is heavily spamming WARN [proxy] in console

### ISSUE THREAD

**Issue by alexander-ossur** [karma-runner/karma#2243]
Hi,

Having a strange behavior here when Karma + Jasmine trying to access non existing file
### Expected behavior
1. Karma should NOT spam warnings (hundreds, may be thousands in time). For example many lines of these:

> 10 07 2016 12:51:43.988:WARN [proxy]: failed to proxy /base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/base/favicon.ico (socket hang up)
### Actual behavior
1. Obviously file is not found - should print this only once
### Enviroment Details
- windows 8.1
- gulp CLI version 3.9.1
- gulp Local version 3.9.1
- Karma version: 1.1.0
- jasmine-core: 2.4.1
- Relevant part of your `karma.config.js` file

```
        "browsers": ["Chrome"],
        "frameworks": ["jasmine-ajax", "jasmine"],
        "basePath": "./dist",
        "files": [
            "asset/library/bluebird/3.3.5/bluebird.js",
            { "pattern": "application/chrome/module/System.js", "included": false, "watched": true, "served": true },
            "test-suite/bootstrap.spec.js",
            "**/test-suite/**/*.spec.js"
        ],
        "urlRoot": "__karma__",
        "proxies": {
            "/": "/base/"
        },
        "reporters": ["progress", "coverage"],
        "autoWatch": true,
        "singleRun": false

```
### Steps to reproduce the behaviour
1. The easiest way is to open existing file in the browser: Ex: http://localhost:9876/asset/library/bluebird/3.3.5/bluebird.js

The file content will show fine, yet after a few seconds console will start spamming the messages
### Workaround

```
        "urlRoot": "",
        "proxies": {
            "/asset/": "/base/asset/",
            "/application/": "/base/application/",
            "/test-suite/": "/base/test-suite/"
        },
```

**Comment by wesleycho** [comment]
Is this still an issue? I haven't seen something like this when a file isn't found, it just spits out a simple 404 in the console with the actual path it tried to request for.

**Comment by alexander-ossur** [comment]
Apologies for the late reply,

Unfortunately I can not check the issue for at least a month. Please feel free to close it if necessary. I will come back with it later for sure if issue is still exists.
