### ISSUE TITLE
INFO [launcher]: Launching browser PhantomJS with unlimited concurrency after execution automatically not coming out from Terminal

### ISSUE THREAD

**Issue by balu123456** [karma-runner/karma#2248]
### Expected behavior

once Karma execution completed it should come out from terminal. 
### Actual behavior

once Karma execution completed still in terminal only in running mode
### Enviroment Details

Using MAC.
- Karma version (output of `karma --version`): karma@1.1.1
- Relevant part of your `karma.config.js` file: 

/recoveries-app/config/karma.config.js
### Steps to reproduce the behaviour
1. I am using Angular2 with Angular CLI, i am using ng test to run karma test cases
2. i have installed following plugins (npm install phantomjs
   npm install karma-phantomjs-launcher --save-dev)
   3.it is running as exepected, please find the below screens shot

<img width="949" alt="screenshot" src="https://cloud.githubusercontent.com/assets/19956404/16734607/28bd0a82-4754-11e6-8ec6-503c299b2ecb.png">

Can you please help me out if i need to keep any additional setting in karma.conf.js and also find conf file

// Karma configuration file, see link for more information
// https://karma-runner.github.io/0.13/config/configuration-file.html

```js
module.exports = function (config) {
  config.set({
    basePath: '..',
    frameworks: ['jasmine'],
    /_plugins: [
      require('karma-jasmine')
      require('karma-chrome-launcher')
    ],
    customLaunchers: {
      // chrome setup for travis CI using chromium
      Chrome_travis_ci: {
        base: 'Chrome',
        flags: ['--no-sandbox']
      }
    },_/
    files: [
      { pattern: 'dist/vendor/es6-shim/es6-shim.js', included: true, watched: false },
      { pattern: 'dist/vendor/zone.js/dist/zone.js', included: true, watched: false },
      { pattern: 'dist/vendor/reflect-metadata/Reflect.js', included: true, watched: false },
      { pattern: 'dist/vendor/systemjs/dist/system-polyfills.js', included: true, watched: false },
      { pattern: 'dist/vendor/systemjs/dist/system.src.js', included: true, watched: false },
      { pattern: 'dist/vendor/zone.js/dist/async-test.js', included: true, watched: false },
      { pattern: 'dist/vendor/zone.js/dist/fake-async-test.js', included: true, watched: false },

  { pattern: 'config/karma-test-shim.js', included: true, watched: true },

  // Distribution folder.
  { pattern: 'dist/**/*', included: false, watched: true }
],
exclude: [
  // Vendor packages might include spec files. We don't want to use those.
  'dist/vendor/**/*.spec.js'
],
preprocessors: {},
reporters: ['progress'],
port: 9876,
colors: true,
logLevel: config.LOG_INFO,
autoWatch: true,
//browsers: ['Chrome'],
browsers: ['PhantomJS'],
//singleRun: false
singleRun: true

  });
};
```
Note: i have made singleRun: true. still it is not coming out from the running mode

**Comment by maksimr** [comment]
@balu123456 could you create stub project which reproduce this problem

Thanks!

**Comment by devoto13** [comment]
Angular CLI overrides Karma's `singleRun` variable, when tests are run through `ng test`. To prevent `ng test` from using watch mode you can run `ng test --watch false` or specify the same property in the `angular.json`.
