### ISSUE TITLE
karma@1.1.1 is spewing "use your own version of lodash" message

### ISSUE THREAD

**Issue by nareshbhatia** [karma-runner/karma#2257]
Is this related to https://github.com/karma-runner/karma-coffee-preprocessor/issues/39? I added my own version of lodash to my project (`npm install --save-dev lodash`), but the message is still there.

**Comment by dignifiedquire** [comment]
Yes, this error message is related to each karma plugin being used and if it's using the lodash from karma it will print this error message.

**Comment by nareshbhatia** [comment]
So I assume nothing can be done about this until the respective plugins stop using lodash from Karma.

**Comment by dignifiedquire** [comment]
Yes, but please file issues on the plugins that have this. karma-coffeescript-preprocessor has this fixed in the last release (769283e7e348a612f54a95ceed672b26ad6fef92)

**Comment by nareshbhatia** [comment]
Yep, will try to track down which one is doing this.

**Comment by aciccarello** [comment]
Should the message say something to indicate that it is the plugin that needs to be changed? Something like "Karma plugin needs to use it's own version of lodash". This would clarify why the warning is being thrown and what code needs to be updated.
