### ISSUE TITLE
Sourcemap with PhantomJS > 2.1.1 ?

### ISSUE THREAD

**Issue by JulienPalard** [karma-runner/karma#2268]
I'm using PhantomJS `2.1.1` from `phantomjs-prebuilt@2.1.7`,  and my stacktraces look like:

(long paths redacted for readability)

```
        TypeError: undefined is not an object (evaluating 't.data.lead') in /[...]/js/all.js (line 1)
        responseHook@/[...]/js/all.js:1:24890
        /[...]/js/all.js:1:25508
```

I tried installing `karma-sourcemap-loader`, `require('source-map-support').install();` in my `conf.js`, and using the `sourcemap` preprocessor for `**/*.js`, but it did not enhanced my stacktraces.
### Expected behavior

Stacktrace should be readable, I mean, "sourcemap-processed", so I can file from which file the exception was raised.
### Actual behavior

Stacktrace are useless, showing sources like: `all.js:1:25182`
### Enviroment Details
- Karma version (output of `karma --version`): 1.1.1
- Relevant part of your `karma.config.js` file

```
frameworks: ['jasmine', 'source-map-support'],
[...]
preprocessors: {
      '**/*.js': ['sourcemap']
},
[...]
browsers: ['PhantomJS']
```

My `all.js` is built using `gulp` which uses `browserify`. `karma` is configured to use the output (Can't use my files as they use `require` so they need the `browserify` step).

**Comment by dignifiedquire** [comment]
Are you using `karma-browserify` for building your bundle?

**Comment by JulienPalard** [comment]
No, my bundle is build using `gulp`, without any reference/specificities to the tests. My gulp is building a normal bundle, then I test it.

If possible I'd like to keep it that way: testing the bundle I really use, not a "test-dependent" or "test-specific", "probably hiding bugs" version of it (but if really needed I still can, it's better than nothing).

**Comment by robmcm** [comment]
Did you manage to resolve this? It seems Phantom doesn't map stack traces to the source maps, but source maps are there for coverage etc

Is it just an issue with PhantomJS source map support?

**Comment by JoshSchreuder** [comment]
Sadly I have the same issue with `phantomjs-prebuilt@2.1.7`. Running the same tests in Chrome / Firefox correctly picks up the sourcemaps in stacktraces. This seems to be a problem with Phantom.

**Comment by devoto13** [comment]
Closing as issue seems to be coming from PhantomJS and not from Karma. Also PhantomJS has been archived and it is better to use headless Chrome or Firefox nowadays.
