### ISSUE TITLE
Chrome (52) have not captured, killing

### ISSUE THREAD

**Issue by Hadev-JHH** [karma-runner/karma#2279]
As of an update to Chrome 52 our CI buildserver is having issues running our karma specs.

below is a log:

INFO [karma]: �[39mKarma v1.1.1 server started at http://localhost:9876/
INFO [launcher]: �[39mLaunching browser Chrome with unlimited concurrency
INFO [launcher]: �[39mStarting browser Chrome
WARN [launcher]: �[39mChrome have not captured in 60000 ms, killing.
INFO [launcher]: �[39mTrying to start Chrome again (1/2).
WARN [launcher]: �[39mChrome have not captured in 60000 ms, killing.
INFO [launcher]: �[39mTrying to start Chrome again (2/2).
WARN [launcher]: �[39mChrome have not captured in 60000 ms, killing.
ERROR [launcher]: �[39mChrome failed 2 times (timeout). Giving up.

Details:
Karma 1.1.1
Karma-Chrome-Launcher 1.0.1
Chrome 52

Kind Regards

copy of issue reported to karma-chrome-launcher

**Comment by dignifiedquire** [comment]
Please keep the issue on the launcher.
