### ISSUE TITLE
Configuration per Test Script

### ISSUE THREAD

**Issue by craig552uk** [karma-runner/karma#2282]
Is is possible to use different Karma configurations for different test scripts?
I'm aware that I can run multiple karma instances with different `karma.conf.js` files, but what I'd like to do it run a single Karma instance which applies different configuration to different test scripts.

Specifically, I'd like to use a `customContextFile` for some tests, while using the default for others.

Given the configuration is exported as a Node module, I wondered if it were possible to override some values within the test script files (possibly in the `before` hook)?

**Comment by dignifiedquire** [comment]
No this is not possible at the moment, and I do not think it would be easily added. Your best bet is to use something like grunt or gulp or a custom node.js script to start and stop karma with different configurations to achieve what you are asking for. 
If the only difference you are looking for though is the contextFile, you might be able to use a contextFile with some JavaScript that checks for globals and inserts different things depending on them, e.g.

```html
<html>
<head>
  <script>
    if (window.testA) {
    } 
  </script>
</head>
</html>
```

**Comment by craig552uk** [comment]
Yes, this is the solution I've put in place.
Thank you
