### ISSUE TITLE
make div go to full-screen, works outside of karma.

### ISSUE THREAD

**Issue by mahmoodabuzaina** [karma-runner/karma#2292]
### Expected behavior

I'm trying to make a div element that I injected before each test go to full-screen, outside of karma it works, but have no idea why nothing happens when I test the function in karma.
### Actual behavior

call the function to go to full screen and actually do it again manually, but doesn' t go to full screen when checked.
### Enviroment Details

node.js, chrome, karma, jasmine
- Karma version (output of `karma --version`): 1.1.1
- Relevant part of your `karma.config.js` file
### Steps to reproduce the behaviour
1. Have a div element with an id.
2. write a function to make it go to full-screen.
3. test the function in karma by injecting a div element and then calling the function.

**Comment by dignifiedquire** [comment]
Karma runs tests inside an iframe, so your div is inside an iframe. If you want to go fullscreen you first need to adjust the iframe

**Comment by wesleycho** [comment]
Wouldn't another option be to not use an iframe using `client.useIframe`?

In any case, this can probably be closed as a support issue.

**Comment by maksimr** [comment]
Agree with @wesleycho try use `useIframe: false` it should resolve your issue

Thanks

**Comment by dignifiedquire** [comment]
Closing, please let us know if this persists @mahmoodabuzaina
