### ISSUE TITLE
Karma does not pick up files from folders containing hyphens in their names

### ISSUE THREAD

**Issue by vivekkodira1** [karma-runner/karma#2305]
### Expected behavior

A test should be picked up even if it is under a folder containing a hyphen in the name
### Actual behavior

Test is not picked up
### Enviroment Details

Version: 0.13.22
Config: files: [
      { pattern: "test/specs/*_/_.js", included: false },
    ],
### Steps to reproduce the behaviour
1. Add a file to a sub-folder containing a hyphen in the name
2. Run Karma: Test is not picked up
3. Rename folder and remove hyphen. 
4. Rerun karma: Test is now picked up

**Comment by MLefebvreICO** [comment]
I'm pretty sure this was fixed in a newer version since it's not happening on my end. Try updating your karma to a newer version and see if you can reproduce it.

**Comment by wesleycho** [comment]
I have not had this problem either - this can probably be closed as fixed in a newer release.

**Comment by EzraBrooks** [comment]
No feedback in a year, assuming fixed. Closing.
