### ISSUE TITLE
NPM run test (Karma) fails always in Windows

### ISSUE THREAD

**Issue by vivinRajagopalan** [karma-runner/karma#2309]
### Actual behavior

This is the test script that has been configured in package.json
**"test": "node --max-old-space-size=4096 ./node_modules/.bin/karma start"**
BUT WHEN i try to execute it, it always error. Please find the below file for npm debug
[npmdebugfile.txt](https://github.com/karma-runner/karma/files/417219/npmdebugfile.txt)

Please let me know what can be done.

I have the latest node js installed and working too !.

Thanks in advance

**Comment by dignifiedquire** [comment]
It seems that there are some issues with how the command is executed. Please make sure that if you execute this command on the command line manually it works. 

Closing this issue as it looks to not be related with karma, but rather Windows + npm + node
