### ISSUE TITLE
Karma depend on chokidar which depend on fsevents - that is not compatiable with Windows

### ISSUE THREAD

**Issue by jacovc86** [karma-runner/karma#2311]
### Expected behavior
Be completely compatiable with Windows
### Actual behavior
Depend on module fsevents which is not compatible with Windows
### Enviroment Details
Windows_NT 10.0.10586
node v6.3.1
npm  v3.10.3
OS: win32
Arch: x64

- Karma version (output of `karma --version`):
1.2.0
- Relevant part of your `karma.config.js` file
irrelevant

**Comment by dignifiedquire** [comment]
`chokidar` is fully compatible with Windows. It is used for example in Microsoft's Visual Studio Code. `fsevents` is only an optional dependency that is used if available, but gracefully falls back to other methods of change detection. For more details see https://github.com/paulmillr/chokidar
