### ISSUE TITLE
JS errors from PhantomJS do not cause a failure

### ISSUE THREAD

**Issue by opensrcken** [karma-runner/karma#2321]
### Expected behavior

A Javascript Error should stop the test run and return a non-0 exit code.
### Actual behavior

Karma ignores the JS error, running whatever tests it can.
### Enviroment Details
- Karma version (output of `karma --version`): 1.2.0
- Relevant part of your `karma.config.js` file

```
module.exports = function (config) {
  config.set({
    port: 9876,
    colors: true,

    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_INFO,

    browsers: ['Chrome', 'PhantomJS'],

    autoWatch: true,
    singleRun: false,

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '.',

    frameworks: ['qunit'],

    files: [
      require.resolve('babel-polyfill/dist/polyfill'),
      require.resolve('jquery'),
      require.resolve('./media/js/tests/karma-debug-handler.js'),
      require.resolve('./media/js/tests/index.js'),
    ],

    plugins: [
      'karma-qunit',
      'karma-junit-reporter',
      'karma-webpack',
      'karma-sourcemap-loader',
      'karma-chrome-launcher',
      'karma-phantomjs-launcher'
    ],

    preprocessors: {
      'media/js/tests/index.js': ['webpack'],
    },

    webpack: webpackConfig,

    reporters: ['progress'],

    client: {
      captureConsole: true,
      qunit: {
        filter: config.testModule
      },
    },

  });
};
```
### Steps to reproduce the behaviour

I'm not sure here.

It looks like a small fraction of the tests executed despite the error.

**Comment by wesleycho** [comment]
Karma will run all the tests it can, as each spec run is instantiated fresh.

Having a minimal reproduction would help greatly for debugging this - otherwise it would be very difficult, if not outright impossible, for anyone to help. FWIW, I do not have any issues with Webpack, karma, and PhantomJS with regards to not exiting with a proper exit code on test failure.

**Comment by EzraBrooks** [comment]
No feedback in a year; closing.
