### ISSUE TITLE
Karma appends guid on script

### ISSUE THREAD

**Issue by RALifeCoach** [karma-runner/karma#2324]
I am loading steal.js. Steal looks at the query string and assumes that if there is a single string, it is the name of a script file to load. That means it tries to load the file [guid].js.

Is there some way to turn off appending the guid?

Karma version 0.13.19

```
            'node_modules/steal/steal.js',
```

**Comment by vivganes** [comment]
@RALifeCoach what exactly do you mean by the guid? Can you share some logs to understand what is happening?

Not sure if it will be useful, but did you try this: https://www.npmjs.com/package/karma-steal-npm

May be this can help you in running karma with steal js.

**Comment by EzraBrooks** [comment]
No follow-up in over a year; closing.
