### ISSUE TITLE
Karma run on Windows7-x64 and GET NUMBER_MAX_VALUE error.

### ISSUE THREAD

**Issue by magixsource** [karma-runner/karma#2334]
Two days ago,i try to install karma and run it . but karma not work. after update node and npm and karma to LTS, karma still not work. so I report a ISSUE:
https://github.com/karma-runner/karma/issues/2329

but karma member ignore and close it by no answer.

So i learn node-debug try to find out the reason. I debug karma line by line in pass two days,finally i found WHY. Here is 
### Expected behaviour

As ISSUE#2329 say, I want karma work. but karma does't.
### Actual behaviour

 karma does't work and no error log and no message output.
### Environment Details
- Karma version 1.2.0 NODE、NPM AND GULP all @LTS
- Core-js version 2.4.1
- Test code, `gulpfile.js`

```
var gulp = require('gulp');
var KarmaServer = require('karma').Server;

gulp.task('test',function(){
    new KarmaServer({
       configFile: 'karma.conf.js',
       singleRun: true
    }, done).start();
});
```

`karma.conf.js` is not necessary, because program run to line 2 and exception raised.
### Steps to reproduce the behaviour
1. `gulp test`.
2. exception raised.

By node-debug , run `node-debug ./node_modules/gulp/bin/gulp.js test` get to CHROME BROWSER to debug program.
Below is js stack of This ISSUE:
karma/bin/karma 
->karma/lib/cli.js#5 
  -> karma/lib/server.js#20 
    -> karma/lib/file-list.js#10 
      -> core-js/index.js#1 
        -> core-js/shim.js#36 
         -> core-js/modules/es6.math.acosh.js#9

here is es6.math.acosh.js code

```
// 20.2.2.3 Math.acosh(x)
var $export = require('./_export')
  , log1p   = require('./_math-log1p')
  , sqrt    = Math.sqrt
  , $acosh  = Math.acosh;

$export($export.S + $export.F * !($acosh
  // V8 bug: https://code.google.com/p/v8/issues/detail?id=3509
   && Math.floor($acosh(Number.MAX_VALUE)) == 710
  // Tor Browser bug: Math.acosh(Infinity) -> NaN 
  && $acosh(Infinity) == Infinity
), 'Math', {
  acosh: function acosh(x){
    return (x = +x) < 1 ? NaN : x > 94906265.62425156
      ? Math.log(x) + Math.LN2
      : log1p(x - 1 + sqrt(x - 1) * sqrt(x + 1));
  }
});
```

Please see LINE 9, breakpoint at line 7 and i type `Number.MAX_VALUE` in Chrome console, debug program error and suddenly exit.

I try to comment line 9 and run `gulp`, gulp and karma work !

But i try another js file like this :
test.js

```
  console.log(Number.MAX_VALUE);
```

and run `node test.js`, output `1.7976931348623157e+308`,didn't get error.

Ok,manager, Any idea ?

**Comment by wesleycho** [comment]
This does not sound like a karma bug. This repository is for issues with karma itself - see https://github.com/karma-runner/karma/blob/master/CONTRIBUTING.md

Closing this as a support issue.
