### ISSUE TITLE
Error occurred when building node - bin/karma start karma.conf.js --no-auto-watch --single-run --no-color

### ISSUE THREAD

**Issue by SManorathna** [karma-runner/karma#2338]
Steps to reproduce the behaviour

**1. I have the node version of v0.12.0
2. Karma version is  0.13.19
3. npm version is 2.5.1**

when building the build fails saying 

**node node_modules/karma/bin/karma start karma.conf.js --no-auto-watch --single-run --no-color**

[ERROR] Return code: 1
[ERROR] Command output:
[ERROR] | ...(1513 lines of output hidden)...
[ERROR] | PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 107 of 122 (17 FAILED) (skipped 1) (0 secs / 1.221 secs)
[ERROR] | PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 108 of 122 (17 FAILED) (skipped 1) (0 secs / 1.268 secs)
[ERROR] | PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 109 of 122 (17 FAILED) (skipped 1) (0 secs / 1.278 secs)
[ERROR] | PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 110 of 122 (17 FAILED) (skipped 1) (0 secs / 1.286 secs)
[ERROR] | PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 111 of 122 (17 FAILED) (skipped 1) (0 secs / 1.294 secs)
[ERROR] | PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 112 of 122 (17 FAILED) (skipped 1) (0 secs / 1.302 secs)
[ERROR] | PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 113 of 122 (17 FAILED) (skipped 1) (0 secs / 1.309 secs)
[ERROR] | PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 114 of 122 (17 FAILED) (skipped 1) (0 secs / 1.318 secs)
[ERROR] | PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 115 of 122 (17 FAILED) (skipped 1) (0 secs / 1.325 secs)
[ERROR] | PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 115 of 122 (17 FAILED) (skipped 7) (0.932 secs / 1.325 secs)

Any suggestions why this is happening ?

**Comment by wesleycho** [comment]
What is the behavior that you are reporting here?

Is it the failure of the script from the test failures? If so, that is expected behavior by Karma. Otherwise, more details should probably be given, as there is not enough to adequately address what is being attempted to be asked, and guessing isn't a good approach :) .

**Comment by EzraBrooks** [comment]
No feedback in a year. Closing.
