### ISSUE TITLE
Can't exclude loading images 

### ISSUE THREAD

**Issue by optimatex** [karma-runner/karma#2344]
### Actual behaviour : I got this warrning:

`03 09 2016 19:38:22.290:WARN [web-server]: 404: /front-end2/assets/img/signup.png`
### Environment Details

my config: 

```
var webpack = require('webpack');

module.exports = function (config) {
   config.set({
      browsers: [ 'Chrome' ],
      singleRun: true,
      frameworks: [ 'mocha' ],
      files: [
         'tests.webpack.js',
         {pattern: './assets/img/signup.png', watched: false, included: false, served: true},
      ],
      proxies: {
         '/assets/img/signup.png': '/assets/img/signup.png'
      },
      preprocessors: {
         'tests.webpack.js': [ 'webpack', 'sourcemap' ]
      },
      reporters: ['mocha'],
      mochaReporter: {
         colors: {
            success: 'green',
            info: 'cyan',
            warning: 'blue',
            error: 'blue',
            false: 'blue'
         },
         symbols: {
            success: '__+__',
            info: '__#__',
            warning: '_!_',
            error: '__-__'
         },
         //output: 'minimal',
         showDiff: true
      },
      webpack: {
         devtool: 'inline-source-map',
         module: {
            loaders: [
               {
                  test: /\.js$/,
                  exclude: /node_modules/,
                  loader: 'babel-loader',
                  query: {
                     cacheDirectory: true,
                     plugins: ['transform-decorators-legacy' ],
                     presets: ['airbnb', 'es2015', 'stage-1', 'react']
                  }
               }
            ]
         },
         externals: {
            'cheerio': 'window',
            'react/addons': true,
            'react/lib/ExecutionEnvironment': true,
            'react/lib/ReactContext': true
         }
      },
      webpackServer: {
         noInfo: true //please don't spam the console when running in karma!
      }
   });
};

```
- Karma version (output of `karma --version`): 3.10.3
- Relevant part of your `karma.config.js` file  : this file is in root folder

**Comment by vivganes** [comment]
Does your test load any page that requires the image?  If your intention is to suppress the test from requesting for the image from karma server, this is not the way karma is designed to be used.  The included: false only makes sure that the image is not perceived as a test case.

**Another observation:** 

With my limited knowledge I can see that `/front-end2/` is extra in the 404 message.  

This would mean that while running tests, the browser is requesting the image file from the karma server but if it was the same image, the request should have gone to `/assets/img/signup.png`

Since the karma server could not find your image under the `front-end2/assets/img/signup.png`, it returned a 404.

**Comment by maksimr** [comment]
@optimatex you have incorrect proxy settings (see comment from @vivganes )

**Comment by megamindbrian** [comment]
Still doesn't work.

**Comment by dignifiedquire** [comment]
@megamindbrian please refrain from leaving these kind of non helpful comments. This is not welcome here.

**Comment by megamindbrian** [comment]
@dignifiedquire, how is someone supposed to know that the related error message that was closed 6 months ago is still an issue?

**Comment by snlacks** [comment]
This is a lot of configuration for something that is static and repeatedly needed. This would be much easier if we could just ignore images not loading.
