### ISSUE TITLE
Missing error handler on `socket`. TypeError: (msg || "").replace is not a function Error #1969

### ISSUE THREAD

**Issue by fkolar** [karma-runner/karma#2345]
It seems that I have the same issue with webpacket#2. version.

It happended to me when I treid to instantiate partical class which was btw. in one .ts file along with other classes. Even this class was exported. When I put this class out into separate file the problem was gone. 

Is there any particulare relation between having files in the same file and using them inside the tests?

Edit: I thought it is related as when I recreated  1 file it is gone but it happens also for others. this has probably nothing to do with it. 

Any idea why I can see such error ?

Thanks, 
Frank

**Comment by fkolar** [comment]
update:

Not really understanding but I can turn it on / off this issue by commenting 1 line of code. 


in the test I do instantiate this class:

new RuleX(....);

```
export class RuleX
{
    constructor (public _selectors: Array<Selector> , public _properties: Map<string, any> , public _rank: number = -1 , public _lineNumber: number = -1) {

    }

    apply (meta: Meta , properties: PropertyMap , declareKey: string): number
    {
        return Rule.merge(meta , this._properties , properties , declareKey);
    }
}
```


When I comment out this Rule.merge - which is some static method in some other file the error is gone. Whne I put it back I see this error. 

```
 static  merge (meta: Meta , src: Map<string, any> , dest: Map<string, any> , declareKey: string): number
    {
        var updatedMask: number = 0;


        return 0;
    }

````

I tried to removed all the code, body everything but not sure why calling static method woudl cause this problem.

**Comment by maksimr** [comment]
@fkolar could you debug and look at value of **msg** variable here `TypeError: (msg || "").replace`

Thanks

**Comment by fkolar** [comment]
I am closing this issue as this one is already resolved while ago. The main problem was it could not instantiate certain class , - and it was at the time I was using barrells and try to import Class as {XX, XX, XX, XX} from 'One common root',  and it did not work propertly - when I imported every single class it started to work.
