### ISSUE TITLE
Upgrade chokidar

### ISSUE THREAD

**Issue by ajsb85** [karma-runner/karma#2347]
### Expected behaviour
No warnings.

### Actual behaviour
This issue: https://github.com/paulmillr/chokidar/issues/529
https://github.com/karma-runner/karma/blob/master/package.json#L299

### Environment Details

- Karma version (output of `karma --version`): 1.2.0
- Relevant part of your `karma.config.js` file

### Steps to reproduce the behaviour

1. npm install karma

**Comment by paulmillr** [comment]
Works as expected. NPM warns about a module which is not supported on Windows.

**Comment by ajsb85** [comment]
npm package.json supports an os key, and also optionalDependencies.

**Comment by paulmillr** [comment]
@ajsb85 we are using optionalDependencies and the os field. How does adding another entry to the field help here?
