### ISSUE TITLE
Invalid command: `karma completion`

### ISSUE THREAD

**Issue by nopnop** [karma-runner/karma#2351]
### Expected behaviour

`karma completion` should return the bash completion script as described by `karma --help` and `karam completion --help
- OR -

`karma --help` should not list the `karma completion` command anymore
### Actual behaviour

``` sh
karma completion
{ Error: ENOENT: no such file or directory, open '(...absolute path to...)/karma/scripts/karma-completion.sh'
    at Error (native)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '(...absolute path to...)/karma/scripts/karma-completion.sh' }
```
### Environment Details
- Karma version (output of `karma --version`): 1.2.0
- Relevant part of your `karma.config.js` file: _not relevant_
### Steps to reproduce the behaviour
1. Install karma **with npm**  (not git clone)
2. Run  `karma --help` (see the listed karam completion command)
3. Run `karma completion`
### Reason

The [.npmignore](https://github.com/karma-runner/karma/blob/master/.npmignore#L7) file ignore `scripts`directory

**Comment by dignifiedquire** [comment]
Thank you for the report
