### ISSUE TITLE
Feature Request: Export all the constants

### ISSUE THREAD

**Issue by marthinus-engelbrecht** [karma-runner/karma#2361]
### Expected behaviour

All the constants would be exported. 
### Actual behaviour

Only the VERSION constant is exported in the [index.html](https://github.com/karma-runner/karma/blob/master/lib/index.js#L22)
### Environment Details
- Karma version 1.3.0
### Reasoning

We use gulp and we want to specify the log level via the Server constructor but it would be more reliable to use the constants defined inside karma than magic string like 'DEBUG'

**Comment by marthinus-engelbrecht** [comment]
This should be a trivial change. I'm more than willing to do a pull request

**Comment by dignifiedquire** [comment]
Sure :) PR welcome.
