### ISSUE TITLE
karma-cli doesn't pass clientArgs in single-run mode

### ISSUE THREAD

**Issue by myklemykle** [karma-runner/karma#2391]
### Expected behaviour

The clientArgs handling of karma's "run" command should also work for karma's "start" command in single-run mode, when karma first "starts" then "runs".  That way, users of karma-cli (including shell scripts) can run a single test via karma-mocha with a single command.  
### Actual behaviour

Karma doesn't pass client args to any clients/adapters in single-run mode.  This can cause various problems, depending on the client. 
My particular issue is with trying to tell karma-mocha which subset of a test suite to run.  The following command should work but doesn't, because config.clientArgs isn't set. Therefore the entire test suite runs instead of just the selected test:

```
karma start --single-run -- --grep="testname"  # grep ignored -- runs entire test suite
```

This works, but it's too complicated for shell scripts & tedious to type:

```
karma start &
karma run -- --grep="testname"
karma stop
```

... this is exactly the kind of thing that --single-run should simplify.
### Environment Details

Karma version: 1.3.0
    frameworks: ['mocha']

**Comment by pauldraper** [comment]
@vojtajina [requested](https://github.com/karma-runner/karma/pull/530#issuecomment-21987888) that the arguments that work for run do not work for start.

You have to do the work yourself if you want that to work; it doesn't happen automatically.

https://github.com/karma-runner/karma/issues/672

**Comment by maksimr** [comment]
@pauldraper Thanks

close as duplicate https://github.com/karma-runner/karma/issues/672
