### ISSUE TITLE
Browser doesn't close itself after a singleRun test.

### ISSUE THREAD

**Issue by guylabs** [karma-runner/karma#24]
If we configure testacular to launch Chrome automatically and set to singleRun to true, the browser doesn't closes itself. The same for Firefox. Is this intentionally? Could you add some kind of a flag for this behavior?

Because we want to execute testacular on a CI server and we need to have it closed after a build.

Thanks and regards,

Guy

**Comment by Mellbourn** [comment]
This problem is still present.
Running 
karma v0.12.28 
karma-chrome-launcer 0.1.4
windows 7 64bit
Chrome 37

**Comment by tparnell8** [comment]
:+1: also seeing this issue
Server 2012
Karma 0.12.31
karma-chrome-launcher 0.1.7
Latest version of chrome

**Comment by kakadiya91** [comment]
Also seeing this problem:

Linux 4.2.0-36-generic #42~14.04.1-Ubuntu SMP Fri May 13 17:27:22 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Karma 0.13.22
karma-chrome-launcher 0.1.12
Chromium 50.0.2661.102 Ubuntu 14.04

**Comment by AlexShemeshWix** [comment]
Same here
Karma 0.13.33
karma-chrome-laquncher 2.00
Chrome 54
Linux Ubuntu 14.04

**Comment by stefaneidelloth** [comment]
Is it possible to keep the browser open on purpose? An extra option for that behavior would be great. Also see https://stackoverflow.com/questions/45352256/how-to-keep-browser-window-open-for-single-karma-run-until-i-close-it-once

**Comment by joeflack4** [comment]
Same problem here. Karma `2.0.5`

Here are my dev dependencies in `package.json`:
```json
  "devDependencies": {
    "autoprefixer": "^7.1.3",
    "babel": "^6.23.0",
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "bootstrap": "^3.3.7",
    "bootstrap-colorpicker": "^2.5.2",
    "bootstrap-select": "^1.12.4",
    "chai": "^4.1.2",
    "chai-spies": "^1.0.0",
    "css-loader": "^0.28.5",
    "esdoc": "^1.1.0",
    "esdoc-importpath-plugin": "^1.0.2",
    "esdoc-standard-plugin": "^1.0.0",
    "eslint": "^5.0.1",
    "eslint-config-google": "^0.9.1",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^0.11.2",
    "font-awesome": "^4.7.0",
    "highcharts": "^5.0.14",
    "install": "^0.10.1",
    "karma": "^2.0.2",
    "karma-chai": "^0.1.0",
    "karma-fixture": "^0.2.6",
    "karma-html2js-preprocessor": "^1.1.0",
    "karma-json-fixtures-preprocessor": "0.0.6",
    "karma-mocha": "^1.3.0",
    "karma-phantomjs-launcher": "^1.0.4",
    "karma-sinon": "^1.0.5",
    "karma-webpack": "^3.0.0",
    "mocha": "^5.2.0",
    "node-sass": "^4.5.3",
    "npm": "^5.4.1",
    "postcss-loader": "^2.0.6",
    "precss": "^2.0.0",
    "resolve-url-loader": "^2.1.0",
    "sass-loader": "^6.0.6",
    "sinon": "^5.1.0",
    "style-loader": "^0.18.2",
    "tether": "^1.4.0",
    "uglify-js": "github:mishoo/UglifyJS2",
    "uglifyjs-webpack-plugin": "^0.4.6",
    "url-loader": "^0.5.9",
    "webpack": "^3.5.5"
  },
```
