### ISSUE TITLE
Running test fails with ERROR, no detail given

### ISSUE THREAD

**Issue by JPMoresmau** [karma-runner/karma#2408]
### Expected behaviour

I have a new Angular2 project created with angular-cli. I haven't modified the karma files. Running ng test should run my test suite, or actually give me a meaningful error message if there was a problem.
### Actual behaviour

I get `Chrome 54.0.2840 (Linux 0.0.0) ERROR in the console`, no more detail
the browser has opened. Clicking on DEBUG gives me a blank page. The console says: 

```
zone.js:355 Unhandled Promise rejection: Cannot read property 'error' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'error' of undefined(…) TypeError: Cannot read property 'error' of undefined
    at directCallParentKarmaMethod (http://localhost:9876/context.js:233:28)
    at ContextKarma.error (http://localhost:9876/context.js:139:5)
    at ZoneDelegate.invoke (http://localhost:9876/base/src/test.ts:21755:28)
    at Zone.run (http://localhost:9876/base/src/test.ts:21648:43)
    at http://localhost:9876/base/src/test.ts:22014:57
    at ZoneDelegate.invokeTask (http://localhost:9876/base/src/test.ts:21788:37)
    at Zone.runTask (http://localhost:9876/base/src/test.ts:21688:47)
    at drainMicroTaskQueue (http://localhost:9876/base/src/test.ts:21920:35)
```

So there was an error apparently but no details are given, it's impossible to debug what's wrong.

running with --log-level DEBUG
...

```
16 10 2016 15:26:04.494:DEBUG [web-server]: serving (cached): /home/jpmoresmau/Documents/angular2/todo/src/test.ts
16 10 2016 15:26:04.666:DEBUG [middleware:source-files]: Requesting /_karma_webpack_/0.bundle.js /
16 10 2016 15:26:04.666:DEBUG [middleware:source-files]: Fetching /_karma_webpack_/0.bundle.js
Chrome 54.0.2840 (Linux 0.0.0) ERROR
```
### Environment Details
- Karma version (output of `karma --version`):
  Karma version: 1.3.0
- Relevant part of your `karma.config.js` file
  Haven't touched the file, was generated by angular-cli
### Steps to reproduce the behaviour

Well I create a project via angular-cli, modified the code, then at some stage thought "I'll look at adding some tests".

**Comment by vivganes** [comment]
I can see the following snippet in the debug error log

```
zone.js:355
```

Can you quickly check if your project has such a file and see if the line 355 leads you to any error?

**Comment by JPMoresmau** [comment]
I'm now using Chrome 55, which also gave me an error with no message, but I manage to fix it (https://github.com/angular/angular-cli/issues/2125). so this can be closed. It would be good to get more information on an error, though.
