### ISSUE TITLE
Karma doesn't load node_module/*/package.json to PhantomJS (404 Error)

### ISSUE THREAD

**Issue by dawud-do** [karma-runner/karma#2422]
I'm using Karma 0.13.22
Node v6.7.0
npm 3.10.3 
and PhantomJS 2.1.1

Using the angular 2 seed as a basis and when I run npm test I receive the following error:

`25 10 2016 20:08:29.857:INFO [PhantomJS 2.1.1 (Windows 7 0.0.0)]: Connected on socket 3G6Eu905pwciAA
3BAAAA with id 70262326
25 10 2016 20:08:30.128:WARN [web-server]: 404: /node_modules/@angular/core/package.json
25 10 2016 20:08:30.131:WARN [web-server]: 404: /node_modules/@angular/platform-browser-dynamic/pack
age.json
PhantomJS 2.1.1 (Windows 7 0.0.0) ERROR: '(SystemJS) XHR error (404 Not Found) loading http://localh
ost:9876/node_modules/@angular/core/package.json
        Error loading http://localhost:9876/node_modules/@angular/core/package.json'
`

I've tried including all json files in a pattern in my karma.conf.js, didn't work. 
I have the correct baseURL and basePath as far as I can tell. 

Any idea where I might look to resolve this issue?

**Comment by maksimr** [comment]
@dawud-do look at *proxy* settings - http://karma-runner.github.io/1.0/config/configuration-file.html

Karma manage files under '/base' so you could try something like this
```js
proxies: {
  '/node_modules/': '/base/node_modules/'
},
```

Thanks!
