### ISSUE TITLE
'Require/System is not defined'

### ISSUE THREAD

**Issue by Davy-F** [karma-runner/karma#2423]
I'm running Karma with Jasmine/Gulp. This is on the latest version of AngularJS, using ES6.

If the module in tsconfig/jsconfig is 'system', then I get the following error when running my test via gulp:

> 'System is not defined'

If the module is 'commonjs', I get this error:

> 'Require is not defined'

![image](https://cloud.githubusercontent.com/assets/19592376/19771617/67ccef74-9c5b-11e6-8bd0-24634adc319f.png)

My program compiles and works fine though, it is only breaking when running a test. Is it worth moving to Webpack rather than SystemJS? Any help would be appreciated.

**Comment by maksimr** [comment]
@Davy-F did you setup preprocessors in karma.config.js which complie your ES6 code to ES6?

**Comment by EzraBrooks** [comment]
No follow-up in over a year; closing.
