### ISSUE TITLE
Can't use http2 with Karma

### ISSUE THREAD

**Issue by itslenny** [karma-runner/karma#2424]
### Expected behaviour

Uses http 2
### Actual behaviour

Uses http 1.1

Is there any way to use http2 in with Karma server?

I'm running tests from gulp using:

```
  new karma.Server({ ... });
```

and my site is heavily utilizing http2's concurrent connections (no bundling). It's working great in production and we're living the dream, but the tests are running horribly slow because the karma server doesn't have http2. Is there anyway to either turn on http2... or provide node's http2 server or possibly even just tell karma to use another http server that does support http2?

**Comment by dignifiedquire** [comment]
To make this possible we would have to upgrade the current http server to be http2 compatible. Do you know of any good nodejs http2 severs that also work well for http1?

**Comment by Florian-R** [comment]
@dignifiedquire It should be possible to add support for this with [node-spdy](https://github.com/indutny/node-spdy), but this seems an heavy solution.

Does a config to provide a custom server instance could be an alternative?

**Comment by dignifiedquire** [comment]
@Florian-R I think it would be nice if users could just enable http2 via a config without thinking about it. Maybe making `node-spdy` not a dependency but just log an error if http2 is enabled and it is not installed prompting the user to install it. That way there is no impact for users not needing it, and if people want to use it, it's just a config + an install away.

**Comment by itslenny** [comment]
Another option is [node-http2](https://github.com/molnarg/node-http2) which is supposed to (mostly) mirror the standard http module so it might be a really easy integration. I don't know much about node-http2 vs node-spdy, but they both look like viable options.

**Comment by jfstephe** [comment]
@itslenny - did you actually get http2 working? I've overridden the http module but even after sacrificing a goat ( 🐐 🔪 ) it doesn't work. I'm having proxy header issues.
