### ISSUE TITLE
Karma reported test duration is negative

### ISSUE THREAD

**Issue by reustonium** [karma-runner/karma#2425]
### Expected behaviour

Running karma tests takes ~12 seconds, expect test duration (runtime) to be ~12 seconds.
### Actual behaviour

PhantomJS 2.1.1 (Windows 7 0.0.0): Executed 316 of 316 SUCCESS (1.959 secs / **-41118 mins 50.274 secs**)
TOTAL: 316 SUCCESS
### Environment Details

[Angular Yeoman](https://github.com/yeoman/generator-angular) Project.
Windows 7
- Karma version (output of `karma --version`): 1.3.0
- Relevant part of your `karma.config.js` file
### Steps to reproduce the behaviour
1. `grunt test`
2. observe large negative test duration.
   3.

**Comment by reustonium** [comment]
I think I found the issue, one of the tests is using `jasmine.clock().mocktime(time)` and that seems to be screwing up how Karma reports the duration for the test.  Since the mocked time is far enough in the past I'm guessing that the signed integer is getting flipped and going way negative.

**Comment by vivganes** [comment]
@reustonium Does this issue need any more work from karma?  If the issue has been addressed, I would like to request you to go ahead and close this issue.

**Comment by reustonium** [comment]
Perhaps just a question first.  Is it expected behavior to have the Karma test duration property affected by setting [`jasmine.clock().mockDate()`](http://jasmine.github.io/2.2/introduction.html#section-Mocking_the_Date)

This error was caused when a test used a mock date resulting in a signed integer overflow of the test duration property of the karma test.

Is that expected behavior?  Thanks!

**Comment by lordmat0** [comment]
Having exactly the same issue.

I don't think it's expected behavior, mocking out the date in the past shouldn't be affecting the Karma runner.

**Comment by lordmat0** [comment]
Looked into the issue and found that this Class calls ` Date.now` which can potential be mocked out.

https://github.com/karma-runner/karma/blob/39d378d20dee61a88572225db9e1855da3adb346/lib/browser_result.js#L21

The simplest solution is to add an afterEach to take out your mockedDate, that way Karma can continue to use `Date.now`.

For example:
```
    afterEach(() => {
        jasmine.clock().uninstall();
    });
```

**Comment by maksimr** [comment]
@reustonium @lordmat0 thanks!

But It's problem of karma-jasmine not karma:
https://github.com/karma-runner/karma-jasmine/blob/master/src/adapter.js#L226
https://github.com/karma-runner/karma-jasmine/blob/master/src/adapter.js#L211

Could you create issue in karma-jasmine project?
