### ISSUE TITLE
Deprecation warnining in Node 7

### ISSUE THREAD

**Issue by isiahmeadows** [karma-runner/karma#2429]
### Expected behavior
Things to work! (i.e. no deprecation warnings crashing Karma)

### Actual behavior

[This deprecation warning:](https://ci.appveyor.com/project/isiahmeadows/thallium/build/93/job/9trd5oiry82wed4u#L615)

```
node.exe : (node:2636) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
```

### Environment Details

- Karma version (output of `karma --version`): 1.3.0
- Relevant part of your `karma.config.js` file: N/A (I think - [here's my config](https://github.com/isiahmeadows/thallium/blob/master/karma.conf.js))
- OS: Windows only

### Steps to reproduce the behavior

1. Run Karma in Node 7
2. Watch the output

-----

This came up in CI, and has been failing my Windows builds (oddly, it's not affecting my Linux builds). Downgrading Node did fix the problem, though.

**Comment by dignifiedquire** [comment]
It's interesting that it is failing your build, it really should be only a warning :/

**Comment by isiahmeadows** [comment]
So is it a Node bug? I didn't think that should've changed the exit code.

**Comment by dotnetCarpenter** [comment]
@isiahmeadows Do you get code coverage on your Windows builds? I recently had a problem with [IstanbulJS's nyc](https://github.com/istanbuljs/nyc#readme) only on Windows. It didn't give an error message but my builds kept failing. In the end I [disabled code coverage for Windows](https://github.com/dotnetCarpenter/pipetree/blob/master/package.json#L8).

**Comment by isiahmeadows** [comment]
Nope. I don't use coverage at all (even though I probably should given the
project size).

**Comment by maksimr** [comment]
@isiahmeadows Why do you think that problem in deprecation waring?

**Comment by dotnetCarpenter** [comment]
Anyway the buffer code in Karma needs to be changed before node version 8 or we might not be able to use Karma. This seems to be the only issue-report tracking that.

**Comment by maksimr** [comment]
@dotnetCarpenter that is true, deprecated code should be rewritten, but it look like a symptom (not a root problem)

**Comment by isiahmeadows** [comment]
@maksimr I honestly have no idea. I just happened to notice a problem and reported it.

**Comment by tmair** [comment]
Just as a reference the deprecation warning was introduced with https://github.com/nodejs/node/pull/8169/commits/996389c0b9bf87e3b393d06e18e722635035d579 and reverted with https://github.com/nodejs/node/commit/4fffe32a4b3a93548c4d39b1c2531aa38403b5e6. So in the next 7.x node version it should not cause any troubles anymore, but it might be a breaking change in nodejs 8

**Comment by maksimr** [comment]
@isiahmeadows @dignifiedquire it's interesting karam use `new Buffer` only.
So problem not in karma itself, looks like one of dependencies use deprecated format for `Buffer`.

**Comment by maksimr** [comment]
@isiahmeadows could you reproduce this problem on stub project?

**Comment by dotnetCarpenter** [comment]
new Buffer might also be deprecated so hold your breath. Very unfortunate I
can't currently find the source of this claim. I saw it somewhere in a
discussion of a PR in node. https://github.com/nodejs/node/pull/

**Comment by wesleycho** [comment]
I see `new Buffer` used https://github.com/karma-runner/karma/blob/8b1b4b1052925e15770a0d4017a6ebc9ea89c0ed/lib/middleware/common.js#L43-L46 - in particular, Node seems to have deprecated all of the `new Buffer` usages as well, see https://nodejs.org/api/buffer.html#buffer_class_buffer . Would it be reasonable to change these two usages to `Buffer.from` and `Buffer.alloc`?

**Comment by maksimr** [comment]
@wesleycho 

> Would it be reasonable to change these two usages to Buffer.from and Buffer.alloc?
Yes, but it's not related to warning from current issue.

Thanks

**Comment by isiahmeadows** [comment]
Welp...it's [likely *not* an issue](https://ci.appveyor.com/project/isiahmeadows/thallium/build/karma-windows%20143) with Karma itself, but one of its dependencies. I'm investigating which.

**Comment by isiahmeadows** [comment]
Here's the involved files:

- `karma.conf.js`:

```js
module.exports = function(config) {
  config.set({
    frameworks: ['mocha'],
    files: ['test.js'],
    browsers: ['Chrome'],
    singleRun: true,
  })
}
```

- `package.json`:

```json
{
  "scripts": {"test": "karma start"},
  "devDependencies": {
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-mocha": "^1.3.0",
    "mocha": "^3.2.0"
  }
}
```

- `test.js`:

```js
describe("foo", function () {
    it("works", function () {})
})
```
