### ISSUE TITLE
Link to v1.0 from v0.8 github config/coverage.html broken

### ISSUE THREAD

**Issue by vgvenkat** [karma-runner/karma#2439]
### Expected behaviour
Clicking on message link at the top that warns users "Heads Up! You're viewing the docs for v0.8, an old version of Karma. `v1.0 is the newest.`" should redirect to v1.0 page
### Actual behaviour
Page redirects to https://karma-runner.github.io/1.0/config/coverage.html with 404
### Environment Details
MBP Yosemite Chrome latest
- Karma version (output of `karma --version`): Not applicable
- Relevant part of your `karma.config.js` file : Not applicable

### Steps to reproduce the behaviour

1. Go to https://karma-runner.github.io/0.8/config/coverage.html
2. Click on v1.0 link
3. Page will redirect with 404.

**Comment by vivganes** [comment]
@vgvenkat I just raised a pull request https://github.com/karma-runner/karma-runner.github.com/pull/38

Meanwhile please check if http://karma-runner.github.io/1.0/config/preprocessors.html has the coverage related content that you were looking for.
