### ISSUE TITLE
BindAddress option

### ISSUE THREAD

**Issue by grifball** [karma-runner/karma#2477]
I'm sorry if this option already exists and I just didn't notice it.
I'm using karma on a private project on a server with port 9876 open.
Rather than going through and closing that port in the firewall, it's easier just to bind to 127.0.0.1 instead of 0.0.0.0.
So I added support into karma for that, it's a simple change, I included a diff of the files.
I'm using karma version 1.3.0
[diff new old.txt](https://github.com/karma-runner/karma/files/623373/diff.new.old.txt)

Let me know what you guys think of having this option.

**Comment by maksimr** [comment]
@grifball Karma don't have this option now
We had a [pull request(PR)](https://github.com/karma-runner/karma/pull/1214) about it with long discussion.
It will be nice if you look at this PR and reanimate it

Thanks!

relates https://github.com/karma-runner/karma/issues/1593

**Comment by grifball** [comment]
I looked at #1311 and #1214 and they both seem fine to solve this issue, so I added them in and fixed the unit tests so that the dummy web server accepts the correct arguments. I'll make a PR.
