### ISSUE TITLE
Drop support for Node 0.10 and 0.12

### ISSUE THREAD

**Issue by dignifiedquire** [karma-runner/karma#2490]
I mentioned this before, the original plan was to support the latest three releases of Node.js and to follow along with the LTS schedule: https://github.com/nodejs/LTS 

At the end of the year both 0.10 and 0.12 will have reached end of maintenance, so Karma can drop them safely.

This should happen in a new major release, aka 2.0.

Things to be done for this

- Update docs
- Update engines matcher in package.json
- Update travis and appveyor configuration to move to `4`, `6`, `7` being tested.

**Comment by nickmccurdy** [comment]
Note that 0.10's maintenance has already ended (0.12 ends December 31st).

**Comment by wesleycho** [comment]
How soon should these changes be made? Is the intention to do a release of 2.0 soon after 0.12 support ends? Will there be an interim release beforehand?

**Comment by dignifiedquire** [comment]
There is no urgent rush to do this, so I would wait until January for a new 2.0 release. We can still do  regular minor and patch releases in the meantime as we need them.

**Comment by dignifiedquire** [comment]
We are ready for this :)

**Comment by nickmccurdy** [comment]
The latest versions of eslint, lodash, and log4js now require Node >=4. I think it would be a good idea to update soon if possible.

**Comment by wesleycho** [comment]
When should this be scheduled for?

Should this declared Node 4+ support change also include an internal change utilizing a Node 4+ feature such as a fat arrow or template literal in order to force code to break if the user is not on Node 4+?

**Comment by johnjbarton** [comment]
Fixed by PR #2825
