### ISSUE TITLE
Test failures do not display accurate test line numbers in stack trace

### ISSUE THREAD

**Issue by wesleycho** [karma-runner/karma#2500]
### Expected behaviour
The line number in a test file referenced when a test fails is correct

### Actual behaviour
The line number reported is incorrect, a virtual line number generated from Babel

### Steps to reproduce the behaviour

1.  Go to https://github.com/karma-runner/karma/blob/e36ba6c1d4cad4fc321f3376129b329fe663068d/test/unit/browser.spec.js#L30
2. Change `.to.equal(fullName)` to `.to.equal(fullName) + '1'`
3. Observe the line number reported

This likely is a simple configuration problem with Babel or one of the grunt plugins

**Comment by grifball** [comment]
I tried to replicate this but couldn't. Your change didn't throw an error so I changed it to this:
`.to.equal(fullName + '1')`
And then it gave me the correct line number (30):
`at Context.<anonymous> (test/unit/browser.spec.js:30:33)`
I'm on the latest commit in the master branch, running `npm test`

**Comment by chriscasola** [comment]
I was able to replicate this on os x with node v6.9.2 - it also incorrectly tells me the test failed on line 32 but the actual failure line is 30.
