### ISSUE TITLE
 RangeError: Invalid Date in 

### ISSUE THREAD

**Issue by veekri** [karma-runner/karma#2504]
i am getting  RangeError: Invalid Date in   eroor 

if i run through jamine spec its working fine 
### Environment Details

- Karma version (output of `karma --version`):
- Relevant part of your `karma.config.js` file

### Steps to reproduce the behaviour

1.
2.
3.

**Comment by wesleycho** [comment]
This sounds like a bug in your test/codebase, and not in karma - do you have a reproduction that we can look at (karma.conf.js, test where error is being thrown, etc.)?
