### ISSUE TITLE
Karma not working with Node v7.3.0

### ISSUE THREAD

**Issue by andrepcg** [karma-runner/karma#2511]
Trying to run karma with node 7.3.0 and I'm getting the following error:

```START:
21 12 2016 14:34:03.540:INFO [karma]: Karma v1.3.0 server started at http://localhost:9876/
21 12 2016 14:34:03.543:INFO [launcher]: Launching browser jsdom with unlimited concurrency
21 12 2016 14:34:03.550:INFO [launcher]: Starting browser jsdom
21 12 2016 14:34:04.336:INFO [Node.js (linux; U; rv:v7.3.0) AppleWebKit/537.36 (KHTML, like Gecko)]: Connected on socket /#tduonCE02UcVqoG8AAAA with id 35304974
21 12 2016 14:34:14.343:WARN [Node.js (linux; U; rv:v7.3.0) AppleWebKit/537.36 (KHTML, like Gecko)]: Disconnected (1 times), because no message in 10000 ms.
Node.js (linux; U; rv:v7.3.0) AppleWebKit/537.36 (KHTML, like Gecko) ERROR
  Disconnected, because no message in 10000 ms.
```

Tried again with Node version 7.2.1 and it works

### Environment Details

- Karma version: 1.3.0
- Node version 7.3.0

**Comment by dignifiedquire** [comment]
Could you try with a different browser? This might be an issue with the browser `jsdom` you are using rather than karma itself

**Comment by madnight** [comment]
if i try to execute karma with 7.3.0 the tests fails "Some of your tests did a full page reload!" without further details

**Comment by maksimr** [comment]
I have checked karma@1.3.0 on node@7.3.0 with Chrome on MacOs all work fine.
Look like problem in `jsdom`

**Comment by maksimr** [comment]
Close because issue has moved to jdom

Thanks!
