### ISSUE TITLE
Question : how to make report while running karma manual mode (without singleRun)

### ISSUE THREAD

**Issue by avocadee** [karma-runner/karma#2512]
Hi, thanks in advance.
My question is , when does karma create report files on browser capture mode?

I am trying to make my environment like below.
- when i am running this env with singleRun=true & browser = chrome, karma makes reports as well.
- but it's not making reports in singleRun=false & no browser.

### Expected behaviour
1. command "start karma" with conf (singleRun:false + no browser(to capture manually))
2. call url and run specs in my browser [ok]
3. run a command "karma stop" [ok]
4. create report files and close

### Actual behaviour
4. karma is stopped without any report.
from 1 to 4, reports are not generated.

### Environment Details

- Karma version (output of `karma --version`): 1.3.0
- Relevant part of your `karma.config.js` file
...
        reporters: ['progress', 'coverage', 'karma-remap-istanbul'],
        remapIstanbulReporter: {
            reports: {
                cobertura: 'karmaRemapIstanbul/cobertura_'+cov_report_postfix+'.xml',
                html: 'karmaRemapIstanbul/coverage_'+cov_report_postfix,
            }
        },
        // browsers: ['Chrome'], // no browser setting

        // Continuous Integration mode
        singleRun: false,

**Comment by maksimr** [comment]
@Heeseong 

> My question is , when does karma create report files on browser capture mode?
First of all, what does mean `report files`?

Karma create reporters when start server. I have checked karma@1.3.0 on node@5.12.0 with progress reporter. All work as expected[1]

[1] I run karma without any browser with --no-single-run then manually open browser and go to http://localhost:9876 after that karma run test and report result in console.

Thanks!

**Comment by devoto13** [comment]
Closing per above.
