### ISSUE TITLE
Karma exits immediately and doesn't throw error when a webpack loader is not found

### ISSUE THREAD

**Issue by nickaversano** [karma-runner/karma#2513]
### Expected behaviour
To throw an error.

### Actual behaviour
Karma exits immediately with no output.

### Environment Details

- Karma version: 1.3.0
- Relevant part of your `karma.config.js` file
```
const path = require('path')
const nodeModulesPath = './node_modules'

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine'],
    files: [
      './app/**/*_test.js',
    ],
    preprocessors: {
      './app/**/*_test.js': ['webpack'],
    },

    webpack: {
      bail: true,
      module: {
        loaders: [
          {
            test: /\.js$/,
            exclude: [nodeModulesPath],
            loader:  'babel-loader',
          }
        ]
      },
      resolve: {
        root: [nodeModulesPath]
      }
    },
    plugins: [
      require('karma-webpack'),
      require('karma-jasmine')
    ],
    logLevel: config.LOG_INFO,
    singleRun: true,
  })
}
```

### Steps to reproduce the behaviour

1. From the parent directory to this `karma.conf.js`, run `./my-directory/node_modules/.bin/karma start my-directory/karma.conf.js --browsers Chrome`
2. Notice that karma exits immediately and does not print anything

If you define the babel-loader with respect to the nodeModulesPath, everything should work as expected: `loader:  nodeModulesPath + '/babel-loader',` However it's very strange that karma doesn't output anything

**Comment by maksimr** [comment]
@nickaversano could you provide stub project which reproduce this problem

Thanks!

**Comment by EzraBrooks** [comment]
Closing issue; please reopen if a stub project is provided.

**Comment by falsefalse** [comment]
We have stumbled on the same problem, here is the minimal project that reproduces the problem

https://github.com/ertrzyiks/karma-webpack-failed-compilation-example
