### ISSUE TITLE
DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

### ISSUE THREAD

**Issue by FezVrasta** [karma-runner/karma#2521]
### Expected behaviour
No deprecation warnings show up.

### Actual behaviour
```
DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
```
Is printed on any karma run.

### Environment Details

- Karma version: 1.3.0

### Steps to reproduce the behaviour

1. Run `karma start` (no config needed)

**Comment by FezVrasta** [comment]
https://github.com/karma-runner/karma-chrome-launcher/issues/79

**Comment by maksimr** [comment]
@FezVrasta thanks

Problem [here](https://github.com/karma-runner/karma/blob/39d378d20dee61a88572225db9e1855da3adb346/lib/temp_dir.js#L7)

**Comment by FezVrasta** [comment]
but in the line you pointed, the new api is used, it should not throw any warning...

**Comment by maksimr** [comment]
@FezVrasta you are right!

Looks like a problem in third party library, because I could not find tmpDir neither in karma nor karma-chrome-launcher 

Thanks

**Comment by maksimr** [comment]
I have checked on macOs


node@7.3.0
karma@1.3.0
karma-chrome-launcher@2.0.0
karma-jasmine@1.1.0

All work whithout warnings

![kapture 2017-01-02 at 2 13 57](https://cloud.githubusercontent.com/assets/616193/21583425/298c6766-d091-11e6-9204-b47ea374776a.gif)

**Comment by FezVrasta** [comment]
Found the problem, it's `wd`.

https://github.com/admc/wd/pull/456

**Comment by MPankajArun** [comment]
"It's not really an error, it's a deprecation warning. You can fix it like, you could just put something like the following at the top of your file: var os = require('os'); os.tmpDir = os.tmpdir;"
