### ISSUE TITLE
API 'window.__karma__.info()` does not work

### ISSUE THREAD

**Issue by devanshah1** [karma-runner/karma#2534]
### Expected behavior

Expect the info emitter to be dispatched which is set in the reporter. The reporter is expected to write to console a message. Refer to: https://groups.google.com/forum/#!topic/karma-users/ShR96TcKm6Q

### Actual behavior

Nothing is written to the terminal/console.
### Enviroment Details
- Karma version (output of `karma --version`): Tried on "0.13.22" and "1.0.0"
- Relevant part of your `karma.config.js` file
  Refer to: https://github.com/devanshah1/sample/blob/master/karma.conf.js
### Steps to reproduce the behaviour
1. Clone Repo: https://github.com/devanshah1/sample
2. Run `bash npm install` in repo folder
3. Run `bash npm install src` in repo folder
4. Run `npm test` in repo folder
5. Now in the console you should see "info emitter was called and following is the object" printed if the info event was triggered

### Additional Details

I used the localStorage.debug = '*'; option in the browser to enable the logs in karma to see if the info emit was going through, I did see that the emit was dispatch. Do you happen to know where I can look to verify if the reporter has received it or to verify if the emmiter is registered from the reporter.

**Comment by devanshah** [comment]
Any update on this one?

**Comment by devanshah1** [comment]
Any update on this issues?

**Comment by devanshah1** [comment]
Closing this one as it is the same as #2192
