### ISSUE TITLE
Is it possible connect application with karma runner  ?

### ISSUE THREAD

**Issue by linuxenko** [karma-runner/karma#2535]
Hey, karmers :bee: , is it possible connect something different with karma runner ? I'm trying connect native application of the very strange device :iphone:, it does not change its `origin`, opening links and `iframes` opens web browser. Is it possible connect to `runner` from the native application, not a web browser ? 
Thanks.

**Comment by maksimr** [comment]
@linuxenko if short 'No', you should have something that implements real browser API (HTTP, HTML, DOM, javascript interpreter etc.)

Could you describe 'Use case'

Thanks

**Comment by linuxenko** [comment]
@maksimr, it is a javascript application with its own `console.*` and `window`, `dom`, `xmlhttprequest`, but i cannot run `context` of the karma inside of a frame or launch a new window for every `context` run.

Right now i can connect to `karma runner` server, it does log my connection activity, i even can recognize events `runner` sent to my application that saying to start a new `context.html` for tests.. (it is a bit difficult debug such apps, i'm debugging mostly inside of a regular web browser). I have a problem with parsing `context.html` and understanding karma's `client <-> server` protocol. I can watch for new tests comming and run them from inside of my app and make all cleanups manually, but i do not know how to get tests/frameworks and how to response to the server if they are `ok or err`. 

anyways - maybe it is possible run context without `iframes, new windows` simple inside of the current window ?

**Comment by maksimr** [comment]
@linuxenko 

> maybe it is possible run context without iframes ...

Yes, look at option [client.useIframe](http://karma-runner.github.io/1.0/config/configuration-file.html).

>  i do not know how to get tests/frameworks and how to response to the server if they are ok or err

Karma use socket between client and server. [Some code](https://github.com/karma-runner/karma/blob/master/client/karma.js) injected to html (context.html) to setup  connection with server, and send data about tests to the server.
Framework use this client API to send data on the server, [for example you could look at karma-jasmine framework](https://github.com/karma-runner/karma-jasmine/blob/master/src/adapter.js#L194-L197)

**Comment by maksimr** [comment]
>i do not know how to get tests/frameworks ...

Tests and frameworks loaded as javascript files - look at [this](https://github.com/karma-runner/karma/blob/master/static/context.html#L25) and [this](https://github.com/karma-runner/karma/blob/master/lib/middleware/karma.js#L211-L215)

**Comment by maksimr** [comment]
@linuxenko If you want understand how karma works, I'm strongly recommend read [this](http://karma-runner.github.io/1.0/intro/how-it-works.html) and [this](https://github.com/karma-runner/karma/raw/master/thesis.pdf)

Thanks

**Comment by linuxenko** [comment]
Thank you @maksimr , it seems like i can create `json` static files with all configuration i need by modifiying `context's` middleware. cool 😎
