### ISSUE TITLE
[config] custom middleware-plugin does not work

### ISSUE THREAD

**Issue by linuxenko** [karma-runner/karma#2539]
### Expected behaviour

Regular middleware behaviour

### Actual behaviour

Nothing, it does not work

### Environment Details

- Karma version (output of `karma --version`):

Karma version: 1.3.0
- Relevant part of your `karma.config.js` file

```
var CustomMiddlewareFactory = function (config) {
  return function (request, response, /* next */) {
    response.writeHead(200)
    return response.end("content!")
  }
}

middleware: ['custom']
plugins: [
  {'middleware:custom': ['factory', CustomMiddlewareFactory]}
  ...
]
```
### Steps to reproduce the behaviour

1. Copy example from  [documentation](http://karma-runner.github.io/1.0/config/configuration-file.html) (middleware part).
2. Request static files (for an instance /context.html) and nothing happens, it does not handle this middleware at all.

**Comment by linuxenko** [comment]
idk why `middleware` option does not work, but `beforeMiddleware` fork just fine for me )

**Comment by maksimr** [comment]
@linuxenko could you provide stub project which reproduce problem with middleware

Thanks

**Comment by linuxenko** [comment]
```
    beforeMiddleware: ['custom'],
    plugins: [
      'karma-browserify',
      'karma-chai',
      'karma-mocha',
      'karma-mocha-reporter',
      {'middleware:custom': ['factory', CustomMiddlewareFactory]}
    ]
```
`beforeMiddleware` works, `middleware` does not )

@maksimr

**Comment by maksimr** [comment]
@linuxenko `middleware` should work. Note `middleware` set [**after** karma middleware](https://github.com/karma-runner/karma/blob/master/lib/web-server.js#L78-L82)! 

Maybe in your case request simple **does not reach** your middleware.
