### ISSUE TITLE
Awkward to install from repo via `npm install karma-runner/karma`

### ISSUE THREAD

**Issue by isiahmeadows** [karma-runner/karma#2553]
It'd be much more helpful to do that if I didn't have to turn around and also `pushd node_modules/karma && npm i grunt && grunt build && popd`.

**Comment by isiahmeadows** [comment]
I'm looking in terms of CI, to clarify.

**Comment by dignifiedquire** [comment]
The git repo is not really meant to be installable due to the code generation. Is there a specific reason why you need to install from git instead of npm?

**Comment by isiahmeadows** [comment]
An important patch is available there that hasn't made it to npm.

**Comment by dignifiedquire** [comment]
I did a release yesterday, so you can use `1.4.1`

**Comment by isiahmeadows** [comment]
Well, then. That fixes my problem. 😄
