### ISSUE TITLE
karma 1.4.0 broke IE8 support

### ISSUE THREAD

**Issue by gkatsev** [karma-runner/karma#2556]
### Expected behaviour
Running karma in IE8 is possible.

### Actual behaviour
IE8 does not work anymore.

### Environment Details

- Karma version (output of `karma --version`):
- Relevant part of your `karma.config.js` file

Karma version: 1.4.1
My karma config is available [here](https://github.com/videojs/video.js/blob/master/test/karma.conf.js)

### Steps to reproduce the behaviour

1. Start karma with something like
```sh
karma start test/karma.conf.js --no-single-run
```
2. navigate to `0.0.0.0:9876` once it loads
3. notice that there are errors in the console.
![errors in ie8](https://cldup.com/DscjamRE5N.png)

I noticed this first when greenkeeper updated the dependency to karma 1.4.0. After several travis build retries, it still wouldn't connect to IE8 (see [build](https://travis-ci.org/videojs/video.js/builds/196417985#L1193-L1199)).
It looks like it's related to the socket.io update and probably broke inadvertently.
Dropping back down to version 1.3.0 of karma, everything works great still.

Potential solutions, they're not mutually exclusive:
* add the `es3` preset to make sure that words like `default` are quoted properly.
* investigate why the socket.io update causes an error
* drop support for IE8 in a major update

I'd be happy to try and help making the first two options happen. In the meantime, I'm staying with the 1.3.0 version of karma.

**Comment by gkatsev** [comment]
Here's greenkeeper's issue against the videojs project which alerted me to this: https://github.com/videojs/video.js/issues/3946

**Comment by dignifiedquire** [comment]
Thank you for the report. If you could help us figure out what exactly the issues are, that would be great. As far as I understood socket.io broke IE8 but fixed it later at which point I upgraded the dependency. But it sounds like sth ist still not right. 
Agreed on using ES3 preset, want to do a PR for that?

**Comment by gkatsev** [comment]
I'll make a PR for the es3 preset and I'll investigate the socket.io thing. Thanks for the quick response!

**Comment by gkatsev** [comment]
The es3 preset PR: https://github.com/karma-runner/karma/pull/2557

**Comment by gkatsev** [comment]
So, the socket.io issue is that uglify 2.7 disabled support for IE8 in a minor version update. Since karma  uses the minified file it broke. Switching to the unminified file works great. I'll open an issue/PR against socket.io-client

**Comment by gkatsev** [comment]
I opened up an issue against socket.io-client: https://github.com/socketio/socket.io-client/issues/1063
Unfortunately, I can't help out anymore with this this week (most likely). It seems like the problem isn't even in socket.io-client but in a dependency.

An easy workaround is to serve the socket.io-client file manually and only use the unminified file as that one works.

I'll check back in next week.

**Comment by exogen** [comment]
Does anyone know of a workaround for this? I can't seem to get IE8 working even if I downgrade Karma to 1.3.0.

**Comment by mgol** [comment]
@exogen [Sizzle](https://github.com/jquery/sizzle/) uses Karma 1.1.1 and it seems to work with IE 8 and even 7: https://travis-ci.org/jquery/sizzle.

**Comment by exogen** [comment]
@mgol Thanks for the tip! After I couldn't get 1.1.1 to work either, I started looking at other dependencies. It works after swapping out `karma-mocha`/`mocha`/`expect.js` for `karma-jasmine`/`jasmine-core`, so I guess one of those deps broke IE8 compatibility. Karma 1.3.0 does indeed work with IE8 (latest is still broken however).

**Comment by maksimr** [comment]
@exogen look at https://github.com/karma-runner/karma-jasmine/issues/105 and https://github.com/karma-runner/karma-mocha/issues/104 maybe this is your case

**Comment by EzraBrooks** [comment]
Can anyone in this thread verify that this issue is fixed on master with socket.io version 2.0.3?

**Comment by gkatsev** [comment]
I had a test run in Video.js using the latest karma from github and it seems to be working: https://travis-ci.org/videojs/video.js/builds/313129759
There's also been a lot of things happening in the repo since the last release, so, another release would be awesome!

**Comment by gkatsev** [comment]
@dignifiedquire any change we could get a new release of karma? The update to socket.io seems to have fixed this issue. Thanks!

**Comment by gkatsev** [comment]
2.0.0 is out and [seems to be working great](https://github.com/videojs/video.js/pull/4834)! Closing this issue as addressed. Thanks!

**Comment by dignifiedquire** [comment]
Great to hear, and sorry for it taking so long.

**Comment by gkatsev** [comment]
It happens, thanks for your hard work!
