### ISSUE TITLE
Possible to serve up a file so that it is available at localhost:9876, and not /base/ ?

### ISSUE THREAD

**Issue by raptoria** [karma-runner/karma#2558]
I have {pattern: './src/newWave.html', watched: false, served: true, included: true}, in my files list, but I would like this file to be available at localhost:9876/newWave.html, and not localhost:9876/base/src/newWave.html/ (the way it is now)

How would I do this?

**Comment by raptoria** [comment]
figured it out
    proxies: {
      '/newWave.html': '/base/src/newWave.html'
    },

**Comment by dignifiedquire** [comment]
Great that you found it yourself, and thank you for reporting your solution :)
