### ISSUE TITLE
Karma does not install in node v7 as --save-dev

### ISSUE THREAD

**Issue by pedrotcaraujo** [karma-runner/karma#2559]
### Expected behaviour
Would like to install Karma in Node v7
### Actual behaviour
NPM engines disable to install karma with node v7 in my project, but global it works.
### Environment Details
- Karma version (output of `karma --version`): Karma version: 1.4.1

### Steps to reproduce the behaviour

1. nvm install v7
2. npm install karma --save-dev
npm ERR! notsup Unsupported engine for karma@1.4.1: wanted: {"node":"0.10 || 0.12 || 4 || 5 || 6"} (current: {"node":"7.1.0","npm":"3.10.9"})

I would like to know if we need to update the version support, since it allow to install as global and works.

**Comment by pedrotcaraujo** [comment]
By myself I found out the answer :). Because LTS https://github.com/nodejs/LTS. It can close if you want.

**Comment by abdulrahmank** [comment]
How did you solve this issue? @pedrotcaraujo

**Comment by pedrotcaraujo** [comment]
I just downgrade my node to LTS version 6 =/

**Comment by dignifiedquire** [comment]
We just need to add `7` in the engine field in `package.json` and do a release with it. PRs welcome

**Comment by pedrotcaraujo** [comment]
@dignifiedquire will this change considered? Since that node v7 is not a LTS yet.

**Comment by dignifiedquire** [comment]
@pedrotcaraujo that's fine, we still want to support it
