### ISSUE TITLE
Fail tests on unhandled exceptions

### ISSUE THREAD

**Issue by dryajov** [karma-runner/karma#2565]
### Expected behaviour
Tests should fail on unhandled exceptions

### Actual behaviour
Tests succeed on unhandled exceptions

### Environment Details
- Karma version (output of `karma --version`):
   Karma version: 1.4.1
- Relevant part of your `karma.config.js` file

### Steps to reproduce the behaviour

1) create a spec file that throws an exception (e.g. `throw 'Throwing on purpose!!!'`)
2) run karma tests
3) output shows that tests are passing even tho an unhandled exception has been thrown

**Comment by dryajov** [comment]
@dignifiedquire any input on this? Is this expected behavior or a bug? I can probably dig around the code base see whats the best solution for this is, but would love to hear your feedback first.

**Comment by maksimr** [comment]
@dryajov could you provide stub project to reproduce this error

Thanks

**Comment by dryajov** [comment]
Turns out that this behavior was caused by `failOnEmptyTestSuite` being set to false and the exception thrown outside an `it` (mocha) definition. Though this flag makes things quite confusing in this particular scenario, I wonder if tests should fail on unhandled exceptions even with this flag set to false, or maybe have a flag to control it this behavior, something like `failTestsOnUnhandledExceptions`, with a default of true.

**Comment by gcca** [comment]
I follow your steps and karma shows the thrown error.

**Comment by vemv** [comment]
A `failTestsOnUnhandledExceptions` would be much welcome for increased flexibility.

My test suite is failing due to low-impact, hard-to-fix errors. The tests themselves fail; that's good enough.

A tiny unhandled error shouldn't prevent the rest of tests from being run.

(possible workaround: set window.onerror myself?)

**Comment by EzraBrooks** [comment]
Seems like a good feature to have, although you’ll have to ensure it doesn’t break assertions. I’d be happy to review a PR on the subject.

**Comment by abduncan** [comment]
What's the word on the street re this feature request?

**Comment by endamccormack** [comment]
Would love to know also

**Comment by johnjbarton** [comment]
The `throw` discussed here is in browser-code and thus needs to be handled by the 'test framework', eg karma-jasmine or karma-mocha.

**Comment by joker-777** [comment]
Why is this closed? I think this is a very valid feature request.

**Comment by johnjbarton** [comment]
Yes! This indeed a very valid feature request...for a test framework like karma-jasmine or karam-mocha. The core project cannot implement it.

**Comment by joker-777** [comment]
Thanks, I think I found a solution.

**Comment by NikolayMakhonin** [comment]
The solution is:
```js
it('test', function() {
  window.onerror = null
  // tests...
})
```

but I think the correct way is:
```js
async function runWithDisabledOnError<T>(func: () => Promise<T>|T): Promise<T> {
  if (typeof window === 'undefined' || window.onerror == null) {
    return func()
  }

  const prevOnError = window.onerror
  window.onerror = null
  try {
    return await func()
  }
  finally {
    window.onerror = prevOnError
  }
}

function delay(timeMilliseconds) {
  return new Promise(resolve => {
    setTimeout(resolve, timeMilliseconds)
  })
}

it('test', async function() {
  await runWithDisabledOnError(() => {
    setTimeout(() => {
      throw new Error('test')
    }, 0)
    return delay(1)
  })
})
```
