### ISSUE TITLE
missing official doc for client.builtPaths configuration setting

### ISSUE THREAD

**Issue by elliot-j** [karma-runner/karma#2567]
The karma.conf.js file in the [angular 2 quickstart](https://github.com/angular/quickstart/blob/master/karma.conf.js) project uses the setting 

    client: {
          builtPaths: [appBase, testingBase], // add more spec base paths as needed
          clearContext: false // leave Jasmine Spec Runner output visible in browser
        },

I have been looking for what exactly the `client.builtPaths` setting  is used for but the [configuration file doc](http://karma-runner.github.io/1.0/config/configuration-file.html) does not have an entry for this setting.

**Comment by lukeatron** [comment]
I found this issue looking for the same answer.  `builtPaths` is not used anywhere by karma.  It's only used in the karam-test-shim.js file, also included in that template.  If I understand what's happening in that file (which is questionable), the values in that object are being used to resolve imports of typescript files back to the transpiled javascript files (the "built" files, if you will).  I'm still not entirely sure how to use this option correctly but it doesn't have anything to do with karma itself.

Confusing choice by the template author to piggy back on the karma config object like that.

**Comment by johnjbarton** [comment]
I verified that 'builtPaths' is not part of karma-runner/karma, thanks @lukeatron
