### ISSUE TITLE
Tests do not tear down properly

### ISSUE THREAD

**Issue by lpender** [karma-runner/karma#2585]
### Expected behaviour

Tests should run independently, cleaning up javascript variables and DOM between test runs.

### Actual behaviour

Tests do not properly tear down and clean up, have poor separation.

### Environment Details

- Karma version (output of `karma --version`):

```
Karma version: 1.5.0
```

### Steps to reproduce the behaviour

1. Create the following test file:

```
describe("test", function() {
  it("creates side effects", function() {
    window.variable = true;
    var element = document.createElement('div');
    element.id = 'side-effect';

    document.body.appendChild(element);
  });

  it("JavaScript environment has been torn down up properly between tests", function () {
    expect(window.variable).not.to.eq(true);
  });

  it("DOM has been torn down up properly between tests", function () {
    expect(document.getElementById('side-effect')).not.to.exist
  });
});
```

2. Run the tests.
3. Tests should pass.

**Comment by maksimr** [comment]
@lpender I don't think that this stuff should be in the karam because:

1. It's hard to implement properly
2. Karma is a test runner, it's not a test framework
3. Client test code know more about test's context and test framework

In your case, it is easy to implement using something like `beforeEach` or `afterEach`. Where you write code which setup(beforeEach) and clean(afterEach) environment.


```js

var sandbox;
beforEach(function() {
     sandbox = document.createElement('div');
     body.appendChild(sandbox);
});

afterEach(function(){
    body.removeChild(sandbox);
});
```

**Comment by lpender** [comment]
I'm working on building end-to-end tests with video ad technology.

Video ads generally, and video js specifically, create side-effects that
can be unpredictable and hard to track down.

The result is that, often, tests pass when run separately but fail when run
together.

Thanks

**Comment by maksimr** [comment]
> create side-effects that
can be unpredictable and hard to track down.

If it's hard to track down by the client application, how should it track `karma`?

Thanks

**Comment by maksimr** [comment]
@lpender I think you could implement this using [customContextFile](http://karma-runner.github.io/1.0/config/configuration-file.html).

You could at [default implementation of context.html](https://github.com/karma-runner/karma/blob/master/static/context.html#L28).
As you can see there you have special variables like ` %MAPPINGS%` and `%SCRIPTS%`.
This allows you control when and how load the files. For example, you could put each file to the separate iframe or something like this.

Thanks

**Comment by lpender** [comment]
I've found that the way around this is to place the tests in separate files.

You can extract setup / teardown methods to an external "helper" file and call them at the beginning of `it` blocks.

Works reasonably well and forces you to keep file size very small
