### ISSUE TITLE
what is the phantom pdf A4 size in pixel?

### ISSUE THREAD

**Issue by iyyappan13391** [karma-runner/karma#2592]
Actually i am using getting final output pdf A4 with help of phantom.I'm having content of exact A4 size(595 * 842 pixels).But **phantom pdf output** is larger than A4(595 * 842 pixels).B size.

Does anybody know???

**Comment by FezVrasta** [comment]
What the hell does it have to do with Karma Runner?

**Comment by iyyappan13391** [comment]
Apologies for my mistake.
