### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by doberkofler** [karma-runner/karma#2605]
### Expected behaviour
run an arbitrary large number of unit tests run in a single invocation

### Actual behaviour
when combining a large number of unit tests, they eventually fail with the error:
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### Environment Details

- Karma version (output of `karma --version`):

    "karma": "~1.5.0",
    "karma-chai": "~0.1.0",
    "karma-chai-datetime": "~0.1.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-firefox-launcher": "~1.0.1",
    "karma-ie-launcher": "~1.0.0",
    "karma-mocha": "~1.3.0",
    "karma-mocha-reporter": "~2.2.2",
    "karma-phantomjs-launcher": "~1.0.4",
    "karma-sinon": "~1.0.5",
    "karma-sourcemap-loader": "~0.3.7",
    "karma-webpack": "~2.0.3",

    "webpack": "~2.2.1",

    "babel-core": "~6.24.0",
    "babel-loader": "~6.4.0",
    "babel-plugin-transform-async-to-generator": "~6.22.0",
    "babel-preset-es2015": "~6.24.0",

- Relevant part of your `karma.config.js` file

```
	// config
	const KARMA_CONFIG = {
		// base path that will be used to resolve all patterns (eg. files, exclude)
		basePath: '',

		// frameworks to use
		// available frameworks: https://npmjs.org/browse/keyword/karma-adapter
		frameworks: ['mocha', 'chai-datetime', 'chai', 'sinon'],

		// list of files / patterns to load in the browser
		files: [
			{pattern: 'dist/core.css', watched: false, included: true, served: true, nocache: false},
			{pattern: 'dist/core.js', watched: false, included: true, served: true, nocache: false},
			{pattern: 'dist/*.*', watched: false, included: false, served: true}
		],

		// list of files to exclude
		exclude: [
		],

		// preprocess matching files before serving them to the browser
		// available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
		preprocessors: {
		},

		// test results reporter to use
		// possible values: 'dots', 'progress'
		// available reporters: https://npmjs.org/browse/keyword/karma-reporter
		reporters: ['mocha'],

		// web server port
		port: 9876,

		// enable / disable colors in the output (reporters and logs)
		colors: true,

		// level of logging
		// possible values: LOG_DISABLE || LOG_ERROR || LOG_WARN || LOG_INFO || LOG_DEBUG
		logLevel: debugFlag ? karma.constants.LOG_DEBUG : karma.constants.LOG_INFO,

		// enable / disable watching file and executing tests whenever any file changes
		autoWatch: false,

		// start these browsers
		// available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
		browsers: browsers,

		// Continuous Integration mode
		// if true, Karma captures browsers, runs the tests and exits
		singleRun: true,

		// Concurrency level
		// how many browser should be started simultaneous
		concurrency: 1,

		// Client
		client: {
			mocha: {
				timeout: timeout
			}
		},

		// Description: A map of path-proxy pairs.
		// The proxy can be specified directly by the target url or path, or with an object to configure more options. The available options are:
		//	target The target url or path (mandatory)
		//	changeOrigin Whether or not the proxy should override the Host header using the host from the target (default false)
		proxies: {
			'/lj_unittest/': {
				target: urlRoot + '/',
				changeOrigin: true
			},
			'/LAS_SYS_DBG.webLog': {
				target: urlRoot + '/LAS_SYS_DBG.webLog',
				changeOrigin: true
			}
		},

		// WebPack
		webpack: getConfigUnitTest({
			target: 'var',
			outputPath: tempPath
		}),
		webpackMiddleware: {
			noInfo: true,
			stats: 'errors-only'
		}
	};

	// add the scripts
	scripts.forEach(function (script) {
		KARMA_CONFIG.preprocessors[script] = ['webpack', 'sourcemap'];
		KARMA_CONFIG.files.push({pattern: script, watched: false, included: true, served: true, nocache: false});
	});
```

### Steps to reproduce the behaviour

Unfortunately like with most out of memory conditions, the error is not 100% reproducible but when the list of scripts within a single execution reaches about 80 unit tests the error message is reported in about 50% of the executions. When I execute each script individually it runs in 100% of cases.
The reason to run multiple tests together is to dramatically improved performed by up to 10 times.

**Comment by dignifiedquire** [comment]
I have seen this issue before and it is not due to karma but due to webpack as far as I can tell

**Comment by doberkofler** [comment]
@dignifiedquire I'm using webpack2 for the production code itself and it actually never reports this problem. Is there any way to track down where the problem comes from?

**Comment by maksimr** [comment]
@doberkofler you can debug it using `node --inspect`

```js
node --inspect --debug-brk node_modules/.bin/karma start
```

**Comment by maksimr** [comment]
@doberkofler am I right that [you already had such problem with webpack](https://github.com/webpack/webpack/issues/1914#issuecomment-280951550)?

**Comment by doberkofler** [comment]
@maksimr Yes, but the problems have been resolved after migrating to webpack2. I'm not sure where the problem comes from but currently it does not seem as if it would be webpack problem because the webpack builds themselves work as expected and are actually even bigger then the unit tests.

**Comment by maksimr** [comment]
@doberkofler I recommend you update [karma-webpack](https://github.com/webpack-contrib/karma-webpack) and try to debug this by `node --inspect`

I'm still thinking that the problem in *webpack*

Thanks

**Comment by doberkofler** [comment]
@maksimr Currently using karma-webpack 2.0.3 and will try to debug. Thank you!

**Comment by CTaylor1118** [comment]
@doberkofler Were you able to resolve this? I am seeing the same error on single runs (sometimes) and when running in watch mode (consistently). I reported #2673 with some of the output from node. Did you have the same output?

**Comment by doberkofler** [comment]
@CTaylor1118 not really. i did not have the time to dig into a debugging session and for now i just process each test script individually. runs a lot slower but at least my ci tests run reliably.
