### ISSUE TITLE
 Uncaught SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by Hosar** [karma-runner/karma#2608]
### Expected behaviour
Run a test with es6
### Actual behaviour
Getting  Uncaught SyntaxError: Unexpected token export
### Environment Details

- Karma version: 1.5.0
 
```basePath: '',
    preprocessors: {      
      '../client/**/*.js': ['babel'],
      'unit/*.js': ['babel']
    },
    babelPreprocessor: {
      options: {
        presets: ['es2015'],
        plugins: ['transform-es2015-modules-umd'],
        sourceMap: 'inline'
      },
      filename: function (file) {
        return file.originalPath.replace(/\.js$/, '.es5.js');
      },
      sourceFileName: function (file) {
        return file.originalPath;
      }
    },
```

- babel-core: "^6.24.0"
- node: v7.4.0

**Comment by maksimr** [comment]
@Hosar [karma-babel-preprocessor](https://github.com/babel/karma-babel-preprocessor) is better place for this issue because I think the problem in babel setup.

Thanks

**Comment by Hosar** [comment]
Ok got it, I'll check on that. Thank you

**Comment by maksimr** [comment]
@Hosar Did you solve the problem?

**Comment by EzraBrooks** [comment]
No feedback in 8 months; closing.
