### ISSUE TITLE
Karma calls Jasmine it test twice. Second call has no preceding beforeEach() call.

### ISSUE THREAD

**Issue by anatesan** [karma-runner/karma#2615]
### Expected behaviour
I expect 
1) each test (specified in it) to be run once 
2) each test run of the it call needs to be preceded by a call to beforeEach().   

### Actual behaviour
On expected behavior (1) above,  I do see the call to the it test happening twice - see trace below.  (Note there is an issue reported here in https://github.com/karma-runner/karma/issues/1873)

On expected behavior (2), I noticed with Karma runs that the second (and only the second call) call is NOT preceded by a beforeEach().   I found this problem because I was relying on some context to be set up in the this reference in the beforeEach & the second test run was failing since the context was not set up.  

NOTE: When I run the same tests with Jasmine directly,  there is only 1 run of the it test and beforeEach is called correctly prior to the test.

### Environment Details

- Karma version (output of `karma --version`): 1.5.0
- Relevant part of your `karma.config.js` file:  I just did karma init and added my files there - nothing else added.  I am running on Chrome.

### Steps to reproduce the behaviour

1.  I did a console log in the Before Each and in each it test.  You can try this on any of your existing Jasmine unit tests.
2. I ran the same tests (a) under Karma and then (b) under Jasmine directly (using SpecRunner) 

####  Console log output when run under Karma  
I refreshed Chrome connected to Karma & got the console log from Dev Tools

![image](https://cloud.githubusercontent.com/assets/7743950/24087149/8daaf8c4-0cd8-11e7-9fc8-ba22b1d154c8.png)

Note that the 3 tests are run a second time.   Also, note that the last 3 tests are NOT preceded by a beforeEach and the "this" properties are NOT set as as result

#### Console log output when run under Jasmine directly (using SpecRunner)

![image](https://cloud.githubusercontent.com/assets/7743950/24087119/1b36f3ce-0cd8-11e7-9735-2895cbb8c3b0.png)

Notice that a beforeEach log precedes every test and each test is run exactly once

I googled around quite a bit but could not find anything similar reported.   

This is somewhat nuanced symptom - you are impacted only if you are relying on a per-test setup rather than a per-suite setup. This problem can be masked if the beforeEach is storing state in variables at the describe/suite level.   So, even if the test is called twice & potentially without the second beforeEach,  the first run may have set up the describe level variables correctly enough for the tests to have the right setup.

**Comment by maksimr** [comment]
@anatesan could you provide test repository which reproduces this problem because we use karma + jasmine in our project and all work as expected.

Thanks

**Comment by cadreon-ashok-natesan** [comment]
This reproduces pretty easily for me with this test - this is the spec file referenced in the karma files section below

`describe('demonstrate 2 calls per it', function(){

  beforeEach(function() {
    console.log('in Before Each');
  });

  it('Test1 run', function(){
    console.log('in Test1');
    expect(1).toEqual(1);
  });

  it('Test2 run', function(){
    console.log('in Test2');
    expect(1).toEqual(1);
  })
})`

I am running karma version 1.5.0, jasmine 2.5.0. I can't seem to get the console.log to show up in the karma output,  so the output below is from the console/debug tools.  Note that Tes1 shows up twice... This seems somewhat random.   Sometimes I see Test 2 being called more than once.

![image](https://cloud.githubusercontent.com/assets/22921146/24278721/c3033018-1002-11e7-8364-56c0a59d0f03.png)

My karma.conf.js - the files section has this
`    files: [
      'css/bootstrap.min.css',
      'lib/jasmine-2.5.2/jasmine.js',
      'lib/jasmine-2.5.2/jasmine-html.js',
      'lib/jasmine-2.5.2/boot.js',
      'lib/jasmine-2.5.2/jasmine.css',
      'lib/jasmine-2.5.2/*.js',
      'lib/angular.min.js',
      'lib/angular-mocks.js',
      'src/test2calls.spec.js'
    ],`

**Comment by maksimr** [comment]
@cadreon-ashok-natesan You should not load jasmine files manually if you set

```js
    frameworks: ['jasmine'],
    files: [
      'css/bootstrap.min.css',
      'lib/angular.min.js',
      'lib/angular-mocks.js',
      'src/test2calls.spec.js'
    ]
```

so the problem that jasmine loaded twice.

Thanks

**Comment by cadreon-ashok-natesan** [comment]
@maksimr Thanks for your pointer.  You are absolutely correct.   

After taking this out,  I no longer see this behavior.   This also solved a couple of other issues I was seeing.

I am not sure if this is possible without causing other issues.  Would this make sense to have karma detect this situation and just prevent these duplicate loads (or at least flagging an error)

**Comment by maksimr** [comment]
@cadreon-ashok-natesan 

>Would this make sense to have karma detect this situation and just prevent these duplicate loads

I don't think that it's karma's responsibility.
In my opinion **jasmine** should show a warning if jasmine was loaded twice, as it's implemented in **Angular** and **React**.

**Comment by MattDillard** [comment]
I experience the same symptoms as the original poster, but it was not due to including jasmine.js in the files section of karma.conf.js. Instead, my files section references only "test.ts", as I am working on an Angular application, and that is how Angular CLI sets up new projects ("ng new MyApp").

Recently, though, the following lines had been accidentally removed from test.ts. Restoring these fixed the problem:

// Prevent Karma from running prematurely.
__karma__.loaded = function () {};

**Comment by cadreon-ashok-natesan** [comment]
@MattDillard:  Are you suggesting that every test have this line?   This seems counter-intuitive as a best practice.   Also,  I don't have this in my tests & things are working fine after I made the fix suggested by @maksimr

**Comment by MattDillard** [comment]
@cadreon-ashok-natesan: No, this is not for every single test. When setting up a new Angular project, it uses a different mechanism for specifying which files contain unit tests. This specification (along with some other boilerplate) is done in a single file called "test.ts". That's where this goes.

I suspect my issue was more specific to running in an Angular environment. I simply wanted indicate that I saw the same problematic behavior, but it had a different cause.
