### ISSUE TITLE
Promise resolver is executed instantly / then never called

### ISSUE THREAD

**Issue by moehlone** [karma-runner/karma#2616]
### Expected behaviour

A promise resolver should only execute after processing the promise with `then`.

### Actual behaviour

Any promise resolver is called instantly and the `then` block/resolver is never called.

### Environment Details

- Karma version: 1.5.0
- `karma.config.js` file:
```javascript
config.set({
    basePath: "",
    frameworks: [
      "mocha",
      "browserify",
      "chai-dom",
      "chai-sinon",
      "fixture"
    ],
    files: [
      // ...
    ],
    exclude: [],
    preprocessors: {
      [`${testJsAssetsDir}js/**/*Spec.js`]: ["browserify"],
      "./fixture/**/*.html": ["html2js"]
    },
    browserify: {
      debug: true,
      transform: [
        [
          "browserify-istanbul",
          {
            instrumenter: isparta
          }
        ]
      ]
    },
    reporters: [
      "mocha",
      "coverage"
    ],
    coverageReporter: {
      type: "lcov",
      dir: "../../../../build/reports/coverage/client"
    },
    port: 9877,
    colors: true,
    logLevel: config.LOG_INFO,
    browserConsoleLogOptions: {
      level: "log",
      terminal: true
    },
    autoWatch: false,
    browsers: ["Chrome"],
    singleRun: false,
    concurrency: os.cpus().length
  });
```
### Steps to reproduce the behaviour

1. Run the following coding anywhere in the test setup.
```javascript
var somePromise = new Promise(function(resolve, reject) {
      console.log("ABC");
      resolve();
    });
    console.log(somePromise);
```
2. `"ABC"` gets logged instantly
3. Promise is resolved before it gets processed

**Comment by dignifiedquire** [comment]
This is not related to Karma, but rather to the promise implementation or shim in the browser you are testing.

**Comment by moehlone** [comment]
The problem is, that Karma runs my local browser (Chrome) and execution fails. Our application itself is working in these steps (also tested with the same Chrome). Any suggestions? :/

**Comment by maksimr** [comment]
@moehlone I agree with @dignifiedquire this is not a problem of the `Karma`.
This is a default behavior in Chrome. Type your example in developer tools and you will see that Chrome resolve promise immediately.

Thanks
![karam-issue-2616](https://cloud.githubusercontent.com/assets/616193/24165278/01ab3ee2-0e81-11e7-8973-92d6728a716d.gif)
