### ISSUE TITLE
Karma proxy behaves weirdly

### ISSUE THREAD

**Issue by timargra** [karma-runner/karma#2622]
### Expected behaviour

Proxy should process requests the same way other servers (e.g. nginx) do.

### Actual behaviour

Getting strange errors - sometimes 404, sometimes other unexpected responses - when proxing my APIs (e.g. Mite API) through Karma. When simply proxying _http://www.google.com_, I get a 404.

To diagnose the problem I proxied an nginx on localhost, but the access log seems fine

### Environment Details

- Karma version 1.5.0

_karma.config.js_
```
proxies: {
  '/google': 'http://www.google.com',
  '/api/mite/': 'https://yxz.mite.yo.lk/',
  '/base/web/node_modules/': '/base/node_modules/'
},
proxyValidateSSL: false
```
nginx _access.log_ (first line: direct request, second line: request proxied through Karma)
```
172.20.0.1 - - [22/Mar/2017:11:44:06 +0000] "GET /api/mite/customers.json?limit=100 HTTP/1.1" 200 8118 "-" "-"
172.20.0.1 - - [22/Mar/2017:11:44:18 +0000] "GET /api/mite/customers.json?limit=100 HTTP/1.1" 404 64 "-" "-"
```

### Steps to reproduce the behaviour

1. Set up a http proxy in the config

**Comment by maksimr** [comment]
@timargra  you should use [`changeOrigin`](http://karma-runner.github.io/1.0/config/configuration-file.html) option

```js
      '/google': {
        'target': 'http://www.google.com',
        'changeOrigin': true
      },
      '/api/mite/': {
        'target': 'https://yxz.mite.yo.lk/',
        'changeOrigin': true      
       }
```

The proxy will send **Host** header which refers to `localhost` if you don't turn on *changeOrigin* option.


Thanks!
