### ISSUE TITLE
Requiring Karma breaks Jasmine tests due to the use of "core-js"

### ISSUE THREAD

**Issue by bennyn** [karma-runner/karma#2631]
### Expected behaviour

Passing tests.

### Actual behaviour

```bash
RangeError: Wrong length!
        at validateArrayBufferArguments (D:\dev\projects\bennyn\karma-core-js-error\node_modules\core-js\modules\_typed-buffer.js:157:39)
```

### Environment Details

- Karma v1.5.0
- Node.js v7.7.3

### Steps to reproduce the behaviour

I have a test setup with [Gulp](http://gulpjs.com/), where I use the [Jasmine](https://jasmine.github.io/) test framework to execute a single test. 

The test is passing but as soon as I require Karma in my `gulpfile.js` (with `const karma = require('karma')`) the test breaks and I get the following error:

```bash
  Stack:
    RangeError: Wrong length!
        at validateArrayBufferArguments (D:\dev\projects\bennyn\karma-core-js-error\node_modules\core-js\modules\_typed-buffer.js:157:39)
```

It looks like Karma is loading [core-js](https://github.com/zloirock/core-js) and core-js seems to override typed array buffers. Can you confirm this?

I have a very detailed project, which proves the error: https://github.com/bennyn/karma-core-js-error

core-js throws the error in this function:

```javascript
var validateArrayBufferArguments = function(that, length){
  anInstance(that, $ArrayBuffer, ARRAY_BUFFER);
  var numberLength = +length
    , byteLength   = toLength(numberLength);
  if(numberLength != byteLength)throw RangeError(WRONG_LENGTH);
  return byteLength;
};
```

The value of `numberLength` is `109.5`  and `byteLength` is `109`, so they are uneven and that's why core-js throws a `RangeError`. But why does Karma load core-js and why does core-js affect Node.js buffers?

**Comment by maksimr** [comment]
@bennyn karma uses [core-js for support **es5**](https://github.com/karma-runner/karma/search?utf8=%E2%9C%93&q=core-js&type=)

cc @dignifiedquire

**Comment by bennyn** [comment]
@zloirock As author of "core-js", maybe you can help with this issue? Can you tell us under which circumstances "core-js" executes `validateArrayBufferArguments`? 

It looks like that "core-js" overwrites Node's ArrayBuffers with a behaviour which makes my test project fail: https://github.com/bennyn/karma-core-js-error

**Comment by zloirock** [comment]
> Can you tell us under which circumstances "core-js" executes `validateArrayBufferArguments`?

In all cases, when `ArrayBuffer` is not completely correct by the spec. By the spec, this error should be thrown if you pass to `ArrayBuffer` constructor incorrect length.
[`24.1.2.1 ArrayBuffer(length)`, step 2](https://tc39.github.io/ecma262/#sec-arraybuffer-constructor) -> [`7.1.17 ToIndex(value)`, step 2, `b` or `c`](https://tc39.github.io/ecma262/#sec-toindex)

**Comment by bennyn** [comment]
Thanks for the answer! So the problem seems to be located in Node.js, which is incorrectly (according to the spec) implementing ArrayBuffers?

@maksimr Do you need any further information from my side? I was quite surprised that a simple `require('karma')` can break my test setup.

**Comment by zloirock** [comment]
@bennyn the problem in code which pass incorrect length to `ArrayBuffer` constructor.

**Comment by bennyn** [comment]
But when `core-js` is not involved, my code works perfect. It's just the core-js ArrayBuffer polyfill which makes it fail. Have you checked my example here? https://github.com/bennyn/karma-core-js-error

**Comment by maksimr** [comment]
@bennyn 

> Do you need any further information from my side? 

Am I right that you use ArrayBuffer and pass incorrect length?

Thanks

**Comment by bennyn** [comment]
@maksimr and @zloirock thanks for your great help!

The problem really sits within a 3rd party library, which I use. The third-party library initializes ArrayBuffers with floating point numbers. Node.js does not bother about it but when integrating "core-js" (which pays close attention to the ArrayBuffer spec) it comes to errors.

Here is an example which works with Node.js:

```javascript
const buffer = new ArrayBuffer(3.5);
console.log(buffer.byteLength); // 3
```

When requiring karma (which integrates "core-js"), it fails:

```javascript
const karma = require('karma');
const buffer = new ArrayBuffer(3.5);
console.log(buffer.byteLength); // RangeError: Wrong length! at validateArrayBufferArguments
```

I made a quickfix using the double tilde (`Math.floor` can be used too):

```javascript
const karma = require('karma');
const buffer = new ArrayBuffer(~~3.5);
console.log(buffer.byteLength); // 3
```

Thanks again for helping me out!
