### ISSUE TITLE
Jenkins ssh slave - Chrome not captured in X ms

### ISSUE THREAD

**Issue by celamb4** [karma-runner/karma#2633]
### Expected behaviour

> 28 03 2017 16:07:05.755:INFO [karma]: Karma v1.5.0 server started at http://0.0.0.0:9876/
> 28 03 2017 16:07:05.756:INFO [launcher]: Launching browser Chrome with unlimited concurrency
> 28 03 2017 16:07:05.762:INFO [launcher]: Starting browser Chrome
> 28 03 2017 16:07:07.429:INFO [Chromium 53.0.2785 (Ubuntu 0.0.0)]: Connected on socket pbLZsYM4ECCPhx3EAAAA with id 38457800

### Actual behaviour

> [Unit] [32m28 03 2017 15:53:20.743:INFO [karma]: [39mKarma v1.5.0 server started at http://0.0.0.0:9876/
> [Unit] [32m28 03 2017 15:53:20.744:INFO [launcher]: [39mLaunching browser Chrome with unlimited concurrency
> [Unit] [32m28 03 2017 15:53:20.748:INFO [launcher]: [39mStarting browser Chrome
> [Unit] [33m28 03 2017 15:54:20.687:WARN [launcher]: [39mChrome have not captured in 60000 ms, killing.
> [Unit] [33m28 03 2017 15:54:22.693:WARN [launcher]: [39mChrome was not killed in 2000 ms, sending SIGKILL.
> [Unit] [33m28 03 2017 15:54:24.695:WARN [launcher]: [39mChrome was not killed by SIGKILL in 2000 ms, continuing.

### Environment Details

- Karma version (output of `karma --version`):
Karma version: 1.5.0

- Relevant part of your `karma.config.js` file
```
    browsers: [
      'Chrome'
    ],

    customLaunchers: {
      Chrome_travis_ci: {
        base: 'Chrome',
        flags: ['--no-sandbox']
      }
    },
```

### Steps to reproduce the behaviour

1. Launch ubuntu ssh slave agent with Xvfb display and chromium. Export Display, export chrome_bin
2. Run npm test via pipeline script (i.e. jenkins agent executes tests)
3. Chrome fails to start

Additional info.
If karma is launched manually via command line in the ssh slave, the tests pass. It only fails when it runs on the slave via the pipeline execution. Note that within the same VM (ubuntu, Xvfb and chromium) I can run manually and pass but fails when executed on the jenkins pipeline.

chromium-browser --version
Chromium 53.0.2785.143 Built on Ubuntu , running on Ubuntu 14.04

Issue #1206 is similar but fix did not work. 
I also tried to increase the timeout to 15000 as mentioned in the comments but no luck. 

> [Unit] [32m28 03 2017 16:40:14.226:INFO [karma]: [39mKarma v1.5.0 server started at http://0.0.0.0:9876/
> [Unit] [32m28 03 2017 16:40:14.226:INFO [launcher]: [39mLaunching browser Chrome with unlimited concurrency
> [Unit] [32m28 03 2017 16:40:14.232:INFO [launcher]: [39mStarting browser Chrome
> [Unit] [33m28 03 2017 16:42:44.277:WARN [launcher]: [39mChrome have not captured in 150000 ms, killing.
> [Unit] [33m28 03 2017 16:42:46.281:WARN [launcher]: [39mChrome was not killed in 2000 ms, sending SIGKILL.
> [Unit] [33m28 03 2017 16:42:48.283:WARN [launcher]: [39mChrome was not killed by SIGKILL in 2000 ms, continuing.
>

**Comment by celamb4** [comment]
Details on the display (Xvfb). This is the output of the command executed by the jenkins ssh agent in the pipeline. Not manual.

`sh 'xset q`

```
[Unit] + xset q
[Unit] Keyboard Control:
[Unit]   auto repeat:  on    key click percent:  0    LED mask:  00000000
[Unit]   XKB indicators:
[Unit]     00: Caps Lock:   off    01: Num Lock:    off    02: Scroll Lock: off
[Unit]     03: Compose:     off    04: Kana:        off    05: Sleep:       off
[Unit]     06: Suspend:     off    07: Mute:        off    08: Misc:        off
[Unit]     09: Mail:        off    10: Charging:    off    11: Shift Lock:  off
[Unit]     12: Group 2:     off    13: Mouse Keys:  off
[Unit]   auto repeat delay:  660    repeat rate:  25
[Unit]   auto repeating keys:  00ffffffdffffbbf
[Unit]                         fadfffefffedffff
[Unit]                         9fffffffffffffff
[Unit]                         fff7ffffffffffff
[Unit]   bell percent:  50    bell pitch:  400    bell duration:  100
[Unit] Pointer Control:
[Unit]   acceleration:  2/1    threshold:  4
[Unit] Screen Saver:
[Unit]   prefer blanking:  yes    allow exposures:  yes
[Unit]   timeout:  600    cycle:  600
[Unit] Colors:
[Unit]   default colormap:  0x20    BlackPixel:  0x0    WhitePixel:  0xffffff
[Unit] Font Path:
[Unit]   /usr/share/fonts/X11/misc,/usr/share/fonts/X11/cyrillic,/usr/share/fonts/X11/100dpi/:unscaled,/usr/share/fonts/X11/75dpi/:unscaled,/usr/share/fonts/X11/Type1,/usr/share/fonts/X11/100dpi,/usr/share/fonts/X11/75dpi,built-ins
[Unit] DPMS (Energy Star):
[Unit]   Display is not capable of DPMS
```

**Comment by maksimr** [comment]
@celamb4 am I right that If you connect to the *slave* by ssh and run *karma* all work fine?

**Comment by celamb4** [comment]
@maksimr thank you for the reply!

Yes. if I ssh manually (i.e. via my laptop terminal) to the slave ssh node. I can run the tests fine. Not sure why karma is not able to connect to the chrome socket when launching via jenkins agent. Might not be karma, I found #1206 and noticed similar issues/behavior. 

Note (FYI): the ssh slave is being launched by the azure vm agent plugin automatically and gets destroyed after a set period of time.

**Comment by maksimr** [comment]
Interesting ...

@celamb4 are you sure that Jenkins starts X-server(Xvfb) when it launches an agent(slave)?
Where located code which starts Xvfb ([like this](https://github.com/karma-runner/karma/blob/master/.travis.yml#L36-L37)?

I think that when you connect to the agent by ssh, it starts X-server properly.

**Comment by celamb4** [comment]
Im pretty sure Xvfb is running. Not sure what I'm missing. 
Thanks for the support @maksimr 

I've tried several ways also. I've been struggling with this for some time now. 

1) starting xvfb from within the init script before jenkins runs Slave.jar with:
`Xvfb :1 -screen 0 '1280x1024x24' -ac`

2) starting xvfb right before npm test with:
`sh "xdpyinfo -display :1 >/dev/null 2>&1 && echo 'Display 1 running' || Xvfb :1 -screen 0 '1280x1024x24' -ac &> /tmp/xvfb.log &"`

3) Using the Xvfb jenkins plugin

I can see that jenkins can see the display from the xset and xdpyinfo command outputs. Here is the output from the pipeline. for Jenkins display :1 is set and available, chromium can be called note that chromium -version is called without issue.

```
[Unit] + xdpyinfo -display :1
[Unit] + echo Display 1 running
[Unit] Display 1 running
[Pipeline] [Unit] sh
[Unit] + which chromium-browser
[Pipeline] [Unit] withEnv
[Pipeline] [Unit] {
[Pipeline] [Unit] sh
[Unit] + chromium-browser --version
[Unit] Chromium 53.0.2785.143 Built on Ubuntu , running on Ubuntu 14.04
[Pipeline] [Unit] sh
[Unit] + xset q
[Unit] Keyboard Control:
[Unit]   auto repeat:  on    key click percent:  0    LED mask:  00000000
[Unit]   XKB indicators:
[Unit]     00: Caps Lock:   off    01: Num Lock:    off    02: Scroll Lock: off
[Unit]     03: Compose:     off    04: Kana:        off    05: Sleep:       off
[Unit]     06: Suspend:     off    07: Mute:        off    08: Misc:        off
[Unit]     09: Mail:        off    10: Charging:    off    11: Shift Lock:  off
[Unit]     12: Group 2:     off    13: Mouse Keys:  off
[Unit]   auto repeat delay:  660    repeat rate:  25
[Unit]   auto repeating keys:  00ffffffdffffbbf
[Unit]                         fadfffefffedffff
[Unit]                         9fffffffffffffff
[Unit]                         fff7ffffffffffff
[Unit]   bell percent:  50    bell pitch:  400    bell duration:  100
[Unit] Pointer Control:
[Unit]   acceleration:  2/1    threshold:  4
[Unit] Screen Saver:
[Unit]   prefer blanking:  yes    allow exposures:  yes
[Unit]   timeout:  600    cycle:  600
[Unit] Colors:
[Unit]   default colormap:  0x20    BlackPixel:  0x0    WhitePixel:  0xffffff
[Unit] Font Path:
[Unit]   /usr/share/fonts/X11/misc,/usr/share/fonts/X11/cyrillic,/usr/share/fonts/X11/100dpi/:unscaled,/usr/share/fonts/X11/75dpi/:unscaled,/usr/share/fonts/X11/Type1,/usr/share/fonts/X11/100dpi,/usr/share/fonts/X11/75dpi,built-ins
[Unit] DPMS (Energy Star):
[Unit]   Display is not capable of DPMS
[Pipeline] [Unit] sh
[Unit] + xdpyinfo -display :1
[Unit] name of display:    :1
[Unit] version number:    11.0
[Unit] vendor string:    The X.Org Foundation
[Unit] vendor release number:    11501000
[Unit] X.Org version: 1.15.1
[Unit] maximum request size:  16777212 bytes
[Unit] motion buffer size:  256
[Unit] bitmap unit, bit order, padding:    32, LSBFirst, 32
[Unit] image byte order:    LSBFirst
[Unit] number of supported pixmap formats:    6
[Unit] supported pixmap formats:
[Unit]     depth 1, bits_per_pixel 1, scanline_pad 32
[Unit]     depth 4, bits_per_pixel 8, scanline_pad 32
[Unit]     depth 8, bits_per_pixel 8, scanline_pad 32
[Unit]     depth 16, bits_per_pixel 16, scanline_pad 32
[Unit]     depth 24, bits_per_pixel 32, scanline_pad 32
[Unit]     depth 32, bits_per_pixel 32, scanline_pad 32
[Unit] keycode range:    minimum 8, maximum 255
[Unit] focus:  PointerRoot
[Unit] number of extensions:    24
[Unit]     BIG-REQUESTS
[Unit]     Composite
[Unit]     DAMAGE
[Unit]     DOUBLE-BUFFER
[Unit]     DPMS
[Unit]     DRI3
[Unit]     GLX
[Unit]     Generic Event Extension
[Unit]     MIT-SCREEN-SAVER
[Unit]     MIT-SHM
[Unit]     Present
[Unit]     RECORD
[Unit]     RENDER
[Unit]     SECURITY
[Unit]     SGI-GLX
[Unit]     SHAPE
[Unit]     SYNC
[Unit]     X-Resource
[Unit]     XC-MISC
[Unit]     XFIXES
[Unit]     XInputExtension
[Unit]     XKEYBOARD
[Unit]     XTEST
[Unit]     XVideo
[Unit] default screen number:    0
[Unit] number of screens:    1
[Unit] 
[Unit] screen #0:
[Unit]   dimensions:    1280x1024 pixels (325x260 millimeters)
[Unit]   resolution:    100x100 dots per inch
[Unit]   depths (6):    24, 1, 4, 8, 16, 32
[Unit]   root window id:    0x169
[Unit]   depth of root window:    24 planes
[Unit]   number of colormaps:    minimum 1, maximum 1
[Unit]   default colormap:    0x20
[Unit]   default number of colormap cells:    256
[Unit]   preallocated pixels:    black 0, white 16777215
[Unit]   options:    backing-store WHEN MAPPED, save-unders NO
[Unit]   largest cursor:    1280x1024
[Unit]   current input event mask:    0x0
[Unit]   number of visuals:    120
[Unit]   default visual id:  0x21
```
.
.
.

```
[Unit] [32m28 03 2017 21:03:37.643:INFO [karma]: [39mKarma v1.5.0 server started at http://0.0.0.0:9876/
[Unit] [32m28 03 2017 21:03:37.643:INFO [launcher]: [39mLaunching browser Chrome with unlimited concurrency
[Unit] [32m28 03 2017 21:03:37.648:INFO [launcher]: [39mStarting browser Chrome
[Unit] [33m28 03 2017 21:06:07.729:WARN [launcher]: [39mChrome have not captured in 150000 ms, killing.
[Unit] [33m28 03 2017 21:06:09.733:WARN [launcher]: [39mChrome was not killed in 2000 ms, sending SIGKILL.
[Unit] [33m28 03 2017 21:06:11.736:WARN [launcher]: [39mChrome was not killed by SIGKILL in 2000 ms, continuing.
```

**Comment by celamb4** [comment]
Fixed this. 

For anyone having a similar issue. Karma was only able to connect to the xvfb display on DISPLAY=:0

I initially had it on a different display and it was timing out. I was able to run tests on the slave and master on display 0.
