### ISSUE TITLE
Angular2 - KarmaJS - unit Tests no executed automatically on npm test

### ISSUE THREAD

**Issue by dalidovski** [karma-runner/karma#2646]
# Dependencies versions

"karma": "^1.2.0"
"karma-chrome-launcher": "^2.0.0"
"karma-cli": "^1.0.1"
"karma-jasmine": "1.0.2"

# Description

I'm using KarmaJS and JasmineJS for unit testing on Angular2. When I run "npm test" the browser opened automatically, however the tests not executed automatically.

![ng-test](https://cloud.githubusercontent.com/assets/22326523/24695660/e65c17e4-19e6-11e7-99a7-aa4b358ef7d3.png)

If I change any file all the tests will be executed in the project.

![ng-test-success](https://cloud.githubusercontent.com/assets/22326523/24695659/e65b9620-19e6-11e7-8ba8-3621b8933f64.png)

Here is my Karma-conf.js

![karma-conf](https://cloud.githubusercontent.com/assets/22326523/24695661/e65daf1e-19e6-11e7-9482-0ce5a3e52612.png)

Here is my test.ts

![test-ts](https://cloud.githubusercontent.com/assets/22326523/24695662/e65e9618-19e6-11e7-8485-6620f5eadebf.png)

**Comment by ralberts** [comment]
Same issue for me :-)

**Comment by dignifiedquire** [comment]
what is the command that `"test"` is actually set to in your package.json?

**Comment by maksimr** [comment]
@dalidovski why do you patch **karma**? 

```js
__karma__.loaded = function() {}
...
__karma__.start()
```

Is problem reproduced if remove such hacks?

**Comment by dalidovski** [comment]
@dignifiedquire ng test -- "test": "ng test"

**Comment by ralberts** [comment]
I haven't looked to see if my dependencies are the same or not as this original thread. Though when the upgrade came out yesterday and I had the same trouble - I tried running from within intellij/webstorm and our grunt file using the command:

Webstorm:
`"C:\Program Files\nodejs\node.exe" C:\Users\<user>\.IntelliJIdea2017.1\config\plugins\js-karma\js_reporter\karma-intellij\lib\intellijServer.js --karmaPackageDir=C:\Dev\Projects\<my_project>\node_modules\karma --configFile=C:\Dev\Projects\<my_project>\test\karma.conf.js --browsers=PhantomJS
`

Gruntfile:
`    grunt.registerTask('test', [
        'karma:single'
    ]);
`

For now I moved back to version 1.5.0.  I would be happy to give more output or files if it is helpful to this thread.

**Comment by dalidovski** [comment]
@ralberts  Did you find a way to fix this issue ?

**Comment by dalidovski** [comment]
I was excluding all *.spec.ts files in tsconfig.json.

> "exclude": [ "node_modules", "wwwroot", "typings/browser", "typings/main", "typings/browser.d.ts", "typings/main.d.ts", "dist", "/*.spec.ts"** ...

It has to be like :

> "exclude": [ "node_modules", "wwwroot", "typings/browser", "typings/main", "typings/browser.d.ts", "typings/main.d.ts", "dist" ], "files": [ "test.ts" ], "include": [ "/.spec.ts", "/.d.ts" ]...
