### ISSUE TITLE
Release notes missing

### ISSUE THREAD

**Issue by thany** [karma-runner/karma#2654]
Release notes for 1.6 are [missing](http://karma-runner.github.io/1.0/about/changelog.html).

I was hoping to find a note that explains any [breaking changes](https://github.com/karma-runner/karma/issues/2652).

**Comment by maksimr** [comment]
@thany you can look at [CHANGELOG](https://github.com/karma-runner/karma/blob/master/CHANGELOG.md#160-2017-04-05)

Thanks
