### ISSUE TITLE
Karma tests are failing due to a warning from React Test Utils

### ISSUE THREAD

**Issue by GeorgeLolos** [karma-runner/karma#2655]
### Expected behaviour
Karma tests should run flawlessly
### Actual behaviour
Karma tests are failing
### Environment Details

```
10 04 2017 16:50:54.496:INFO [karma]: Karma v1.6.0 server started at http://0.0.0.0:9876/
10 04 2017 16:50:54.500:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
10 04 2017 16:50:54.511:INFO [launcher]: Starting browser PhantomJS
10 04 2017 16:50:55.608:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket Xgavd4UdxYtoWbtnAAAA with id 99001992
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR: 'Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.'
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  Error: Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.
  at client/index-tests.js:55

Finished in 0.762 secs / 0 secs @ 16:50:56 GMT+0200 (CEST)
```

### Steps to reproduce the behaviour

1. Update to react@1.15.1 and react-dom@1.15.1
2. Run your Karma tests
3. Watch it fail

**Comment by maksimr** [comment]
@GeorgeLolos could you create sample project which reproduces the problem?

Thanks

**Comment by wesleycho** [comment]
My suspicion is this is due to the fact that the user is using a development build of React, and not a production one for running tests. The culprit is likely https://github.com/facebook/fbjs/blob/e66ba20ad5be433eb54423f2b097d829324d9de6/packages/fbjs/src/__forks__/warning.js#L36 .

This does not appear to be a karma bug though.

**Comment by GeorgeLolos** [comment]
Hi @maksimr there's a github repo that you can test that has almost the same result https://github.com/justinwoo/react-karma-webpack-testing/

@wesleycho React at 15.4 introduced this warning and karma has been handling it as an error. It's not a development build. The guys from enzyme have solved it here https://github.com/airbnb/enzyme/issues/875

To all the people that use Karma out there and have the same problem, you can just replace your
```
import TestUtils from 'react-addons-test-utils';
```
with
```
import TestUtils from 'react-dom/lib/ReactTestUtils'
```

Be aware though that your shallow renderer has been moved as well.

**Comment by wesleycho** [comment]
@GeorgeLolos the reason it is an error is almost certainly because of the line I linked. This is not a karma problem.

**Comment by GeorgeLolos** [comment]
@wesleycho I see, then there's no way to use Karma with React anymore without overriding the __DEV__ global variable. Good job.

**Comment by GeorgeLolos** [comment]
@wesleycho Thanks for looking into it :)
