### ISSUE TITLE
Error: spawn babel-node ENOENT #105

### ISSUE THREAD

**Issue by pavel06081991** [karma-runner/karma#2656]
I'm not sure where this issue comes from, I've created it in cross-env repository(https://github.com/kentcdodds/cross-env/issues/105)
Maybe it is related to karma, here is my karma config file, hope you can help me:

```
import settings from './settings';
import webpackAppTestConfig from './webpack/testing/app.config';

const {
  PATHS,
} = settings;

export default (config) => {
  config.set({
    basePath: PATHS.rootDir,
    browsers: ['Chrome'],
    singleRun: true,
    frameworks: [
      'mocha',
      'chai',
      'sinon',
    ],
    files: [
      'tests/unit/tests.js',
    ],
    plugins: [
      'karma-chrome-launcher',
      'karma-mocha',
      'karma-chai',
      'karma-sinon',
      'karma-sourcemap-loader',
      'karma-webpack',
      'karma-coverage',
    ],
    preprocessors: {
      'tests/unit/tests.js': [
        'webpack',
        'sourcemap',
      ],
    },
    reporters: [
      'progress',
      'coverage',
    ],
    webpack: webpackAppTestConfig,
    coverageReporter: {
      type: 'html',
      dir: PATHS.unitTestCoverageDir,
    },
  });
};

```

**Comment by maksimr** [comment]
This error

> Error: spawn babel-node ENOENT
    at notFoundError (D:\work\my_projects\react-starter\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (D:\work\my_projects\react-starter\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (D:\work\my_projects\react-starter\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

Does not related to the karma so my suggestion look at *react-starter*

Thank
