### ISSUE TITLE
PhantomJS crashing on Windows Bash

### ISSUE THREAD

**Issue by rafaelubal** [karma-runner/karma#2659]
Hi all,

Running unit tests on Karma + PhantomJS is crashing on Windows Bash, most likely due to a missing feature in Windows Bash itself, probably in a socket-related system call. The issue has been reported here:

https://github.com/Microsoft/BashOnWindows/issues/903#issuecomment-293376190

It is manifested as a Segfault on PhantomJS. We're trying to find a way to run PhantomJS under GDB, in order to obtain a stack trace at the moment the segfault occurs, since we haven't been able to reproduce the issue other than through the combined execution of Karma + PhantomJS. Would anybody be able to provide some advice here?

Thank you!

**Comment by Florian-R** [comment]
I dont know enough GDB, so this is maybe a stupid idea, but what about tweaking the command that Karma use to launch Phantom. I mean by modifying manually karma-phantomjs-launcher [here](https://github.com/karma-runner/karma-phantomjs-launcher/blob/eb0ca03d1938ed7b18da572284d3d52e2c1b70c9/index.js#L104), either directly in your `node_modules` or with a linked copy.

**Comment by mbland** [comment]
FYI, I'm reasonably sure the source of the crash is [the lack of nonblocking `connect()` support in WSL causing a low-level QT error when using WebSockets](https://github.com/Microsoft/BashOnWindows/issues/903#issuecomment-306066510).

**Comment by EzraBrooks** [comment]
According to the issue you linked, this was an issue in Windows, not Karma. It appears to have been fixed in the Fall Creator's Update.
