### ISSUE TITLE
Complete browser log output when process isn't started

### ISSUE THREAD

**Issue by LoveIsGrief** [karma-runner/karma#2663]
I was working on litixsoft/karma-detect-browsers#22 and travis isn't able to start Chromium successfully ([logs](https://travis-ci.org/LoveIsGrief/karma-detect-browsers/jobs/222597188)).

![lamb sauce1](https://cloud.githubusercontent.com/assets/2829538/25073317/2b6acf96-22e4-11e7-9d8b-534a3fb2e5c3.png)

The process exits "successfully", yet too early and I have no idea why. I cannot recreate it locally and am lacking the logs to investigate. So this is just a feature request to help debugging.

### Expected behaviour

Logs as to why the process exited

### Actual behaviour

No logs

### Environment Details

- Karma version (output of `karma --version`): taken from package.json `"karma": "^0.13.22"`
- **Relevant part of your `karma.config.js` file**  
I don't know what's relevant so here's the whole thing [karma.conf.js](https://github.com/LoveIsGrief/karma-detect-browsers/blob/karma-detect-browsers-22/demo/karma.conf.js)

### Steps to reproduce the behaviour

I'm not able to reproduce locally, but see the [travis logs](https://travis-ci.org/LoveIsGrief/karma-detect-browsers/jobs/222597188). I guess one could:

1. create an executable dummy script that simply outputs rubbish and exits with 0 
2. name the script `chromium-browser`
3. add the location of the script as the first element in `PATH`
4. `npm install -D karma-chrome-launcher`
5. Add karma-chrome-launcher to the karma.conf.js
6. launch karma with and watch it fail without logs

**Comment by wesleycho** [comment]
@dignifiedquire can this issue be closed? Looks like the referenced PR is merged.
