### ISSUE TITLE
usePolling should be false for newer macOS?

### ISSUE THREAD

**Issue by michaelsbradleyjr** [karma-runner/karma#2669]
See: https://github.com/karma-runner/karma/blob/master/lib/config.js#L318

tracking it back w/ blame:

https://github.com/karma-runner/karma/commit/66f50d7e584d4cbde820e70746be3f3378440fa8

https://github.com/karma-runner/karma/commit/66f50d7e584d4cbde820e70746be3f3378440fa8#commitcomment-21831412

On current macOS (I'm running 10.12.4, for example) setting `usePolling` to false works much better than having it set true, and the CPU utilization is dramatically lower. I'm running node v7.9.0, latest releases of karma, etc.

**Comment by wesleycho** [comment]
Thoughts on this @dignifiedquire? Sounds like it might be reasonable to change this and releasing a hotfix if it becomes an issue again.

**Comment by dignifiedquire** [comment]
I haven't tested it myself, but I am okay changing the default with `2.0`.
