### ISSUE TITLE
Karma is not able to run if any methods in `Array.prototype` are modified beforehand.

### ISSUE THREAD

**Issue by AndyRightNow** [karma-runner/karma#2671]
### Expected behaviour

Karma should be running.

### Actual behaviour

Not able to parse the paths given in the `config.files` and throw an error:

```javascript
ERROR [karma]: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.extname (path.js:887:5)
    at d:\Test\test-karma\node_modules\.1.6.0@karma\lib\middleware\karma.js:181:32
    at d:\Test\test-karma\node_modules\.1.6.0@karma\lib\middleware\common.js:117:36
    at d:\Test\test-karma\node_modules\.4.1.11@graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
```

### Environment Details

- Karma version (output of `karma --version`): `v1.6.0`
- Node.js version: `v7.9.0`
- Relevant part of your `karma.config.js` file
```javascript
module.exports = function (config) {
    config.set({
        browsers: ['PhantomJS'],
        files: [
            './test.js'
        ],
        singleRun: true,
        // coverage reporter generates the coverage
        reporters: ['progress'],
        plugins: [
            'karma-mocha',
            'karma-phantomjs-launcher'
        ]
    });
};
```

### Steps to reproduce the behaviour

Run this snippet of script:
```javascript
var Karma = require('karma').Server;
var path = require('path');

var fn = Array.prototype.indexOf;
delete Array.prototype['indexOf'];

Array.prototype['indexOf'] = function () {
    return fn.apply(this, arguments);
};

new Karma({
    configFile: path.resolve(__dirname, 'karma.conf.js')
}).start();
```

### Cause
At [this line](https://github.com/karma-runner/karma/blob/master/lib/middleware/karma.js#L177) in `lib/middleware/karma.js`:
```javascript
for (var i in files.included) 
```
`for...in` is used to traverse an array and this is a known bad practice. Maybe there is a particular reason for using it here?

**Comment by wesleycho** [comment]
Question - what are you trying to accomplish with modifying `indexOf`? The modification of the prototype method looks like a major code smell on first appearance.

There is a particular scenario that the `for-in` loop is accounting for I believe, so a solution is not as simple as replacing with `forEach`.

**Comment by AndyRightNow** [comment]
@wesleycho In fact, I totally agree with you but that was written by someone else and I wasn't able to modify that at the time.

I am more like trying to figure out why `for...in` is used instead of trying to "correct" it. If there are some situations to tackle using this expression, is there any chance of using something like `for...of` or `for (let i = 0; i < length; i++)` to replace this while having no errors in those particular situations and the problem mentioned above?

**Comment by wesleycho** [comment]
That will be possible when we start official work on 2.0 to remove node 0.10 and 0.12 support :) . We may be able to switch to `for..of` soon, just need the green light.

**Comment by wesleycho** [comment]
As for `for...in` - I'm not sure. We could certainly switch to a more traditional for loop here I guess.

**Comment by dignifiedquire** [comment]
I don't think there is a specific reason for using `for...in`, except that we don't want to rely on `.forEach` being present. So I suggest changing to `for (var i = 0; i < arr.length; i++)` which is still the safest way to iterate over arrays.
