### ISSUE TITLE
npm no longer supports Node.js <4, stop updating it to the latest there

### ISSUE THREAD

**Issue by mgol** [karma-runner/karma#2677]
### Expected behaviour
npm shouldn't be updated to a version not supported in a particular environment.

### Actual behaviour
npm gets updated to the latest version on all Node versions, including 0.10 & 0.12 which it no longer supports. This causes lots of warning messages and in some time it will most likely stop working:
https://travis-ci.org/karma-runner/karma/jobs/225953592

### Environment Details

- Karma version (output of `karma --version`): master
- Relevant part of your `karma.config.js` file: N/A

### Steps to reproduce the behaviour

1. Open https://travis-ci.org/karma-runner/karma/jobs/225953592
2. See warnings.
3.

**Comment by mgol** [comment]
When is it planned to drop support for Node.js <4 in Karma? That would solve this issue for now.

If that's not planned soon, we should perhaps:
1. Update npm to v3 in Node 0.10/0.12/4.
2. Not touch npm in newer Nodes. This means we'll get stronger coverage as we'll be testing on Node 3 & 4 and soon on v5 as well - which is what people use as most of them don't update the built-in npm version.

**Comment by dignifiedquire** [comment]
There is already a task open for that #2490. The main thing here is getting all modules ready for this for v2.0, which should include other breaking changes that we want to do.

**Comment by dignifiedquire** [comment]
See https://github.com/karma-runner/karma/milestone/9

**Comment by mgol** [comment]
I think we should update npm in Node 0.10/0.12/4 to npm@3 as that we know is officially supported and leave the other Nodes as they are. Then we'll only test on npm>=3 but where such npm is already available by default we'll use the included version. That's the version most people will use so I think that's preferable.

PR: #2715.
