### ISSUE TITLE
karma rxjs not working

### ISSUE THREAD

**Issue by bhawanaa** [karma-runner/karma#2680]
### Trying to test signalR client with jasmine-karma but getting lots of errors.

1.  If I include angular-mocks - I'm getting ' Accot read property of undefined'

2. After commenting it out getting lots of errors for rxjs/symbol/observable

### Chrome 58.0.3029 (Windows 7 0.0.0) ERROR
  Error: (SystemJS) module is not defined
        ReferenceError: module is not defined
            at eval (node_modules/rxjs/symbol/observable.js:20:
            at eval (<anonymous>)
            at Object.eval (app/shared/services/trade.service.j
        Evaluating node_modules/rxjs/symbol/observable.js
        Evaluating app/shared/services/trade.service.js
        Error loading app/shared/services/trade.service.js

### Environment Details

- Karma version (output of `karma --version`):
-  files: [

        'Scripts/*.js',

        'node_modules/angular/angular.js',

      //'node_modules/angular/angular.js',

          // Paths loaded via module imports:
          // Angular itself
          {pattern: 'node_modules/@angular/**/*.js', included: false, watched: false},
          {pattern: 'node_modules/@angular/**/*.js.map', included: false, watched: false},

        {pattern: 'node_modules/devextreme-angular/*.js', included: false, watched: false},

        {pattern: 'node_modules/devextreme-angular/**/*.js', included: false, watched: false},

        {pattern: 'node_modules/devextreme-angular/**/**/*.js', included: false, watched: false},

          { pattern: 'node_modules/rxjs/**/**/*.js', included: false, watched: false },
          { pattern: 'node_modules/rxjs/**/*.js', included: false, watched: false },
          { pattern: 'node_modules/rxjs/**/*.js.map', included: false, watched: false },

        {pattern: 'index.html',included:false, watched: false},

        {pattern: 'app/allTrades/all-trades.component.js', included: false, watched: false},

        {pattern: 'app/marketData/market-data.component.js', included: false, watched: false},

        {pattern: 'app/slideTreeMenu/slide-tree-menu.component.js', included: false, watched: false},

        {pattern: 'app/filteredTrades/filtered-trades.component.js', included: false, watched: false},

        {pattern: 'app/positions/positions.component.js', included: false, watched: false},

         {pattern: 'app/app.component.js', included: false, watched: false},

         {pattern: 'app/shared/services/trade.service.js', included: false, watched: false},

         {pattern: 'app/shared/models/dx/*.js', included: false, watched: false},

         {pattern: 'node_modules/devextreme/**/*.js', included: false, watched: false},

         {pattern: 'node_modules/devextreme/ui/pivot_grid/data_source.js', included: false, watched: false},

         {pattern: 'node_modules/jquery/dist/jquery.min.js', included: false, watched: false},

         {pattern: 'node_modules/devextreme/ui/accordion.js', included: false, watched: false},

         {pattern: 'node_modules/jszip/dist/jszip.min.js', included: false, watched: false},

         {pattern: 'app/app.module.js', included: false, watched: false},

         {pattern: 'app/Counter.js', included: false, watched: false},

          { pattern: 'systemjs.config.js', included: false, watched: false }, 
          'app/shared/services/trade.service.js',
          'app/shared/services/trade.service.spec.js'
    ],

    systemjs: {
        configFile:'systemjs.config.js'

    },

    // list of files / patterns to load in the browser

    // list of files to exclude
    exclude: [
      
    ],

    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {

        'app/example*.js': 'coverage',
        'test/unit/trade*.js' : 'browserify'

        
    },

**Comment by wesleycho** [comment]
This looks like an incomplete karma config - can you paste your full config?

**Comment by EzraBrooks** [comment]
No additional information in over six months. Closing.
