### ISSUE TITLE
browserify error

### ISSUE THREAD

**Issue by bhawanaa** [karma-runner/karma#2681]
Chrome 58.0.3029 (Windows 7 0.0.0) ERROR
  Uncaught Error: Cannot find module '../util/root'
  at C:/Users/BAGGAR~1/AppData/Local/Temp/90918cb8ed733bfe3627b234589ffcab.browserify:1

browserify on command line on that file works fine but it gives error while loading the file with karma with preprocessor set to 'browserify' for that file.

**Comment by wesleycho** [comment]
Can you give more information here about your karma config/setup?

**Comment by EzraBrooks** [comment]
No additional information since over six months ago. Closing.
