### ISSUE TITLE
Absolute path error when running 'ng test' karma@1.7.0 webpack@2.4.1

### ISSUE THREAD

**Issue by Ezeon** [karma-runner/karma#2696]
### Expected behaviour
No Webpack validation error shoud occur.

### Actual behaviour
Running 'ng test' fails with the error below. 'ng serve' and 'ng build' are fine. It seems that karma is triggering this issue due to wrong slashes in the path, I opened an issue to Webpack, and they responded with 'The slashes are incorrect'. The Webpack issue can be found here: https://github.com/webpack/webpack/issues/4832

Error:
07 05 2017 02:23:04.825:ERROR [preprocess]: Can not load "webpack"!
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.

configuration.context: The provided value "C:/dev/ndd" is not an absolute path!
at webpack (C:\dev\ndd\node_modules\webpack\lib\webpack.js:19:9)
at new Plugin (C:\dev\ndd\node_modules\karma-webpack\lib\karma-webpack.js:63:18)
at invoke (C:\dev\ndd\node_modules\di\lib\injector.js:75:15)
at Array.instantiate (C:\dev\ndd\node_modules\di\lib\injector.js:59:20)
at get (C:\dev\ndd\node_modules\di\lib\injector.js:48:43)
at C:\dev\ndd\node_modules\di\lib\injector.js:71:14
at Array.map (native)
at Array.invoke (C:\dev\ndd\node_modules\di\lib\injector.js:70:31)
at Injector.get (C:\dev\ndd\node_modules\di\lib\injector.js:48:43)
at instantiatePreprocessor (C:\dev\ndd\node_modules\karma\lib\preprocessor.js:55:20)
at C:\dev\ndd\node_modules\karma\lib\preprocessor.js:106:17
at Array.forEach (native)
at C:\dev\ndd\node_modules\karma\lib\preprocessor.js:103:27
at module.exports (C:\dev\ndd\node_modules\karma\node_modules\isbinaryfile\index.js:28:12)
at C:\dev\ndd\node_modules\karma\lib\preprocessor.js:84:7
at C:\dev\ndd\node_modules\graceful-fs\graceful-fs.js:78:16
at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
07 05 2017 02:23:04.839:WARN [karma]: No captured browser, open http://localhost:9876/
07 05 2017 02:23:04.852:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/
07 05 2017 02:23:04.853:INFO [launcher]: Launching browser Chrome with unlimited concurrency
07 05 2017 02:23:04.855:ERROR [karma]: Found 1 load error

If the current behavior is a bug, please provide the steps to reproduce.

### Environment Details

Windows 7
Git Bash
Node v6.9.4
NPM 4.5.0
Webpack 2.41
Angular 4.1.0
Karma 1.7.0

- Karma version (output of `karma --version`):
- Relevant part of your `karma.config.js` file

**Comment by maksimr** [comment]
@Ezeon 

The problem in webpack not in karma, look at webpack documentation about config
```
configuration.context: The provided value "C:/dev/ndd" is not an absolute path!
at webpack (C:\dev\ndd\node_modules\webpack\lib\webpack.js:19:9)
```
As you can see exception was thrown by webpack

Thanks

**Comment by Ezeon** [comment]
@maksimr 
Webpack throws an error because an invalid configuration object is passed to Webpack. This configuration object is being passed from _'karma-webpack.js'_. As I state in my post, I already an issue submitted to Webpack, and the response from Webpack is that the slashes is the wrong way. It should be '\' and not '/'. Somewhere, karma-webpack.js is picking up and sending an illegal path. Sorry for not making this more clear in my inital post.

As you can see in the error trace:
configuration.context: The provided value "C:/dev/ndd" is not an absolute path!
at webpack (C:\dev\ndd\node_modules\webpack\lib\webpack.js:19:9)
**at new Plugin (C:\dev\ndd\node_modules\karma-webpack\lib\karma-webpack.js:63:18)**

**Comment by Ezeon** [comment]
After a little digging in the code, I can confirm that the error is caused by Karma. In karma-webpack.js, webpack is called by the following line:
   _var compiler = webpack(webpackOptions);_
The issue is in the webpackOptions object passed by karma. The illegal path is in the webpackOptions.context property.

As a hack to get it working again until a permanent fix is in place, a simple string replacement works; changing '/' to '\\\\'. Just add the following code on the previous line:
   _webpackOptions.context = webpackOptions.context.replace(/[//]/g, "\\\\");_

**Comment by maksimr** [comment]
@Ezeon 

> In karma-webpack.js, webpack is called by the following line:
var compiler = webpack(webpackOptions);

Yup, it is still not karma issue, as you can see [karma-webpack](https://github.com/webpack-contrib/karma-webpack) supported by [webpack-contrib](https://github.com/webpack-contrib) team so feel free open issue there.

**Comment by Ezeon** [comment]
@maksimr  Sorry, my mistake. I though you were responsible for the 'webpack-karma' package as well. I'll take it up with the webpack-contrib team then. Thanks.

**Comment by willperring** [comment]
@Ezeon 

Did you open a ticket on webpack-karma for this, and did you get a response? I'm facing the same issue, but can't find a ticket for it.

**Comment by Ezeon** [comment]
@willperring 

Once I realized that the issue was with webpack-karma, I updated to the newest version of the package which resolved the problem for me. That's why I never open at ticket with the webpack-contrib team.

**Comment by willperring** [comment]
@Ezeon 

That's really helpful, thanks for the quick reply! :D
