### ISSUE TITLE
Cannot use SCSS files in karma config

### ISSUE THREAD

**Issue by tyschreiver** [karma-runner/karma#2700]
### Expected behaviour
Should be able to import an SCSS style sheet in the files section just like CSS

### Actual behaviour
Karma does not recognize SCSS and gives the following error: 

Chrome 55.0.2883 (Linux 0.0.0) ERROR
  Uncaught SyntaxError: Unexpected token {
  at http://localhost:9879src/app/styles.scss:1

### Environment Details
(from package.json, karma --version didn't work)
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",

- Relevant part of your `karma.config.js` file

    files: [
			{ pattern: './src/app/styles.scss'},
                        { pattern: './src/test.ts', watched: false },
			'./node_modules/bootstrap/dist/css/bootstrap.min.css',
			'./node_modules/jquery/dist/jquery.min.js',
			'./node_modules/bootstrap/dist/js/bootstrap.min.js',
    ],	

### Steps to reproduce the behaviour

1. add scss file to files array
2. run ng test

**Comment by istibekesi** [comment]
Installing 'karma-scss-prepocessor' solved it for me, also included the scss files during karma test.
https://stackoverflow.com/a/44498689/3612124

**Comment by EzraBrooks** [comment]
The above comment is the solution; Karma itself is not meant to do your stylesheet preprocessing. This issue should be closed.

**Comment by EzraBrooks** [comment]
Closing as, by definition, Sass is a preprocessor. Please see [karma-scss-preprocessor](https://www.npmjs.com/package/karma-scss-preprocessor) to compile SCSS before Karma tests.
