### ISSUE TITLE
Docs: Broken link in old docs

### ISSUE THREAD

**Issue by Sibiraj-S** [karma-runner/karma#2720]
In your old docs.

 http://karma-runner.github.io/0.8/plus/RequireJS.html. 

there is a notification mentioning a link to the new documentation. but the link is not working it redirects to the old doc only.

**Comment by Sibiraj-S** [comment]
closing this issue, as #43

**Comment by megamindbrian** [comment]
Same thing I said!

I don't know how the version bar is controlled but the docs use https://pages.github.com/

https://github.com/karma-runner/karma/issues/2738

**Comment by Sibiraj-S** [comment]
@megamindbrian. The website is hosted here https://github.com/karma-runner/karma-runner.github.com

**Comment by megamindbrian** [comment]
Done.

https://github.com/karma-runner/karma-runner.github.com/pull/45
