### ISSUE TITLE
Browserstack api access has been removed

### ISSUE THREAD

**Issue by wesleycho** [karma-runner/karma#2725]
Here is an example of a recent CI failure where the API usage fails: https://travis-ci.org/karma-runner/karma/jobs/234152709

All builds are guaranteed to fail in Travis currently due to this issue.

This looks like Browserstack needs to be contacted and some credentials may need to be updated.

@dignifiedquire I think this task may also be in your realm.

**Comment by dignifiedquire** [comment]
Sorry for the delay, will take a look

**Comment by dignifiedquire** [comment]
Updated the credentials, lets hope it works
