### ISSUE TITLE
Older documentation messaging points to wrong version

### ISSUE THREAD

**Issue by megamindbrian** [karma-runner/karma#2738]
When the older documentation says I'm using the wrong version, it should probably point to the right version like the link highlights:
Heads Up! You're viewing the docs for v0.8, an old version of Karma. v1.0 is the newest.
v1.0 is the newest links back to the same 0.8 page that I am on.  Should point to the new 1.0 API.  Maybe we need a karma test-case for this?

**Comment by EzraBrooks** [comment]
This appears to have been fixed in a PR in the website repository.
