### ISSUE TITLE
Documentation is poor

### ISSUE THREAD

**Issue by megamindbrian** [karma-runner/karma#2743]
Has anyone considered splitting this page up in to something more digestible?

https://angular.io/docs/ts/latest/guide/testing.html

**Comment by chrisdothtml** [comment]
You've linked to the Angular docs website. You would need to make this issue in [the repo for angular.io](https://github.com/angular/angular.io) instead (that particular page is [here](https://github.com/angular/angular.io/blob/master/public/docs/ts/latest/guide/testing.jade))

**Comment by z-vr** [comment]
The documentation for plugin development is pretty much non-existent and only based on examples :(

**Comment by megamindbrian** [comment]
If I am expected to write unit tests, there should be an entire category
for "Testing", not a one page link inside the "features" section.  Pretty
amazed that Google being such a big company cares so little, but like Chris
said, that's a different repo.  They do have to work together since Angular
depends on Karma for testing and karma has a specific set of "customers"
for each framework.  Just my $.02.

**Comment by EzraBrooks** [comment]
Karma is a test runner, not a unit testing framework. Angular and Jasmine's documentation are the most relevant to your question, and neither are run by the Karma team.
