### ISSUE TITLE
Awful docs, support for Angular 2

### ISSUE THREAD

**Issue by shcallaway** [karma-runner/karma#2745]
What's the deal? 

The only information about Angular on the Karma website is [this lousy page](http://karma-runner.github.io/1.0/plus/angularjs.html), which references an out-dated blog post and an equally useless scaffolding generator. From here, you might — just might — figure out how to configure Karma for Angular, but there's no telling what the two are capable of together, thanks to the lack of documentation.

The best information on Karma and Angular is from [the Angular docs](https://angular.io/guide/testing). It introduces the `karma-test-shim`, a work-around that's necessary because Karma won't play nicely otherwise. 

Why doesn't Karma have more support for Angular 2, one of the most popular JS web frameworks?

**Comment by aressler38** [comment]
Because angular sucks and so does this issue. Let them handle the framework specific docs.

**Comment by shcallaway** [comment]
You're right my tone was really off in this issue. I apologize for that. I think I was just frustrated.

But considering Karma was written by a member of the Angular team _for_ Angular, I think it should handle the framework specific docs, in this case. Some select quotes from the thesis:

> That said, I assume huge part of Karma users to be AngularJS developers. AngularJS has become very popular recently and we recommend Karma as “the test runner”.

>  I feel confident to use it everyday and it significantly improved my daily workflow. The
whole AngularJS team has been successfully using it as well - both for local development
and on the CI server.

> Without AngularJS, Karma would never have happened.

**Comment by EzraBrooks** [comment]
Support for Angular in Karma is provided by a plugin, not Karma itself. This isn't within the scope of this repository. I would advise using the Angular CLI's Karma integration.
