### ISSUE TITLE
Not able to create spy on method

### ISSUE THREAD

**Issue by tak2ashokkumar** [karma-runner/karma#2751]
My service is : 

      var testappserviceone = angular.module('testappserviceonemodule',[])
        testappserviceone.factory('testappServiceone',[ function(){
        return function (x,y) {

             function addobj (x,y){
                 return x+y;
             }

             return{
                add:addobj
             }
        }
       }]);

 My test suite is : 

    describe('testappserviceone add method functionality', function(){
        beforeEach(function () {
            spyOn(testappServiceone(10,15),'add').and.callThrough();
        });

        it('testappServiceone add method functionality', function() {
            testappServiceone(10,15).add();
            expect(testappServiceone(10,15).add).toHaveBeenCalled();
        });
    });

The Exception I am getting is : 

    Error: <toHaveBeenCalled> : Expected a spy, but got Function.
    Usage: expect(<spyObj>).toHaveBeenCalled()

I think spy() is not creating a spy object . Please help me in understanding and solving this problem.

**Comment by maksimr** [comment]
Every time when you evaluate this expression/call function it returns new object with new function in property add
```
testappServiceone(10,15) // -> Object A
testappServiceone(10,15) // -> Object A'
// A !== A'
```

In your case you should write something like this

```
var foo = testappServiceone(10,15);
spyOn(foo, 'add');
foo.add()

expect(foo.add).toHaveBeenCalled()
```

**Comment by tak2ashokkumar** [comment]
Thank you for proposing solution.
