### ISSUE TITLE
TravisCI is failing on node <6

### ISSUE THREAD

**Issue by naganowl** [karma-runner/karma#2753]
### Expected behaviour
https://github.com/karma-runner/karma/pull/2752 and https://github.com/karma-runner/karma/pull/2747 only pass Travis for node 6.

### Actual behaviour
They should pass on npm 6

### Environment Details
The PRs are failing on validation of the commit message on older versions of npm, but succeeds on npm 6. The error message it outputs is

```
0.77s$ npm run init
0.09s$ if [ "$VALIDATE_COMMIT_MSG" == "true" ]; then npm run travis; else ./scripts/validate-commit-msg.sh $TRAVIS_COMMIT; fi
INVALID COMMIT MSG: does not match "<type>(<scope>): <subject>" !
/home/travis/build/karma-runner/karma/.git/COMMIT_EDITMSG
The command "if [ "$VALIDATE_COMMIT_MSG" == "true" ]; then npm run travis; else ./scripts/validate-commit-msg.sh $TRAVIS_COMMIT; fi" failed and exited with 1 during .
```

### Steps to reproduce the behaviour

1. https://travis-ci.org/karma-runner/karma/jobs/248146863
2. https://travis-ci.org/karma-runner/karma/builds/244545086

**Comment by chrahunt** [comment]
The validation is not succeeding on 6, it is just not being done (since `$VALIDATE_COMMIT_MSG` is set to `true`).
