### ISSUE TITLE
Node 8 Support

### ISSUE THREAD

**Issue by joerideg** [karma-runner/karma#2754]
### Expected behaviour
I can install and run karma using Node 8
### Actual behaviour
Karma will fail to install because engine support has not included Node 8 yet.

Hi,
First of all thanks for your hard work on this great open source project.

Could you guys please add support for Node 8, and/or give us a timeline for when this change will be released to the public.

**Comment by shaiksphere** [comment]
Is there an update on this one? This is blocking the usage of `karma` on the Node 8 based projects of ours.

The pull request has been sitting idle since June 29.

**Comment by joerideg** [comment]
It seems the pull request fixing this has been merged. Awesome work guys!

**Comment by shaiksphere** [comment]
Great (thumbsup)

Any idea when the `1.7.1` will be released containing the fix?

**Comment by cletusw** [comment]
@shaiksphere 1.7.1 has just been released with this fix in #2818 !

**Comment by shaiksphere** [comment]
Thank you @cletusw. This issue will pop up again in a few months when Node 9.x will be released. Will there be a better solution to make sure it doesn't break again every 6 months or so?
