### ISSUE TITLE
FEATURE: Is it possible to run 2000 test cases less than a minute?

### ISSUE THREAD

**Issue by krischandra** [karma-runner/karma#2783]
### Expected behaviour
Run 2000 test cases less than a minute
### Actual behaviour
running 2000 test cases in 3 minutes
### Environment Details
angular 4, TS
- Karma version (output of `karma --version`):
- Relevant part of your `karma.config.js` file

**Comment by maksimr** [comment]
If short - **Yes**

There are many factors which can affect your tests performance (Code quality, CPU, Browser).
First of all, you should profile your code and try to find [bottleneck](https://en.wikipedia.org/wiki/Bottleneck) after that you should experiment with your environment.

In our project, we have around 3000 tests and they took around 40 seconds[*] but we use angular@1.x and babel@x

I recommend watching Vojta presentation where he describes some common bottlenecks in **unit tests**
https://www.youtube.com/watch?v=5mHjJ4xf_K0 

Thanks

[*]
<img width="1024" alt="karma-tests" src="https://user-images.githubusercontent.com/616193/28502129-5fdafa50-6ff4-11e7-8120-178820c9cfc7.png">

**Comment by krischandra** [comment]
Can you share me your karma.config,js setup so that i can go through that. I am now to this. 
Thanks.

**Comment by krischandra** [comment]
Do i need to add any plugins or something to make it fast? If so please give me some basic idea.
Thanks

**Comment by maksimr** [comment]
@krischandra 

> Can you share me your karma.config,js setup so that i can go through that

We have a standard karma config nothing special so I think it does not help you

```js
  config.set({
    frameworks: ['jasmine', 'phantomjs-shim'],
    files: [{
      pattern: 'test/unit/test-bundle.webpack.js',
      watched: false
    }],

    plugins: [
      'karma-*',
      {
        'reporter:inline-jasmine-seed': ['type', function(baseReporterDecorator) {...}]
      }
    ],

    preprocessors: [
      'test/unit/test-bundle.webpack.js'
    ].reduce(function(preprocessors, fileMask) {
      preprocessors[fileMask] = ['webpack'];
      return preprocessors;
    }, {}),

    webpack: webpackConf,
    webpackServer: webpackConf.devServer,

    client: {
      jasmine: {
        random: true
      }
    },

    browsers: ['PhantomJS']
  });
};
``` 

```json
    "karma": "1.3.0",
    "karma-cli": "0.0.4",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-diff-reporter": "0.6.3",
    "karma-phantomjs-launcher": "1.0.1",
    "karma-phantomjs-shim": "1.1.2",
    "karma-teamcity-reporter": "0.2.2",
    "karma-webpack-with-fast-source-maps": "1.10.1",
```

> Do i need to add any plugins or something to make it fast? If so please give me some basic idea.

We don't use special plugins and as I already wrote in my previous comment "Profile your code and try to find bottleneck" and watch the suggested video. 

IMHO:
I think the better place to ask such questions is stackoverflow.com because your problem does not relate to the karma core functionality.

Thanks
