### ISSUE TITLE
version 1.7.0 is not compatible with ie8

### ISSUE THREAD

**Issue by bvarga** [karma-runner/karma#2787]
### Expected behaviour

connecting to ie8 browsers

### Actual behaviour

won't connect, time outs.

### Environment Details

- Karma version (output of `karma --version`):
Karma version: 1.7.0
- Relevant part of your `karma.config.js` file

### Steps to reproduce the behaviour

1. https://github.com/browserstack/karma-browserstack-example.git
2. update package.json to karma version 1.7.0 & karma-browserstack-launcher to 1.3.0
3. npm install
4. add ie8 to the karma config, something like this:

```
ie8: {
        base: 'BrowserStack',
        browser: 'IE',
        browser_version: '8.0',
        os: 'Windows',
        os_version: '7',
      },

```
5. npm test

If we update socket.io dependency in node_modules/karma to 2.0.3 it works.

now it's using socket.io 1.7.3

maybe https://github.com/socketio/engine.io/issues/407 is connected.

**Comment by xuexb** [comment]
+1

**Comment by kerdany** [comment]
+1

**Comment by EzraBrooks** [comment]
This issue is fixed on master, socket.io has been upgraded to 2.0.3.
