### ISSUE TITLE
Using Angular4 AOT...Stil we are not getting much benefit in initial page load execution

### ISSUE THREAD

**Issue by vijayKumar2017** [karma-runner/karma#2796]
### Expected behaviour
Using Ahead of Time compilation, Initial page load should be reduced

### Actual behaviour
Still it is taking 3 to 5 seconds to start execution after page loading

### Environment Details
Angular 4.1.2
angular-cli: "1.0.0-beta.28.3"

Could you please help us out.

**Comment by kubal5003** [comment]
I'm not in any way related to Karma, but just try getting in their shoes. You're referring to some test suites that only you have, not providing any details, you did not give any measurements on what is taking so long, you did not provide any reproduction steps not to mention any JSFiddle or anything.

**Comment by EzraBrooks** [comment]
Karma is included by Angular, but is not responsible for Angular's performance. If you can provide reproduction steps that prove that this is the fault of the test runner itself, please reopen.
