### ISSUE TITLE
Karma version not updated with socket.io dep update

### ISSUE THREAD

**Issue by guilhermejcgois** [karma-runner/karma#2798]
### Expected behaviour
With the merge #2744, the patch version was incremented, and `npm install karma` retrieve karma with updated socket.io package version (1.7.4).

### Actual behaviour
Patch version of karma steals on 1.7.0. When doing `npm install karma` the socket.io merge steals the previous (1.7.3)

### Environment Details

- Karma version (output of `karma --version`): 1.7.0
- Relevant part of your `karma.config.js` file (not relevant)

### Steps to reproduce the behaviour

```
npm install karma
less node_modules/karma/package.json | grep socket.io
# "socket.io": "1.7.3",
```

**Comment by guilhermejcgois** [comment]
When running karma, I'm getting the error mentioned in  #2593.

**Comment by kevinsalter** [comment]
Looks related to #2777 as well

**Comment by EzraBrooks** [comment]
This is a major issue. My project can't run _any_ of our unit tests.

**Comment by skylarjhdownes** [comment]
https://github.com/karma-runner/karma/pull/2880 ought to fix this issue.

**Comment by EzraBrooks** [comment]
A fresh install still yields the same error.

**Comment by EzraBrooks** [comment]
Karma@1.7.1 on npm appears to be corrupt. Once it has been fixed, this issue should be as well. Please forward discussion to #2827.
