### ISSUE TITLE
Angular2/4: calling function directly from component instance does not change component property

### ISSUE THREAD

**Issue by jay-shi** [karma-runner/karma#2801]
## Problem description

This happens during unit testing a angular2/4 function.  The testing framework is Jasmine on a Karma Runner. FunctionA is a trivial function, and all it does is changing the properties of a angular component object. I instantiated the object component by using `var component = Testbed.componentInstance()`. When I call functionA via `component.functionA()` and spy on it. It turns out functionA indeed was called but it did not change the properties of component. For example, if functionA suppose to change propertyA  of the component object ( `functionA(){ this.propertyA = true; }`), `this.propertyA` does not change if I call functionA is called via `component.functionA()` in a spec. However, if I call the function from a different way, it will change the property. See the code for more details.

## Detailed Code
**Component:**

    export class LoginComponent{
   
      constructor(private loginService: LoginService){}; 
   
      noUsername: boolean= false; 
      noPassword: boolean= false; 
    
      setStarFlag(id:boolean, pw:boolean){
          this.noUsername = id;
          this.noPassword = pw;
      }

    }

**Unit test:**

    var fixture: ComponentFixture<LoginComponent>,
        component: LoginComponent,
        loginService: LoginService, 
        loginServiceStub: LoginServiceStub;
    
    describe('LoginComponent', () => {

    beforeEach(async(() => {

        //set up testing environment
        TestBed.configureTestingModule({

            declarations: [LoginComponent],

            providers: [
                        { provide: HttpModule, useValue: true }, 
                        { provide: Http, useValue: true }, 
                        { provide: Router, useValue: true },
                       ] 

        }).overrideComponent(LoginComponent, {
            set: {
                //override original service with a stub one
                providers: [
                    { provide: LoginService, useClass: LoginServiceStub},
                    { provide: ActivatedRoute, useValue: { params: Observable.of({resumePath: 'testpath'})} }
                ]
            }
        }).compileComponents().then(() => {
            
            fixture = TestBed.createComponent(LoginComponent); //end testbed config & create fixture that provides access to component instance itself

            component = fixture.componentInstance; //getting component itself

            loginService = fixture.debugElement.injector.get(LoginService); 
            
        });

    }));

    describe('function setStarFlag', ()=>{

        it('set the flag to the right values', ()=>{

            spyOn(component, 'setStarFlag');

            component.setStarFlag(true, false);

            expect(component.noUsername).toBeTruthy(); //this doesnt work
            expect(component.noPassword).toBeFalsy();  //this doesnt work
        })
    });

The problem is that if i directly call the function `setStarFlag` using `component.setStarFlag(true, false)`, the function `setStarFlag` cannot change the property `noUsername` and `noPassword` of component itself. 

But lets say if I trigger the function by simulating a button click, the property `noUsername` and `noPassword` will change. 

**HTML file:**

    <button (click)="setStarFlag(true, false)"></button>

**Unit test:**

    let btn = fixture.debugElement.query(By.css('button'));
    btn.triggerEventHandler('click', null);
    
    expect(component.noUsername).toBeTruthy(); //this works 
    expect(component.noPassword).toBeFalsy(); // this works

## Environment Details
angular/cli: 1.0.4
node: 6.10.3
os: win32 x64
angular/common: 4.1.3
angular/compiler: 4.1.3
angular/core: 4.1.3
angular/forms: 4.1.3
angular/http: 4.1.3
angular/platform-browser: 4.1.3
angular/platform-browser-dynamic: 4.1.3
angular/router: 4.1.3
angular/cli: 1.0.4
angular/compiler-cli: 4.1.3
karma: 0.13
karma.conf.js: 
```
module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular/cli'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular/cli/plugins/karma')
    ],
    client:{
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    files: [
      { pattern: './src/test.ts', watched: false }
    ],
    preprocessors: {
      './src/test.ts': ['@angular/cli']
    },
    mime: {
      'text/x-typescript': ['ts','tsx']
    },
    coverageIstanbulReporter: {
      reports: [ 'html', 'lcovonly' ],
      fixWebpackSourcePaths: true
    },
    angularCli: {
      environment: 'dev'
    },
    reporters: config.angularCli && config.angularCli.codeCoverage
              ? ['progress', 'coverage-istanbul']
              : ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false
  });
};
```

**Comment by guilhermejcgois** [comment]
Do u try to call `fixture.detectChanges();` after calling the function directely?

**Comment by jay-shi** [comment]
@guilhermejcgois  I did. I console logged the component both before and after I called the function and `fixture.detectChanges()`, the two logs are the same. That being said, the component did not get affected by the function somehow.

**Comment by jay-shi** [comment]
More information:

I used debug mode and inserted some testing code on the original function. Turns out Jasmine did not call the actual function albeit spy says so.

**Comment by jay-shi** [comment]
@guilhermejcgois After inserting a few testing code, I finally found where the problem is.

Somehow `spyOn(component, 'functionA')` alter funtionA into another function for the purpose of spy. If I get rid of `spyOn`, my function works perfectly! 
To people that encountered the same problem, please use two separate specs to test the functions. One for if the function is being called, the other is for if the functionality of such function.

**Comment by Francis-Leigh** [comment]
Due to the Lexical binding nature of fat arrow functions, it may be that your context is being lost through those... i have read before that using fat arrows with testing frameworks can be problematic. Try exchanging your fat arrows for `function() {...}` and see if that works.

**Comment by ChaitanyaPuritipati** [comment]
Hi
