### ISSUE TITLE
NODE_PATH solution doesn't seem to work

### ISSUE THREAD

**Issue by ORESoftware** [karma-runner/karma#2803]
### Expected behaviour

set NODE_PATH, and I can use global karma npm version

### Actual behaviour

set NODE_PATH, and I **cannot** use global karma npm version

### Environment Details

```console
$ karma --version
Cannot find local Karma!
  Please install Karma by `npm install karma --save-dev`.
  If you wanna use a global instance, please set NODE_PATH env variable.
```

if I use this:

```bash
export NODE_PATH="${NODE_PATH}:$(npm root -g)"
karma $@
```

then I get:

```console
Cannot find local Karma!
  Please install karma by `npm install karma --save-dev`.
```

(without the NODE_PATH warning, but still doesn't work).

**Comment by EzraBrooks** [comment]
Are you still experiencing this issue?

**Comment by ORESoftware** [comment]
I don't remember, but it was probably operator error, will close thanks!
