### ISSUE TITLE
Support question - I only can get tests to run in "debug" mode...

### ISSUE THREAD

**Issue by ORESoftware** [karma-runner/karma#2805]
### Expected behaviour

Browser launches, tests will run. (using `karma start`).

### Actual behaviour

The tests only run if I click on the debug button in the browser, and the "test results" only show up in the browser console. I tried several different reporters (progress and spec).

I am on MacOS.

Just to be clear, I have to click the debug button here, in order to get any output at all:

<img width="868" alt="screenshot 2017-08-08 16 39 05" src="https://user-images.githubusercontent.com/11139560/29099674-b11b2192-7c5b-11e7-885e-e3fadce82d5c.png">

Hopefully that's enough information, thanks

**Comment by EzraBrooks** [comment]
Are you still experiencing this problem?

**Comment by ORESoftware** [comment]
thanks I think we figured this one out

**Comment by mbajambit** [comment]
@ORESoftware 
> thanks I think we figured this one out

Could you please share your findings? I'm struggling with the same issue.

**Comment by beatrichartz** [comment]
Use `--single-run` when you `karma start` to do a single run.
