### ISSUE TITLE
One failing test causes other async tests to fail in the Karma DEBUG RUNNER

### ISSUE THREAD

**Issue by daanstolp** [karma-runner/karma#2811]
Consider the following tests (in Jasmine), where the first is synchronous and the second is asynchronous:

```
describe("The system", function() {
    
    it("should fail", function() {
        expect(true).toBe(false);
    });

    it("should succeed", function(done) {
        setTimeout(function() {
            expect(1).toBe(1);
            done();
        }, 10);
    });
});
```

### Expected behaviour
- When I run the tests in the default runner, I expect the first test to fail and the second test to pass.
- When I run the tests in the Karma DEBUG RUNNER, I expect the first test to fail and the second test to pass.

### Actual behaviour
- When I run the tests in the default runner, the first test fails and the second test passes, as expected.
- When I run the tests in the Karma DEBUG RUNNER, **both** tests fail. The error message for the second test is the same failure message that caused the first test to fail:

```
Uncaught Expected true to be false.
    at UserContext.<anonymous> (http://localhost:9876/base/test.spec.js:4:22) thrown
```

### Environment Details

- Karma version (output of `karma --version`): 1.7.0
- `karma.config.js` file is default out of the box, configured to load '*.js' files.

### Steps to reproduce the behaviour

1. Create a new application using `npm init`
2. `npm install karma karma-jasmine jasmine-core karma-chrome-launcher --save-dev`
3. Create a new file called `test.spec.js` and add the test code that is listed above.
4. Run `karma init` and accept all defaults. Enter `*.js` and `*.spec.js` as files location.
5. Add `"test": "karma start"` to the package.json `scripts` section.
6. run `npm run test`
7. Click the `Debug` button to open the Karma DEBUG RUNNER.
8. In the console of Google Chrome, you can now see the error messages.

**Comment by michael-letcher** [comment]
@daanstolp I think this has resurfaced. Using Angular CLI (karam ^2.0.4).

If a tests throws an error, the next test will fail. Running the tests in isolation will return a success.

**Comment by ovitrif** [comment]
@michael-letcher I'm encountering this with such code:

```
spyOn(service, 'uploadFile').and.returnValue(throwError(Error()));
```

If I test in isolation, it works, if I run all tests, the second one fails.
Also, if I use `DoneFn` and I call it, the test including the spyOn fails

**Comment by Prinsn** [comment]
I don't have an isolation of this (currently isolating cause), but this is happening for me as part of other tests.  have 46/46 passing specs, and if I run them via `ng test` it's 46/46 passing, but if I run it in headless chrome, non-failiing errors propogate to fail other tests.
