### ISSUE TITLE
running npm test => karma start throws "sh: replaced: command not found"

### ISSUE THREAD

**Issue by dewwwald** [karma-runner/karma#2814]
Not sure how to go about solving this issue, any advice? 

### Expected behaviour
It should just work. Replaced node_module replaced can't be found even after I installed it first locally and then globally (installation has its own error)

### Actual behaviour
Successfully runs the tests but then throws this error:
```
sh: replaced: command not found
npm ERR! Test failed.  See above for more details.
```
### Environment Details
- Mac Osx 
- v6.9.1
- Karma version: 1.7.0
- I don't think the config file is relevant

**Comment by dewwwald** [comment]
I am an idiot! Sorry. 

This is a non issue. It was my package json file post test.

**Comment by EzraBrooks** [comment]
Since you resolved the issue, can you close this?

**Comment by dewwwald** [comment]
@EzraBrooks thanks. Will remember next time.
