### ISSUE TITLE
Release Karma 1.7.1 with Node 8 support

### ISSUE THREAD

**Issue by alecf** [karma-runner/karma#2818]
Now that #2754 is fixed, someone needs to release a new version of karma that has node 8 support specified.

**Comment by cletusw** [comment]
@dignifiedquire Can we get this release for Node 8 support? Thanks.

**Comment by dignifiedquire** [comment]
we currently have some breaking changes on `master` which will require some careful testing before I can release them, which I didn't found time for yet sorry

**Comment by cletusw** [comment]
Okay.

**Comment by cletusw** [comment]
@dignifiedquire Would you accept a branch with just 1.7.0 and the node 8 commit? That way it could just be released as 1.7.1 without the changes in master.

**Comment by cletusw** [comment]
@dignifiedquire In case you agree, I've created a `1.x` branch on my fork that is simply `1.7.0` plus the node 8 change. If you'd like, you can create that branch in the main repo, run `npm version patch`, update the changelog, and use `npm publish` to publish *that* branch as 1.7.1

https://github.com/cletusw/karma/tree/1.x

**Comment by dignifiedquire** [comment]
Thanks @cletusw that is probably something we can do. I will check it out later today.

**Comment by nicksrandall** [comment]
@cletusw, you're always one step ahead of me.

**Comment by cletusw** [comment]
@nicksrandall Lol. As a workaround, you can `npm install --force karma` and then `npm install`.

**Comment by dignifiedquire** [comment]
Published from https://github.com/karma-runner/karma/tree/1.7.1 which includes only that change

**Comment by cletusw** [comment]
Thanks!
