### ISSUE TITLE
Karma slows down over multiple runs causing timeouts

### ISSUE THREAD

**Issue by Ghirigoro** [karma-runner/karma#2823]
### Expected behaviour
Every run of the tests should exhibit (roughly) the same performance.

### Actual behaviour
Tests take increasingly longer causing them to start timing out. E.g. The first run all tests are averaging less than 2 seconds, a few minutes later tests are taking 4 seconds or more to complete. Eventually an increasing amount of tests time out.
The increase in time is not constant (e.g. one run may take 3 seconds, the next 2.5 seconds and the next 3.3), but on average the run time increases.

### Environment Details
OS: MacOS 10.12.6
Node: 8.3.0
Karma: 1.7.1 
Karma Typescript: 3.0.5
Karma Chrome Launcher: 2.2.0
Karma Mocha: 1.3.0
Karma Chai: 0.1.0
Chai: 4.1.1
Mocha: 3.5.0

### Steps to reproduce the behaviour
- Run the tests
- Wait and run the tests again a few times (without restarting the Karma server)

### Notes
- I'm using Headless Chrome as the only browser, but I've experienced the problem with Safari and Chrome as well
- I'm testing a websocket-based library. Almost all the tests require a websocket-server running locally and are asynchronous. 
- I've tried resetting my websocket server between test runs and there was no improvement.
- I'm using `mocha` and `chai` and promises for all the async tests. 
- I was using the `ws` library originally but there were conflicts with the version used by Karma's socket-io so I switched to `uws`
- This is an existing project (that has been used in production) which I'm transitioning to use Karma. I've never experienced these performance degradations before. That doesn't rule out a problem in my code but makes me think it less likely.

**Comment by makeros** [comment]
Hi @Ghirigoro 
I have a similar setup like yours. I see the same but also I'm using chrome and firefox and after few reloads firefox is disconnecting. Did you tried with ff? Or can you maybe try to see if you will experience the same problem?

**Comment by Ghirigoro** [comment]
Just tried it with Firefox and I also get disconnected. It will run the tests (very slowly) once and then the second run it starts hanging on a lot of tests and disconnects.

**Comment by EzraBrooks** [comment]
I think it might help to diagnose the issue if you could post some profile results (CPU, RAM usage, etc) across multiple runs here.

**Comment by Ghirigoro** [comment]
It's been a couple of months since I ran these tests and the issue seems to be resolved. Here's what a few runs came out to:


Run # | Max CPU % | Total Test Time
-- | -- | --
1 | 19.4 | 2.816
2 | 22 | 2.818
3 | 15.9 | 2.810
4 | 20.9 | 2.810
5 | 12.7 | 2.815
6 | 16.8 | 2.832
7 | 31.8 | 2.837
8 | 17.5 | 2.823
9 | 18.7 | 2.826
10 | 20.4 | 2.834
11 | 30.35 | 2.820
12 | 14.2 | 2.820
13 | 22.3 | 2.813
14 | 16.9 | 2.832

Not sure what changed in the intervening time (nothing was updated on the project as far as I know), but maybe a Chrome update fixed the issue I was having (I don't know about the Firefox issue @makeros was referring to).
