### ISSUE TITLE
Provide clarity in upgrade path

### ISSUE THREAD

**Issue by benjaminapetersen** [karma-runner/karma#2828]
I am currently working on updating an old toolchain, karma version `0.12.23` to `1.7.0` (or any fairly current version).  I'm using the latest `karma-chrome-launcher` @ `2.0.0` and `karma-firefox-laucher` at `1.0.0` both before and after the upgrade.  The problem is that after updating karma, the browsers stall out & communication fails.  There is no other change, and its not clear what is causing the problem.  The best error I get is:

```
13 09 2017 10:32:32.513:WARN [launcher]: Firefox have not captured in 60000 ms, killing.
13 09 2017 10:32:32.542:DEBUG [launcher]: Process Firefox exited with code 0
13 09 2017 10:32:32.543:DEBUG [temp-dir]: Cleaning temp dir /var/folders/bh/12345/T/karma-12345
13 09 2017 10:32:32.575:ERROR [launcher]: Firefox failed 2 times (timeout). Giving up.
13 09 2017 10:32:32.576:DEBUG [karma]: Run complete, exiting.
13 09 2017 10:32:32.576:DEBUG [launcher]: Disconnecting all browsers
Warning: Task "karma:unit" failed. Use --force to continue.
```
I'm working through the Changelog to see if there is anything that might provide a clue, but I'm skeptical this will be a productive route.  

Any suggestions?
Thanks!

**Comment by benjaminapetersen** [comment]
For those who might find this, so far I've found the best method is to delete your config file & start over 😄

**Comment by EzraBrooks** [comment]
If you'd like to contribute a guide on updating from early versions to more recent ones, I'd be happy to review a pull request if you can put one together from your experience upgrading (comparing your config files via git, etc)

**Comment by devoto13** [comment]
I think this issue is pretty obsolete by now, so I'm going to close it.

But feel free to open a new issue providing a minimal reproduction if you still experience issues with upgrading Karma to a newer version.
