### ISSUE TITLE
Unable to pass --user-data-dir flag into Chrome when opening browser

### ISSUE THREAD

**Issue by ohansrud** [karma-runner/karma#2835]
### Expected behaviour

Expect a directory to be written to C:\chrome-dev-profile when browser is opened. 
Expect devtools settings to be stored for next run, so it will automatically open in full screen undocked. 

### Actual behaviour

Directory not written, settings are not stored. 

### Environment Details
- Windows 10
- Karma 1.1.1
- Node 8.5.0

Karma custom browser config.

```
customLaunchers: {
    Chrome_DevTools: {
        base: 'Chrome',
        flags: ['--user-data-dir=C:\chrome-dev-profile --auto-open-devtools-for-tabs']
    }
}
```

### Steps to reproduce the behaviour

1. Run Karma with settings above.
2. Undock devtools 
3. Close Karma task
4. Rerun same Karma task.

**Comment by EzraBrooks** [comment]
Have you tried separating the flags like so?
```
customLaunchers: {
    Chrome_DevTools: {
        base: 'Chrome',
        flags: ['--user-data-dir=C:\chrome-dev-profile', '--auto-open-devtools-for-tabs']
    }
}
```

**Comment by EzraBrooks** [comment]
I'm going to assume this issue is solved, due to lack of response. Please re-open if you haven't solved it or the above solution doesn't work.
