### ISSUE TITLE
Type error @types\karma\index.d.ts

### ISSUE THREAD

**Issue by omkadiri** [karma-runner/karma#2838]
Karma test failing to run Am getting error TS2694: Namespace '"/node_modules/log4js/index"' has no exported member 'AppenderConfigBase'.

I believe log4js depreciated @types/log4js  for https://github.com/nomiddlename/log4js-node definitions file.

Am not sure if this is the place to open this issue so feel free to close it.

- Karma version (output of `karma --version`):1.7.0 and @types\karma 1.7.0

**Comment by EzraBrooks** [comment]
According to the NPM registry, `@types/karma` appears to be maintained by DefinitelyTyped, not by the Karma team.

**Comment by johnjbarton** [comment]
Please reopen if you find more information.

**Comment by vincecampanale** [comment]
Resolved by upgrading `@types/karma` package.
