### ISSUE TITLE
Can't get existing angular app injector. 

### ISSUE THREAD

**Issue by DzmVasileusky** [karma-runner/karma#2839]
### Expected behaviour
Call `angular.element('body').injector()` should return injector of existing bootstrapped application.

### Actual behaviour
TypeError: undefined is not an object (evaluating 'injector.get')

### Environment Details

- Karma version (output of `karma --version`):
1.7.1

### Steps to reproduce the behaviour

1. Create angular.js app. 

2. Create ES6 class whose constructor function inject dependencies through angular.element('body').injector()

3. Create angular controller as a ES6 class and extend it with previously created common class.

4. Test controller initialization with karma.

**Comment by DzmVasileusky** [comment]
Found a workaround for the issue.
Add in your test the following:

```
beforeEach(function(){	
	...
	module(app); // app initialization

	// decorate angular.element with injector
	angular.mock.inject(function($injector){
		// save original
		var original = angular.element;

		// replace with our own
		angular.element = function() {
		// proxy all calls to the original
		var result = original.apply(this, arguments);

		// add the injector to the result
		result.injector = function() { return $injector; };
			return result;
		}

		// also add all the angular.element properties to our fake or some other stuff will break
		for (let prop in original) {
			angular.element[prop] = original[prop];
		}
	})
});
```

Notice that injector creation should be after app initialization.  
About injector mock:
https://docs.angularjs.org/api/ngMock/function/angular.mock.inject

**Comment by ScottTrenda** [comment]
FYI, this can be done _much_ more easily like this (assuming `module(app)` was previously called):
```
beforeEach(inject(function($injector) {
  // Return the mock injector from `.injector()` every time
  angular.element.fn.extend({ injector: function() { return $injector } });
});
```
