### ISSUE TITLE
Promises don't fail tests

### ISSUE THREAD

**Issue by megamindbrian** [karma-runner/karma#2848]
### Expected behaviour
Internal libraries that I have no control over sometimes use promises.  When those fail, it should fail the test case.

### Actual behaviour
All tests pass.

### Environment Details
Freshly made project using angular-cli ```ng new```.  Nothing special, using > 4.2.0

- Karma version (output of `karma --version`): ~1.7.0 from package.json
- Relevant part of your `karma.config.js` file

### Steps to reproduce the behaviour

0) extract zip file
1) run npm install
2) run npm run test
3) be amazed!  all tests pass because poor design makes developers lives harder?

Let's make this a game.  You tell me what's wrong with the code; assuming I already know the answer, and I'll send you $10 on whatever "beer-bucks" site of your choice.
[promisetest.zip](https://github.com/karma-runner/karma/files/1403576/promisetest.zip)

![screen shot 2017-10-20 at 4 21 05 pm](https://user-images.githubusercontent.com/25057134/31845143-bdf689a2-b5b2-11e7-8f77-fa43e442348e.png)

I am sure there is a valid reason behind this, I am just making the argument after using the platform for a year that this situation is misleading and nuanced.

**Comment by johnjbarton** [comment]
Looks like you are using the karma-jasmine framework and the jasmine test "BDD" test API.

I also guess that one or more functions in your test code return promises (based on the test description, you did not provide any code).  

You can read about the jasmine async testing here: https://jasmine.github.io/2.0/introduction.html#section-Asynchronous_Support
or a lot of other places.  

The short version, in general whenever your function returns a promise, return it. If you fail to return it then the entire test suite can exit before the promise resolves or rejects.

In addition you code does not have any "expect().toEqual()" calls so there is nothing to fail.  jasmine considers any test that has 0 expectation failures and 0 thrown exceptions as a pass.  

The jasmine spec reporter can be make to fail tests with 0 successful expectations.  You could open a bug on karma-jasmine for that aspect.

karma-runner is the bit of the system that coordinates the tests. So issues like this one, from jasmine, cannot be solved by karma-runner.

**Comment by johnjbarton** [comment]
Or sorry I didn't see the zip file.

**Comment by johnjbarton** [comment]
Yes, I think if you use 
`return app.shouldFail();`
the test should fail.

**Comment by johnjbarton** [comment]
And... by the way, I completely agree that your experience of a test that passes when it should not sucks.

**Comment by megamindbrian** [comment]
Interesting. You actually gave me a few more cases/styles to try. I was
just thinking the answer is async(() => { which does cause the test to fail
like we need.

I didn't know Jasmine was related. Should I file a bug there? Is there a
way to add an error if a promise rejection fails after the test completes?
It shows up in the console in the right order but I am not that familiar
with the codebase.



On Oct 20, 2017 4:52 PM, "johnjbarton" <notifications@github.com> wrote:

And... by the way, I completely agree that your experience of a test that
passes when it should not sucks.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/karma-runner/karma/issues/2848#issuecomment-338347099>,
or mute the thread

**Comment by johnjbarton** [comment]
There are two cases of false positive here:

1.  promise rejection in a sync test (did not return promise).
2. test fails to call expect().toMatch(), including expect();

The latest jasmine has afterAll trapping of unhandled promise rejections.  This can be captured by karma-jasmine and report a synthetic test cases that fails.

By counting both failed and success expectations we can fail tests with total 0. That avoids the second case.

Both of these would need to be done in the reporting phase of karma-jasmine. I have code like this built on top of karma-jasmine, maybe I will try to move it out.

**Comment by megamindbrian** [comment]
Woohoo!  Thank you :D

**Comment by megamindbrian** [comment]
In relation to false positive #1.
Here's a bit more context from the documentation:
https://angular.io/guide/router#component-less-route-grouping-routes-without-a-component

I noticed "return of Promise not used" popup in the de-linter.  This is a common pattern:
```
  checkLogin(url: string): boolean {
    if (this.authService.isLoggedIn) { return true; }

    // Store the attempted URL for redirecting
    this.authService.redirectUrl = url;

    // Navigate to the login page with extras
    this.router.navigate(['/login']);
    return false;
  }
```
