### ISSUE TITLE
Plugin development API docs - help requested

### ISSUE THREAD

**Issue by ORESoftware** [karma-runner/karma#2851]
re: the plugin development API docs

I am trying to write a framework plugin, like `karma-runner/karm-mocha` or karma-runner/karma-jasmine.

My current question is - 

Should the total number of specs be reported using:

`window.__karma__.info({total: x})`

or

`window.__karma__.complete({total:x})`

?

**Comment by johnjbarton** [comment]
Closing pre @ORESoftware
