### ISSUE TITLE
browser console logs miss vital information

### ISSUE THREAD

**Issue by rssfrncs** [karma-runner/karma#2854]
### Expected behaviour
Entire log object is logged by Karma
### Actual behaviour
An unhelpful empty object is logged
![image](https://user-images.githubusercontent.com/7808978/31987455-c9940aaa-b963-11e7-929e-8f030092b177.png)

### Environment Details

- Karma version 1.7.1
- `karma.config.js` file
![image](https://user-images.githubusercontent.com/7808978/31987493-e577fb78-b963-11e7-8e48-bcd713a0875a.png)

### Steps to reproduce the behaviour

1. Run tests
2. Observe browser error objects are empty

**Comment by johnjbarton** [comment]
If you post steps I can use to reproduce this I would look into it. Such steps would start
1. Install following https://karma-runner.github.io/latest/intro/installation.html
2. Add test file that fails and its config
3. Run <cmd here>
I know that creating a test file and config and verifying that your issue still occurs under these simple steps is a lot of work. But for me there is no alternative.
