### ISSUE TITLE
Question about implementation of Karma itself

### ISSUE THREAD

**Issue by ORESoftware** [karma-runner/karma#2860]
How does the Karma runner work with Webpack and Angular2.x, when it was originally designed to work with Angular1.x? How does Karma know when it's handling a Webpack-based project as opposed to an Angular1.x project?

My guess, is that when working with Angular2.0, that Karma generates a webpack config file dynamically? The user selects which tests to run, and those tests are added to the `entry` argument in the config (or at the command line)? Then Karma builds the project with webpack and sends it to the browser?

Is that correct? I am curious thanks

**Comment by EzraBrooks** [comment]
It appears to me that, at least when the Karma config comes from an Angular CLI project, it includes an Angular CLI plugin. That's probably where the configuration difference comes in.

**Comment by johnjbarton** [comment]
My guess is that karma does not know anything about angular.  But much more information is available in the documentation
http://karma-runner.github.io/1.0/plus/angularjs.html

**Comment by ORESoftware** [comment]
@johnjbarton  karma at the very least needs to know what .js files to run ... I think with Webpack based projects, you have a to run a build for the tests to run.

**Comment by johnjbarton** [comment]
Maybe the answer you want is: karma "knows" about angular (or webpack etc) only through builds steps or plugins set in configuration files.   karma does not deal with that stuff directly, it just runs tests in the browser.
