### ISSUE TITLE
Script launched from karma-script-launcher is not killed after tests.

### ISSUE THREAD

**Issue by jschwartzentruber** [karma-runner/karma#2861]
### Expected behaviour

Scripts launched with `karma-script-launcher` should be killed after tests are completed with `singleRun=true`

### Actual behaviour

Browser launched from `karma-script-launcher` is never killed. It opens properly but remains open after karma has disconnected and the log says `exited with code 0`.

Edited log from `./node_modules/karma/bin/karma start --log-level=debug` :

    $ ./node_modules/karma/bin/karma start --log-level debug
    27 10 2017 12:14:04.208:DEBUG [config]: Loading config /home/truber/src/m/bug/karma.conf.js
    27 10 2017 12:14:04.213:DEBUG [config]: autoWatch set to false, because of singleRun
    27 10 2017 12:14:04.214:DEBUG [plugin]: Loading plugin karma-mocha.
    27 10 2017 12:14:04.217:DEBUG [plugin]: Loading plugin karma-script-launcher.
    27 10 2017 12:14:04.228:DEBUG [web-server]: Instantiating middleware
    27 10 2017 12:14:04.269:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
    27 10 2017 12:14:04.270:INFO [launcher]: Launching browser ./scripts/run-web-ext-karma.sh with unlimited concurrency
    27 10 2017 12:14:04.275:INFO [launcher]: Starting browser ./scripts/run-web-ext-karma.sh
    27 10 2017 12:14:04.275:DEBUG [temp-dir]: Creating temp dir at /tmp/karma-95120481
    27 10 2017 12:14:04.276:DEBUG [launcher]: scripts/run-web-ext-karma.sh http://localhost:9876/?id=95120481
    27 10 2017 12:14:06.218:DEBUG [web-server]: serving: /home/truber/src/m/bug/node_modules/karma/static/client.html
    27 10 2017 12:14:06.314:DEBUG [web-server]: serving: /home/truber/src/m/bug/node_modules/karma/static/karma.js
    27 10 2017 12:14:06.365:DEBUG [karma]: A browser has connected on socket n8bwyjYDcfObVBiHAAAA
    27 10 2017 12:14:06.370:DEBUG [web-server]: upgrade /socket.io/?EIO=3&transport=websocket&sid=n8bwyjYDcfObVBiHAAAA
    27 10 2017 12:14:06.435:INFO [Firefox 58.0.0 (Linux 0.0.0)]: Connected on socket n8bwyjYDcfObVBiHAAAA with id 95120481
    27 10 2017 12:14:06.435:DEBUG [launcher]: ./scripts/run-web-ext-karma.sh (id 95120481) captured in 2.165 secs
    27 10 2017 12:14:06.468:DEBUG [middleware:karma]: custom files null null null
    27 10 2017 12:14:06.468:DEBUG [middleware:karma]: Serving static request /context.html
    27 10 2017 12:14:06.469:DEBUG [web-server]: serving: /home/truber/src/m/bug/node_modules/karma/static/context.html
    27 10 2017 12:14:06.482:DEBUG [middleware:source-files]: Requesting /base/node_modules/mocha/mocha.js?186ea2375e92d9e5c2a9d55ae910e732cf61a912 /
    27 10 2017 12:14:06.483:DEBUG [middleware:source-files]: Fetching /home/truber/src/m/bug/node_modules/mocha/mocha.js
    27 10 2017 12:14:06.483:DEBUG [middleware:source-files]: Requesting /base/node_modules/karma-mocha/lib/adapter.js?e8826109cf50b958ee4bd667517729ffdd4de363 /
    27 10 2017 12:14:06.483:DEBUG [middleware:source-files]: Fetching /home/truber/src/m/bug/node_modules/karma-mocha/lib/adapter.js
    27 10 2017 12:14:06.484:DEBUG [web-server]: serving (cached): /home/truber/src/m/bug/node_modules/mocha/mocha.js
    27 10 2017 12:14:06.488:DEBUG [web-server]: serving (cached): /home/truber/src/m/bug/node_modules/karma-mocha/lib/adapter.js
    27 10 2017 12:14:06.488:DEBUG [web-server]: serving: /home/truber/src/m/bug/node_modules/karma/static/context.js
    Firefox 58.0.0 (Linux 0.0.0): Executed 0 of 0 SUCCESS (0 secs / 0 secs)
    Firefox 58.0.0 (Linux 0.0.0): Executed 0 of 0 ERROR (0.001 secs / 0 secs)
    27 10 2017 12:14:06.627:DEBUG [karma]: Run complete, exiting.
    27 10 2017 12:14:06.627:DEBUG [launcher]: Disconnecting all browsers
    27 10 2017 12:14:06.629:DEBUG [launcher]: Process ./scripts/run-web-ext-karma.sh exited with code 0
    27 10 2017 12:14:06.629:DEBUG [temp-dir]: Cleaning temp dir /tmp/karma-95120481
    27 10 2017 12:14:06.631:DEBUG [launcher]: Finished all browsers
    27 10 2017 12:14:06.634:DEBUG [web-server]: serving (cached): /home/truber/src/m/bug/node_modules/karma/static/favicon.ico

### Environment Details

- Karma version:

      karma@1.7.1
      karma-mocha@1.3.0
      karma-script-launcher@1.0.0

- Relevant part of your `karma.conf.js` file

      module.exports = (config) => {
        config.set({
          singleRun: true,
          browsers: ['./scripts/run-web-ext-karma.sh'],
          frameworks: ['mocha'],
          plugins: [
            'karma-mocha',
            'karma-script-launcher'
          ]
        })
      }

### Steps to reproduce the behaviour

1. `npm init -y`
1. `npm install -D karma karma-script-launcher karma-mocha mocha web-ext`
1. `svn export https://github.com/mdn/webextensions-examples.git/trunk/borderify add-on`
1. Create `./scripts/scripts/run-web-ext-karma.sh` :

       #!/bin/sh -ex
       exec ./node_modules/web-ext/bin/web-ext -v --no-reload -s ./add-on run \
           --pref browser.bookmarks.restore_default_bookmarks=false \
           --pref browser.shell.checkDefaultBrowser=false \
           --pref browser.tabs.remote.autostart=false \
           --pref browser.tabs.remote.autostart.1=false \
           --pref browser.tabs.remote.autostart.2=false \
           --pref datareporting.policy.dataSubmissionEnabled=false \
           --pref dom.disable_open_during_load=false \
           --pref dom.max_script_run_time=0 \
           --pref dom.min_background_timeout_value=10 \
           --start-url "$@"

1. Create `./karma.conf.js` per above "Environment Details"
1. Run `./node_modules/karma/bin/karma start --log-level debug`
1. Tests should run and `karma` should exit, but script process remains.

**Comment by EzraBrooks** [comment]
This issue probably belongs on [karma-runner/karma-script-launcher](https://github.com/karma-runner/karma-script-launcher).
