### ISSUE TITLE
Document port collision scenario

### ISSUE THREAD

**Issue by reda-alaoui** [karma-runner/karma#2862]
### Expected behaviour

Ability to let karma select a random server port

### Actual behaviour

The server port have to be fixed before deployment.

### Environment Details

- Karma version (output of `karma --version`): 1.7.1

### Why

In a CI server, multiple karma instance could be running concurrently.
There is no way to predict which port will be available.
It would be nice to let karma automatically select a random available port.

### Absence of workaround

I wanted to implement this behaviour using https://github.com/sindresorhus/get-port. 
But since the library returns a promise of port, it seems that I have no way to pass it inside my synchronous `karma.conf.js`.

**Comment by EzraBrooks** [comment]
Looks like `server.js` already avoids port collisions, albeit in a primitive way. Are you experiencing port collisions regardless?
https://github.com/karma-runner/karma/blob/334f9fbe353f42d5232aeaf07d2ad1de075220d6/lib/server.js#L159-L167

**Comment by reda-alaoui** [comment]
I didn't experience any port colision but I didn't found any documentation or configuration about it, 
therefore I thought it was not implemented.

The description of the port attribute in https://karma-runner.github.io/1.0/config/configuration-file.html made me think the port selection was purely static.

Maybe some explanation should be added in this documentation?
