### ISSUE TITLE
Karma console.log or error work differently.

### ISSUE THREAD

**Issue by UniverseHan** [karma-runner/karma#2863]
### When 
```Javascript
it('should show error message in Error Object', () => {
  console.log(new Error('This should be displayed'));
});

```
### Expected behaviour
``` bash
LOG: Error: This should be displayed
    at <anonymous>:1:13
    ...
    ...
```
### Actual behaviour
```bash
LOG: TypeError{}
```

### Environment Details

- Karma version (output of `karma --version`):
    "karma": "^1.7.1",
    "karma-chrome-launcher": "^2.2.0",
    "karma-jasmine": "^1.1.0",

- Relevant part of your `karma.config.js` file

#### 1. Write code like below 
```Javascript
it('Error message should be displayed', function() {
  console.log(new Error('This should be displayed'));
});
```

#### 2. run karma test
``` bash
$ karma start
```

#### When you log in normal nodejs app
``` JavaScript
// shouldbe.js
console.log(new TypeError('This should be displayed'));
```

Got this.
```bash
TypeError: This should be displayed
    at Object.<anonymous> (/Users/haseok/workspace/karma-test/expected.js:1:75)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Function.Module.runMain (module.js:653:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by EzraBrooks** [comment]
Can you clarify why your "Actual behavior" section is blank? Does it not log the message at all?

**Comment by UniverseHan** [comment]
@EzraBrooks I have updated actual behaviour.

I think it caused by That karma use JSON.stringify in console.log wraper function. `JSON.stringify(new Error('...'))` does not display message in Error.

**Comment by macjohnny** [comment]
@UniverseHan can you retry with `2.0.0`? maybe this was resolved with https://github.com/karma-runner/karma/pull/2712 ?
