### ISSUE TITLE
Karma 1.7.1 does not contain #2817 (as mentioned in release notes)

### ISSUE THREAD

**Issue by juanca** [karma-runner/karma#2882]
### Expected behaviour

Installing `karma@1.7.1` in `static/debug.js` should contain :

```
setTimeout(function () {
  console.error(err);
});
```

This is the fix from #2817 which is mentioned in the [release notes](https://github.com/karma-runner/karma/releases/tag/1.7.1). 
 
### Actual behaviour

It still contains `karma@1.7.0` code:

```
setTimeout(function () {
  thow err;
});
```

### Environment Details

- Karma version (output of `karma --version`): 1.7.1
- Relevant part of your `karma.config.js` file: N/A

### Steps to reproduce the behaviour

1. `npm install karma@1.7.1`
2. `cat node_modules/karma/static/debug.js`

**Comment by juanca** [comment]
More information with screenshots @ https://github.com/karma-runner/karma/pull/2817

**Comment by EzraBrooks** [comment]
1.7.1's deployment on npm appears to be corrupt. Discussion at #2827.

**Comment by dignifiedquire** [comment]
The only 1.7.1 change is listed here: https://github.com/karma-runner/karma/blob/1.7.1/CHANGELOG.md#171-2017-08-30 sorry the releases pages is incorrect
