### ISSUE TITLE
setTimeout behaves differently than a promise, using $httpBackend.flush()

### ISSUE THREAD

**Issue by ORESoftware** [karma-runner/karma#2901]
Please see this SO question:
https://stackoverflow.com/questions/47645921

### Expected behaviour

I would expect the Promise code to work the same as the setTimeout code

### Actual behaviour

The code with setTimeout works, but the code with an intermediate Promise does not

### Environment Details
Karma version: 1.7.1

### Steps to reproduce the behaviour
Please see SO question for code.

**Comment by johnjbarton** [comment]
Asked on Stackoverflow.

**Comment by ORESoftware** [comment]
@johnjbarton don't have an answer on SO tho, do you have any idea why it's not working?

**Comment by johnjbarton** [comment]
Your problem is not related to karma AFAICT. My guess is that the issue is related to how flush() works and how jasmine works.   Angular has a lot of idiosyncratic issues; I suggest you ask someone with angular experience.

**Comment by ORESoftware** [comment]
yeah np, who can we spam next is the question
