### ISSUE TITLE
Error: Unexpected request: GET API_URL No more request expected

### ISSUE THREAD

**Issue by Atul-sac** [karma-runner/karma#2902]
### Expected behaviour

Error: Unexpected request: GET API_URL No more request expected should not be thrown while calling $scope.apply()

Error: Unexpected request: GET templates/*.html No more request expected should not be thrown while calling $httpBackend.flush()

### Actual behaviour

I am using $routeProvider and i have started facing same issue from 10 days back. same test cases were working before approx 10 days, but when i did fresh installation of all dependencies mentioned in package.json. my all test cases started failing which are dependent on $http service call and also which are based on $watch (basically where $apply() is called manually).
I am getting basically these two types of error -

1. Error: Unexpected request: GET templates/home.html No more request expected
2. Error: Unexpected request: GET API_URL No more request expected

### Environment Details

- Karma version (output of `karma --version`): Karma version: 0.13.3
- Relevant part of your `karma.config.js` file
Using Gruntfile.js. karma section is - 
```

karma: {
		  unit: {
			options: {
			  frameworks: ['browserify', 'jasmine'],
			  singleRun: false,
			  browsers: ['Chrome'],//'PhantomJS'
			  browserify: {
                    debug: true,
                    transform: [
                        istanbul({
                            ignore: [
                                "**/node_modules/**",
                                "**/unit_test/**"
                            ]
                        })
                    ]
                },
			  files: [
				'<%= test_dir %>/**/*.js'
			  ],
			  preprocessors : {
					'<%= test_dir %>/**/*.js': ['browserify'],
					'**/<%= js_dir %>/**/*.js': ['coverage'],
				},
				reporters : ['progress', 'coverage'],
				coverageReporter  : {
				  type : 'html',
				  dir : 'coverage/'
				}
			}
		  }
		}
```

It seems that few wrong commits has been made recently on KARMA/JASMINE, which are causing these issues, as mine old code base is working fine, only after installing fresh dependencies these test cases are failing now.

I am using below dependencies -
```

"devDependencies": {
"angular": "^1.6.5",
"angular-mocks": "^1.6.5",
"angular-route": "^1.6.5",
"browserify-istanbul": "^2.0.0",
"grunt": "^1.0.1",
"grunt-browserify": "^5.0.0",
"grunt-contrib-connect": "^1.0.2",
"grunt-contrib-copy": "^1.0.0",
"grunt-contrib-jshint": "^1.1.0",
"grunt-karma": "^2.0.0",
"istanbul": "^0.4.5",
"jasmine-core": "^2.6.4",
"karma": "^1.7.0",
"karma-bro": "^0.11.1",
"karma-browserify": "^5.1.1",
"karma-chrome-launcher": "^2.2.0",
"karma-coverage": "^1.1.1",
"karma-jasmine": "^1.1.0",
"karma-phantomjs-launcher": "^1.0.4"
}

```
### Steps to reproduce the behaviour
1. install new dependencies as mentioned above, your test cases will start failing.
2.
3.

**Comment by johnjbarton** [comment]
> Karma version (output of karma --version): Karma version: 0.13.3

The current version is 1.7.1.  Please update, re-install deps and try again.
