### ISSUE TITLE
Unsupported engine for karma@1.7.1

### ISSUE THREAD

**Issue by ayarushin** [karma-runner/karma#2906]
Hi all, I use `npm config set engine-strict true`, when I try to run npm install I catch next error:
```
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for karma@1.7.1: wanted: {"node":"0.10 || 0.12 || 4 || 5 || 6 || 7 || 8"} (current: {"node":"9.2.0","npm":"5.5.1"})
npm ERR! notsup Not compatible with your version of node/npm: karma@1.7.1
npm ERR! notsup Not compatible with your version of node/npm: karma@1.7.1
npm ERR! notsup Required: {"node":"0.10 || 0.12 || 4 || 5 || 6 || 7 || 8"}
npm ERR! notsup Actual:   {"npm":"5.5.1","node":"9.2.0"}
```
### Expected behaviour
npm install will be ok
### Actual behaviour
Crashed with error
### Environment Details
OS X high sierra, node 9.2.0 npm 5.5.1
- Karma version (output of `karma --version`): 1.7.1

### Steps to reproduce the behaviour

1. Add to package.json:
```json
  "engines": {
    "node": "9.2.0",
    "npm": "5.5.1"
  },
  "scripts": {
    "preinstall": "npm config set engine-strict true"
  },
```
2. Check that you use node 9.2.0 and npm 5.5.1
3. Run `npm install`

**Comment by johnjbarton** [comment]
The source is already upgraded, so this will be fixed in the next release.

**Comment by ayarushin** [comment]
@johnjbarton great, thanks!

**Comment by JatinGupta40** [comment]
Hello

**Comment by MHHJisan** [comment]
I am facing this issue for node v14.21.3 and npm v6.14.18
