### ISSUE TITLE
Running karma gets killed before starting anything

### ISSUE THREAD

**Issue by tleunen** [karma-runner/karma#2908]
I'm trying to run Karma inside a docker container and I can see that it's slower (but not only karma, everything is slower) in docker compared to my machine... Which is fine I guess. But the problem is that Karma gets killed before doing anything.

Here's my log when instantiating Karma via Gulp.
```
[01:12:46] Starting 'karma'...
Killed
npm ERR! Test failed.  See above for more details.
```

As you can see, there's not much. Even when enabling the logs in the karma config, I don't have anything else.

Do you know what I can do to find out what the issue is?

I have added this few params in my config to hopefully fix any timing issue but it doesn't change anything.
```
browserDisconnectTolerance: 3,
browserDisconnectTimeout: 80000000,
browserNoActivityTimeout: 80000000,
processKillTimeout: 80000000,
```

**Comment by johnjbarton** [comment]
Maybe check var/log/syslog:
 https://stackoverflow.com/questions/10876136/what-can-cause-node-js-to-print-killed-and-exit

**Comment by tleunen** [comment]
Looks like it was caused by a lack of memory for the container. Thanks!
