### ISSUE TITLE
On node 8, karma doesn't run and the process returns to terminal

### ISSUE THREAD

**Issue by tleunen** [karma-runner/karma#2909]
### Expected behaviour
Karma should run fine on Node 8+.

### Actual behaviour
Karma doesn't run and the process seems to be killed
```
~/dev/xxxxx
❯ npx gulp karma
[20:01:19] Failed to load external module @babel/register
[20:01:19] Requiring external module babel-register
[20:01:20] Using gulpfile ~/dev/xxx/gulpfile.babel.js
[20:01:20] Starting 'karma'...

~/dev/xxxxx
❯ 
```
So here, like 1 sec after displaying "Starting Karma", the process stops and returns to the terminal.. I don't know why and I open this ticket to see if anyone has an idea.

I believe I've already seen the issue (with karma or something else) in the past where a specific task didn't run at all but I can't find anything right now. I probably don't search the right terms...

The same karma config and same command work fine in Node 6

### Environment Details

- Karma version (output of `karma --version`): 1.7.1

**Comment by tleunen** [comment]
Finally found my issue. There were an issue in the webpack conf used by karma. Not sure why it was working for node 6 and not node 8 tho.

**Comment by internetchris** [comment]
This is old, but next time please describe what you did, and in the off-chance you remember!?
