### ISSUE TITLE
Document v2.0.0  breaking changes in CHANGELOG.md

### ISSUE THREAD

**Issue by apetro** [karma-runner/karma#2912]
### Expected behaviour

+ 2.0.0 release signifies breaking changes from v 1.x.
+ [Change log][CHANGELOG.md] clarifies just what those breaking changes are and what they mean for adopters.

### Actual behaviour

+ There's a 2.0.0 release
+ It has an entry in the [change log][CHANGELOG.md]
+ But it's not clear from the change log what the breaking change is and what it means for adopters.

### Steps to reproduce the behaviour

1. View the [change log][CHANGELOG.md]
2. Try to understand what breaking change led to the major version rev
3. Be frustrated.

[CHANGELOG.md]: https://github.com/karma-runner/karma/blob/master/CHANGELOG.md

**Comment by insin** [comment]
Guessing it's because Karma dropped support for Node.js 0.10 and 0.12.

**Comment by johnjbarton** [comment]
The changelog error has been fixed.

**Comment by apetro** [comment]
I don't think this issue wrt the 2.0.0 changelog entry has been addressed.

Reading [the changelog](https://github.com/karma-runner/karma/blob/master/CHANGELOG.md), looking at [the 2.0.0 release](https://github.com/karma-runner/karma/blob/master/CHANGELOG.md#200-2017-12-21), it still doesn't seem apparent what the breaking change was. Contrast the treatment in [the 3.0.0 release](https://github.com/karma-runner/karma/blob/master/CHANGELOG.md#300-2018-08-09), where breaking changes are called out thanks to #3109 .

**Comment by johnjbarton** [comment]
Please open a PR to fix the log if you like.

The breaking change was
https://github.com/karma-runner/karma/commit/ec92ea9
but it was not marked so in the description and thus the script did not emit the changelog entry.

In any case the supported version is 3.0.

**Comment by apetro** [comment]
It's a little odd that https://github.com/karma-runner/karma/commit/ec92ea9 is the breaking change yielding `2.0.0` when that change is also in `1.7.1`. Is this a matter of the `1.7.1` patch release inadvertently included a breaking change?
