### ISSUE TITLE
Adding browserify to the deps cause a huge cascade of new dependencies.

### ISSUE THREAD

**Issue by johnjbarton** [karma-runner/karma#2921]
### Expected behaviour
I can install karma 2.0
### Actual behaviour
So many new deps caused by browserify
### Environment Details

#2889 added browserify as a dep.  

### Steps to reproduce the behaviour

1.  install karma
2. OMG 
3.

**Comment by johnjbarton** [comment]
browserify seems to add around 75 new deps.  We review the code for every dep.  If this change is vital then ok, but a simpler alternative is available, we'd like to switch to it before adopting 2.x.

**Comment by benitogf** [comment]
Think that browserify is used on some core functionalities e.g in the [server](https://github.com/karma-runner/karma/pull/2889/files#diff-c945a46d13b34fcaff544d966cffcabaR30) I take your concern however as an entry to discuss log4js "optional" deps: https://github.com/log4js-node/log4js-node/blob/master/package.json#L64

    "hipchat-notifier": "^1.1.0",
    "loggly": "^1.1.0",
    "mailgun-js": "^0.7.0",
    "nodemailer": "^2.5.0",
    "redis": "^2.7.1",
    "slack-node": "~0.2.0",
    "axios": "^0.15.3",
    "amqplib": "^0.5.2"

Unlike what the name may suggest [optional deps](https://docs.npmjs.com/files/package.json#optionaldependencies) are installed every time.

haven't counted but I think that this adds more than 75, which are not needed nor used in the scope of this project 😟

**Comment by johnjbarton** [comment]
> browserify is used on some core functionalities

No, browserify is used to allow the use of the github repo in production without a build.  IMO that is inappropriate: the value of the use case does not justify the cost it imposes on all users.

**Comment by johnjbarton** [comment]
I think there are two other ways to solve issue #2884 rather than PR #2889.

The goal for #2884 is to allow the repo to be used directly without a build step. (I disagree with the premise, but here I want to concentrate on solutions that don't force everyone to use many more deps).

1. Attempt to read the static compiled file. If it exists, done. Else require('browserify'). Move the browserify dep to devDependencies.  Go back to shipping the static file in npm package.  install --production now has no deps on browserify.

or

2. Build the static file during npm test, commit the new built file with each PR.
