### ISSUE TITLE
Unable to build and test karma using source on Ubuntu 16.04

### ISSUE THREAD

**Issue by spurti-chopra** [karma-runner/karma#2924]
### Expected behaviour
Build and test via npm should be successful on Ubuntu 16.04 
### Actual behaviour
Build showing several warnings related to peer dependency
### Environment Details
Target Platform: Ubuntu 16.04 
Architecture: Intel (x86_64) and ppc64le
NPM version  v9.4.0

### Steps to reproduce the behaviour
Followed below steps on x86_64 ubuntu 16.04

$curl https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh| bash
$source ~/.nvm/nvm.sh
$nvm install stable
$nvm use stable
cloned karma repository
$ npm install
$ npm run init 
$ npm test

npm install shows following warning related to peer dependencies:
_npm WARN karma-browserify@5.1.3 requires a peer of karma@>=0.10.0 but none is installed. You must install peer dependencies yourself.
npm WARN karma-browserify@5.1.3 requires a peer of watchify@>=3 <4 but none is installed. You must install peer dependencies yourself.
npm WARN karma-browserstack-launcher@1.3.0 requires a peer of karma@>=0.9 but none is installed. You must install peer dependencies yourself.
npm WARN karma-chai@0.1.0 requires a peer of karma@>=0.10.9 but none is installed. You must install peer dependencies yourself.
npm WARN karma-coffee-preprocessor@1.0.1 requires a peer of karma@>=0.11.14 but none is installed. You must install peer dependencies yourself.
npm WARN karma-commonjs@1.0.0 requires a peer of karma@>=0.9 but none is installed. You must install peer dependencies yourself.
npm WARN karma-growl-reporter@1.0.0 requires a peer of karma@>=0.9 but none is installed. You must install peer dependencies yourself.
npm WARN karma-html2js-preprocessor@1.1.0 requires a peer of karma@>=0.9 but none is installed. You must install peer dependencies yourself.
npm WARN karma-jasmine@1.1.1 requires a peer of karma@* but none is installed. You must install peer dependencies yourself.
npm WARN karma-junit-reporter@1.2.0 requires a peer of karma@>=0.9 but none is installed. You must install peer dependencies yourself.
npm WARN karma-live-preprocessor@0.2.2 requires a peer of karma@>=0.10 but none is installed. You must install peer dependencies yourself.
npm WARN karma-mocha-reporter@2.2.5 requires a peer of karma@>=0.13 but none is installed. You must install peer dependencies yourself.
npm WARN karma-ng-scenario@1.0.0 requires a peer of karma@>=0.9 but none is installed. You must install peer dependencies yourself.
npm WARN karma-phantomjs-launcher@1.0.4 requires a peer of karma@>=0.9 but none is installed. You must install peer dependencies yourself.
npm WARN karma-requirejs@1.1.0 requires a peer of karma@>=0.9 but none is installed. You must install peer dependencies yourself.
npm WARN karma-script-launcher@1.0.0 requires a peer of karma@>=0.9 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):_

npm test failures are:
_488 passing (6s)
  4 failing

1) helper
       browserFullNameToShort
         should parse IE7:

      AssertionError: expected 'IE 7.0.0 (Windows Vista.0.0)' to equal 'IE 7.0.0 (Windows Vista 0.0.0)'
      + expected - actual

      -IE 7.0.0 (Windows Vista.0.0)
      +IE 7.0.0 (Windows Vista 0.0.0)
      
      at Context.it (test/unit/helper.spec.js:76:16)
  

  2) helper
       browserFullNameToShort
         should parse IE8:

      AssertionError: expected 'IE 8.0.0 (Windows 7.0.0)' to equal 'IE 8.0.0 (Windows 7 0.0.0)'
      + expected - actual

      -IE 8.0.0 (Windows 7.0.0)
      +IE 8.0.0 (Windows 7 0.0.0)
      
      at Context.it (test/unit/helper.spec.js:84:16)

  3) helper
       browserFullNameToShort
         should parse IE9:

      AssertionError: expected 'IE 9.0.0 (Windows 7.0.0)' to equal 'IE 9.0.0 (Windows 7 0.0.0)'
      + expected - actual

      -IE 9.0.0 (Windows 7.0.0)
      +IE 9.0.0 (Windows 7 0.0.0)
      
      at Context.it (test/unit/helper.spec.js:92:16)
  
  4) helper
       browserFullNameToShort
         should parse IE10:

      AssertionError: expected 'IE 10.0.0 (Windows 8.0.0)' to equal 'IE 10.0.0 (Windows 8 0.0.0)'
      + expected - actual

      -IE 10.0.0 (Windows 8.0.0)
      +IE 10.0.0 (Windows 8 0.0.0)
      
      at Context.it (test/unit/helper.spec.js:100:16)
  
Warning: Task "mochaTest:unit" failed. Use --force to continue.
Aborted due to warnings._

I am running this with default configurations. Please let me know if I am missing something.
Thanks !

**Comment by lusarz** [comment]
@spurti-chopra I think it's fixed with [this pr](https://github.com/karma-runner/karma/pull/2937).

**Comment by johnjbarton** [comment]
Please reopen if not fixed.
