### ISSUE TITLE
expect(false).toBeTruthy does NOT fail

### ISSUE THREAD

**Issue by CHBaker** [karma-runner/karma#2925]
### Expected behaviour
1) expect(false).toBeTruthy() ----> fail
2) expect(0).toEqual(1)          ----> fail

### Actual behaviour
1) expect(false).toBeTruthy() ----> success
2) expect(0).toEqual(1)          ----> success

### Environment Details

App: **Angular CLI,  Angular 5**

```
"jasmine-core": "~2.9.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.3.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
```

config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular/cli'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular/cli/plugins/karma')
    ],
    client:{
      clearContext: false, // leave Jasmine Spec Runner output visible in browser
      captureConsole: true
    },
    coverageIstanbulReporter: {
      reports: [ 'html', 'lcovonly' ],
      fixWebpackSourcePaths: true
    },
    angularCli: {
      environment: 'dev'
    },
    browserConsoleLogOptions: {
        level: '',
        format: '%b %T: %m',
        terminal: true
    },
    logLevel: config.LOG_LOG,
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false,
    captureTimeout: 240000,
    browserDisconnectTimeout : 10000,
    browserDisconnectTolerance : 1,
    browserNoActivityTimeout : 60000,
  });

### Steps to reproduce the behaviour

1. write failing test `expect(false).toBeTruthy()`
2. run test
3. see output as 'Success'

I'm not sure what is different about my code. I have karma running on another project and everything seems to be working great. I'm suddenly worried about all my other tests, they might be passing even if the test fails.

**Comment by CHBaker** [comment]
what do you mean?

**Comment by johnjbarton** [comment]
I mean: if your code fails to execute: `expect(false).toBeTruthy()` then it cannot fail.  For examples, the tests could be disabled, could have failed earlier etc. 

jasmine has comprehensive test so expect(false).toBeTruthy()  is very unlikely to pass if executed.

Did you try the debug window with chrome devtools?

**Comment by CHBaker** [comment]
Alright, I believe I wasn't using async with a done() function so my test was bleeding over and failing in another test, thank you

**Comment by johnjbarton** [comment]
Thanks for the update!

**Comment by etl722** [comment]
https://bob-dark-eyed.github.io/_-0s67R3nRz1UCpkeKmPfHAPBSd5l6rJBJY_xR2pq7wEPNsGEmLcytQ/ Look at the provided answer
