### ISSUE TITLE
Using Karma to test Gulp Tasks

### ISSUE THREAD

**Issue by branpar** [karma-runner/karma#2929]
Hello,

My company uses Gulp on the front-end for our build process. We also have code quality gates we must pass before a build can be completed, such as passing unit tests. We currently test using the Karma, Mocha, Sinon, Chai, Istanbul, and Webpack stack. Because our Gulp tasks are so critical I want to extent testing to them as well, writing unit tests for them.

I am running into a lot of problems and my research points to Karma/Webpack considering these modules for the Gulp tasks to be node, not browser, environment. Can anyone point me to a configuration for Karma that enables my testing for Gulp tasks?  (I totally understand this might not be the right project to post this in but I wanted to start here at our test runner first.)

Thanks in advance!

**Comment by johnjbarton** [comment]
gulp runs on nodejs, so unit tests for gulp would be unit test on nodejs: use mocha.  Karma-runner can' help you.
