### ISSUE TITLE
ERROR     at http://localhost:9876/_karma_webpack_/vendor.bundle.js:114339 

### ISSUE THREAD

**Issue by neridonk** [karma-runner/karma#2934]
### Expected behaviour
Should run tests

### Actual behaviour
when i have 190 tests jenkins can run anything fine, after 191 I get following error which says nothing to me

` Uncaught Response with status: 0  for URL: null at http://localhost:9876/_karma_webpack_/vendor.bundle.js:114339  `

### Environment Details

- Karma version (output of `karma --version`): 2.0.0
- Relevant part of your `karma.config.js` file

````
module.exports = function (config)
{
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular/cli'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular/cli/plugins/karma')
    ],
    client: {
      clearContext: false
    },
    files: [
      { pattern: './src/test.ts', watched: false }
    ],
    preprocessors: {
      './src/test.ts': ['@angular/cli'],
    },
    mime: {
      'text/x-typescript': ['ts', 'tsx']
    },
    coverageIstanbulReporter: {
      reports: ['html', 'lcovonly'],
      fixWebpackSourcePaths: true
    },

    angularCli: {
      environment: 'dev'
    },
```
    reporters: config.angularCli && config.angularCli.codeCoverage
      ? ['progress', 'coverage-istanbul']
      : ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
  
    browsers: ['Chrome_no_sandbox', 'Chrome'], customLaunchers: {
      Chrome_no_sandbox: {
        base: 'Chrome',
        flags: ['--no-sandbox'] // for running within Docker
      }
    },
    singleRun: false,
    colors: true
  });
};`

**Comment by blacknight811** [comment]
@neridonk did you figure this out? I have the same issue.

**Comment by bschwartz757** [comment]
@rawberg @neridonk I'm having a similar issue (tests error out with ```  {
    "message": "Script error.\nat :0:0",
    "str": "Script error.\nat :0:0"
  }``` after running a certain number of tests.) I'm trying to upgrade an AngularJS project with a large number of tests (a few thousand.) The previous setup using Browserify/karma-browserify/karma-jasmine with Karma 1.3 doesn't have this issue, however the new setup using Webpack/karma-webpack/karma-jasmine with Karma 2.0.2 does.

I'm not seeing a message like `http://localhost:9876/_karma_webpack_/vendor.bundle.js:114339`; any ideas on how to track down the offending file?

**Comment by AndrewEastwood** [comment]
same stuff

**Comment by dougludlow** [comment]
It appears as if karma-webpack doesn't report errors to the console as expected. In order to debug the `{ "message": "Script error.\nat :0:0", "str": "Script error.\nat :0:0" }` error, I have to set `singleRun` to false and use Chrome. When the browser opens, I have to click "Debug" and open the developer tools to see the error causing the issue in the console.

**Comment by HaydarAlaeddine** [comment]
did anyone solve this issue, i have the same problem with angular 6.

**Comment by johnjbarton** [comment]
Try the singleRun debugging suggestion. (This is not a karma-runner bug AFAICT)
