### ISSUE TITLE
timespan 2.3.0 vulnerability

### ISSUE THREAD

**Issue by billsmith5** [karma-runner/karma#2943]
### Expected behaviour
Passes security scan

### Actual behavior
Fails security scan, is block by company firewall

### Environment Details
I am using Anular CLI project
My company scans all dependencies for vulnerabilities using SonarQube. timespan 2.3.0 was blocked, so my builds fails

- Karma version (output of `karma --version`):
-- karma@2.0.0 / -- log4js@2.5.2 / -- loggly@1.1.1 / -- timespan@2.3.0

### Steps to reproduce the behavior
https://snyk.io/test/npm/karma/2.0.0?
.
Is there a fix for this?

**Comment by johnjbarton** [comment]
The downstream bug:
https://github.com/indexzero/TimeSpan.js/issues/10

**Comment by johnjbarton** [comment]
fixed in 3.0, log4js updated.
