### ISSUE TITLE
Karma always exit with exitcode 1 in windows

### ISSUE THREAD

**Issue by sn1ckers** [karma-runner/karma#2961]
### Expected behaviour
After successful test in windows it should exit with exitcode 0
### Actual behaviour
In windows I always get exitcode 1 
### Environment Details
This is a problem in Windows i'm running it in Windows 10. It works fine in unix environments

- Karma version (output of `karma --version`): tested in 1.3.0 and also 2.0.0
- Relevant part of your `karma.config.js` file

### Steps to reproduce the behaviour

1. create a karma.Server(config, callbackfunc);
2. Run some tests with the karma.runner.
3. stopping with karma.Stopper(config, callbackStop);

because in middleware stopper process.kill(process.pid, "SIGINT") get called and then windows is shutting down the process with errorcode 1 and not gracefully as in a unix environments. I tried to shut it down with kill.process(process.pid, 0) and that works fine, if I also in my callback calls process.exit(0).

Can I write my own stopper middleware as a plugin? Or should I try to fix it with a pull request?

**Comment by johnjbarton** [comment]
According the current source:
https://github.com/karma-runner/karma/blob/39d378d20dee61a88572225db9e1855da3adb346/lib/middleware/stopper.js#L9
`SIGINT` is called only if the server url says 'stop':
```js
if (request.url !== urlRoot + 'stop') return next()
```

Also: why step 1,  
> create a karma.Server(config, callbackfunc);
?

**Comment by sn1ckers** [comment]
This is what I have used.
https://karma-runner.github.io/2.0/dev/public-api.html

I need to stop the server otherwise my browser will hang and I need to finish without errors.

**Comment by johnjbarton** [comment]
I gather you are writing some nodejs code not using the normal command line?  If so you are responsible for the exit code.  Don't call the stopper, just exit with the code you want.

**Comment by sn1ckers** [comment]
Thanks for the support, I stopped using the stopper in windows and it worked fine, but in unix it was needed so i hade to fix it with a check on process.plattform. But now it works in both windows and unix.
