### ISSUE TITLE
Deprecated packages

### ISSUE THREAD

**Issue by asghol** [karma-runner/karma#2969]
### Expected behaviour
As few deprecations as possible without breaking patch version behaviour.

### Actual behaviour
12 deprecations listed on install.

### Environment Details

- Karma version (output of `karma --version`): 2.0.0

### Steps to reproduce the behaviour

1. Clone Karma repo
2. `npm install`

or if you already have the source go to latest 'master' or 'update-deps' branch and
1. `rm -rf node_modules` (if you have a local package-lock.json, delete it as well)
2. `npm install`

Deprecations will be listed quite early.

Below is a summary from the 'update-deps' branch.

#### Direct dependencies

- http2@3.3.7: Use the built-in module in node 9.0.0 or newer, instead
- qunitjs@2.4.1: 2.4.1 is the last version where QUnit will be published as 'qunitjs'. To receive future updates, you will need to change the package name to 'qunit'.
- validate-commit-msg@2.14.0: Check out CommitLint which provides the same functionality with a more user-focused experience.

#### Sub dependencies

- coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
- nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
- github@0.2.4: 'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)
- mailcomposer@4.0.1: This project is unmaintained
- socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
- node-uuid@1.4.8: Use uuid module instead
- buildmail@4.0.1: This project is unmaintained
- graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
- natives@1.1.3: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.

### Comments on some specific dependencies
- http2: This deprecation will not be possible to remove without excluding all environments running lower than node 9. We might need to add this as an optional dependency but we should also consider finding other approaches.

**Comment by kaiyoma** [comment]
I'm seeing a slightly different list upon a fresh install of 2.0.3:

```
warning karma > log4js > nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer
.com/status/
warning karma > log4js > loggly > request > node-uuid@1.4.8: Use uuid module instead
warning karma > socket.io > engine.io > engine.io-parser > has-binary2 > isarray@2.0.1: Just use Array.isArray directly
warning karma > socket.io > socket.io-parser > isarray@2.0.1: Just use Array.isArray directly
```

**Comment by huarse** [comment]
+1, 

karma 2.0.5 still dependence on `log4js@2.11`, and it dependence on `nodemailer@2.5.0` which has been deprecated.

**Comment by johnjbarton** [comment]
Please install v3.0 and update this issue.

**Comment by sinclairzx81** [comment]
Just following up on this issue. Noting that karma is indirectly taking a dependency on `circular-json` by way of `log4js@3.0.6`
```
npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted 
is its successor.
```
```
└─┬ karma@4.0.0
  └─┬ log4js@3.0.6
    └── circular-json@0.5.9 
```

**Comment by devoto13** [comment]
The latest `karma@5.0.4` does not depend on any deprecated packages, so closing this issue. Please open a new issue/submit a PR if another dependency gets deprecated.
