### ISSUE TITLE
singleRun property not working properly

### ISSUE THREAD

**Issue by rstor** [karma-runner/karma#2982]
Hi and sorry if this issue is misplaced or is not an issue of karma. Maybe it has something to do with the version of Angular being a RC?

### Expected behaviour
With property `singleRun =  false` Karma continues to run and Chrome browser stays open 
### Actual behaviour
Everything terminates with `singleRun = false`
### Environment Details
Windows 10
Angular 6.0.0-rc.5
Angular-cli 6.0.0-rc.4
In package.json:
    "jasmine-core": "~3.1.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^1.0.0",
- Karma version (output of `karma --version`): 2.0.0
- Relevant part of your `karma.config.js` file
module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular-devkit/build-angular/plugins/karma')
    ],
    client:{
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    coverageIstanbulReporter: {
      dir: require('path').join(__dirname, 'coverage'),
      reports: [ 'html', 'lcovonly' ],
      fixWebpackSourcePaths: true
    },
    angularCli: {
      environment: 'dev'
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_DEBUG,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false
  });
};
### Steps to reproduce the behaviour

1. Create a project with Angular 6.0.0-rc.5 with Angular cli 6.0.0-rc.4 with above karma and jasmine packages
2. Make sure everything builds and runs
3. Run `ng test`

**Comment by johnjbarton** [comment]
We use singlerun=false a lot also with chrome and see no problems. I think you will need to debug this issue in your environment.

**Comment by rstor** [comment]
Thanks @johnjbarton for the reply! actually this works fine: `ng test --watch`. It keeps the browser open. I will close this.
