### ISSUE TITLE
Code Coverage is not covered while writing spyon in test suites by using jasmine in karma

### ISSUE THREAD

**Issue by snspvd** [karma-runner/karma#2986]
Am facing with code coverage while writing spyon for methods.Please suggest me solution.

**Component.ts**
getProducts() {
return service.getproducts();
}
component.spec.ts
 spyOn(component, 'getProducts').and.callFake(() => {
});
 
Test suite passed but code coverage is failed as shown in  below image.
![image](https://user-images.githubusercontent.com/14179865/39626354-28a37598-4fbf-11e8-895a-230a578bab69.png)

**Comment by johnjbarton** [comment]
Delete this. You can't get coverage if you fake the code.
```js
spyOn(component, 'getProducts').and.callFake(() => {
});
```
