### ISSUE TITLE
Update in `core-js` to v2.5.6 breaks assertion `toEqual(jasmine.any(Promise))`

### ISSUE THREAD

**Issue by grisanu** [karma-runner/karma#2993]
Traced back to recent update of karma dependency `core-js` to `v2.5.6`. It looks like all karma versions depends on `"core-js": "^2.2.0",` which would include this `core-js` update.

### Expected behaviour
Note that `transferPlateContentsService.apiCallToTransferPlateContents` was declared with `async`

```
it('should return a Promise', () => {
      const RETURNED_RESULTS = transferPlateContentsService.apiCallToTransferPlateContents(API_DATA);
      expect(RETURNED_RESULTS).toEqual(jasmine.any(Promise)); // passes
    });
```
### Actual behaviour
<img width="1004" alt="screen shot 2018-05-09 at 14 27 25" src="https://user-images.githubusercontent.com/8594433/39841517-d8f7440c-5397-11e8-973e-a8149dd5db7d.png">

### Environment Details
- Karma version (output of `karma --version`): **0.13.22**

### Steps to reproduce the behaviour

1.
2.
3.

**Comment by johnjbarton** [comment]
> Karma version (output of karma --version): 0.13.22

Please update.

**Comment by grisanu** [comment]
Still fails with exact same error, I've updated to `v2.0.2`

**Comment by johnjbarton** [comment]
Sorry, the issue just does not have enough info to even guess. The test is not a karma-runner test. The expect() and jasmine.any() calls are jasmine.   I'm unsure how core-js is related to the test above, but I upgraded locally to core-js@2.5.6 and ran npm test: all pass.

**Comment by grisanu** [comment]
Sorry, you're right. It's got nothing to do with karma but actually with the `babel-core` dependency on `core-js`. Thanks! Sorry about that!
