### ISSUE TITLE
Better error message (than EACCES) for wrongly configured CHROME_BIN

### ISSUE THREAD

**Issue by szpak** [karma-runner/karma#3008]
### Expected behaviour

For `CHROME_BIN` set to a directory more meaningful error should be reported than `EACCES`:
> at Timer.listOnTimeout (timers.js:262:5) errno: 'EACCES', code: 'EACCES', syscall: 'spawn' }

It can be shared with some other launchers, so I create it here.

Motivation. For `CHROME_BIN` misconfigured to point to point a directory (e.g. a Chrome(mium) home directory) instead of a binary there is a stacktrace with `EACCES`. While at the OS level it is ok, there error is misleading as the search results suggest an [issue](https://github.com/karma-runner/karma/issues/483) with [sandbox and SUID](https://github.com/GoogleChrome/puppeteer/issues/807) or [SELinux](https://bugzilla.redhat.com/show_bug.cgi?id=730179). There could be a clear error that a directory is set instead of an executable binary.

I'm aware that that variable is named correctly, however in some other places/technologies that kind of variables often refers to a directory, not a particular binary. I know more than two other people who spent some time on resolving that "trival" problem.

### Actual behaviour

Somehow misleading `EACCES`
```
[INFO] 18 05 2018 16:05:41.928:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
[INFO] 18 05 2018 16:05:41.929:INFO [launcher]: Launching browser ChromeHeadless with unlimited concurrency
[INFO] 18 05 2018 16:05:41.934:INFO [launcher]: Starting browser ChromeHeadless
[INFO] 18 05 2018 16:05:41.954:ERROR [karma]: { Error: spawn EACCES
[INFO]     at _errnoException (util.js:1031:13)
[INFO]     at ChildProcess.spawn (internal/child_process.js:340:11)
[INFO]     at exports.spawn (child_process.js:499:9)
[INFO]     at spawnWithoutOutput (/home/foo/bar/node_modules/karma/lib/launchers/process.js:168:24)
[INFO]     at Object.ProcessLauncher._execCommand (/home/foo/bar/node_modules/karma/lib/launchers/process.js:76:21)
[INFO]     at Object.ProcessLauncher._start (/home/foo/bar/node_modules/karma/lib/launchers/process.js:33:10)
[INFO]     at Object.<anonymous> (/home/foo/bar/node_modules/karma/lib/launchers/process.js:19:10)
[INFO]     at Object.emit (events.js:164:20)
[INFO]     at Object.BaseLauncher.start (/home/foo/bar/node_modules/karma/lib/launchers/base.js:42:10)
[INFO]     at Object.j (/home/foo/bar/node_modules/karma/lib/launcher.js:116:17)
[INFO]     at Object.setTimeout.bind.j (/home/foo/bar/node_modules/qjobs/qjobs.js:143:18)
[INFO]     at ontimeout (timers.js:478:11)
[INFO]     at tryOnTimeout (timers.js:302:5)
[INFO]     at Timer.listOnTimeout (timers.js:262:5) errno: 'EACCES', code: 'EACCES', syscall: 'spawn' }
```

### Environment Details

- Karma version (output of `karma --version`): 1.7.1
- ~Relevant part of your `karma.config.js` file~

### Steps to reproduce the behaviour

1. Set `CHROME_BIN` to a Chrome(ium) home directory
2. Run UI tests

**Comment by johnjbarton** [comment]
Please open this issue with https://github.com/karma-runner/karma-chrome-launcher
