### ISSUE TITLE
EADDRINUSE error leads to improper port usage by server middleware

### ISSUE THREAD

**Issue by sergei-startsev** [karma-runner/karma#3011]
### Expected behaviour
If a port is changed in the passed configuration before server start (e.g. if `EADDRINUSE` is thrown for a specified port, the next available is used), it should be respected by server middleware.
### Actual behaviour
Middleware use a port that was initially passed in the configuration.
### Environment Details

- Karma version (output of `karma --version`): reproduced in 1.7.1, but should be also actual for 2.0.2
- Relevant part of your `karma.config.js` file: proxy middleware can be used as an example
```js
proxies: {
  '/img/': '/base/test/images/'
},
port: <specify already used port>
```
### Steps to reproduce the behaviour

1. Run karma instance (`karma start`) with already used port – in other words you have to raise `EADDRINUSE` error in https://github.com/karma-runner/karma/blob/667b47efbe42800189efc9ba697f07c2671a7845/lib/server.js#L186 It can be reproduced by running 2 or more karma instances that use the same port (e.g. `9876`)
2. You have to see Karma warning: `WARN [karma]: Port 9876 in use` 
and a new port that Karma uses: `INFO [karma]: Karma <v> server started at http://0.0.0.0:9877/`

![image](https://user-images.githubusercontent.com/748074/40381616-cfae02f6-5e04-11e8-9890-c51952892508.png)

3. Try to load any resources that match proxy rules.
4. Resources are proxied to the initial port `9876` instead of changed `9877`.

**Comment by EzraBrooks** [comment]
This seems to be (as you can see in the linked source snippet) intentional behavior. I would agree with you that it's not very intuitive - when you tell an application to use a port, it should use it or fail. Changing this would be, I assume, a reversal of a design decision, so it'll probably require some discussion.

**Comment by ViieeS** [comment]
@lusarz it's not fixed for me

![image](https://user-images.githubusercontent.com/8194543/41920615-c06cbfdc-7969-11e8-9aec-25ae4387eec5.png)

**Comment by lusarz** [comment]
@ViieeS it is Karma v2.0.4 ?

**Comment by ViieeS** [comment]
@lusarz yes. I have 3 pipelines running in the same time in gitlab. v2.0.2 works fine.
