### ISSUE TITLE
Drop Node 4 support

### ISSUE THREAD

**Issue by devoto13** [karma-runner/karma#3016]
Node 4 has reached end-of-life on [30th of April](https://github.com/nodejs/Release#end-of-life-releases). There are libraries out there, which have already dropped support for it to benefit from new ES feature available with newer versions. 

Opening this issue to discuss how Karma can drop Node 4 support. This will probably require a major version bump as it will break everybody, who is stuck with Node 4.

Benefits of dropping Node 4 support:
- `class` is available without strict mode
- support for default parameter values in functions
- support for rest function parameters (which is better alternative for `arguments` and will allow to move remaining functions to arrow functions)
- new methods on Array, Promise and other built-in objects
- detailed in the [compat-table](https://github.com/nodejs/Release#end-of-life-releases)

So, what does it take to drop support for Node 4?

**Comment by lusarz** [comment]
I definetely agree with @devoto13. 

I think it may be enough to prepare pull request which remove these lines:
https://github.com/karma-runner/karma/blob/80cf39c4f2a327921d3d4d3d2edbb10448425bf2/appveyor.yml#L5

https://github.com/karma-runner/karma/blob/3add635f4efd183e91b6e36714c64d0c8b941a54/.travis.yml#L4

**Comment by devoto13** [comment]
@johnjbarton What is the issue? Anything I can help with?

**Comment by johnjbarton** [comment]
https://travis-ci.org/karma-runner/karma/jobs/385281416

yarn install v1.3.2
[1/5] Validating package.json...
[2/5] Resolving packages...
error Received malformed response from registry for undefined. The
registry may be down.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation
about this command.
The command "eval yarn " failed. Retrying, 2 of 3.

**Comment by johnjbarton** [comment]
As I suspected, the issue resolved itself.

**Comment by lusarz** [comment]
@johnjbarton, @devoto13 any update on that ? Is there anything that stop us from removing Node 4 support ?

**Comment by johnjbarton** [comment]
Next week I will try to:
   1) release one more 2.x version,
   2) update 3.0 dropping node 4 and log4js 2.x

**Comment by johnjbarton** [comment]
Fixed by #3082
