### ISSUE TITLE
`result.time` always set to `null`

### ISSUE THREAD

**Issue by J-Swift** [karma-runner/karma#3040]
### Expected behaviour
`reportSlowerThan` reports slow tests
### Actual behaviour
Nothing gets reported because `result.time` within `BaseReporter.onSpecResult` is always `null`
### Environment Details

- Karma version (output of `karma --version`): `v2.0.2`
- Relevant part of your `karma.config.js` file
```ts
module.exports = function(config) {
    config.set({
        basePath: '',
        frameworks: ['jasmine', '@angular/cli'],
        plugins: [
            require('karma-jasmine'),
            require('karma-chrome-launcher'),
            require('karma-jasmine-html-reporter'),
            require('karma-coverage-istanbul-reporter'),
            require('@angular/cli/plugins/karma')
        ],
        reportSlowerThan: 1,
        client: {
            clearContext: false
        },
        files: [{
            pattern: './src/test.ts',
            watched: false
        }],
        preprocessors: {
            './src/test.ts': ['@angular/cli']
        },
        mime: {
            'text/x-typescript': ['ts', 'tsx']
        },
        coverageIstanbulReporter: {
            reports: ['html', 'lcovonly'],
            fixWebpackSourcePaths: true
        },
        angularCli: {
            environment: 'dev'
        },
        reporters: config.angularCli && config.angularCli.codeCoverage ? ['progress', 'coverage-istanbul'] : ['progress', 'kjhtml'],
        port: 9876,
        colors: true,
        logLevel: config.LOG_INFO,
        autoWatch: true,
        browsers: ['Chrome'],
        singleRun: false
    });
};
```

### Steps to reproduce the behaviour

1. Set `reportSlowerThan` to non-zero value
2. Run tests
3. Observe that no slow tests get reported

**Comment by johnjbarton** [comment]
As far as I can tell `reportSlowerThan` is just passed to reporters. There is no internal support in karma for this feature.  (IMO this feature should be replaced with a way to configure reporters).

**Comment by J-Swift** [comment]
OK, interesting. After digging further, it ended up being related to `karma-jasmine`, as outlined in this issue: https://github.com/karma-runner/karma-jasmine/issues/196

I upgraded to `karma-jasmine` v1.1.2 and it fixed things for me.
