### ISSUE TITLE
"Connected on socket /#DL1_Pe-Z5rlx3VwlAAAA with id 30584584" error when tesing angular using karma

### ISSUE THREAD

**Issue by Dotisandhyarani** [karma-runner/karma#3043]
[###]([url](`url`)) Expected behaviour

### Environment Details

- Karma version (output of `karma --version`):
- Relevant part of your `karma.config.js` file

### Steps to reproduce the behaviour

1.
2.
3.

**Comment by johnjbarton** [comment]
Reopen if you have a bug to report.
