### ISSUE TITLE
Proposal: Allow preprocessor to handle binary files

### ISSUE THREAD

**Issue by kyliau** [karma-runner/karma#3046]
Karma currently detects whether a file is binary, and does not allow binary files to be passed on to preprocessors. The code is [here](https://github.com/karma-runner/karma/blob/master/lib/preprocessor.js#L101) and reproduced below.

```
if (thisFileIsBinary) {
  log.warn('Ignoring preprocessing (%s) %s because it is a binary file.',
    config[patterns[i]].join(', '), file.originalPath)
} else {
  preprocessorNames = combineLists(preprocessorNames, config[patterns[i]])
}
```

I'd like to propose that this restriction be removed, and allow binary files to be handled by preprocessors.

The main use case I have for this is to create a preprocessor that handles zip files containing Javascript code. In Google, due to the restriction of the build system, zip files are unavoidable, and it is not possible to extract them before running Karma. Relaxing this restriction would allow the creation of a preprocessor that handles this case.

To maintain backwards compatibility and prevent breakages, all plugins that handle binary files would
need to explicitly declare so. This can be done by adding a property `handleBinaryFile = true` to the
plugin. Without this flag, Karma will automatically fall back to the existing behavior - print a warning and ignore the file.

The actual code change is minimal, please see this [PR](https://github.com/karma-runner/karma/compare/master...kyliau:allowbinary?expand=1).

**Comment by johnjbarton** [comment]
Fixed by #3054, thanks @kyliau
