### ISSUE TITLE
Server.start static method was removed in a patch release

### ISSUE THREAD

**Issue by GreenGremlin** [karma-runner/karma#3053]
### Expected behaviour

Patch releases should not break things.

### Actual behaviour

v2.0.3 removed the Server.start static method, breaking functionality that worked on v2.0.2.

### Environment Details

- Karma version (output of `karma --version`): 2.0.3
- Relevant part of your `karma.config.js` file N/A

### Steps to reproduce the behaviour

1. Attempt to start a server with `require('karma').Server.start({...})`.

It looks like the static method has been deprecated for a while, but no warning was given.

**Comment by johnjbarton** [comment]
Source said
`Deprecated since version 0.13, to be removed in 0.14`

**Comment by GreenGremlin** [comment]
I hope it’s not the expectation that consumers read the source before upgrading.
