### ISSUE TITLE
Regression in 2.0.3: Use `for...in` to bind EventEmitter functions

### ISSUE THREAD

**Issue by johnjbarton** [karma-runner/karma#3057]
The PR 

refactor(events): refactor karma EventEmitter (#3012)

https://github.com/karma-runner/karma/commit/8197408188ce4eb6161e640ac35e3271d6aeb2ff

misfired: we need to iterate the objects prototype, not just the own enumerable functions.

**Comment by nicojs** [comment]
Wow! Took me a few hours to find this one. I had 2 sets of integration tests, one using 2.0.2 , one using 2.0.3. Big head scratcher. Thanks for fixing! 🤝
