### ISSUE TITLE
The changelog for v2.0.3 include changes back to 1.7.1 (or more?)

### ISSUE THREAD

**Issue by scottohara** [karma-runner/karma#3058]
### Expected behaviour
The diff between https://github.com/karma-runner/karma/compare/v2.0.2...v2.0.3 shows only 55 commits, over 91 files.

### Actual behaviour
The release notes/changelog for v2.0.3 seems uncharacteristically large (compared to prior releases), particularly for a simple patch version bump.

The change log includes items such as https://github.com/karma-runner/karma/commit/1082f35 (the `restartOnFileChange` option), which was committed back in 2015 and has been available since v0.13.11.

### Environment Details

N/A

### Steps to reproduce the behaviour

1. View [CHANGELOG.md](https://github.com/karma-runner/karma/blob/master/CHANGELOG.md) for `v2.0.3`
2. View diff from `v2.0.2...v2.0.3` (https://github.com/karma-runner/karma/compare/v2.0.2...v2.0.3)
3. Note the discrepancy
4. Note that the link for v2.0.3 in the changelog actually points to https://github.com/karma-runner/karma/compare/v0.12.16...v2.0.3

**Comment by johnjbarton** [comment]
I think is it wrong, I think the CHANGELOG generation was messed up by my tag change:
https://github.com/karma-runner/karma/releases/tag/1.7.1
which I did to fix another issue. Sorry, I guess it won't happen next time, we'll see.

**Comment by johnjbarton** [comment]
The 2.0.4 Changelog looks ok.
