### ISSUE TITLE
Can Karma be configured to generate a TS report?

### ISSUE THREAD

**Issue by MadHatter122312** [karma-runner/karma#3086]
- Karma version (output of `karma --version`): 2.0.0

I there anyway to configure Karma to generate a TS report?  In jest one is able to do something like this:

```
module.exports = {
  collectCoverageFrom: ["src/**/*.ts"],
  globals: {
    "ts-jest": {
      skipBabel: true,
    },
  },
  mapCoverage: true,
  moduleFileExtensions: ["js", "ts"],
  testResultsProcessor: "jest-sonar-reporter",
  transform: {
    "^.+\\.ts$": "<rootDir>/node_modules/ts-jest/preprocessor.js",
  },
  testMatch: ["<rootDir>/tests/**/*.test.ts"],
};
```

Can we do something like this in Karma?

**Comment by johnjbarton** [comment]
What is a "TS report"?

Maybe you mean a test coverage report for TypeScript input sources? If yes, look at https://www.npmjs.com/package/karma-remap-coverage

**Comment by MadHatter122312** [comment]
@johnjbarton I believe this might be it, but I want to make sure my use case makes sense.

At present, my report is generated AGAINST js files.  I would like my report to be generated from TS files, and look something like this:

-----------------------------------------------|----------|----------|----------|----------|----------
File                                           |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-----------------------------------------------|----------|----------|----------|----------|----------
 components/                                   |    64.17 |    57.77 |     47.5 |    64.58 |                |
  error.component.ts                           |       80 |    62.07 |    71.43 |       85 |       16,17,20 |
  grid-header-translate.component.ts           |       85 |       50 |    66.67 |     87.5 |          21,22 |
  index.ts                                     |       25 |        0 |    33.33 |    22.22 |... ,9,10,11,12 |
  login.component.ts                           |    60.98 |    51.43 |    41.67 |    61.11 |... 35,41,44,47 |
  menu.component.ts                 |    77.42 |    82.76 |     62.5 |    80.77 | 17,18,21,24,27 |
--------------------------------------

The main purpose of this is to show a TS coverage report in SonarQube running the TS plugin.

Does that make sense?

When you say `test coverage report for TypeScript input sources`, we are referring to the same thing right?

**Comment by johnjbarton** [comment]
The File column in your output includes TypeScript .ts files; the other columns look like coverage data. So your goal is a coverage report for Typescript sources.
