### ISSUE TITLE
putting an `x` in front of describe() does not disable it

### ISSUE THREAD

**Issue by tripti825** [karma-runner/karma#3090]
### Expected behaviour
using xdescribe() instead of describe should refrain karma from running that test

### Actual behaviour
that test case is still being run

### Environment Details

- Karma version (output of `karma --version`): 2.0.4
- Relevant part of your `karma.config.js` file:

```
module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular-devkit/build-angular/plugins/karma')
    ],
    client: {
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    coverageIstanbulReporter: {
      dir: require('path').join(__dirname, '../coverage'),
      reports: ['html', 'lcovonly'],
      fixWebpackSourcePaths: true
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false
  });
};
```
- This karma conf.js file is from an angular project, and run using `ng test`
- test.js ->
// This file is required by karma.conf.js and loads recursively all the .spec and framework files

```
import 'zone.js/dist/zone-testing';
import { getTestBed } from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting
} from '@angular/platform-browser-dynamic/testing';

declare const require: any;

// First, initialize the Angular testing environment.
getTestBed().initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting()
);
// Then we find all the tests.
const context = require.context('./', true, /\.spec\.ts$/);
// And load the modules.
context.keys().map(context);
```
-tsconfig.spec.ts
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/spec",
    "module": "commonjs",
    "types": [
      "jasmine",
      "node"
    ]
  },
  "files": [
    "test.ts",
    "polyfills.ts"
  ],
  "include": [
    "**/*.spec.ts",
    "**/*.d.ts"
  ]
}

```

**Comment by tripti825** [comment]
OK what was happening is it(xdescribe) DID skip the test, but was still printing the string it takes (even the string of `it()` ) on the browser, because of which it gave the impression all the test cases are being run, whether or not proceeded by x.

**Comment by tripti825** [comment]
There are some observations I'd like to draw your attention to, if this turns out normal then well and good.

1. First, like I mentioned in my previous comment, even after putting an `x` on a describe() function, it prints its string on browser, though on console it skips it, i.e. overall it skips the test but still prints the string on browser. Shouldn't this be avoided?

2. Now here's the flow -> 
- I have two test cases, one of them contains error, and for the time being I comment this test case.
- I start `ng test` and it runs smoothly, printing the one test case which does NOT contain error.
- Now, I uncomment  the other test case (which was previously commented) and put an `x` on its describe() and save it. The `ng test` on console automatically reloads itself on sensing a change. It prints the output on the console, but runs smoothly for the other correct test case on browser.
- Now I stop `ng test` on console using `Ctrl + C` and start it again; this time it starts the browser, prints the error of the wrong test case BUT doesn't work for the right test case too (this was working previously).

Am I doing something wrong here or is this normal?

**Comment by johnjbarton** [comment]
The xdescribe issue is very likely something under the control of `karma-jasmine-html-reporter`.  karma itself does not write into the browser window.

The other issue is something to take up with users of `ng test`.
