### ISSUE TITLE
Silence logs in console of browser debug tab 

### ISSUE THREAD

**Issue by chrisdel101** [karma-runner/karma#3095]
### Actual behaviour
The output of the debug tab is full of stuff that I would like turned off but don't know how to do it.
### Environment Details
Windows 10, webpack4, mocha, Chrome
- Karma version (output of `karma --version`):
2.0,4
- Relevant part of your `karma.config.js` file
I tried this:
`logLevel: config.LOG_DISABLE`
### Steps to reproduce the behaviour

As soon as it is opened the console fills with unneeded logs. It is a mess and hard to use. Please inform me how I can silence these.
![image 1](https://user-images.githubusercontent.com/14151974/43420247-2ff69410-9411-11e8-8d96-0dddadcfd7b8.png)

Thanks!

**Comment by johnjbarton** [comment]
I suggest you look into your local copy (maybe node_modules/mocha) of mocha.js on line 6964.

**Comment by chrisdel101** [comment]
While maybe obvious in retrospect this is a helpful comment for me. (I just have to figure out how to make a change to the node module now so it remains permanent in my code base.)
Thanks!
