### ISSUE TITLE
Vulnerabilities in depenedency log4js

### ISSUE THREAD

**Issue by nader-eloshaiker** [karma-runner/karma#3098]
### Expected behaviour

Running "npm audit" should either return no vulnerabilities or low risk vulnerabilities.

### Actual behaviour

Running "npm audit" shows vulnerabilities in log4js@2.11
log4js@2.11 requires an update to the latest version or a version without vulnerabilities.

### Environment Details

- Karma version (output of `karma --version`): 2.0.5
- log4js@2.11

### Steps to reproduce the behaviour

1. npm audit

**Comment by devoto13** [comment]
Already fixed by https://github.com/karma-runner/karma/pull/3082 and will be included in the next release.
