### ISSUE TITLE
[Question] Is there a way to view the webpack bundle that gets produced by running 'grunt karma'?

### ISSUE THREAD

**Issue by gwevans** [karma-runner/karma#3104]
I am getting an error while running `grunt karma`. I am using a the preprocessors key to bundle my tests into one bundle, from there I use phantomJS as my browser.

I am using
```
karma: {
    options: {
        preprocessors: {
             'test/testFile.js': ['webpack'],
        }
    }
}
```

Karma is failing due to 'unexpected token const', and points to line 9452 of testFile.js (ie the newly created bundle). This is clearly babel-loader related, and is coming from somewhere within node_modules, but I have no idea where. Is there a way to view the newly created bundle is created when running 'grunt karma'?

**Comment by johnjbarton** [comment]
Run karma with `--no-single-run` http://karma-runner.github.io/2.0/config/configuration-file.html.

Then follow 
I'm getting an error during the installation related to the ws module, how can I solve it?
from 
http://karma-runner.github.io/2.0/intro/troubleshooting.html
