### ISSUE TITLE
Given up on semver?

### ISSUE THREAD

**Issue by alasdairhurst** [karma-runner/karma#3105]
Looking at all the 2.x releases i don't see any attempt to follow semver, with breaking changes and features dotted around in each patch version. Are we expected to just rely on package-lock to stop CI picking up breaking changes unexpectedly now?

**Comment by johnjbarton** [comment]
There are no changes to the API in 2.x.  If you have a specific bug, please provide actual information.

**Comment by alasdairhurst** [comment]
The changelog says otherwise

On 7 Aug 2018 16:05, johnjbarton <notifications@github.com> wrote:

There are no changes to the API in 2.x. If you have a specific bug, please provide actual information.

**Comment by johnjbarton** [comment]
You are welcome to review changes as they occur and suggest improvements.

What breaking changes occurred in 2.0.3?  

v3 dropped node 4, a breaking change.

**Comment by leoselig** [comment]
@johnjbarton 

> ### What breaking changes occurred in 2.0.3?

I'm afraid I already clearly stated that in my [comment](https://github.com/karma-runner/karma/issues/3105#issuecomment-412028621):

> ### v3 dropped node 4, a breaking change.

This is correct. However, as visible from the link I put into my comment, I was referring to the releases page: https://github.com/karma-runner/karma/releases/tag/v3.0.0
There it does **not** include that change. Apparently, the breaking change got documented later in
commit ab9333f4283dded1527d41148fc2d1081afbaa83 specifically in the `CHANGELOG.md` 10 hours ago. I usually refer to the releases page first and only if those are unmaintained do I consult any changelog files.

**Comment by johnjbarton** [comment]
v2.0.3 had no breaking change; the docs were wrong due to an old error, and they were corrected.

v3.0.0 had breaking changes; the docs omitted these, turns out 'chore' commits are omitted from the change log. The error has also been corrected.

Next time please consider sending a PR to fix docs.

**Comment by Florian-R** [comment]
@johnjbarton Any chance to add this breaking change in https://github.com/karma-runner/karma/releases ?

Missed that when scanning the changelog through this page.

**Comment by johnjbarton** [comment]
Ugh, 2 changelogs? We should delete one.

I updated the second one as well, thanks.
