### ISSUE TITLE
Unamble to run Karma

### ISSUE THREAD

**Issue by palavaianoop** [karma-runner/karma#3108]
### Expected behaviour
karma start
08 08 2018 12:30:02.720:WARN [karma]: No captured browser, open http://localhost:9876/
08 08 2018 12:30:02.732:INFO [karma]: Karma v2.0.5 server started at http://0.0.0.0:9876/
08 08 2018 12:30:02.733:INFO [launcher]: Launching browser Chrome with unlimited concurrency
08 08 2018 12:30:02.753:INFO [launcher]: Starting browser Chrome
08 08 2018 12:30:02.754:ERROR [launcher]: No binary for Chrome browser on your platform.
Please, set "CHROME_BIN" env variable.
/usr/bin/chromium-browser
It's not processing anything
can anyone guide next step
### Environment Details

- Karma version (output of `karma --version`): karma --version
Karma version: 2.0.5

- Relevant part of your `karma.config.js` file

// Karma configuration
// Generated on Wed Aug 08 2018 13:03:28 GMT-0600 (Mountain Daylight Time)

module.exports = function(config) {
  config.set({

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '',

    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['jasmine'],

    // list of files / patterns to load in the browser
    files: [
      './htdocs/Gruntfile.js',
      './htdocs/dispo_file_viewer/dispo_file_viewer.js',
      './htdocs/dispo_viewer/dispo_viewer.js',
      './htdocs/dispo_viewer/future_dispo_viewer.js',
      './htdocs/examples/altGuage.js',
      './htdocs/examples/plugin_example.js',
      './htdocs/plugins/freeboard/freeboard.datasources.js',
      './htdocs/plugins/freeboard/freeboard.widgets.js',
      './htdocs/plugins/thirdparty/datepicker.js',
      './htdocs/plugins/thirdparty/handlebars.js',
      './htdocs/plugins/thirdparty/jqplot.js',
      './htdocs/plugins/thirdparty/jquery.sparkline.min.js',
      './htdocs/plugins/thirdparty/json.ex.js',
      './htdocs/plugins/thirdparty/justgage.1.0.1.js',
      './htdocs/plugins/thirdparty/plugin_highcharts.js',
      './htdocs/plugins/thirdparty/plugin_highcharts_theme.js',
      './htdocs/plugins/thirdparty/plugin_node.js',
      './htdocs/plugins/thirdparty/raphael.2.1.0.min.js',
      './htdocs/plugins/thirdparty/widget.tables.js',
      './htdocs/test/casper/tests/smoke_test.js',
      './htdocs/test/casper/util/test_util.js',
      './htdocs/thirdparty/jqPlot/1.0.8/jquery.jqplot.min.js',
      './htdocs/thirdparty/jqPlot/1.0.8/plugins/jqplot.barRenderer.min.js',
      './htdocs/thirdparty/jqPlot/1.0.8/plugins/jqplot.categoryAxisRenderer.min.js',
      './htdocs/thirdparty/jqPlot/1.0.8/plugins/jqplot.dateAxisRenderer.min.js',
      './htdocs/thirdparty/jqPlot/1.0.8/plugins/jqplot.meterGaugeRenderer.min.js',
      './htdocs/thirdparty/jqPlot/1.0.8/plugins/jqplot.pieRenderer.min.js',
      './htdocs/thirdparty/jqPlot/1.0.8/plugins/jqplot.pointLabels.min.js',
      './src/talos/wwwroot/Scripts/vue.js',
      './src/talos/wwwroot/Scripts/vue.min.js',
      './src/talos/wwwroot/Scripts/axios.min.js',
      './src/talos/wwwroot/Scripts/periscope_index.js',
      './src/talos/wwwroot/extjs/ext-core.js',
      './src/talos/wwwroot/lib/bootstrap/dist/js/bootstrap.js',
      './src/talos/wwwroot/lib/bootstrap/dist/js/bootstrap.min.js',
      './src/talos/wwwroot/lib/bootstrap/dist/js/npm.js',
      './src/talos/wwwroot/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js',
      './src/talos/wwwroot/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js',
      './src/talos/wwwroot/lib/jquery-validation/dist/additional-methods.js',
      './src/talos/wwwroot/lib/jquery-validation/dist/additional-methods.min.js',
      './src/talos/wwwroot/lib/jquery-validation/dist/jquery.validate.js',
      './src/talos/wwwroot/lib/jquery-validation/dist/jquery.validate.min.js',
      './src/talos/wwwroot/lib/jquery/dist/jquery.js',
      './src/talos/wwwroot/lib/jquery/dist/jquery.min.js',
      './src/talos/wwwroot/panojs/PanoJS.js',
      './src/talos/wwwroot/panojs/control_info.js',
      './src/talos/wwwroot/panojs/control_svg.js',
      './src/talos/wwwroot/panojs/control_thumbnail.js',
      './src/talos/wwwroot/panojs/controls.js',
      './src/talos/wwwroot/panojs/pyramid_Bisque.js',
      './src/talos/wwwroot/panojs/pyramid_Zoomify.js',
      './src/talos/wwwroot/panojs/pyramid_imgcnv.js',
      './src/talos/wwwroot/panojs/utils.js'
    ],

    // list of files / patterns to exclude
    exclude: [
    ],

    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {
    },

    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: ['progress'],

    // web server port
    port: 9876,

    // enable / disable colors in the output (reporters and logs)
    colors: true,

    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_INFO,

    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: true,

    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: ['Chrome'],

    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: false,

    // Concurrency level
    // how many browser should be started simultaneous
    concurrency: Infinity
  })
}

**Comment by johnjbarton** [comment]
Please follow the instruction in the error message

> 08 08 2018 12:30:02.754:ERROR [launcher]: No binary for Chrome browser on your platform.
Please, set "CHROME_BIN" env variable.

**Comment by palavaianoop** [comment]
08 08 2018 14:40:18.732:INFO [launcher]: Launching browser Chrome with unlimited concurrency
08 08 2018 14:40:18.751:INFO [launcher]: Starting browser Chrome
08 08 2018 14:40:20.204:ERROR [launcher]: Cannot start Chrome

(chromium-browser:23831): Gtk-WARNING **: cannot open display:

08 08 2018 14:40:20.205:ERROR [launcher]: Chrome stdout:
08 08 2018 14:40:20.205:ERROR [launcher]: Chrome stderr:
(chromium-browser:23831): Gtk-WARNING **: cannot open display:

08 08 2018 14:40:20.211:INFO [launcher]: Trying to start Chrome again (1/2).
08 08 2018 14:40:21.825:ERROR [launcher]: Cannot start Chrome

(chromium-browser:23845): Gtk-WARNING **: cannot open display:

08 08 2018 14:40:21.825:ERROR [launcher]: Chrome stdout:
08 08 2018 14:40:21.826:ERROR [launcher]: Chrome stderr:
(chromium-browser:23845): Gtk-WARNING **: cannot open display:

08 08 2018 14:40:21.827:INFO [launcher]: Trying to start Chrome again (2/2).
08 08 2018 14:40:23.194:ERROR [launcher]: Cannot start Chrome

(chromium-browser:23859): Gtk-WARNING **: cannot open display:

08 08 2018 14:40:23.194:ERROR [launcher]: Chrome stdout:
08 08 2018 14:40:23.194:ERROR [launcher]: Chrome stderr:
(chromium-browser:23859): Gtk-WARNING **: cannot open display:

08 08 2018 14:40:23.195:ERROR [launcher]: Chrome failed 2 times (cannot start). Giving up.

**Comment by ihor-zinchenko** [comment]
same for me

**Comment by johnjbarton** [comment]
The karma-runner does not provide any browser or browser plugin. It is a
testing framework. Someone could provide a fully functional install
package, but this repo is not that.
