### ISSUE TITLE
Tests pass in debug but fail in ChromeHeadless

### ISSUE THREAD

**Issue by EricHanLiu** [karma-runner/karma#3120]
### Expected behaviour
I'm running some unit tests that depend on the top offset of an element, and these tests pass in debug mode but fail when I run them without `single-run=false`. I tried switching my browser to Chrome and they still fail, and I believe it could be because of the banner that appears at the top 
![screen shot 2018-08-28 at 10 30 19 am](https://user-images.githubusercontent.com/17733887/44730184-60ced800-aaae-11e8-934f-f769892f1209.png)

Is this banner present in HeadlessChrome? These tests all passed before I made a small css change which affected the viewport height (from 100% to 95vh), but I've fixed the tests accordingly and they all pass in the debug runner.

### Actual behaviour
These tests should pass in debug **and** in the single-run HeadlessChrome mode.

### Environment Details

- Karma version (output of `karma --version`): 2.0.5
- Relevant part of your `karma.config.js` file
```javascript
    ...

    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: ['ChromeHeadless'],


    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: true,

    // Concurrency level
    // how many browser should be started simultaneous
    concurrency: Infinity
  })
```

### Steps to reproduce the behaviour

1. Have tests which depend on the top offset of an element
2. Run the tests with HeadlessChrome single-run and in debug (`single-run=false`)
3. Tests will pass in debug but fail in HeadlessChrome

Any help is greatly appreciated

**Comment by EricHanLiu** [comment]
Some of the tests that are failing actually don't rely on the top offset at all, and they pass in debug but fail in single-run headless, so I don't think it's the banner issue.

The main problem is how can my tests be all passing in debug but fail in single-run headless? And I can't debug why they fail because they all throw the `Timeout of 2000ms exceeded` error since I'm running async tests and I can only debug them in debug

**Comment by johnjbarton** [comment]
Perhaps 'headless' is also not related? Simply try a regular chrome test to check.

Note that karma tests are run in an iframe by default.

**Comment by EricHanLiu** [comment]
You're right, running it with the Chrome browser also causes some tests to fail, although slightly different tests than headless. But they still should be passing

**Comment by johnjbarton** [comment]
Perhaps you have some kind of race bug in your code. As you vary the circumstances, the winner varies.  In debug the winner is always the path that passes. (This issue is very unlikely to a bug in karma-runner).

**Comment by EricHanLiu** [comment]
How can the winner consistently be in the debug runner? Are there other differences from debug and single-run that could help identify what the race condition is?

**Comment by EricHanLiu** [comment]
could this perhaps be an issue with ChromeHeadless (puppeteer) not running with the same window size? I set the size of the parent wrapper before each test in JS, but apparently puppeteer runs in 800x600px.

it's odd that I didn't have problems with this before (if this is the case) before my `height` changes

**Comment by EricHanLiu** [comment]
Yeah that seems to have been the issue, I adjusted the tests to work with a viewport of 800x600 and they work now.

Strangely, pre-height changes the tests should've also failed but somehow passed in headless, maybe just pure luck
