### ISSUE TITLE
Uncaught Error: Cannot find module 'chai'

### ISSUE THREAD

**Issue by jcrosby10** [karma-runner/karma#3130]
I am currently trying to get our JavaScript tests to run in Karma as some of our code references the global window object which is not available in tests. I run karma start my.conf.js and I get this error
`{
    "message": "Uncaught Error: Cannot find module 'chai'\nat node_modules/mocha/mocha.js:1:196\n\nError: Cannot find module 'chai'\n    at s (node_modules/mocha/mocha.js:1:156)\n    at s (node_modules/mocha/mocha.js:1:122)\n    at test/CatenaBackbone.test.js:4:12",
    "str": "Uncaught Error: Cannot find module 'chai'\nat node_modules/mocha/mocha.js:1:196\n\nError: Cannot find module 'chai'\n    at s (node_modules/mocha/mocha.js:1:156)\n    at s (node_modules/mocha/mocha.js:1:122)\n    at test/CatenaBackbone.test.js:4:12"
  }`

I have done some searching and I do have chai installed locally, not globally as I've seen in a few other places. Any ideas on why its not finding chai? Here is my conf file

`module.exports = function(config) {`
    `config.set({`
        `basePath: '',`
        `frameworks: ['mocha'],`
        `files: [`
            `'./test/*.js'`
        `],`
        `exclude: [`
        `],`
        `preprocessors: {`
        `},`
        `reporters: ['progress'],`
        `port: 9876,`
        `colors: true,`
        `logLevel: config.LOG_INFO,`
        `autoWatch: true,`
        `browsers: ['Chrome'],`
        `singleRun: true,`
        `concurrency: Infinity`
    `})`
`}`

**Comment by inf3rno** [comment]
The chai lib is not in your test folder.

**Comment by johnjbarton** [comment]
@inf3rno Thanks!
