### ISSUE TITLE
Feature: Option to fail run on empty test suite

### ISSUE THREAD

**Issue by stanislavgeorgiev** [karma-runner/karma#3135]
### Expected behaviour

I have 20 files with tests and each of those files has its `describe()` section and at least one `it()` section. In Angular when a new component is create a test file is created automatically with a single boiler plate test to check whether the component is creating successfully. Sometimes a team member may be enticed to comment a failing test so they can deliver the code and to keep the build green. 

I would like to have an option in `karma.config.js` to fail/show error when there's a single test suite that has a `describe()` block but doesn't have any `it()` blocks. There's already a similar option `failOnEmptyTestSuite` but that one is if there are no tests at all so perhaps it could be extended to cover this case too or add another option.

### Actual behaviour

It would skip the entire empty test suite

### Environment Details

- Karma version: 3.0.0
- Jasmine: 2.99.1
- Angular 6.1.1

### Steps to reproduce the behaviour

1. Have a couple of test files with Jasmine tests in them.
2. Add another test file with only a `describe()` block and no `it()` blocks

**Comment by johnjbarton** [comment]
This feature cannot be implemented in karma-runner: it has no knowledge of jasmine.  Please try karma-jasmine project.

**Comment by stanislavgeorgiev** [comment]
Thanks @johnjbarton. I posted the same issue there:
https://github.com/karma-runner/karma-jasmine/issues/216
