### ISSUE TITLE
[karma]: Error: Module not found: Error: Can't resolve 'jquery'

### ISSUE THREAD

**Issue by buddyackerman** [karma-runner/karma#3138]
I installed Jquery into an Angular project and I'm getting the above error when I try to build the app.   I have a simple import statement in my component

   import * as $ from 'jquery';

I also installed the typings for Jquery. 

### Expected behavior
Run the tests

### Actual behavior
These messages/error:

    INFO [karma]: Front-end scripts not present. Compiling...
    ERROR [karma]: Error: Module not found: Error: Can't resolve 'jquery' 

### Environment Details
Karma: 2.0.0
Angular: 5.2.6
Jasmine: 2.99.0
NodeJS: 8.9.1
Windows Server: 2016

karma.config

    module.exports = function (config) {
      config.set({
        basePath: '',
        frameworks: ['jasmine', '@angular/cli', 'jquery-3.3.1'],
        plugins: [
          require('karma-jasmine'),
          require('karma-jquery'),
          require('karma-chrome-launcher'),
          require('karma-jasmine-html-reporter'),
          require('karma-coverage-istanbul-reporter'),
          require('@angular/cli/plugins/karma')
        ],
        client: {
          clearContext: false // leave Jasmine Spec Runner output visible in browser
        },
        coverageIstanbulReporter: {
          reports: ['html', 'lcovonly'],
          fixWebpackSourcePaths: true
        },
        angularCli: {
          environment: 'dev',
          sourcemaps: false
        },
        reporters: ['progress', 'kjhtml'],
        port: 9876,
        colors: true,
        logLevel: config.LOG_INFO,
        autoWatch: false,
        browsers: ['ChromeHeadless'],
        singleRun: true
      });
    };

**Comment by johnjbarton** [comment]
> require('karma-jquery'),

You have to have issue  `npm install karma-jquery`

**Comment by buddyackerman** [comment]
@johnjbarton You think I didn't install karma-jquery?  Of course I installed it.  You shouldn't close an issue with such ridiculous comment.

**Comment by johnjbarton** [comment]
Please open a bug report with karma-jquery. I would also appreciate a more civil tone.
