### ISSUE TITLE
Error: [$injector:unpr] Unknown provider: dataProvider <- data

### ISSUE THREAD

**Issue by dmohan001c** [karma-runner/karma#3146]
I am trying to write some unit test for my app, but I am running into an issue.

My .js file looks like
`
function () {

    angular.module('app',[])
        .factory('code', function ($http, svc, $q) {

		 function getCodeByID(id) {
                return $http.get(svc.get('my-application') + id)
                    .then(function (res) {
                        return res;
                    });
            }

        function getCodes(query) {
            var qry = ccUtils.buildQuery(query);
            return $http.get(svc.get('url')
                .then(function (response) {
                    var resObj = {};
                    resObj.data = response.data.content;
                    resObj.pageData = {
                        totalPages: response.data.totalPages,
                        totalElements: response.data.totalElements
                    };
                    return resObj;
                }));
        }
		});
	})();
`
My spec.js file looks like.
`
// testing controller
describe('MyController', function() {
   var data, svc, code;

    // Set up the module
    //beforeEach(module('app'));
    beforeEach(angular.mock.module('app'));

    beforeEach(inject(function(_data_) {
        data = _data_;
    }));

    beforeEach(inject(function(_svc_) {
        svc = _svc_;
    }));

    beforeEach(inject(function(_code_) {
        code = _code_;
    }));

    it('Should exist', function() {
        expect(code).toBeDefined();
    });
});
`
Error
`MyController
    × Should exist
        Error: [$injector:unpr] Unknown provider: dataProvider <- data
        https://errors.angularjs.org/1.7.4/$injector/unpr?p0=dataProvider%20%3C-%20data
            at node_modules/angular/angular.js:138:12
            at node_modules/angular/angular.js:4905:19
            at Object.getService [as get] (node_modules/angular/angular.js:5065:32)
            at node_modules/angular/angular.js:4910:45
            at getService (node_modules/angular/angular.js:5065:32)
            at injectionArgs (node_modules/angular/angular.js:5090:58)
            at Object.invoke (node_modules/angular/angular.js:5114:18)
            at UserContext.WorkFn (node_modules/angular-mocks/angular-mocks.js:3439:20)
        Error: Declaration Location
            at window.inject.angular.mock.inject (node_modules/angular-mocks/angular-mocks.js:3402:25)
            at Suite.<anonymous> (src/app/epcCodes/epc.spec.js:9:16)
            at src/app/epcCodes/epc.spec.js:2:1
`
I have injected all the dependencies required for this code, still, I am running out of this issue. 
I am pretty new to unit testing, so any help with this would be appreciated.

**Comment by johnjbarton** [comment]
Your call stack shows `node_modules/angular/angular.js`, so you need to ask some where that knows about Angular.

**Comment by dmohan001c** [comment]
I have been added this in the Karma configuration file, as I know it should have been called.

**Comment by dmohan001c** [comment]
Can anyone help me in fixing this issue

**Comment by johnjbarton** [comment]
Run with `--no-single-run` then http://karma-runner.github.io/2.0/intro/troubleshooting.html
