### ISSUE TITLE
Support for async/await in karma code

### ISSUE THREAD

**Issue by lusarz** [karma-runner/karma#3151]
What do you thinks about using async/await in our code. It is natively supported from `Node 8`, but [`Node 6`](https://github.com/nodejs/Release) is now in maintenance, and it's end of life is planned to April 2019.

We can consider remove karma support for Node 6 now, or adapt [puppeteer solution](https://github.com/GoogleChrome/puppeteer/blob/81d42c4688618f19b74513230e7e30c69599f4ed/install.js#L108-L122).

**Comment by johnjbarton** [comment]
Personally I would like to see the node-v4-level updates completed first, like `var` -> `const` and use of classes.  Adopting node 6 now could force us to support two versions which would not be practical. I could see switching to node 6 once we are closer to April.

Somewhat related but perhaps more difficult: a way to support existing plugins but also allow asynchronous plugins would be cool.

**Comment by lusarz** [comment]
Ok, it sounds good to me

**Comment by jniles** [comment]
@johnjbarton, if one wanted to work on the node v4 level updates, is there anywhere you would recommend to start?

**Comment by jniles** [comment]
@johnjbarton, am I right in thinking that both `/common` and `/context` are also shipped to the client?  It looks like both are processed by browserify in the build process.

**Comment by johnjbarton** [comment]
Looks like @lusarz got them all huh?

**Comment by lusarz** [comment]
@johnjbarton yeah, now I'm waiting for green light to introduce async/await ;)

@jniles Some times ago I've did some research about possibility to replace `var` into `const/let` in `/common` and `/context`, but [varify ](https://github.com/thlorenz/varify) didn't wanted to work for me.

**Comment by johnjbarton** [comment]
If we add `async/await` and thus create a breaking 4.x version, what will be our plan if we have to create another 3.x release (say a security issue or compat with some dep release)?  Doesn't have to be a great option but I'd like to know the cost of the extreme case.

**Comment by johnjbarton** [comment]
Yes, I assumed we would drop node v6.  So our story could be "Sorry, if you want to use node v6 after 3.1.2, you have to fork the source".  I just want to make a clear decision, not an accident and no implied support for two versions at the same time.

**Comment by lusarz** [comment]
Yes, I agree with that.
