### ISSUE TITLE
npm audit highlights multiple vulnerabilities in package dependencies

### ISSUE THREAD

**Issue by kburson** [karma-runner/karma#3164]
### Expected behaviour
clean install of package and all dependencies

### Actual behaviour
added 1265 packages from 1324 contributors and audited 38522 packages in 19.391s
found 12 vulnerabilities (9 low, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details

### Environment Details
OSX 10.13.6
Node v8.11.4

- Karma version (output of `karma --version`):  2.02

### Steps to reproduce the behaviour

1. npm install

**Comment by kburson** [comment]
The vulnerabilities are localized to 2 dependencies:

socket.io
lodash

| dependency of | package | path | priority | description | more info |
|---------------|---------|------|----------|-------------|-----------|
| karma [dev]   | debug   | karma > socket.io > debug  | Low | Regular Expression Denial of Service | https://nodesecurity.io/advisories/534  |
| karma [dev]   | debug   | karma > socket.io > socket.io-adapter > debug  | Low | Regular Expression Denial of Service | https://nodesecurity.io/advisories/534 |
| karma [dev]   | debug   | karma > socket.io > socket.io-client > debug  | Low | Regular Expression Denial of Service | https://nodesecurity.io/advisories/534 |
| karma [dev]   | debug   | karma > socket.io > socket.io-client > engine.io-client > debug  | Low | Regular Expression Denial of Service | https://nodesecurity.io/advisories/534 |
| karma [dev]   | debug   | karma > socket.io > socket.io-adapter > socket.io-parser > debug  | Low | Regular Expression Denial of Service | https://nodesecurity.io/advisories/534  |
| karma [dev]   | debug   | karma > socket.io > socket.io-client > socket.io-parser >  debug  | Low | Regular Expression Denial of Service | https://nodesecurity.io/advisories/534  |
| karma [dev]   | debug   | karma > socket.io > socket.io-parser > socket.io-parser >  debug  | Low | Regular Expression Denial of Service | https://nodesecurity.io/advisories/534  |
| karma [dev]   | lodash  | karma > lodash  | Low | Prototype Pollution | https://nodesecurity.io/advisories/577 |
| karma [dev]   | ws      | karma > socket.io > engine.io > ws  | High | Denial of Service | https://nodesecurity.io/advisories/550 |
| karma [dev]   | ws      | karma > socket.io > socket.io-client > engine.io-client > ws  | High | Denial of Service | https://nodesecurity.io/advisories/550 |
| karma [dev]   | parsejson      | karma > socket.io > socket.io-client > engine.io-client > parsejson  | High | Regular Expression Denial of Service | https://nodesecurity.io/advisories/528 |

**Comment by johnjbarton** [comment]
The current version is 3.0, please update.
