### ISSUE TITLE
Chromium crashing with karma supplied --user-data-dir

### ISSUE THREAD

**Issue by Lalem001** [karma-runner/karma#3166]
### Expected behaviour

Chromium should run forever, until karma exits.

### Actual behaviour

Chromium is crashing approximately 30 seconds after starting.

### Environment Details

- Karma version (output of `karma --version`): 3.0.0
- Relevant part of your `karma.config.js` file

```javascript
const puppeteer = require('puppeteer');
process.env.CHROME_BIN = puppeteer.executablePath();
module.exports = function(config) {
  config.set({
    frameworks: ['jasmine'],
    files: ['app/**/*.spec.js'],
    reporters: ['progress'],
    port: 9876,
    colors: false,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['ChromeHeadless'],
    singleRun: false,
    concurrency: Infinity
  })
}
```

### Steps to reproduce the behaviour

1. `$(npm bin)/karma start`
2. Observe crash at around the 30 second mark
3. [Optional] Manually run chromium with the same args that karma uses, but with `--user-data-dir` either removed or pointing to an empty directory. No crash, tests pass fine.

**Comment by Lalem001** [comment]
Chromium crash log shown in Karma's log:

```text
Received signal 11 SEGV_MAPERR 000000000000
 [0x0001127796fc]
 [0x000112779611]
 [0x7fff7a65cf5a]
 [0x7fb21105e238]
 [0x000113d94e45]
 [0x000113d95206]
 [0x000113d99791]
 [0x0001126c5d82]
 [0x0001127410be]
 [0x000112782ff4]
 [0x0001127408f4]
 [0x0001127387af]
 [0x000112738514]
 [0x0001127834c7]
 [0x7fff7a666661]
 [0x7fff7a66650d]
 [0x7fff7a665bf9]
[end of stack trace]
```

**Comment by Lalem001** [comment]
The thing is, chromium appears to be crashing because of items that karma is putting into the specified `--user-data-dir`. If I start Chromium using the exact same arguments that karma uses, but point `--user-data-dir` to an empty directory, Chromium does not crash. I did plenty of investigation before opening here, and I believe this is an issue caused by Karma.

And actually, as I say that, I think I need to retract that. I actually think it is caused by `karma-chrome-launcher`. Should I go ahead and open there then?

**Comment by johnjbarton** [comment]
> Should I go ahead and open there then?

Yes thanks!
