### ISSUE TITLE
Karma not capturing Chrome (Angular project)

### ISSUE THREAD

**Issue by gultyaev** [karma-runner/karma#3185]
### Expected behaviour
Should run tests and show them in browser

### Actual behaviour
Tries to capture browser with no success. (Browser is opened by Karma with proper url and port)

### Environment Details

- Karma version (output of `karma --version`): 3.0.0
- Relevant part of your `karma.config.js` file
```// Karma configuration file, see link for more information
// https://karma-runner.github.io/1.0/config/configuration-file.html

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular-devkit/build-angular/plugins/karma')
    ],
    client: {
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    coverageIstanbulReporter: {
      dir: require('path').join(__dirname, '../coverage'),
      reports: ['html', 'lcovonly'],
      fixWebpackSourcePaths: true
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false
  });
};
```
### Steps to reproduce the behaviour

There is no such steps since it's about one specific private project.

### Question

Is there a logging or something like that so I could understand why Karma cannot capture Chrome? 

The interesting part is that it successfully captures browser in other projects.

### Log information 

![image](https://user-images.githubusercontent.com/22374911/46915913-76935080-cfbb-11e8-916e-c216100f6d52.png)

**Comment by johnjbarton** [comment]
Try `--log-level=DEBUG`

Try running with `--no-single-run` then opening a browser at the localhost port given.  Open devtools and look into your test page. The karma server is waiting for the browser to load: your code may be hanging or erroring the load.
