### ISSUE TITLE
Wildcard for files not working

### ISSUE THREAD

**Issue by wwarme** [karma-runner/karma#3186]
### Expected behaviour
Karma recognizes and executes test-files in the directories matched by minimatch path (see config below).
### Actual behaviour
After upgrading Karma **from 1.5 to 3.0** neither wildcard `/*.*` nor extglob `'/*.+(ts|tsx)'` is working. Explicitely linking .ts files _does work_, doing so with .tsx files does _not_ execute any tests provided in .tsx files. Linking single .tsx-files in the karma conf file array _does_ work though! 
Defining a Test.ts and a Test.tsx file in the project **root** and linking them via `/*.(ts|tsx)` _also does work_! More explicitely (paths are equal on files and preprocessors setting): 
`packages/*/test/**/*.*` - **not** working
`packages/*/test/**/*.+(ts|tsx)` - **not** working
`packages/*/test/**/*.tsx` - **not** working
`packages/*/test/**/*.ts` - working, but only executes .ts test-files
`packages/core/test/security/SecurityWrapper.tsx` - working, but requires explicit definition of all single .tsx test files

Tests execute as expected (if executed).
Test files (.ts _and_ .tsx) are recognized by watcher, thus karma even reruns when changing a .tsx file, but is not executing the tests. 
### Environment Details

- Karma version (output of `karma --version`): 3.0.0
- Webpack version: 4.20.1
- node.js version: 8.12.0
- OS: Windows 8.1 Pro
- Relevant part of your `karma.config.js` file
```
module.exports = function karmaConfig(config) {
config.set({
    frameworks: ['mocha', 'intl-shim'],
    reporters: ['spec','junit'],
    files: [
        //We need this, otherwise we will get an error, everytime we use "assign" with Redux
        './node_modules/phantomjs-polyfill-object-assign/object-assign-polyfill.js',
        './node_modules/babel-polyfill/browser.js',
        'packages/*/test/**/*.*'
    ],
    preprocessors: {
        'packages/*/test/**/*.*':['webpack','sourcemap']
    },
    browsers: [
        'PhantomJS'
    ],
    port:9888,
    webpack: require('./webpack.test.config.js'),
    junitReporter: {
        outputDir: 'reports/unittests'
    }
});
};

**Comment by johnjbarton** [comment]
Try investigating with `--log-level=DEBUG`.  Try testing without webpack: does it work then?

**Comment by wwarme** [comment]
Yeah of course... Thanks for the tipp, investigating with loglevel debug made it. looks like one of the test files is causing phantomjs to silentyl stop or crash:
`17 10 2018 10:40:21.767:DEBUG [phantomjs.launcher]: TypeError: undefined is not an object (evaluating 'index_1.default.onReset')`

Thank you so far, I think this can be closed since not karma related. Sorry for the false alert...
