### ISSUE TITLE
Karma homepage redirects to v2.0

### ISSUE THREAD

**Issue by robphoenix** [karma-runner/karma#3189]
### Expected behaviour

The [Karma homepage](https://karma-runner.github.io) should redirect to [v3.0](https://karma-runner.github.io/3.0/index.html)

### Actual behaviour

Redirects to [v2.0](https://karma-runner.github.io/2.0/index.html)

### Environment Details

- Karma version (output of `karma --version`):
- Relevant part of your `karma.config.js` file

### Steps to reproduce the behaviour

1.
2.
3.

**Comment by devoto13** [comment]
@robphoenix Thanks for letting us know. I've changed the home page to redirect to the latest version.

Note that you may need to clear browser cache/wait until it expires for the fix to take effect.

**Comment by robphoenix** [comment]
Grand, thanks @devoto13 :+1:
