### ISSUE TITLE
Odd coverage marker placements and no uncovered highlights

### ISSUE THREAD

**Issue by pixx3l** [karma-runner/karma#3190]
### Expected behaviour
A fully covered file ends up with 100% coverage. If it is not 100% covered, the markers point out where the uncovered code is, via either `[E]`/`[I]`, or uncovered highlighting.

### Actual behaviour
Reporter showing incomplete coverage, markers are misplaced (screenshot), and highlighting doesn't seem to work, so Im not sure what it wants me to fix.

### Environment Details

- Karma version 3.0.0:
- karma-chrome-launcher: 2.2.0:
- karma-coverage-istanbul-reporter: 2.0.4:
- karma-jasmine: 1.1.0

### Sample Code

```javascript
// mock source file
export function evalToSuccess() { return true; }

export function evalToFail() { return false; }

export function evalToUncovered() { return null; } // should be highlighted in red

export class TestCheck {
  evalCovered() {
    return true;
  }

  evalUncovered() { return null; } // should be highlighted in red
}
```

```javascript
// mock .spec file. purposely skips two functions
describe(`evalToSuccess`, () => {
  it('should pass', () => {
    const actual = evalToSuccess();
    expect(actual).toBe(true);
  });

  it('should fail', () => {
    const actual = evalToFail();
    expect(actual).toBe(true);
  });

  it('should only check the covered function', () => {
    const mock = new TestCheck();

    expect(mock.evalCovered()).toBe(true);
  });
});

```

<img width="848" alt="report" src="https://user-images.githubusercontent.com/34278658/46891456-f0023600-ce37-11e8-95c9-05b277ff4ca9.png">

**Comment by johnjbarton** [comment]
I don't know where the UI comes from, but it is not from karma-runner.  Maybe it is `karma-coverage-istanbul-reporter`.

**Comment by pixx3l** [comment]
Fair enough, thanks for checking.
