### ISSUE TITLE
Karma has a non-dev dependency on chromium (via the puppeteer package)

### ISSUE THREAD

**Issue by davidshepherd7** [karma-runner/karma#3191]
[This commit](https://github.com/karma-runner/karma/commit/0f8b2b17e8fb4aab101ed9acfc65a3090b3298ca?diff=split) added puppeteer (which is a wrapper around headless chrome) as a non-dev dependency of karma. Previously karma had phantomjs-prebuilt as a dev dependency. 

Presumably this change was unintentional? It's a bit annoying because it makes the install of karma take a long time.

### Expected behaviour

Installing karma does not install any particular browser.

### Actual behaviour

Installing karma installs chromium.

### Environment Details

- Karma version (output of `karma --version`): Karma version: 3.1.0
- Relevant part of your `karma.config.js` file: N/A

### Steps to reproduce the behaviour

1. npm install -D karma

**Comment by lukehutton** [comment]
I am also getting failures on all my builds after doing npm install -g karma, is this relevant?

```
> puppeteer@1.9.0 install /root/.nvm/versions/node/v8.9.4/lib/node_modules/karma/node_modules/puppeteer
> node install.js

module.js:472
    throw err;
    ^

Error: Cannot find module '/root/.nvm/versions/node/v8.9.4/lib/node_modules/karma/node_modules/puppeteer/install.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3`
```
downgrading to npm install -g karma@3.0.0  seems to work

**Comment by WebTechnolog** [comment]
**puppeteer** also takes 303 Mb of disk space which equals to the "weight" of all other packages in my setup (angular 7 app). It's very annoying
