### ISSUE TITLE
failed to proxy: tls_process_ske_dhe:dh key too small

### ISSUE THREAD

**Issue by Sevyls** [karma-runner/karma#3197]
### Expected behaviour
Proxy to https should work
### Actual behaviour
proxy fails with error: 
`WARN [proxy]: failed to proxy /finesse/api/User/Agent001 (write EPROTO 4455228864:error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small:../deps/openssl/openssl/ssl/statem/statem_clnt.c:1457:`
### Environment Details
- macOS 10.14
- WebStorm 2018.1.5
- Karma version 3.0.0
- ng-cli Project 
```
Angular CLI: 7.0.3
Node: 10.8.0
OS: darwin x64
Angular: 7.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.3
@angular-devkit/build-angular     0.10.3
@angular-devkit/build-optimizer   0.10.3
@angular-devkit/build-webpack     0.10.3
@angular-devkit/core              7.0.3
@angular-devkit/schematics        7.0.3
@angular/cdk                      7.0.2
@angular/cli                      7.0.3
@angular/material                 7.0.2
@ngtools/webpack                  7.0.3
@schematics/angular               7.0.3
@schematics/update                0.10.3
rxjs                              6.3.3
typescript                        3.1.3
webpack                           4.19.1
```

- Relevant part of your `karma.config.js` file
```
{
// ..
proxies: {
  "/finesse": "https://hq-uccx.abc.inc:8445/finesse"
},
proxyValidateSSL: false
// ..
}
```

### Steps to reproduce the behaviour

1. Use Cisco Sandbox for UCCX (requires VPN connection to sandbox environment)
https://developer.cisco.com/docs/finesse/#!sandbox

2. Try to proxy finesse REST API with karma.conf.js
3. Run karma server 
4. REST API Call: 
```
GET  http://localhost:9876/finesse/api/User/Agent001
Authorization Basic QWdlbnQwMDE6Y2lzY29wc2R0
```

**Comment by johnjbarton** [comment]
Sorry `tls_process_ske_dhe` is not part of karma-runner.  You can try to run with `--logLevel=DEBUG` to see if you get any more hints.
