### ISSUE TITLE
Cannot read property 'build' of undefined

### ISSUE THREAD

**Issue by hansemart** [karma-runner/karma#3206]
### Expected behaviour
Karma tests would run

### Actual behaviour
Some Tests fail with error message 

### Environment Details

-     Karma version 3.1.1
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
    require('karma-jasmine'),
    require('karma-chrome-launcher'),
    require('karma-typescript'),
    require('karma-jasmine-html-reporter'),
    require('karma-coverage-istanbul-reporter'),
    require('@angular-devkit/build-angular/plugins/karma')
    ],
    client:{
    clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    coverageIstanbulReporter: {
    dir: require('path').join(__dirname, 'coverage'), reports: [ 'html', 'lcovonly' ],
    fixWebpackSourcePaths: true
    },
    angularCli: {
    environment: 'dev'
    },
    reporters: ["progress", "karma-typescript"],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['ChromeHeadless'],
    customLaunchers: {

    ChromeHeadless: {
    base: 'Chrome',
    flags: ['--headless', '--disable-gpu', '--remote-debugging-port=9222', '--no-sandbox']
    }
    },
    singleRun: false
    });  `                                                                                      

### Steps to reproduce the behaviour

1. start ng test from folder
2. Result
 {
   "message": "An error was thrown in afterAll\nUncaught TypeError: Cannot read property 'build' of undefined",
   "str": "An error was thrown in afterAll\nUncaught TypeError: Cannot read property 'build' of undefined"
 }

**Comment by johnjbarton** [comment]
Your code has a bug, you need to fix it.

Try remove the headless flag, open browser devtools and look for the fail.
