### ISSUE TITLE
Better UI

### ISSUE THREAD

**Issue by ameerthehacker** [karma-runner/karma#3208]
Hi, 

I just thought why can we have some better UI for showing the test results, something like an angular app showing the result. If this is a good idea can I start working on it!

**Comment by johnjbarton** [comment]
Please take a look at eg karma-html-reporter, karma-jasmine-html-reporter, karma-html-detailed-reporter and so on.  Architecturally karma does not require or prevent new UI: just write a plugin and advertise it!
