### ISSUE TITLE
Can't install v2.0.6

### ISSUE THREAD

**Issue by woteska** [karma-runner/karma#3213]
### Expected behaviour

I want to install v2.0.6 installed via npm.

### Actual behaviour

There is no v2.0.6 (only v2.0.5) release, so npm install fails, but v2.0.6 exists in the changlog: https://github.com/karma-runner/karma/blob/master/CHANGELOG.md#206-2018-08-09

1. npm init
2. npm install karma@2.0.6 --save

**Comment by johnjbarton** [comment]
The supported version is 3.1.1.  Please upgrade.

**Comment by woteska** [comment]
Ok, but why does the Changelog includes v2.0.6 if it is impossible to install? 🤣

**Comment by johnjbarton** [comment]
I suppose the install script failed after posting the ChangeLog but before publishing to npm, perhaps because the npm login was incorrect at the push time.
