### ISSUE TITLE
after file-watcher trigger re-run - one test is executed without calling beforeAll & beforeEach

### ISSUE THREAD

**Issue by Kobico** [karma-runner/karma#3228]
when the browser is open and file has been changed, karma trigger rerun for all specs

the problem is that the last "it" that was executed in the last run - will run again first and without beforeAll, beforeEach called
all later tests run perefectly OK, the issue is only with the last executed test in the last run 
(maybe this information will help to target the root cause?)
### Expected behaviour
to run beforeEach and beforeAll before the test executed
### Actual behaviour
beforeEach and beforeAll aren't running before the test
### Environment Details

- Karma version (output of `karma --version`): 2.0.5
- Relevant part of your `karma.config.js` file:
conf.singleRun = false;

### Steps to reproduce the behaviour

1. create a single test which will pass dependent on beforeEach setup
2. run it with singleRun:false mode
3. change something in the test to trigger the file watcher

**Comment by johnjbarton** [comment]
The current version is 3.1.3, please upgrade.

karma core does not implement `beforeEach()/beforeAll()`; this sounds like jasmine and thus perhaps karma-jasmine plugin issue.  

If you can create a standalone case that illustrates this problem we might be able to take a look. But I don't see anyway to make this happen, so my guess is that the behavior is specific to something in your setup so you will need to investigate. 

It's also not clear to me why this is an issue: do you care about the  last executed test in the last run?  The result that matters is in the run after the file change.
