### ISSUE TITLE
Angular 7 karma test with importing external JS modules

### ISSUE THREAD

**Issue by mengzhen94** [karma-runner/karma#3229]
I am testing a Angular 7 component which has importing JS modules like:

component.ts

    import * as classA from '../../classA'; // Imported JS modules
    export class component implements OnInit {
      public a = new classA(10); // Instantiate
      ...
    }

classA.js

    class classA {
      constructor (a) {
        this.max = a;
        ...
    }
    
    if (typeof module !== 'undefined' && typeof module.exports !== 'undefined') {
        module.exports = classA;
    }

component.spec.ts
I am importing classA as what I did in component.ts. 
`    import * as classA from '../../classA';`

Component.ts is working perfectly but when I am running ng test, this gives an error: `TypeError: classA is not a constructor`

I tried to include it in karma.conf.js like:

    module.exports = function (config) {
      config.set({
        ...
        files: [
          "../app/classA.js"
        ]
      });
    };

And in angular.json, I added 
```"test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "karmaConfig": "./karma.conf.js",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "scripts": [
                  "../app/classA.js"
             ]
```
But still get same error. Anyone has any idea how to import JS modules in karma testing?

**Comment by johnjbarton** [comment]
Please run karma with --log-level debug or the equivalent config file value.  Look through the log output carefully to see if your file is sent to the browser. 

Try the new troubleshooting page https://github.com/karma-runner/karma/blob/2682bff15888cd88cc7e97be2e276cf1cb7f39be/docs/intro/05-troubleshooting.md
