### ISSUE TITLE
Possible issue with normalize paths in `source_files` middleware (WIN)

### ISSUE THREAD

**Issue by jeremyrajan** [karma-runner/karma#3255]
### Expected behaviour
Karma should be able to handle file paths according to the OS and `findByPath` should be able to match the test files via path.
### Actual behaviour
Karma is able to pickup the right files for test and run them when we are on *nix environments. But when running against WIN, we saw that there is a possible mismatch in the path, that `source_files` middleware uses which leads them to be skipped and later on `[web-server]` to complain with a `404`.

What we saw was:

```javascript
function findByPath (files, path) {
 /**
 * file.path respects the OS type and normalizes the path.
 * path on the other hand, doesn't respect that. Possiblily because the value is coming from 
 * `request.url` which comes from connect?
 */
  return Array.from(files).find((file) => file.path === path)
}

function createSourceFilesMiddleware (filesPromise, serveFile, basePath, urlRoot) {
  return function (request, response, next) {
    const requestedFilePath = composeUrl(request.url, basePath, urlRoot)
    // When a path contains HTML-encoded characters (e.g %2F used by Jenkins for branches with /)
    const requestedFilePathUnescaped = composeUrl(querystring.unescape(request.url), basePath, urlRoot)

    request.pause()

    log.debug(`Requesting ${request.url}`)
    log.debug(`Fetching ${requestedFilePath}`)

    return filesPromise.then(function (files) {
      // TODO(vojta): change served to be a map rather then an array
     // issue starts here :(
      const file = findByPath(files.served, requestedFilePath) || findByPath(files.served, requestedFilePathUnescaped)
```
the `request.url` path doesn't handle normalizing which leads it to not match with the `files` path dictionary that Karma has.
### Environment Details
Node: 8.9.0
- Karma version (output of `karma --version`): 3.1.4

The odd part is, this is happening with the new and old (^2.0.5) version as well. I believe, this happens somewhere up the chain or possibly where I have pointed out? 🤷‍♂️ 

Our setup includes `karma-webpack`, but as far as we saw the issue was fixed once I changed the path in karma middleware above.

** The tests are running fine on any *nix machine.

**Comment by johnjbarton** [comment]
Please try the troubleshooting guide. http://karma-runner.github.io/3.0/intro/troubleshooting.html

This is probably an issue with your config or a plugin as we run many tests on Windows.
