### ISSUE TITLE
Error in populating textarea while passing data between controllers

### ISSUE THREAD

**Issue by AB0412** [karma-runner/karma#3256]
### Expected behaviour
Text area should display the data i am parsing in a controller
### Actual behaviour
getting error as 
[$injector:unpr] Unknown provider: successcount1Provider <- successcount1 <- ViewXMLCtrl
### Environment Details

- Karma version (output of `karma --version`):
- Relevant part of your `karma.config.js` file

### Steps to reproduce the behaviour

1. I have a viewXML controller, nothing complex

///Creating controller for ViewXML - Data will be displayed in text area
angular.module('fbsiperf').controller('ViewXMLCtrl', ['$scope','successcount1',function($scope,successcount) {
//angular.module('fbsiperf').controller('ViewXMLCtrl', ['$scope',function($scope) {
	//$scope.successcount="Name";
	$scope.successcount=successcount;
	
	$scope.cancel = function() {
		$scope.$dismiss();
	}
	
}])
2.

It gets data from below function

$scope.viewXML = function() {
		//if(null != $scope.ticket && "" != $scope.ticket) {
		if(true) {
			//open modal for adding data
			var modalInstance = $uibModal.open({
				templateUrl : '../../views/templates/viewXML.html',
				controller : 'ViewXMLCtrl',
				windowClass : 'center-modal',
				backdrop : 'static',
				keyboard : false,
				size : 'lg',
				resolve : {
					successcount : function() {
							return $scope.successCount;
						//return "Name";
					}
				}
			});
		} else {
			alert("No CM# found")
		}
3.
i am displaying it in html here

<textarea rows="4" cols="50" ng-model="successcount"></textarea><br><br> 

instead of populating the text box i get error as 
$injector:unpr] Unknown provider: successcount1Provider <- successcount1 <- ViewXMLCtrl

**Comment by johnjbarton** [comment]
Looks like an angular injector error message to me.  Not related to karma-runner.
