### ISSUE TITLE
Incorrect work Karma + BrowserStack in WebStorm

### ISSUE THREAD

**Issue by NikolayMakhonin** [karma-runner/karma#3258]
### Expected behaviour

I excpect correct work Karma + BrowserStack if I run it from WebStorm

### Actual behaviour

Incorrect work Karma + BrowserStack if I run it from WebStorm
But it work correctly if I run it from console
The problem is that WebStrom is not stopped karma server after use. And in BrowserStack there is a limit - a maximum of 5 launched browsers.
`config.concurrency = 5` does not solve this problem

WebStorm (for reasons I do not understand) force set config.singleRun = false
When I try to prevent him from doing this, he stops working correctly.
```
// Do not allow WebStorm to disable singleRun:
delete config.singleRun
Object.defineProperty(config, 'singleRun', {
	value   : true,
	writable: false
})
```

I know how to make it work correctly, but for this you need to make changes to karma:
File karma\lib\server.js  line 261
```js
if (config.singleRun) {
  newBrowser.execute(config.client) // If I commented this line WebStorm starts working correctly
  singleRunBrowsers.add(newBrowser)
}
```
Making an optional shutdown of this line would be a bad decision.
But perhaps experienced developers will understand why disabling this line fixed the error. I do not understand this.

### Environment Details

- Karma version: 4.0.0
- karma-browserstack-launcher: 1.4.0

### Steps to reproduce the behaviour

If you show at least one way how to make karma + BrowserStack work in WebStorm correctly with more than 5 browsers (without errors and freezes for 5 minutes), then I can assume that the problem has been solved.

**Comment by johnjbarton** [comment]
To avoid re-execution set the config option `--no-single-run` then you will get `false` in the code:
>if (config.singleRun) {

**Comment by johnjbarton** [comment]
> the opposite to enable singleRun

Yes, that is exactly `--no-single-run`

**Comment by NikolayMakhonin** [comment]
> Yes, that is exactly `--no-single-run`

WebStorm does not provide the ability to add such parameters when running Karma. So I can't even check if it works.

**Comment by johnjbarton** [comment]
I went back to your original post:
> WebStorm (for reasons I do not understand) force set config.singleRun = false
> When I try to prevent him from doing this, he stops working correctly.

So now I understand you want karma to exit (singleRun true) but WebStorm does not support it. Ok so that is an issue with WebStorm.  karma supports running either way.  karma is working as intended here, I don't see how we can fix WebStorm.
