### ISSUE TITLE
Security Vulnerability: karma & dendency combine-lists depends on lodash < 4.17.11

### ISSUE THREAD

**Issue by joshlrogers** [karma-runner/karma#3265]
Karma itself as well as the dependency combine-lists has a dependency on lodash < 4.17.11

Combine-lists repo seems unmaintained so might need to swap out behavior.

https://tools.cisco.com/security/center/viewAlert.x?alertId=59546

**Comment by johnjbarton** [comment]
Does npm audit pass at HEAD now?
