### ISSUE TITLE
Remove warning when running Angular tests

### ISSUE THREAD

**Issue by VVKot** [karma-runner/karma#3271]
Is there a way to specify file formats which are recognized by Karma? I'm getting this warning when running tests using Angular `ng test`.
```
WARN [middleware:karma]: Invalid file type, defaulting to js. ts
```
### Expected behaviour
No warnings are displayed for *.ts *or* an option for specifying file types is provided.
### Actual behaviour
A warning is displayed.
### Environment Details
- Karma version (output of `karma --version`): 3.1.4

**Comment by johnjbarton** [comment]
You need to compile TS to JS before testing.  TS is not a language that runs in browsers or nodejs.

**Comment by VVKot** [comment]
What about svg pictures?

**Comment by johnjbarton** [comment]
Huh?

**Comment by VVKot** [comment]
I'm receiving the same error when including svg pictures to run tests(to correctly display UI). I.e.
```
WARN [middleware:karma]: Invalid file type, defaulting to js. svg
```

**Comment by johnjbarton** [comment]
This is a warning that your config specified that an SVG file should be included verbatim in the HTML file, but karma does not support this inclusion.

If you would like to add support for including SVG in HTML, see
https://github.com/karma-runner/karma/blob/c311ac00cef4a957f889ed613238793c0ffa95a2/lib/middleware/karma.js#L199
