### ISSUE TITLE
Change support to Maintenance LTS branches

### ISSUE THREAD

**Issue by martinheidegger** [karma-runner/karma#3275]
Node v6 is not quite three years old. Most of the other frameworks I use still support it. Karma is the only outlier (noted in the `node-tap` dependencies) that requires node 8. Would it be reasonable to change the support policy to LTS maintenance?

**Comment by johnjbarton** [comment]
Node v6 will exit LTS in less than 40 days.  karma 3.x still supports node 6.  We chose to move on to v8 so we could begin to leverage `async`.   I think this is a reasonable tradeoff.

**Comment by martinheidegger** [comment]
I understand that the timing is unfortunate for Node v6. I tried to make my
point generally about the Maintenance LTS status.
Node 8 is not an active LTS anymore and with your policy it seems
appropriate to drop 8 support.

**Comment by johnjbarton** [comment]
v8 is LTS Maintenance until 2020.  It seems reasonable to support it until close to that date.  Is there a problem with that?

**Comment by martinheidegger** [comment]
> works on all active LTS versions

from the docs.

**Comment by johnjbarton** [comment]
Yes, you are correct, our docs are out of date for a month. Have you tried v3.x on node 6?
