### ISSUE TITLE
Help suppressing "noise" middleware warning

### ISSUE THREAD

**Issue by plroebuck** [karma-runner/karma#3276]
**Please tell me what needs to change in the config file to turn this warning off**...
Apologies for not knowing enough about "karma" to fix my own problem...

### Desired behaviour
Elimination of this middleware warning:
`"WARN [middleware:karma]: Invalid file type, defaulting to js. browserify"`

### Actual behaviour
[Just an example](https://travis-ci.org/mochajs/mocha/jobs/471617921#L1406)

### Environment Details

- Karma version (output of `karma --version`):
**Karma v3.1.4 server** (per TravisCI output from link above)
- Relevant part of your `karma.config.js` file
[karma.conf.js](https://github.com/mochajs/mocha/blob/master/karma.conf.js)

**Comment by johnjbarton** [comment]
This warning occurs when you tell karma to 'include' a file that it does not know how to include.
In your case some file you attempted to include ended in`.browserify`.

Note that the `files` is an array of `patterns`, not an array of globs:
http://karma-runner.github.io/3.0/config/files.html

**Comment by plroebuck** [comment]
> This warning occurs when you tell karma to 'include' a file that it does not know how to include.
In your case some file you attempted to include ended in`.browserify`.

For anyone else that has this problem, the solution is to upgrade the ['karma-browserify'](https://www.npmjs.com/package/karma-browserify) module to at least v6.0.0.
