### ISSUE TITLE
Ag Grid DOM elements are not found in test

### ISSUE THREAD

**Issue by PersonaIx** [karma-runner/karma#3277]
### Expected behaviour

After following the steps on https://www.ag-grid.com/angular-getting-started/, I would expect to write a simple test like this: 
```
describe('AppComponent', () => {
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [
        AgGridModule.withComponents([]),
      ],
      declarations: [
        AppComponent
      ],
    }).compileComponents();
  }));

  it('should display ag grid', async(() => {
    const fixture = TestBed.createComponent(AppComponent);
    fixture.detectChanges();
    const compiled = fixture.debugElement;
    const outer: DebugElement = compiled.query(By.css('.ag-theme-balham'));
    expect(outer).toBeTruthy();
    const inner: DebugElement = compiled.query(By.css('.ag-root-wrapper'));
    expect(inner).toBeTruthy();
  }));
});
```

I would expect to be able to select inner, because I can see it in the DOM tree in the browser (in application and while debugging test).

### Actual behaviour

The actual behaviour is that inner is null, even though it is displayed in the browser when debugging.

### Environment Details

    "ag-grid-angular": "^20.0.0",
    "ag-grid-community": "^20.0.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",

- Relevant part of your `karma.config.js` file

### Steps to reproduce the behaviour

1. Follow steps on https://www.ag-grid.com/angular-getting-started/
2. Run test I have pasted above

**Comment by johnjbarton** [comment]
This issue is not related to karma-runner, maybe try the site with the code you posted.
