### ISSUE TITLE
What is the release strategy for Karma?

### ISSUE THREAD

**Issue by Adam-Kernig** [karma-runner/karma#3278]
Im curious as to where I can see any release strategies for Karma, a fix for the braces issue which is causing an NPM AUDIT failure has arisen and this has been fixed and moved to the master branch, however there seems to be no release?

How often does master get built and deployed?

**Comment by johnjbarton** [comment]
As needed; contributors can ask for releases.

**Comment by Adam-Kernig** [comment]
@johnjbarton when will you be performing a release?

**Comment by johnjbarton** [comment]
See #3269
