### ISSUE TITLE
Vulnerabilities in dependency 'braces'

### ISSUE THREAD

**Issue by imtheu** [karma-runner/karma#3279]
### Actual behaviour

 === npm audit security report ===  
| :---: |
| Manual Review 
Some vulnerabilities require your attention to resolve 
Visit https://go.npm.me/audit-guide for additional guidance |
 
| **Low** | **Regular Expression Denial of Service** |
| --- | --- |
| Package | braces |
| Patched in | >= 2.3.1 |
| Dependency of | karma[dev] |
| Path | karma > expand-braces > braces |
| More info | [https://npmjs.com/advisories/786](https://npmjs.com/advisories/786)

found 1 low severity vulnerability in 49786 scanned packages
  1 vulnerability requires manual review. See the full report for details.

### Environment Details

- Karma version: 4.0.0

### Steps to reproduce the behaviour

1. npm audit

**Comment by maedewiza** [comment]
duplicate https://github.com/karma-runner/karma/issues/3269
