### ISSUE TITLE
Karma Dependencies Security Vulnerabilities (NPM Audit)

### ISSUE THREAD

**Issue by hackeo1** [karma-runner/karma#3281]
### Expected behaviour
When npm audit is run I shouldn't find any vulnerability

### Actual behaviour
When npm audit is run: Found 1 low severity vulnerability

                       === npm audit security report ===                        
                                                                                
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ braces                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.3.1                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ karma [dev]                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ karma > expand-braces > braces                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/786                             │
└───────────────┴──────────────────────────────────────────────────────────────┘

### Environment Details

- Karma version (output of `karma --version`): 4.0.0

### Steps to reproduce the behaviour

* install karma@latest via npm
* run npm audit

**Comment by johnjbarton** [comment]
dupe #3269
