### ISSUE TITLE
Get more detailed output on "Invalid config file" errors

### ISSUE THREAD

**Issue by bennyn** [karma-runner/karma#3283]
### Expected behaviour

Error stack trace which tells me which lines of my config file are invalid so I know which properties Karma does not like.

### Actual behaviour

Very generic error telling the following:

> 19:01:08.496:ERROR [config]: Invalid config file!
  TypeError: karma.conf.ts: Emit skipped
    at getOutput (D:\dev\projects\wireapp\wire-web-packages\node_modules\ts-node\src\index.ts:337:15)
    at Object.compile (D:\dev\projects\wireapp\wire-web-packages\node_modules\ts-node\src\index.ts:367:11)
    at Module.m._compile (D:\dev\projects\wireapp\wire-web-packages\node_modules\ts-node\src\index.ts:413:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (D:\dev\projects\wireapp\wire-web-packages\node_modules\ts-node\src\index.ts:416:12)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)

### Environment Details

- Karma version (output of `karma --version`): 4.0.1
- Relevant part of your `karma.config.ts` file

```ts
import {Config, ConfigOptions} from 'karma';

module.exports = function(config: Config) {
  const options: ConfigOptions = {
    autoWatch: false,
    basePath: 'src',
    browsers: ['ChromeHeadless'],
    colors: true,
    concurrency: Infinity,
    files: ['**/*.ts'],
    frameworks: ['jasmine', 'karma-typescript'],
    logLevel: config.LOG_INFO,
    port: 9876,
    preprocessors: {
      '**/*.ts': ['karma-typescript'],
    },
    reporters: ['progress', 'karma-typescript'],
    singleRun: true,
  };

  config.set(options);
};
```

### Steps to reproduce the behaviour

1. Create a TypeScript Karma config like the one posted above (`karma.config.ts`)
2. Run `karma start`

**Comment by johnjbarton** [comment]
If you look up 'Invalid config file!' in our source:
https://github.com/karma-runner/karma/blob/f94284d4cf01b2b5c473e62fe32732cf744b1797/lib/config.js#L359

So the error message follows the string.  The call stack points at code outside of karma-runner.
You need to look at this line:
`at getOutput (D:\dev\projects\wireapp\wire-web-packages\node_modules\ts-node\src\index.ts:337:15)`

**Comment by bennyn** [comment]
@johnjbarton I checked the code you pointed out but then I am right on my way to debug `ts-node` but the problem may actually sit in my `karma.config.ts` code and not inside of `ts-node`.

I discovered that I can get better debugging output on a "`TypeError: karma.conf.ts: Emit skipped`" error, when I set the `noEmitOnError` property in my `tsconfig.json` to `false`. I just did that and received the following message which is much more of help:

> 06 03 2019 19:12:11.273:INFO [compiler.karma-typescript]: Compiling project using Typescript 3.3.3333
> 06 03 2019 19:12:18.447:ERROR [compiler.karma-typescript]: src/Decoder.test.ts(29,27): error TS2732: Cannot find module './test/fixtures.json'. Consider using '--resolveJsonModule' to import module with '.json' extension

So my suggestion is to mention the `noEmitOnError` compiler setting when there is an invalid configuration. Could be as simple as this:

```js
if (extension === '.ts') {
  log.error('You may get more detailed output when setting "noEmitOnError" to "false".') 
}
```
