### ISSUE TITLE
Error: [$injector:unpr] thrown by karma - CallRequest not found

### ISSUE THREAD

**Issue by kinjalhinguss** [karma-runner/karma#3285]
Hi,
I am trying to inject my 'CallRequest' service in Test while testing a controller. It should inject 'CallRequest' service and allow me to call functions from that service.

### When i am injecting 'CallRequest' in a testingController.js it is showing 
[(Error: [$injector:unpr] http://errors.angularjs.org/1.7.7/$injector/unpr?p0=CallRequestProvider%20%3C-%20CallRequest)] in terminal. 

### My code is something like this.
 **karma.conf.js** file contains array of below files
 files: [
      'bower_components/angular/angular.min.js',
      'app.js',
      'inquiry/inquiry.js',
      'shared/apiservice.js',
      'shared/services.js',
      'inquiry/callcontroller.js',
      'shared/qbchatservice.js',
      'shared/directives.js',
      'bower_components/angular-mocks/angular-mocks.js',
      'inquiry/TestCallController.spec.js'
    ],
**apiservices.js**
blitzApp.service('CallRequest', function($http,$rootScope,API_URL,$q,$rootScope) {

    this.url=API_URL;
    var _this = this;

});

**CallController.js**
inquiryapp.controller('CallController',
[ '$scope', '$rootScope', '$location', '$http',  '$state', 'CallRequest',
    function ($scope, $rootScope, $location, $http, $state, CallRequest) {
        $rootScope.deviceData = deviceDetector;
        $rootScope.localVideoTrack = null;     
    }]);

**testingController**
describe('CallController Tests',function(){

    beforeEach(module('inquiryModule'));
    var $controller;
    var $rootScope;
    var $stateParams;
    var CallRequest;
    var $http;
    var $q;
      describe('JoinCall',function(){
        beforeEach(inject(function(_$controller_,_$rootScope_,_$stateParams_,_$http_,_$q_,_CallRequest_){
            // The injector unwraps the underscores (_) from around the parameter names when matching
            $controller = _$controller_;
            $rootScope = _$rootScope_;
            $stateParams = _$stateParams_;
            $http = _$http_;
            $q = _$q_;
            CallRequest = _CallRequest_;
          
          }));
 it('it should join a call',function(){
        var scope = $rootScope.$new();
        var controller = $controller('CallController', {
            $scope: scope,
            $rootScope = _$rootScope_,
            $location : $location,
            
            $http : $http,
            $state : $state,
            CallRequest : CallRequest,
        });
            scope.meetingid = 123456789;
            scope.getLocationPermission();
            expect(scope.callinprogress).toBeDefined();
            expect(scope.callinprogress).toBe(true);
       })
    })
})
 
Please giude me on this if anything gone wrong. 
Thank you.

**Comment by johnjbarton** [comment]
> [(Error: [$injector:unpr] http://errors.angularjs.org/1.7.7/$injector/unpr?

Please consult the linke printed by the angular error message.
