### ISSUE TITLE
Testing a directive defined in a sub-module

### ISSUE THREAD

**Issue by ankita240796** [karma-runner/karma#3299]
I am writing a karma test to test a directive in a sub-module The test needs to access the controller scope of the directive and uses `$rootScope` to compile the directive and obtain the controller scope but the controllers of the sub-modules cannot be accessed by $rootScope, so the test is failing. I am unable to find any documentation on how we can test a directive defined in a sub-module. 

Can you please direct me to any documentation for how I can proceed in this case, Thanks!

**Comment by johnjbarton** [comment]
karma does not know anything about controllers or sub-modules.  My guess is that these are questions about testing Angular apps?  So try asking on StackOverFlow tagged with angular.
