### ISSUE TITLE
Karma outputs unspecified verbose info

### ISSUE THREAD

**Issue by falsandtru** [karma-runner/karma#3301]
Since Node.js 12 with Firefox. This info is also outputted with test errors and it is very annoying.

### Expected behaviour

Output only the specified data.

### Actual behaviour

```
Browser {
  id: '96848431',
  fullName: 'Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0',
  name: 'Firefox 66.0.0 (Linux 0.0.0)',
  lastResult: [BrowserResult],
  disconnectsCount: 0,
  activeSockets: [Array],
  noActivityTimeout: 100000,
  collection: [BrowserCollection],
  emitter: [Server],
  socket: [Socket],
  timer: [Object],
  disconnectDelay: 2000,
  log: [Logger],
  noActivityTimeoutId: Timeout {
    _idleTimeout: 100000,
    _idlePrev: [TimersList],
    _idleNext: [TimersList],
    _idleStart: 34033,
    _onTimeout: [Function],
    _timerArgs: undefined,
    _repeat: null,
    _destroyed: false,
    [Symbol(refed)]: true,
    [Symbol(asyncId)]: 28047,
    [Symbol(triggerId)]: 28045
  },
  pendingDisconnect: null,
  state: 'EXECUTING'
}
```

### Environment Details

- Karma version (output of `karma --version`): 4.1.0
- Relevant part of your `karma.config.js` file: https://github.com/falsandtru/spica/blob/master/karma.conf.js

### Steps to reproduce the behaviour

https://travis-ci.org/falsandtru/spica/jobs/524330826#L508-L537

**Comment by johnjbarton** [comment]
That looks like the result of `console.log(browser)`  though of course the variable name could differ. This is not part of karma-runner AFAICT. (Also your config is for chrome, not firefox).  Consider installing locally and grep all files for "console\.log\("

**Comment by falsandtru** [comment]
SEE THE LOG CAREFULLY. Tests are run with Chrome and Firefox. And Chrome doesn't output such annoying info.

**Comment by johnjbarton** [comment]
Well the config you posted shows `browsers: ['Chrome']`, no firefox.

But since this does not happen in chrome, it almost certainly is not karma-runner but rather a firefox-specific karma plugin.

**Comment by falsandtru** [comment]
>Well the config you posted shows browsers: ['Chrome'], no firefox.

Firefox come from https://github.com/falsandtru/spica/blob/master/gulpfile.js#L16.

>But since this does not happen in chrome, it almost certainly is not karma-runner but rather a firefox-specific karma plugin.

Opened https://github.com/karma-runner/karma-firefox-launcher/issues/90.

**Comment by kurkle** [comment]
Its not actually dependent on plugin, last one of multiple plugins is output.
Probably same issue as #3305 though (`util.format` dumping the object in node 12).
