### ISSUE TITLE
Karma ignore VueJS test with <style>

### ISSUE THREAD

**Issue by throrin19** [karma-runner/karma#3302]
### Expected behaviour

All my tests are executed and, if my configuration is not valid to compile correctly my code, return error

### Actual behaviour

When I have to compile other code than JS (json, inline VueJS <style>, CSS import file, ...), Karma ignore this specific test file without any information about this.

I try without the <style> attribute on tested component and the test execute fine.

I create already an issue in the @poi project : https://github.com/egoist/poi/issues/562

And after research, I saw other people have this error with only Karma and VueJS : https://stackoverflow.com/questions/53817120/single-file-vue-component-tests-wont-run-if-style-is-tag-is-in-file

### Environment Details

- Karma is used by the @poi/plugin-karma version 13.0.2

**Comment by devoto13** [comment]
In essence Karma takes a list of files, adds these files to the HTML page and opens this page in the browser. Once page is loaded the code included in the page runs and reports test results back to Karma using its API.

So you take something which browser does not understand, process it with something which is not in any way related to Karma to produce something browser can understand and ask Karma to include this processed something into the page. Karma never sees any of your Vue single file components in whatever format they are, it sees the result produced by the bundler and includes it in the test page. If some tests are not included, then your bundler has produced an incorrect bundle and Karma has no way to know if it is correct or not and can not produce any error or warning to help you.

Closing as this is not an issue with Karma, but either with a bundler or your configuration.
