### ISSUE TITLE
istanbul is deprecated use other options

### ISSUE THREAD

**Issue by santoshyadav198613** [karma-runner/karma#3306]
### Expected behaviour

As Istanbul is already deprecated and no longer maintained let's move to other options 

https://www.npmjs.com/package/istanbul

Other options: https://istanbul.js.org/integrations
### Environment Details

- Karma version (output of `karma --version`):
- Relevant part of your `karma.config.js` file

### Steps to reproduce the behaviour

1.
2.
3.

**Comment by johnjbarton** [comment]
Istanbul is not used directly by karma and multiple coverage options can be supported with plugins. You can write one today! Here is the documentation for contributors.
http://karma-runner.github.io/3.0/dev/contributing.html
