### ISSUE TITLE
Karma server exits once tests are successfully completed

### ISSUE THREAD

**Issue by ezl-13** [karma-runner/karma#3310]
### Expected behaviour
After running all of the tests, it should echo "Done!" I am using Docker in conjunction with karma. 

### Actual behaviour
![image](https://user-images.githubusercontent.com/21316782/57824604-6fe6da80-7750-11e9-9427-d4936674f6cd.png)
................. [more successful tests]...........................
![image](https://user-images.githubusercontent.com/21316782/57824632-8a20b880-7750-11e9-96ba-254f38ead42f.png)

The server is closed after all the tests run, and localhost:9876 closes. 
Any thoughts? Thanks!

**Comment by johnjbarton** [comment]
Looks like a successful run with singleRun=true. Check your final configuration print in the debug log.

**Comment by ezl-13** [comment]
I see. Where can I find the debug log?

**Comment by johnjbarton** [comment]
Your output looks like logLevel=debug, just look for the config further up
