### ISSUE TITLE
why the test result no the same ?

### ISSUE THREAD

**Issue by cleverboy32** [karma-runner/karma#3319]
### Environment Details

- Karma version 4.1.0
```
var webpackConfig = require('../../build/webpack.test');

module.exports = function (config) {
    config.set({
        // to run in additional browsers:
        // 1. install corresponding karma launcher
        //    http://karma-runner.github.io/0.13/config/browsers.html
        // 2. add it to the `browsers` array below.
        browsers: ['Chrome'],
        frameworks: ['mocha', 'sinon-chai'],
        reporters: ['spec', 'coverage'],
        files: ['../../node_modules/babel-polyfill/dist/polyfill.js', './index.js'],
        preprocessors: {
            './index.js': ['webpack', 'sourcemap']
        },
        webpack: webpackConfig,
        webpackMiddleware: {
            noInfo: true
        },
        coverageReporter: {
            dir: './coverage',
            reporters: [
                {
                    type: 'lcov',
                    subdir: '.'
                },
                {
                    type: 'text-summary'
                }
            ]
        }
    });
};
```

### Steps to reproduce the behaviour

1. when i test all files, some file show the result wrong, but when i want to fix the file , so i test the file single .there is no error, its test pass.  why ?

**Comment by devoto13** [comment]
Probably one of your tests does not cleanup after itself. Let's say test B modifies some variables and doesn't reset them to original values. Then test A relies on this variables and fails if test B was run, but works if it was not. This sounds more like issue with your tests and not with Karma.

**Comment by cleverboy32** [comment]
ops, it because i use  vue-test-utils . it influences my old files test . when i remove it , my test work good. 
its really make me feel sick.......
