### ISSUE TITLE
Random Files Skipped

### ISSUE THREAD

**Issue by mlucool** [karma-runner/karma#3327]
### Expected behaviour
All tests in all files should always be run always run.

### Actual behaviour
Some test files are not run. By not run, I mean that karma does not even list it as a test case. It is as if that file does not exist. The number of tests karma finds decreases.

I have found I can reproduce this in my setup when a test has an async expect statement that fails when the test is correctly written for callbacks.
```
it('does something', () => {
    setTimeout(() => {
        expect(10).to.eql(4);
    }, 10);
});
```
### Environment Details
- Karma version (output of `karma --version`):
4.1.0

**Comment by johnjbarton** [comment]
I guess that you are using karma-jasmine? (The test framework is not part of karma-runner).

The test above is incorrect.  A correct version would be:
```js
it('does something', (done) => {
    setTimeout(() => {
        expect(10).to.eql(4);
       done();
    }, 10);
});
```
See https://jasmine.github.io/tutorials/async

**Comment by mlucool** [comment]
@johnjbarton I had a typo, my bad! I mean to say when the test is incorrectly written for callbacks.

**Comment by mlucool** [comment]
@johnjbarton can we reopen this request?

**Comment by johnjbarton** [comment]
I don't see a practical way for karma-runner to do anything in this case. karma-runner has no idea what your tests do or don't do.  It simply bundles your tests with your test framework, puts them in the browser and waits for test results. 

jasmine or karma-jasmine maybe able to detect that the it() block was executed but the callback never occurred. I believe that jasmine 3.x does that , but you don't say what framework you are running.

**Comment by mlucool** [comment]
@johnjbarton thanks for the info. I am running karma-mocha@1.3. It sounds like this ticket should be opened there instead.
