### ISSUE TITLE
Unable to karma tests it says Found 8 load errors

### ISSUE THREAD

**Issue by j41b4l4j1** [karma-runner/karma#3330]
### Expected behaviour
Unable to karma tests
### Actual behaviour
Karma v4.0.0 server started at http://0.0.0.0:9876/
INFO [launcher]: Launching browsers PhantomJS with concurrency unlimited
[karma-server]: Error: Found 8 load errors at Server.webServer.listen (C:\Users\*****\AppData\Roaming\npm\node_modules\karma\lib\server.js:182:27
### Environment Details
Windows
- Karma version (output of `karma --version`):~0.12.0

- Relevant part of your `karma.config.js` file

### Steps to reproduce the behaviour

1.npm start
2.
3.

**Comment by johnjbarton** [comment]
Run with logLevel DEBUG to figure out what you have wrong (maybe missing plugins?)
http://karma-runner.github.io/4.0/config/configuration-file.html
