### ISSUE TITLE
10x slowdown in 0.5.8 after 0.4.0

### ISSUE THREAD

**Issue by ahaurw01** [karma-runner/karma#334]
Anecdotal evidence of troublesome performance decreases in 0.5.8:

I have a suite of about 150 tests being run with the mocha adapter in phantomjs. Using 0.4.0 these tests finish within a little over 1 second. Upgrading to 0.5.8 sees a running time of around 11 seconds. 

Is anyone else seeing these results?

**Comment by Dignifiedquire** [comment]
Closing this for now due to inactivity. Feel free to open a new issue with current information if this is still a problem.
