### ISSUE TITLE
New Version 4.2.0 crashes tests

### ISSUE THREAD

**Issue by NtgJoshi** [karma-runner/karma#3340]
### Actual behaviour
/node_modules/karma/node_modules/braces/lib/compile.js:39
08:18:52       let range = fill(...args, { ...options, wrap: false, toRegex: true });
08:18:52                                   ^^^
08:18:52 SyntaxError: Unexpected token ...
08:18:52     at createScript (vm.js:53:10)
08:18:52     at Object.runInThisContext (vm.js:95:10)
08:18:52     at Module._compile (module.js:543:28)
08:18:52     at Object.Module._extensions..js (module.js:580:10)
08:18:52     at Module.load (module.js:488:32)
08:18:52     at tryModuleLoad (module.js:447:12)
08:18:52     at Function.Module._load (module.js:439:3)
08:18:52     at Module.require (module.js:498:17)
08:18:52     at require (internal/module.js:20:19)
08:18:52     at Object.<anonymous> (/home/.../node_modules/karma/node_modules/braces/index.js:4:17)
08:18:52     at Module._compile (module.js:571:32)
08:18:52     at Object.Module._extensions..js (module.js:580:10)
08:18:52     at Module.load (module.js:488:32)
08:18:52     at tryModuleLoad (module.js:447:12)
08:18:52     at Function.Module._load (module.js:439:3)
08:18:52     at Module.require (module.js:498:17)

### Environment Details
- Karma version 4.2.0

**Comment by NtgJoshi** [comment]
downgrade to 4.1.0 solves issue

**Comment by devoto13** [comment]
Probably you run older version of Node, then Karma requires to run.

**Comment by NtgJoshi** [comment]
I have node 7. I´ll try it with a newer version
