### ISSUE TITLE
Consolidated report display the test run result across multiple library in Nrwl Nx based Workspace

### ISSUE THREAD

**Issue by sameerinfodb** [karma-runner/karma#3346]
Hi Karma team,

### Expected behaviour
We are working with Nrwl Nx Workspace which consist of  multiple library and we want to run all the test using karma 4.0.0 and generate a single file displaying the result of the test executed by Karma test Runner.

### Actual behaviour

Currently , Report generated by karma-html-detailed-reporter reports only the latest project got executed.  

### Environment Details
   "karma": "~4.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-firefox-launcher": "^1.1.0",
    "karma-html-detailed-reporter": "^2.1.0",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",

Can you please suggest how to consolidate the result of all the test execution in one html file.

**Comment by johnjbarton** [comment]
I don't know enough about your setup to know your issue, but the 'reporter' api is simple: you could write a custom reporter for your use case.

**Comment by sameerinfodb** [comment]
@johnjbarton  basically , what we are looking is consolidate report of test run across all library and app in the nx workspace (nx.dev).

**Comment by johnjbarton** [comment]
Well I have no idea what an 'nx' is but it sounds like you need a 'karma-nx-reporter'.  Lots of examples for 'karma-*-reporter' around, shouldn't be too hard.
