### ISSUE TITLE
karma uses a vulnerable version of lodash

### ISSUE THREAD

**Issue by michdsouza** [karma-runner/karma#3349]
karma uses a vulnerable version of lodash, see https://www.npmjs.com/advisories/1065 for more details on the security issue.
lodash >=4.17.12 is patched.

| high          | Prototype Pollution                                                       |   
|---------------|---------------------------------------------------------------------------|
| Package       | lodash                                                                    |
| Patched in    | >=4.17.12                                                                 |
| Dependency of | karma                                                                     |
| Path          | karma > lodash                                                            |
| More info     | https://www.npmjs.com/advisories/1065                                     |

**Comment by Karolis92** [comment]
old lodash is probably locked in your `package-lock.json`
run `npm audit fix` That helped me

**Comment by johnjbarton** [comment]
Please update. karma uses lodash 4.17.14, past the point of the patch.

**Comment by brycekahle** [comment]
@johnjbarton There isn't a released version of karma with your change in https://github.com/karma-runner/karma/commit/5614c040f2e84d74ec95227c23d634356fbf5b60#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
