### ISSUE TITLE
Tests are not running with Angular Module specific providedIn-Dependency mechanism

### ISSUE THREAD

**Issue by ENM1989** [karma-runner/karma#3350]
### Expected behaviour
Tests should run.

### Actual behaviour
Tests are not running.

### Environment Details
- Karma version: 4.2.0

### Steps to reproduce the behaviour
1. Provide a service within a specific Module `@Injectable({providedIn: MyModule})`
2. Run the tests with "ng test"
3. Karma will not run any further than "[middleware:source-files]: Fetching /_karma_webpack_/vendor.js"

4. Try the same with `@Injectable({providedIn: 'root'})` and the tests will run.

**Comment by johnjbarton** [comment]
Try the project which supplies `ng test` and `@Injectable`.  These are not karma-runner things.
