### ISSUE TITLE
Karma is using ranges for its releases in package.json

### ISSUE THREAD

**Issue by jeremy-dobler** [karma-runner/karma#3353]
### Expected behaviour
Builds that are hardcoded to a specific version should not break if one of karma's dependencies decides to update their version.
### Actual behaviour
https://github.com/karma-runner/karma/blob/master/package.json#L409
Karma has a version of ^2.6.0 for rimraf. Rimraf updated their version to 2.7.0 (modified the major version which means the change is NOT backwards compatible according to semvar). After they released rimraf@2.7.0, builds that used karma and an older version of nodejs stopped working. Rimraf changed their code to use ES6 (i.e let variable), this broke the build scripts for old builds. Karma should NOT be using "^" in its package.json bc this will cause previous releases to no longer be buildable when one of karma's dependencies is changed. Rimraf is needing to undo their release because of this breakage which I disagree with as Rimraf followed correct semvar standards and updated their major version when they made a backwards breaking change. https://github.com/isaacs/rimraf/issues/194
### Environment Details

- Karma version (output of `karma --version`):
- Relevant part of your `karma.config.js` file
NodeJS version: 5.6.0
Karma version in package.json: 0.13.22

### Steps to reproduce the behaviour

1.npm install with above nodeJS and karma version in package.json
2.See error thrown https://github.com/isaacs/rimraf/issues/194
3.

**Comment by johnjbarton** [comment]
Dependence on ^2.6.0 rimraf does not allow v2.7.0. https://nodesource.com/blog/semver-tilde-and-caret/.

From your post:
```
Relevant part of your karma.config.js file
NodeJS version: 5.6.0
Karma version in package.json: 0.13.22
```

This version of karma is not supported, nor the version of nodejs.  Please update.
