### ISSUE TITLE
karma 4.1.0, angular/cli 8, ng test, karma.conf.js, failOnEmptyTestSuite: false is ignored. why?

### ISSUE THREAD

**Issue by maks187** [karma-runner/karma#3362]
### Expected behaviour

The karma.conf.js conf key failOnEmptyTestSuite is documented. Setting it on false still lead to failed test if no spec files exist. Why?

### Actual behaviour

Should work as aspected.

### Environment Details

- Karma version (output of `karma --version`):
4.1.0

- Relevant part of your `karma.config.js` file
,failOnEmptyTestSuite: false,

### Steps to reproduce the behaviour

10 09 2019 14:57:05.029:INFO [karma-server]: Karma v4.1.0 server started at http://0.0.0.0:9821/
10 09 2019 14:57:05.030:INFO [launcher] 63% building 443/444 modules 1 active ...TestApp\src\main\webapp\styles_src.scss10 09 2019 14:57:05.421:INFO [launcher]10 09 2019 14:57:14.540:INFO [Chrome 71.0.3563 (Windows 10.0.0)]: Connected on socket Hd16OOjub-O3-pJ3AAAA with id 73285272
Chrome 71.0.3563 (Windows 10.0.0): Executed 0 of 0 SUCCESS (0 secs / 0 secs)
Chrome 71.0.3563 (Windows 10.0.0): Executed 0 of 0 ERROR (0.017 secs / 0 secs)

**Comment by johnjbarton** [comment]
This feature is tested and works for us.  Please try running with --logLevel=debug and look at the final configuration printed to verify that the flag is set.  (v4.3 has a cleaner output for the final config).

**Comment by maks187** [comment]
I have to wait till we are going to release the next iteration. I have worked around that by defining an dummy test on every reference app we have. Hopefully this is fixed correctly on Angular 9. But a config-switch which was only created to prevent this should work as expected :) Thank you.

**Comment by cbejensen** [comment]
Upgrading to `karma@4.3.0` fixed it for me. `ng test <lib>` now returns exit code 0 when all tests are pending.

**Comment by johnjbarton** [comment]
Thanks for the update!
