### ISSUE TITLE
Karma Configuration Issue on JavaScript 1.8. Karma Doesn't run any test cases. 

### ISSUE THREAD

**Issue by maddykws** [karma-runner/karma#3365]
###JS version: 1.8
### Expected behaviour
Should run the unit test cases. After starting the server, the test runner open but doesn't run anything. 
- Karma version (output of `karma --version`): 
4.0.1
- Relevant part of your `karma.config.js` file
[process.env.CHROME_BIN = require('puppeteer').executablePath();

const path = require('path');
const webpackConfig = require('./webpack.dev.config.js');
const basePath = path.join(__dirname, './');
const fireballDev = String(process.env. ** ).toLowerCase() === "true";
webpackConfig.entry = undefined;
webpackConfig.output = undefined;
webpackConfig.plugins = [];

let preprocessors = {};
preprocessors[( ** ? '../../test/' : '') + 'scripts/**/*_test.js'] = 'webpack';

module.exports = (config) => {
config.set({
    basePath: basePath,
    failOnEmptyTestSuite: false,
    frameworks: ['jasmine'],
    files: [
        //path to the files 
    ],
    webpack: webpackConfig,
    preprocessors: preprocessors,
    webpackMiddleware: {
        stats: 'normal'
    },
    reporters: ['progress'],
    port: 9876, // karma web server port
    colors: true,
    logLevel: config.LOG_INFO,
    browsers: ['Chrome'],
    customLaunchers: {
        ChromeHeadlessNoSandbox: {
            base: 'ChromeHeadless',
            flags: ['--no-sandbox']
        }
    },
    autoWatch: true,
    singleRun: false, // Karma captures browsers, runs the tests and exits
    concurrency: Infinity,
    plugins: [
        'karma-jasmine',
        'karma-chrome-launcher',
        'karma-webpack'
    ]
});](url)](url)

**Comment by johnjbarton** [comment]
Try `--logLevel=DEBUG` and the most recent karma release.  The information here is not enough to make any guesses.
