### ISSUE TITLE
Autowatch stopped working

### ISSUE THREAD

**Issue by thebpmgroup** [karma-runner/karma#3366]
### Expected behaviour

running from command line using ng test with configuration file having autowatch set to true and restartOnFileChange also set to true, when changing a spec file the karma test runner would re-run the tests.

### Actual behaviour

It runs the tests once on start up and then does nothing more, even if you change a spec file and save the changes

### Environment Details

config file
`module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular-devkit/build-angular/plugins/karma')
    ],
    client: {
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    coverageIstanbulReporter: {
      dir: require('path').join(__dirname, '../coverage/bpmgroup'),
      reports: ['html', 'lcovonly', 'text-summary'],
      fixWebpackSourcePaths: true
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    //logLevel: config.LOG_INFO,
    logLevel: config.DEBUG,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false,
    restartOnFileChange: true
  });
};`

- Karma version (output of `karma --version`): Command 'karma' not found, however Karma v4.1.0 server is reported by ng.
- Relevant part of your `karma.config.js` file
`autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false,
    restartOnFileChange: true`

### Steps to reproduce the behaviour

1. Write spec
2. Run ng test
3. change spec and save file

**Comment by johnjbarton** [comment]
Our watcher works so I have no idea why yours does not.

**Comment by johnjbarton** [comment]
You can try `--logLevel=debug` to verify that your watcher is loaded.

**Comment by devoto13** [comment]
I've tried this with the freshly generated Angular CLI application and tests are indeed re-run after editing a spec file. Your error is likely a misconfiguration or environment-specific. In either case we can't really do anything to resolve it without being able to reproduce it. Please open a new issue providing a minimal reproduction of this behaviour if you still experience the problem.
