### ISSUE TITLE
Karma freezes randomly when we try to run karma.

### ISSUE THREAD

**Issue by rWeave** [karma-runner/karma#3389]
Hi all,
When i use the default install from: 
```
npm init @open-wc
```
karma start randomly freezes, when i put on the debug log for karma i see that is freezes at the following line:
```
21 10 2019 11:22:02.372:DEBUG [middleware:karma]: Serving customContextFile /open-wc-test/node_modules/@open-wc/karma-esm/src/esm-context.html
21 10 2019 11:22:02.376:DEBUG [web-server]: serving: /open-wc-test/node_modules/@open-wc/karma-esm/src/esm-context.html
21 10 2019 11:22:02.392:DEBUG [web-server]: serving: /open-wc-test/node_modules/karma/static/context.js
```
It doesn't give any warning or error message when i interrupt the command. So i don't know what went wrong. Had anyone else this experience and maybe have a solution to how to fix karma not working all the time.

### Environment Details

- Karma version is 4.3.0
- OSX version 10.14.6
- Open-wc version ^2.3.4
- Relevant part of your `karma.config.js` file
```
const { createDefaultConfig } = require('@open-wc/testing-karma');
const merge = require('webpack-merge');

module.exports = config => {
  config.set(
    merge(createDefaultConfig(config), {
      logLevel: config.LOG_DEBUG,
      files: [
        // runs all files ending with .test in the test folder,
        // can be overwritten by passing a --grep flag. examples:
        //
        // npm run test -- --grep test/foo/bar.test.js
        // npm run test -- --grep test/bar/*
        { pattern: config.grep ? config.grep : '/**/*.test.js', type: 'module' },
      ],

      esm: {
        nodeResolve: true,
      },
      // you can overwrite/extend the config further
    }),
  );
  return config;
};
```

### Steps to reproduce the behaviour
1. karma start --auto-watch=true --single-run=false --no-cache

**Comment by johnjbarton** [comment]
If thing I would try is to open the browser development tools and see what is going in the browser. You can try running with `--logLevel=debug` to see if you learn more.  I doubt karma is "freezing", it is just waiting for your tests to do something.   If your test or app code fall over or burn all the CPU karma has no way to help.

**Comment by rWeave** [comment]
But it's the basic open-wc install that does that as well. I already put on the debug mode and the only output i've got is written above.

**Comment by johnjbarton** [comment]
Ok so I suggest you investigate open-wc, it's not something I'm familiar with.

Do you see anything in the browser?  Do you learn anything from opening the devtools? Errors? Is the JS runtime running event?
What happens if you run without flags?

**Comment by rWeave** [comment]
There arn't any errors it just freezes, i cannot find anything in the devtools as well thats seems wrong or explains more. I found that more people experience the same problem as you can see here:
[https://github.com/karma-runner/karma-chrome-launcher/issues/63](Chrome hangs on new start)

**Comment by johnjbarton** [comment]
In the `singleRun=false` case, look in the log that karma prints to find the port it uses, probably 9876. Then open a desktop browser on localhost:<that port>. Open devtools. Is your test code loaded in to context.html?

**Comment by rWeave** [comment]
> In the `singleRun=false` case, look in the log that karma prints to find the port it uses, probably 9876. Then open a desktop browser on localhost:. Open devtools. Is your test code loaded in to context.html?

I know what you describe already did that as well to make it more concrete this would maybe explain it better:

[Chrome(Headless) randomly not running all tests and no errors reported.](https://github.com/karma-runner/karma-chrome-launcher/issues/213)

**Comment by johnjbarton** [comment]
What happens if you run a trivial test with none of your app code?

**Comment by rWeave** [comment]
It was my fault, i searched al the files in my project folder with:
`**/*.test.ts`
So it wouldn't exclude node_modules thats why it was idle and wouldn't run instant or fast.

I've changed it to:
`src/**/*.test.ts`
