### ISSUE TITLE
handled errors should not make the spec fail

### ISSUE THREAD

**Issue by MichaelOdumosu57** [karma-runner/karma#3393]
the title says what is meant if the jasmine spec receives an exception and my code handles it, the spec should not fail, the spec should continue 
to test the feature that I expect to pass in my code. Karma is the test runner for my jasmine testing framework in my Angular 7 project, they told me come here so im here
[errorHandled-memory-leak.zip](https://github.com/karma-runner/karma/files/3793760/errorHandled-memory-leak.zip)

## Expected Behavior
if the test code handles an error jasmine should not fail becuase an exception is thrown by the js code

## Current Behavior
onerror, the spec fails even though the js fn handles the error 

## Suite that reproduces the behavior (for bugs)
src/app/e-dispatch.component.spec.ts
inline (same content
import { async, ComponentFixture, TestBed } from '@angular/core/testing';

import { EDispatchComponent } from './e-dispatch.component';

describe('EDispatchComponent', () => {
  let component: EDispatchComponent;
  let fixture: ComponentFixture<EDispatchComponent>;

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [ EDispatchComponent ]
    })
    .compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(EDispatchComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });

  it('should not fail other test if I call AfterViewInit w the dispatch invocation inside create', () => {
    spyOn(component,'ngAfterViewInit').and.callThrough()
    component.ngAfterViewInit()
  });  

  it('its not supposed to fail but if the code it tested sees an exceptioon it wil fail', () => {
    expect(component).toBeTruthy();
  });  

  it('its not supposed to fail but if the code it tested sees an exceptioon it wil fail', () => {
    expect(component).toBeTruthy();
  });  
  
  it('its not supposed to fail but if the code it tested sees an exceptioon it wil fail', () => {
    expect(component).toBeTruthy();
  });  
  
  it('its not supposed to fail but if the code it tested sees an exceptioon it wil fail', () => {
    expect(component).toBeTruthy();
  });    
});
)

## Context
I perform CI on my web app to deal with nasty bugs but how can I use this framework when I have to spend time on recreating the production environment
and having test fail on simulation that is given wrong weight values almost as if its telling me how I should code my work. this is a a base version as most bug reports request
but if you contact me to see the actual bug where the error is handled not by throwing an error but by handling the event trigger with a different event trigger contact me.
Jasmine should not automate what fails or passes in the realm of programming language features such as no-ops and error handling, the developer should always decide

## Your Environment
System: Linux Ubuntu 16.04.5 Xenial
System Architecture: amd64
node -v 10.17.0
npm - 6.11.3
Angular 7.2.0
Karma: 4.0.0
Jasmine: 2.99.1
refer to ./package.json ./package.lock-json and src/karma.conf.js  to better replicate

Developer bug filing format

System: Linux Ubuntu 16.04.5 Xenial
System Architecture: amd64
node -v 10.17.0
npm - 6.11.3
refer to ./package.json ./package.lock-json and src/karma.conf.js  to better replicate

description: window dispatchEvent in app code causes memory leak and specs to fail in different areas of the application

solution: use another framework

attempt scripts: ErrorComponent.spec.ts

command: ng test
run command inside directory of Angular 7 project

path to attempts: ./

file sturture : Angular 7 project file structure, expect the specific spec to be found in /src/app/e-dispatch

**Comment by johnjbarton** [comment]
Issues in jasmine need to be reported to jasmine.  Karma is only reporting what jasmine tells it to report.  

Nevertheless I encourage you too look again at your example.  In general jasmine already handles these kinds of cases correctly.  One case it cannot handle are errors in the code outside of its execution, for example errors in defining the test functions.   Another case it cannot handle is exceptions in async functions that have no `catch()` functions chained. Such exceptions are triggered out of the scope of Jasmine.  Maybe one of these cases apply to your case.
