### ISSUE TITLE
Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

### ISSUE THREAD

**Issue by pooja-tester** [karma-runner/karma#3394]
### Environment Details

- Karma version (output of `karma --version`):
- Relevant part of your `karma.config.js` file

### Steps to reproduce the behaviour

1.
2.
3.

**Comment by johnjbarton** [comment]
You will need to fix your tests, not an issue in the runner.
