### ISSUE TITLE
Modify ng update behavior

### ISSUE THREAD

**Issue by SAkhil95** [karma-runner/karma#3397]
### Expected behaviour

**ng update karma** updates: 

1. "karma"
2. "karma-chrome-launcher"
3. "karma-coverage-istanbul-reporter"
4. "karma-jasmine": "~2.0.1"
5. "karma-jasmine-html-reporter"

### Actual behaviour

**ng update karma** updates, only: 

1. "karma"

### Environment Details

- Karma version (output of `karma --version`): 4.4.1
- Relevant part of your `karma.config.js` file

### Steps to reproduce the behaviour

1. Update an existing Angular 7 app to Angular 8 which wont update devDependencies by default.
2. Do, ng update karma
3. You can notice only karma gets updated, rest all others mentioned in expected behavior wont update

**Comment by johnjbarton** [comment]
Please report this issue to the project that supplies "ng".
