### ISSUE TITLE
Can Karma be configured to throw an error if a file is not found?

### ISSUE THREAD

**Issue by Taytay** [karma-runner/karma#3398]
### (desired) Expected behaviour
Karma throws an error and exits with an error code if a specified file cannot be found

### Actual behaviour
Karma logs a warning to the console, which is easy to miss: 
`WARN [filelist]: Pattern "/some/absolute/path.js" does not match any file.`

### Environment Details

- Karma version (output of `karma --version`): 4.2.0
- Relevant part of your `karma.config.js` file
files: 

### Steps to reproduce the behaviour

1. Specify a file in the `files` array that does not exist.
2. Run Karma
3. Observe the warning, but no error.

I thought there would be something like `required: true` in the Files options, but I didn't see that: http://karma-runner.github.io/4.0/config/files.html

**Comment by Russianze** [comment]
Currently, karma uses the minimatch library which does not throw errors.
The best solution would be to write a test:
```
"use strict";
describe('check files', function() {
let files = [ '**/*.module.js' ];
var minimatch = require("minimatch");
var find = require('fs-find'), path = process.cwd();
find(path, function(err, results) {
  if(err)
    expect('error find').toBe(true);
  let c = 0;
  for(let f of files) {
    for(let el of results) {
        if(minimatch(el.file, f))
          c++;
     if(c == 0)
       except(f).toBe('does not match any file');
    }
  }
}
});
```
And put this test before of all tests

**Comment by johnjbarton** [comment]
I would like to see an option to fail the test in case a pattern does not match.  We have some setups where we pass full paths as patterns and failure to match is an error then.

**Comment by johnjbarton** [comment]
Please see #3442
