### ISSUE TITLE
Karma incorrectly reports [main] attribute deprecation on base Ionic 4 application

### ISSUE THREAD

**Issue by daviddickson** [karma-runner/karma#3404]
### Expected behaviour
No warnings related to the [main] attribute when using the correct syntax

### Actual behaviour
Warnings are displayed that the syntax is deprecated even though the syntax doesn't exist in the project.

### Environment Details
Karma version: 4.1.0

### Steps to reproduce the behaviour

1. Start a new Ionic project with Angular as the codebase and sidemenu as the starter template.
2. Go the project and run `npm run test'

This will be the resulting logging:
```
WARN: '[DEPRECATED][ion-menu] Using the [main] attribute is deprecated, please use the "contentId" property instead:
BEFORE:
  <ion-menu>...</ion-menu>
  <div main>...</div>

AFTER:
  <ion-menu contentId="my-content"></ion-menu>
  <div id="my-content">...</div>
```

It is reporting on this html, which is correct based on https://ionicframework.com/docs/api/split-pane#usage. There is no [main] attribute in this html.
```
<ion-app>
  <ion-split-pane contentId="main-content">
    <ion-menu contentId="main-content" type="overlay">
      <ion-header>
        <ion-toolbar>
          <ion-title>Menu</ion-title>
        </ion-toolbar>
      </ion-header>
      <ion-content>
        <ion-list>
          <ion-menu-toggle auto-hide="false" *ngFor="let p of appPages">
            <ion-item [routerDirection]="'root'" [routerLink]="[p.url]">
              <ion-icon slot="start" [name]="p.icon"></ion-icon>
              <ion-label>
                {{p.title}}
              </ion-label>
            </ion-item>
          </ion-menu-toggle>
        </ion-list>
      </ion-content>
    </ion-menu>
    <ion-router-outlet id="main-content"></ion-router-outlet>
  </ion-split-pane>
</ion-app>
```

**Comment by johnjbarton** [comment]
Please report this to whatever code is responsible for emitting the incorrect warning.
