### ISSUE TITLE
Strange warning: All files matched by "./app/*!(.module|_test).js" were excluded or matched by prior matchers

### ISSUE THREAD

**Issue by Russianze** [karma-runner/karma#3408]
### Environment Details
Karma 6.13.4
karma.conf.js:
```
module.exports = function(config) {
  config.set({

    basePath: './app',

    files: [
      'lib/angular/angular.js',
      'lib/angular-route/angular-route.js',
      'lib/angular-aria/angular-aria.js',
      'lib/angular-animate/angular-animate.js',
      'lib/angular-messages/angular-messages.js',
      'lib/angular-material/angular-material.js',
      '../node_modules/angular-mocks/angular-mocks.js',
      '../node_modules/angular-material/angular-material-mocks.js',
      '**/*.module.js',
      '*!(.module|_test).js',
      '!(lib)/**/*!(.module|_test).js',
      '**/*_test.js'
    ],

    autoWatch: true,

    frameworks: ['jasmine'],

    browsers: ['Chrome'],

    plugins: [
      'karma-chrome-launcher',
      'karma-firefox-launcher',
      'karma-jasmine'
    ]

  });
};
```

### Expected behaviour

1. all the necessary modules are connected first
2. '**/*.module.js'- all the modules I created are connected
3. '*!(.module|_test).js' - loads everything in the ./app folder except for modules and tests, but not in subfolders
4. '!(lib)/**/*!(.module|_test).js' - all folders in the ./app folder except the lib folder, all the files inside these folders except modules and tests
5. '**/*_test.js' - all tests in child folders ./app

### Actual behaviour
Throws two warnings:
```
14 01 2020 11:42:00.324:WARN [filelist]: All files matched 
by "./app/*!(.module|_test).js" were excluded or matched by prior matchers.
14 01 2020 11:42:00.329:WARN [filelist]: All files matched 
by "./app/**/*_test.js" were excluded or matched by prior matchers.
```
Although these files were not included before these expressions, I don’t understand why these warnings came from

### Steps to reproduce the behaviour

1. karma start

**Comment by johnjbarton** [comment]
You clearly know more about the matching than I do, but I would verify that files named `_test.js` really existed in `./app`.  And I would look at the output of `--logLevel=DEBUG`
