### ISSUE TITLE
Unexpected token '.' when trying to start tests

### ISSUE THREAD

**Issue by sebastianroming** [karma-runner/karma#3417]
### Expected behaviour
Karma should run like a charm.

### Actual behaviour
Receiving an error as soon as `context.js` is served:
```
05 02 2020 12:23:07.973:DEBUG [middleware:karma]: Serving static request /context.html
05 02 2020 12:23:07.973:DEBUG [web-server]: serving: /data/jenkins/workspace/ui-scada-pipeline_PR-17-head/node_modules/karma/static/context.html
05 02 2020 12:23:08.196:DEBUG [web-server]: serving: /data/jenkins/workspace/ui-scada-pipeline_PR-17-head/node_modules/karma/static/context.js
HeadlessChrome 79.0.3945 (Linux 0.0.0) ERROR
  Uncaught SyntaxError: Unexpected token '.'
  at src/components/ld-breadcrumb/index.ts:1407:73
```

**FYI**: the mentioned file `index.ts` only consists of 125 lines (not 1407!)

### Environment Details

- Karma version (output of `karma --version`): 4.4.1
- NodeJS Version 11.10.1
- Running on `Debian 4.9.189-3+deb9u2 (2019-11-11) x86`
- Started by Jenkins 2.204.1 Pipeline

**Comment by johnjbarton** [comment]
From the readme: `A simple tool that allows you to execute JavaScript code in multiple real browsers.`  

From your issue:
```
Uncaught SyntaxError: Unexpected token '.'
  at src/components/ld-breadcrumb/index.ts:1407:73
```
Typically users have a TS build step feeding karma.  I bet Jenkins can support that. 

There are several karma plugins that transpile TS on the fly: https://www.google.com/search?q=karma+typescript+preprocessor&oq=karma+typescript+pre&aqs=chrome.1.69i57j0l4j69i64l3.6340j1j4&sourceid=chrome&ie=UTF-8

I would like to have better TS support, even an auto warning for this kind of configuration error.

**Comment by sebastianroming** [comment]
Okay, I should have mentioned that karma runs perfectly when executing locally from the console. Besides that, it worked without any error on the Jenkins machine until some days ago (we reverted the code to see what causes this error, but it occures now even in the commits that've worked previously).

Btw, we're using [@open-wc/testing-karma](https://github.com/open-wc/open-wc/tree/master/packages/testing-karma) and that's my `karma.conf.js`:

```javascript
/* eslint-disable import/no-extraneous-dependencies */
const {createDefaultConfig} = require('@open-wc/testing-karma');
const merge                 = require('webpack-merge');
const webpackConfig         = require('./webpack.config.js');

module.exports = config => {
  config.set(
      merge(createDefaultConfig(config), {
        files: [
          {pattern: 'images/**/*.png', watched: false, included: false, served: true},
          {pattern: 'images/**/*.svg', watched: false, included: false, served: true},
          {pattern: config.grep ? config.grep : 'test/**/*.test.ts', type: 'module'},
        ],
        proxies: {
          '/images/': 'dist/images/'
        },
        coverageIstanbulReporter: {
          thresholds: {
            global: {
              statements: 75,
              lines: 75,
              branches: 75,
              functions: 75,
            },
            emitWarning: true
          },
        },
        esm: {
          babel: true,
          nodeResolve: true,
          fileExtensions: ['.ts']
        },
        webpack: webpackConfig,
      }),
  );
  return config;
};

```

**Comment by johnjbarton** [comment]
Your test has a syntax error.   There isn't anything karma-runner can do to fix it.

I would look carefully at the Jenkins log for a missing file or other info in the log that may explain the local success.

Try running on Jenkins and local with `--logLevel=DEBUG`. Compare the outputs, esp. the Final config.

**Comment by sebastianroming** [comment]
The displayed error message doesn't appear in the test file, it's in the corresponding source file, but as mentioned, no file has >1400 LOC.

I already ran the tests with the debug log level, as you may see in the original posting.

Even if I restart runs that already passed, they fail... That's the problem I don't understand 🤷‍♂️

**Comment by sebastianroming** [comment]
Okay, fixed it. 
Had to use `@babel/plugin-proposal-optional-chaining` in my `.babelrc` file... 🤦‍♂ 

Thanks anyways!

**Comment by TreehouseNorris** [comment]
I was using an outdated version of ChromeHeadless due to Puppeteer v1, and updating to v16 (for node 16) removed the "Unexpected token '.'" error.
