### ISSUE TITLE
FireFoxHeadless doesn't run in headless mode

### ISSUE THREAD

**Issue by adjenks** [karma-runner/karma#3426]
### Expected behaviour
Run headless.
### Actual behaviour

Does not

### Environment Details
Karma version: 4.4.1
Ran with or without a config file, I get the same error.
### Steps to reproduce the behaviour

1. Install karma
2. Install karma-firefox-launcher
3. Attempt to run with `--browsers FirefoxHeadless`

I can remedy the problem by setting FIREFOX_BIN to '/path/firefox --headless'

But I don't think this is the right solution.

**Comment by adjenks** [comment]
Apparently I can fix it by simply adding a space to he end of the env var like `export FIREFOX_BIN="/path/firefox "`

**Comment by adjenks** [comment]
It actually says it's starting in headless mode, but fails when the environment variable has no trailing space.


> 18 02 2020 17:18:47.634:INFO [launcher]: Trying to start Firefox again (1/2).
> 18 02 2020 17:18:47.676:ERROR [launcher]: Cannot start Firefox
>         *** You are running in headless mode.
> 
> (firefox:17972): Gtk-WARNING **: 17:18:47.673: This process is currently running setuid or setgid.
> This is not a supported use of GTK+. You must create a helper
> program instead. For further details, see:
> 
>     http://www.gtk.org/setuid.html
> 
> Refusing to initialize GTK+.
> 
> 18 02 2020 17:18:47.676:ERROR [launcher]: Firefox stdout:
> 18 02 2020 17:18:47.676:ERROR [launcher]: Firefox stderr: *** You are running in headless mode.
> 
> (firefox:17972): Gtk-WARNING **: 17:18:47.673: This process is currently running setuid or setgid.
> This is not a supported use of GTK+. You must create a helper
> program instead. For further details, see:
> 
>     http://www.gtk.org/setuid.html
> 
> Refusing to initialize GTK+.
> 
> 18 02 2020 17:18:47.678:INFO [launcher]: Trying to start Firefox again (2/2).
>

**Comment by adjenks** [comment]
Adding a space:
```
$ export FIREFOX_BIN="/path/ff/firefox/firefox "
$ karma start
18 02 2020 17:23:28.661:INFO [karma-server]: Karma v4.4.1 server started at http://0.0.0.0:9876/
18 02 2020 17:23:28.666:INFO [launcher]: Launching browsers FirefoxHeadless with concurrency unlimited
18 02 2020 17:23:28.674:INFO [launcher]: Starting browser Firefox
```

**Comment by devoto13** [comment]
@adjenks Can you still reproduce this issue with the latest versions of `karma` and `karma-firefox-launcher`? I've tried on macOS and Debian and in both cases everything works correctly:

```
$ npm i karma karma-firefox-launcher karma-jasmine
$ cat karma.conf.js
module.exports = (config) => {
  config.set({
    frameworks: ["jasmine"],
    files: ["test.js"],
    browsers: ["FirefoxHeadless"],
    plugins: ["karma-jasmine", "karma-firefox-launcher"],
    singleRun: true,
  });
};
$ cat test.js
describe("test", () => {
  it("test", () => {
    expect(true).toBe(true);
  });
});
$ ./node_modules/.bin/karma start
23 05 2020 22:39:22.859:INFO [karma-server]: Karma v5.0.9 server started at http://0.0.0.0:9876/
23 05 2020 22:39:22.870:INFO [launcher]: Launching browsers FirefoxHeadless with concurrency unlimited
23 05 2020 22:39:22.893:INFO [launcher]: Starting browser FirefoxHeadless
23 05 2020 22:39:25.521:INFO [Firefox 68.0 (Linux x86_64)]: Connected on socket fKTA9ZIP_jPTBTIEAAAA with id 47683041
Firefox 68.0 (Linux x86_64): Executed 1 of 1 SUCCESS (0.061 secs / 0.002 secs)
TOTAL: 1 SUCCESS
```

**Comment by adjenks** [comment]
Not sure. I stopped using it.
