### ISSUE TITLE
kindof "forces" karma to install as "devDependency"

### ISSUE THREAD

**Issue by DoubleU23** [karma-runner/karma#3444]
### Expected behaviour
installs karma as defined in [@viewar/webpack's package.json](https://github.com/viewar/webpack/blob/master/package.json) 'dependencies'  

### Actual behaviour
installs `karma-cli` and all karma-related packages,  
but kindof "forces" `karma` to install as devDependency 
(located in `./node_modules/@viewar/webpack/node_modules/karma/bin/karma`

so we have to install `karma` manually or run  
`./node_modules/@viewar/webpack/node_modules/karma/bin/karma start ./node_modules/@viewar/webpack/karma`

### global installation
also tried to install `karma-cli` globally and added the path to `PATH` and `NODE_PATH` env vars
which didn't work either

### Environment Details
- running on Windows 10
- Karma version: latest (`^4.4.1`)
- Relevant part of your `karma.config.js` file: none

### Steps to reproduce the behaviour

1. `npm install @viewar/webpack`
2. run `npx karma start ./node_modules/@viewar/webpack/karma`
3. `Cannot find local Karma! Please install Karma by npm install karma --save-dev`.

related to viewar/webpack#130

**Comment by johnjbarton** [comment]
How is this a karma bug?
