### ISSUE TITLE
Bug: window scrolling

### ISSUE THREAD

**Issue by jasonkuhrt** [karma-runner/karma#345]
I would like to use testacular for testing a window-scroll-related utility.

There seems to a bug wherein I cannot get correct scrolling behaviour. Given this code:

``` js
chai.should()

describe("foo", function () {

  it("bar", function () {
    $('body').append('<div id="foo"></div>')
    $('#foo').css('height', 3000)
    dump(window.innerHeight)
    window.innerHeight.should.equal(300)
    window.scrollY.should.equal(0)
    window.scrollTo(window.scrollX, 50)
    window.scrollY.should.equal(50)
  });
});

```

I get the unexpected error:

``` bash
info (watcher): Changed file "/Users/jasonkuhrt/projects/components/scroll-over/test.js".
PhantomJS 1.7 DUMP: 300
PhantomJS 1.7 foo bar FAILED
    expected 0 to equal 50
        at /Users/jasonkuhrt/projects/components/scroll-over/node_modules/chai/chai.js:258
        at assertEqual (/Users/jasonkuhrt/projects/components/scroll-over/node_modules/chai/chai.js:662)
        at /Users/jasonkuhrt/projects/components/scroll-over/node_modules/chai/chai.js:2780
        at /Users/jasonkuhrt/projects/components/scroll-over/test.js:15
PhantomJS 1.7: Executed 1 of 1 (1 FAILED) (0.031 secs / NaN secs)
```

The specific assertion failing is:

``` js
    window.scrollY.should.equal(50)
```

I am able to make this test pass with mocha-phantomjs. What's going on in this testacular context?

**Comment by hydhaval** [comment]
Any solution on this?

**Comment by neilbaylor** [comment]
I've found a way to "scroll" the iframe, but the problem appears to be that the Component itself in not actually in the DOM

Is it possibly that the test DOM is in a DocumentFragment or something?

it('becomes "fixed" when scrolling past the break point', function (done) {

  	var node = React.findDOMNode(component);
  	
        document.body.style.height = '10000px';
  	window.scrollTo(0, 300);
	
        window.setTimeout(function () {
	  dump('offset + window.pageYOffset); //outputs 300
	  expect(window.getComputedStyle(node).position.toLowerCase()).toEqual('fixed'); //fails
	  document.body.style.height = '';
          dump(node.parentNode.parentNode) //undefined, ie not attached to the DOM
	  
          done();
	 }, 0);
  });

**Comment by neilbaylor** [comment]
Got it working :smile:

```
it('becomes "fixed" when scrolling past the break point', function (done) {
  	var node = React.findDOMNode(component);
  	document.body.style.height = '10000px';
  	document.body.appendChild(node.parentNode); //this is the key
  	window.scrollTo(0, component.SCROLL_BREAK_POINT + 1);
  	window.setTimeout(function () {
	  	expect(window.getComputedStyle(node).position.toLowerCase()).toEqual('fixed');
	  	document.body.style.height = '';
	  	done();
	}, 100)
  });
```

**Comment by hydhaval** [comment]
Wrapping aroung  window.setTimeout did the trick. thx

**Comment by neilbaylor** [comment]
The setTimeout is needed to allow the window.scrollTo to occur.

For me the ***hard*** part was having to append the nodes.parent to the DOM - otherwise it appears the test gets run without being attached to the iframe's DOM

**Comment by Cassidie** [comment]
I know this is a really old post, but I wanted to let others know that anything in the `setTimeout()` is ignored. :(
I still can't get scrolling to work in my tests. The event is fired, but the `window.pageYOffset` stays at 0. I've even tried using a host component and scrolling to other elements in the template with `scrollIntoView()`, but nothing seems to work. `window.pageYOffset`  just won't update unless you manually scroll in the karma window.

**Comment by neilbaylor** [comment]
Hey Cassidie

I dont really recall much context here, but if you look at my code, *before* the `window. scrollTo`, a the subsequent setTimeout, i do this: 

```
document.body.style.height = '10000px';
document.body.appendChild(node.parentNode); //this is the key
```

I seemed to think that was the "magic" at the time, hope it helps!

**Comment by Cassidie** [comment]
Thanks! I'm still not having luck with the setTimeout firing anything inside of it. I appreciate your response though. I've got another approach I'm going to try, and if it doesn't work I'm going to call it a day! haha

**Comment by DzmVasileusky** [comment]
Similar issue. It fails randomly with frequency about 2/3

`describe('Scroll', () => {

    const componentHTML = '<div id="fragment" style="margin-top: 500px; height: 5000px; width: 5000px;">!!!</div>';
    let dynamicParent: HTMLElement;
    let element: HTMLElement;

    beforeEach(() => {

        dynamicParent = document.createElement('div');
        dynamicParent.innerHTML = componentHTML;
        element = <HTMLElement>dynamicParent.firstChild;
        document.body.appendChild(element);

        window.scrollTo(0, 0);

    });

    afterEach(() => {

        element.parentNode.removeChild(element);

    });

    it('should scroll', (done) => {

        const topOffset = 200;

        setTimeout(() => {

            window.scrollTo(0, topOffset);
            setTimeout(() => {

                console.log(document.body.scrollHeight, document.body.clientHeight);
                // 6133, 600
                console.log(window.innerHeight);
                // 600
                console.log(window.pageYOffset, document.body.scrollTop);
                // 0, 0
                console.log(document.getElementById('fragment'));
                // <div id="fragment" style="margin-top: 500px; height: 5000px; width: 5000px;">!!!</div> 

                expect(window.pageYOffset).toEqual(topOffset);
                done();

            }, 200);

        });

    });

});`

Config

```
module.exports = (config) => {

    config.set({
        autoWatch: true,
        basePath: '',
        browserConsoleLogOptions: { terminal: true },
        browsers: ['ChromeHeadless'],
        client: {
            captureConsole: true,
            clearContext: false // leave Jasmine Spec Runner output visible in browser
        },
        colors: true,
        coverageIstanbulReporter: {
            dir: require('path').join(__dirname, '../build-webpack/coverage'),
            fixWebpackSourcePaths: true,
            reports: ['html', 'lcovonly']
        },
        customLaunchers: {
            ChromeHeadless: {
                base: 'Chrome',
                flags: [
                    '--disable-translate',
                    '--headless',
                    '--disable-gpu',
                    '--disable-extensions',
                    '--remote-debugging-port=9222'
                ]
            }
        },
        frameworks: ['jasmine', '@angular-devkit/build-angular'],
        logLevel: config.LOG_INFO,
        plugins: [
            require('karma-jasmine'),
            require('karma-chrome-launcher'),
            require('karma-jasmine-html-reporter'),
            require('karma-coverage-istanbul-reporter'),
            require('karma-teamcity-reporter'),
            require('karma-sourcemap-loader'),
            require('@angular-devkit/build-angular/plugins/karma')
        ],
        port: 9876,
        reporters: ['progress', 'kjhtml', 'teamcity'],
        singleRun: true
    });

};
```

"karma": "^3.1.4",
"karma-chrome-launcher": "^2.2.0",
"karma-cli": "^2.0.0",
"karma-coverage-istanbul-reporter": "~2.0.0",
"karma-jasmine": "^2.0.1",
"karma-jasmine-html-reporter": "^1.4.0",
"karma-sourcemap-loader": "^0.3.7",
"karma-teamcity-reporter": "^1.1.0",
