### ISSUE TITLE
After Upgrading Angular 9 Getting Karma Error in node_modules , karma - Config.tpl.ts , ERROR in node_modules/karma/config.tpl.ts:13:18 - error TS1109: 

### ISSUE THREAD

**Issue by Abhilashtiwari0301** [karma-runner/karma#3450]
Hi Everyone,
I am getting below Karma Config file error after upgrading Angular 9 , 

ERROR in node_modules/karma/config.tpl.ts:13:18 - error TS1109: Expression expected.
frameworks: [%FRAMEWORKS%],
node_modules/karma/config.tpl.ts:13:30 - error TS1109: Expression expected.
frameworks: [%FRAMEWORKS%],
node_modules/karma/config.tpl.ts:17:13 - error TS1109: Expression expected.
files: [%FILES%
node_modules/karma/config.tpl.ts:18:5 - error TS1109: Expression expected.
node_modules/karma/config.tpl.ts:22:15 - error TS1109: Expression expected.

Package.json

"devDependencies": {
"@angular-devkit/build-angular": "~0.900.7",
"@angular/cli": "~9.0.7",
"@angular/compiler-cli": "~9.0.7",
"@angular/language-service": "~9.0.7",
"@types/jasmine": "^3.0.0",
"@types/jasminewd2": "^2.0.0",
"@types/node": "~8.9.4",
"codelyzer": "^5.1.2",
"jasmine-core": "^3.0.0",
"jasmine-spec-reporter": "~4.2.1",
"karma": "^4.0.0",
"karma-chrome-launcher": "^3.0.0",
"karma-cli": "^2.0.0",
"karma-coverage-istanbul-reporter": "~2.0.1",
"karma-html-reporter": "^0.2.7",
"karma-jasmine": "~1.1.2",
"karma-jasmine-html-reporter": "^0.2.2",
"karma-junit-reporter": "^1.2.0",
"node-sass": "^4.13.1",
"protractor": "^5.4.3",
"ts-node": "~7.0.0",
"tslint": "~6.1.0",
"typescript": "^3.6.4"
}

**Comment by johnjbarton** [comment]
Looks like you compiled a template for a config rather than expanding it and compiling it.
