### ISSUE TITLE
Launcher cannot start Chrome

### ISSUE THREAD

**Issue by abtraju** [karma-runner/karma#3473]
### Expected behaviour
Launcher should open the chrome

### Actual behaviour
Launcher exited without throw the valid error

> 15 04 2020 17:00:36.244:DEBUG [launcher]: Process Chrome exited with code 1 and signal null
> 15 04 2020 17:00:36.245:ERROR [launcher]: Cannot start Chrome
> 	
> 15 04 2020 17:00:36.245:ERROR [launcher]: Chrome stdout: 
> 15 04 2020 17:00:36.245:ERROR [launcher]: Chrome stderr: 

### Environment Details
- Karma version (output of `karma --version`): 4.2.0
-OS: Ubuntu 16.04.4 LTS
- Relevant part of your `karma.config.js` file

> {
> 
>         // base path that will be used to resolve all patterns (eg. files, exclude)
>         basePath: '', // No I18N
>         // frameworks to use
>         // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
>         frameworks: [ 'mocha', 'chai', 'sinon', 'inline-mocha-fix' ], // No I18N
>         pact: {
>             cors: true
>         },
>         files: [],
>         // browsers: ["Chrome"],
>         // list of files / patterns to exclude
>         exclude: [],
>         // Proxy to be included.
> 
>         proxies: {
>             '/assets/': '/base/assets/'
>         },
> 
>         // preprocess matching files before serving them to the browser
>         // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
>         preprocessors: {
>             'templates/**/*.html': [ 'html2js' ] // No I18N
>         },
> 
>         // test results reporter to use
>         // possible values: 'dots', 'progress'
>         // available reporters: https://npmjs.org/browse/keyword/karma-reporter
>         reporters: [ 'progress', 'html' ], // No I18N
> 
>         // web server port
>         port: testConfig.port || 9876,
> 
>         // enable / disable colors in the output (reporters and logs)
>         colors: true,
>         proxyValidateSSL: false,
> 
>         // level of logging
>         // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
>         logLevel: config.LOG_INFO,
>         logLevel: config.LOG_DEBUG,
> 
>         captureTimeout: 60000,
>         browserNoActivityTimeout: 100000,
>         browserDisconnectTimeout: 7000,
>         browserDisconnectTolerance: 3,
>         processKillTimeout: 5000,
> 
>         // enable / disable watching file and executing tests whenever any file changes
>         autoWatch: false,
> 
>         // start these browsers
>         // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
>         // Added because CORS error is being thrown when an API request is made
>         customLaunchers: {
>             ChromeWithoutSecurity: {
>                 base: 'Chrome',
>                 flags: [ '--disable-web-security' ]
>             },
>             IE9: {
>                 base: 'IE',
>                 'x-ua-compatible': 'IE=EmulateIE9'
>             },
>             IE10: {
>                 base: 'IE',
>                 'x-ua-compatible': 'IE=EmulateIE10'
>             },
>             FirefoxHeadless: {
>                 base: 'Firefox',
>                 flags: [ '-headless' ]
>             },
>             OperaHeadless: {
>                 base: 'Opera',
>                 flags: [ '-headless' ]
>             }
>         },
>         // browserConsoleLogOptions: {
>         //   terminal: false
>         // },
>         // Continuous Integration mode
>         // if true, Karma captures browsers, runs the tests and exits
>         singleRun: testConfig.singleRun,
>         crossOriginAttribute: false,
> 
>         // Concurrency level
>         // how many browser should be started simultaneous
>         concurrency: 10,
>         client: {
>             // runInParent: false,
>             // useIframe: false
>         },
>         plugins: [ 'karma-*', {
>             'framework:inline-mocha-fix': [ 'factory', unit8ArrayPolyfill ]
>         } ],
>         htmlReporter: {
>             outputDir: 'tempReports', // where to put the reports
>             templatePath: null, // set if you moved jasmine_template.html
>             focusOnFailures: false, // reports show failures on start
>             namedFiles: true, // name files instead of creating sub-directories
>             pageTitle: null, // page title for reports; browser info by default
>             urlFriendlyName: true, // simply replaces spaces with _ for files/dirs
>             reportName: undefined, // report summary filename; browser info by default
>             // experimental
>             preserveDescribeNesting: false, // folded suites stay folded
>             foldAll: false // reports start folded (only with preserveDescribeNesting)
>         }
>     }

### Steps to reproduce 
1. Host the setup in remote server.
2. And run the command from your machine.

**Comment by johnjbarton** [comment]
All browsers are launched by plugins, so look into your plugins for this issue.
