### ISSUE TITLE
Karma Proxies have never worked

### ISSUE THREAD

**Issue by Javaman2** [karma-runner/karma#3477]
Please read http://karma-runner.github.io/4.0/intro/troubleshooting.html first

There's over [7,000 questions on StackOverflow concerning Karma Proxies](https://www.google.com/search?q=karma+proxy+are+not+working+site%3Astackoverflow.com)

Over the past three years I keep trying to get it to work but it never does.

Is there a working example somewhere that shows how this works, what it does, what it doesn't do etc.  As far as I can tell; there's no way to redirect anything that goes to the default Karma port.  The idea being that I don't want 404 errors; I want test data from the real site.  

The real question is shouldn't this work?

```html

// trying to redirect ports.

      proxies: {
         "http://localhost:9876/Configuration/SettingGroups": {
            target: "http://localhost:8180/Configuration/SettingGroups",
            changeOrigin: true,
         },
      },

//or this...

      proxies: {
         "/Configuration/SettingGroups": {
            target: "http://localhost:8180/Configuration/SettingGroups",
            changeOrigin: true,
         },
      },

//or this...

      proxies: {
         "/Configuration/SettingGroups": "http://localhost:8180/Configuration/SettingGroups"
      },


```

**Comment by devoto13** [comment]
The official documentation of [`proxies`](https://karma-runner.github.io/4.0/config/configuration-file.html) provides usage examples. Depending on your setup one of the last two samples should work. There is a test verifying this behaviour and it passes.

Please follow the advice from http://karma-runner.github.io/4.0/intro/troubleshooting.html and run Karma with `--log-level debug`. Look for records like `DEBUG [proxy]: proxying request - /Configuration/SettingGroups to localhost:8180`. This means that the proxy is sending request to your server. Check logs on your server to verify that these requests are reaching the server and are processed successfully.

**Comment by Javaman2** [comment]
Thanks... I did get it to work, here's the rules:
1) In first part do not include this part "http://localhost:9878", it already "knows" the port
2) Starting with first slash, put in complete path on first part. e.g. /Configuration/SettingsGroups
3) In the 2nd part include only the URL portion (with new port)
 
      proxies: {
         "/Configuration/SettingGroups": "http://localhost:8180",
         "/Identity/Info": "http://localhost:8180",
      },

Partial paths do not work in 1st part

      proxies: {
         "/Configuration": "http://localhost:8180",
         "/Identity": "http://localhost:8180",
      },

Wild Cards do not work either:
      proxies: {
         "/Configuration/*": "http://localhost:8180",
         "/Identity/*": "http://localhost:8180",
      },

If you make any changes to karma.config you must save and bring up new instance of 'ng test', if using Angular.

**Comment by Javaman2** [comment]
I wrote an article documenting my findings and how to configure the proxy. There's probably more to it, but this got me going.  Thanks!

https://dev.to/jwp/angular-karma-proxy-configuration-1kbb

**Comment by Javaman2** [comment]
Thanks again...

**Comment by devoto13** [comment]
Good writeup @Javaman2! Couple of corrections:

> The right side which is the "redirection". It includes the Schema, port but not the path. This is because the proxy redirects to the same path.

You can actually specify the path on the right side as well. It allows to proxy request to a different path than original. But it will use the path from the right side by default if you omit it.

> You still need to configure CORS support on the back-end because the outbound requests look like this:

A `changeOrigin` option is an alternative solution. As pointed out in the [documentation](http://karma-runner.github.io/4.0/config/configuration-file.html): `changeOrigin` Whether or not the proxy should override the Host header using the host from the target (default false).

> Karma Proxy Configuration Internals

This has nothing to do with Karma specifically. Any TCP connection consists of two sockets (host + port pairs). I would recommend to read up on how TCP works.
