### ISSUE TITLE
Feature Request/Proposal: Flag for specifying plugin directories/plug n' play support

### ISSUE THREAD

**Issue by njradford** [karma-runner/karma#3498]
I believe Plugn'Play in Yarn breaks this due to the relative path lookup from node_modules to obtain plugins. If I'm thinking about it correctly, this could be fixed with an option to specify explicitly how to obtain the plugin modules. Or a flag to turn off the relative import. If this sounds right/sense-making/useful I'd be happy to implement a PR.

**Comment by devoto13** [comment]
I'm not sure that Karma can support plugin auto-loading with plug'n'play package manager. So you'll probably have to explicitly require and add all plugins to the config file, e.g.

```
plugins: [
  require('karma-chorme-launcher'),
  require('karma-jasmine')
]
```

Or is there a generic API, which allows to iterate through all available dependencies?

**Comment by njradford** [comment]
I had no idea you could wire them up directly in that way. Thanks @devoto13.
