### ISSUE TITLE
Karma test runner does not display mocha test results and may not be running them

### ISSUE THREAD

**Issue by 76784** [karma-runner/karma#3508]
When running tests using mocha (`./node_modules/.bin/mocha test`) the tests in the test file run, and the following is outputted to powershell:
```
TEST ************

  myFunc
    - a pending test


  0 passing (4ms)
  1 pending
```
When running the same file using karma (`./node_modules/.bin/karma start`), the `console.log("TEST ************");` prints out, but the test suite does not run. Karma gives the following output:
```
10 05 2020 14:27:24.326:WARN [karma]: No captured browser, open http://localhost:9876/
10 05 2020 14:27:24.352:INFO [karma-server]: Karma v5.0.5 server started at http://0.0.0.0:9876/
10 05 2020 14:27:24.352:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
10 05 2020 14:27:24.358:INFO [launcher]: Starting browser ChromeHeadless
10 05 2020 14:27:26.898:INFO [Chrome Headless 81.0.4044.138 (Windows 10)]: Connected on socket IBnhFoW1f9d9zLHsAAAA with id 8234878
Chrome Headless 81.0.4044.138 (Windows 10) LOG: 'TEST ************'

Chrome Headless 81.0.4044.138 (Windows 10): Executed 0 of 1 (skipped 1) SUCCESS (0.004 secs / 0 secs)
TOTAL: 0 SUCCESS
```
**test.js**
```
console.log("TEST ************");

describe('myFunc', function() {
  it("a pending test");
});
```
**karma.conf.js**
```
module.exports = function(config) {
  config.set({
    frameworks: ["mocha"],
    files: [ "test/test.js"],
    plugins: [
      "karma-chrome-launcher",
      "karma-mocha"    
    ],
    browsers: ["ChromeHeadless"]
  })
}
```
**package.json**
```
{
  "name": "karma-mocha-test",
  "devDependencies": {
    "karma-chrome-launcher": "^3.1.0",
    "karma": "^5.0.5",
    "karma-mocha": "^2.0.1",
    "mocha": "^7.1.2"
  }
}
```
I believe the mocha test results should be displayed in powershell in the above scenario, and that therefore this is a bug.

**Comment by devoto13** [comment]
I don't think this issue is relevant for the core Karma project. Karma itself only supports couple of very basic reporters and relies on [plugins](https://www.npmjs.com/search?q=keywords:karma-reporter) to add more advanced reporters. Apparently `karma-mocha` package does not provide a Mocha-style reporter, but only integration with Mocha framework. There is a [`karma-mocha-reporter`](https://www.npmjs.com/package/karma-mocha-reporter) package, which seems to provide exactly what you're asking for.

**Comment by devoto13** [comment]
And as for your other concern. It is only that default `progress` reporter does not output anything for the skipped tests. If you actually add some logic to the body of your tests case you'll see that it is executed.
