### ISSUE TITLE
Karma tests running twice

### ISSUE THREAD

**Issue by erwindemoel** [karma-runner/karma#3516]
### Expected behaviour
All Karma tests should run once and afterwards show the progress report.

### Actual behaviour
All tests are run twice, and the progress report shows all errors twice as well.

### Environment Details
Karma version 4.1.0

Karma config file:
`// Karma configuration file, see link for more information
// https://karma-runner.github.io/1.0/config/configuration-file.html

module.exports = function (config)
{
    config.set({
        basePath                : '',
        frameworks              : ['jasmine', '@angular-devkit/build-angular'],
        plugins                 : [
            require('karma-jasmine'),
            require('karma-chrome-launcher'),
            require('karma-jasmine-html-reporter'),
            require('karma-coverage-istanbul-reporter'),
            require('@angular-devkit/build-angular/plugins/karma'),
            require('karma-junit-reporter'),
            require('karma-spec-reporter')
        ],
        client                  : {
            clearContext: false // leave Jasmine Spec Runner output visible in browser
        },
        coverageIstanbulReporter: {
            dir                  : require('path').join(__dirname, '../coverage'),
            reports              : ['html', 'cobertura', 'lcovonly'],
            fixWebpackSourcePaths: true
        },
        jasmine: {
            random: false
        },
        junitReporter: {
            outputdir: '',
            outputFile: 'test-angular.xml'
        },
        reporters               : ['spec', 'kjhtml', 'junit'],
        port                    : 9876,
        colors                  : true,
        logLevel                : config.LOG_INFO,
        autoWatch               : true,
        autoWatchBatchDelay     : 10000,
        browsers                : ['ChromeHeadless'],
        singleRun               : false,
        files: [
            { pattern: '../node_modules/@angular/material/prebuilt-themes/indigo-pink.css', included: true, watched: false }
        ],
        specReporter: {
            maxLogLines: 5,         // limit number of lines logged per test
            suppressErrorSummary: false,  // do not print error summary
            suppressFailed: false,  // do not print information about failed tests
            suppressPassed: false,  // do not print information about passed tests
            suppressSkipped: true,  // do not print information about skipped tests
            showSpecTiming: true // print the time elapsed for each spec
        }
    });
};`

### Steps to reproduce the behaviour

1. Run ng test, it starts running all tests and then starts over and does it again.

**Comment by devoto13** [comment]
I am able to reproduce it. Seems to be duplicate/related to https://github.com/karma-runner/karma/issues/2342.

```
$ ng new karma-test
? Would you like to add Angular routing? No
? Which stylesheet format would you like to use? CSS
CREATE karma-test/README.md (1026 bytes)
CREATE karma-test/.editorconfig (274 bytes)
CREATE karma-test/.gitignore (631 bytes)
CREATE karma-test/angular.json (3598 bytes)
CREATE karma-test/package.json (1286 bytes)
CREATE karma-test/tsconfig.json (489 bytes)
CREATE karma-test/tslint.json (3125 bytes)
CREATE karma-test/browserslist (429 bytes)
CREATE karma-test/karma.conf.js (1022 bytes)
CREATE karma-test/tsconfig.app.json (210 bytes)
CREATE karma-test/tsconfig.spec.json (270 bytes)
CREATE karma-test/src/favicon.ico (948 bytes)
CREATE karma-test/src/index.html (295 bytes)
CREATE karma-test/src/main.ts (372 bytes)
CREATE karma-test/src/polyfills.ts (2835 bytes)
CREATE karma-test/src/styles.css (80 bytes)
CREATE karma-test/src/test.ts (753 bytes)
CREATE karma-test/src/assets/.gitkeep (0 bytes)
CREATE karma-test/src/environments/environment.prod.ts (51 bytes)
CREATE karma-test/src/environments/environment.ts (662 bytes)
CREATE karma-test/src/app/app.module.ts (314 bytes)
CREATE karma-test/src/app/app.component.css (0 bytes)
CREATE karma-test/src/app/app.component.html (25723 bytes)
CREATE karma-test/src/app/app.component.spec.ts (954 bytes)
CREATE karma-test/src/app/app.component.ts (214 bytes)
CREATE karma-test/e2e/protractor.conf.js (808 bytes)
CREATE karma-test/e2e/tsconfig.json (214 bytes)
CREATE karma-test/e2e/src/app.e2e-spec.ts (643 bytes)
CREATE karma-test/e2e/src/app.po.ts (301 bytes)
✔ Packages installed successfully.
$ sed -i.bak 's/toBeTruthy/toBeFalsy/' src/app/app.component.spec.ts
$ ng test
$ 18 05 2020 12:54:38.321:WARN [karma]: No captured browser, open http://localhost:9876/
18 05 2020 12:54:38.327:INFO [karma-server]: Karma v4.4.1 server started at http://0.0.0.0:9876/
18 05 2020 12:54:38.328:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
18 05 2020 12:54:38.337:INFO [launcher]: Starting browser Chrome
18 05 2020 12:54:43.523:WARN [karma]: No captured browser, open http://localhost:9876/
18 05 2020 12:54:43.708:INFO [Chrome 81.0.4044 (Mac OS X 10.15.4)]: Connected on socket 2SQjnPZzyawCzYdUAAAA with id 5384671
Chrome 81.0.4044 (Mac OS X 10.15.4) AppComponent should create the app FAILED
	Error: Expected AppComponent({ title: 'karma-test', __ngContext__: [ null, TView({ type: 0, id: -1, blueprint: [ null, <circular reference: Object>, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, 0, 0, 0, 0, 0, 0, 0, null, NodeInjectorFactory({ factory: Function, resolving: false, canSeeViewProviders: true, injectImpl: null }) ], template: null, queries: null, viewQuery: null, node: TNode$1({ tView_: <circular reference: Object>, type: 2, index: -1, injectorIndex: -1, directiveStart: -1, directiveEnd: -1, directiveStylingLast: -1, propertyBindings: null, flags: 0, providerIndexes: 0, tagName: null, attrs: null, mergedAttrs: null, localNames: null, initialInputs: undefined, inputs: null, outputs: null, tViews: null, next: null, projectionNext: null, child: TNode$1({ tView_: <circular reference: Object>, type: 3, index: 20, injectorIndex: 21, directiveStart: 30, directiveEnd: 31, directiveStylingLast: -1, propertyBindings: null, flags ... to be falsy.
	    at <Jasmine>
	    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/src/app/app.component.spec.ts:16:17)
	    at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:364:1)
	    at ProxyZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:292:1)
Chrome 81.0.4044 (Mac OS X 10.15.4): Executed 2 of 3 (1 FAILED) (0 secs / 0.227 secs)
Chrome 81.0.4044 (Mac OS X 10.15.4) AppComponent should create the app FAILED
	Error: Expected AppComponent({ title: 'karma-test', __ngContext__: [ null, TView({ type: 0, id: -1, blueprint: [ null, <circular reference: Object>, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, 0, 0, 0, 0, 0, 0, 0, null, NodeInjectorFactory({ factory: Function, resolving: false, canSeeViewProviders: true, injectImpl: null }) ], template: null, queries: null, viewQuery: null, node: TNode$1({ tView_: <circular reference: Object>, type: 2, index: -1, injectorIndex: -1, directiveStart: -1, directiveEnd: -1, directiveStylingLast: -1, propertyBindings: null, flags: 0, providerIndexes: 0, tagName: null, attrs: null, mergedAttrs: null, localNames: null, initialInputs: undefined, inputs: null, outputs: null, tViews: null, next: null, projectionNext: null, child: TNode$1({ tView_: <circular reference: Object>, type: 3, index: 20, injectorIndex: 21, directiveStart: 30, directiveEnd: 31, directiveStylingLast: -1, propertyBindings: null, flags ... to be falsy.
	    at <Jasmine>
	    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/src/app/app.component.spec.ts:16:17)
	    at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:364:1)
Chrome 81.0.4044 (Mac OS X 10.15.4): Executed 3 of 3 (1 FAILED) (0.32 secs / 0.239 secs)
TOTAL: 1 FAILED, 2 SUCCESS
TOTAL: 1 FAILED, 2 SUCCESS
```

**Comment by erwindemoel** [comment]
@devoto13 I see the label has been added "needs: work". Any clue when is this going to be fixed?

**Comment by devoto13** [comment]
No, not really. Label just means that it is reproducible and somebody needs to investigate the root cause and work on a fix.

**Comment by erwindemoel** [comment]
@devoto13 Ah, thanks for the clarification. Any clue when it's going to start being investigated?

**Comment by devoto13** [comment]
This is an open source project, so as soon as somebody decides to fix it for everybody ;)

I'm pretty sure that tests don't run twice, the results are reported twice. My educated guess is that there are multiple reporters, which extend the base implementation. By default they would print results and as there are multiple such reporters they would print results multiple times. You can try to debug Karma with Node debugger and check if it is the case if you need this fixed.

If the above theory is correct, the workaround would be to remove the problematic reporter and fix would be to ensure that reporter does not print what it should not print.

**Comment by erwindemoel** [comment]
No, they are actually running twice, not just printing twice.

All the unit tests are run, when it's finished it reports the results. Then after a few seconds it repeats the entire process and starts running all the unit tests again from the beginning. The whole test run process is repeated which takes a very long time. That's why it's so annoying for us.

Perhaps we are having a different issue then what you're describing?

**Comment by devoto13** [comment]
Yes, indeed! Sorry for the confusion.

**Comment by erwindemoel** [comment]
We fixed this by upgrading to the latest version of Karma
