### ISSUE TITLE
[web-server]: 404: /context.js

### ISSUE THREAD

**Issue by nicolasalcina** [karma-runner/karma#3520]
Hello,
I just migrate from angular 8 to angular 9,
I was in Karma 4.0.2/Jasmine 3.4.0, all worked fine
now I am in Karma 5.0.5/Jasmine 3.5.0
but I got a 404 on context.js, and no test are running.
the path is http://localhost:9876/context.js, I think that it must be http://localhost:9876/test/context.js, but I don't find HTML, try to modify node_modules\karma\static\context.html, but nothing change.

my package.json :
`"dependencies": {
    "@angular-devkit/build-angular": "~0.901.6",
    "@angular/animations": "^9.1.7",
    "@angular/cdk": "^9.2.3",
    "@angular/cli": "^9.1.6",
    "@angular/common": "^9.1.7",
    "@angular/compiler": "^9.1.7",
    "@angular/core": "^9.1.7",
    "@angular/flex-layout": "^9.0.0-beta.30",
    "@angular/forms": "^9.1.7",
    "@angular/material": "^9.2.3",
    "@angular/material-moment-adapter": "^9.2.3",
    "@angular/platform-browser": "^9.1.7",
    "@angular/platform-browser-dynamic": "^9.1.7",
    "@angular/router": "^9.1.7",
    "@types/form-data": "^2.5.0",
    "ajv": "^6.10.2",
    "ajv-keywords": "^3.4.1",
    "angular2-signaturepad": "^2.11.0",
    "cordova-android": "^8.0.0",
    "cordova-plugin-device": "^2.0.3",
    "cordova-sqlite-storage": "^3.2.1",
    "cordova-webpack": "^1.0.2",
    "core-js": "^3.1.4",
    "form-data": "^2.5.1",
    "karma-jspm": "^2.2.3",
    "md5-typescript": "^1.0.5",
    "moment": "^2.24.0",
    "ng-click-outside": "^5.1.1",
    "ngx-color-picker": "^9.1.0",
    "ngx-ui-loader": "^8.0.0",
    "rxjs": "^6.5.5",
    "rxjs-compat": "^6.5.3",
    "tslib": "^1.10.0",
    "typescript": "^3.8.3",
    "web-animations-js": "^2.3.2",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^9.1.7",
    "@angular/language-service": "^9.1.7",
    "@types/jasmine": "^3.5.10",
    "@types/jasminewd2": "~2.0.6",
    "@types/node": "^14.0.1",
    "angular-ide": "^0.9.74",
    "codelyzer": "^5.2.2",
    "cordova-plugin-whitelist": "^1.3.4",
    "jasmine-core": "^3.5.0",
    "jasmine-spec-reporter": "^5.0.2",
    "karma": "^5.0.8",
    "karma-chrome-launcher": "^3.1.0",
    "karma-cli": "^2.0.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "^3.1.1",
    "karma-jasmine-html-reporter": "^1.5.4",
    "node-sass": "^4.14.1",
    "protractor": "^7.0.0",
    "rxjs-tslint": "^0.1.8",
    "ts-node": "~8.3.0",
    "tslint": "^6.1.2",
    "webpack": "^4.43.0",
    "webpack-cordova-plugin": "^0.1.6"
  },`

where is my mistake.
thanks

**Comment by devoto13** [comment]
As this works in the fresh Angular CLI project the issue is most likely on your side and you need to debug it yourself. Compare your `karma.conf.js` with the one generated by the fresh Angular CLI project, remove `node_moduels` and `dist`, run `npm i` and try again.

Please don't use the issue tracker for support requests.

If you manage to produce a minimal reproduction showing that this issue is coming from the `karma` package, then open a new issue including the minimal reproduction of the problem.

**Comment by devoto13** [comment]
Not sure if it is the same issue, but https://github.com/karma-runner/karma/issues/3357#issuecomment-634630974 looks similar.

**Comment by nicolasalcina** [comment]
Thanks it was the urlRoot
must be empty
