### ISSUE TITLE
Karma: configuration of the context iframe

### ISSUE THREAD

**Issue by dvoytenko** [karma-runner/karma#3525]
Context iframe works very well in general. But in some types of applications tests are a bit more sensitive of the on-the-screen content and it'd be great to have an option to customize this iframe's size/position. Currently it is styled to be `width:100%; height: 100%`. With the Karma runner header, the bottom of the iframe is always cut off from the bottom of the screen. For some tests it'd be convenient to configure the iframe to take the whole screen, e.g. by setting its styles to `position:fixed; top: 0; width: 100%; height: 100%`.

**Comment by devoto13** [comment]
You can provide you own version using [`customContextFile`](http://karma-runner.github.io/5.0/config/configuration-file.html) configuration option. 

Not sure whether it is sustainable to start adding extra options to customise various aspects of the context file. Can you elaborate about what kind of test is affected by the current setup? Maybe we can improve the built-in one instead.

**Comment by dvoytenko** [comment]
@devoto13 thanks for the suggestion! It looks like actually the `customClientContextFile` option is what we need. I'm closing this issue.
