### ISSUE TITLE
Lodash is vulnerable to prototype pollution

### ISSUE THREAD

**Issue by Christian24** [karma-runner/karma#3536]
Hi,

npm just released a new advisory regarding lodash:  https://npmjs.com/advisories/1523

There is an open issue here: https://github.com/lodash/lodash/issues/4836

At the moment there is no fixed version available, however there seem to be a few PR.

**Comment by devoto13** [comment]
This has been fixed by https://github.com/karma-runner/karma/commit/5db46b799b84a3d29157edfdbb8d0d0bc57f8fbc.

**Comment by jimmywarting** [comment]
Maybe make some effort to try and replace some of lodash methods to vanilla js?

Like here for example:
https://github.com/karma-runner/karma/blob/94cf15e8fa4420c8716998873b77f0c4f59b9e94/lib/middleware/runner.js#L53

Change `_.isArray` to `Array.isArray`

**Comment by devoto13** [comment]
@jimmywarting While some of the lodash methods are trivial to replace, others are more tricky. But I agree that we should reduce our usage of lodash to the bare minimum and ideally remove the dependency. A PR(s) to replace lodash methods with built-in alternatives where it's trivial to do so is welcome.

Right now we seem to be using these methods:

```
_.mergeWith
_.debounce
_.isEmpty
_.uniq
_.values
_.isUndefined
_.isFunction
_.isString
_.isObject
_.isArray
_.isNumber
_.merge
_.identity
_.cloneDeep
_.sortBy
_.map
_.isPlainObject
_.union
_.isError
```

**Comment by jimmywarting** [comment]
_.mergeWith
_.debounce
_.isEmpty > `item.length`
_.uniq > `new Set(items)`
_.values > `Object.values(obj)`
_.isUndefined > `??` `x == null` (checks for both null and undefined)
_.isFunction > `typeof x === 'function'`
_.isString > `typeof x === 'string'`
_.isObject > `typeof x === 'object'`
_.isArray > `Array.isArray(obj)`
_.isNumber > `typeof x === 'number'`
_.merge > `Object.assign(target, source)`
_.identity > `x => x`
_.cloneDeep
_.sortBy > `arr.sort(fn)`
_.map > `arr.map(fn)`
_.isPlainObject > `typeof x === 'object'`
_.union > `new Set(...arr)`
_.isError > err instanceof Error

**Comment by devoto13** [comment]
@jimmywarting Yeah, something like that, but also think about semantics and corner cases.

E.g. `new Set(items)` changes original order, which is probably undesirable in our usage. `_.union ` may have the same assumption. _.isEmpty` also checks for `null` and primitives, which needs to be assessed on a case by case basis. `_.merge` performs a deep merge, so `Object.assign()` is not enough. `arr.sort(fn)` is a bit controversial change as it adds more noise to the code.

**Comment by jimmywarting** [comment]
> _.merge performs a deep merge

Thought that was what `_.cloneDeep` was doing 
haven't had much hands on lodash lately...

haven't looked into the codebase in Karma either, just saw a security risk in my toolchain
