### ISSUE TITLE
Breaking changes in dependency source-map

### ISSUE THREAD

**Issue by puppe** [karma-runner/karma#3557]
As of commit 5db46b799b84a3d29157edfdbb8d0d0bc57f8fbc, Karma uses version ^0.7.3 of source-map. [Version 0.7.0](https://github.com/mozilla/source-map/blob/master/CHANGELOG.md#070) had introduced several breaking changes. At least one of those breaks error reporting in Karma when source maps are used:

> **Breaking change:** `new SourceMapConsumer` now returns a `Promise` object
  that resolves to the newly constructed `SourceMapConsumer` instance, rather
  than returning the new instance immediately.

This invariably results in the following error message whenever a test fails:

```
SourceMap position not found for trace: …
```

**Comment by puppe** [comment]
PS: The exception is thrown [here](https://github.com/karma-runner/karma/blob/4fdef7059a0930907f4bbd74c54e2a019ac20687/lib/reporter.js#L65), when `originalPositionFor` is called because `getSourceMapConsumer` now returns a Promise of a SourceMapConsumer instead of a SourceMapConsumer.

**Comment by devoto13** [comment]
Thanks for a report. Would you be willing to send a PR to rollback to a previous version of `source-map` as a temporary workaround?

**Comment by puppe** [comment]
No problem. See #3558.

**Comment by johnjbarton** [comment]
Fixed by PR #3559
