### ISSUE TITLE
How to access the browser DOM from reporter?

### ISSUE THREAD

**Issue by Sayan751** [karma-runner/karma#3561]
Sorry to ask a question here. But I could not find any detailed documentation on writing a custom reporter.

I am moving from Jasmine to Mocha. And using Karma as a test runner. Previously with jasmine + [karma-jasmine-html-reporter](https://github.com/dfederm/karma-jasmine-html-reporter) I have this nice HTML report on the browser. However, for mocha I could not find any reporter that provides this behavior.

Thus, I thought of having something similar for my mocha setup as well. To this end, I am trying to write my own custom reporter for karma. The goal is that as a spec completes, the reporter will trigger a change to the DOM, loaded in browser, to reflect the spec completion result. So far I have the folllowing.

```js
function MochaHtmlReporter(decorator, config, logger, helper, formatError) {
    decorator(this);
    this.onSpecComplete = (browser, result) => {
        const message = `onSpecCompleted: ${JSON.stringify(result)}`;
        console.log(message);
         // this.write(message); // this writes to console, not useful for my purpose.
    };
    this.renderBrowser = (browser, result) => {
        console.log(`renderBrowser: ${JSON.stringify(result)}`);
    }
}

MochaHtmlReporter.$inject = ['baseReporterDecorator', 'config', 'logger', 'helper', 'formatError'];

module.exports = {
    'reporter:kmhtml': ['type', MochaHtmlReporter]
};
```

However, I am not sure, how to trigger the DOM change from the reporter. During debug I saw that the `browser` has a socket object. One idea might be to inject a script that is "serve"d, and it listens to the socket. Thereby the reporter can emit an event to the script. Not sure however, if this is a sensible idea.  I can use some help regarding this.

The other idea was to somehow use the `renderBrowser` method. But that never got called during the run.

Is there any general recipe for this?

**Comment by devoto13** [comment]
You can not access DOM from the reporter as this code runs in the Karma server process. What karma-jasmine-html-reporter does is that it [adds a file to the test page](https://github.com/dfederm/karma-jasmine-html-reporter/blob/master/src/index.js#L31), which registers a Jasmine plugin in the browser, which in turn updates the HTML in the browser. I think you should be able to do similar in your plugin. 

PS You don't really need to have a Karma reporter for this (unless you want to publish it as a library on NPM), you can as well just add the plugin file in the `files` property in your Karma configuration.

Hope this helps. Good luck!

**Comment by Sayan751** [comment]
@devoto13 Thanks for the reply. That is exactly what I mean by serving an injected script. However, I think I still need something like a reporter, to actually get notified of the test completions. The close to a plugin in mocha might be a [custom reporter](https://mochajs.org/api/tutorial-custom-reporter.html), although I am not sure if that is "serve"d . Will give it a try.

On a different note, as far as I have understood, the karma server talks to the client/browser over a websocket connection. In that case, why it is difficult to tap into that socket and send data from the reporter to the injected script? Asking out of curiosity.

**Comment by devoto13** [comment]
If you use `karma-mocha`, I think you should be able to add customer reporter to the `window.Mocha` or something.

> On a different note, as far as I have understood, the karma server talks to the client/browser over a websocket connection. In that case, why it is difficult to tap into that socket and send data from the reporter to the injected script? Asking out of curiosity.

I don't think there are any mechanisms to support arbitrary communication over the WebSocket connection at the moment. This is just a Karma's internal part, which is not supposed to be used directly by the third-party code.

**Comment by Sayan751** [comment]
@devoto13 Your suggestion was spot on. It worked! Thank you!

Closing this issue.
