### ISSUE TITLE
Potentially vulnerable dependency ua-parser-js 0.7.21

### ISSUE THREAD

**Issue by jmthibault79** [karma-runner/karma#3562]
See https://app.snyk.io/vuln/SNYK-JS-UAPARSERJS-610226 and https://github.com/faisalman/ua-parser-js/commit/233d3bae22a795153a7e6638887ce159c63e557d

Please upgrade the dependency on ua-parser-js from the exact value "0.7.21" in order to choose corrected versions 0.7.22+

Thanks!

**Comment by devoto13** [comment]
Fixed by #3564
