### ISSUE TITLE
Add support for Yarn lifecycle scripts

### ISSUE THREAD

**Issue by handerss-tibco** [karma-runner/karma#3566]
Using Yarn, karma cannot be added as a dependency resolved from GitHub due to `package.json` lacking a `prepack` script. When Yarn clones a package from github it runs `npm install` and `npm pack`, but since karma needs to be built before being packed the resulting package will not function.

See:
https://yarnpkg.com/advanced/lifecycle-scripts
https://github.com/karma-runner/karma/issues/3530 (issue where this is a problem)

**Comment by devoto13** [comment]
I believe this has been fixed by https://github.com/karma-runner/karma/pull/3524. Are you trying to install the latest version from GitHub? Maybe your branch/version does not include this change?

**Comment by handerss-tibco** [comment]
Did a quick test and it seems that #3524 does indeed fix this issue. I linked the wrong related issue, but https://github.com/karma-runner/karma/issues/3530 is the reason for wanting to resolve from github (meant to link https://github.com/yarnpkg/berry/issues/1515). Thanks!
