### ISSUE TITLE
await promise return promise instead of value 

### ISSUE THREAD

**Issue by db-conception** [karma-runner/karma#3574]
Hello,

I don't know if it is a Karma issue, but in TS, when you do an await of function who return a promise of a value, you should get the value unwrapped.  But some functions that I am testing using Karma and jasmine are async/await but return a promise who wrap the value. 

### Expected behaviour
Please consider this code :
```javascript
let f = async () => {
  return new Promise((res) => {
    setTimeout(() => {
      res("Why am I being unwrapped")
    }, 1000)
  })
}


(async () => {
  console.log(await f())
})();
```
Return well "Why am I being unwrapped" in this jsfiddle  https://jsfiddle.net/1m7tevsz/

### Actual behaviour
But In my karma window, all my  async functions  called after a 'await' return promise. And when I execute the same script than in the jsfiddle, I get a promise too, instead of the string unwrapped.
See this screenshot : https://i.imgur.com/OgdGCzL.png 

### Environment Details

I am using karma inside a ionic project. I don't know why the command to get the version doesn't work. But you can see below my conf karma file: 

```typescript
module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular-devkit/build-angular/plugins/karma')
    ],
    client: {
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    coverageIstanbulReporter: {
      dir: require('path').join(__dirname, '../coverage'),
      reports: ['html', 'lcovonly', 'text-summary'],
      fixWebpackSourcePaths: true
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false
  });
};

```

Ionic version : 5.4.13
Jasmine version : 3.6.3
Karma version : 5.2.3 (I used 'npm view karma')

Regard,

David

**Comment by devoto13** [comment]
I don't think this has anything to do with Karma, but with how browser console works. You can observe this in the browser console even without Karma. What you see is not what is printed by `console.log()` but the result of the last expression in your code snippet, namely:

```
(async () => {
  console.log(await f())
})()
```

IIFE is async, so it returns `Promise` and that's what you see.

**Comment by db-conception** [comment]
Hello,

Thank's for your answer. 

It is not from the console. Because if you press F12 and past the snipet on the console of github, the console will well print the value unwrapped. 

And, I reproduce the bug on my code after a stack of await of async function who return value wrapped in promise. I just write this snipet with a console.log to simplify the problem for your understanding. 

Other solution ?

**Comment by db-conception** [comment]
Do you get a the promise or unwrapped value if you run karma and past the snipet in the console of one of your project ?

**Comment by devoto13** [comment]
Not sure I fully understand the problem.

> It is not from the console. Because if you press F12 and past the snipet on the console of github, the console will well print the value unwrapped.

On GitHub console will print `Promise {<pending>}` and after 1 second (when timeout handler is called) it will console.log the "Why am I being unwrapped" string. Expected behaviour.

Judging from your [screenshot](https://i.imgur.com/OgdGCzL.png) you have stopped on the breakpoint, so timeout handler is not called until you resume the execution. Hence you only see `Promise {<pending>}`, but not "Why am I being unwrapped" string.

**Comment by db-conception** [comment]
> you have stopped on the breakpoint, so timeout handler is not called until you resume the execution

Yes you was right. Sorry

**Comment by devoto13** [comment]
@db-conception No problems. Have a good one! :)
