### ISSUE TITLE
Change the style of main website to be dark mode

### ISSUE THREAD

**Issue by shanewaz-abbas** [karma-runner/karma#3582]
http://karma-runner.github.io/5.2/index.html

Since it's a developer tool, it would be really helpful to have dark mode support. The current website burns my eyes.

**Comment by johnjbarton** [comment]
Please send a pull request.

**Comment by shanewaz-abbas** [comment]
Sure

**Comment by devoto13** [comment]
I'm going to close it as duplicate of #3576 because it has more discussion. But PR is still welcome!

**Comment by devoto13** [comment]
Oh, never mind. It was about the website.

**Comment by shanewaz-abbas** [comment]
I'm almost done. Should have a pr soon.

**Comment by devoto13** [comment]
Fixed by https://github.com/karma-runner/karma-runner.github.com/pull/78. Thanks @shane99a!

**Comment by shane99a** [comment]
Awesome. Thank you !!

**Comment by jdugas** [comment]
Dark mode appears to no longer work. 
![image](https://user-images.githubusercontent.com/9133679/235912777-a9f45238-8f03-4f96-8b76-c1808041e45b.png)
