### ISSUE TITLE
Karma v5.2.3 has dependency on library with known vulnerability 

### ISSUE THREAD

**Issue by ondrejmartinak** [karma-runner/karma#3594]
I have been going through security review for up-taking the Karma v5.2.3 and noticed the dependency on library that has been patched in v5.2.2 (ua-parser-js 0.7.21 ) is still vulnerable with the same issue ua-parser-js 0.7.22.

Not sure if you are aware of recently released version 0.7.23, but just want to bring it to your attention.

Please see the detail
https://snyk.io/vuln/SNYK-JS-UAPARSERJS-1023599

**Comment by devoto13** [comment]
Thanks for the report. This has already been [fixed in master](https://github.com/karma-runner/karma/blob/master/package.json#L428) and will be included in the next release.

**Comment by talsi** [comment]
hi,
when will the next release be available?
