### ISSUE TITLE
Remove Annotation Based DI.

### ISSUE THREAD

**Issue by jginsburgn** [karma-runner/karma#3610]
There are instances of [annotation-based DI](https://github.com/vojtajina/node-di/blob/master/lib/annotation.js) in the code, for example: [here](https://github.com/karma-runner/karma/blob/1c9c2de54fa1abcb2c0edceebb159440b77e4863/lib/browser.js#L257). This feature of node-di makes it hard to figure out code, debug and trace. All uses should be removed and disallowed in the code.

**Comment by johnjbarton** [comment]
Duplicate of #3533
