### ISSUE TITLE
Group testing does not wait for shadowRoot content

### ISSUE THREAD

**Issue by lmadueno10** [karma-runner/karma#3614]
I'm trying to access the innerHTML of the wc "navbar-nv2" that is inside the shadowRoot of the wc "listproducts-nv2" however there are two different behaviors for the same test:

When I run all the tests I receive an error message "Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

But when I run the test individually it actually returns the content of shadowRoot to me and I can verify it in the console.

Although I am waiting for the fixture and for the component inside the shadowRoot using waitUntil. This is a bug that according to the documentation should wait using fixture/waitUntil.

I want to test a component that includes several components inside, when I run the independent test it doesn't present any major problem, however when I run all the tests it generates an error and returns the shadowRoot blank.

![component](https://user-images.githubusercontent.com/64743098/104140621-54e2c880-5380-11eb-9c90-8fc501fc7546.PNG)
![webcomponentev2](https://user-images.githubusercontent.com/64743098/104140623-557b5f00-5380-11eb-8e68-1e49238cbd95.PNG)
![webcomponent](https://user-images.githubusercontent.com/64743098/104140624-5613f580-5380-11eb-8092-20bc3f1b186e.PNG)
![testing](https://user-images.githubusercontent.com/64743098/104140626-56ac8c00-5380-11eb-934b-3c671c34933e.PNG)

**Comment by johnjbarton** [comment]
> But when I run the test individually it actually returns

This is a sign that your tests are not correctly set up. Other specs changed the environment and proper clean up was not performed. 

You can try disabling 1/2 of the other tests at a time as in a binary search.  Also check the devtools console for errors.  

In any case this is not a problem we can solve in the test infrastructure.
