### ISSUE TITLE
No configuration option to log error stack traces

### ISSUE THREAD

**Issue by arobinson** [karma-runner/karma#3617]
After looking through the documentation and the source code, I cannot find a way to include the stack traces for errors. This is a large issue as errors in jasmine `afterAll` blocks end up being extremely difficult to debug, especially because the errors are thrown outside of an `it` test method. In order to track down this bad/incomplete tests, we need to know where the error is occurring and that only can come from the stack trace.

In [reporter.js](https://github.com/karma-runner/karma/blob/05dc28801627e3ce7054ae548046714dc2cf7a5e/lib/reporter.js#L44) the code automatically converts `Error` objects to the `.message` property so that even providing a `formatError` function on the `config` does not allow us to get access to the error object and thus its stack property.

The `formatError` function should be invoked with the `Error` instance and not the `message` property. If this is not desirable, then please at least provide an option to include the `Error.stack` property as part of the error to be displayed.

If there is a means to get this to work with stack traces, please let me know.

**Comment by johnjbarton** [comment]
Try one of the many karma reporter plugins:
https://www.npmjs.com/search?q=karma%20reporter
We have a thin karma wrapper around the:
https://www.npmjs.com/package/jasmine-spec-reporter

**Comment by jginsburgn** [comment]
@arobinson did @johnjbarton advise solve your issue?
Closing for now.
