### ISSUE TITLE
Karma error after update to version 6.0.0

### ISSUE THREAD

**Issue by SymbioticKilla** [karma-runner/karma#3619]
Hi,

I get following error after update:

```
ERROR [karma-server]: Server start failed on port 9876: Error: No provider for "customFileHandlers"! (Resolving: framework:@angular-devkit/build-angular -> customFileHandlers)   
ERROR [karma-server]: Error while calling exit event listeners
TypeError: Cannot read property 'name' of undefined
    at TfsReporter.onExit (C:\Dev\***\spa\node_modules\karma-tfs-reporter\index.js:53:38)
    at Server.<anonymous> (C:\Dev\***\spa\node_modules\karma\lib\events.js:40:26)
    at Server.emit (events.js:327:22)
    at Server.emitExitAsync (C:\Dev\***\spa\node_modules\karma\lib\server.js:146:12)
    at Server._close (C:\Dev\***\spa\node_modules\karma\lib\server.js:413:10)
    at Server.start (C:\Dev\***\spa\node_modules\karma\lib\server.js:120:12)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

**Comment by alecgibson** [comment]
This is probably a `karma-webpack` issue: https://github.com/ryanclark/karma-webpack/issues/462

**Comment by devoto13** [comment]
Note that 6.0.0 is a major release, which has breaking changes. It is not compatible with the current release of `@angular-devkit/build-angular` package, hence the error. You should have received a warning about incompatible peer dependency from NPM when you updated to it.

The support for Karma 6.0.0 has already been added to Angular CLI (https://github.com/angular/angular-cli/pull/19784) and will probably be released in 11.1.0. Until then, please stick with Karma 5.x.

**Comment by SymbioticKilla** [comment]
@devoto13 Thanks! Will it be back ported to 10.2?

**Comment by devoto13** [comment]
I don’t think so. AFAIK only critical fixes get backported.

**Comment by SymbioticKilla** [comment]
Ist it possible to back port CVE Fixes to Karma 5?

**Comment by devoto13** [comment]
Unfortunately we don't have a process to backport changes at the moment... I guess we can either try to make a patch release on 5.x branch or restore `customFileHandlers` provider with the deprecation warning on the 6.x branch (so people can use Karma 6.x with older Angular CLI with the peer dependency warning). 

@johnjbarton Which option do you think is better?
