### ISSUE TITLE
Upgrade to socket.io v4

### ISSUE THREAD

**Issue by johnjbarton** [karma-runner/karma#3620]
We just updated to v3, but v4 has an important improvement that should help karma-runner on large web app tests:

https://github.com/socketio/engine.io-client/commit/81d7171c6bb4053c802e3cc4b29a0e42dcf9c065

The update would be a breaking change.

**Comment by devoto13** [comment]
We don't depend on `engine.io-client` NPM package and we already require the latest [`socket.io`](https://www.npmjs.com/package/socket.io) (which depends on the engine protocol v4 according to the [migrations docs](https://socket.io/docs/v3/migrating-from-2-x-to-3-0/)). I think we can close this issue as done.
