### ISSUE TITLE
CVE issue with karma@3.1.4 -> socket.io@2.1.1

### ISSUE THREAD

**Issue by kumarmadurai** [karma-runner/karma#3648]
Please read http://karma-runner.github.io/4.0/intro/troubleshooting.html first
the fixed version is socket.io@2.4.0

please tell me which version has this fix or can you please fix this

thanks

**Comment by devoto13** [comment]
The latest version of Karma is 6.1.0 and it depends on socket.io@3.1.0, so it should be fixed. We only make security fixes on master, so either update to the latest or look through the [changelog](https://github.com/karma-runner/karma/blob/master/CHANGELOG.md) or use 5.2.3, which depends on the latest socket.io@2 release.
