### ISSUE TITLE
For every change karma test case count is added to previous one

### ISSUE THREAD

**Issue by KrishnaAnanthi** [karma-runner/karma#3670]
### Expected behaviour
Everytime karma has to show same test case count untill new test cases are never added

### Actual behaviour
karma is adding testcase count to previous run. let says there are 300 test cases. first time it shows 300, next it shows 600 then 900,.. it keeps increasing

### Environment Details

- Karma version (output of `karma --version`):
- Relevant part of your `karma.config.js` file

### Steps to reproduce the behaviour

1. run ng test --code-coverage --> shows test case count

========================================================================================================================
START:

Finished in 0 secs / 0 secs @ 15:20:51 GMT+0530 (India Standard Time)

SUMMARY:
√ 269 tests completed
TOTAL: 269 SUCCESS

=============================== Coverage summary ===============================
Statements   : 94.27% ( 1136/1205 )
Branches     : 85.69% ( 425/496 )
Functions    : 88.53% ( 332/375 )
Lines        : 94% ( 1081/1150 )
================================================================================
05 04 2021 15:20:52.179:WARN [reporter.coverage-istanbul]: Coverage for statements (94.27%) does not meet global threshold (100%)
05 04 2021 15:20:52.179:WARN [reporter.coverage-istanbul]: Coverage for lines (94%) does not meet global threshold (100%)
05 04 2021 15:20:52.181:WARN [reporter.coverage-istanbul]: Coverage for branches (85.69%) does not meet global threshold (100%)
05 04 2021 15:20:52.182:WARN [reporter.coverage-istanbul]: Coverage for functions (88.53%) does not meet global threshold (100%)
========================================================================================================================
START:

Finished in 0 secs / 0 secs @ 15:21:01 GMT+0530 (India Standard Time)

SUMMARY:
√ 522 tests completed
× 1 test failed

FAILED TESTS:

=============================== Coverage summary ===============================
Statements   : 94.27% ( 1136/1205 )
Branches     : 85.69% ( 425/496 )
Functions    : 88.53% ( 332/375 )
Lines        : 94% ( 1081/1150 )
================================================================================
05 04 2021 15:21:02.338:WARN [reporter.coverage-istanbul]: Coverage for statements (94.27%) does not meet global threshold (100%)
05 04 2021 15:21:02.339:WARN [reporter.coverage-istanbul]: Coverage for lines (94%) does not meet global threshold (100%)
05 04 2021 15:21:02.340:WARN [reporter.coverage-istanbul]: Coverage for branches (85.69%) does not meet global threshold (100%)
05 04 2021 15:21:02.340:WARN [reporter.coverage-istanbul]: Coverage for functions (88.53%) does not meet global threshold (100%)

=============================== Coverage summary ===============================
Statements   : Unknown% ( 0/0 )
Branches     : Unknown% ( 0/0 )
Functions    : Unknown% ( 0/0 )
Lines        : Unknown% ( 0/0 )

========================================================================================================================
START:

Finished in 0 secs / 0 secs @ 15:21:20 GMT+0530 (India Standard Time)

SUMMARY:
√ 1076 tests completed
TOTAL: 1076 SUCCESS

=============================== Coverage summary ===============================
Statements   : 94.36% ( 1137/1205 )
Branches     : 85.69% ( 425/496 )
Functions    : 88.8% ( 333/375 )
Lines        : 94.09% ( 1082/1150 )
================================================================================
05 04 2021 15:21:21.346:WARN [reporter.coverage-istanbul]: Coverage for statements (94.36%) does not meet global threshold (100%)
05 04 2021 15:21:21.346:WARN [reporter.coverage-istanbul]: Coverage for lines (94.09%) does not meet global threshold (100%)
05 04 2021 15:21:21.347:WARN [reporter.coverage-istanbul]: Coverage for branches (85.69%) does not meet global threshold (100%)
05 04 2021 15:21:21.348:WARN [reporter.coverage-istanbul]: Coverage for functions (88.8%) does not meet global threshold (100%)

=============================== Coverage summary ===============================
Statements   : 94.36% ( 1137/1205 )
Branches     : 85.69% ( 425/496 )
Functions    : 88.8% ( 333/375 )
Lines        : 94.09% ( 1082/1150 )

**Comment by KrishnaAnanthi** [comment]
karma version is 5.0.2
  "_from": "karma@5.0.2",
  "_id": "karma@5.0.2",

**Comment by johnjbarton** [comment]
sorry none of this is from karma-runner. You need to look into the plugins loaded by `ngtest`.

Obviously if the count is increasing then you are not exiting the test, eg you are not using `single-run`, the normal setup for testing.  The only time we use `--no-single-run` is for debugging.

**Comment by KrishnaAnanthi** [comment]
I am using defualt karma loaded by angular project

**Comment by devoto13** [comment]
@KrishnaAnanthi As pointed out by @johnjbarton, `ng test` command is provided by Angular CLI (a plugin for Karma, not the Karma itself), so there is not much we can do here.

I've tried to reproduce the problem with the latest Angular CLI project and everything seems to work correctly:

```
$ npm i -g @angular/cli@latest
+ @angular/cli@11.2.7
$ ng new test-project
$ cd test-project
$ ng test --code-coverage
⠋ Generating browser application bundles...06 04 2021 14:53:16.968:WARN [karma]: No captured browser, open http://localhost:9876/
06 04 2021 14:53:16.973:INFO [karma-server]: Karma v6.1.2 server started at http://localhost:9876/
06 04 2021 14:53:16.973:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
⠙ Generating browser application bundles (phase: building)...06 04 2021 14:53:16.977:INFO [launcher]: Starting browser Chrome
✔ Browser application bundle generation complete.
06 04 2021 14:53:22.019:WARN [karma]: No captured browser, open http://localhost:9876/
06 04 2021 14:53:22.138:INFO [Chrome 89.0.4389.114 (Mac OS 11.2.3)]: Connected on socket ZjWEawYitis11qVcAAAB with id 82869791
Chrome 89.0.4389.114 (Mac OS 11.2.3): Executed 3 of 3 SUCCESS (0.259 secs / 0.179 secs)
TOTAL: 3 SUCCESS

=============================== Coverage summary ===============================
Statements   : 100% ( 6/6 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 0/0 )
Lines        : 100% ( 5/5 )
================================================================================
✔ Browser application bundle generation complete.
Chrome 89.0.4389.114 (Mac OS 11.2.3) AppComponent should have as title 'test-project' FAILED
	Error: Expected 'test-project' to equal 'test-project1'.
	    at <Jasmine>
	    at UserContext.<anonymous> (src/app/app.component.spec.ts:20:23)
	    at ZoneDelegate.invoke (node_modules/zone.js/dist/zone-evergreen.js:372:1)
	    at ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/zone-testing.js:301:1)
Chrome 89.0.4389.114 (Mac OS 11.2.3): Executed 3 of 3 (1 FAILED) (0.27 secs / 0.25 secs)
TOTAL: 1 FAILED, 2 SUCCESS

=============================== Coverage summary ===============================
Statements   : 100% ( 6/6 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 0/0 )
Lines        : 100% ( 5/5 )
================================================================================
✔ Browser application bundle generation complete.
Chrome 89.0.4389.114 (Mac OS 11.2.3): Executed 3 of 3 SUCCESS (0.151 secs / 0.135 secs)
TOTAL: 3 SUCCESS

=============================== Coverage summary ===============================
Statements   : 100% ( 6/6 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 0/0 )
Lines        : 100% ( 5/5 )
================================================================================
✔ Browser application bundle generation complete.
```

So most likely the problem is somewhere in your code or configuration and we can only guess without a minimal reproduction. What I would recommend is to create a new Angular project, add a minimal code, which reproduces the problem, and report this issue to the Angular CLI repository (https://github.com/angular/angular-cli) as `ng test` command and Angular plugin are developed there.
