### ISSUE TITLE
Module imports without extension fail loading

### ISSUE THREAD

**Issue by mlasak** [karma-runner/karma#3678]
I've configured regarding the documentation as follows

karma.config.js
```JavaScript
    files: [
      { pattern: 'test/**/*.js', type: 'module' },
      { pattern: 'src/**/*.js', type: 'module', included: false }
    ],
```

Then when using a working mocha test with imports without .js extensions, like
```JavaScript
import TestModule from '../../src/TestModule';

````

...the execution with karma fails with:
```bash
...
26 05 2021 15:09:57.267:WARN [web-server]: 404: /base/src/TestModule
Chrome Headless 90.0.4430.212 (Mac OS 10.15.7) ERROR
  Uncaught Error loading test/Test.js
  at http://localhost:9876/context.html:286:271
```

Importing '../../src/TestModule.js' does work, but is not a solution as the TestModule.js itself imports without extensions. The implementation of TestModule.js shall not be changed.

Is this a bug in Karma runner or did a missed an important configuration here? Help appreciated

**Comment by mlasak** [comment]
Ok,  closing this one. I think it's a duplicate of https://github.com/karma-runner/karma/issues/3335

**Comment by mlasak** [comment]
Sorry, not sure if this one is a duplicate of #3335 
They do not mention extensions there. Re-opening. Any comments?

**Comment by devoto13** [comment]
Seems to work as intended: https://stackoverflow.com/a/55289496/1377864

> In a browser with support for ES Modules (ESM), no extensions will be added to the URL that you import - if your file for example has .js extension, you have to write import {x} from "./file.js".

Unless you told it to do so, Karma will not do any file processing, so it will just load the file "as is" in the browser.

**Comment by mlasak** [comment]
Got it working as i needed it with [karma-webpack ](https://github.com/ryanclark/karma-webpack). I believe it works there due to webpack's ```transformPath```

If there is no way doing it in karma without any plugins then we can close this issue.

**Comment by devoto13** [comment]
No, there is no way to do it without plugins. Vanilla Karma just loads your JS code in the browser without any extra processing and therefore JS should be in the format which the browser understands.
