### ISSUE TITLE
Is there a way to output the .js bundle for debugging?

### ISSUE THREAD

**Issue by kruncher** [karma-runner/karma#3687]
We have the following in our 'karma.conf.js' file:

```js
preprocessors: {
    'src/tests/spec/**/*.spec.js': ['browserify'],
},

browserify: {
    debug: true,
    transform: [
        [ 'babelify', {
            presets: [
                [
                    '@babel/preset-env',
                    {
                        targets: {
                            browsers: ['ie 11'],
                        },
                    },
                ],
            ],
        } ]
    ],
},
```

However, we are seeing the following error when the tests are ran in BrowserStack for Windows 10 IE11:

> Unexpected quantifier
  at /tmp/lib/rendering/helpers/sub-navigation-helper.js:1:1 <- /tmp/24f96a134b2ab6d26815c25cc31cf787.browserify.js:103:14531

Having looked up the error it seems to be caused by the lack of support in IE11 for lookbehind in regular expressions. The strange thing is that it works fine with the exact same browserify/babelify configuration in our build function.

Is there a way to have karma output the transformed .js so that we can verify that the lookahead regular expression logic is actually being converted into something that works in IE11?

**Comment by devoto13** [comment]
I don't think there is something built-in for this purpose in karma.

Assuming that you can't check the actual served file from the Network tab in the browser's developer tools, I guess you can use [`configure`](https://github.com/nikku/karma-browserify#additional-bundle-configuration) to add an event listener for the [`bundle` event](https://github.com/browserify/browserify#bonbundle-function-bundle-) and then print/save the generated bundle to somewhere.

**Comment by kruncher** [comment]
Thank you; I have added the following:
```js
      configure: function(bundle) {
        bundle.on('bundle', function(output) {
          console.log(output)
          fs.writeFileSync('./bundle.js', output, { encoding: 'utf8' });
        });
      }
```
But all that I am seeing is the following:
```
_readableState: ReadableState {
    objectMode: true,
    highWaterMark: 16,
    buffer: BufferList { length: 0 },
    length: 0,
    pipes: ConcatStream {
      _writableState: [WritableState],
      writable: true,
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      encoding: undefined,
      shouldInferEncoding: true,
      body: [],
      [Symbol(kCapture)]: false
    },
    pipesCount: 1,
    flowing: true,
    ended: false,
    endEmitted: false,
    reading: false,
    sync: true,
    needReadable: false,
    emittedReadable: false,
    readableListening: false,
    resumeScheduled: true,
    destroyed: false,
    defaultEncoding: 'utf8',
    awaitDrain: 0,
    readingMore: false,
    decoder: null,
    encoding: null
  },
  readable: true,
  _events: [Object: null prototype] {
    error: [Function (anonymous)],
    end: [Function: bound onceWrapper] { listener: [Function: onend] },
    data: [Function: ondata]
  },
  _eventsCount: 3,
  _maxListeners: undefined,
  _read: [Function (anonymous)],
  [Symbol(kCapture)]: false
}
```
How do I pull the content from this stream?

**Comment by devoto13** [comment]
I guess [something like this](https://stackoverflow.com/a/49428486/1377864) will work?

**Comment by kruncher** [comment]
Awesome, thank you that worked perfectly.
