### ISSUE TITLE
yarn berry works, but plugins need to be explicitly defined in config

### ISSUE THREAD

**Issue by timmywil** [karma-runner/karma#3689]
I recently upgraded a project to yarn 2. I wasn't sure the problem and was searching issues here for guidance.

I eventually figured out that I needed to specify all karma plugins explicitly:

```js
plugins: ['karma-mocha', 'karma-typescript', 'karma-firefox-launcher'],
```

This wasn't necessary with npm or yarn 1, but is obvious to me in retrospect. karma probably searches the node_modules folder for karma plugins and the node_modules folder doesn't exist when using yarn berry.

I just wanted to post this issue here for anyone having the same problem.

karma may be able to change the way it's looking for karma plugins to fix this issue, but it's not a big deal once I knew how to fix it so I will just immediately close this. You may also consider documenting this for anyone using yarn berry.

Thanks.

**Comment by jginsburgn** [comment]
Thanks for sharing this :)
