### ISSUE TITLE
Who to contact for security issues

### ISSUE THREAD

**Issue by JamieSlome** [karma-runner/karma#3737]
Hey there!

I belong to an open source security research community, and a member (@r0hansh) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by CarlMungazi** [comment]
@JamieSlome Are you by any chance referring to [this issue](https://github.com/advisories/GHSA-273r-mgr4-v34f)? I wanted to raise a ticket since the latest version of Karma depends on a `socket.io` version which in turn depends on the affected `engine-io` package. Will avoid double posting if you opened this issue regarding that matter.

**Comment by JamieSlome** [comment]
@CarlMungazi - no, the issue that has been reported to us is meant to be in the component itself.

**Comment by katrina95** [comment]
We are working on this, pull request: https://github.com/karma-runner/karma/pull/3746. 

If you have any urgent security issue, please contact karma-runner-eng+security@google.com.

**Comment by JamieSlome** [comment]
E-mail sent! ❤️ 

Just for reference, the report can be found here:

https://huntr.dev/bounties/64b67ea1-5487-4382-a5f6-e8a95f798885/ - it is private and only accessible to maintainers with repository write permissions.

**Comment by katrina95** [comment]
SECURITY.md is added in repo and we have received your report. Thanks :)

**Comment by amarden** [comment]
> @JamieSlome Are you by any chance referring to [this issue](https://github.com/advisories/GHSA-273r-mgr4-v34f)? I wanted to raise a ticket since the latest version of Karma depends on a `socket.io` version which in turn depends on the affected `engine-io` package. Will avoid double posting if you opened this issue regarding that matter.

Sorry to be off-topic on the thread, but has an issue for the engine-io vulnerability been opened?, I could not locate it myself. Thank you.

**Comment by jginsburgn** [comment]
> > @JamieSlome Are you by any chance referring to [this issue](https://github.com/advisories/GHSA-273r-mgr4-v34f)? I wanted to raise a ticket since the latest version of Karma depends on a `socket.io` version which in turn depends on the affected `engine-io` package. Will avoid double posting if you opened this issue regarding that matter.
> 
> Sorry to be off-topic on the thread, but has an issue for the engine-io vulnerability been opened?, I could not locate it myself. Thank you.

@amarden I was not able to locate an issue about that vulnerability. Please feel free to create one.

**Comment by jginsburgn** [comment]
Actually, it is better to use the process laid out in SECURITY.md to report vulnerabilities. Please follow it :)

**Comment by devoto13** [comment]
Both [this issue](https://github.com/advisories/GHSA-273r-mgr4-v34f) and [this issue](https://huntr.dev/bounties/64b67ea1-5487-4382-a5f6-e8a95f798885/) are fixed now. And the `SECURITY.md` file has been added, so I'm closing this as resolved.
