### ISSUE TITLE
pin colors lib to 1.4.0 as it been hacked and version 1.4.1 is broken

### ISSUE THREAD

**Issue by arelg** [karma-runner/karma#3738]
Please read https://karma-runner.github.io/4.0/intro/troubleshooting.html first
https://github.com/Marak/colors.js/issues/285#issuecomment-1008168237

**Comment by donmahallem** [comment]
No hack... just the author breaking his package on purpose. he did the same with faker.js

**Comment by arelg** [comment]
didnt know ty @YoniSegal for patching

**Comment by bouhady** [comment]
the problem also exists on 1.4.0 suddenly! 
is there any workaround for libraries such as gulp-nodemon which is using this version as sub-dependencies?

**Comment by YoniSegal** [comment]
> the problem also exists on 1.4.0 suddenly! is there any workaround for libraries such as gulp-nodemon which is using this version as sub-dependencies?

Are you sure you're using 1.4.0?
I'm not having any issues.

**Comment by YoniSegal** [comment]
> didnt know ty @YoniSegal for patching

No problem.
I closed my PR because I've never contributed to an open source project and am not sure i'm doing it right.

The PR is trying to merge into master, but I want it to fix an issue at the v4.4.1 tag.

**Comment by XhmikosR** [comment]
@jginsburgn this should be addressed sooner than later since it seems npm hasn't removed the offending colors versions.

**Comment by esskar** [comment]
Please provide a quick fix with an update to 1.4.0

**Comment by RupprechJo** [comment]
Yes, this is really urgent, breaks all builds with karma on the CI Server

**Comment by donmahallem** [comment]
Can't you just add colors as dev dependency with pinned version to 1.4.0 as a temporary fix? 

E.g.

`npm install --save-dev --save-exact colors@1.4.0`

**Comment by sharif-elshobkshy** [comment]
Hello everyone.

Currently Magicscroll is using the newest/latest "Colors" version.

https://github.com/karma-runner/karma/blob/master/package.json#L427
`"colors": "^1.4.0"`

If a new tag is created on "Colors", Karma will eventually update "Colors" to newest (broken) version.

Shouldn't Karma fix the package on the latest working version (before the corrupted commits)?
`"colors": "1.4.0"`

Thanks.

**Comment by falsandtru** [comment]
npm fixed colors and karma works well now.

**Comment by reduckted** [comment]
Looks like this was fixed in #3763 and releasd in v6.3.17.

**Comment by devoto13** [comment]
Closing per above.
