### ISSUE TITLE
OOM in 6.3.10

### ISSUE THREAD

**Issue by taymonbeal** [karma-runner/karma#3744]
https://github.com/google/fledge-shim/runs/4765450371

Upgrading Karma from 6.3.9 to 6.3.10 causes what appear to be out-of-memory errors on GitHub Actions. Rerunning the job doesn't help. The PR is from Dependabot and makes no other changes, and everything's passing at head, so I figure this has to somehow be a Karma regression.

**Comment by devoto13** [comment]
See https://github.com/karma-runner/karma/issues/3738.
