### ISSUE TITLE
Deprecation warning related to log4js syntax

### ISSUE THREAD

**Issue by andrei-gheorghiu** [karma-runner/karma#3753]
When running tests in a brand new Angular 12 application, I'm getting the following deprecation warning:

> (node:14940) [log4js-node-DEP0004] DeprecationWarning: Pattern %d{DATE} is deprecated due to the confusion it causes when used. Please use %d{DATETIME} instead.

, which is pretty self-explanatory. 

Is there a fix in sight? 
Thanks.

**Comment by devoto13** [comment]
Are you using [the latest 6.3.12 release](https://github.com/karma-runner/karma/releases/tag/v6.3.12)?

**Comment by andrei-gheorghiu** [comment]
> Are you using [the latest 6.3.12 release](https://github.com/karma-runner/karma/releases/tag/v6.3.12)?

No, i'm on `6.3.11` (installed today), using `ng generate name-of-project`
