### ISSUE TITLE
Forbid new branches

### ISSUE THREAD

**Issue by jginsburgn** [karma-runner/karma#3760]
@devoto13 I propose that we should forbid creating new branches on this repository and work by having PRs have head branches from repo forks. This will ensure that this repo is always tidy (i.e. no stale branches). WDYT?

**Comment by devoto13** [comment]
One reason why we may want to use branches in this repo is to run CI with BrowserStack and SauceLabs enabled as branches in this repo will have access to the tokens while branches in forks won't have it unless we copy the same values to our own forks. I agree about keeping this repository tidy as much as possible, but I'm not sure if outright prohibiting to create braches is a good idea as we'll loose a possibility to debug CI failures which comes quite handy sometimes. E.g. I could not reproduce https://github.com/karma-runner/karma/issues/3730#issuecomment-977174906 on my local machine, but it reproduced on CI.

**Comment by jginsburgn** [comment]
You're right!
