### ISSUE TITLE
ERROR [karma]: { inspect: [Function: inspect] }

### ISSUE THREAD

**Issue by charafsalmi** [karma-runner/karma#3764]
Hi,

On an angular project, the test stops with only this error.

```
17 02 2022 10:33:56.251:ERROR [karma]: { inspect: [Function: inspect] }
17 02 2022 10:33:56.252:DEBUG [launcher]: Disconnecting all browsers
17 02 2022 10:33:56.541:DEBUG [launcher]: Process Chrome exited with code 0
17 02 2022 10:33:56.541:DEBUG [temp-dir]: Cleaning temp dir C:\Users\---\AppData\Local\Temp\karma-11132084
17 02 2022 10:33:56.658:DEBUG [launcher]: Finished all browsers
```

Using ```"karma": "^2.0.2",``` as a devDependency on this angular project. No single run is set to true, as well as log level set to debug. On a windows 10 environment. NG Code 9.1.12, Jasmine ^2.8.17 .

Is there a way to have more verbosity ?

Thank you.

**Comment by charafsalmi** [comment]
After a huge investigation, I ended up locating the issue as coming from karma/lib/server.js line 355 on my version :
```
    processWrapper.on('uncaughtException', (error) => {
      this.log.error(error)
    })
```
No explicit log or trace here, unfortunately.

On master, it points to a more verbose code : https://github.com/karma-runner/karma/blob/ab4b32898bcb4e0ba3a1e99835d30c113db3eeeb/lib/server.js#L404

**Comment by devoto13** [comment]
I have a vague memory of something like this being fixed some long time ago. IIRC the problem was that some Node version has made `req.headers` non-enumerable as a result code like `{ ...req }` stopped copying the request `headers` somewhere in Angular CLI plugin for karma, which caused this problem and was then fixed. 

You seem to be using quite old versions, consider updating to the newer versions.

**Comment by devoto13** [comment]
Here are some refs: https://github.com/nodejs/node/issues/36550, https://github.com/karma-runner/karma/issues/3588, https://github.com/angular/angular-cli/issues/19644

**Comment by devoto13** [comment]
Hope you were able to resolve your problem by now.
Closing as a stale support request.
