### ISSUE TITLE
Tests does not run as expected with WebAssembly

### ISSUE THREAD

**Issue by ZhaoXiangXML** [karma-runner/karma#3800]
I'm trying to write some unit tests in typescript for a WebAssembly (wasm) lib written in rust. I'm developing on Windows 10.

I've a sample project [here](https://github.com/ZhaoXiangXML/threets-rust-wasm-template). To compile the rust part, you will need to install [rust](https://www.rust-lang.org/tools/install) and [wasm-pack](https://rustwasm.github.io/wasm-pack/installer/).

The test file looks like this:

```typescript

console.log("before import");
import * as wasm from '../target/pkg'

console.log("after import");
describe("test", function () {
    it("should be ok", function () {
        console.log("test 1");
        expect(wasm.get_color()).to.be("#F5D742");
    }),
    it("should be also ok", function () {
        console.log("test 2");
        expect(1).to.be(1);
    })
})
console.log("end of file");
```

There are two tests, a wasm one and a javascript one. Both should be ok.

## Case 1: large .wasm file

So I ran the tests with `npm run test`, I got this output in terminal:

```
TOTAL: 0 SUCCESS
```

No tests ran as there was no console log from my code.

By checking Chrome Dev tool, Network tab, I noticed the .wasm file is not fully downloaded. Chrome says 69.6KB was downloaded but there should be 15MB.

## Case 2: large .wasm file in Karma Debug page
So I clicked the "DEBUG" button, things are getting better, I've this in Chrome console log:
```
Skipped 0 tests
test.spec.ts:6 before import
test.spec.ts:8 after import
test.spec.ts:19 end of file
```

The .wasm file is successfully downloaded, all 15MB of 15MB, but still no tests ran.

## Case 3: small .wasm file

Then I removed the `get_some_large_string` function in lib.rs file, this time the compiled .wasm file size is 58KB.

I got logs like this:

```
LOG: 'before import'
LOG: 'after import'
LOG: 'end of file'
TOTAL: 0 SUCCESS
```

By refresh the page in Chrome for several times, I got this log:

```
Chrome 102.0.5005.63 (Windows 10) LOG: 'before import'

Chrome 102.0.5005.63 (Windows 10) LOG: 'after import'

Chrome 102.0.5005.63 (Windows 10) LOG: 'end of file'

LOG: 'test 1'
LOG: 'test 2'
Chrome 102.0.5005.63 (Windows 10): Executed 2 of 0 SUCCESS (0.002 secs / 0 secs)
TOTAL: 2 SUCCESS
```

It's now working!

I think the problem has something to do with WebAssembly download and compilation must happen asynchronous, there is a line `asyncWebAssembly: true` in karma.conf.js which is required.

Please kindly check out this issue. Thanks.

**Comment by ZhaoXiangXML** [comment]
I've also tried:

```typescript
console.log("before import");
import * as wasm from '../target/pkg'

console.log("after import");
describe("test", function () {
    it("should be ok", function () {
        console.log("test 1");
        expect((async wasm).get_color()).to.be("#F5D742");
    }),
    it("should be also ok", function () {
        console.log("test 2");
        expect(1).to.be(1);
    })
})
console.log("end of file");
```

The result is the same

**Comment by ZhaoXiangXML** [comment]
I've also tried:

```typescript

console.log("before import");
import('../target/pkg').then((wasm) => {
    console.log("after import");
    describe("test", function () {
        it("should be ok", function () {
            console.log("test 1");
            expect(wasm.get_color()).to.be("#F5D742");
        }),
        it("should be also ok", function () {
            console.log("test 2");
            expect(1).to.be(1);
        })
    })
 });


console.log("end of file");
```

The result is 
```
Chrome 102.0.5005.63 (Windows 10) LOG: 'before import'

Chrome 102.0.5005.63 (Windows 10) LOG: 'end of file'

Chrome 102.0.5005.63 (Windows 10): Executed 0 of 0 SUCCESS (0.001 secs / 0 secs)
TOTAL: 0 SUCCESS
```

**Comment by ZhaoXiangXML** [comment]
This works:

```typescript

console.log("before import");

let wasm : typeof import('../target/pkg');

describe("test", function () {
    before(async function () {
        wasm = await import('../target/pkg');
        console.log("after import");
    });
    it("should be ok", function () {
        console.log("test 1");
        expect(wasm.get_color()).to.be("#F5D742");
    }),
    it("should be also ok", function () {
        console.log("test 2");
        expect(1).to.be(1);
    })
})

console.log("end of file");
```

**Comment by abdojulari** [comment]
I am facing the issue with angular but in my case I am using automerge and karma. Automerge uses webassembly
