### ISSUE TITLE
Dependencies problem

### ISSUE THREAD

**Issue by szqsy17** [karma-runner/karma#3805]
Karma v5.2.3 depends on socket.io ^2.3.0. When new participant run "npm install" in our project, it will download socket.io v2.5.0. But from the [release page](https://github.com/socketio/socket.io/releases/tag/2.5.0) we can known that the threshold of websocket reduces from 100Mb to 1Mb. But in our project, it can be easily more than 1 Mb.

**Comment by jginsburgn** [comment]
Unfortunately we only support the latest version for Karma, which at the moment is 6.4.0. Try updating to the latest and determining if that solves your problem. Otherwise reopen this bug agains the latest version.
