### ISSUE TITLE
:has is broken in jquery so also in karma cause it has it as dependency [chrome 105]

### ISSUE THREAD

**Issue by pascalvos** [karma-runner/karma#3814]
since release chrome 105 and some others that now suport **:has**
this is something that is supported inside chrome now see: https://developer.chrome.com/blog/new-in-chrome-105
this brakes jquery and also karma when using chrome 105 see issue: https://github.com/jquery/jquery/issues/5098
might be an idea to keep a eye on this and update jquery when posible.

**Comment by mgol** [comment]
Where does Karma use jQuery?
