### ISSUE TITLE
An error was thrown in afterAll. Error during loading: Uncaught ReferenceError: my_interface_name_1 is not defined in http://localhost:9876/_karma_webpack_/main.js

### ISSUE THREAD

**Issue by labeled** [karma-runner/karma#3815]
I'm attempting to upgrade my angular to latest. In doing so I am receiving some really strange issues running karma unit tests. It appears as though webpack is looking for my interface type to be defined and it's not.
Here is the code (I can make the error go away by typing it to 'any' but do not want to do this)
![image](https://user-images.githubusercontent.com/17855377/189532949-007ee1ca-54e9-4e12-8c5c-06abdeb8133c.png)
Where AlertDialogConfig is a simple interface
![image](https://user-images.githubusercontent.com/17855377/189532959-c35e4c91-62b5-4fc0-9b05-81ef0e6c840a.png)
Here is the compiled source in main.js
```
/***/ 83620:
/*!************************************************************************************!*\
  !*** ./libs/shared/ui/alert-dialog/src/lib/alert-dialog/alert-dialog.component.ts ***!
  \************************************************************************************/
/***/ ((__unused_webpack_module, exports, __webpack_require__) => {

"use strict";

var _a;
Object.defineProperty(exports, "__esModule", ({ value: true }));
exports.AlertDialogComponent = void 0;
const tslib_1 = __webpack_require__(/*! tslib */ 34929);
const core_1 = __webpack_require__(/*! @angular/core */ 22560);
const dialog_1 = __webpack_require__(/*! @angular/material/dialog */ 31484);
let AlertDialogComponent = class AlertDialogComponent {
    constructor(alertDialogConfig) {
        this.alertDialogConfig = alertDialogConfig;
    }
};
AlertDialogComponent.ctorParameters = () => [
    { type: undefined, decorators: [{ type: core_1.Inject, args: [dialog_1.MAT_DIALOG_DATA,] }] }
];
AlertDialogComponent = tslib_1.__decorate([
    (0, core_1.Component)({
        selector: 'altec-alert-dialog',
        template: __webpack_require__(/*! ./alert-dialog.component.html?ngResource */ 59897),
        changeDetection: core_1.ChangeDetectionStrategy.OnPush,
        styles: [__webpack_require__(/*! ./alert-dialog.component.scss?ngResource */ 73724)]
    }),
    tslib_1.__metadata("design:paramtypes", [typeof (_a = typeof alert_dialog_config_1.AlertDialogConfig !== "undefined" && alert_dialog_config_1.AlertDialogConfig) === "function" ? _a : Object])
], AlertDialogComponent);
exports.AlertDialogComponent = AlertDialogComponent;
```
The third from the last line is where it is failing `alert_dialog_config_1.AlertDialogConfig` where alert_dialog_config_1 is undefined.
Here is my karma.config.js settings. 
```
const { constants } = require('karma');

module.exports = () => {
  return {
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('@angular-devkit/build-angular/plugins/karma')
    ],
    client:{
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    reporters: ['progress', 'kjhtml'],
    colors: true,
    logLevel: constants.LOG_DEBUG,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false,
    reportSlowerThan: 100
  };
};
```
Here are my versions
```
    "@angular/cli": "~14.2.2".
    "@angular/core": "14.2.1",
    "@angular-devkit/build-angular": "14.2.2",
    "karma": "6.4.0",
    "karma-chrome-launcher": "3.1.1",
    "karma-cli": "~2.0.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "5.1.0",
    "karma-jasmine-html-reporter": "2.0.0",
    "karma-spec-reporter": "^0.0.34",
    "@angular/material": "14.2.1",
    "tslib": "^2.4.0",
"webpack": "5.4.0"
```
It's possible I'm missing something but I can't seem to put my finger on why the compiled source expects the interface to be defined. And as I said above, if I type it to 'any' it's fine but breaks on another place that I do the same thing.
It's worth noting that it builds and serves just fine.

**Comment by labeled** [comment]
I was able to find some configuration settings in my config files that were incorrect and have resolved the issue.

**Comment by fonsecaj** [comment]
@labeled Hello, can you provide more information about how you resolved this issue, please? I've the same problem 😞

**Comment by labeled** [comment]
> @labeled Hello, can you provide more information about how you resolved this issue, please? I've the same problem 😞

I'll have to check my notes on Monday. I believe it was a tsconfig setting I had to change.  Make sure there are no trailing commas.

**Comment by H0schi** [comment]
I had the same error. Maybe my case also helps someone: I use Angular and had imports from my data model files to the `app-routing.module.ts` file which exported an object and also imported many main app files. I think this lead to some sort of circular dependency problem, that otherwise did not materialize when using `ng serve` (probably because the order of execution/loading/import is different with `ng serve`) The Uncought ReferenceError was resolved by moving the exported object of `app-routing.module.ts` to a separate file.

I managed to locate the problem by looking at the file on top of the errors "stack trace" and then examining each import in that file. After eliminating each import one by one, I found a state where no error was thrown. Then I looked into the file of the removed import and did the elimination thing again, which lead me to the import of `app-routing.module.ts`.

**Comment by Fellendorf** [comment]
> I had the same error. Maybe my case also helps someone: I use Angular and had imports from my data model files to the `app-routing.module.ts` file which exported an object and also imported many main app files. I think this lead to some sort of circular dependency problem, that otherwise did not materialize when using `ng serve` (probably because the order of execution/loading/import is different with `ng serve`) The Uncought ReferenceError was resolved by moving the exported object of `app-routing.module.ts` to a separate file.
> 
> I managed to locate the problem by looking at the file on top of the errors "stack trace" and then examining each import in that file. After eliminating each import one by one, I found a state where no error was thrown. Then I looked into the file of the removed import and did the elimination thing again, which lead me to the import of `app-routing.module.ts`.

Your comment helped me a lot, thank you!
In my case, an enum with route paths (as strings) was exported from "app.routes.ts". After moving this enum to a separate file, the issue disappeared.
