### ISSUE TITLE
Tests are being run multiple times in a row

### ISSUE THREAD

**Issue by ProLoser** [karma-runner/karma#393]
I'm not sure why it appears that the test suite is running over and over:

https://travis-ci.org/angular-ui/ui-select2/builds/5462673

The repo in question:

https://github.com/angular-ui/ui-select2

**Comment by mrlove** [comment]
Hi, same for me.

i am running an jasmine test with two test cases in it and it runs 30. times in a row. :(

**Comment by justinIs** [comment]
Same issue for me, however I get an error on my third try:

```
*-web$ grunt karma:store
Running "karma:store" (karma) task
08 09 2015 12:07:30.011:INFO [karma]: Karma v0.13.9 server started at http://localhost:9876/
08 09 2015 12:07:30.019:INFO [launcher]: Starting browser Chrome
08 09 2015 12:07:30.972:INFO [Chrome 45.0.2454 (Mac OS X 10.10.5)]: Connected on socket yg--JmBSGa5yqVSxAAAA with id 41886837
Chrome 45.0.2454 (Mac OS X 10.10.5): Executed 9 of 9 SUCCESS (0 secs / 0.396 secs)
ERROR: 'RefererNotAllowedMapError: https://developers.google.com/console/help/new/#apikeybestpractices'
ALERT: 'This page was unable to display a Google Maps element. The provided Google API key is invalid or this site is not authorized to use it. Error Code: InvalidKeyOrUnauthorizedURLMapError'
Chrome 45.0.2454 (Mac OS X 10.10.5): Executed 9 of 9 SUCCESS (0 secs / 0.396 secs)
Chrome 45.0.2454 (Mac OS X 10.10.5): Executed 9 of 9 DISCONNECTED (12.304 secs / 0.396 secs)
Warning: Task "karma:store" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by rocket13531** [comment]
Same issue for me as well. 

`PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 12 of 13 (skipped 1) SUCCESS (0.003 secs / 0.518 secs)
PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 12 of 13 (skipped 1) SUCCESS (0.003 secs / 0.586 secs)
Chrome 51.0.2704 (Mac OS X 10.9.5): Executed 12 of 13 (skipped 1) SUCCESS (1.007 secs / 0.932 secs)
TOTAL: 36 SUCCESS`

**Comment by rwslinkman** [comment]
I'm having the same problem

```
INFO [karma]: Karma v1.1.2 server started at http://localhost:9876/
INFO [launcher]: Launching browser Chrome with concurrency 1
INFO [launcher]: Starting browser Chrome
INFO [Chrome 51.0.2704 (Mac OS X 10.11.5)]:  Connected on socket /#d1yxC0yC6OgxMFmBAAAA with id 36508617
Chrome 51.0.2704 (Mac OS X 10.11.5): Executed 0 of 2 SUCCESS (0 secs / 0 secs)
Chrome 51.0.2704 (Mac OS X 10.11.5): Executed 1 of 2 SUCCESS (0 secs / 0.002 secs)
Chrome 51.0.2704 (Mac OS X 10.11.5): Executed 2 of 2 SUCCESS (0 secs / 0.003 secs)
Chrome 51.0.2704 (Mac OS X 10.11.5): Executed 2 of 2 SUCCESS (0.045 secs / 0.003 secs)
```

**Comment by smcauliffe** [comment]
Anyone know why this happens?

**Comment by pebanfield** [comment]
I just noticed that my configuration is running tests in all configured browsers. So while I just have one test in my suite, I still see TOTAL: 2 SUCCESS. Looking more closely, I can see that the single test is running in both Chrome and PhantomJS. Could this be this issue?

**Comment by lbouriez** [comment]
Having the same issue, any idea ?
