### ISSUE TITLE
Allow proxying root without urlRoot

### ISSUE THREAD

**Issue by vojtajina** [karma-runner/karma#399]
After discussion about https://github.com/testacular/testacular/commit/8b4fd64df6b7d07b5479e43dcd8cd2aa5e1efc9c

Basically during the test run, the proxy has preference over testacular handler.

So hitting http://localhost:9876/ during test run is proxied, but hitting the same url outside a test run means capturing the browser (testacular handler).

**Comment by Dignifiedquire** [comment]
I think this is mostly solved in the latest canary so closing this
