### ISSUE TITLE
"Delaying execution, these browsers are not ready" Error

### ISSUE THREAD

**Issue by mpaulucci** [karma-runner/karma#411]
Hi, I've been having this issue for a couple of weeks now, and its driving me nuts. 

I have my setup configured to retest on every save, but now after a couple of changes in the code and saving, after 3 or 4 saves the tests don't run anymore and I get this message:

```
INFO [testacular]: Delaying execution, these browsers are not ready: PhantomJS 1.8 (Linux)
```

changing browser

```
INFO [testacular]: Delaying execution, these browsers are not ready: Chrome 25.0 (Linux)
```

As you can see, it happens when using Chrome as well as PhantomJS

Restarting Karma fixes the problem, but after a couple of saves I'm in the same situation.

Additional info: I'm on linux and using coffeescript.

**Comment by keithharvey** [comment]
Set up a project using coffeescript and encountered this issue.

Switching my spec to use -> instead of => fixed the issue

**Comment by dachibro** [comment]
Hmmm also running into this problem with unit tests written in TypeScript.  

Versions:

karma: 0.13.22
PhantomJS: 2.1.1
npm: 3.3.6
node: 5.0.0
