### ISSUE TITLE
Include css files in browser

### ISSUE THREAD

**Issue by alindsay55661** [karma-runner/karma#431]
Some of my tests require css libraries to be included such as Bootstrap. Currently I don't see a way of doing this. It would be nice if Karma would allow for specifying css files in a fashion similar to javascript files.

**Comment by bupy7** [comment]
Don't work in my case. Version of Karma: 1.6.0. Additional I'm using `grunt-karma` package. I added path to a css file, but it don't work.

Config: https://github.com/bupy7/js-cropbox/blob/master/Gruntfile.js#L41
My solution of the problem: https://github.com/bupy7/js-cropbox/blob/master/tests/fixtures/body.html#L2

What do I do wrong? May be `grunt-karma` have a bug?
