### ISSUE TITLE
Allow setting of browser dimensions

### ISSUE THREAD

**Issue by alindsay55661** [karma-runner/karma#438]
For some basic visual tests it would be nice to be able to specify a browser window size. This would allow for checking dimensions of various elements, viewport, etc.

**Comment by idmontie** [comment]
@myoung8  Thanks for mentioning karma-phantomjs-launcher! I was hoping karma would have exposed this functionality, but it makes sense to not have karma tie in too much with PhantomJS.

**Comment by silvestreh** [comment]
@myoung8 I'm not able to resize the viewport using that config. It seems to be ignored.

**Comment by esr360** [comment]
Config didn't work for me either, I'm still having issues with media-query dependent code due to being unable to alter the browser resolution.

**Comment by squidfunk** [comment]
For anyone who is coming here from Google and has this problem: I wrote a simple karma plugin called [karma-viewport](github.com/squidfunk/karma-viewport) which enables testing of responsive features at ease, as long as karma runs inside an iframe (default).

**Comment by a11smiles** [comment]
guys,  I figured out a solution... I'm running Karma + Jasmine + TypeScript against an Angular app...

consider the following directive (custom html attribute for those of you unfamiliar with Angular):
```typescript
import { Directive, ElementRef } from '@angular/core';

@Directive({
  selector: '[fullHeight]',
})
export class FullHeightDirective {
  constructor(el: ElementRef) {
    this.resize(el);

    window.onresize = () => this.resize(el);
  }

  private resize (el: ElementRef): void {
    el.nativeElement.style['min-height'] = `${window.innerHeight}px`;
  }
}
```

notice the `window.innerHeight` property is setting the style of the current element

Now, for my test fixture:
```typescript
    it('should set "min-height" style of element', () => {
        // Call 'dispatchEvent' so the window tracks the initial resize
        window.dispatchEvent(new Event('resize'));

        // I cannot set the `innerHeight`, but I can overwrite it with a new property
        (<any>window).innerHeight = 1024;
        window.dispatchEvent(new Event('resize'));   /* Then call the resize event again */
        expect(divEl.nativeElement.style['min-height']).toBe('1024px');

        // Then, set the innerHeight once more
        (<any>window).innerHeight = 700;
        window.dispatchEvent(new Event('resize'));
        expect(divEl.nativeElement.style['min-height']).toBe('700px');
    });
```
