### ISSUE TITLE
Replace log4js with winston

### ISSUE THREAD

**Issue by vojtajina** [karma-runner/karma#458]
log4js already caused me enough pain, eg. whole yesterday and now I just realized that the hacky install does fail when installing karma with sudo. I'm tired of this.

- many issues, as there is no version compatible with both 0.8 and 0.10
- global state

**Comment by Dignifiedquire** [comment]
For now log4js is working okay and there more important things to do.

**Comment by ciekawy** [comment]
I know this might be not a good enough reason but anyway just for reference - having winston in karma would help on integration here:
http://stackoverflow.com/questions/35597719/log4js-and-winston-loggers-conflicting-when-trying-to-run-karma-from-ionic-cli

**Comment by xelifret0** [comment]
I also would like winston instead of log4js, things change over time!

**Comment by xelifret0** [comment]
warning karma > log4js > nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/

**Comment by jpickwell** [comment]
There's a PR for log4js to update Nodemailer (https://github.com/log4js-node/log4js-node/pull/641). But, they're going to wait until v3.0.0 to do it.

I also think that log4js should be replaced with Winston.

**Comment by johnjbarton** [comment]
Is it possible to implement the function of karma-runner's `lib/logger.js` with Winston? If yes then this change should not be too difficult; a Pull Request could be welcomed.
