### ISSUE TITLE
Mismatched anonymous define() module

### ISSUE THREAD

**Issue by zvictor** [karma-runner/karma#466]
I am trying to start using karma with mocha, but I am confused.
All I want is to put my source files in one folder, and the mocha tests in another, then run my tests with karma without that mess of Html files and SpecRunners.
I read some posts and instruction but I do not know how to make it working, so I created the most simple example and [pushed into github](https://github.com/zvictor/karma-mocha-bootstrap).
It is using the [requirejs workaround](http://karma-runner.github.com/0.8/plus/RequireJS.html) (Is that necessary?).

So, after cloning my [example code](https://github.com/zvictor/karma-mocha-bootstrap), please run

``` bash
$ karma start
```

It will give you an error like that (here with log-level debug activated):

``` bash
$ karma start --log-level debug
DEBUG [reporter]: Using reporter "progress".
INFO [karma]: Karma server started at http://localhost:9876/
INFO [launcher]: Starting browser Chrome
DEBUG [launcher]: Creating temp dir at /tmp/testacular-73403888
DEBUG [launcher]: google-chrome --user-data-dir=/tmp/testacular-73403888 --no-default-browser-check --no-first-run --disable-default-apps --start-maximized http://localhost:9876/?id=73403888
DEBUG [watcher]: Resolved files:
    /usr/local/lib/node_modules/karma/adapter/lib/mocha.js
    /usr/local/lib/node_modules/karma/adapter/mocha.js
    /usr/local/lib/node_modules/karma/adapter/lib/require.js
    /usr/local/lib/node_modules/karma/adapter/require.js
    /home/zvictor/development/karma-mocha-bootstrap/src/source.js
    /home/zvictor/development/karma-mocha-bootstrap/test/test-main.js
    /home/zvictor/development/karma-mocha-bootstrap/test/tests.js
DEBUG [watcher]: Watching "/usr/local/lib/node_modules/karma/adapter/lib/mocha.js"
DEBUG [watcher]: Watching "/usr/local/lib/node_modules/karma/adapter/mocha.js"
DEBUG [watcher]: Watching "/usr/local/lib/node_modules/karma/adapter/lib/require.js"
DEBUG [watcher]: Watching "/usr/local/lib/node_modules/karma/adapter/require.js"
DEBUG [watcher]: Watching "/home/zvictor/development/karma-mocha-bootstrap/src"
DEBUG [watcher]: Watching "/home/zvictor/development/karma-mocha-bootstrap/test"
DEBUG [watcher]: Add file "/usr/local/lib/node_modules/karma/adapter/mocha.js" ignored. Already in the list.
DEBUG [watcher]: Add file "/usr/local/lib/node_modules/karma/adapter/require.js" ignored. Already in the list.
DEBUG [watcher]: Add file "/usr/local/lib/node_modules/karma/adapter/lib/mocha.js" ignored. Already in the list.
DEBUG [watcher]: Add file "/usr/local/lib/node_modules/karma/adapter/lib/require.js" ignored. Already in the list.
DEBUG [watcher]: Add file "/home/zvictor/development/karma-mocha-bootstrap/test/tests.js" ignored. Already in the list.
DEBUG [watcher]: Add file "/home/zvictor/development/karma-mocha-bootstrap/test/test-main.js" ignored. Already in the list.
DEBUG [watcher]: Add file "/home/zvictor/development/karma-mocha-bootstrap/src/source.js" ignored. Already in the list.
DEBUG [web server]: serving: /usr/local/lib/node_modules/karma/static/client.html
DEBUG [web server]: serving: /usr/local/lib/node_modules/karma/static/testacular.js
DEBUG [karma]: New browser has connected on socket p8ITz4W6sJK_AFVj0om6
INFO [Chrome 25.0 (Linux)]: Connected on socket id p8ITz4W6sJK_AFVj0om6
DEBUG [karma]: All browsers are ready, executing
DEBUG [web server]: serving: /usr/local/lib/node_modules/karma/static/context.html
DEBUG [web server]: serving: /usr/local/lib/node_modules/karma/adapter/lib/mocha.js
DEBUG [web server]: serving: /home/zvictor/development/karma-mocha-bootstrap/src/source.js
DEBUG [web server]: serving: /usr/local/lib/node_modules/karma/adapter/require.js
DEBUG [web server]: serving: /usr/local/lib/node_modules/karma/adapter/lib/require.js
DEBUG [web server]: serving: /usr/local/lib/node_modules/karma/adapter/mocha.js
Chrome 25.0 (Linux) ERROR
    Uncaught Error: Mismatched anonymous define() module: function (arg1) {
      return arg1;
    }
    http://requirejs.org/docs/errors.html#mismatch
    at http://localhost:9876/adapter/lib/require.js?1365027060000:1746
Chrome 25.0 (Linux): Executed 0 of 0 ERROR (0.121 secs / 0 secs)
```

Any way I define my source module, this error happens. As I am also new with RequireJS, maybe I am making any mistake there.

I appreciate any atention to this issue and improvement suggestions to the [bootstrap](https://github.com/zvictor/karma-mocha-bootstrap)

**Comment by jbarros35** [comment]
Hi,
your sample is interesting but real world projects like mine doesn't have only 2 or 3 dependencies. By the way I'm stuck on try run a project like this:

 files: [
      'bower_components/jquery/dist/jquery.js',
      'bower_components/crypto-js/sha256.js',
      'bower_components/bootstrap/dist/css/bootstrap.min.css',
      'bower_components/angular-mass-autocomplete/massautocomplete.theme.css',
      'bower_components/ngDialog/css/ngDialog.css',
      'bower_components/ngDialog/css/ngDialog-theme-default.css',
      'bower_components/angular/angular.js',
      'bower_components/angular-route/angular-route.js',
      'bower_components/angular-resource/angular-resource.js',
      'bower_components/angular-mocks/angular-mocks.js',
      'bower_components/angular-sanitize/angular-sanitize.js',
      'bower_components/angular-touch/angular-touch.js',
      'bower_components/angular-loader/angular-loader.js',
      'bower_components/angular-bootstrap/ui-bootstrap-tpls.js',
      'bower_components/requirejs/require.js',
      //'bower_components/requirejs-text/text.js',
      'bower_components/ngstorage/ngStorage.js',
      'bower_components/angular-mass-autocomplete/massautocomplete.js',
      'bower_components/bootstrap/dist/js/bootstrap.js',
      'bower_components/ngDialog/js/ngDialog.js',
      'bower_components/ngInfiniteScroll/build/ng-infinite-scroll.js',
      'require-config.js',
      'test/test-main.js',
      'login/login.js',
      'layout/menu.js',
      'home/home.js',
      'profile/signup.js',
      'layout/utils.js',
      'app.js',
      'test/*.js',
    ],

It always fails at ngDialog and I don't know why... can you provide me more information why karma cannot use those dependencies? my application is working fine but I cant test my controllers and my modules without injecting those referencies.

Uncaught Error: Mismatched anonymous define() module: function (angular) {

**Comment by shershen08** [comment]
this answer helped me a to solve this problem: http://stackoverflow.com/a/23754804/405623

```
//in tests - first include your app files
define(['angular-mocks', 'jquery', 'app/app'], function(angularmocks, $, app){

//in karma.conf - set included: false
files: [
    {pattern: 'vendor/angular/1.2.1/angular.js', included: false},
```
