### ISSUE TITLE
WARN [launcher]: Launcher "Script" is not registered! karma@canary (v0.9.1)

### ISSUE THREAD

**Issue by mgcrea** [karma-runner/karma#471]
What is the proper way to make browser scripts work again with karma@canary?

Tried to add `karma-script-launcher` as a plugin, but it looks like the module does not exists yet.

Thanks.

**Comment by helzgate** [comment]
Karma was actually using karma-chrome-launcher for me. I had to look this module up on Github and the docs showed how to add "Chrome_without_security" in the Karma.conf.js file which fixed it for me.
