### ISSUE TITLE
karma won't launch any browser ENOENT

### ISSUE THREAD

**Issue by orestes** [karma-runner/karma#479]
I'm runnning
- Windows 7 x64
- node.js 0.10.3
- karma 0.8.4

I've set all my *_BIN ENV variables,
`echo %CHROME_BIN%
"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"``

I've checked the paths are correct and I can launch the browsers by launching %CHROME_BIN% myself.

However, karma wont launch any browser.

`ERROR [karma]: { [Error: spawn ENOENT] code: 'ENOENT', errno: 'ENOENT', syscall:
 'spawn' }
Error: spawn ENOENT
    at errnoException (child_process.js:977:11)
    at Process.ChildProcess._handle.onexit (child_process.js:768:34)`

It happens with every browser. I've been checking the other issues but it seemed that they all were fixed by setting the ENV variables, but not in my case.

I've also tried launching karma from a cmd shell with administrative rights (just in case) but had no luck either.

**Comment by harshadbankar** [comment]
I resolved this issue by simply running **'npm rebuild**'
I got same issue when I have updated my npm, but after rebuild it worked fine.
Hope this will help someone!

**Comment by enmanuelduran** [comment]
@harshadbankar worked for me, thanks.
