### ISSUE TITLE
Fixtures not loaded through 'jasmine-jquery'

### ISSUE THREAD

**Issue by sebarmeli** [karma-runner/karma#481]
I'm trying to integrate Karma in a Backbone.js app. I'm using Jamine as Testing framework and jasmine-jquery as an extension. I've got a few fixtures (html and json) into the spec/javascript/fixtures folder and part of my karma.conf file looks like this:

``` js
// list of files / patterns to load in the browser
files = [
  JASMINE,
  JASMINE_ADAPTER,
  'public/javascripts/vendor/jquery.js',
  'public/javascripts/vendor/underscore-1.4.3.js',
  'public/javascripts/vendor/json2.js',
  'public/javascripts/vendor/backbone-0.9.2.js',
  'public/javascripts/**/*.js',
  'spec/javascripts/spec-helper.js',
  'spec/javascripts/support/jasmine-jquery-1.2.0.js',
  'spec/javascripts/support/jasmine-underscore.js',
  'spec/javascripts/support/sinon-1.1.1.js',
  'spec/javascripts/**/*.js',
  {
    pattern: 'spec/javascripts/fixtures/**/*.html',
    watched: true,
    included: false,
    served: true
  },
  {
    pattern: 'spec/javascripts/fixtures/*.json',
    watched: true,
    included: false,
    served: true
  }
];
```

In my spec-helper.js, I try to load the fixture with

``` js
'readFixtures("reference-data.json")'
```

and I start karma 

``` bash
karma start
```

I get that the fixture is not loaded and if I debug in the browser opened by Karma I get a 404 for the `/spec/javascripts/fixtures/reference-data.json` resource.

Missing anything?

**Comment by insetCoad** [comment]
plz , can anyone post the karma.conf.js file
@robdodson 
@sebarmeli
