### ISSUE TITLE
Small Question, Can I run specific test file when using karma?

### ISSUE THREAD

**Issue by msk86** [karma-runner/karma#553]
You know I have lots of test cases, when code on only one file, I dont want karma to run all the test for me, that will take a lot of time. So, I can specify the test case I want to run under command line? thanks!

**Comment by devi432** [comment]
hii am new to angular js...anyone help me how to write testcases in angular js using karma-jasmine

**Comment by bobber205** [comment]
@devi432 my sides are in orbit

**Comment by shelbeniskb** [comment]
any update？I want to run a specific file test.

**Comment by dbkaplun** [comment]
FYI for Jasmine you can use `fdescribe` and `fit`.

**Comment by bastianwegge** [comment]
+1 @dbkaplun

**Comment by martynchamberlin** [comment]
For the record, I'm absolutely glad that this question was asked in public and not in a mailing list. None of us would have this information if it were otherwise.

**Comment by bochove** [comment]
can the comment of  psyked commented on 21 May 2013  be updated to mention the f instead of d?

**Comment by w3chtml** [comment]
@bochove Should be useful
http://thejsguy.com/2016/01/03/controlling-which-tests-run-in-jasmine.html

**Comment by g-patel** [comment]
@vojtajina, following does not work for me, it runs all suite and tests still.
```
karma start

# and then, everytime you wanna run some tests
karma run -- --grep=filteredtestexpr
```

Why the `--grep` option not mentioned in the karma docs?
```
gpatel$ ./node_modules/.bin/karma run --help
Karma - Spectacular Test Runner for JavaScript.

RUN - Run the tests (requires running server).

Usage:
  ../../.nvm/versions/node/v4.3.0/bin/node ./node_modules/.bin/karma run [<configFile>] [<options>] [ -- <clientArgs>]

Options:
  --port                         <integer> Port where the server is listening.            
  --no-refresh                   Do not re-glob all the patterns.                         
  --fail-on-empty-test-suite     Fail on empty test suite.                                
  --no-fail-on-empty-test-suite  Do not fail on empty test suite.                         
  --help                         Print usage.                                             
  --log-level                    <disable | error | warn | info | debug> Level of logging.
  --colors                       Use colors when reporting and printing logs.             
  --no-colors                    Do not use colors when reporting or printing logs.       

gpatel$
```

**Comment by g-patel** [comment]
I don't like the `describe.only` (mocha) and `ddescribe` (jasmine) solutions as those are error prone. You might forget to revert the `.only` part before committing and your jenkins/builds would still be in joy thinking the test suites are passing.. ;)

**Comment by Hubro** [comment]
Is there seriously no way to run focused tests while working on a single file without *modifying* the file in question? That seems super stupid.

**Comment by hamxabaig** [comment]
Exactly, +1 for this as sometimes you just push your code with focused tests.

**Comment by MarkoCen** [comment]
Currently, I use command line arguments to define which set of tests I need to run. For example, I want to run those tests under `src/controllers` folder, and the start command is something like:
```bash
karma start src/controllers
``` 
And in `karma.config.js`, I select files based on the argument passed:
```javascript
let path = process.argv[process.argv.length-1];

//only load files under the path
let files = `${path}/**/*.js`;

module.exports = function(config){
    config.set({
       // ...
       files
    })
}

```

**Comment by alexluecke** [comment]
@hamxabaig While I still want to see support for testing a single file, your problem can be avoided with git hooks.

**Comment by ORESoftware** [comment]
What the heck do `fdescribe` and `fit`, stand for? lol

**Comment by psyked** [comment]
@ORESoftware Apparently it's 'focused': 

> Focusing specs will make it so that they are the only specs that run.
> Any spec declared with `fit` is focused.
> You can focus on a `describe` with `fdescribe`

https://jasmine.github.io/2.1/focused_specs.html

**Comment by bobbyg603** [comment]
@MarkoCen thank you so much! we were trying to add an npm script for running a suite of acceptance tests separate from our suite of unit tests. having a script per suite is much nicer than endlessly swapping describes for fdescribes and vice versa.

**Comment by reiinakano** [comment]
@alexluecke What kind of script would I put in the git hook? Could you give an example?

**Comment by alexluecke** [comment]
@reiinakano 

You could put something like the following in the `pre-commit` hook:

```
#!/usr/bin/env bash

focused_test_files=()

for file in $(git --no-pager diff --name-only --staged); do

  # Search only through staged changes since user might be commit only partial changes of a file that has focused tests.
  # Make sure only the staged changes do not contain a focused test:
  result=$(git --no-pager diff --cached $file \
    | egrep -v "^(\+)\1{1}" \
    | grep "\(fdescribe\|fit\)"
  )

  [ -n "$result" ] && focused_test_files+=("$file")
done

if [ -n "$focused_test_files" ]; then
  echo "Following files have focused_test_files tests:"
  for f in "${focused_test_files[@]}"; do echo -e "  $f"; done
  exit 1
fi
```

I haven't vetted this too much, but it shouldn't have too many issues.

**Comment by ORESoftware** [comment]
@devi432 lol

**Comment by muzir** [comment]
With grunt you can run package test like below : 

`grunt karma:packageName`

**Comment by kedar9444** [comment]
define the file name in the test.ts file
const context = require.context('./', true, /my-component.spec.ts\.spec\.ts$/);

**Comment by neerajjain92** [comment]
@kedar9444 Thanks this is what I was searching for ...... Works beautifully 👍

**Comment by jalmansa88** [comment]
@kedar9444 should be 
`const context = require.context('./', true, /my-component\.spec\.ts$/);`

because `.spec.ts` is already there.

**Comment by colbymelvin** [comment]
FWIW, if you want to run a specific test or tests, you can do something like this:

(in your config)
```
module.exports = function(config) {
    config.glob = config.glob ? config.glob : 'path/to/my/spec/files/*.js';

    return config.set({
        
        ...

        files: [

            ...

            config.glob,

            ...

        ],

        ...

    });
};
```

To run every spec file starting with 'c':
```
 karma start my/karma.conf.js --glob=path/to/my/spec/files/**/c*.js
```

To run a specific file:
```
 karma start my/karma.conf.js --glob=path/to/my/spec/files/some_spec.js
```
