### ISSUE TITLE
Serving sources from different folders

### ISSUE THREAD

**Issue by phtrivier** [karma-runner/karma#561]
I'm running into a bit of an issue. I would like karma to run in a project, serving and watching files from several projects (different folders that are "sibblings" of my main project.)

For example, if I have

```
projectA
- src
-- js
--- fileA.js

projectB
- src
-- js
--- fileB.js
- karma.conf.js
```

I want the karma server to serve both "base/fileB.js" and "base/fileA.js" ; since I'm using requirejs in my tests, this is all I need to effectively "share" the files. 

For the moment, I have a custom "watcher" file that basically copies everything for projectA/src and projectB/src into a temp folder, where my karma tests are run. This works but feels a bit tricky...

Is there a way to do achieve this ?

**Comment by deeperton** [comment]
I have one BIG project

```
- <A> folder with components for SDK implemented in <APP>
-- < js files in subfolders which I need in main app >
- <B> folder with APP
---frontend
----resources
----- APP runtime js-code
----- karma.conf.js
```

During build process grunt task copying all components from `A`-folder into `APP/js/components` subfolder.
For running APP which wasn't built in browser, my nginx have alias for `'js/components` to that external <A> folder.

I want to be able to run tests with `karma start` for APP which wasn't built. 

Is there any possibility to configure `karma` use something like nginx alias?

**Comment by deeperton** [comment]
Probably the answer is -- use nginx by `proxies`

```
proxies = {
                '/base/js/components/': {
                    'target': 'http://app.local:80/dev/js/components/',
                    'changeOrigin': true
                }
            }
```

Setting port is mandatory because otherwise, karma proxy will use own local port, of course without any luck.

In this case I got many errors in console about no timestamp, but I don't have any other solution for now.

Is it possible to write karma plugin to resolve such issue without using fs symlinks or forcing copying files? Just an alias for folder.
