### ISSUE TITLE
Reporter with all specs

### ISSUE THREAD

**Issue by cbier** [karma-runner/karma#564]
I would like to see each spec in my Jasmine test and its status **in the console** when I run a test using Karma. As of now, all I get in the console is a total of executions and any errors that come out.

> Chrome 26.0 (Windows): Executed 3 of 3 SUCCESS (1.153 secs / 0.131 secs)

I need to see something like this:

> [description of spec1] [success/fail]
> [description of spec2] [success/fail]

I read the docs but I am unable to find a way to achieve this. Is there something i'm missing? If not, may I please put in an enhancement request?

Here is someone else asking the same question, on StackOverflow:
http://stackoverflow.com/questions/16684582/generate-jasmine-report-using-karma-runner

The answer gives some ways to work it out, but the second option he proposes would be the only option for this case. An option which I am not currently able to handle on my own.

**Comment by Dignifiedquire** [comment]
Closing in favor of https://github.com/karma-runner/karma-runner.github.com/issues/30
