### ISSUE TITLE
https support for karma server

### ISSUE THREAD

**Issue by kpe** [karma-runner/karma#581]
It would be nice, if a browser could connect to the karma server through https. This would come handy, if your unit test are using the GetUserMedia API. At least in Chrome one could skip/remember the security prompt/warning, if https is used. Without https you have to manually accept/click the security warning.

So is there any way to make karma serve https instead of http?

**Comment by subhash85** [comment]
+1

**Comment by Dignifiedquire** [comment]
Fixed in the latest canary.
