### ISSUE TITLE
Use source maps for stacktraces

### ISSUE THREAD

**Issue by pluma** [karma-runner/karma#594]
Currently the stacktraces returned by karma are pretty much useless if any source code transformation or bundling is taking place. This impacts workflows using bundlers (e.g. browserify, component) and transpilers (e.g. CoffeeScript, LiveScript, TypeScript, Dart) alike.

As karma seems to be able to print stacktraces from the browser to the console, it should be possible to run a function on them in between.

Mozilla provides a library at [mozilla/source-map](https://github.com/mozilla/source-map) for parsing sourcemaps and translating generated source positions to original source positions and filenames.

From what I can see this would require the following steps:
1. When a source file is loaded, try to find source map comments.
2. Parse any inlined source maps (needs to support base64-encoded data URLs)
3. When a browser returns a stacktrace, try to find any file/line/col references.
4. Translate per-file line/col references via mozilla/source-map.

This should probably be optional because of the overhead involved in finding, parsing and applying the source maps.

**Comment by tschaub** [comment]
For others looking to have improved stack traces with inline source maps, see if the [`karma-source-map-support` plugin](https://www.npmjs.com/package/karma-source-map-support) helps (also referenced here https://github.com/karma-runner/karma/issues/893#issuecomment-68567853).
