### ISSUE TITLE
Reload config file when it changes

### ISSUE THREAD

**Issue by jamesshore** [karma-runner/karma#595]
When the karma.conf.js file changes, reload it. Currently, changes to the config file aren't reflected in later test runs until you manually restart Karma, which can be very confusing.

If reloading the config file is difficult, a graceful exit with an error message is also fine.

This was reproduced in Karma 0.8.5. Apologies if this has been resolved since then; a quick search of the issue list didn't reveal anything.

**Comment by brianmhunt** [comment]
I would just like to add that some folks (including myself) pass the karma config as a parameter to the `start` function e.g.


```javascript
gulp.task('karma', function (done) {
    karmaServer.start(config.karma, done);
});
```

Where `config` is either stored as part of a bigger set of parameters, or generated/modified by the test runner. In any case, it would be most handy in this scenario to have a manual system for restarting.

I trust that a manual restart is subsumed by this issue, but I am happy to open another.

(p.s. :heart: karma)

**Comment by Dignifiedquire** [comment]
I'm not a 100% sure this is such a great idea, so I'm closing this issue. Feel free to discuss here and I might reopen it.

**Comment by deeperx** [comment]
@dignifiedquire I think it's a good feature. Because, we don't have to use gulp or grunt type build systems; at least npm might be sufficient. 

Especially, when configuring something or when building a new project, this would become handy, I lived that. Currently, I wrote a bash script to do that, but native support would be good.

**Comment by deeperx** [comment]
How can we add this to karma?

**Comment by ezk84** [comment]
With `grunt-contrib-watch` I am able to watch the config file, the problem now is simply restarting the Karma server with the new configuration. 
Running the `karma:unit:start` task again does not seem to reset the server. Maybe a `:restart` task could be used which will kill the old server and start a new one with the updated config?

**Comment by mlewand** [comment]
I was surprised to see that after adding `'karma.conf.js'` to watched `files` in Karma config it does not reload itself. It's not a crucial feature, but it would be a nice addition, especially helpful at the beginning of Karma integration to the project.
