### ISSUE TITLE
Chrome have not captured in 5000 ms

### ISSUE THREAD

**Issue by lc3t35** [karma-runner/karma#635]
MacOS X 10.8.4, node v0.10.12, karma 0.9.4, Chrome 28.0.1500.71

In order to investigate on the problem submitted here (https://github.com/xolvio/real-time-development-with-meteor/issues/17) , i've installed the karma source and run the tests.

<pre>
imac-de-laurent:karma laurent$ git checkout v0.9.4
Previous HEAD position was 8606695... chore: release v0.8.6
HEAD is now at 5fe6a57... chore: release v0.9.4
imac-de-laurent:karma laurent$ grunt
Running "build:client" (build) task
>> Created static/karma.js
Running "test:unit" (test) task
Running "simplemocha:unit" (simplemocha) task
  239 tests complete (3 seconds)
Running "test:tasks" (test) task
Running "simplemocha:tasks" (simplemocha) task
  12 tests complete (6 ms)

Running "test:client" (test) task
Running /Users/laurent/dev/karma/bin/karma start test/client/karma.conf.js --single-run --no-auto-watch --reporters=dots --browsers=Chrome
INFO [karma]: Karma v0.9.4 server started at http://localhost:9876/
INFO [launcher]: Starting browser Chrome
WARN [launcher]: Chrome have not captured in 5000 ms, killing.
INFO [launcher]: Trying to start Chrome again.
WARN [launcher]: Chrome have not captured in 5000 ms, killing.
INFO [launcher]: Trying to start Chrome again.
WARN [launcher]: Chrome have not captured in 5000 ms, killing.
[Error]
Fatal error: Client unit tests failed.
</pre>

Chrome is launched ,but it says he cannot open http://localhost:9876/?id=15999490.

if i open the page with another browser (Firefox), the page opens -> it's related to Chrome ....

**Comment by mnmeyers** [comment]
thank you @lc3t35 your solution helped me out!! 👏  🙏
