### ISSUE TITLE
PhantomJS: Reset localStorage after test run

### ISSUE THREAD

**Issue by trkoch** [karma-runner/karma#654]
By default PhantomJS keeps `localStorage` settings across sessions. While this is equivalent to a real browser, it can be problematic in a test setup. If a test leaves traces in the `localStorage` (say, a user is logged in) seemingly random failures can happen (false negatives and positives).

From my observations I guess Chrome and other real browsers are reset across test runs (i.e. they get a new preference directory). I suggest to treat Phantom similarly.

On Mac OS, Phantom writes its localStorage settings by default to `/Users/<User>/Library/Application Support/Ofi Labs/PhantomJS`. This can be changed with the `--local-storage-path` flag.

**Comment by guioconnor** [comment]
@trkoch Wouldn't it be advisable to call ```localStorage.clear()``` in ```beforeEach``` instead? It makes sense for a test not to assume anything about the previous session.

**Comment by ciekawy** [comment]
as for `localStorage.clear()` in `beforeEach` what to do in case of karma/node crash on CI environment?
