### ISSUE TITLE
feat: pass command line arguments for `start` command

### ISSUE THREAD

**Issue by timbertson** [karma-runner/karma#672]
Following on from #530 

We now have:

```
$ karma start &
$ karma run -- --grep someTest
```

But that sucks for batch runs (like CI scripts), because you need to:
- run `karma start`
- parse its output (!) to see when it's ready
- run `karma run -- <args>`
- kill the first process
- deal with other messy stuff related to managing multiple processes

There is real need for this feature, e.g segmenting travis builds by test type:
- `karma start --single-run -- --tag unit`
- `karma start --single-run -- --tag integration`

Options:
- treat everything after `--` as clientArgs, just like we do for `run`.
  @vojtajina doesn't like this, because it removes the possibility of using this for something else in the future.
- an explicit `--client-args` would trigger that _ALL_ following arguments should be taken as clientArgs:
    `karma start --single-run --client-args --grep unit`
    This should probably grab only up to the next "--" argument though.
- more tediously, specifying them individually:
    `karma start --single-run --client-arg=--grep --client-arg=unit`

Other suggestions?

**Comment by danielsiwiec** [comment]
@gaelazzo A bit late to the party, but since [this](https://github.com/karma-runner/karma/issues/1561) there's a much simpler solution now:

```
karma start --grep integration
```

karma.conf.js:
```javascript
module.exports = function (config) {
  config.set({
    ...,
    client: {
      args: ['--grep', config.grep]
    }
  })
}
```

**Comment by gaelazzo** [comment]
Many thanks.

**Comment by rochapablo** [comment]
@danielsiwiec, still getting `Executed 1 of 12`.

```
./node_modules/.bin/karma start --grep test/user.spec.ts

./node_modules/.bin/karma start --grep UserService

./node_modules/.bin/karma start -- --grep="UserService"
```

None of those codes above seems to make any diference.

Is it really possible run a single test?
