### ISSUE TITLE
Web Server Fails to Serve karma.js

### ISSUE THREAD

**Issue by mccalltd** [karma-runner/karma#691]
Everything was working fine yesterday. Today I tried to npm link a fork of the project, and since then I get the following HTTP error every time a browser connects:

```
WARN [web-server]: 404: /path/to/project/node_modules/karma/static/karma.js
```

I have tried the following:
- removed symlinks added by npm link
- completely removed my project repo from local fs and re-cloned
- re-installed latest karma from npm

I don't know what happened. But what's obvious is that the web server expects to find karma.js inside /static, and there is no such file on my local fs in that location. Any tips or clues would be appreciated. I'm positive this is all my fault. :)

**Comment by Sjors** [comment]
I ran into the same error with Phantomjs2. I then added the commit from this pull request to the current master in my own fork, ran "grunt build" and the error was replaced by a warning. That and lots of other error messages, but hopefully those are specific to my project.
