### ISSUE TITLE
Routing problem with XHR-polling, returns 404

### ISSUE THREAD

**Issue by fredrikbonander** [karma-runner/karma#705]
When running older browsers (tested with Firefox 3.5, IE 8&9) sometimes it runs into 404 errors when trying to establish connection with socket.io client. Unfortunately it's seems to somewhat random error. The only way I can re-create the error every time is have IE8 or IE9 connect to karma over Local Tunnel connection with browserstasck.

The output error in Karma is simpy:

````
WARN[web-server]: 404: http://localhost:9876/socket.io/1/xhr-polling/SwHOcEkGfW1nLQc7HL2p?t=1376924853049
WARN [web-server]: 404: http://localhost:9876/socket.io/1/?t=1376924853644 
```

I don't know if it's a problem with the webserver in karma or something in the socket.io library.

**Comment by Dignifiedquire** [comment]
This should be fixed in the latest version.
