### ISSUE TITLE
Modules not loaded with karma requirejs

### ISSUE THREAD

**Issue by drano** [karma-runner/karma#707]
With Karma v0.10.1, in my karma.conf.js, I have this part:

```javascript
frameworks: ['requirejs', 'jasmine'],
files: [
      {pattern: 'components/requirejs-text/text.js', included: false},
      {pattern: 'components/jquery/jquery.js', included: false},
      {pattern: 'components/lodash/lodash.js', included: false},
      {pattern: 'components/backbone/backbone.js', included: false},
      {pattern: 'components/noty/js/noty/jquery.noty.js', included: false},
      {pattern: 'gensrc/**/*.js', included: false},
      {pattern: 'gentests/*.js', included: false},

      'config/test-config.js'
]
```

And, in my test-config.js (in fact .coffee), I have

```coffeescript
tests = []
for file of window.__karma__.files when /Spec\.js$/.test(file)
  tests.push file

require.config 
  baseUrl: '/base',

  paths:
      jquery: "components/jquery/jquery"
      underscore: "components/lodash/lodash"
      backbone: "components/backbone/backbone"
      text: "components/requirejs-text/text"

  shim:
      backbone:
          deps: ["underscore", "jquery"]
          exports: "Backbone"
      underscore:
          exports: '_'

  deps: tests
  callback: window.__karma__.start

console.log "BEFORE INIT"
require ['jquery', 'backbone'], ($, Backbone) ->
    console.log "INIT 001"
```

After karma start, I can see "BEFORE INIT", but never "INIT 001".
It looks like my callback is never called, maybe because jquery or backbone modules are not loaded.

Have you some ideas about this problem ?

**Comment by Dignifiedquire** [comment]
For questions and support please use the mailing list or Gitter. The issue tracker is for bug reports and feature discussions only.

**Comment by chovy** [comment]
I'm having same problem. Did anyone figure out a solution?

**Comment by anji22** [comment]
I'm having same problem. Did anyone figure out a solution?
This below is my typescript file.
----------------------------------
import { AppComponent } from './app.component';
import { SampleTest } from './SampleUnitTest';
import { async, ComponentFixture, TestBed } from '@angular/core/testing';
import { By } from '@angular/platform-browser';
import { DebugElement } from '@angular/core';

describe('SampleTest', ()=> {
    var test: SampleTest;
    beforeEach(() => {
        test = new SampleTest();       
    });

    it('should show the addition', () => {
        test.number1 = 5; test.number2 = 10;
        expect(test.AddClick(test.number1, test.number2)).toBe(15);
    });

    it('should show the subtraction', () => {
        test.number1 = 15; test.number2 = 10;
        expect(test.SubClick(test.number1, test.number2)).toBe(5);
    });


    it('should show the multiplication', () => {
        test.number1 = 5; test.number2 = 10;
        expect(test.MultiClick(test.number1, test.number2)).toBe(50);
    });
   
});
----------------------------------------
The below is my javascript file after complile the typescript
--------------------------------------------------------------------
"use strict";
var SampleUnitTest_1 = require('./SampleUnitTest');
describe('SampleTest', function () {
    var test;
    beforeEach(function () {
        test = new SampleUnitTest_1.SampleTest();
    });
    it('should show the addition', function () {
        test.number1 = 5;
        test.number2 = 10;
        expect(test.AddClick(test.number1, test.number2)).toBe(15);
    });
    it('should show the subtraction', function () {
        test.number1 = 15;
        test.number2 = 10;
        expect(test.SubClick(test.number1, test.number2)).toBe(5);
    });
    it('should show the multiplication', function () {
        test.number1 = 5;
        test.number2 = 10;
        expect(test.MultiClick(test.number1, test.number2)).toBe(50);
    });
});
-----------------------------------------------------------------------------------------
The below is my karma.config.js file
------------------------------------------------------------------------------------------
// Karma configuration
// Generated on Fri Dec 23 2016 12:59:58 GMT+0530 (India Standard Time)

module.exports = function(config) {
  config.set({

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '',

plugins : [
  'karma-requirejs',
  'karma-jasmine',
  'karma-chrome-launcher',  
  'karma-browserify'
],
    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['jasmine'],


    // list of files / patterns to load in the browser
    files: [
	'node_modules/requirejs/require.js',
    'node_modules/karma-requirejs/lib/adapter.js',
	'app/SampleUnitTest.spec.js'
    ],


    // list of files to exclude
    exclude: [
    ],


    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {
    },


    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: ['progress'],


    // web server port
    port: 9876,


    // enable / disable colors in the output (reporters and logs)
    colors: true,


    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_INFO,


    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: true,


    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: ['Chrome'],


    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: false,

    // Concurrency level
    // how many browser should be started simultaneous
    concurrency: Infinity	
  })
}

While running i am getting the below error

 Uncaught Error: Module name "SampleUnitTest" has not been loaded yet for context: _. Use require([])
  http://requirejs.org/docs/errors.html#notloaded
  at node_modules/requirejs/require.js:143


please any one provide solution for this!
