### ISSUE TITLE
BaseReporter.onBrowserLog doesn't honor logLevel

### ISSUE THREAD

**Issue by fredrikbonander** [karma-runner/karma#710]
Is this by design or bug?

Should one created a new reporter that looks at logLevel or mod BaseReporter?

**Comment by Dignifiedquire** [comment]
@fredrikbonander is this still an issue for you?

**Comment by kketch** [comment]
Indeed captureConsole set to false doesn't seems to prevent karma (0.12.37) to capture the console

**Comment by fredrikbonander** [comment]
@Dignifiedquire No. Tried both 0.12.32 and 0.12.37 and it captures as expected. 

```client: {captureConsole:false}``` omits all ```console.*()```
```client: {captureConsole:true}``` prints all ```console.*()```

**Comment by Dignifiedquire** [comment]
Thanks @fredrikbonander
