### ISSUE TITLE
The package karma does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by tamsler** [karma-runner/karma#716]
npm ERR! peerinvalid The package karma does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer karma-chrome-launcher@0.0.1 wants karma@~0.9
npm ERR! peerinvalid Peer karma-firefox-launcher@0.0.1 wants karma@~0.9
npm ERR! peerinvalid Peer karma-html2js-preprocessor@0.0.2 wants karma@~0.9
npm ERR! peerinvalid Peer karma-jasmine@0.0.1 wants karma@~0.9
npm ERR! peerinvalid Peer karma-requirejs@0.0.1 wants karma@~0.9
npm ERR! peerinvalid Peer karma-script-launcher@0.0.1 wants karma@~0.9
npm ERR! peerinvalid Peer karma-coffee-preprocessor@0.0.1 wants karma@~0.9
npm ERR! peerinvalid Peer karma-phantomjs-launcher@0.0.2 wants karma@~0.9

npm ERR! System Darwin 11.4.2
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/tamsler/src/edu-stream
npm ERR! node -v v0.10.16
npm ERR! npm -v 1.3.8
npm ERR! code EPEERINVALID
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/tamsler/src/edu-stream/npm-debug.log
npm ERR! not ok code 0

**Comment by michaelO93** [comment]
@maksimr  Thank you so much for your recommendation. That solved my problem I've been researching on for awhile now. I am so grateful.

**Comment by yaarams** [comment]
@maksimr thank you. npm cache clean -g worked.

**Comment by hgoebl** [comment]
Sometimes it might be good idea to update npm. Newer versions of npm are better in resolving peer dependencies.
