### ISSUE TITLE
progress reporter clobbers logs

### ISSUE THREAD

**Issue by segrey** [karma-runner/karma#724]
When running tests from https://github.com/angular/angular.js using WebStorm 7 integration, there are the following lines in "Karma Server" tab:
```
INFO [karma]: Karma v0.10.2 server started at http://localhost:9876/
INFO [launcher]: Starting browser Chrome
INFO [Chrome 28.0.1500 (Linux)]: Connected on socket 0BuEXA7DrI_qhdCkmRPz
WARN [web-server]: 404: /%7B%7BtestUrl%7D%7D
WARN [web-server]: 404: /%7B%7BdataUri%7D%7D
WARN [web-server]: 404: /foo/bar
```

Running the same tests in the console results in:
```
INFO [karma]: Karma v0.10.2 server started at http://localhost:9876/
INFO [launcher]: Starting browser Chrome
INFO [Chrome 28.0.1500 (Linux)]: Connected on socket PLMLEAGJ_TBTBbyMmvOO
Chrome 28.0.1500 (Linux): Executed 692 of 2241 SUCCESS (0 secs / 1.432 secs)
Chrome 28.0.1500 (Linux): Executed 695 of 2241 SUCCESS (0 secs / 1.438 secs)
Chrome 28.0.1500 (Linux): Executed 699 of 2241 SUCCESS (0 secs / 1.448 secs)
```

Diff: no "WARN" messages in the console.
Initially, I thought it's something wrong with WebStrom 7 integration, but it turned out that `log.warn('404: ' + path)` is executed in both cases (this line is in karma/lib/middleware/common.js).
Nevertheless `log.warn`s are called, warning messages aren't shown in the console.

**Comment by Dignifiedquire** [comment]
Closing in favor of #1411
