### ISSUE TITLE
webserver failing to serve served; !included files with querystring

### ISSUE THREAD

**Issue by davedx** [karma-runner/karma#739]
Hi there, I'm trying to setup a project with karma. The framework I'm using has its own internal 'include' mechanism that appends timestamps to source files. Here's the relevant bits of my karma conf:

```
basePath: './',

files: [
  'apps/com.libertyglobal.widget.SocialTv/Contents/metro_init.js',
  {pattern: 'lib/maf-sdk.js', included: true, served: true},
  {pattern: 'src/maf-ui.js', included: false, served: true},
  {pattern: 'apps/com.libertyglobal.widget.SocialTv/**/*.js', included: false, served: true},
],
```

The "src/maf-ui.js" file needs to be served but not included as it's included by the framework. When the framework requests the file:

```
WARN [web-server]: 404: /src/maf-ui.js?1378808042184
WARN: 'error loading maf-ui file: maf-ui.js'
```

I have tried using maf-ui.js_, maf-ui.js_\* but nothing seems to work. I've also tried hacking around in the middleware, and found the issue seems to be that src/maf-ui.js does NOT get 'base' prepended as the other files do, so the serve fails.

Am I doing something wrong here, or is this a bug? If you can point me to where to look to fix it then I'm happy to submit a PR.

Thanks!

**Comment by Madd0g** [comment]
This /base/ magic keyword needs to be in the docs. I spent so long tinkering and changing correct configuration.

It's on the page that talks about requirejs, but it should be where the files part of the config is documented. This was *seriously frustrating*. I probably went through every karma guide in google until I stumbled on an SO post that mentions this.

**Comment by iongion** [comment]
@Madd0g do you still have that SO link

**Comment by Madd0g** [comment]
@iongion - these are the two links from my history that seem related (sorry I haven't touched karma in a while so I don't really remember what all this is about)

https://groups.google.com/forum/#!topic/karma-users/Ytu-JtsZH3g

https://stackoverflow.com/questions/22959188/karmas-base-directory-location
