### ISSUE TITLE
Option to surpress console.log

### ISSUE THREAD

**Issue by binarykitchen** [karma-runner/karma#744]
When I run my e2e tests with PhantomJS over Karma I see lots of console outputs. They are good for development but I do not want to pollute my screen with them while running tests.

Can you please add an option to suppress `console.log` ?

**Comment by sedghi** [comment]
is it possible to only suppress console.warn?

**Comment by jginsburgn** [comment]
> is it possible to only suppress console.warn?

You could probably use `grep` to filter out all logs with the `warn` tag.
