### ISSUE TITLE
Simulate clicks and other events

### ISSUE THREAD

**Issue by georgiosd** [karma-runner/karma#746]
How does one test a click on a directive in a jasmine unit test?

It seems that angularjs in their own ng- directive specs use `browserTrigger` which is defined in `angular-scenario`. However including the karma scenario plugin breaks the jasmine matchers.

How to do this??

**Comment by ricardomlourenco** [comment]
Have you tried use Selenium? There is a plugin for karma I guess:
https://www.npmjs.com/package/karma-selenium-webdriver-launcher

I've never used with Karma however I used it with .net and it worked pretty good.

**Comment by StanislawVictorovich** [comment]
Have the same problem
