### ISSUE TITLE
Getting "Executed 0 of 0 ERROR" in the console

### ISSUE THREAD

**Issue by marcobarbosa** [karma-runner/karma#753]
Hi all,

I'm trying to use karma with jasmine-flight and require.js.

I have no tests in place, just want to get a normal "0 of 0 SUCESS" before getting started.

However this is ERROR is shown in my console:

```
INFO [karma]: Karma v0.10.2 server started at http://localhost:9876/
INFO [launcher]: Starting browser Chrome
INFO [Chrome 29.0.1547 (Mac OS X 10.8.5)]: Connected on socket YRMSwebi_lNtEYDnL0rk
Chrome 29.0.1547 (Mac OS X 10.8.5): Executed 0 of 0 ERROR (0.171 secs / 0 secs)
```

I have found similar issues but related to "Angular" not "Flight".

This is my karma.conf:

```
// Karma configuration
// Generated on Thu Sep 19 2013 16:31:19 GMT+0200 (CEST)

module.exports = function(config) {
  config.set({

    // base path, that will be used to resolve files and exclude
    basePath: '',

    // frameworks to use
    frameworks: ['requirejs', 'jasmine'],

    // list of files / patterns to load in the browser
    files: [
        '../bower_components/jasmine-flight/lib/jasmine-flight.js',
        '../bower_components/jasmine-jquery/lib/jasmine-jquery.js',

        {pattern: '*.js', included: false},
        {pattern: 'mixins/*.js', included: false},
        {pattern: 'data/*.js', included: false},
        {pattern: 'pages/*.js', included: false},
        {pattern: 'ui/**/*.js', included: false},
        {pattern: 'tests/spec/**/*.spec.js', included: false},

        // Entry point for karma.
        'tests/test-main.js'
    ],

    // list of files to exclude
    exclude: [
        '../bower_components/flight/lib/standalone/*.js'
    ],

    // test results reporter to use
    // possible values: 'dots', 'progress', 'junit', 'growl', 'coverage'
    reporters: ['dots'],


    // web server port
    port: 9876,

    // enable / disable colors in the output (reporters and logs)
    colors: true,


    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_INFO,


    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: true,


    // Start these browsers, currently available:
    // - Chrome
    // - ChromeCanary
    // - Firefox
    // - Opera
    // - Safari (only Mac)
    // - PhantomJS
    // - IE (only Windows)
    browsers: ['Chrome'],


    // If browser does not capture in given timeout [ms], kill it
    captureTimeout: 5000,


    // Continuous Integration mode
    // if true, it capture browsers, run tests and exit
    singleRun: false,

    // report which specs are slower than 500ms
    // CLI --report-slower-than 500
    reportSlowerThan: 500,

    plugins: [
            'karma-jasmine',
            'karma-requirejs',
            'karma-chrome-launcher',
            'karma-safari-launcher'
        ]
  });
};

```

Is this a bug or am I doing something wrong?

**Comment by andrerpena** [comment]
In case this helps anyone, I ran into this problem because my main test file has 2 `describe` but no `it`.

It was like this:

    describe('Something abstract', function() {
        describe('Something specific', function() {
        });
    });

And when I made it like this, it worked:

    describe('Something abstract', function() {
        describe('Something specific', function() {
            it('Something', function() {
                assert.equal(1, 1);
            });
        });
    });

**Comment by axelson** [comment]
For those still coming across this from searches the default behavior appears to have possibly switched so that having no tests causes an error: https://github.com/karma-runner/karma/issues/1690

**Comment by yasuda22m** [comment]
g

**Comment by yasuda22m** [comment]
Hi guys!
**Getting "Executed 0 of 0 ERROR" in the console (FIXED)**

My config file name is **_(test.conf.js)_** 

============================Code Start======================================
module.exports = function(config) {
  config.set({

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '',


    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['jasmine'],


    // list of files / patterns to load in the browser
    files: [
    '../www/lib/angular/angular.js',
    '../www/js/*.js',
    '../www/lib/angular-mocks/angular-mocks.js',
    '**/*.js'
    ],


    // list of files to exclude
    exclude: [
    ],


    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {
    },


    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: ['progress'],


    // web server port
    port: 9876,


    // enable / disable colors in the output (reporters and logs)
    colors: true,


    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_INFO,


    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: true,


    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: ['Chrome'],


    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: false,

    // Concurrency level
    // how many browser should be started simultaneous
    concurrency: Infinity
  })
}
==========================Code====END===============================
Explanation:-

 files: [
    '../www/lib/angular/angular.js',
    '../www/js/*.js',
    '../www/lib/angular-mocks/angular-mocks.js',
    '**/*.js'
    ]

In this part, I always ignore. But here was the problem 
My old code  [ 'test/**/*.js' ] and new is  [ '**/*.js' ]

My project directory

**Project22
   -js
  -css
 **-test (test folder)
      -test.conf.js**
 -templates**


I think it should work fine for you.

**Comment by dummdidumm** [comment]
I got this error while using Chrome (or ChromeHeadless) as browser + using typescript. This solution fixed it for me: https://github.com/angular/angular-cli/issues/2125#issuecomment-247395088

**Comment by pmandapuram** [comment]
Hi ,
I am written jasmine test cases to a method that get all attributes which are available in database 
is it possible to test from jasmine test suite 
and i am getting 0 specs and 0 failures when i am running the tests

![image](https://user-images.githubusercontent.com/34510275/33938786-b4427686-e02e-11e7-9833-d9861ba5f75d.png)

**Comment by johnjbarton** [comment]
1. If you are using asynchronous code (promises), verify that you return a promise chain or call done().
2. Open the DEBUG window and use devtools to examine the test.

**Comment by pmandapuram** [comment]
thanks Johnjbarton

**Comment by Drumstix42** [comment]
Anyone coming across this thread years later, as I did. I discovered there is a boolean you can set in the config object, **failOnEmptyTestSuite**
This let me setup a configuration without needing to define any test cases.

See: http://karma-runner.github.io/2.0/config/configuration-file.html

**Comment by aj-r** [comment]
Got this error when testing with typescript. The reason is because karma does not host typescript files by default. The solution was to add this to my karma config:

```
    mime: {
      "text/x-typescript": ["ts", "tsx"],
    },
```

**Comment by yogeshwar1996** [comment]
Thanks @aj-r  adding mime property to karma.conf.js helped me. Now my tests are executing

**Comment by roopkt** [comment]
In my case it was below line that I was missing bootstrap angular. 
```
const app = bootstrapModule(getMockSettings());
(angular as any).lowercase = text => text.toLowerCase();
angular.bootstrap(document, [app ]);
```

**Comment by collinkrawll** [comment]
In my case, I was actually getting "Executed 0 of N ERROR". Simple tests would show in N but would never actually be executed. I removed each of my scripts and eventually narrowed it down to a `jQuery(document).ready(...` function that was throwing an exception that was being swallowed. I guess the tests were being registered but never got to execute (and the exception was being swallowed).

**Comment by Kendsar** [comment]
In my case I was trying to run 

> ng test

 While I'am not running 

> npm start

And that's will not work and will show 0 specs, 0 failures ,of course.

**Comment by cluzier** [comment]
> I resolved the error when I remove `angular-scenario` from `vendor.js` file.
> 
> Thanks stackoverflow: http://stackoverflow.com/questions/18366837/karma-not-running-tests
> 
> @marcobarbosa is it can help you?

can anyone else confirmed this worked for them before I do it myself?
