### ISSUE TITLE
Pattern configuration error with PhamtonJs Runner

### ISSUE THREAD

**Issue by tarsisazevedo** [karma-runner/karma#761]
My pattern was configured like this
![karma conf js____projetos_globo_g1_g1_projetos_beta_novo_g1__-_vim2](https://f.cloud.github.com/assets/118348/1217859/09c30d64-26b1-11e3-822b-266c2539f541.png)

It works when I run karma with chrome, but when I change to phantomjs I got an error.
![1 _bash](https://f.cloud.github.com/assets/118348/1218011/78eca9aa-26b3-11e3-85b6-668d70705ce5.png)

So I change to explicit the shim/shan path and it works
``` javascript
    {pattern: 'common_beta/static/libs/esr5-shim/es5-shim.js', watched: false},
    {pattern: 'common_beta/static/libs/esr5-shim/es5-sham.js', watched: false},
```
![1 _bash-2](https://f.cloud.github.com/assets/118348/1218001/5e05b226-26b3-11e3-9b95-197b2f6397c7.png)

**Comment by Dignifiedquire** [comment]
For questions and support please use the mailing list or Gitter. The issue tracker is for bug reports and feature discussions only.
