### ISSUE TITLE
Multiple callbacks from preprocessors cause premature execution.

### ISSUE THREAD

**Issue by lennym** [karma-runner/karma#763]
A preprocessor we are using (https://github.com/xdissent/karma-browserify) has an issue where it occasionally calls back as complete more than once for some files.

Because lib/file-list.js only keeps a simple counter to track which files have been processed, this causes test execution to commence before all files have been processed.

I accept that this is a bug in the preprocessor (and have PR'ed it accordingly), but it is easily defended against within karma itself. 

I have some code in https://github.com/ConnectedHomes/karma/commit/454fadb1f4b4e30980e51bc9bfea36b4adeafc2e which will fix the issue, and I can PR it if you like, but it doesn't remotely meet your contribution guidelines (which I only found after writing it) and is very simple, so it may be easier to simply add it yourself if you want it.

Thanks.

**Comment by Dignifiedquire** [comment]
As this hasn't come up in the last 1,5 years I'll close this for now. If this still is an issue please feel free to open a new issue.
