### ISSUE TITLE
Allow custom browser names

### ISSUE THREAD

**Issue by vojtajina** [karma-runner/karma#779]
Eg. when running two versions of Chrome with different flags.

Possible solution:
- browser can report a custom name
- launcher pass the custom name to the browser

**Comment by budde377** [comment]
How about extending the `browsers` configuration to accepting objects:

```javascript
{
  name: string
  displayName: string
}
```

the `displayName` would then be reported.

**Comment by Dignifiedquire** [comment]
@budde377 not sure if that's needed, maybe it would be enough to just add `displayName` to the `customLaunchers` config, as I expect that is the main usage for this

**Comment by budde377** [comment]
@Dignifiedquire Ok, that makes sense. 
I can do that as soon as my outstanding pull-requests has been resolved :)

**Comment by Dignifiedquire** [comment]
@budde377 cool, I will get on with review then :)

**Comment by Dignifiedquire** [comment]
Fixed in #1806
