### ISSUE TITLE
Error: No provider for framework:requirejs

### ISSUE THREAD

**Issue by tychio** [karma-runner/karma#785]
I according to the [karma page](http://karma-runner.github.io/0.8/plus/RequireJS.html) write a test with requirejs. But output a error is no provider requirejs.

And I downloaded the [Demo](https://github.com/kjbekkelund/karma-requirejs/) and fixed some old version problems. But still output it.

version: `node 0.8.7` `karma 0.10.2`
config: `frameworks: ['jasmine', 'requirejs'],`

Should I update version or change config?

Or to update the Demo and tell me right,please!

**Comment by sunfeng90** [comment]
Solved this problem by calling "npm install karma-requirejs"

**Comment by bashisha** [comment]
"npm install karma-requirejs" solved it.

**Comment by edarioq** [comment]
This isn't enough, you also have to `https://requirejs.org/docs/node.html`

See [](https://requirejs.org/docs/node.html)

**Comment by saladinjake** [comment]
npm install requirejs karma-requirejs . then add the karma-requirejs in the plugin section of the karma config file
