### ISSUE TITLE
Kill Karma if user closes all the captured browsers

### ISSUE THREAD

**Issue by vojtajina** [karma-runner/karma#824]
When closing all the captured browsers, it might make sense to kill Karma.

We should probably distinguish between closed and crashed browser (which means another "closed" event).

Also, we need to make sure that it does not kill the long-running Karma use case, where I can run Karma for many days. When I wake my laptop from sleep, Karma reconnects. We need to preserve that.

**Comment by Dignifiedquire** [comment]
Closing this, as I actually feel this is not always the case.
