### ISSUE TITLE
Karma does not install a binary anymore

### ISSUE THREAD

**Issue by fidian** [karma-runner/karma#838]
I see in your changelog and with commit c7d46270aca83ecfe78f69fa923bc574c0b5bfdc that you intentionally removed the command from being installed.  Why is this?

This is causing problems for my build setups because I would list necessary packages in my `package.json` file, let `npm` install them and I would expect that they would be installed in `node_modules/.bin/` automatically.

The message associated with the commit explains the effect but does not enlighten anyone regarding the reasoning behind the change.  Would you please help me to understand why the old behavior is undesirable?

**Comment by jmendiara** [comment]
+1 
Most packages with binaries are nowadays being installed in `node_modules/.bin/` (examples: `mocha`, `dgeni`, `eslint`, `jscs`, ....) and lots of user modules are using `npm v2` `"scripts"` property in `package.json` to launch developer tools, moving away from grunt / gulp.

Please, reconsider the decision and let the users to use 
```json
"scripts": { 
    "test": "karma start"
}
```

instead of 
```json
"scripts": { 
    "test": "./node_modules/karma/bin/karma start"
}
```

**Comment by maksimr** [comment]
@jmendiara you can install `karma-cli` locally and use:

```js
"scripts": { 
    "test": "karma start"
}
```

**Comment by jmendiara** [comment]
@maksimr Thanks for the advice! It works like expected!

Unfortunately, I didn't succeed on finding some info about command line usage and karma-cli meaning in the __website__ (only some references about `CLI` in the [config section](http://karma-runner.github.io/0.12/config/configuration-file.html))
I had to execute `./node_modules/karma/bin/karma --help` for figuring out how to use it.
Maybe can be interesting for devs having such information stated clearly in the doc.

**Comment by jmendiara** [comment]
I've found it! at `Intro -> configuration`.

Maybe can have another path for easy finding?
