### ISSUE TITLE
Support for asynchronous plugins

### ISSUE THREAD

**Issue by caitp** [karma-runner/karma#851]
**Use case:**

Looking to test an AngularJS module (angular-ui/ui-router) against several versions of AngularJS, with and without specific plugins (angular-animate).

So, rather than making a big ugly grunt task to manage all of this, I thought it would be nice to write a karma plugin to simplify this.

The goal is this: interface with the bower API to install modules before a test suite is run (by injecting config.bower into the framework factory)

The problem I run into is that I can't seem to find a way to have a plugin treated as asynchronous, so that it can wait for installation to complete.

---

This would be a super-awesome plugin (I think), and it would depend on a super-awesome feature of Karma.

I could look at implementing this, but I am not aware of all of the finer points of the karma-runner, so it would be really nice if someone could give this some consideration

**Comment by Dignifiedquire** [comment]
Just a warning, this hack won't work in 0.13 any more as the `file_list_modified` event does not emit a promise anymore. 

I'm closing this issue for now as there hasn't been much activity lately.

**Comment by wilsonjackson** [comment]
@Dignifiedquire Thanks for the heads up. I haven't had a chance to look yet — do you know if Karma has introduced any kind of real support for asynchronous plugins yet? If not, any plugin using this trick will probably be SOL until they remedy that.

**Comment by Dignifiedquire** [comment]
No we hadn't yet. I'll reopen this, as it seems there is a need for supporting this properly.

**Comment by z-vr** [comment]
It would be really good to support this feature please. I want to write a framework which would start a certain server, but I don't have a way of making Karma wait before it is initialised. I could register it as pre-processor I suppose, but that's quite hackish.

**Comment by mboudreau** [comment]
Is this even possible yet?  I tied returning a promise in the factory function, but it doesn't seem to wait for it to resolve before moving onto tests.  This is extremely annoying to say the least.

**Comment by mjd0** [comment]
git clone git@github.com:material-foundation/material-remixer-remote-web.git
cd material-remixer-remote-web && npm install
