### ISSUE TITLE
Throw an error on not found browsers

### ISSUE THREAD

**Issue by dcherman** [karma-runner/karma#855]
Currently, it looks like if a browser isn't able to be loaded, karma just warns you and happily proceeds with the browsers that could be loaded.

https://github.com/karma-runner/karma/blob/master/lib/launcher.js#L41-L46

In a CI environment, it would be really, really easy to overlook that all of the sudden one of your configured browsers isn't working anymore, but since no errors are thrown the build is still happy.

I'm proposing that instead of continuing on, encountering a browser that couldn't be loaded should be treated as a fatal error - any loaded browsers should be cleaned up, and the process should exit.

**Comment by dignifiedquire** [comment]
@budde377 mind taking a look at this? This is the last thing I want to get in that isn't PRed yet before finally moving to 1.0 and using proper semver.

**Comment by dignifiedquire** [comment]
@budde377 there exists a PR already that started this, but it's not finished yet: #1239

**Comment by budde377** [comment]
@dignifiedquire Will do!
