### ISSUE TITLE
Public API for config

### ISSUE THREAD

**Issue by abuchanan** [karma-runner/karma#860]
I've just filed this bug with grunt-karma,
https://github.com/karma-runner/grunt-karma/issues/79

Which got me thinking, should config have a public API?

If it did, grunt-karma could parse the config itself, do whatever merging/overwriting of config it needed to, and then pass that to karma.server.

**Comment by Dignifiedquire** [comment]
The original issue was fixed, I don't think there is a need for exposing an api for that at the moment.
