### ISSUE TITLE
karma + jquerymobile

### ISSUE THREAD

**Issue by char0n** [karma-runner/karma#865]
Hello,

I have been having problems with karma runner + jquerymobile framework. Whenever I try to use jquerymobile while running tests, I get errors and exeptions.

This is my  karma.conf.js:

module.exports = function(config) {
  config.set({
    basePath: '',
    frameworks: ['qunit'],
    files: [
      {pattern: 'lib/jquery.js', included: true},
      {pattern: 'lib/jquerymobile.js', included: true},
      'tests/main.js'
    ],
    exclude: ['main.js', 'lib/qunit.js', 'lib/require.js', 'lib/almond.js', 'lib/add2home.js'],
    reporters: ['progress'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_DEBUG,
    autoWatch: false,
    browsers: ['PhantomJS'],
    captureTimeout: 60000,
    singleRun: true
  });
};

This is my tests/main.js:

test('test', function() {
  equal(3, 3);
});

//describe("A suite", function() {
//  it("contains spec with an expectation", function() {
//    expect(true).toBe(true);
//  });
//});

When I run karma, I get this exception:

        Died on test #1     at /home/char0n/.virtualenvs/mcat/lib/node/lib/node_modules/qunitjs/qunit/qunit.js:425
            at /home/char0n/projects/python/mcat/src/frontend/mcat/static/mcat/js/tests/main.js:22: assertion outside test context, was     at :556
            at /home/char0n/projects/python/mcat/src/frontend/mcat/static/mcat/js/tests/main.js:21
            at /home/char0n/.virtualenvs/mcat/lib/node/lib/node_modules/qunitjs/qunit/qunit.js:203
            at /home/char0n/.virtualenvs/mcat/lib/node/lib/node_modules/qunitjs/qunit/qunit.js:361
            at process (/home/char0n/.virtualenvs/mcat/lib/node/lib/node_modules/qunitjs/qunit/qunit.js:1453)
            at /home/char0n/.virtualenvs/mcat/lib/node/lib/node_modules/qunitjs/qunit/qunit.js:479
        Error: assertion outside test context, was     at :556

When I modify my karma.conf.js and use jasmine instead of qunit this is what I get:

PhantomJS 1.9.2 (Linux) ERROR
        RangeError: Maximum call stack size exceeded.
        at /home/char0n/.virtualenvs/mcat/lib/node/lib/node_modules/karma-jasmine/lib/jasmine.js:1811
PhantomJS 1.9.2 (Linux): Executed 1 of 1 ERROR (0.42 secs / 0.214 secs)

It seems like some compatibli issue with karma + jquerymobile. When I remove jquerymobile from config, everything works as expected. Tests pass.

This is my npm list:

├─┬ karma@0.10.8
│ ├── chokidar@0.7.1
│ ├── coffee-script@1.6.3
│ ├── colors@0.6.0-1
│ ├─┬ connect@2.8.8
│ │ ├── buffer-crc32@0.2.1
│ │ ├── bytes@0.2.0
│ │ ├── cookie@0.1.0
│ │ ├── cookie-signature@1.0.1
│ │ ├── debug@0.7.4
│ │ ├── formidable@1.0.14
│ │ ├── fresh@0.2.0
│ │ ├── methods@0.0.1
│ │ ├── pause@0.0.1
│ │ ├── qs@0.6.5
│ │ ├─┬ send@0.1.4
│ │ │ └── range-parser@0.0.4
│ │ └── uid2@0.0.2
│ ├── di@0.0.1
│ ├─┬ glob@3.1.21
│ │ └── inherits@1.0.0
│ ├── graceful-fs@1.2.3
│ ├─┬ http-proxy@0.10.3
│ │ ├── pkginfo@0.2.3
│ │ └─┬ utile@0.1.7
│ │   ├── async@0.1.22
│ │   ├── deep-equal@0.1.0
│ │   ├── i@0.3.2
│ │   ├── mkdirp@0.3.5
│ │   ├── ncp@0.2.7
│ │   └── rimraf@1.0.9
│ ├── lodash@1.1.1
│ ├─┬ log4js@0.6.9
│ │ ├── async@0.1.15
│ │ ├── readable-stream@1.0.17
│ │ └── semver@1.1.4
│ ├── mime@1.2.11
│ ├─┬ minimatch@0.2.12
│ │ ├── lru-cache@2.5.0
│ │ └── sigmund@1.0.0
│ ├─┬ optimist@0.3.7
│ │ └── wordwrap@0.0.2
│ ├── q@0.9.7
│ ├── rimraf@2.1.4
│ ├─┬ socket.io@0.9.16
│ │ ├── base64id@0.1.0
│ │ ├── policyfile@0.0.4
│ │ ├── redis@0.7.3
│ │ └─┬ socket.io-client@0.9.16
│ │   ├─┬ active-x-obfuscator@0.0.1
│ │   │ └── zeparser@0.0.5
│ │   ├── uglify-js@1.2.5
│ │   ├─┬ ws@0.4.31
│ │   │ ├── commander@0.6.1
│ │   │ ├── nan@0.3.2
│ │   │ ├── options@0.0.5
│ │   │ └── tinycolor@0.0.1
│ │   └── xmlhttprequest@1.4.2
│ └─┬ useragent@2.0.7
│   └── lru-cache@2.2.4
├── karma-chrome-launcher@0.1.1
├─┬ karma-coffee-preprocessor@0.1.1
│ └── coffee-script@1.6.3
├── karma-firefox-launcher@0.1.2
├── karma-html2js-preprocessor@0.1.0
├── karma-ie-launcher@0.1.1
├── karma-jasmine@0.1.4
├── karma-opera-launcher@0.1.0
├─┬ karma-phantomjs-launcher@0.1.1
│ └─┬ phantomjs@1.9.2-5
│   ├── adm-zip@0.2.1
│   ├── kew@0.1.7
│   ├── mkdirp@0.3.5
│   ├── ncp@0.4.2
│   ├─┬ npmconf@0.0.24
│   │ ├─┬ config-chain@1.1.8
│   │ │ └── proto-list@1.2.2
│   │ ├── inherits@1.0.0
│   │ ├── ini@1.1.0
│   │ ├─┬ nopt@2.1.2
│   │ │ └── abbrev@1.0.4
│   │ ├── once@1.1.1
│   │ ├── osenv@0.0.3
│   │ └── semver@1.1.4
│   ├── rimraf@2.2.5
│   └── which@1.0.5
├── karma-requirejs@0.2.0
├── karma-safari-launcher@0.1.1
├── karma-script-launcher@0.1.0
└── qunitjs@1.12.0

node version==v0.10.22
jquerymobile version=1.3.2 & 1.4.0

If you need any more information about my env, don't hasitate to responed. Thanks for any help.

**Comment by Dignifiedquire** [comment]
Solved

**Comment by char0n** [comment]
Yep, thanks a lot.

On Fri, Jun 26, 2015 at 11:07 PM, Friedel Ziegelmayer <
notifications@github.com> wrote:

> Solved
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/karma-runner/karma/issues/865#issuecomment-115883632>.
>



-- 

Vladimír Gorej | CodeScale s.r.o.
email: gorej@codescale.net
tel: +420 777 861 279, +421 948 023 011
web: http://www.codescale.net
