### ISSUE TITLE
Run all the tests in strict mode

### ISSUE THREAD

**Issue by vojtajina** [karma-runner/karma#868]
`node --use_strict`

**Comment by BevanR** [comment]
Why was this closed?  How can I have run karma run in strict mode?  Do I really need to add "use strict" to every file in my project?

**Comment by dignifiedquire** [comment]
> How can I have run karma run in strict mode?

What part of karma do you want to run in strict mode? The node part does not need strict mode the way it is written now.

> Do I really need to add "use strict" to every file in my project?

Yes, or just use sth like babel which compiles to strict mode. The flag would have no effect on the tests as they are executed in the browser and not in node.
