### ISSUE TITLE
Cannot use karma after installation on Windows 8

### ISSUE THREAD

**Issue by gmardok** [karma-runner/karma#871]
After installing karma with comman 
npm install karma
I'm not able to even check version with command
karma --version
It says "'karma' is not recognized as an internal or external command, operable program or batch file."
Also I can't find any command or bat fles under c:\Users<username>\node_modules\karma\bin folder.

**Comment by techno2mahi** [comment]
![600x300](https://cloud.githubusercontent.com/assets/6048590/6980521/ae22f554-da10-11e4-9eb2-5ba5f25055e8.gif)
