### ISSUE TITLE
There should be a way to ask karma to serve a specific directory in a given path

### ISSUE THREAD

**Issue by lgalfaso** [karma-runner/karma#872]
There should be a way to specify karma that a specific content should be served from a specified path. Right now, the only (very hacky) way to do this is

``` javascript
files = [
  {pattern: 'images/*.png', included: false, served: true}
];

proxies =  {
  '/images': 'http://localhost:9876/base/images'
};

```

That has the big issue that, when the configuration is run, we cannot be positive that karma will run at port 9876 or another port

**Comment by thirusabari** [comment]
I have tried above fix  for karma-warnings. But it was not fixed for me. Could you any one provide me an right solution to the clear the WARN web- server in karma

**Comment by einav7** [comment]
I've also encountered this issue,
can't I have fake images URL that doesn't exists when I run the tests?

**Comment by silvaw** [comment]
None of those answers solved this annoying 404 warn.

I've this setup in my karma.conf.js:

```
files: [
    {pattern: 'src/main/webapp/assets/images/**/*.png', included: false, served: true},
    'src/main/webapp/assets/scripts/vendor/*.js',
    'src/main/webapp/assets/scripts/dist/*.js',
    'src/main/webapp/assets/bower_components/angular-mocks/angular-mocks.js',
    'src/main/webapp/assets/partials/**/*.html',
    'src/test/javascript/spec_helper.js',
    'src/test/javascript/**/*.js',
],
exclude: [],
.
.
.
proxies: {
    '/assets/images/diagnostico-assinador/': '/base/',
    '/assets/images/prioridade/': '/base/'
}
```

and got this warn:

**WARN [web-server]: 404: /base/image.png**
