### ISSUE TITLE
The package karma does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by DrStep** [karma-runner/karma#873]
Hello! Is there any alternatives for solving this problem except reinstall?

npm ERR! peerinvalid The package karma does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-karma@0.7.2 wants karma@~0.11.0
npm ERR! peerinvalid Peer karma-html2js-preprocessor@0.1.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-chrome-launcher@0.1.1 wants karma@>=0.9.3
npm ERR! peerinvalid Peer karma-jasmine@0.1.3 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-firefox-launcher@0.1.2 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-script-launcher@0.1.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-requirejs@0.2.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-coffee-preprocessor@0.1.1 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-phantomjs-launcher@0.1.1 wants karma@>=0.9
npm ERR! System Linux 2.6.32-5-xen-amd64
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /home/bamboo/bamboo/data/xml-data/build-dir/MBR-KARMA-JS/tools/pc-builder
npm ERR! node -v v0.8.22
npm ERR! npm -v 1.2.14
npm ERR! code EPEERINVALID
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/bamboo/bamboo/data/xml-data/build-dir/MBR-KARMA-JS/tools/pc-builder/npm-debug.log
npm ERR! not ok code 0

**Comment by distinctdan** [comment]
Just had this. Turns out, npm was incorrectly installing karma 0.13.0, even though grunt-karma wants ~0.12.0. The fix was to manually specify "karma": "~0.12.0" in my package.json.

**Comment by alexandrehebert** [comment]
@distinctdan same for me, your solution worked

**Comment by balmas** [comment]
:+1:

**Comment by bdeanindy** [comment]
Thanks @distinctdan that worked. I've created a ticket in grunt-karma (referencing this issue) for them to look at resolving (could be a publishing error or something else).

**Comment by distinctdan** [comment]
Sounds good, thanks.
