### ISSUE TITLE
Close the karma tab after tests finish

### ISSUE THREAD

**Issue by mgol** [karma-runner/karma#878]
Currently Karma doesn't close its tab on which tests are run. For most browsers it's not a problem as there are new profiles created for each Karma run. However, Safari is an exception. If you have an option to keep tabs from the previous session turned on, it causes the Karma tab to open twice, making all tests run twice on the browser (and 3 times during the next one etc.).

I think this is a problem & Karma should just close its tab just before closing the browser.

**Comment by chevdor** [comment]
same with Safari 8.0.3 (Mac OS X 10.10.2)

**Comment by gardenvarietyse** [comment]
A small hack (emphasis on hack) for the Safari launcher that seems to work, but has definitely not been extensively tested: gardenvarietyse/karma-safari-launcher@28eb4f19737af74037cb5cf17160f9770172bbd1

Should be possible to properly hook into the event system somehow, but I'm not that fluent in Node or Karma's codebase

**Comment by shaharmor** [comment]
Any update on this?

**Comment by xhocquet** [comment]
I'd also love some info, I'm getting three Safari instances in my tests, and I'm not sure if it's related but the last Safari instance takes way more time than the other browsers:
```Uzj9AAAA with id 53890878
Safari 9.0.1 (Mac OS X 10.10.5): Executed 28 of 50 SUCCESS (0 secs / 0.099 secs)
Safari 9.0.1 (Mac OS X 10.10.5): Executed 33 of 50 SUCCESS (0 secs / 0.998 secs)
Safari 9.0.1 (Mac OS X 10.10.5): Executed 50 of 50 SUCCESS (7.001 secs / 5.99 secs)
Chrome 46.0.2490 (Mac OS X 10.10.5): Executed 50 of 50 SUCCESS (0.177 secs / 0.157 secs)
Firefox 41.0.0 (Mac OS X 10.10.0): Executed 50 of 50 SUCCESS (0.266 secs / 0.246 secs)
TOTAL: 150 SUCCESS
```

**Comment by shaharmor** [comment]
Solution: run this on terminal: `defaults write com.apple.Safari ApplePersistenceIgnoreState YES`

**Comment by HowlingEverett** [comment]
That's not a wonderful solution since it means that Safari will never remember open tabs in between app launches, which is a really useful feature for normal browsing. Closing the open tab before killing the safari-launcher is a better solution.

I'll have a look and see if there's any decent way of doing this.

**Comment by HowlingEverett** [comment]
It's not a wonderful set of options, but we have pretty much two ways to programatically control Safari:

1. AppleScript (Hacky, but free-standing, the main difficulty will be identifying the instance and the tab containing the Karma runner)
2. A Safari Extension: this gives us a nice programatic API for locating tabs, selecting them, closing them, etc. But it would require the user to install the extension separately before using karma-safari-launcher. It would be possible to just distribute the extension package with the karma-safari-launcher distribution, though.

Of the two, probably the extension is the safer bet. You could spend many hours on an Applescript solution that fails in annoying and hard-to-control ways. But, I'm more of a JS guy than an Applescript guy so maybe somebody knows a reliable way of making it work :P

**Comment by HowlingEverett** [comment]
So, AppleScript may be actually a decent way to go, this *almost* works:

```applescript
tell application "Safari"
	set windowList to every tab of every window whose (URL contains "localhost:9876")
	
	repeat with tabList in windowList
		repeat with thistab in tabList
			close thistab
		end repeat
	end repeat
end tell
```

This works if I manually paste the karma runner URL into a normal, manually launched version of Safari. However, it doesn't work with the secondary instance of Safari launched by `karma-safari-launcher`

**Comment by HowlingEverett** [comment]
Hrm. The AppleScript 'tell' block doesn't have any way of noticing running instances unless they have different names. Honestly, since there is no such thing as a clean profile for Safari, there's not a whole lot of point launching a separate instance. It wouldn't be too difficult to patch `karma-safari-launcher` to do the whole thing using a node module wrapping AppleScript. This way you can launch the app if it's closed, or just attach to the running instance and open the karma runner in a new tab...and then also close the tab at the end of the session.

Of course, none of this applies to Safari on Windows, but that application is so out of date now I highly recommend that nobody runs it, lets alone tests code in it.

**Comment by HowlingEverett** [comment]
Hold the phone, we get a much lower level API using the OSAscripting API (with the nice benefit that you can use js as a scripting language for this). The other benefit is you can, for example, run grep directly and pull out the bundle identifier as a process for selecting the application.

I have to go to work now, but I think this is pretty solvable with an update to the karma-safari-launcher + OSAScript. I'll see if I can PR tonight.

**Comment by Dianna** [comment]
Glad to see someone's looking into this! Thank you

**Comment by mgol** [comment]
Another idea on how to make it work is in #20. That would not require OSAscripting and would resolve some other issues as well.

**Comment by johnjbarton** [comment]
Please open this issue on karma-safari-launcher. If it is important for you I suggest you investigate and propose a fix.  It just does not look like something that will be addressed here because it only affects safari and a fix is likely to be browser specific.

**Comment by mgol** [comment]
FYI, I think resolving this issue would fix this issue for Safari: https://github.com/karma-runner/karma-safari-launcher/issues/20.
