### ISSUE TITLE
Strange error trying to run Jasmine specs

### ISSUE THREAD

**Issue by callum** [karma-runner/karma#880]
```
callum:tool-test $ gulp test
[gulp] Using file /Users/madebymany/tool-test/gulpfile.js
[gulp] Working directory changed to /Users/madebymany/tool-test
[gulp] Running 'scripts'...
[gulp] Finished 'scripts' in 4.52 ms
[gulp] Running 'test'...
/Users/madebymany/tool-test/src/main.js
[gulp] Starting Karma server...

/Users/madebymany/tool-test/node_modules/gulp-karma/node_modules/karma/node_modules/di/lib/injector.js:9
      throw error('No provider for "' + name + '"!');
            ^
Error: No provider for "framework:jasmine"! (Resolving: framework:jasmine)
    at error (/Users/madebymany/tool-test/node_modules/gulp-karma/node_modules/karma/node_modules/di/lib/injector.js:22:68)
    at Object.parent.get (/Users/madebymany/tool-test/node_modules/gulp-karma/node_modules/karma/node_modules/di/lib/injector.js:9:13)
    at get (/Users/madebymany/tool-test/node_modules/gulp-karma/node_modules/karma/node_modules/di/lib/injector.js:54:19)
    at /Users/madebymany/tool-test/node_modules/gulp-karma/node_modules/karma/lib/server.js:29:14
    at Array.forEach (native)
    at start (/Users/madebymany/tool-test/node_modules/gulp-karma/node_modules/karma/lib/server.js:28:21)
    at invoke (/Users/madebymany/tool-test/node_modules/gulp-karma/node_modules/karma/node_modules/di/lib/injector.js:75:15)
    at Object.exports.start (/Users/madebymany/tool-test/node_modules/gulp-karma/node_modules/karma/lib/server.js:272:12)
    at Object.<anonymous> (/Users/madebymany/tool-test/node_modules/gulp-karma/lib/background.js:3:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
[gulp] Finished 'test' in 566 ms
```

I have tried reinstalling Karma and associated modules. Explicitly installing `karma-jasmine` didn't seem to work (http://stackoverflow.com/questions/19185548/no-provider-error-on-karma-serve-running-angularjs-phonecat-tutorial).

**Comment by vinneyk** [comment]
Any progress with this, @munishmehta27 or @maksimr? I'm experiencing the same issue. Below are my config files. Thanks in advance!

    // Karma configuration
    // Generated on Mon Feb 09 2015 11:38:40 GMT-0700 (Mountain Standard Time)

    module.exports = function(config) {
      config.set({

        // base path that will be used to resolve all patterns (eg. files, exclude)
        basePath: '',


        // frameworks to use
        // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
        frameworks: ['jasmine'],


        // list of files / patterns to load in the browser
        files: [
          'app/build/*',
          'Test/*Spec.js'
        ],


        // list of files to exclude
        exclude: [
        ],


        // preprocess matching files before serving them to the browser
        // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
        preprocessors: {
            'app/build/*': ['webpack', 'sourcemap'],
            'Test/*Spec.js': ['webpack', 'sourcemap'],
        },


        webpack: {
            devtool: 'inline-source-map'
        },


        webpackMiddleware: {
            // webpack-dev-middleware configuration
            noInfo: true
        },


        plugins: [
            require("karma-webpack")
        ],


        // test results reporter to use
        // possible values: 'dots', 'progress'
        // available reporters: https://npmjs.org/browse/keyword/karma-reporter
        reporters: ['progress'],


        // web server port
        port: 9876,


        // enable / disable colors in the output (reporters and logs)
        colors: true,


        // level of logging
        // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
        logLevel: config.LOG_INFO,


        // enable / disable watching file and executing tests whenever any file changes
        autoWatch: true,


        // start these browsers
        // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
        browsers: ['Chrome'],


        // Continuous Integration mode
        // if true, Karma captures browsers, runs the tests and exits
        singleRun: false
      });
    };

    {
      "name": "RVC",
      "version": "0.0.1",
      "description": "",
      "main": " ",
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "author": "",
      "license": "ISC",
      "devDependencies": {
        "css-loader": "^0.9.0",
        "exports-loader": "^0.6.2",
        "expose-loader": "^0.6.0",
        "imports-loader": "^0.6.3",
        "jasmine-core": "^2.2.0",
        "karma": "^0.12.31",
        "karma-chrome-launcher": "^0.1.7",
        "karma-ie-launcher": "^0.1.5",
        "karma-jasmine": "^0.3.5",
        "karma-sourcemap-loader": "^0.3.3",
        "karma-webpack": "^1.5.0",
        "raw-loader": "^0.5.1",
        "style-loader": "^0.8.2"
      },
      "dependencies": {
        "knockout": "^3.2.0",
        "page": "^1.5.0",
        "webpack": "^1.4.14"
      }
    }

**Comment by raphaelhudvoy** [comment]
I had the same problem. Adding 'karma-jasmine', 'karma-chrome-launcher' in the plugins fixed it.

      plugins : [
            require('karma-webpack'),
            'karma-jasmine',
            'karma-chrome-launcher'
        ]

**Comment by garora** [comment]
Why this is closed?

**Comment by jorgenbs** [comment]
Resolved this issue by checking if I had karma/jasmine installed globally:

    npm ls -g karma
    npm ls -g jasmine

Removed both, then `npm install -g karma-cli` and have jasmine+karma only locally installed

**Comment by rajeshtulika** [comment]
I had the same problem and the @raphaelhudvoy suggestion to add 'karma-jasmine' in the plugins inside karma.config.js fixed it.

**Comment by garora** [comment]
Still having problem with VS2015

**Comment by npx** [comment]
I can confirm that adding `'karma-jasmine'` to the plugins works. I kinda wonder why the karma init does not add it if it becomes a necessary step now.

I have karma-cli installed globally, and karma, karma-jasmine locally.

**Comment by EightArmCode** [comment]
I had the same problem, and uninstalling the global instance of karma fixed it for me, too. Since this is a 1.5 year old bug, it would make sense if the dev team found an actual fix for this...

**Comment by garora** [comment]
Its again broke my dev environment

**Comment by maksimr** [comment]
@EightArmCode it's not bug. If you run global `karma` then `karma` will try find global `karma-jasmine` that logical. Special for this case was made `karma-cli` which run project instance of karma that solve this issue.

Thanks!

**Comment by ws-perelyaynen** [comment]
npm install -g karma-cli
worked for me

**Comment by utpal-kumar** [comment]
I have included all the dependencies then working fine.
 "devDependencies": {
    "angular-mocks": "^1.3.12",
    "jasmine": "^2.4.1",
    "requirejs": "2.1",
    "karma": "^0.10.10",
    "karma-chrome-launcher": "0.1.2",
    "karma-coffee-preprocessor": "0.1.3",
    "karma-firefox-launcher": "0.1.0",
    "karma-html2js-preprocessor": "0.1.0",
    "karma-jasmine": "0.1.0",
    "karma-phantomjs-launcher": "0.1.0",
    "karma-requirejs": "0.2.0",
    "karma-script-launcher": "0.1.0"
  }

**Comment by benjaGarrido** [comment]
I resolved this problem doing:
rm -rf node_modules/
npm install --save-dev karma
npm install --save-dev karma-cli
npm install --save-dev jasmine
npm install --save-dev jasmine-core
npm install --save-dev karma-jasmine
npm install --save-dev karma-chrome-launcher
npm install --save-dev requirejs
npm install --save-dev karma-requirejs

**Comment by shengxihu** [comment]
I resolved this problem with this conf:
```js
frameworks: ['jasmine'],
plugins: [
    require("karma-jasmine"),
 ]
```
by the way, i also get:
```
{ Error: Cannot find module 'PhantomJS'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)...
```
with:
```
browsers: ['PhantomJS'],
```
and I also resolved this problem with:
```
plugins: [
   require("karma-phantomjs-launcher")
],
```
maybe this will help somebody.

**Comment by cjemagid** [comment]
I struggled with the exact same problem. After investigating I realized that karma was running globally using '/usr/' directory as the base folder.

A solution that worked for me was to replace karma with karma-cli:

```
npm remove -g karma
npm install -g karma-cli
```
