### ISSUE TITLE
karma throws IE11 into compatibility mode

### ISSUE THREAD

**Issue by WickyNilliams** [karma-runner/karma#883]
Hosts in the local zone cause IE to render in compatibility mode. Since the karma page is running locally it falls into this category, causing IE to go into IE7 mode. This can be fixed by going into dev tools and altering the document mode, but it's an annoyance. 

The problem can be remedied by sending the `X-UA-Compatible` HTTP header with a value of `ie=edge`

**Comment by mzgol** [comment]
Shouldn't Karma send:
```html
<meta http-equiv="X-UA-Compatible" content="IE=Edge"/>
```
by default and only change it to another value if it's explicitly provided? On the public web IE11 will receive its most standards-compliant mode so the Karma default should force it to IE11 mode by default as well.
