### ISSUE TITLE
Did not manage to run jasmine tests

### ISSUE THREAD

**Issue by ghost** [karma-runner/karma#888]
I intended to run jasmine test on win7, phpstorm7, phpstorm karma plugin. I found multiple problems...

I installed karma from git bash:

`npm install -g karma`

Despite the statements in the documentation it did not install the karma-\* plugins, so I had to install them manually:

`npm install -g karma-jasmine`
`npm install -g karma-requirejs`
...

After that I generated a test file with karma:

``` js
module.exports = function (config) {
    config.set({
        basePath: 'test',
        frameworks: ['jasmine', 'requirejs'],
        files: [
            {pattern: 'test-mixin.js', included: true}
        ],
        exclude: [

        ],
        reporters: ['progress'],
        port: 9876,
        colors: true,
        logLevel: config.LOG_INFO,
        autoWatch: true,
        browsers: ['Firefox'],
        captureTimeout: 60000,
        singleRun: false
    });
};

```

I tried to run (ofc I installed the plugins after found out by run that they are not installed), but I got the following phenomenons:
- Sometimes I got port is already in use message, sot it automatically tries with other port (but nothing runs on the 9876 just karma). I tried with another port, I got the same results after some runs.
- If I close the browser window manually it does not start a new window, just writes that server is not running. If I add the new window manually it starts complaining about port collisions, and opens a new window with different port.
- I tried to change the browser to Chrome in the config file, but it still did open Firefox window.
- I have confusing messages in phpstorm windows: 
  - empty test suite (in event log)
  - no tests found
  - instantiating tests (for several minutes)
  - unable to attach test reporter to test framework or test framework quit unexpectedly
  - waiting for previous execution
  - [DEBUG] config - No config file specified
  - INFO [karma]: Delaying execution, these browsers are not ready: Firefox 26.0.0 (Windows 7)

I don't know what happens in the background, but the test obviously does not run. :S 

![1](https://f.cloud.github.com/assets/408911/1926786/92404a6c-7e4a-11e3-9cd7-421de2896372.png)
![2](https://f.cloud.github.com/assets/408911/1926788/94eb25fc-7e4a-11e3-8e4f-3d9a0f81874b.png)
![3](https://f.cloud.github.com/assets/408911/1926790/973a515c-7e4a-11e3-8dc8-acf66d0fcf9f.png)
![4](https://f.cloud.github.com/assets/408911/1926799/c81b9d76-7e4a-11e3-92de-ecc2a216d6de.png)

(The code uses core js only, it does not require browser specific tests, so I'll change to jasmine-node instead of this.)

**Comment by raphaelLacerda** [comment]
i was having the same problem

it was basically removing requirejs from the list of frameworks
frameworks: ['jasmine'],
