### ISSUE TITLE
crashes on save

### ISSUE THREAD

**Issue by bibodha** [karma-runner/karma#963]
Karma v0.12.0
Browswer: Chrome 33.0.1750 (Windows 7)
Windows 7 running on VMWare on Mac OSX 10.9

Error Message:

```
ERROR [karma]: { [Error: ENOENT, stat 'c:\Projects\demo\test\appSpec.js']
  errno: 34,
  code: 'ENOENT',
path: 'c:\\Projects\\demo\\test\\appSpec.js' }
Error: ENOENT, stat 'c:\Projects\demo\test\appSpec.js'
INFO [watcher]: Changed file "c:/Projects/demo/test/appSpec.js".
```

This also happens when running PhantomJS instead of Chrome and happens very frequently.

**Comment by dignifiedquire** [comment]
Is this still an issue?

**Comment by devoto13** [comment]
As we haven't heard any more reports of this problem in 4 years, I think it is pretty safe to assume that it was resolved. Happy to re-open if anybody still experiences the problem and can provide a reproduction.
