### ISSUE TITLE
Improve watching

### ISSUE THREAD

**Issue by vojtajina** [karma-runner/karma#974]
There are still many issues with file watching (both using events and polling).
See https://github.com/paulmillr/chokidar/issues/105, https://github.com/paulmillr/chokidar/issues/9, https://github.com/paulmillr/chokidar/issues/35, https://github.com/karma-runner/karma/issues/960 and many others...

I looked into chokidar and I think we might workaround some of these issues by never watching a file, but rather parent directory.

THE CHANGE:
Right now, for patterns such as `src/*.js` we have to watch the `src/` directory and so we do (see https://github.com/karma-runner/karma/blob/65b5f1b37fedfb5bd1c43c900c7520b5d0c26017/lib/watcher.js#L16-L39). But for patterns such as `src/main.js`, we watch that file. Instead, we should watch the parent directory (`src/`).

ISSUES (when watching a single file):
- if file does not exist, it's not watched (eg. when later added, it's ignored) (https://github.com/paulmillr/chokidar/issues/105)
- with OS events, it even throws ENOENT error
- if file is removed, chokidar won't notice on OSX (https://github.com/paulmillr/chokidar/issues/9) and when later added, chokidar won't notice either

This workaround will fix these issues. At least on Mac OSX. We need to test this on Linux and Windows, too. Both with `usePolling: true` and `usePolling: false`.

It still won't work if the parent directory does not exist (we should show a warning), but I think it would be a significant improvement. This has to be fixed in chokidar, but I think the change is not trivial.

@paulmillr what do you think?

**Comment by Dignifiedquire** [comment]
Closing as most of the work was done in chokdiar and we have upgraded
