### ISSUE TITLE
Failing build on reportSlowerThan

### ISSUE THREAD

**Issue by mbarzeev** [karma-runner/karma#978]
Hi,
I searched but couldn't find a way to fail the tests if one of them exceeds the reportSlowerThan limit. I know it is a bit harsh but sometimes that's the only way ;)
Is there a way of doing that?

Cheers

**Comment by Dignifiedquire** [comment]
For questions and support please use the mailing list or Gitter. The issue tracker is for bug reports and feature discussions only.
