### ISSUE TITLE
"npm install -g karma" fails to compile a node module

### ISSUE THREAD

**Issue by MarkStega** [karma-runner/karma#997]
Microsoft Windows [Version 6.3.9600](c) 2013 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>npm install -g karma
npm http GET https://registry.npmjs.org/karma
npm http 304 https://registry.npmjs.org/karma
npm http GET https://registry.npmjs.org/di
npm http GET https://registry.npmjs.org/socket.io
npm http GET https://registry.npmjs.org/chokidar
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/http-proxy
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/q
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/log4js
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/useragent
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/connect
npm http GET https://registry.npmjs.org/source-map
npm http 304 https://registry.npmjs.org/chokidar
npm http 304 https://registry.npmjs.org/http-proxy
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/di
npm http 304 https://registry.npmjs.org/socket.io
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/log4js
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/colors
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/useragent
npm http 304 https://registry.npmjs.org/connect
npm http 304 https://registry.npmjs.org/source-map
npm http 304 https://registry.npmjs.org/q
npm http 304 https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/fsevents/0.2.0
npm http GET https://registry.npmjs.org/recursive-readdir/0.0.2
npm http 304 https://registry.npmjs.org/recursive-readdir/0.0.2
npm http 304 https://registry.npmjs.org/fsevents/0.2.0
npm WARN optional dep failed, continuing fsevents@0.2.0
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/sigmund
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/minimist
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/minimist
npm http GET https://registry.npmjs.org/socket.io-client/0.9.16
npm http GET https://registry.npmjs.org/policyfile/0.0.4
npm http GET https://registry.npmjs.org/base64id/0.1.0
npm http GET https://registry.npmjs.org/redis/0.7.3
npm http 304 https://registry.npmjs.org/base64id/0.1.0
npm http GET https://registry.npmjs.org/amdefine
npm http 304 https://registry.npmjs.org/policyfile/0.0.4
npm http 304 https://registry.npmjs.org/socket.io-client/0.9.16
npm http 304 https://registry.npmjs.org/amdefine
npm http 304 https://registry.npmjs.org/redis/0.7.3
npm http GET https://registry.npmjs.org/async/0.1.15
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/pkginfo
npm http GET https://registry.npmjs.org/utile
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/async/0.1.15
npm http 304 https://registry.npmjs.org/pkginfo
npm http 304 https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/batch/0.5.0
npm http GET https://registry.npmjs.org/qs/0.6.6
npm http GET https://registry.npmjs.org/cookie-signature/1.0.1
npm http GET https://registry.npmjs.org/buffer-crc32/0.2.1
npm http GET https://registry.npmjs.org/cookie/0.1.0
npm http GET https://registry.npmjs.org/send/0.1.4
npm http GET https://registry.npmjs.org/bytes/0.2.1
npm http GET https://registry.npmjs.org/fresh/0.2.0
npm http GET https://registry.npmjs.org/pause/0.0.1
npm http GET https://registry.npmjs.org/uid2/0.0.3
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/methods/0.1.0
npm http GET https://registry.npmjs.org/raw-body/1.1.2
npm http GET https://registry.npmjs.org/negotiator/0.3.0
npm http GET https://registry.npmjs.org/multiparty/2.2.0
npm http 304 https://registry.npmjs.org/utile
npm http 304 https://registry.npmjs.org/qs/0.6.6
npm http 304 https://registry.npmjs.org/buffer-crc32/0.2.1
npm http 304 https://registry.npmjs.org/batch/0.5.0
npm http 304 https://registry.npmjs.org/cookie/0.1.0
npm http 304 https://registry.npmjs.org/bytes/0.2.1
npm http 304 https://registry.npmjs.org/send/0.1.4
npm http 304 https://registry.npmjs.org/pause/0.0.1
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/methods/0.1.0
npm http 304 https://registry.npmjs.org/cookie-signature/1.0.1
npm http 304 https://registry.npmjs.org/raw-body/1.1.2
npm http 304 https://registry.npmjs.org/negotiator/0.3.0
npm http 304 https://registry.npmjs.org/multiparty/2.2.0
npm http 304 https://registry.npmjs.org/fresh/0.2.0
npm http 304 https://registry.npmjs.org/uid2/0.0.3
npm http GET https://registry.npmjs.org/range-parser/0.0.4
npm http GET https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/range-parser/0.0.4
npm http 304 https://registry.npmjs.org/string_decoder
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/deep-equal
npm http GET https://registry.npmjs.org/i
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/ncp
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/ncp
npm http 304 https://registry.npmjs.org/i
npm http 304 https://registry.npmjs.org/deep-equal
npm http GET https://registry.npmjs.org/stream-counter
npm http 304 https://registry.npmjs.org/stream-counter
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/debuglog/0.0.2
npm http 304 https://registry.npmjs.org/debuglog/0.0.2
npm http GET https://registry.npmjs.org/uglify-js/1.2.5
npm http GET https://registry.npmjs.org/xmlhttprequest/1.4.2
npm http GET https://registry.npmjs.org/ws
npm http GET https://registry.npmjs.org/active-x-obfuscator/0.0.1
npm http 304 https://registry.npmjs.org/xmlhttprequest/1.4.2
npm http 304 https://registry.npmjs.org/active-x-obfuscator/0.0.1
npm http 304 https://registry.npmjs.org/uglify-js/1.2.5
npm http 304 https://registry.npmjs.org/ws
npm http GET https://registry.npmjs.org/zeparser/0.0.5
npm http 304 https://registry.npmjs.org/zeparser/0.0.5
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/tinycolor
npm http GET https://registry.npmjs.org/options
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/tinycolor
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/options
npm http 304 https://registry.npmjs.org/commander

> ws@0.4.31 install C:\Users\Mark\AppData\Roaming\npm\node_modules\karma\node_mo
> dules\socket.io\node_modules\socket.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\Mark\AppData\Roaming\npm\node_modules\karma\node_modules\socket.io\node
_modules\socket.io-client\node_modules\ws>node "C:\Program Files\nodejs\node_mod
ules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild

karma@0.12.1 C:\Users\Mark\AppData\Roaming\npm\node_modules\karma
├── di@0.0.1
├── graceful-fs@2.0.3
├── colors@0.6.2
├── rimraf@2.2.6
├── mime@1.2.11
├── q@0.9.7
├── chokidar@0.8.2 (recursive-readdir@0.0.2)
├── minimatch@0.2.14 (sigmund@1.0.0, lru-cache@2.5.0)
├── glob@3.2.9 (inherits@2.0.1)
├── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.8)
├── source-map@0.1.33 (amdefine@0.1.0)
├── lodash@2.4.1
├── log4js@0.6.12 (semver@1.1.4, readable-stream@1.0.26-2, async@0.1.15)
├── http-proxy@0.10.4 (pkginfo@0.3.0, utile@0.2.1)
├── useragent@2.0.8 (lru-cache@2.2.4)
├── connect@2.12.0 (uid2@0.0.3, methods@0.1.0, pause@0.0.1, cookie-signature@1.0
.1, fresh@0.2.0, qs@0.6.6, debug@0.7.4, bytes@0.2.1, buffer-crc32@0.2.1, batch@0
.5.0, raw-body@1.1.2, cookie@0.1.0, negotiator@0.3.0, send@0.1.4, multiparty@2.2
.0)
└── socket.io@0.9.16 (base64id@0.1.0, policyfile@0.0.4, redis@0.7.3, socket.io-c
lient@0.9.16)

C:\WINDOWS\system32>

The build error is:

gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:101:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:64:11
gyp ERR! stack     at Object.oncomplete (fs.js:107:15)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Mark\AppData\Roaming\npm\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok

**Comment by BorisMoore** [comment]
The install docs here http://karma-runner.github.io/0.12/intro/installation.html still do not indicate to Windows users that Python needs to be installed as a prerequisite. Maybe this issue should be re-opened, or replace by a new documentation issue?

**Comment by fbengrid** [comment]
I've had that issue for a while, but i would say you can safely ignore it (at least i didn't notice any drawback).

The issue is not directly due to karma but to socket.io ( see the following link where someone else is reporting the issue: https://github.com/socketio/socket.io/issues/2185 ).

Because i can't install VC 2013+ on my vista environment (one of these days i'll install this silly win7 waiting on my shelves...) i usually first run the command:
```npm install --ignore-script``` and then a normal ```npm install```

hope that helps.

**Comment by BorisMoore** [comment]
Thanks. But I found that if I didn't install Python then `install karma` failed and `karma-cli` installed but did not work, so I didn't find any way to just ignore the issue. 

So I went ahead and installed Python, and then `install karma` worked. I didn't try `--ignore-script`.

**Comment by Dignifiedquire** [comment]
@BorisMoore the issue is node-gyp needs python to run, which in turn is needed to compile native addons, which in turn is needed for socket.io. So the actual requirement for python come more or less from npm itself, but we could add a section describing this to the docs I agree. Would you like to make a PR for it? :)

**Comment by BorisMoore** [comment]
@Dignifiedquire: Yes, I understand it comes from a chain of dependencies. I think it just needs a comment in the docs that karma has a dependency on node-gyp but that node-gyp will not install unless Python is first installed. Do you know if this this issue only arises on Windows, or is it more general?

**Comment by Dignifiedquire** [comment]
It only happens on Windows, as OS X and most Unix flavors come with Python preinstalled

**Comment by MarkStega** [comment]
I know that this also is not a Karma issue but the build of native socket.io not only needs Python but also defaults to an ancient Visual Studio. Most users will have to perform "npm config set msvs_version 2015 --global" (or 2013 or 2012 or 2010 as few will have the default 2008 installed at this point which is what the script tries to use).

**Comment by GiampaLab** [comment]
The easiest thing to do is to run npm without optional dependencies so that you won't need to install python and a stand alone c++ compiler on each box.

npm install --no-optional
